# frozen_string_literal: true
# AUTO-GENERATED FILE — DO NOT EDIT
# Source: verilog.tokens
# Regenerate with: grammar-tools compile-tokens verilog.tokens
#
# This file embeds a TokenGrammar as native Ruby data structures.
# Downstream packages require this file directly instead of reading
# and parsing the .tokens file at runtime.

require "coding_adventures_grammar_tools"

GT = CodingAdventures::GrammarTools unless defined?(GT)

TOKEN_GRAMMAR = GT::TokenGrammar.new(
  version: 0,
  case_insensitive: false,
  case_sensitive: true,
  definitions: [
      GT::TokenDefinition.new(
        name: "STRING",
        pattern: "\"([^\"\\\\]|\\\\.)*\"",
        is_regex: true,
        line_number: 49,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SIZED_NUMBER",
        pattern: "[0-9]*'[sS]?[bBoOdDhH][0-9a-fA-F_xXzZ]+",
        is_regex: true,
        line_number: 76,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "REAL_NUMBER",
        pattern: "[0-9]+\\.[0-9]+([eE][+-]?[0-9]+)?",
        is_regex: true,
        line_number: 80,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NUMBER",
        pattern: "[0-9][0-9_]*",
        is_regex: true,
        line_number: 84,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SYSTEM_ID",
        pattern: "\\$[a-zA-Z_][a-zA-Z0-9_$]*",
        is_regex: true,
        line_number: 112,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DIRECTIVE",
        pattern: "`[a-zA-Z_][a-zA-Z0-9_]*",
        is_regex: true,
        line_number: 113,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "ESCAPED_IDENT",
        pattern: "\\\\[^ \\t\\r\\n]+",
        is_regex: true,
        line_number: 114,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NAME",
        pattern: "[a-zA-Z_][a-zA-Z0-9_$]*",
        is_regex: true,
        line_number: 117,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "ARITH_LEFT_SHIFT",
        pattern: "<<<",
        is_regex: false,
        line_number: 129,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "ARITH_RIGHT_SHIFT",
        pattern: ">>>",
        is_regex: false,
        line_number: 130,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CASE_EQ",
        pattern: "===",
        is_regex: false,
        line_number: 139,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CASE_NEQ",
        pattern: "!==",
        is_regex: false,
        line_number: 140,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LOGIC_AND",
        pattern: "&&",
        is_regex: false,
        line_number: 148,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LOGIC_OR",
        pattern: "||",
        is_regex: false,
        line_number: 149,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LEFT_SHIFT",
        pattern: "<<",
        is_regex: false,
        line_number: 150,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RIGHT_SHIFT",
        pattern: ">>",
        is_regex: false,
        line_number: 151,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQUALS_EQUALS",
        pattern: "==",
        is_regex: false,
        line_number: 152,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NOT_EQUALS",
        pattern: "!=",
        is_regex: false,
        line_number: 153,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_EQUALS",
        pattern: "<=",
        is_regex: false,
        line_number: 154,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_EQUALS",
        pattern: ">=",
        is_regex: false,
        line_number: 155,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "POWER",
        pattern: "**",
        is_regex: false,
        line_number: 156,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "TRIGGER",
        pattern: "->",
        is_regex: false,
        line_number: 157,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS",
        pattern: "+",
        is_regex: false,
        line_number: 171,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS",
        pattern: "-",
        is_regex: false,
        line_number: 172,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR",
        pattern: "*",
        is_regex: false,
        line_number: 173,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SLASH",
        pattern: "/",
        is_regex: false,
        line_number: 174,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PERCENT",
        pattern: "%",
        is_regex: false,
        line_number: 175,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AMP",
        pattern: "&",
        is_regex: false,
        line_number: 176,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PIPE",
        pattern: "|",
        is_regex: false,
        line_number: 177,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CARET",
        pattern: "^",
        is_regex: false,
        line_number: 178,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "TILDE",
        pattern: "~",
        is_regex: false,
        line_number: 179,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BANG",
        pattern: "!",
        is_regex: false,
        line_number: 180,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_THAN",
        pattern: "<",
        is_regex: false,
        line_number: 181,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_THAN",
        pattern: ">",
        is_regex: false,
        line_number: 182,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQUALS",
        pattern: "=",
        is_regex: false,
        line_number: 183,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "QUESTION",
        pattern: "?",
        is_regex: false,
        line_number: 184,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COLON",
        pattern: ":",
        is_regex: false,
        line_number: 185,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LPAREN",
        pattern: "(",
        is_regex: false,
        line_number: 197,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RPAREN",
        pattern: ")",
        is_regex: false,
        line_number: 198,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACKET",
        pattern: "[",
        is_regex: false,
        line_number: 199,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACKET",
        pattern: "]",
        is_regex: false,
        line_number: 200,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACE",
        pattern: "{",
        is_regex: false,
        line_number: 201,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACE",
        pattern: "}",
        is_regex: false,
        line_number: 202,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SEMICOLON",
        pattern: ";",
        is_regex: false,
        line_number: 203,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COMMA",
        pattern: ",",
        is_regex: false,
        line_number: 204,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DOT",
        pattern: ".",
        is_regex: false,
        line_number: 205,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "HASH",
        pattern: "#",
        is_regex: false,
        line_number: 206,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AT",
        pattern: "@",
        is_regex: false,
        line_number: 207,
        alias_name: nil,
      ),
    ],
  keywords: ["always", "and", "assign", "begin", "buf", "case", "casex", "casez", "default", "defparam", "else", "end", "endcase", "endfunction", "endgenerate", "endmodule", "endtask", "for", "function", "generate", "genvar", "if", "initial", "inout", "input", "integer", "localparam", "module", "nand", "negedge", "nor", "not", "or", "output", "parameter", "posedge", "real", "reg", "signed", "supply0", "supply1", "task", "tri", "unsigned", "wire", "xnor", "xor"],
  mode: nil,
  escape_mode: nil,
  skip_definitions: [
      GT::TokenDefinition.new(
        name: "LINE_COMMENT",
        pattern: "\\/\\/[^\\n]*",
        is_regex: true,
        line_number: 34,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BLOCK_COMMENT",
        pattern: "\\/\\*([^*]|\\*[^/])*\\*\\/",
        is_regex: true,
        line_number: 35,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "WHITESPACE",
        pattern: "[ \\t\\r\\n]+",
        is_regex: true,
        line_number: 36,
        alias_name: nil,
      ),
    ],
  reserved_keywords: [],
  error_definitions: [],
  groups: {},
  layout_keywords: [],
  context_keywords: [],
  soft_keywords: [],
)
