# frozen_string_literal: true
# AUTO-GENERATED FILE — DO NOT EDIT
# Source: haskell1.0.tokens
# Regenerate with: grammar-tools compile-tokens haskell1.0.tokens
#
# This file embeds a TokenGrammar as native Ruby data structures.
# Downstream packages require this file directly instead of reading
# and parsing the .tokens file at runtime.

require "coding_adventures_grammar_tools"

GT = CodingAdventures::GrammarTools unless defined?(GT)

TOKEN_GRAMMAR = GT::TokenGrammar.new(
  version: 1,
  case_insensitive: false,
  case_sensitive: true,
  definitions: [
      GT::TokenDefinition.new(
        name: "FLOAT",
        pattern: "[0-9]+\\.[0-9]+",
        is_regex: true,
        line_number: 29,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "INTEGER",
        pattern: "[0-9]+",
        is_regex: true,
        line_number: 30,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CHARACTER",
        pattern: "'(?:[^'\\\\]|\\\\.)'",
        is_regex: true,
        line_number: 31,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STRING",
        pattern: "\"(?:[^\"\\\\]|\\\\.)*\"",
        is_regex: true,
        line_number: 32,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LAMBDA",
        pattern: "\\\\",
        is_regex: false,
        line_number: 37,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RARROW",
        pattern: "->",
        is_regex: false,
        line_number: 38,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LARROW",
        pattern: "<-",
        is_regex: false,
        line_number: 39,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DARROW",
        pattern: "=>",
        is_regex: false,
        line_number: 40,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DOUBLE_COLON",
        pattern: "::",
        is_regex: false,
        line_number: 41,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DOUBLE_DOT",
        pattern: "..",
        is_regex: false,
        line_number: 42,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQUALS",
        pattern: "=",
        is_regex: false,
        line_number: 43,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQ",
        pattern: "==",
        is_regex: false,
        line_number: 44,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS",
        pattern: "+",
        is_regex: false,
        line_number: 45,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS",
        pattern: "-",
        is_regex: false,
        line_number: 46,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR",
        pattern: "*",
        is_regex: false,
        line_number: 47,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SLASH",
        pattern: "/",
        is_regex: false,
        line_number: 48,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PIPE",
        pattern: "|",
        is_regex: false,
        line_number: 49,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AMPERSAND",
        pattern: "&",
        is_regex: false,
        line_number: 50,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CARET",
        pattern: "^",
        is_regex: false,
        line_number: 51,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "TILDE",
        pattern: "~",
        is_regex: false,
        line_number: 52,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BANG",
        pattern: "!",
        is_regex: false,
        line_number: 53,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESSTHAN",
        pattern: "<",
        is_regex: false,
        line_number: 54,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATERTHAN",
        pattern: ">",
        is_regex: false,
        line_number: 55,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COLON",
        pattern: ":",
        is_regex: false,
        line_number: 56,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COMMA",
        pattern: ",",
        is_regex: false,
        line_number: 57,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SEMICOLON",
        pattern: ";",
        is_regex: false,
        line_number: 58,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DOT",
        pattern: ".",
        is_regex: false,
        line_number: 59,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LPAREN",
        pattern: "(",
        is_regex: false,
        line_number: 60,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RPAREN",
        pattern: ")",
        is_regex: false,
        line_number: 61,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACKET",
        pattern: "[",
        is_regex: false,
        line_number: 62,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACKET",
        pattern: "]",
        is_regex: false,
        line_number: 63,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACE",
        pattern: "{",
        is_regex: false,
        line_number: 64,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACE",
        pattern: "}",
        is_regex: false,
        line_number: 65,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NAME",
        pattern: "[A-Za-z_][A-Za-z0-9_']*",
        is_regex: true,
        line_number: 70,
        alias_name: nil,
      ),
    ],
  keywords: ["as", "case", "class", "data", "do", "else", "foreign", "if", "import", "in", "infix", "infixl", "infixr", "let", "module", "of", "then", "type", "where"],
  mode: "layout",
  escape_mode: nil,
  skip_definitions: [
      GT::TokenDefinition.new(
        name: "LINE_COMMENT",
        pattern: "--[^\\n]*",
        is_regex: true,
        line_number: 22,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BLOCK_COMMENT",
        pattern: "\\{-[\\s\\S]*?\\-\\}",
        is_regex: true,
        line_number: 23,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "WHITESPACE",
        pattern: "[ \\t\\r]+",
        is_regex: true,
        line_number: 24,
        alias_name: nil,
      ),
    ],
  reserved_keywords: [],
  error_definitions: [],
  groups: {},
  layout_keywords: ["let", "where", "do", "of"],
  context_keywords: [],
  soft_keywords: [],
)
