cd ../../../packages/typescript/logic-gates && npm install --quiet
cd ../../../packages/typescript/transistors && npm install --quiet
cd ../../../packages/typescript/ui-components && npm install --quiet
cd ../../../packages/typescript/arithmetic && npm install --quiet
cd ../../../packages/typescript/eniac && npm install --quiet
npm install --quiet
npx vitest run
