cd ../../../packages/typescript/logic-gates && npm install
cd ../../../packages/typescript/transistors && npm install
cd ../../../packages/typescript/arithmetic && npm install
cd ../../../packages/typescript/eniac && npm install
cd ../../../packages/typescript/ui-components && npm install
npm install
npx vitest run
