cd ../../../packages/typescript/transistors && npm install
cd ../logic-gates && npm install
cd ../arithmetic && npm install
cd ../eniac && npm install
cd ../ui-components && npm install
cd ../../../programs/typescript/eniac-visualizer && npm install
npx vitest run
