// GENERATED by code/scripts/generate_scytale_fixture_consumers.py.
// Source SHA-256: efd6c3a85a0c1d0676c31bf709d7c3d7eb5f4aef6b31ac2f904ebad6d76ad02c
// Do not edit by hand.

package com.codingadventures.scytalecipher;

import java.util.List;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class GeneratedClassicalCipherFixtureTest {
    @Test
    void matchesAllNormativeScytaleCases() {
        // classical-ciphers-v1-scytale-worked-encrypt
        assertEquals("HLWLEOODL R ", ScytaleCipher.encrypt("HELLO WORLD", 3));
        // classical-ciphers-v1-scytale-worked-decrypt
        assertEquals("HELLO WORLD", ScytaleCipher.decrypt("HLWLEOODL R ", 3));
        // classical-ciphers-v1-scytale-ragged-decrypt
        assertEquals("ACEFBD", ScytaleCipher.decrypt("ABCDEF", 4));
        // classical-ciphers-v1-scytale-unicode-encrypt
        assertEquals("Aé😀 B ", ScytaleCipher.encrypt("A😀Bé", 3));
        // classical-ciphers-v1-scytale-unicode-decrypt
        assertEquals("A😀Bé", ScytaleCipher.decrypt("Aé😀 B ", 3));
        // classical-ciphers-v1-scytale-combining-scalar-encrypt
        assertEquals("ABe ́ ", ScytaleCipher.encrypt("AéB", 3));
        // classical-ciphers-v1-scytale-combining-scalar-decrypt
        assertEquals("AéB", ScytaleCipher.decrypt("ABe ́ ", 3));
        // classical-ciphers-v1-scytale-genuine-trailing-space-encrypt
        assertEquals("E N D ", ScytaleCipher.encrypt("END ", 3));
        // classical-ciphers-v1-scytale-genuine-trailing-space-loss
        assertEquals("END", ScytaleCipher.decrypt("E N D ", 3));
        // classical-ciphers-v1-scytale-trailing-tab-retained
        assertEquals("AB\t", ScytaleCipher.decrypt("A\tB ", 2));
        // classical-ciphers-v1-scytale-newline-nbsp-retained
        assertEquals("A\t\n ", ScytaleCipher.decrypt("A \t \n ", 3));
        // classical-ciphers-v1-scytale-empty-before-low-key
        assertEquals("", ScytaleCipher.encrypt("", -1));
        // classical-ciphers-v1-scytale-empty-before-high-key
        assertEquals("", ScytaleCipher.decrypt("", 8194));
        // classical-ciphers-v1-scytale-invalid-low-key
        assertThrows(IllegalArgumentException.class, () -> ScytaleCipher.encrypt("A", 1));
        // classical-ciphers-v1-scytale-invalid-high-key
        assertThrows(IllegalArgumentException.class, () -> ScytaleCipher.decrypt("ABC", 4));
        // classical-ciphers-v1-scytale-brute-force-ascending
        var brute = ScytaleCipher.bruteForce("HLWLEOODL R ");
        assertEquals(List.of(2, 3, 4, 5, 6), brute.stream().map(result -> result.key).toList());
        assertEquals(List.of("HOLDWLL ERO", "HELLO WORLD", "HLO LEDRWOL", "HLOLRLED  WO", "HWEOLRLLOD"), brute.stream().map(result -> result.text).toList());
        // classical-ciphers-v1-scytale-brute-force-short
        assertTrue(ScytaleCipher.bruteForce("ABC").isEmpty());
        // classical-ciphers-v1-scytale-brute-force-preflight-limit
        assertThrows(IllegalArgumentException.class, () -> ScytaleCipher.bruteForce("A".repeat(4097)));
    }
}
