defmodule CodingAdventures.HaskellLexer.Grammar.V1_3 do
  # AUTO-GENERATED FILE — DO NOT EDIT
  # Source: haskell1.3.tokens
  # Regenerate with: grammar-tools compile-tokens haskell1.3.tokens
  #
  # This file embeds a TokenGrammar as native Elixir data structures.
  # Call token_grammar/0 instead of reading and parsing the .tokens file.
  
  alias CodingAdventures.GrammarTools.TokenGrammar
  
  def token_grammar do
    %TokenGrammar{
      definitions: [
          %{
            name: "FLOAT",
            pattern: "[0-9]+\\.[0-9]+",
            is_regex: true,
            line_number: 29,
            alias: nil,
          },
          %{
            name: "INTEGER",
            pattern: "[0-9]+",
            is_regex: true,
            line_number: 30,
            alias: nil,
          },
          %{
            name: "CHARACTER",
            pattern: "'(?:[^'\\\\]|\\\\.)'",
            is_regex: true,
            line_number: 31,
            alias: nil,
          },
          %{
            name: "STRING",
            pattern: "\"(?:[^\"\\\\]|\\\\.)*\"",
            is_regex: true,
            line_number: 32,
            alias: nil,
          },
          %{
            name: "LAMBDA",
            pattern: "\\\\",
            is_regex: false,
            line_number: 37,
            alias: nil,
          },
          %{
            name: "RARROW",
            pattern: "->",
            is_regex: false,
            line_number: 38,
            alias: nil,
          },
          %{
            name: "LARROW",
            pattern: "<-",
            is_regex: false,
            line_number: 39,
            alias: nil,
          },
          %{
            name: "DARROW",
            pattern: "=>",
            is_regex: false,
            line_number: 40,
            alias: nil,
          },
          %{
            name: "DOUBLE_COLON",
            pattern: "::",
            is_regex: false,
            line_number: 41,
            alias: nil,
          },
          %{
            name: "DOUBLE_DOT",
            pattern: "..",
            is_regex: false,
            line_number: 42,
            alias: nil,
          },
          %{
            name: "EQUALS",
            pattern: "=",
            is_regex: false,
            line_number: 43,
            alias: nil,
          },
          %{
            name: "EQ",
            pattern: "==",
            is_regex: false,
            line_number: 44,
            alias: nil,
          },
          %{
            name: "PLUS",
            pattern: "+",
            is_regex: false,
            line_number: 45,
            alias: nil,
          },
          %{
            name: "MINUS",
            pattern: "-",
            is_regex: false,
            line_number: 46,
            alias: nil,
          },
          %{
            name: "STAR",
            pattern: "*",
            is_regex: false,
            line_number: 47,
            alias: nil,
          },
          %{
            name: "SLASH",
            pattern: "/",
            is_regex: false,
            line_number: 48,
            alias: nil,
          },
          %{
            name: "PIPE",
            pattern: "|",
            is_regex: false,
            line_number: 49,
            alias: nil,
          },
          %{
            name: "AMPERSAND",
            pattern: "&",
            is_regex: false,
            line_number: 50,
            alias: nil,
          },
          %{
            name: "CARET",
            pattern: "^",
            is_regex: false,
            line_number: 51,
            alias: nil,
          },
          %{
            name: "TILDE",
            pattern: "~",
            is_regex: false,
            line_number: 52,
            alias: nil,
          },
          %{
            name: "BANG",
            pattern: "!",
            is_regex: false,
            line_number: 53,
            alias: nil,
          },
          %{
            name: "LESSTHAN",
            pattern: "<",
            is_regex: false,
            line_number: 54,
            alias: nil,
          },
          %{
            name: "GREATERTHAN",
            pattern: ">",
            is_regex: false,
            line_number: 55,
            alias: nil,
          },
          %{
            name: "COLON",
            pattern: ":",
            is_regex: false,
            line_number: 56,
            alias: nil,
          },
          %{
            name: "COMMA",
            pattern: ",",
            is_regex: false,
            line_number: 57,
            alias: nil,
          },
          %{
            name: "SEMICOLON",
            pattern: ";",
            is_regex: false,
            line_number: 58,
            alias: nil,
          },
          %{
            name: "DOT",
            pattern: ".",
            is_regex: false,
            line_number: 59,
            alias: nil,
          },
          %{
            name: "LPAREN",
            pattern: "(",
            is_regex: false,
            line_number: 60,
            alias: nil,
          },
          %{
            name: "RPAREN",
            pattern: ")",
            is_regex: false,
            line_number: 61,
            alias: nil,
          },
          %{
            name: "LBRACKET",
            pattern: "[",
            is_regex: false,
            line_number: 62,
            alias: nil,
          },
          %{
            name: "RBRACKET",
            pattern: "]",
            is_regex: false,
            line_number: 63,
            alias: nil,
          },
          %{
            name: "LBRACE",
            pattern: "{",
            is_regex: false,
            line_number: 64,
            alias: nil,
          },
          %{
            name: "RBRACE",
            pattern: "}",
            is_regex: false,
            line_number: 65,
            alias: nil,
          },
          %{
            name: "NAME",
            pattern: "[A-Za-z_][A-Za-z0-9_']*",
            is_regex: true,
            line_number: 70,
            alias: nil,
          },
        ],
      keywords: ["as", "case", "class", "data", "do", "else", "foreign", "if", "import", "in", "infix", "infixl", "infixr", "let", "module", "of", "then", "type", "where"],
      mode: "layout",
      escape_mode: nil,
      skip_definitions: [
          %{
            name: "LINE_COMMENT",
            pattern: "--[^\\n]*",
            is_regex: true,
            line_number: 22,
            alias: nil,
          },
          %{
            name: "BLOCK_COMMENT",
            pattern: "\\{-[\\s\\S]*?\\-\\}",
            is_regex: true,
            line_number: 23,
            alias: nil,
          },
          %{
            name: "WHITESPACE",
            pattern: "[ \\t\\r]+",
            is_regex: true,
            line_number: 24,
            alias: nil,
          },
        ],
      reserved_keywords: [],
      error_definitions: [],
      groups: %{},
      layout_keywords: ["let", "where", "do", "of"],
      case_sensitive: true,
      version: 1,
      case_insensitive: false,
      start_mode: nil,
      transitions: [],
    }
  end
  end
