load("code/packages/starlark/program-rules/elixir_binary.star", "elixir_binary")

_targets = [
    elixir_binary(
        name = "unix-tools",
        srcs = ["lib/**/*.ex", "test/**/*.exs"],
        deps = [],
    ),
]
