# AUTO-GENERATED FILE — DO NOT EDIT
# Source: csharp8.0.tokens
# Regenerate with: perl code/programs/perl/grammar-tools/grammar-tools.pl compile-tokens csharp8.0.tokens
#
# This file embeds a TokenGrammar as native Perl data structures.
# Call token_grammar() instead of reading and parsing the .tokens file.

package CodingAdventures::CSharpLexer::_Grammar_8_0;
use strict;
use warnings;

sub token_grammar {
    return bless {
        definitions => [
            bless({
                name => 'NAME',
                pattern => '[a-zA-Z_][a-zA-Z0-9_]*',
                is_regex => 1,
                line_number => 63,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'VERBATIM_NAME',
                pattern => '@[a-zA-Z_][a-zA-Z0-9_]*',
                is_regex => 1,
                line_number => 64,
                alias => 'NAME',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BINARY_ULONG',
                pattern => '0[bB]_?[01][01_]*([uU][lL]|[lL][uU])',
                is_regex => 1,
                line_number => 96,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BINARY_LONG',
                pattern => '0[bB]_?[01][01_]*[lL]',
                is_regex => 1,
                line_number => 97,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BINARY_UINT',
                pattern => '0[bB]_?[01][01_]*[uU]',
                is_regex => 1,
                line_number => 98,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BINARY_NUMBER',
                pattern => '0[bB]_?[01][01_]*',
                is_regex => 1,
                line_number => 99,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'HEX_ULONG',
                pattern => '0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*([uU][lL]|[lL][uU])',
                is_regex => 1,
                line_number => 100,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'HEX_LONG',
                pattern => '0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*[lL]',
                is_regex => 1,
                line_number => 101,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'HEX_UINT',
                pattern => '0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*[uU]',
                is_regex => 1,
                line_number => 102,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'HEX_NUMBER',
                pattern => '0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*',
                is_regex => 1,
                line_number => 103,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'DECIMAL_FLOAT',
                pattern => '[0-9][0-9_]*\\.[0-9_]*([eE][+-]?[0-9][0-9_]*)?[fFdDmM]?',
                is_regex => 1,
                line_number => 104,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEADING_DOT_FLOAT',
                pattern => '\\.[0-9][0-9_]*([eE][+-]?[0-9][0-9_]*)?[fFdDmM]?',
                is_regex => 1,
                line_number => 105,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SCI_NUMBER',
                pattern => '[0-9][0-9_]*[eE][+-]?[0-9][0-9_]*[fFdDmM]?',
                is_regex => 1,
                line_number => 106,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'ULONG_NUMBER',
                pattern => '[0-9][0-9_]*([uU][lL]|[lL][uU])',
                is_regex => 1,
                line_number => 107,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LONG_NUMBER',
                pattern => '[0-9][0-9_]*[lL]',
                is_regex => 1,
                line_number => 108,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'UINT_NUMBER',
                pattern => '[0-9][0-9_]*[uU]',
                is_regex => 1,
                line_number => 109,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOAT_SUFFIX',
                pattern => '[0-9][0-9_]*[fFdDmM]',
                is_regex => 1,
                line_number => 110,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'INT_NUMBER',
                pattern => '[0-9][0-9_]*',
                is_regex => 1,
                line_number => 111,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING',
                pattern => '"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 137,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'VERBATIM_STRING',
                pattern => '@"([^"]|"")*"',
                is_regex => 1,
                line_number => 138,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'INTERPOLATED_STRING',
                pattern => '\\$"([^"\\\\{]|\\\\.|\\{\\{|\\}\\})*"',
                is_regex => 1,
                line_number => 139,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'INTERPOLATED_VERBATIM',
                pattern => '(\\$@|@\\$)"([^"{]|""|\\{\\{|\\}\\})*"',
                is_regex => 1,
                line_number => 140,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'CHAR',
                pattern => '\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 141,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'QUESTION_QUESTION_EQUALS',
                pattern => '??=',
                is_regex => 0,
                line_number => 177,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NULL_CONDITIONAL_DOT',
                pattern => '?.',
                is_regex => 0,
                line_number => 178,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NULL_CONDITIONAL_BRACKET',
                pattern => '?[',
                is_regex => 0,
                line_number => 179,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NULL_COALESCING',
                pattern => '??',
                is_regex => 0,
                line_number => 180,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LAMBDA_ARROW',
                pattern => '=>',
                is_regex => 0,
                line_number => 181,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEFT_SHIFT_EQUALS',
                pattern => '<<=',
                is_regex => 0,
                line_number => 182,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RIGHT_SHIFT_EQUALS',
                pattern => '>>=',
                is_regex => 0,
                line_number => 183,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'DOT_DOT',
                pattern => '..',
                is_regex => 0,
                line_number => 184,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'EQUALS_EQUALS',
                pattern => '==',
                is_regex => 0,
                line_number => 185,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NOT_EQUALS',
                pattern => '!=',
                is_regex => 0,
                line_number => 186,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LESS_EQUALS',
                pattern => '<=',
                is_regex => 0,
                line_number => 187,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'GREATER_EQUALS',
                pattern => '>=',
                is_regex => 0,
                line_number => 188,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AND_AND',
                pattern => '&&',
                is_regex => 0,
                line_number => 189,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'OR_OR',
                pattern => '||',
                is_regex => 0,
                line_number => 190,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS_PLUS',
                pattern => '++',
                is_regex => 0,
                line_number => 191,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS_MINUS',
                pattern => '--',
                is_regex => 0,
                line_number => 192,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS_EQUALS',
                pattern => '+=',
                is_regex => 0,
                line_number => 193,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS_EQUALS',
                pattern => '-=',
                is_regex => 0,
                line_number => 194,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STAR_EQUALS',
                pattern => '*=',
                is_regex => 0,
                line_number => 195,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SLASH_EQUALS',
                pattern => '/=',
                is_regex => 0,
                line_number => 196,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PERCENT_EQUALS',
                pattern => '%=',
                is_regex => 0,
                line_number => 197,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AMPERSAND_EQUALS',
                pattern => '&=',
                is_regex => 0,
                line_number => 198,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PIPE_EQUALS',
                pattern => '|=',
                is_regex => 0,
                line_number => 199,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'CARET_EQUALS',
                pattern => '^=',
                is_regex => 0,
                line_number => 200,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEFT_SHIFT',
                pattern => '<<',
                is_regex => 0,
                line_number => 201,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RIGHT_SHIFT',
                pattern => '>>',
                is_regex => 0,
                line_number => 202,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COLON_COLON',
                pattern => '::',
                is_regex => 0,
                line_number => 203,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'ARROW',
                pattern => '->',
                is_regex => 0,
                line_number => 204,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'EQUALS',
                pattern => '=',
                is_regex => 0,
                line_number => 222,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS',
                pattern => '+',
                is_regex => 0,
                line_number => 223,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS',
                pattern => '-',
                is_regex => 0,
                line_number => 224,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STAR',
                pattern => '*',
                is_regex => 0,
                line_number => 225,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SLASH',
                pattern => '/',
                is_regex => 0,
                line_number => 226,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PERCENT',
                pattern => '%',
                is_regex => 0,
                line_number => 227,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LESS_THAN',
                pattern => '<',
                is_regex => 0,
                line_number => 228,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'GREATER_THAN',
                pattern => '>',
                is_regex => 0,
                line_number => 229,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BANG',
                pattern => '!',
                is_regex => 0,
                line_number => 230,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AMPERSAND',
                pattern => '&',
                is_regex => 0,
                line_number => 231,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PIPE',
                pattern => '|',
                is_regex => 0,
                line_number => 232,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'CARET',
                pattern => '^',
                is_regex => 0,
                line_number => 233,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'TILDE',
                pattern => '~',
                is_regex => 0,
                line_number => 234,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'QUESTION',
                pattern => '?',
                is_regex => 0,
                line_number => 235,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LPAREN',
                pattern => '(',
                is_regex => 0,
                line_number => 243,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RPAREN',
                pattern => ')',
                is_regex => 0,
                line_number => 244,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LBRACE',
                pattern => '{',
                is_regex => 0,
                line_number => 245,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RBRACE',
                pattern => '}',
                is_regex => 0,
                line_number => 246,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LBRACKET',
                pattern => '[',
                is_regex => 0,
                line_number => 247,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RBRACKET',
                pattern => ']',
                is_regex => 0,
                line_number => 248,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SEMICOLON',
                pattern => ';',
                is_regex => 0,
                line_number => 249,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COMMA',
                pattern => ',',
                is_regex => 0,
                line_number => 250,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'DOT',
                pattern => '.',
                is_regex => 0,
                line_number => 251,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COLON',
                pattern => ':',
                is_regex => 0,
                line_number => 252,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PP_NULLABLE',
                pattern => '#\\s*nullable\\b[^\\n]*',
                is_regex => 1,
                line_number => 400,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PP_IF',
                pattern => '#\\s*if\\b[^\\n]*',
                is_regex => 1,
                line_number => 401,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PP_ELIF',
                pattern => '#\\s*elif\\b[^\\n]*',
                is_regex => 1,
                line_number => 402,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PP_ELSE',
                pattern => '#\\s*else\\b[^\\n]*',
                is_regex => 1,
                line_number => 403,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PP_ENDIF',
                pattern => '#\\s*endif\\b[^\\n]*',
                is_regex => 1,
                line_number => 404,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PP_DEFINE',
                pattern => '#\\s*define\\b[^\\n]*',
                is_regex => 1,
                line_number => 405,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PP_UNDEF',
                pattern => '#\\s*undef\\b[^\\n]*',
                is_regex => 1,
                line_number => 406,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PP_REGION',
                pattern => '#\\s*region\\b[^\\n]*',
                is_regex => 1,
                line_number => 407,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PP_ENDREGION',
                pattern => '#\\s*endregion\\b[^\\n]*',
                is_regex => 1,
                line_number => 408,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PP_ERROR',
                pattern => '#\\s*error\\b[^\\n]*',
                is_regex => 1,
                line_number => 409,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PP_WARNING',
                pattern => '#\\s*warning\\b[^\\n]*',
                is_regex => 1,
                line_number => 410,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PP_LINE',
                pattern => '#\\s*line\\b[^\\n]*',
                is_regex => 1,
                line_number => 411,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PP_PRAGMA',
                pattern => '#\\s*pragma\\b[^\\n]*',
                is_regex => 1,
                line_number => 412,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        keywords => [
            'abstract',
            'as',
            'async',
            'await',
            'base',
            'bool',
            'break',
            'byte',
            'case',
            'catch',
            'char',
            'checked',
            'class',
            'const',
            'continue',
            'decimal',
            'default',
            'delegate',
            'do',
            'double',
            'else',
            'enum',
            'event',
            'explicit',
            'extern',
            'false',
            'finally',
            'fixed',
            'float',
            'for',
            'foreach',
            'goto',
            'if',
            'implicit',
            'in',
            'int',
            'interface',
            'internal',
            'is',
            'lock',
            'long',
            'namespace',
            'new',
            'null',
            'object',
            'operator',
            'out',
            'override',
            'params',
            'private',
            'protected',
            'public',
            'readonly',
            'ref',
            'return',
            'sbyte',
            'sealed',
            'short',
            'sizeof',
            'stackalloc',
            'static',
            'string',
            'struct',
            'switch',
            'this',
            'throw',
            'true',
            'try',
            'typeof',
            'uint',
            'ulong',
            'unchecked',
            'unsafe',
            'ushort',
            'using',
            'virtual',
            'void',
            'volatile',
            'while',
        ],
        context_keywords => [],
        layout_keywords => [],
        soft_keywords => [],
        mode => '',
        escape_mode => '',
        skip_definitions => [
            bless({
                name => 'WHITESPACE',
                pattern => '[ \\t\\r\\n\\v\\f]+',
                is_regex => 1,
                line_number => 379,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LINE_COMMENT',
                pattern => '\\/\\/[^\\n]*',
                is_regex => 1,
                line_number => 380,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BLOCK_COMMENT',
                pattern => '\\/\\*([^*]|\\*[^\\/])*\\*\\/',
                is_regex => 1,
                line_number => 381,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        error_definitions => [
            bless({
                name => 'BAD_STRING',
                pattern => '"[^"]*$',
                is_regex => 1,
                line_number => 419,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BAD_CHAR',
                pattern => '\'[^\']*$',
                is_regex => 1,
                line_number => 420,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BAD_VERBATIM_STRING',
                pattern => '@"([^"]|"")*$',
                is_regex => 1,
                line_number => 421,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BAD_INTERPOLATED_STRING',
                pattern => '\\$"([^"\\\\{]|\\\\.)*$',
                is_regex => 1,
                line_number => 422,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        reserved_keywords => [],
        groups => {},
        start_mode => '',
        transitions => [],
    }, 'CodingAdventures::GrammarTools::TokenGrammar';
}

1;
