import type { DuctusEntry } from "../registry.ts";

export const entry: DuctusEntry = [
  "ஐ",
  {
    script: "tamil",
    glyph: "ஐ",
    strokes: [
      {
        segments: [
          {
            label: "spiral out, then down the upright",
            path: [
              { x: 263, y: 467 },
              { x: 322, y: 428 },
              { x: 359, y: 369 },
              { x: 357, y: 299 },
              { x: 315, y: 243 },
              { x: 250, y: 219 },
              { x: 180, y: 227 },
              { x: 125, y: 270 },
              { x: 107, y: 337 },
              { x: 113, y: 407 },
              { x: 153, y: 465 },
              { x: 216, y: 495 },
              { x: 279, y: 526 },
              { x: 349, y: 531 },
              { x: 419, y: 520 },
              { x: 480, y: 485 },
              { x: 525, y: 431 },
              { x: 555, y: 369 },
              { x: 555, y: 298 },
              { x: 555, y: 227 },
            ],
          },
          {
            label: "draw the upright back up",
            path: [
              { x: 555, y: 227 },
              { x: 555, y: 286 },
              { x: 555, y: 345 },
              { x: 551, y: 403 },
            ],
          },
          {
            label: "round the right loop and back left",
            path: [
              { x: 551, y: 403 },
              { x: 592, y: 458 },
              { x: 640, y: 507 },
              { x: 705, y: 527 },
              { x: 774, y: 524 },
              { x: 837, y: 499 },
              { x: 885, y: 449 },
              { x: 909, y: 385 },
              { x: 911, y: 316 },
              { x: 903, y: 248 },
              { x: 870, y: 188 },
              { x: 817, y: 145 },
              { x: 753, y: 120 },
              { x: 685, y: 108 },
              { x: 616, y: 103 },
              { x: 547, y: 101 },
              { x: 479, y: 99 },
              { x: 410, y: 98 },
              { x: 341, y: 95 },
              { x: 273, y: 88 },
              { x: 207, y: 67 },
            ],
          },
          {
            label: "circle the left bowl to the centre",
            path: [
              { x: 207, y: 67 },
              { x: 151, y: 23 },
              { x: 115, y: -37 },
              { x: 111, y: -108 },
              { x: 125, y: -177 },
              { x: 170, y: -231 },
              { x: 231, y: -267 },
              { x: 301, y: -281 },
              { x: 372, y: -281 },
              { x: 441, y: -267 },
              { x: 498, y: -226 },
              { x: 544, y: -171 },
              { x: 559, y: -104 },
              { x: 555, y: -33 },
            ],
          },
          {
            label: "down the stem, round the right bowl",
            path: [
              { x: 555, y: -33 },
              { x: 557, y: -103 },
              { x: 570, y: -171 },
              { x: 613, y: -227 },
              { x: 668, y: -270 },
              { x: 736, y: -281 },
              { x: 806, y: -276 },
              { x: 866, y: -241 },
              { x: 904, y: -182 },
              { x: 911, y: -112 },
              { x: 910, y: -42 },
              { x: 887, y: 23 },
            ],
          },
        ],
      },
    ],
    source: {
      citation:
        "Info-farmer, Writing Tamil 10.gif, ஐ stroke-order animation (Wikimedia Commons, CC BY-SA 3.0, 2008), cross-checked with Sankaran Radhakrishnan, Tamil Script Learners Manual, Appendix I Frame 11 (University of Texas at Austin), p. 194",
      url: "https://commons.wikimedia.org/wiki/File:Writing_Tamil_10.gif",
      variation:
        "Info-farmer's 13-frame animation draws ஐ in five parts in this order: the upper-left spiral, the central upright drawn upward, the upper-right loop returning left across the middle, the lower-left bowl, then the lower-right bowl. The frames sample one movement; they are not evidence of pen lifts. Radhakrishnan's Appendix I Frame 11 independently numbers the same shape as seven movements. Native writers draw ஐ as one continuous stroke, and this ductus follows the five parts in order without lifting. In the bundled Noto Sans Tamil outline the spiral's inner end and the central upright's foot are free ends, so the pen starts inside the spiral and curls outward, runs down the upright to its foot and draws it back up; the lower-left bowl ends at the top of the short centre stem, so the pen comes back down that stem into the lower-right bowl. In HP Labs India's online Tamil handwriting data (the LipiTk 4.0 Tamil isolated-character recognizer, trained on hpl-tamil-iso-char), 99% of the 169 stored prototypes of ஐ are a single pen-down stroke. Tamil handwriting varies by school; this is one attested order fitted to the bundled Noto Sans Tamil outline.",
    },
  },
];
