import type { DuctusEntry } from "../registry.ts";

export const entry: DuctusEntry = [
  "ழ",
  {
    script: "tamil",
    glyph: "ழ",
    strokes: [
      {
        segments: [
          {
            label: "climb the left upright",
            path: [
              { x: 135, y: 47 },
              { x: 131, y: 113 },
              { x: 131, y: 179 },
              { x: 131, y: 246 },
              { x: 131, y: 312 },
              { x: 131, y: 378 },
              { x: 131, y: 445 },
              { x: 131, y: 511 },
            ],
          },
          {
            label: "back down it",
            path: [
              { x: 131, y: 511 },
              { x: 131, y: 445 },
              { x: 131, y: 378 },
              { x: 131, y: 312 },
              { x: 131, y: 246 },
              { x: 131, y: 179 },
              { x: 131, y: 113 },
              { x: 135, y: 47 },
            ],
          },
          {
            label: "along the bar and up the bowl",
            path: [
              { x: 135, y: 47 },
              { x: 204, y: 39 },
              { x: 274, y: 37 },
              { x: 344, y: 35 },
              { x: 414, y: 35 },
              { x: 484, y: 39 },
              { x: 554, y: 39 },
              { x: 623, y: 46 },
              { x: 686, y: 75 },
              { x: 729, y: 130 },
              { x: 747, y: 197 },
              { x: 755, y: 266 },
              { x: 748, y: 336 },
              { x: 734, y: 405 },
              { x: 700, y: 465 },
              { x: 651, y: 515 },
            ],
          },
          {
            label: "left over the top, into the stem",
            path: [
              { x: 651, y: 515 },
              { x: 575, y: 527 },
              { x: 503, y: 506 },
              { x: 455, y: 447 },
            ],
          },
          {
            label: "down the stem",
            path: [
              { x: 455, y: 447 },
              { x: 444, y: 380 },
              { x: 443, y: 313 },
              { x: 443, y: 245 },
              { x: 443, y: 178 },
              { x: 443, y: 110 },
              { x: 443, y: 43 },
              { x: 445, y: -25 },
              { x: 479, y: -81 },
              { x: 527, y: -129 },
            ],
          },
          {
            label: "to the hook's tip and back",
            path: [
              { x: 527, y: -129 },
              { x: 498, y: -195 },
              { x: 447, y: -247 },
              { x: 380, y: -277 },
              { x: 308, y: -285 },
              { x: 235, y: -284 },
              { x: 164, y: -266 },
              { x: 114, y: -214 },
              { x: 119, y: -142 },
              { x: 178, y: -103 },
              { x: 251, y: -97 },
              { x: 182, y: -101 },
              { x: 123, y: -136 },
              { x: 111, y: -202 },
              { x: 152, y: -257 },
              { x: 216, y: -281 },
              { x: 285, y: -286 },
              { x: 355, y: -283 },
              { x: 421, y: -264 },
              { x: 475, y: -221 },
              { x: 515, y: -165 },
              { x: 564, y: -129 },
              { x: 634, y: -129 },
              { x: 703, y: -129 },
            ],
          },
        ],
      },
    ],
    source: {
      citation:
        "Sankaran Radhakrishnan, Tamil Script Learners Manual, Appendix I: Hand-movements, Frame 7, ழ (University of Texas at Austin), p. 193",
      url: "https://sites.la.utexas.edu/tamilscript/files/2009/08/hw_lettersinstructions.pdf",
      variation:
        "Appendix I Frame 7 numbers six movements: 1–3 form the left body and bar, 4–5 the inner upright and broad right bowl, and 6 the lower hook. Native writers draw them as one continuous stroke, and this ductus follows them in order without lifting. The bundled Noto Sans Tamil print face simplifies the source's looped left body and high bar into a retraced upright with a low crossbar that runs straight into the bowl's foot, so movement 3 carries on round the foot and up the bowl's right side, movement 4 comes back left over the top into the inner upright, and movement 5 descends it into the stem below the baseline. The face joins the hook to that stem only at the hook's far end, so movement 6 runs round the hook to its tip and comes back round it into the short tail. In HP Labs India's online Tamil handwriting data (the LipiTk 4.0 Tamil isolated-character recognizer, trained on hpl-tamil-iso-char), 97% of the 182 stored prototypes of ழ are a single pen-down stroke. Tamil handwriting varies by school; this is one attested order.",
    },
  },
];
