"""
sql-codegen — compile LogicalPlan trees into flat IR bytecode.

Pipeline position::

    LogicalPlan (from sql-planner, rewritten by sql-optimizer)
        │  sql_codegen.compile()
        ▼
    Program {
      instructions: tuple[Instruction, ...],
      labels: dict[str,int],
      result_schema: tuple[str,...],
    }
        │  sql-vm (next stage)
        ▼
    QueryResult

The code generator is pure — no I/O, no side effects. It is a simple
recursive post-order traversal that emits a flat instruction stream,
wraps children in loop scaffolding, and runs a single label-resolution
pass at the end.
"""

from __future__ import annotations

from .compiler import compile, compile_expr  # noqa: A004 — shadowing builtin is intentional
from .errors import CodegenError, InternalError, UnsupportedNode
from .ir import (
    CHECK_CURSOR_ID,
    AdvanceCursor,
    AdvanceGroupKey,
    AlterTable,
    BeginRow,
    BeginTransaction,
    Between,
    BinaryOp,
    BinaryOpCode,
    CallScalar,
    CaptureLeftResult,
    CloseScan,
    Coalesce,
    CommitTransaction,
    ComputeWindowFunctions,
    CreateIndex,
    CreateTable,
    CreateTriggerDef,
    DeleteRows,
    Direction,
    DistinctResult,
    DropIndex,
    DropTable,
    DropTriggerDef,
    EmitColumn,
    EmitRow,
    ExceptResult,
    FinalizeAgg,
    Halt,
    InitAgg,
    InList,
    InsertFromResult,
    InsertRow,
    Instruction,
    IntersectResult,
    IsNotNull,
    IsNull,
    JoinBeginRow,
    JoinIfMatched,
    JoinSetMatched,
    Jump,
    JumpIfFalse,
    JumpIfTrue,
    Label,
    Like,
    LimitResult,
    LoadColumn,
    LoadConst,
    LoadGroupKey,
    NullsOrder,
    OpenIndexScan,
    OpenScan,
    OpenWorkingSetScan,
    Pop,
    Program,
    RollbackTransaction,
    RunExistsSubquery,
    RunInSubquery,
    RunRecursiveCTE,
    RunScalarSubquery,
    RunSubquery,
    SaveGroupKey,
    ScanAllColumns,
    SetResultSchema,
    SortKey,
    SortResult,
    SqlValue,
    UnaryOp,
    UnaryOpCode,
    UpdateAgg,
    UpdateRows,
    WinFunc,
    WinFuncSpec,
)
from .ir import (
    AggFunc as IrAggFunc,
)
from .ir import (
    ColumnDef as IrColumnDef,
)

__all__ = [
    "AdvanceCursor",
    "AdvanceGroupKey",
    "AlterTable",
    "BeginRow",
    "BeginTransaction",
    "BinaryOp",
    "BinaryOpCode",
    "Between",
    "CallScalar",
    "CaptureLeftResult",
    "CloseScan",
    "Coalesce",
    "CodegenError",
    "CommitTransaction",
    "CreateIndex",
    "CreateTable",
    "CreateTriggerDef",
    "DeleteRows",
    "Direction",
    "DistinctResult",
    "DropIndex",
    "DropTable",
    "DropTriggerDef",
    "EmitColumn",
    "EmitRow",
    "ExceptResult",
    "FinalizeAgg",
    "Halt",
    "InList",
    "InitAgg",
    "InsertFromResult",
    "InsertRow",
    "Instruction",
    "IntersectResult",
    "InternalError",
    "CHECK_CURSOR_ID",
    "JoinBeginRow",
    "JoinIfMatched",
    "JoinSetMatched",
    "IrAggFunc",
    "IrColumnDef",
    "IsNotNull",
    "IsNull",
    "Jump",
    "JumpIfFalse",
    "JumpIfTrue",
    "Label",
    "Like",
    "LimitResult",
    "LoadColumn",
    "LoadConst",
    "LoadGroupKey",
    "NullsOrder",
    "OpenIndexScan",
    "OpenScan",
    "OpenWorkingSetScan",
    "Pop",
    "Program",
    "RollbackTransaction",
    "RunExistsSubquery",
    "RunInSubquery",
    "RunRecursiveCTE",
    "RunScalarSubquery",
    "RunSubquery",
    "SaveGroupKey",
    "ScanAllColumns",
    "SetResultSchema",
    "SortKey",
    "SortResult",
    "SqlValue",
    "UnaryOp",
    "UnaryOpCode",
    "UnsupportedNode",
    "UpdateAgg",
    "UpdateRows",
    "WinFunc",
    "WinFuncSpec",
    "ComputeWindowFunctions",
    "compile",
    "compile_expr",
]
