# GENERATED by code/scripts/generate_scytale_fixture_consumers.py.
# Source SHA-256: efd6c3a85a0c1d0676c31bf709d7c3d7eb5f4aef6b31ac2f904ebad6d76ad02c
# Do not edit by hand.

defmodule CodingAdventures.GeneratedClassicalCipherFixtureTest do
  use ExUnit.Case, async: true
  alias CodingAdventures.ScytaleCipher

  test "all normative Scytale cases" do
    # classical-ciphers-v1-scytale-worked-encrypt
    assert ScytaleCipher.encrypt(List.to_string([72, 69, 76, 76, 79, 32, 87, 79, 82, 76, 68]), 3) == List.to_string([72, 76, 87, 76, 69, 79, 79, 68, 76, 32, 82, 32])
    # classical-ciphers-v1-scytale-worked-decrypt
    assert ScytaleCipher.decrypt(List.to_string([72, 76, 87, 76, 69, 79, 79, 68, 76, 32, 82, 32]), 3) == List.to_string([72, 69, 76, 76, 79, 32, 87, 79, 82, 76, 68])
    # classical-ciphers-v1-scytale-ragged-decrypt
    assert ScytaleCipher.decrypt(List.to_string([65, 66, 67, 68, 69, 70]), 4) == List.to_string([65, 67, 69, 70, 66, 68])
    # classical-ciphers-v1-scytale-unicode-encrypt
    assert ScytaleCipher.encrypt(List.to_string([65, 128512, 66, 233]), 3) == List.to_string([65, 233, 128512, 32, 66, 32])
    # classical-ciphers-v1-scytale-unicode-decrypt
    assert ScytaleCipher.decrypt(List.to_string([65, 233, 128512, 32, 66, 32]), 3) == List.to_string([65, 128512, 66, 233])
    # classical-ciphers-v1-scytale-combining-scalar-encrypt
    assert ScytaleCipher.encrypt(List.to_string([65, 101, 769, 66]), 3) == List.to_string([65, 66, 101, 32, 769, 32])
    # classical-ciphers-v1-scytale-combining-scalar-decrypt
    assert ScytaleCipher.decrypt(List.to_string([65, 66, 101, 32, 769, 32]), 3) == List.to_string([65, 101, 769, 66])
    # classical-ciphers-v1-scytale-genuine-trailing-space-encrypt
    assert ScytaleCipher.encrypt(List.to_string([69, 78, 68, 32]), 3) == List.to_string([69, 32, 78, 32, 68, 32])
    # classical-ciphers-v1-scytale-genuine-trailing-space-loss
    assert ScytaleCipher.decrypt(List.to_string([69, 32, 78, 32, 68, 32]), 3) == List.to_string([69, 78, 68])
    # classical-ciphers-v1-scytale-trailing-tab-retained
    assert ScytaleCipher.decrypt(List.to_string([65, 9, 66, 32]), 2) == List.to_string([65, 66, 9])
    # classical-ciphers-v1-scytale-newline-nbsp-retained
    assert ScytaleCipher.decrypt(List.to_string([65, 160, 9, 32, 10, 32]), 3) == List.to_string([65, 9, 10, 160])
    # classical-ciphers-v1-scytale-empty-before-low-key
    assert ScytaleCipher.encrypt(List.to_string([]), -1) == List.to_string([])
    # classical-ciphers-v1-scytale-empty-before-high-key
    assert ScytaleCipher.decrypt(List.to_string([]), 8194) == List.to_string([])
    # classical-ciphers-v1-scytale-invalid-low-key
    invalid_error_0 = assert_raise ArgumentError, fn -> ScytaleCipher.encrypt(List.to_string([65]), 1) end
    assert String.starts_with?(Exception.message(invalid_error_0), List.to_string([75, 101, 121, 32, 109, 117, 115, 116]))
    assert List.to_string([115, 99, 121, 116, 97, 108, 101, 45, 105, 110, 118, 97, 108, 105, 100, 45, 107, 101, 121]) == List.to_string([115, 99, 121, 116, 97, 108, 101, 45, 105, 110, 118, 97, 108, 105, 100, 45, 107, 101, 121])
    # classical-ciphers-v1-scytale-invalid-high-key
    invalid_error_1 = assert_raise ArgumentError, fn -> ScytaleCipher.decrypt(List.to_string([65, 66, 67]), 4) end
    assert String.starts_with?(Exception.message(invalid_error_1), List.to_string([75, 101, 121, 32, 109, 117, 115, 116]))
    assert List.to_string([115, 99, 121, 116, 97, 108, 101, 45, 105, 110, 118, 97, 108, 105, 100, 45, 107, 101, 121]) == List.to_string([115, 99, 121, 116, 97, 108, 101, 45, 105, 110, 118, 97, 108, 105, 100, 45, 107, 101, 121])
    # classical-ciphers-v1-scytale-brute-force-ascending
    assert ScytaleCipher.brute_force(List.to_string([72, 76, 87, 76, 69, 79, 79, 68, 76, 32, 82, 32])) == [%{key: 2, text: List.to_string([72, 79, 76, 68, 87, 76, 76, 32, 69, 82, 79])}, %{key: 3, text: List.to_string([72, 69, 76, 76, 79, 32, 87, 79, 82, 76, 68])}, %{key: 4, text: List.to_string([72, 76, 79, 32, 76, 69, 68, 82, 87, 79, 76])}, %{key: 5, text: List.to_string([72, 76, 79, 76, 82, 76, 69, 68, 32, 32, 87, 79])}, %{key: 6, text: List.to_string([72, 87, 69, 79, 76, 82, 76, 76, 79, 68])}]
    # classical-ciphers-v1-scytale-brute-force-short
    assert ScytaleCipher.brute_force(List.to_string([65, 66, 67])) == []
    # classical-ciphers-v1-scytale-brute-force-preflight-limit
    assert_raise ArgumentError, List.to_string([115, 99, 121, 116, 97, 108, 101, 45, 98, 114, 117, 116, 101, 45, 102, 111, 114, 99, 101, 45, 108, 105, 109, 105, 116]), fn ->
      ScytaleCipher.brute_force(String.duplicate(List.to_string([65]), 4097))
    end
  end
end
