load("code/packages/starlark/program-rules/python_binary.star", "py_binary")

_targets = [
    py_binary(
        name = "pipeline-visualizer",
        srcs = ["src/**/*.py", "*.py"],
        deps = [],
    ),
]
