// AUTO-GENERATED FILE - DO NOT EDIT
// Source: java1.4.tokens
// Regenerate with: grammar-tools compile-tokens java1.4.tokens
//
// This file embeds a TokenGrammar as native TypeScript object literals.
// Import it directly instead of reading and parsing the .tokens file at
// runtime.

import type { TokenGrammar } from "@coding-adventures/grammar-tools";

export const TOKEN_GRAMMAR: TokenGrammar = {
  version: 1,
  caseInsensitive: false,
  caseSensitive: true,
  definitions: [
    {
      name: "NAME",
      pattern: "[a-zA-Z_$][a-zA-Z0-9_$]*",
      isRegex: true,
      lineNumber: 71,
    },
    {
      name: "HEX_NUMBER",
      pattern: "0[xX][0-9a-fA-F]+[lL]?",
      isRegex: true,
      lineNumber: 98,
      alias: "NUMBER",
    },
    {
      name: "OCTAL_NUMBER",
      pattern: "0[0-7]+[lL]?",
      isRegex: true,
      lineNumber: 99,
      alias: "NUMBER",
    },
    {
      name: "FLOAT_NUMBER",
      pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?[fFdD]?",
      isRegex: true,
      lineNumber: 100,
      alias: "NUMBER",
    },
    {
      name: "LEADING_DOT_FLOAT",
      pattern: "\\.[0-9]+([eE][+-]?[0-9]+)?[fFdD]?",
      isRegex: true,
      lineNumber: 101,
      alias: "NUMBER",
    },
    {
      name: "SCI_NUMBER",
      pattern: "[0-9]+[eE][+-]?[0-9]+[fFdD]?",
      isRegex: true,
      lineNumber: 102,
      alias: "NUMBER",
    },
    {
      name: "LONG_NUMBER",
      pattern: "[0-9]+[lL]",
      isRegex: true,
      lineNumber: 103,
      alias: "NUMBER",
    },
    {
      name: "FLOAT_SUFFIX",
      pattern: "[0-9]+[fFdD]",
      isRegex: true,
      lineNumber: 104,
      alias: "NUMBER",
    },
    {
      name: "INT_NUMBER",
      pattern: "[0-9]+",
      isRegex: true,
      lineNumber: 105,
      alias: "NUMBER",
    },
    {
      name: "STRING",
      pattern: "\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 135,
    },
    {
      name: "CHAR",
      pattern: "'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 136,
    },
    {
      name: "UNSIGNED_RIGHT_SHIFT_EQUALS",
      pattern: ">>>=",
      isRegex: false,
      lineNumber: 147,
    },
    {
      name: "UNSIGNED_RIGHT_SHIFT",
      pattern: ">>>",
      isRegex: false,
      lineNumber: 148,
    },
    {
      name: "LEFT_SHIFT_EQUALS",
      pattern: "<<=",
      isRegex: false,
      lineNumber: 149,
    },
    {
      name: "RIGHT_SHIFT_EQUALS",
      pattern: ">>=",
      isRegex: false,
      lineNumber: 150,
    },
    {
      name: "EQUALS_EQUALS",
      pattern: "==",
      isRegex: false,
      lineNumber: 151,
    },
    {
      name: "NOT_EQUALS",
      pattern: "!=",
      isRegex: false,
      lineNumber: 152,
    },
    {
      name: "LESS_EQUALS",
      pattern: "<=",
      isRegex: false,
      lineNumber: 153,
    },
    {
      name: "GREATER_EQUALS",
      pattern: ">=",
      isRegex: false,
      lineNumber: 154,
    },
    {
      name: "AND_AND",
      pattern: "&&",
      isRegex: false,
      lineNumber: 155,
    },
    {
      name: "OR_OR",
      pattern: "||",
      isRegex: false,
      lineNumber: 156,
    },
    {
      name: "PLUS_PLUS",
      pattern: "++",
      isRegex: false,
      lineNumber: 157,
    },
    {
      name: "MINUS_MINUS",
      pattern: "--",
      isRegex: false,
      lineNumber: 158,
    },
    {
      name: "PLUS_EQUALS",
      pattern: "+=",
      isRegex: false,
      lineNumber: 159,
    },
    {
      name: "MINUS_EQUALS",
      pattern: "-=",
      isRegex: false,
      lineNumber: 160,
    },
    {
      name: "STAR_EQUALS",
      pattern: "*=",
      isRegex: false,
      lineNumber: 161,
    },
    {
      name: "SLASH_EQUALS",
      pattern: "/=",
      isRegex: false,
      lineNumber: 162,
    },
    {
      name: "PERCENT_EQUALS",
      pattern: "%=",
      isRegex: false,
      lineNumber: 163,
    },
    {
      name: "AMPERSAND_EQUALS",
      pattern: "&=",
      isRegex: false,
      lineNumber: 164,
    },
    {
      name: "PIPE_EQUALS",
      pattern: "|=",
      isRegex: false,
      lineNumber: 165,
    },
    {
      name: "CARET_EQUALS",
      pattern: "^=",
      isRegex: false,
      lineNumber: 166,
    },
    {
      name: "LEFT_SHIFT",
      pattern: "<<",
      isRegex: false,
      lineNumber: 167,
    },
    {
      name: "RIGHT_SHIFT",
      pattern: ">>",
      isRegex: false,
      lineNumber: 168,
    },
    {
      name: "EQUALS",
      pattern: "=",
      isRegex: false,
      lineNumber: 180,
    },
    {
      name: "PLUS",
      pattern: "+",
      isRegex: false,
      lineNumber: 181,
    },
    {
      name: "MINUS",
      pattern: "-",
      isRegex: false,
      lineNumber: 182,
    },
    {
      name: "STAR",
      pattern: "*",
      isRegex: false,
      lineNumber: 183,
    },
    {
      name: "SLASH",
      pattern: "/",
      isRegex: false,
      lineNumber: 184,
    },
    {
      name: "PERCENT",
      pattern: "%",
      isRegex: false,
      lineNumber: 185,
    },
    {
      name: "LESS_THAN",
      pattern: "<",
      isRegex: false,
      lineNumber: 186,
    },
    {
      name: "GREATER_THAN",
      pattern: ">",
      isRegex: false,
      lineNumber: 187,
    },
    {
      name: "BANG",
      pattern: "!",
      isRegex: false,
      lineNumber: 188,
    },
    {
      name: "AMPERSAND",
      pattern: "&",
      isRegex: false,
      lineNumber: 189,
    },
    {
      name: "PIPE",
      pattern: "|",
      isRegex: false,
      lineNumber: 190,
    },
    {
      name: "CARET",
      pattern: "^",
      isRegex: false,
      lineNumber: 191,
    },
    {
      name: "TILDE",
      pattern: "~",
      isRegex: false,
      lineNumber: 192,
    },
    {
      name: "QUESTION",
      pattern: "?",
      isRegex: false,
      lineNumber: 193,
    },
    {
      name: "LPAREN",
      pattern: "(",
      isRegex: false,
      lineNumber: 203,
    },
    {
      name: "RPAREN",
      pattern: ")",
      isRegex: false,
      lineNumber: 204,
    },
    {
      name: "LBRACE",
      pattern: "{",
      isRegex: false,
      lineNumber: 205,
    },
    {
      name: "RBRACE",
      pattern: "}",
      isRegex: false,
      lineNumber: 206,
    },
    {
      name: "LBRACKET",
      pattern: "[",
      isRegex: false,
      lineNumber: 207,
    },
    {
      name: "RBRACKET",
      pattern: "]",
      isRegex: false,
      lineNumber: 208,
    },
    {
      name: "SEMICOLON",
      pattern: ";",
      isRegex: false,
      lineNumber: 209,
    },
    {
      name: "COMMA",
      pattern: ",",
      isRegex: false,
      lineNumber: 210,
    },
    {
      name: "DOT",
      pattern: ".",
      isRegex: false,
      lineNumber: 211,
    },
    {
      name: "COLON",
      pattern: ":",
      isRegex: false,
      lineNumber: 212,
    },
  ],
  keywords: ["abstract","assert","boolean","break","byte","case","catch","char","class","continue","default","do","double","else","extends","final","finally","float","for","if","implements","import","instanceof","int","interface","long","native","new","package","private","protected","public","return","short","static","strictfp","super","switch","synchronized","this","throw","throws","transient","try","void","volatile","while","true","false","null"],
  mode: undefined,
  escapeMode: undefined,
  skipDefinitions: [
    {
      name: "WHITESPACE",
      pattern: "[ \\t\\r\\n\\v\\f]+",
      isRegex: true,
      lineNumber: 342,
    },
    {
      name: "LINE_COMMENT",
      pattern: "\\/\\/[^\\n]*",
      isRegex: true,
      lineNumber: 343,
    },
    {
      name: "BLOCK_COMMENT",
      pattern: "\\/\\*([^*]|\\*[^\\/])*\\*\\/",
      isRegex: true,
      lineNumber: 344,
    },
  ],
  reservedKeywords: ["const","goto"],
  layoutKeywords: [],
  contextKeywords: [],
  errorDefinitions: [],
  groups: {},
  softKeywords: [],
};
