cd ../../../packages/typescript/logic-gates && npm install
cd ../../../packages/typescript/transistors && npm install
cd ../../../packages/typescript/pixel-container && npm install --quiet
cd ../../../packages/typescript/paint-instructions && npm install --quiet
cd ../../../packages/typescript/paint-vm && npm install --quiet
cd ../../../packages/typescript/paint-vm-canvas && npm install --quiet
cd ../../../packages/typescript/ui-components && npm install
npm install
npx vitest run
