load("code/packages/starlark/program-rules/typescript_binary.star", "ts_binary")

_targets = [
    ts_binary(
        name = "logic-gates-visualizer",
        srcs = ["src/**/*.ts", "src/**/*.tsx", "*.ts"],
        deps = [],
    ),
]
