"""AArch64 (ARMv8-A, 2011) behavioral simulator — Layer 07v."""

from .simulator import (
    COND_AL,
    COND_CC,
    COND_CS,
    COND_EQ,
    COND_GE,
    COND_GT,
    COND_HI,
    COND_LE,
    COND_LS,
    COND_LT,
    COND_MI,
    COND_NE,
    COND_PL,
    COND_VC,
    COND_VS,
    HALT,
    AArch64Simulator,
    branch_cond,
    branch_imm,
    branch_reg,
    cbz_cbnz,
    csel_enc,
    dp_imm,
    dp_reg,
    ldst_uoff,
    logic_imm,
    logic_reg,
    madd_msub,
    movwide,
    tbz_tbnz,
)
from .state import (
    MASK32,
    MASK64,
    MEM_SIZE,
    NZCV_C,
    NZCV_N,
    NZCV_V,
    NZCV_Z,
    AArch64State,
    make_initial_state,
)

__all__ = [
    # Simulator and state
    "AArch64Simulator",
    "AArch64State",
    "make_initial_state",
    # Constants
    "HALT",
    "MASK32",
    "MASK64",
    "MEM_SIZE",
    "NZCV_N",
    "NZCV_Z",
    "NZCV_C",
    "NZCV_V",
    # Condition codes
    "COND_EQ",
    "COND_NE",
    "COND_CS",
    "COND_CC",
    "COND_MI",
    "COND_PL",
    "COND_VS",
    "COND_VC",
    "COND_HI",
    "COND_LS",
    "COND_GE",
    "COND_LT",
    "COND_GT",
    "COND_LE",
    "COND_AL",
    # Encoding helpers
    "dp_imm",
    "dp_reg",
    "logic_imm",
    "logic_reg",
    "movwide",
    "ldst_uoff",
    "branch_imm",
    "branch_cond",
    "branch_reg",
    "cbz_cbnz",
    "madd_msub",
    "csel_enc",
    "tbz_tbnz",
]
