cd ../../../packages/typescript/indexeddb && npm install
cd ../../../packages/typescript/store && npm install
cd ../../../packages/typescript/ui-components && npm install
cd ../../../programs/typescript/checklist-app && npm install
npx vitest run
