# AUTO-GENERATED FILE — DO NOT EDIT
# Source: es2015.tokens
# Regenerate with: perl code/programs/perl/grammar-tools/grammar-tools.pl compile-tokens es2015.tokens
#
# This file embeds a TokenGrammar as native Perl data structures.
# Call token_grammar() instead of reading and parsing the .tokens file.

package CodingAdventures::JavascriptLexer::_Grammar_es2015;
use strict;
use warnings;

sub token_grammar {
    return bless {
        definitions => [
            bless({
                name => 'NAME',
                pattern => '[a-zA-Z_$][a-zA-Z0-9_$]*',
                is_regex => 1,
                line_number => 44,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BINARY_NUMBER',
                pattern => '0[bB][01]+',
                is_regex => 1,
                line_number => 49,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'OCTAL_NUMBER',
                pattern => '0[oO][0-7]+',
                is_regex => 1,
                line_number => 50,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'HEX_NUMBER',
                pattern => '0[xX][0-9a-fA-F]+',
                is_regex => 1,
                line_number => 51,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOAT_NUMBER',
                pattern => '[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?',
                is_regex => 1,
                line_number => 52,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEADING_DOT_FLOAT',
                pattern => '\\.[0-9]+([eE][+-]?[0-9]+)?',
                is_regex => 1,
                line_number => 53,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SCI_NUMBER',
                pattern => '[0-9]+[eE][+-]?[0-9]+',
                is_regex => 1,
                line_number => 54,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'INT_NUMBER',
                pattern => '[0-9]+',
                is_regex => 1,
                line_number => 55,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_DQ',
                pattern => '"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 60,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_SQ',
                pattern => '\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 61,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'REGEX',
                pattern => '\\/([^\\/\\\\\\n]|\\\\.)+\\/[gimu]*',
                is_regex => 1,
                line_number => 65,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'TEMPLATE_NO_SUB',
                pattern => '`([^`\\\\$]|\\\\.|\\$[^{])*`',
                is_regex => 1,
                line_number => 73,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'TEMPLATE_HEAD',
                pattern => '`([^`\\\\$]|\\\\.|\\$[^{])*\\$\\{',
                is_regex => 1,
                line_number => 74,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'ARROW',
                pattern => '=>',
                is_regex => 0,
                line_number => 82,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'ELLIPSIS',
                pattern => '...',
                is_regex => 0,
                line_number => 83,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRICT_EQUALS',
                pattern => '===',
                is_regex => 0,
                line_number => 85,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRICT_NOT_EQUALS',
                pattern => '!==',
                is_regex => 0,
                line_number => 86,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'UNSIGNED_RIGHT_SHIFT_EQUALS',
                pattern => '>>>=',
                is_regex => 0,
                line_number => 87,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'UNSIGNED_RIGHT_SHIFT',
                pattern => '>>>',
                is_regex => 0,
                line_number => 88,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEFT_SHIFT_EQUALS',
                pattern => '<<=',
                is_regex => 0,
                line_number => 89,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RIGHT_SHIFT_EQUALS',
                pattern => '>>=',
                is_regex => 0,
                line_number => 90,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'EQUALS_EQUALS',
                pattern => '==',
                is_regex => 0,
                line_number => 91,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NOT_EQUALS',
                pattern => '!=',
                is_regex => 0,
                line_number => 92,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LESS_EQUALS',
                pattern => '<=',
                is_regex => 0,
                line_number => 93,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'GREATER_EQUALS',
                pattern => '>=',
                is_regex => 0,
                line_number => 94,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS_EQUALS',
                pattern => '+=',
                is_regex => 0,
                line_number => 95,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS_EQUALS',
                pattern => '-=',
                is_regex => 0,
                line_number => 96,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STAR_EQUALS',
                pattern => '*=',
                is_regex => 0,
                line_number => 97,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SLASH_EQUALS',
                pattern => '/=',
                is_regex => 0,
                line_number => 98,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PERCENT_EQUALS',
                pattern => '%=',
                is_regex => 0,
                line_number => 99,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AMPERSAND_EQUALS',
                pattern => '&=',
                is_regex => 0,
                line_number => 100,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PIPE_EQUALS',
                pattern => '|=',
                is_regex => 0,
                line_number => 101,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'CARET_EQUALS',
                pattern => '^=',
                is_regex => 0,
                line_number => 102,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEFT_SHIFT',
                pattern => '<<',
                is_regex => 0,
                line_number => 103,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RIGHT_SHIFT',
                pattern => '>>',
                is_regex => 0,
                line_number => 104,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AND_AND',
                pattern => '&&',
                is_regex => 0,
                line_number => 105,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'OR_OR',
                pattern => '||',
                is_regex => 0,
                line_number => 106,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS_PLUS',
                pattern => '++',
                is_regex => 0,
                line_number => 107,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS_MINUS',
                pattern => '--',
                is_regex => 0,
                line_number => 108,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'EQUALS',
                pattern => '=',
                is_regex => 0,
                line_number => 114,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS',
                pattern => '+',
                is_regex => 0,
                line_number => 115,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS',
                pattern => '-',
                is_regex => 0,
                line_number => 116,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STAR',
                pattern => '*',
                is_regex => 0,
                line_number => 117,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SLASH',
                pattern => '/',
                is_regex => 0,
                line_number => 118,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PERCENT',
                pattern => '%',
                is_regex => 0,
                line_number => 119,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LESS_THAN',
                pattern => '<',
                is_regex => 0,
                line_number => 120,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'GREATER_THAN',
                pattern => '>',
                is_regex => 0,
                line_number => 121,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BANG',
                pattern => '!',
                is_regex => 0,
                line_number => 122,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AMPERSAND',
                pattern => '&',
                is_regex => 0,
                line_number => 123,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PIPE',
                pattern => '|',
                is_regex => 0,
                line_number => 124,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'CARET',
                pattern => '^',
                is_regex => 0,
                line_number => 125,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'TILDE',
                pattern => '~',
                is_regex => 0,
                line_number => 126,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'QUESTION',
                pattern => '?',
                is_regex => 0,
                line_number => 127,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LPAREN',
                pattern => '(',
                is_regex => 0,
                line_number => 133,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RPAREN',
                pattern => ')',
                is_regex => 0,
                line_number => 134,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LBRACE',
                pattern => '{',
                is_regex => 0,
                line_number => 135,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RBRACE',
                pattern => '}',
                is_regex => 0,
                line_number => 136,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LBRACKET',
                pattern => '[',
                is_regex => 0,
                line_number => 137,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RBRACKET',
                pattern => ']',
                is_regex => 0,
                line_number => 138,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SEMICOLON',
                pattern => ';',
                is_regex => 0,
                line_number => 139,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COMMA',
                pattern => ',',
                is_regex => 0,
                line_number => 140,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COLON',
                pattern => ':',
                is_regex => 0,
                line_number => 141,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'DOT',
                pattern => '.',
                is_regex => 0,
                line_number => 142,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        keywords => [
            'break',
            'case',
            'catch',
            'class',
            'const',
            'continue',
            'debugger',
            'default',
            'delete',
            'do',
            'else',
            'export',
            'extends',
            'finally',
            'for',
            'function',
            'if',
            'import',
            'in',
            'instanceof',
            'let',
            'new',
            'return',
            'super',
            'switch',
            'this',
            'throw',
            'try',
            'typeof',
            'var',
            'void',
            'while',
            'with',
            'yield',
            'true',
            'false',
            'null',
        ],
        context_keywords => [
            'as',
            'from',
            'of',
            'get',
            'set',
            'static',
        ],
        layout_keywords => [],
        soft_keywords => [],
        mode => '',
        escape_mode => '',
        skip_definitions => [
            bless({
                name => 'WHITESPACE',
                pattern => '[ \\t\\r\\n\\v\\f]+',
                is_regex => 1,
                line_number => 232,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LINE_COMMENT',
                pattern => '\\/\\/[^\\n]*',
                is_regex => 1,
                line_number => 233,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BLOCK_COMMENT',
                pattern => '\\/\\*([^*]|\\*[^\\/])*\\*\\/',
                is_regex => 1,
                line_number => 234,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        error_definitions => [
            bless({
                name => 'BAD_STRING_DQ',
                pattern => '"[^"]*$',
                is_regex => 1,
                line_number => 241,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BAD_STRING_SQ',
                pattern => '\'[^\']*$',
                is_regex => 1,
                line_number => 242,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BAD_REGEX',
                pattern => '\\/([^\\/\\\\\\n]|\\\\.)*$',
                is_regex => 1,
                line_number => 243,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BAD_TEMPLATE',
                pattern => '`([^`\\\\$]|\\\\.|\\$[^{])*$',
                is_regex => 1,
                line_number => 244,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        reserved_keywords => [
            'enum',
        ],
        groups => {
            'template' => bless({
                name => 'template',
                definitions => [
                        bless({
                            name => 'TEMPLATE_MIDDLE',
                            pattern => '\\}([^`\\\\$]|\\\\.|\\$[^{])*\\$\\{',
                            is_regex => 1,
                            line_number => 224,
                            alias => '',
                        }, 'CodingAdventures::GrammarTools::TokenDefinition'),
                        bless({
                            name => 'TEMPLATE_TAIL',
                            pattern => '\\}([^`\\\\$]|\\\\.|\\$[^{])*`',
                            is_regex => 1,
                            line_number => 225,
                            alias => '',
                        }, 'CodingAdventures::GrammarTools::TokenDefinition'),
                    ],
            }, 'CodingAdventures::GrammarTools::PatternGroup'),
        },
        start_mode => '',
        transitions => [],
    }, 'CodingAdventures::GrammarTools::TokenGrammar';
}

1;
