# AUTO-GENERATED FILE — DO NOT EDIT
# Source: es2020.tokens
# Regenerate with: perl code/programs/perl/grammar-tools/grammar-tools.pl compile-tokens es2020.tokens
#
# This file embeds a TokenGrammar as native Perl data structures.
# Call token_grammar() instead of reading and parsing the .tokens file.

package CodingAdventures::JavascriptLexer::_Grammar_es2020;
use strict;
use warnings;

sub token_grammar {
    return bless {
        definitions => [
            bless({
                name => 'NAME',
                pattern => '[a-zA-Z_$][a-zA-Z0-9_$]*',
                is_regex => 1,
                line_number => 44,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BIGINT_HEX',
                pattern => '0[xX][0-9a-fA-F]+n',
                is_regex => 1,
                line_number => 57,
                alias => 'BIGINT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BIGINT_BINARY',
                pattern => '0[bB][01]+n',
                is_regex => 1,
                line_number => 58,
                alias => 'BIGINT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BIGINT_OCTAL',
                pattern => '0[oO][0-7]+n',
                is_regex => 1,
                line_number => 59,
                alias => 'BIGINT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BIGINT_DECIMAL',
                pattern => '[0-9]+n',
                is_regex => 1,
                line_number => 60,
                alias => 'BIGINT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BINARY_NUMBER',
                pattern => '0[bB][01]+',
                is_regex => 1,
                line_number => 64,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'OCTAL_NUMBER',
                pattern => '0[oO][0-7]+',
                is_regex => 1,
                line_number => 65,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'HEX_NUMBER',
                pattern => '0[xX][0-9a-fA-F]+',
                is_regex => 1,
                line_number => 66,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOAT_NUMBER',
                pattern => '[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?',
                is_regex => 1,
                line_number => 67,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEADING_DOT_FLOAT',
                pattern => '\\.[0-9]+([eE][+-]?[0-9]+)?',
                is_regex => 1,
                line_number => 68,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SCI_NUMBER',
                pattern => '[0-9]+[eE][+-]?[0-9]+',
                is_regex => 1,
                line_number => 69,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'INT_NUMBER',
                pattern => '[0-9]+',
                is_regex => 1,
                line_number => 70,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_DQ',
                pattern => '"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 74,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_SQ',
                pattern => '\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 75,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'TEMPLATE_HEAD',
                pattern => '`([^`\\\\$]|\\\\.|\\$[^{])*\\$\\{',
                is_regex => 1,
                line_number => 79,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'TEMPLATE_NO_SUB',
                pattern => '`([^`\\\\$]|\\\\.|\\$[^{])*`',
                is_regex => 1,
                line_number => 80,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'REGEX',
                pattern => '\\/([^\\/\\\\\\n]|\\\\.)+\\/[gimsuy]*',
                is_regex => 1,
                line_number => 84,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'OPTIONAL_CHAIN',
                pattern => '?.',
                is_regex => 0,
                line_number => 99,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NULLISH_COALESCE',
                pattern => '??',
                is_regex => 0,
                line_number => 100,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STAR_STAR_EQUALS',
                pattern => '**=',
                is_regex => 0,
                line_number => 104,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STAR_STAR',
                pattern => '**',
                is_regex => 0,
                line_number => 105,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRICT_EQUALS',
                pattern => '===',
                is_regex => 0,
                line_number => 106,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRICT_NOT_EQUALS',
                pattern => '!==',
                is_regex => 0,
                line_number => 107,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'UNSIGNED_RIGHT_SHIFT_EQUALS',
                pattern => '>>>=',
                is_regex => 0,
                line_number => 108,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'UNSIGNED_RIGHT_SHIFT',
                pattern => '>>>',
                is_regex => 0,
                line_number => 109,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEFT_SHIFT_EQUALS',
                pattern => '<<=',
                is_regex => 0,
                line_number => 110,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RIGHT_SHIFT_EQUALS',
                pattern => '>>=',
                is_regex => 0,
                line_number => 111,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'EQUALS_EQUALS',
                pattern => '==',
                is_regex => 0,
                line_number => 112,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NOT_EQUALS',
                pattern => '!=',
                is_regex => 0,
                line_number => 113,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LESS_EQUALS',
                pattern => '<=',
                is_regex => 0,
                line_number => 114,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'GREATER_EQUALS',
                pattern => '>=',
                is_regex => 0,
                line_number => 115,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS_EQUALS',
                pattern => '+=',
                is_regex => 0,
                line_number => 116,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS_EQUALS',
                pattern => '-=',
                is_regex => 0,
                line_number => 117,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STAR_EQUALS',
                pattern => '*=',
                is_regex => 0,
                line_number => 118,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SLASH_EQUALS',
                pattern => '/=',
                is_regex => 0,
                line_number => 119,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PERCENT_EQUALS',
                pattern => '%=',
                is_regex => 0,
                line_number => 120,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AMPERSAND_EQUALS',
                pattern => '&=',
                is_regex => 0,
                line_number => 121,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PIPE_EQUALS',
                pattern => '|=',
                is_regex => 0,
                line_number => 122,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'CARET_EQUALS',
                pattern => '^=',
                is_regex => 0,
                line_number => 123,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEFT_SHIFT',
                pattern => '<<',
                is_regex => 0,
                line_number => 124,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RIGHT_SHIFT',
                pattern => '>>',
                is_regex => 0,
                line_number => 125,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AND_AND',
                pattern => '&&',
                is_regex => 0,
                line_number => 126,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'OR_OR',
                pattern => '||',
                is_regex => 0,
                line_number => 127,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS_PLUS',
                pattern => '++',
                is_regex => 0,
                line_number => 128,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS_MINUS',
                pattern => '--',
                is_regex => 0,
                line_number => 129,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'ARROW',
                pattern => '=>',
                is_regex => 0,
                line_number => 130,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'ELLIPSIS',
                pattern => '...',
                is_regex => 0,
                line_number => 131,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'EQUALS',
                pattern => '=',
                is_regex => 0,
                line_number => 137,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS',
                pattern => '+',
                is_regex => 0,
                line_number => 138,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS',
                pattern => '-',
                is_regex => 0,
                line_number => 139,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STAR',
                pattern => '*',
                is_regex => 0,
                line_number => 140,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SLASH',
                pattern => '/',
                is_regex => 0,
                line_number => 141,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PERCENT',
                pattern => '%',
                is_regex => 0,
                line_number => 142,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LESS_THAN',
                pattern => '<',
                is_regex => 0,
                line_number => 143,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'GREATER_THAN',
                pattern => '>',
                is_regex => 0,
                line_number => 144,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BANG',
                pattern => '!',
                is_regex => 0,
                line_number => 145,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AMPERSAND',
                pattern => '&',
                is_regex => 0,
                line_number => 146,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PIPE',
                pattern => '|',
                is_regex => 0,
                line_number => 147,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'CARET',
                pattern => '^',
                is_regex => 0,
                line_number => 148,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'TILDE',
                pattern => '~',
                is_regex => 0,
                line_number => 149,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'QUESTION',
                pattern => '?',
                is_regex => 0,
                line_number => 150,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LPAREN',
                pattern => '(',
                is_regex => 0,
                line_number => 156,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RPAREN',
                pattern => ')',
                is_regex => 0,
                line_number => 157,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LBRACE',
                pattern => '{',
                is_regex => 0,
                line_number => 158,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RBRACE',
                pattern => '}',
                is_regex => 0,
                line_number => 159,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LBRACKET',
                pattern => '[',
                is_regex => 0,
                line_number => 160,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RBRACKET',
                pattern => ']',
                is_regex => 0,
                line_number => 161,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SEMICOLON',
                pattern => ';',
                is_regex => 0,
                line_number => 162,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COMMA',
                pattern => ',',
                is_regex => 0,
                line_number => 163,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COLON',
                pattern => ':',
                is_regex => 0,
                line_number => 164,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'DOT',
                pattern => '.',
                is_regex => 0,
                line_number => 165,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        keywords => [
            'break',
            'case',
            'catch',
            'class',
            'const',
            'continue',
            'debugger',
            'default',
            'delete',
            'do',
            'else',
            'export',
            'extends',
            'finally',
            'for',
            'function',
            'if',
            'import',
            'in',
            'instanceof',
            'let',
            'new',
            'return',
            'super',
            'switch',
            'this',
            'throw',
            'try',
            'typeof',
            'var',
            'void',
            'while',
            'with',
            'yield',
            'true',
            'false',
            'null',
        ],
        context_keywords => [
            'as',
            'async',
            'await',
            'from',
            'of',
            'get',
            'set',
            'static',
        ],
        layout_keywords => [],
        soft_keywords => [],
        mode => '',
        escape_mode => '',
        skip_definitions => [
            bless({
                name => 'WHITESPACE',
                pattern => '[ \\t\\r\\n\\v\\f]+',
                is_regex => 1,
                line_number => 244,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LINE_COMMENT',
                pattern => '\\/\\/[^\\n]*',
                is_regex => 1,
                line_number => 245,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BLOCK_COMMENT',
                pattern => '\\/\\*([^*]|\\*[^\\/])*\\*\\/',
                is_regex => 1,
                line_number => 246,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        error_definitions => [
            bless({
                name => 'BAD_STRING_DQ',
                pattern => '"[^"]*$',
                is_regex => 1,
                line_number => 253,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BAD_STRING_SQ',
                pattern => '\'[^\']*$',
                is_regex => 1,
                line_number => 254,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BAD_REGEX',
                pattern => '\\/([^\\/\\\\\\n]|\\\\.)*$',
                is_regex => 1,
                line_number => 255,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BAD_TEMPLATE',
                pattern => '`([^`\\\\$]|\\\\.|\\$[^{])*$',
                is_regex => 1,
                line_number => 256,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        reserved_keywords => [
            'enum',
        ],
        groups => {
            'template' => bless({
                name => 'template',
                definitions => [
                        bless({
                            name => 'TEMPLATE_MIDDLE',
                            pattern => '\\}([^`\\\\$]|\\\\.|\\$[^{])*\\$\\{',
                            is_regex => 1,
                            line_number => 236,
                            alias => '',
                        }, 'CodingAdventures::GrammarTools::TokenDefinition'),
                        bless({
                            name => 'TEMPLATE_TAIL',
                            pattern => '\\}([^`\\\\$]|\\\\.|\\$[^{])*`',
                            is_regex => 1,
                            line_number => 237,
                            alias => '',
                        }, 'CodingAdventures::GrammarTools::TokenDefinition'),
                    ],
            }, 'CodingAdventures::GrammarTools::PatternGroup'),
        },
        start_mode => '',
        transitions => [],
    }, 'CodingAdventures::GrammarTools::TokenGrammar';
}

1;
