(cd ../../../packages/typescript/directed-graph && npm install --silent)
(cd ../../../packages/typescript/state-machine && npm install --silent)
(cd ../../../packages/typescript/cli-builder && npm install --silent)
npm install --silent
./node_modules/.bin/vitest run --coverage
