-- Tests for coding_adventures.document_ast
-- ==========================================
--
-- Tests that all node constructors create tables with the correct structure,
-- and that type predicates work correctly.

package.path = "../src/?.lua;../src/?/init.lua;" .. package.path

local ast = require("coding_adventures.document_ast")

describe("document_ast", function()

  -- ─── Block node constructors ──────────────────────────────────────────────

  describe("document()", function()
    it("creates a document node with empty children by default", function()
      local node = ast.document()
      assert.equals("document", node.type)
      assert.same({}, node.children)
    end)

    it("creates a document node with provided children", function()
      local children = { ast.paragraph({ ast.text("hello") }) }
      local node = ast.document(children)
      assert.equals("document", node.type)
      assert.equals(1, #node.children)
      assert.equals("paragraph", node.children[1].type)
    end)
  end)

  describe("heading()", function()
    it("creates a heading node with level and children", function()
      local node = ast.heading(2, { ast.text("Title") })
      assert.equals("heading", node.type)
      assert.equals(2, node.level)
      assert.equals(1, #node.children)
      assert.equals("text", node.children[1].type)
      assert.equals("Title", node.children[1].value)
    end)

    it("accepts levels 1-6", function()
      for level = 1, 6 do
        local node = ast.heading(level, {})
        assert.equals(level, node.level)
      end
    end)
  end)

  describe("paragraph()", function()
    it("creates a paragraph node with children", function()
      local node = ast.paragraph({ ast.text("Hello") })
      assert.equals("paragraph", node.type)
      assert.equals(1, #node.children)
    end)

    it("creates a paragraph with empty children by default", function()
      local node = ast.paragraph()
      assert.equals("paragraph", node.type)
      assert.same({}, node.children)
    end)
  end)

  describe("code_block()", function()
    it("creates a code block with language and value", function()
      local node = ast.code_block("lua", "local x = 1\n")
      assert.equals("code_block", node.type)
      assert.equals("lua", node.language)
      assert.equals("local x = 1\n", node.value)
    end)

    it("creates a code block with nil language", function()
      local node = ast.code_block(nil, "code\n")
      assert.equals("code_block", node.type)
      assert.is_nil(node.language)
    end)
  end)

  describe("blockquote()", function()
    it("creates a blockquote with children", function()
      local node = ast.blockquote({ ast.paragraph({}) })
      assert.equals("blockquote", node.type)
      assert.equals(1, #node.children)
    end)
  end)

  describe("list()", function()
    it("creates an unordered list", function()
      local item = ast.list_item({ ast.paragraph({ ast.text("item") }) })
      local node = ast.list(false, nil, true, { item })
      assert.equals("list", node.type)
      assert.is_false(node.ordered)
      assert.is_nil(node.start)
      assert.is_true(node.tight)
      assert.equals(1, #node.children)
    end)

    it("creates an ordered list with a start number", function()
      local node = ast.list(true, 3, false, {})
      assert.equals("list", node.type)
      assert.is_true(node.ordered)
      assert.equals(3, node.start)
      assert.is_false(node.tight)
    end)
  end)

  describe("list_item()", function()
    it("creates a list item with children", function()
      local node = ast.list_item({ ast.paragraph({}) })
      assert.equals("list_item", node.type)
      assert.equals(1, #node.children)
    end)
  end)

  describe("task_item()", function()
    it("creates a task item with children", function()
      local node = ast.task_item(true, { ast.paragraph({}) })
      assert.equals("task_item", node.type)
      assert.is_true(node.checked)
      assert.equals(1, #node.children)
    end)
  end)

  describe("thematic_break()", function()
    it("creates a thematic break leaf node", function()
      local node = ast.thematic_break()
      assert.equals("thematic_break", node.type)
    end)
  end)

  describe("raw_block()", function()
    it("creates a raw block with format and value", function()
      local node = ast.raw_block("html", "<div>test</div>\n")
      assert.equals("raw_block", node.type)
      assert.equals("html", node.format)
      assert.equals("<div>test</div>\n", node.value)
    end)
  end)

  describe("table nodes", function()
    it("creates table, row, and cell nodes", function()
      local cell = ast.table_cell({ ast.text("A") })
      local row = ast.table_row(true, { cell })
      local node = ast.table({ "left" }, { row })
      assert.equals("table", node.type)
      assert.equals("table_row", node.children[1].type)
      assert.equals("table_cell", node.children[1].children[1].type)
    end)
  end)

  -- ─── Inline node constructors ─────────────────────────────────────────────

  describe("text()", function()
    it("creates a text node", function()
      local node = ast.text("Hello, world!")
      assert.equals("text", node.type)
      assert.equals("Hello, world!", node.value)
    end)

    it("creates an empty text node by default", function()
      local node = ast.text()
      assert.equals("", node.value)
    end)
  end)

  describe("emphasis()", function()
    it("creates an emphasis node", function()
      local node = ast.emphasis({ ast.text("hi") })
      assert.equals("emphasis", node.type)
      assert.equals(1, #node.children)
    end)
  end)

  describe("strong()", function()
    it("creates a strong node", function()
      local node = ast.strong({ ast.text("bold") })
      assert.equals("strong", node.type)
      assert.equals(1, #node.children)
    end)
  end)

  describe("strikethrough()", function()
    it("creates a strikethrough node", function()
      local node = ast.strikethrough({ ast.text("gone") })
      assert.equals("strikethrough", node.type)
      assert.equals(1, #node.children)
    end)
  end)

  describe("code_span()", function()
    it("creates a code span node", function()
      local node = ast.code_span("const x = 1")
      assert.equals("code_span", node.type)
      assert.equals("const x = 1", node.value)
    end)
  end)

  describe("link()", function()
    it("creates a link node", function()
      local node = ast.link("https://example.com", "Example", { ast.text("click") })
      assert.equals("link", node.type)
      assert.equals("https://example.com", node.destination)
      assert.equals("Example", node.title)
      assert.equals(1, #node.children)
    end)

    it("creates a link with nil title", function()
      local node = ast.link("https://example.com", nil, {})
      assert.is_nil(node.title)
    end)
  end)

  describe("image()", function()
    it("creates an image node", function()
      local node = ast.image("cat.png", nil, "a cat")
      assert.equals("image", node.type)
      assert.equals("cat.png", node.destination)
      assert.is_nil(node.title)
      assert.equals("a cat", node.alt)
    end)
  end)

  describe("autolink()", function()
    it("creates a URL autolink", function()
      local node = ast.autolink("https://example.com", false)
      assert.equals("autolink", node.type)
      assert.equals("https://example.com", node.destination)
      assert.is_false(node.is_email)
    end)

    it("creates an email autolink", function()
      local node = ast.autolink("user@example.com", true)
      assert.equals("autolink", node.type)
      assert.is_true(node.is_email)
    end)
  end)

  describe("raw_inline()", function()
    it("creates a raw inline node", function()
      local node = ast.raw_inline("html", "<em>hi</em>")
      assert.equals("raw_inline", node.type)
      assert.equals("html", node.format)
      assert.equals("<em>hi</em>", node.value)
    end)
  end)

  describe("hard_break()", function()
    it("creates a hard break node", function()
      local node = ast.hard_break()
      assert.equals("hard_break", node.type)
    end)
  end)

  describe("soft_break()", function()
    it("creates a soft break node", function()
      local node = ast.soft_break()
      assert.equals("soft_break", node.type)
    end)
  end)

  -- ─── Type predicates ──────────────────────────────────────────────────────

  describe("is_block()", function()
    it("returns true for block nodes", function()
      assert.is_true(ast.is_block(ast.document()))
      assert.is_true(ast.is_block(ast.heading(1, {})))
      assert.is_true(ast.is_block(ast.paragraph()))
      assert.is_true(ast.is_block(ast.code_block(nil, "")))
      assert.is_true(ast.is_block(ast.blockquote()))
      assert.is_true(ast.is_block(ast.list(false, nil, true, {})))
      assert.is_true(ast.is_block(ast.list_item()))
      assert.is_true(ast.is_block(ast.task_item(false, {})))
      assert.is_true(ast.is_block(ast.thematic_break()))
      assert.is_true(ast.is_block(ast.raw_block("html", "")))
      assert.is_true(ast.is_block(ast.table({}, {})))
      assert.is_true(ast.is_block(ast.table_row(false, {})))
      assert.is_true(ast.is_block(ast.table_cell({})))
    end)

    it("returns false for inline nodes", function()
      assert.is_false(ast.is_block(ast.text("hi")))
      assert.is_false(ast.is_block(ast.emphasis({})))
      assert.is_false(ast.is_block(ast.hard_break()))
    end)

    it("returns false for nil", function()
      assert.is_false(ast.is_block(nil))
    end)
  end)

  describe("is_inline()", function()
    it("returns true for inline nodes", function()
      assert.is_true(ast.is_inline(ast.text("hi")))
      assert.is_true(ast.is_inline(ast.emphasis({})))
      assert.is_true(ast.is_inline(ast.strong({})))
      assert.is_true(ast.is_inline(ast.strikethrough({})))
      assert.is_true(ast.is_inline(ast.code_span("x")))
      assert.is_true(ast.is_inline(ast.link("", nil, {})))
      assert.is_true(ast.is_inline(ast.image("", nil, "")))
      assert.is_true(ast.is_inline(ast.autolink("", false)))
      assert.is_true(ast.is_inline(ast.raw_inline("html", "")))
      assert.is_true(ast.is_inline(ast.hard_break()))
      assert.is_true(ast.is_inline(ast.soft_break()))
    end)

    it("returns false for block nodes", function()
      assert.is_false(ast.is_inline(ast.paragraph()))
      assert.is_false(ast.is_inline(ast.heading(1, {})))
    end)

    it("returns false for nil", function()
      assert.is_false(ast.is_inline(nil))
    end)
  end)

end)
