(cd ../../../packages/typescript/matrix && npm ci --quiet)
(cd ../../../packages/typescript/multi-directed-graph && npm ci --quiet)
(cd ../../../packages/typescript/neural-graph-vm && npm ci --quiet)
(cd ../../../packages/typescript/neural-network && npm ci --quiet)
(cd ../../../packages/typescript/single-layer-network && npm ci --quiet)
(cd ../../../packages/typescript/two-layer-network && npm ci --quiet)
npm ci --quiet
npx vitest run
