defmodule CodingAdventures.FSharpLexer.Grammar.V4_5 do
  # AUTO-GENERATED FILE — DO NOT EDIT
  # Source: fsharp4.5.tokens
  # Regenerate with: grammar-tools compile-tokens fsharp4.5.tokens
  #
  # This file embeds a TokenGrammar as native Elixir data structures.
  # Call token_grammar/0 instead of reading and parsing the .tokens file.
  
  alias CodingAdventures.GrammarTools.TokenGrammar
  
  def token_grammar do
    %TokenGrammar{
      definitions: [
          %{
            name: "UNDERSCORE",
            pattern: "_",
            is_regex: false,
            line_number: 13,
            alias: nil,
          },
          %{
            name: "CHAR",
            pattern: "'([^'\\\\]|\\\\.)'",
            is_regex: true,
            line_number: 14,
            alias: nil,
          },
          %{
            name: "TYPEVAR",
            pattern: "'[a-zA-Z_][a-zA-Z0-9_']*",
            is_regex: true,
            line_number: 15,
            alias: nil,
          },
          %{
            name: "NAME",
            pattern: "[a-zA-Z_][a-zA-Z0-9_']*",
            is_regex: true,
            line_number: 16,
            alias: nil,
          },
          %{
            name: "LEADING_DOT_FLOAT",
            pattern: "\\.[0-9][0-9_]*([eE][+-]?[0-9][0-9_]*)?[fFdDmM]?",
            is_regex: true,
            line_number: 18,
            alias: "NUMBER",
          },
          %{
            name: "FLOAT_NUMBER",
            pattern: "[0-9][0-9_]*\\.[0-9][0-9_]*([eE][+-]?[0-9][0-9_]*)?[fFdDmM]?",
            is_regex: true,
            line_number: 19,
            alias: "NUMBER",
          },
          %{
            name: "SCI_NUMBER",
            pattern: "[0-9][0-9_]*[eE][+-]?[0-9][0-9_]*[fFdDmM]?",
            is_regex: true,
            line_number: 20,
            alias: "NUMBER",
          },
          %{
            name: "HEX_NUMBER",
            pattern: "0[xX][0-9a-fA-F][0-9a-fA-F_]*([uU][lL]?|[lL][uU]?|[yY]|[sS]|[nN]|[iI]|[mM]|[fF])?",
            is_regex: true,
            line_number: 21,
            alias: "NUMBER",
          },
          %{
            name: "BINARY_NUMBER",
            pattern: "0[bB][01][01_]*([uU][lL]?|[lL][uU]?|[yY]|[sS]|[nN]|[iI]|[mM]|[fF])?",
            is_regex: true,
            line_number: 22,
            alias: "NUMBER",
          },
          %{
            name: "INT_NUMBER",
            pattern: "[0-9][0-9_]*([uU][lL]?|[lL][uU]?|[yY]|[sS]|[nN]|[iI]|[mM]|[fF])?",
            is_regex: true,
            line_number: 23,
            alias: "NUMBER",
          },
          %{
            name: "STRING",
            pattern: "\"([^\"\\\\]|\\\\.)*\"",
            is_regex: true,
            line_number: 25,
            alias: nil,
          },
          %{
            name: "ARRAY_LBRACKET",
            pattern: "[|",
            is_regex: false,
            line_number: 31,
            alias: nil,
          },
          %{
            name: "ARRAY_RBRACKET",
            pattern: "|]",
            is_regex: false,
            line_number: 32,
            alias: nil,
          },
          %{
            name: "PIPE_RIGHT",
            pattern: "|>",
            is_regex: false,
            line_number: 33,
            alias: nil,
          },
          %{
            name: "PIPE_LEFT",
            pattern: "<|",
            is_regex: false,
            line_number: 34,
            alias: nil,
          },
          %{
            name: "COMPOSE_RIGHT",
            pattern: ">>",
            is_regex: false,
            line_number: 35,
            alias: nil,
          },
          %{
            name: "COMPOSE_LEFT",
            pattern: "<<",
            is_regex: false,
            line_number: 36,
            alias: nil,
          },
          %{
            name: "NOT_EQUALS",
            pattern: "<>",
            is_regex: false,
            line_number: 37,
            alias: nil,
          },
          %{
            name: "LESS_EQUALS",
            pattern: "<=",
            is_regex: false,
            line_number: 38,
            alias: nil,
          },
          %{
            name: "GREATER_EQUALS",
            pattern: ">=",
            is_regex: false,
            line_number: 39,
            alias: nil,
          },
          %{
            name: "EQUALS_EQUALS",
            pattern: "==",
            is_regex: false,
            line_number: 40,
            alias: nil,
          },
          %{
            name: "COLON_EQUALS",
            pattern: ":=",
            is_regex: false,
            line_number: 41,
            alias: nil,
          },
          %{
            name: "DOUBLE_COLON",
            pattern: "::",
            is_regex: false,
            line_number: 42,
            alias: nil,
          },
          %{
            name: "LARROW",
            pattern: "<-",
            is_regex: false,
            line_number: 43,
            alias: nil,
          },
          %{
            name: "ARROW",
            pattern: "->",
            is_regex: false,
            line_number: 44,
            alias: nil,
          },
          %{
            name: "DOT_DOT",
            pattern: "..",
            is_regex: false,
            line_number: 45,
            alias: nil,
          },
          %{
            name: "AND_AND",
            pattern: "&&",
            is_regex: false,
            line_number: 46,
            alias: nil,
          },
          %{
            name: "OR_OR",
            pattern: "||",
            is_regex: false,
            line_number: 47,
            alias: nil,
          },
          %{
            name: "EQUALS",
            pattern: "=",
            is_regex: false,
            line_number: 53,
            alias: nil,
          },
          %{
            name: "PLUS",
            pattern: "+",
            is_regex: false,
            line_number: 54,
            alias: nil,
          },
          %{
            name: "MINUS",
            pattern: "-",
            is_regex: false,
            line_number: 55,
            alias: nil,
          },
          %{
            name: "STAR",
            pattern: "*",
            is_regex: false,
            line_number: 56,
            alias: nil,
          },
          %{
            name: "SLASH",
            pattern: "/",
            is_regex: false,
            line_number: 57,
            alias: nil,
          },
          %{
            name: "PERCENT",
            pattern: "%",
            is_regex: false,
            line_number: 58,
            alias: nil,
          },
          %{
            name: "LESS_THAN",
            pattern: "<",
            is_regex: false,
            line_number: 59,
            alias: nil,
          },
          %{
            name: "GREATER_THAN",
            pattern: ">",
            is_regex: false,
            line_number: 60,
            alias: nil,
          },
          %{
            name: "BANG",
            pattern: "!",
            is_regex: false,
            line_number: 61,
            alias: nil,
          },
          %{
            name: "AMPERSAND",
            pattern: "&",
            is_regex: false,
            line_number: 62,
            alias: nil,
          },
          %{
            name: "PIPE",
            pattern: "|",
            is_regex: false,
            line_number: 63,
            alias: nil,
          },
          %{
            name: "CARET",
            pattern: "^",
            is_regex: false,
            line_number: 64,
            alias: nil,
          },
          %{
            name: "TILDE",
            pattern: "~",
            is_regex: false,
            line_number: 65,
            alias: nil,
          },
          %{
            name: "QUESTION",
            pattern: "?",
            is_regex: false,
            line_number: 66,
            alias: nil,
          },
          %{
            name: "DOT",
            pattern: ".",
            is_regex: false,
            line_number: 67,
            alias: nil,
          },
          %{
            name: "COLON",
            pattern: ":",
            is_regex: false,
            line_number: 68,
            alias: nil,
          },
          %{
            name: "COMMA",
            pattern: ",",
            is_regex: false,
            line_number: 69,
            alias: nil,
          },
          %{
            name: "SEMICOLON",
            pattern: ";",
            is_regex: false,
            line_number: 70,
            alias: nil,
          },
          %{
            name: "LPAREN",
            pattern: "(",
            is_regex: false,
            line_number: 71,
            alias: nil,
          },
          %{
            name: "RPAREN",
            pattern: ")",
            is_regex: false,
            line_number: 72,
            alias: nil,
          },
          %{
            name: "LBRACE",
            pattern: "{",
            is_regex: false,
            line_number: 73,
            alias: nil,
          },
          %{
            name: "RBRACE",
            pattern: "}",
            is_regex: false,
            line_number: 74,
            alias: nil,
          },
          %{
            name: "LBRACKET",
            pattern: "[",
            is_regex: false,
            line_number: 75,
            alias: nil,
          },
          %{
            name: "RBRACKET",
            pattern: "]",
            is_regex: false,
            line_number: 76,
            alias: nil,
          },
        ],
      keywords: ["abstract", "and", "as", "assembly", "assert", "base", "begin", "class", "default", "delegate", "do", "done", "downcast", "downto", "else", "end", "event", "exception", "extern", "false", "field", "finally", "for", "fun", "function", "global", "if", "in", "inherit", "inline", "interface", "internal", "lazy", "let", "match", "member", "method", "module", "mutable", "namespace", "new", "null", "of", "open", "or", "override", "param", "private", "property", "public", "rec", "return", "static", "struct", "then", "this", "to", "true", "try", "type", "upcast", "use", "val", "void", "when", "while", "with", "yield"],
      mode: nil,
      escape_mode: nil,
      skip_definitions: [
          %{
            name: "WHITESPACE",
            pattern: "[ \\t\\r]+",
            is_regex: true,
            line_number: 83,
            alias: nil,
          },
          %{
            name: "LINE_COMMENT",
            pattern: "\\/\\/[^\\n]*",
            is_regex: true,
            line_number: 84,
            alias: nil,
          },
          %{
            name: "BLOCK_COMMENT",
            pattern: "\\(\\*[\\s\\S]*?\\*\\)",
            is_regex: true,
            line_number: 85,
            alias: nil,
          },
          %{
            name: "DIRECTIVE",
            pattern: "#[^\\n]*",
            is_regex: true,
            line_number: 86,
            alias: nil,
          },
        ],
      reserved_keywords: [],
      error_definitions: [
          %{
            name: "BAD_STRING",
            pattern: "\"([^\"\\\\]|\\\\.)*$",
            is_regex: true,
            line_number: 93,
            alias: nil,
          },
          %{
            name: "BAD_CHAR",
            pattern: "'([^'\\\\]|\\\\.)*$",
            is_regex: true,
            line_number: 94,
            alias: nil,
          },
        ],
      groups: %{},
      layout_keywords: [],
      case_sensitive: true,
      version: 1,
      case_insensitive: false,
      start_mode: nil,
      transitions: [],
    }
  end
  end
