cd ../../../packages/typescript/transistors && npm install --quiet
cd ../../../packages/typescript/logic-gates && npm install --quiet
cd ../../../packages/typescript/pixel-container && npm install --quiet
cd ../../../packages/typescript/paint-instructions && npm install --quiet
cd ../../../packages/typescript/paint-vm && npm install --quiet
cd ../../../packages/typescript/paint-vm-canvas && npm install --quiet
cd ../../../packages/typescript/ui-components && npm install --quiet
cd ../../../packages/typescript/arithmetic && npm install --quiet
cd ../../../packages/typescript/intel4004-gatelevel && npm install --quiet
npm install --quiet
npx vitest run
