cd ../../../packages/typescript/logic-gates && npm install
cd ../../../packages/typescript/arithmetic && npm install
cd ../../../packages/typescript/intel4004-gatelevel && npm install
cd ../../../packages/typescript/ui-components && npm install
npm install
npx vitest run
