// AUTO-GENERATED FILE — DO NOT EDIT
// Source: css.tokens
// Regenerate with: grammar-tools compile-tokens css.tokens
//
// This file embeds a TokenGrammar as native Rust data structures.
// Call `token_grammar()` instead of reading and parsing the .tokens file.

#[allow(unused_imports)]
use grammar_tools::token_grammar::{PatternGroup, TokenDefinition, TokenGrammar};
#[allow(unused_imports)]
use std::collections::HashMap;

pub fn token_grammar() -> TokenGrammar {
    TokenGrammar {
        definitions: vec![
            TokenDefinition {
                name: r#"STRING_DQ"#.to_string(),
                pattern: r#""([^"\\\n]|\\.)*""#.to_string(),
                is_regex: true,
                line_number: 67,
                alias: Some(r#"STRING"#.to_string()),
            },
            TokenDefinition {
                name: r#"STRING_SQ"#.to_string(),
                pattern: r#"'([^'\\\n]|\\.)*'"#.to_string(),
                is_regex: true,
                line_number: 68,
                alias: Some(r#"STRING"#.to_string()),
            },
            TokenDefinition {
                name: r#"DIMENSION"#.to_string(),
                pattern: r#"-?[0-9]*\.?[0-9]+([eE][+-]?[0-9]+)?[a-zA-Z]+"#.to_string(),
                is_regex: true,
                line_number: 94,
                alias: None,
            },
            TokenDefinition {
                name: r#"PERCENTAGE"#.to_string(),
                pattern: r#"-?[0-9]*\.?[0-9]+([eE][+-]?[0-9]+)?%"#.to_string(),
                is_regex: true,
                line_number: 95,
                alias: None,
            },
            TokenDefinition {
                name: r#"NUMBER"#.to_string(),
                pattern: r#"-?[0-9]*\.?[0-9]+([eE][+-]?[0-9]+)?"#.to_string(),
                is_regex: true,
                line_number: 96,
                alias: None,
            },
            TokenDefinition {
                name: r#"HASH"#.to_string(),
                pattern: r#"#[a-zA-Z0-9_-]+"#.to_string(),
                is_regex: true,
                line_number: 109,
                alias: None,
            },
            TokenDefinition {
                name: r#"AT_KEYWORD"#.to_string(),
                pattern: r#"@-?[a-zA-Z][a-zA-Z0-9-]*"#.to_string(),
                is_regex: true,
                line_number: 123,
                alias: None,
            },
            TokenDefinition {
                name: r#"URL_TOKEN"#.to_string(),
                pattern: r#"url\([^)'"]*\)"#.to_string(),
                is_regex: true,
                line_number: 136,
                alias: None,
            },
            TokenDefinition {
                name: r#"FUNCTION"#.to_string(),
                pattern: r#"-?[a-zA-Z_][a-zA-Z0-9_-]*\("#.to_string(),
                is_regex: true,
                line_number: 149,
                alias: None,
            },
            TokenDefinition {
                name: r#"CDO"#.to_string(),
                pattern: r#"<!--"#.to_string(),
                is_regex: false,
                line_number: 162,
                alias: None,
            },
            TokenDefinition {
                name: r#"CDC"#.to_string(),
                pattern: r#"-->"#.to_string(),
                is_regex: false,
                line_number: 163,
                alias: None,
            },
            TokenDefinition {
                name: r#"UNICODE_RANGE"#.to_string(),
                pattern: r#"[Uu]\+[0-9a-fA-F?]{1,6}(-[0-9a-fA-F]{1,6})?"#.to_string(),
                is_regex: true,
                line_number: 190,
                alias: None,
            },
            TokenDefinition {
                name: r#"CUSTOM_PROPERTY"#.to_string(),
                pattern: r#"--[a-zA-Z_][a-zA-Z0-9_-]*"#.to_string(),
                is_regex: true,
                line_number: 192,
                alias: None,
            },
            TokenDefinition {
                name: r#"IDENT"#.to_string(),
                pattern: r#"-?[a-zA-Z_][a-zA-Z0-9_-]*"#.to_string(),
                is_regex: true,
                line_number: 193,
                alias: None,
            },
            TokenDefinition {
                name: r#"COLON_COLON"#.to_string(),
                pattern: r#"::"#.to_string(),
                is_regex: false,
                line_number: 202,
                alias: None,
            },
            TokenDefinition {
                name: r#"TILDE_EQUALS"#.to_string(),
                pattern: r#"~="#.to_string(),
                is_regex: false,
                line_number: 203,
                alias: None,
            },
            TokenDefinition {
                name: r#"PIPE_EQUALS"#.to_string(),
                pattern: r#"|="#.to_string(),
                is_regex: false,
                line_number: 204,
                alias: None,
            },
            TokenDefinition {
                name: r#"CARET_EQUALS"#.to_string(),
                pattern: r#"^="#.to_string(),
                is_regex: false,
                line_number: 205,
                alias: None,
            },
            TokenDefinition {
                name: r#"DOLLAR_EQUALS"#.to_string(),
                pattern: r#"$="#.to_string(),
                is_regex: false,
                line_number: 206,
                alias: None,
            },
            TokenDefinition {
                name: r#"STAR_EQUALS"#.to_string(),
                pattern: r#"*="#.to_string(),
                is_regex: false,
                line_number: 207,
                alias: None,
            },
            TokenDefinition {
                name: r#"LBRACE"#.to_string(),
                pattern: r#"{"#.to_string(),
                is_regex: false,
                line_number: 216,
                alias: None,
            },
            TokenDefinition {
                name: r#"RBRACE"#.to_string(),
                pattern: r#"}"#.to_string(),
                is_regex: false,
                line_number: 217,
                alias: None,
            },
            TokenDefinition {
                name: r#"LPAREN"#.to_string(),
                pattern: r#"("#.to_string(),
                is_regex: false,
                line_number: 218,
                alias: None,
            },
            TokenDefinition {
                name: r#"RPAREN"#.to_string(),
                pattern: r#")"#.to_string(),
                is_regex: false,
                line_number: 219,
                alias: None,
            },
            TokenDefinition {
                name: r#"LBRACKET"#.to_string(),
                pattern: r#"["#.to_string(),
                is_regex: false,
                line_number: 220,
                alias: None,
            },
            TokenDefinition {
                name: r#"RBRACKET"#.to_string(),
                pattern: r#"]"#.to_string(),
                is_regex: false,
                line_number: 221,
                alias: None,
            },
            TokenDefinition {
                name: r#"SEMICOLON"#.to_string(),
                pattern: r#";"#.to_string(),
                is_regex: false,
                line_number: 222,
                alias: None,
            },
            TokenDefinition {
                name: r#"COLON"#.to_string(),
                pattern: r#":"#.to_string(),
                is_regex: false,
                line_number: 223,
                alias: None,
            },
            TokenDefinition {
                name: r#"COMMA"#.to_string(),
                pattern: r#","#.to_string(),
                is_regex: false,
                line_number: 224,
                alias: None,
            },
            TokenDefinition {
                name: r#"DOT"#.to_string(),
                pattern: r#"."#.to_string(),
                is_regex: false,
                line_number: 225,
                alias: None,
            },
            TokenDefinition {
                name: r#"PLUS"#.to_string(),
                pattern: r#"+"#.to_string(),
                is_regex: false,
                line_number: 226,
                alias: None,
            },
            TokenDefinition {
                name: r#"GREATER"#.to_string(),
                pattern: r#">"#.to_string(),
                is_regex: false,
                line_number: 227,
                alias: None,
            },
            TokenDefinition {
                name: r#"TILDE"#.to_string(),
                pattern: r#"~"#.to_string(),
                is_regex: false,
                line_number: 228,
                alias: None,
            },
            TokenDefinition {
                name: r#"STAR"#.to_string(),
                pattern: r#"*"#.to_string(),
                is_regex: false,
                line_number: 229,
                alias: None,
            },
            TokenDefinition {
                name: r#"PIPE"#.to_string(),
                pattern: r#"|"#.to_string(),
                is_regex: false,
                line_number: 230,
                alias: None,
            },
            TokenDefinition {
                name: r#"BANG"#.to_string(),
                pattern: r#"!"#.to_string(),
                is_regex: false,
                line_number: 231,
                alias: None,
            },
            TokenDefinition {
                name: r#"SLASH"#.to_string(),
                pattern: r#"/"#.to_string(),
                is_regex: false,
                line_number: 232,
                alias: None,
            },
            TokenDefinition {
                name: r#"EQUALS"#.to_string(),
                pattern: r#"="#.to_string(),
                is_regex: false,
                line_number: 233,
                alias: None,
            },
            TokenDefinition {
                name: r#"AMPERSAND"#.to_string(),
                pattern: r#"&"#.to_string(),
                is_regex: false,
                line_number: 234,
                alias: None,
            },
            TokenDefinition {
                name: r#"MINUS"#.to_string(),
                pattern: r#"-"#.to_string(),
                is_regex: false,
                line_number: 235,
                alias: None,
            },
        ],
        keywords: vec![],
        mode: None,
        skip_definitions: vec![
            TokenDefinition {
                name: r#"COMMENT"#.to_string(),
                pattern: r#"\/\*[\s\S]*?\*\/"#.to_string(),
                is_regex: true,
                line_number: 51,
                alias: None,
            },
            TokenDefinition {
                name: r#"WHITESPACE"#.to_string(),
                pattern: r#"[ \t\r\n]+"#.to_string(),
                is_regex: true,
                line_number: 52,
                alias: None,
            },
        ],
        reserved_keywords: vec![],
        escapes: Some(r#"none"#.to_string()),
        error_definitions: vec![
            TokenDefinition {
                name: r#"BAD_STRING"#.to_string(),
                pattern: r#""[^"]*$"#.to_string(),
                is_regex: true,
                line_number: 251,
                alias: None,
            },
            TokenDefinition {
                name: r#"BAD_URL"#.to_string(),
                pattern: r#"url\([^)]*$"#.to_string(),
                is_regex: true,
                line_number: 252,
                alias: None,
            },
        ],
        groups: HashMap::new(),
        case_sensitive: true,
        version: 1,
        case_insensitive: false,
        context_keywords: vec![],
        soft_keywords: vec![],
        layout_keywords: vec![],
    }
}
