defmodule CodingAdventures.SqlLexer.Grammar do
  # AUTO-GENERATED FILE — DO NOT EDIT
  # Source: sql.tokens
  # Regenerate with: grammar-tools compile-tokens sql.tokens
  #
  # This file embeds a TokenGrammar as native Elixir data structures.
  # Call token_grammar/0 instead of reading and parsing the .tokens file.

  alias CodingAdventures.GrammarTools.TokenGrammar

  def token_grammar do
    %TokenGrammar{
      definitions: [
          %{
            name: "BLOB_HEX",
            pattern: "[xX]'[0-9A-Fa-f]*'",
            is_regex: true,
            line_number: 23,
            alias: "BLOB",
          },
          %{
            name: "HEX_INT",
            pattern: "0[xX][0-9A-Fa-f]+",
            is_regex: true,
            line_number: 29,
            alias: "NUMBER",
          },
          %{
            name: "NAME",
            pattern: "[a-zA-Z_][a-zA-Z0-9_]*",
            is_regex: true,
            line_number: 30,
            alias: nil,
          },
          %{
            name: "NUMBER",
            pattern: "[0-9]+\\.?[0-9]*",
            is_regex: true,
            line_number: 31,
            alias: nil,
          },
          %{
            name: "STRING_SQ",
            pattern: "'(''|[^'])*'",
            is_regex: true,
            line_number: 32,
            alias: "STRING",
          },
          %{
            name: "QUOTED_ID",
            pattern: "`[^`]+`",
            is_regex: true,
            line_number: 33,
            alias: "NAME",
          },
          %{
            name: "QUOTED_ID_DQ",
            pattern: "\"([^\"]|\"\")*\"",
            is_regex: true,
            line_number: 38,
            alias: "NAME",
          },
          %{
            name: "LESS_EQUALS",
            pattern: "<=",
            is_regex: false,
            line_number: 40,
            alias: nil,
          },
          %{
            name: "GREATER_EQUALS",
            pattern: ">=",
            is_regex: false,
            line_number: 41,
            alias: nil,
          },
          %{
            name: "NOT_EQUALS",
            pattern: "!=",
            is_regex: false,
            line_number: 42,
            alias: nil,
          },
          %{
            name: "NEQ_ANSI",
            pattern: "<>",
            is_regex: false,
            line_number: 43,
            alias: "NOT_EQUALS",
          },
          %{
            name: "CONCAT_OP",
            pattern: "||",
            is_regex: false,
            line_number: 44,
            alias: nil,
          },
          %{
            name: "SHIFT_LEFT",
            pattern: "<<",
            is_regex: false,
            line_number: 48,
            alias: nil,
          },
          %{
            name: "SHIFT_RIGHT",
            pattern: ">>",
            is_regex: false,
            line_number: 49,
            alias: nil,
          },
          %{
            name: "JSON_ARROW_TEXT",
            pattern: "->>",
            is_regex: false,
            line_number: 56,
            alias: nil,
          },
          %{
            name: "JSON_ARROW",
            pattern: "->",
            is_regex: false,
            line_number: 57,
            alias: nil,
          },
          %{
            name: "EQUALS",
            pattern: "=",
            is_regex: false,
            line_number: 59,
            alias: nil,
          },
          %{
            name: "LESS_THAN",
            pattern: "<",
            is_regex: false,
            line_number: 60,
            alias: nil,
          },
          %{
            name: "GREATER_THAN",
            pattern: ">",
            is_regex: false,
            line_number: 61,
            alias: nil,
          },
          %{
            name: "PLUS",
            pattern: "+",
            is_regex: false,
            line_number: 62,
            alias: nil,
          },
          %{
            name: "MINUS",
            pattern: "-",
            is_regex: false,
            line_number: 63,
            alias: nil,
          },
          %{
            name: "STAR",
            pattern: "*",
            is_regex: false,
            line_number: 64,
            alias: nil,
          },
          %{
            name: "SLASH",
            pattern: "/",
            is_regex: false,
            line_number: 65,
            alias: nil,
          },
          %{
            name: "PERCENT",
            pattern: "%",
            is_regex: false,
            line_number: 66,
            alias: nil,
          },
          %{
            name: "BIT_AND_OP",
            pattern: "&",
            is_regex: false,
            line_number: 70,
            alias: nil,
          },
          %{
            name: "BIT_OR_OP",
            pattern: "|",
            is_regex: false,
            line_number: 71,
            alias: nil,
          },
          %{
            name: "BIT_NOT_OP",
            pattern: "~",
            is_regex: false,
            line_number: 72,
            alias: nil,
          },
          %{
            name: "LPAREN",
            pattern: "(",
            is_regex: false,
            line_number: 74,
            alias: nil,
          },
          %{
            name: "RPAREN",
            pattern: ")",
            is_regex: false,
            line_number: 75,
            alias: nil,
          },
          %{
            name: "COMMA",
            pattern: ",",
            is_regex: false,
            line_number: 76,
            alias: nil,
          },
          %{
            name: "SEMICOLON",
            pattern: ";",
            is_regex: false,
            line_number: 77,
            alias: nil,
          },
          %{
            name: "DOT",
            pattern: ".",
            is_regex: false,
            line_number: 78,
            alias: nil,
          },
        ],
      keywords: ["WITH", "RECURSIVE", "SELECT", "FROM", "WHERE", "GROUP", "BY", "HAVING", "ORDER", "LIMIT", "OFFSET", "INSERT", "INTO", "VALUES", "UPDATE", "SET", "DELETE", "ALTER", "ADD", "COLUMN", "CREATE", "DROP", "RENAME", "TABLE", "IF", "EXISTS", "NOT", "AND", "OR", "NULL", "IS", "IN", "BETWEEN", "LIKE", "ESCAPE", "AS", "DISTINCT", "ALL", "UNION", "INTERSECT", "EXCEPT", "JOIN", "INNER", "LEFT", "RIGHT", "OUTER", "CROSS", "FULL", "ON", "ASC", "DESC", "TRUE", "FALSE", "CASE", "WHEN", "THEN", "ELSE", "END", "PRIMARY", "KEY", "AUTOINCREMENT", "UNIQUE", "INDEX", "INDEXED", "CHECK", "REFERENCES", "DEFAULT", "COLLATE", "ATTACH", "DETACH", "DATABASE", "STRICT", "WITHOUT", "VIEW", "BEGIN", "COMMIT", "ROLLBACK", "TRANSACTION", "SAVEPOINT", "RELEASE", "TO", "OVER", "PARTITION", "WINDOW", "TRIGGER", "BEFORE", "AFTER", "FOR", "EACH", "ROW", "RETURNING", "CAST", "GLOB", "NATURAL", "USING", "REPLACE", "IGNORE", "ABORT", "FAIL", "CONFLICT", "DO", "NOTHING", "ROWS", "RANGE", "GROUPS", "PRECEDING", "FOLLOWING", "UNBOUNDED", "CURRENT", "MATERIALIZED", "NULLS"],
      mode: nil,
      escape_mode: "none",
      skip_definitions: [
          %{
            name: "WHITESPACE",
            pattern: "[ \\t\\r\\n]+",
            is_regex: true,
            line_number: 194,
            alias: nil,
          },
          %{
            name: "LINE_COMMENT",
            pattern: "--[^\\n]*",
            is_regex: true,
            line_number: 195,
            alias: nil,
          },
          %{
            name: "BLOCK_COMMENT",
            pattern: "\\x2f\\*([^*]|\\*[^\\x2f])*\\*\\x2f",
            is_regex: true,
            line_number: 196,
            alias: nil,
          },
        ],
      reserved_keywords: [],
      error_definitions: [],
      groups: %{},
      layout_keywords: [],
      case_sensitive: false,
      version: 1,
      case_insensitive: true,
      start_mode: nil,
      transitions: [],
    }
  end
end
