"""logic-engine — a Prolog-ready relational solving engine for Python.

This package sits one layer above ``logic-core``. It keeps LP00's term and
unification machinery, then adds the missing "programming with relations"
pieces: named predicates, facts, rules, clause databases, and recursive
resolution.
"""

from logic_engine.engine import (
    Atom,
    Clause,
    Compound,
    ConjExpr,
    DeferredExpr,
    Disequality,
    DisjExpr,
    EqExpr,
    FailExpr,
    FreshExpr,
    GoalExpr,
    LogicVar,
    NativeGoalExpr,
    NativeGoalRunner,
    NeqExpr,
    Number,
    Program,
    Relation,
    RelationCall,
    State,
    String,
    Substitution,
    SucceedExpr,
    Term,
    all_different,
    atom,
    conj,
    defer,
    disj,
    eq,
    fact,
    fail,
    fresh,
    logic_list,
    native_goal,
    neq,
    num,
    program,
    reify,
    relation,
    rule,
    solve,
    solve_all,
    solve_from,
    solve_n,
    string,
    succeed,
    term,
    var,
)

__all__ = [
    "__version__",
    "Atom",
    "Disequality",
    "Clause",
    "Compound",
    "ConjExpr",
    "DeferredExpr",
    "DisjExpr",
    "EqExpr",
    "FailExpr",
    "FreshExpr",
    "GoalExpr",
    "LogicVar",
    "NativeGoalExpr",
    "NativeGoalRunner",
    "NeqExpr",
    "Number",
    "Program",
    "Relation",
    "RelationCall",
    "State",
    "String",
    "Substitution",
    "SucceedExpr",
    "Term",
    "all_different",
    "atom",
    "conj",
    "defer",
    "disj",
    "eq",
    "fact",
    "fail",
    "fresh",
    "logic_list",
    "native_goal",
    "neq",
    "num",
    "program",
    "relation",
    "reify",
    "rule",
    "solve",
    "solve_all",
    "solve_from",
    "solve_n",
    "string",
    "succeed",
    "term",
    "var",
]

__version__ = "0.4.0"
