// AUTO-GENERATED FILE - DO NOT EDIT
// Source: code/grammars/algol/algol60.tokens
// Regenerate with: grammar-tools compile-tokens <source.tokens>
import 'package:coding_adventures_grammar_tools/grammar_tools.dart';

final tokenGrammar = TokenGrammar(
  version: 1,
  caseInsensitive: false,
  definitions: [
    TokenDefinition(
      name: "REAL_LIT",
      pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?|[0-9]+[eE][+-]?[0-9]+",
      isRegex: true,
      lineNumber: 38,
      alias: null,
    ),
    TokenDefinition(
      name: "INTEGER_LIT",
      pattern: "[0-9]+",
      isRegex: true,
      lineNumber: 41,
      alias: null,
    ),
    TokenDefinition(
      name: "STRING_LIT",
      pattern: "'[^']*'|\"[^\"]*\"",
      isRegex: true,
      lineNumber: 46,
      alias: null,
    ),
    TokenDefinition(
      name: "NAME",
      pattern: "[a-zA-Z][a-zA-Z0-9]*",
      isRegex: true,
      lineNumber: 53,
      alias: null,
    ),
    TokenDefinition(
      name: "ASSIGN",
      pattern: ":=",
      isRegex: false,
      lineNumber: 61,
      alias: null,
    ),
    TokenDefinition(
      name: "POWER",
      pattern: "**",
      isRegex: false,
      lineNumber: 66,
      alias: null,
    ),
    TokenDefinition(
      name: "LEQ",
      pattern: "<=|≤",
      isRegex: true,
      lineNumber: 70,
      alias: null,
    ),
    TokenDefinition(
      name: "GEQ",
      pattern: ">=|≥",
      isRegex: true,
      lineNumber: 71,
      alias: null,
    ),
    TokenDefinition(
      name: "NEQ",
      pattern: "!=|<>|≠",
      isRegex: true,
      lineNumber: 72,
      alias: null,
    ),
    TokenDefinition(
      name: "NOT_SYM",
      pattern: "¬",
      isRegex: false,
      lineNumber: 76,
      alias: null,
    ),
    TokenDefinition(
      name: "AND_SYM",
      pattern: "∧",
      isRegex: false,
      lineNumber: 77,
      alias: null,
    ),
    TokenDefinition(
      name: "OR_SYM",
      pattern: "∨",
      isRegex: false,
      lineNumber: 78,
      alias: null,
    ),
    TokenDefinition(
      name: "IMPL_SYM",
      pattern: "⊃",
      isRegex: false,
      lineNumber: 79,
      alias: null,
    ),
    TokenDefinition(
      name: "EQV_SYM",
      pattern: "≡",
      isRegex: false,
      lineNumber: 80,
      alias: null,
    ),
    TokenDefinition(
      name: "PLUS",
      pattern: "+",
      isRegex: false,
      lineNumber: 86,
      alias: null,
    ),
    TokenDefinition(
      name: "MINUS",
      pattern: "-",
      isRegex: false,
      lineNumber: 87,
      alias: null,
    ),
    TokenDefinition(
      name: "STAR",
      pattern: "\\*|×",
      isRegex: true,
      lineNumber: 90,
      alias: null,
    ),
    TokenDefinition(
      name: "SLASH",
      pattern: "\\/|÷",
      isRegex: true,
      lineNumber: 91,
      alias: null,
    ),
    TokenDefinition(
      name: "CARET",
      pattern: "\\^|↑",
      isRegex: true,
      lineNumber: 95,
      alias: null,
    ),
    TokenDefinition(
      name: "EQ",
      pattern: "=",
      isRegex: false,
      lineNumber: 98,
      alias: null,
    ),
    TokenDefinition(
      name: "LT",
      pattern: "<",
      isRegex: false,
      lineNumber: 100,
      alias: null,
    ),
    TokenDefinition(
      name: "GT",
      pattern: ">",
      isRegex: false,
      lineNumber: 101,
      alias: null,
    ),
    TokenDefinition(
      name: "LPAREN",
      pattern: "(",
      isRegex: false,
      lineNumber: 107,
      alias: null,
    ),
    TokenDefinition(
      name: "RPAREN",
      pattern: ")",
      isRegex: false,
      lineNumber: 108,
      alias: null,
    ),
    TokenDefinition(
      name: "LBRACKET",
      pattern: "[",
      isRegex: false,
      lineNumber: 109,
      alias: null,
    ),
    TokenDefinition(
      name: "RBRACKET",
      pattern: "]",
      isRegex: false,
      lineNumber: 110,
      alias: null,
    ),
    TokenDefinition(
      name: "SEMICOLON",
      pattern: ";",
      isRegex: false,
      lineNumber: 111,
      alias: null,
    ),
    TokenDefinition(
      name: "COMMA",
      pattern: ",",
      isRegex: false,
      lineNumber: 112,
      alias: null,
    ),
    TokenDefinition(
      name: "COLON",
      pattern: ":",
      isRegex: false,
      lineNumber: 116,
      alias: null,
    ),
  ],
  keywords: [
    "begin",
    "end",
    "if",
    "then",
    "else",
    "for",
    "do",
    "step",
    "until",
    "while",
    "goto",
    "switch",
    "procedure",
    "own",
    "array",
    "label",
    "value",
    "integer",
    "real",
    "boolean",
    "string",
    "true",
    "false",
    "not",
    "and",
    "or",
    "impl",
    "eqv",
    "div",
    "mod",
    "comment",
  ],
  mode: null,
  skipDefinitions: [
    TokenDefinition(
      name: "WHITESPACE",
      pattern: "[ \\t\\r\\n]+",
      isRegex: true,
      lineNumber: 183,
      alias: null,
    ),
    TokenDefinition(
      name: "COMMENT",
      pattern: "comment[^a-zA-Z0-9_][^;]*;",
      isRegex: true,
      lineNumber: 192,
      alias: null,
    ),
  ],
  reservedKeywords: const [],
  escapeMode: null,
  errorDefinitions: const [],
  groups: const {},
  caseSensitive: true,
  layoutKeywords: const [],
  contextKeywords: const [],
  softKeywords: const [],
);
