-- AUTO-GENERATED FILE - DO NOT EDIT
-- Source: verilog2005.tokens
-- Regenerate with: grammar-tools compile-tokens verilog2005.tokens
--
-- This file embeds a TokenGrammar as native Lua data structures.
-- Call token_grammar() instead of reading and parsing the .tokens file.

local gt = require("coding_adventures.grammar_tools")

local function token_grammar()
  local g = gt.TokenGrammar.new()
  g.definitions = {
        {
          name="STRING",
          pattern="\"([^\"\\\\]|\\\\.)*\"",
          is_regex=true,
          line_number=46,
          alias=nil,
        },
        {
          name="SIZED_NUMBER",
          pattern="[0-9]*'[sS]?[bBoOdDhH][0-9a-fA-F_xXzZ]+",
          is_regex=true,
          line_number=73,
          alias=nil,
        },
        {
          name="REAL_NUMBER",
          pattern="[0-9]+\\.[0-9]+([eE][+-]?[0-9]+)?",
          is_regex=true,
          line_number=77,
          alias=nil,
        },
        {
          name="NUMBER",
          pattern="[0-9][0-9_]*",
          is_regex=true,
          line_number=81,
          alias=nil,
        },
        {
          name="SYSTEM_ID",
          pattern="\\$[a-zA-Z_][a-zA-Z0-9_$]*",
          is_regex=true,
          line_number=109,
          alias=nil,
        },
        {
          name="DIRECTIVE",
          pattern="`[a-zA-Z_][a-zA-Z0-9_]*",
          is_regex=true,
          line_number=110,
          alias=nil,
        },
        {
          name="ESCAPED_IDENT",
          pattern="\\\\[^ \\t\\r\\n]+",
          is_regex=true,
          line_number=111,
          alias=nil,
        },
        {
          name="NAME",
          pattern="[a-zA-Z_][a-zA-Z0-9_$]*",
          is_regex=true,
          line_number=114,
          alias=nil,
        },
        {
          name="ARITH_LEFT_SHIFT",
          pattern="<<<",
          is_regex=false,
          line_number=126,
          alias=nil,
        },
        {
          name="ARITH_RIGHT_SHIFT",
          pattern=">>>",
          is_regex=false,
          line_number=127,
          alias=nil,
        },
        {
          name="CASE_EQ",
          pattern="===",
          is_regex=false,
          line_number=136,
          alias=nil,
        },
        {
          name="CASE_NEQ",
          pattern="!==",
          is_regex=false,
          line_number=137,
          alias=nil,
        },
        {
          name="LOGIC_AND",
          pattern="&&",
          is_regex=false,
          line_number=145,
          alias=nil,
        },
        {
          name="LOGIC_OR",
          pattern="||",
          is_regex=false,
          line_number=146,
          alias=nil,
        },
        {
          name="LEFT_SHIFT",
          pattern="<<",
          is_regex=false,
          line_number=147,
          alias=nil,
        },
        {
          name="RIGHT_SHIFT",
          pattern=">>",
          is_regex=false,
          line_number=148,
          alias=nil,
        },
        {
          name="EQUALS_EQUALS",
          pattern="==",
          is_regex=false,
          line_number=149,
          alias=nil,
        },
        {
          name="NOT_EQUALS",
          pattern="!=",
          is_regex=false,
          line_number=150,
          alias=nil,
        },
        {
          name="LESS_EQUALS",
          pattern="<=",
          is_regex=false,
          line_number=151,
          alias=nil,
        },
        {
          name="GREATER_EQUALS",
          pattern=">=",
          is_regex=false,
          line_number=152,
          alias=nil,
        },
        {
          name="POWER",
          pattern="**",
          is_regex=false,
          line_number=153,
          alias=nil,
        },
        {
          name="TRIGGER",
          pattern="->",
          is_regex=false,
          line_number=154,
          alias=nil,
        },
        {
          name="PLUS",
          pattern="+",
          is_regex=false,
          line_number=168,
          alias=nil,
        },
        {
          name="MINUS",
          pattern="-",
          is_regex=false,
          line_number=169,
          alias=nil,
        },
        {
          name="STAR",
          pattern="*",
          is_regex=false,
          line_number=170,
          alias=nil,
        },
        {
          name="SLASH",
          pattern="/",
          is_regex=false,
          line_number=171,
          alias=nil,
        },
        {
          name="PERCENT",
          pattern="%",
          is_regex=false,
          line_number=172,
          alias=nil,
        },
        {
          name="AMP",
          pattern="&",
          is_regex=false,
          line_number=173,
          alias=nil,
        },
        {
          name="PIPE",
          pattern="|",
          is_regex=false,
          line_number=174,
          alias=nil,
        },
        {
          name="CARET",
          pattern="^",
          is_regex=false,
          line_number=175,
          alias=nil,
        },
        {
          name="TILDE",
          pattern="~",
          is_regex=false,
          line_number=176,
          alias=nil,
        },
        {
          name="BANG",
          pattern="!",
          is_regex=false,
          line_number=177,
          alias=nil,
        },
        {
          name="LESS_THAN",
          pattern="<",
          is_regex=false,
          line_number=178,
          alias=nil,
        },
        {
          name="GREATER_THAN",
          pattern=">",
          is_regex=false,
          line_number=179,
          alias=nil,
        },
        {
          name="EQUALS",
          pattern="=",
          is_regex=false,
          line_number=180,
          alias=nil,
        },
        {
          name="QUESTION",
          pattern="?",
          is_regex=false,
          line_number=181,
          alias=nil,
        },
        {
          name="COLON",
          pattern=":",
          is_regex=false,
          line_number=182,
          alias=nil,
        },
        {
          name="LPAREN",
          pattern="(",
          is_regex=false,
          line_number=194,
          alias=nil,
        },
        {
          name="RPAREN",
          pattern=")",
          is_regex=false,
          line_number=195,
          alias=nil,
        },
        {
          name="LBRACKET",
          pattern="[",
          is_regex=false,
          line_number=196,
          alias=nil,
        },
        {
          name="RBRACKET",
          pattern="]",
          is_regex=false,
          line_number=197,
          alias=nil,
        },
        {
          name="LBRACE",
          pattern="{",
          is_regex=false,
          line_number=198,
          alias=nil,
        },
        {
          name="RBRACE",
          pattern="}",
          is_regex=false,
          line_number=199,
          alias=nil,
        },
        {
          name="SEMICOLON",
          pattern=";",
          is_regex=false,
          line_number=200,
          alias=nil,
        },
        {
          name="COMMA",
          pattern=",",
          is_regex=false,
          line_number=201,
          alias=nil,
        },
        {
          name="DOT",
          pattern=".",
          is_regex=false,
          line_number=202,
          alias=nil,
        },
        {
          name="HASH",
          pattern="#",
          is_regex=false,
          line_number=203,
          alias=nil,
        },
        {
          name="AT",
          pattern="@",
          is_regex=false,
          line_number=204,
          alias=nil,
        },
      }
  g.keywords = {"always", "and", "assign", "begin", "buf", "case", "casex", "casez", "default", "defparam", "else", "end", "endcase", "endfunction", "endgenerate", "endmodule", "endtask", "for", "function", "generate", "genvar", "if", "initial", "inout", "input", "integer", "localparam", "module", "nand", "negedge", "nor", "not", "or", "output", "parameter", "posedge", "real", "reg", "signed", "supply0", "supply1", "task", "tri", "unsigned", "wire", "xnor", "xor"}
  g.mode = nil
  g.escape_mode = nil
  g.skip_definitions = {
        {
          name="LINE_COMMENT",
          pattern="\\/\\/[^\\n]*",
          is_regex=true,
          line_number=31,
          alias=nil,
        },
        {
          name="BLOCK_COMMENT",
          pattern="\\/\\*([^*]|\\*[^/])*\\*\\/",
          is_regex=true,
          line_number=32,
          alias=nil,
        },
        {
          name="WHITESPACE",
          pattern="[ \\t\\r\\n]+",
          is_regex=true,
          line_number=33,
          alias=nil,
        },
      }
  g.reserved_keywords = {}
  g.error_definitions = {}
  g.groups = {}
  g.case_sensitive = true
  g.version = 0
  g.case_insensitive = false
  return g
end

return { token_grammar = token_grammar }
