// MosaicPlatformEffects.kt -- the operating-system capabilities Mosaic provides
// on Android, shared by every generated app (UI87 §7, UI89 §3.8).
//
// Generated by mosaic-app-bindings; do not edit in a generated project. This
// is Android's half of the platform library: the Storage Access Framework's
// document picker, as the router's MosaicDocumentPicker. The contracts, the
// rules a request must meet and the router are MosaicFileEffects.kt's, the
// same file the desktop project compiles; the desktop's own half (AWT dialogs)
// never reaches Android.
//
//   files.open  ACTION_OPEN_DOCUMENT (ActivityResultContracts.OpenDocument),
//               filtered on the request's MIME types (any document when none
//               map); the bytes come from ContentResolver.openInputStream,
//               bounded while reading -- a provider's reported size is not
//               trusted.
//   files.save  checked first, exactly as on the desktop; then
//               ACTION_CREATE_DOCUMENT with the suggested name and its type,
//               and the bytes go to openOutputStream(uri, "wt"). The answer's
//               name is the provider's display name, which may differ from
//               the suggestion (most providers add " (1)" rather than replace).
//               A provider owns the file, and SAF offers no atomic replace, so
//               there is no temporary-and-rename here. A write that fails is
//               a failure and nothing more: the picker may have handed back a
//               document the person already had (DocumentsUI asks "replace?"),
//               and deleting it would lose its history with the bytes.
//
// Threading
// ---------
//
// The router shows a picker from the main thread, which is where the activity
// result registry answers too; the document is read or written on a
// background thread, and the outcome is handed back to the main thread before
// the effect is completed (the host's props-changed handler writes Compose
// state). The launchers are registered when the activity is created, before
// it starts, as the registry requires; MosaicActivity does that and installs
// the router when the host loads.

import android.app.Activity
import android.content.ActivityNotFoundException
import android.content.ContentResolver
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Handler
import android.os.Looper
import android.provider.OpenableColumns
import androidx.activity.ComponentActivity
import androidx.activity.result.ActivityResultLauncher
import androidx.activity.result.contract.ActivityResultContract
import androidx.activity.result.contract.ActivityResultContracts
import java.util.concurrent.ExecutorService
import java.util.concurrent.Executors

/**
 * `ACTION_CREATE_DOCUMENT` with the type and title chosen per request:
 * `ActivityResultContracts.CreateDocument` fixes its type when registered,
 * and a launcher must be registered before the activity starts.
 */
private class MosaicCreateDocument : ActivityResultContract<Pair<String, String>, Uri?>() {
    override fun createIntent(context: Context, input: Pair<String, String>): Intent =
        Intent(Intent.ACTION_CREATE_DOCUMENT)
            .addCategory(Intent.CATEGORY_OPENABLE)
            .setType(input.first)
            .putExtra(Intent.EXTRA_TITLE, input.second)

    override fun parseResult(resultCode: Int, intent: Intent?): Uri? =
        if (resultCode == Activity.RESULT_OK) intent?.data else null
}

/**
 * The Storage Access Framework's picker as the router's [MosaicDocumentPicker].
 * Construct it in the activity's `onCreate`, before the activity starts.
 *
 * One request at a time, which the router already guarantees; the `done` of
 * the request in flight is held here until the registry answers, and only
 * ever touched on the main thread.
 */
class MosaicAndroidDocumentPicker(activity: ComponentActivity) : MosaicDocumentPicker {
    // The application's resolver, not the activity's: a read or write that
    // outlives the activity must not keep it alive.
    private val resolver: ContentResolver = activity.applicationContext.contentResolver
    private var openDone: ((MosaicOpenedDocument?) -> Unit)? = null
    private var createDone: ((MosaicSaveTarget?) -> Unit)? = null

    private val openLauncher: ActivityResultLauncher<Array<String>> =
        activity.registerForActivityResult(ActivityResultContracts.OpenDocument()) { uri ->
            val done = openDone ?: return@registerForActivityResult
            openDone = null
            done(uri?.let { MosaicContentDocument(resolver, it) })
        }

    private val createLauncher: ActivityResultLauncher<Pair<String, String>> =
        activity.registerForActivityResult(MosaicCreateDocument()) { uri ->
            val done = createDone ?: return@registerForActivityResult
            createDone = null
            done(uri?.let { MosaicContentTarget(resolver, it) })
        }

    /**
     * True while a picker is open and its answer has not arrived: what the
     * activity checks before failing the request when it is destroyed.
     */
    val isWaiting: Boolean get() = openDone != null || createDone != null

    override fun open(accept: MosaicAccept, done: (MosaicOpenedDocument?) -> Unit) {
        openDone = done
        try {
            openLauncher.launch(accept.mimeTypes.ifEmpty { listOf("*/*") }.toTypedArray())
        } catch (missing: ActivityNotFoundException) {
            openDone = null
            throw MosaicFileFailure("there is no app to choose a file with")
        } catch (error: Throwable) {
            // Not waiting on anything that failed to launch (a launcher the
            // destroyed activity already unregistered, say).
            openDone = null
            throw error
        }
    }

    override fun create(request: MosaicSaveRequest, done: (MosaicSaveTarget?) -> Unit) {
        // The name's own type when the request accepts it (or accepts
        // anything); otherwise the first type it accepts.
        val named = mosaicMimeTypeForName(request.suggestedName)
        val mimeType = if (request.accept.mimeTypes.isEmpty() || named in request.accept.mimeTypes) {
            named
        } else {
            request.accept.mimeTypes.first()
        }
        createDone = done
        try {
            createLauncher.launch(mimeType to request.suggestedName)
        } catch (missing: ActivityNotFoundException) {
            createDone = null
            throw MosaicFileFailure("there is no app to save a file with")
        } catch (error: Throwable) {
            createDone = null
            throw error
        }
    }
}

/**
 * A document's display name, as its provider reports it -- any provider, so
 * the app is told it only when it is an ordinary name: the part after any `/`
 * or `\`, not `.` or `..`, no control, line or paragraph separator, lone
 * surrogate or bidirectional control (a right-to-left override would disguise
 * it), at most 255 UTF-16 units. Other format characters are part of ordinary
 * writing -- the zero-width joiners of Persian and Devanagari and of emoji
 * sequences, a soft hyphen -- and pass, as does a character newer than the
 * device's Unicode tables.
 * Anything else, or nothing, is null, and the app is told "document".
 */
private fun mosaicDisplayName(resolver: ContentResolver, uri: Uri): String? {
    val reported = try {
        resolver.query(uri, arrayOf(OpenableColumns.DISPLAY_NAME), null, null, null)?.use { cursor ->
            if (cursor.moveToFirst() && !cursor.isNull(0)) cursor.getString(0) else null
        }
    } catch (error: Exception) {
        null
    } ?: return null
    val name = reported.substringAfterLast('/').substringAfterLast('\\')
    if (name.isBlank() || name == "." || name == ".." || name.length > 255) return null
    val unsafe = name.codePoints().anyMatch { point ->
        point in MOSAIC_BIDI_CONTROLS || when (Character.getType(point).toByte()) {
            Character.CONTROL, Character.LINE_SEPARATOR,
            Character.PARAGRAPH_SEPARATOR, Character.SURROGATE -> true
            else -> false
        }
    }
    return name.takeUnless { unsafe }
}

/**
 * The characters that reorder text: ARABIC LETTER MARK, LEFT-TO-RIGHT and
 * RIGHT-TO-LEFT MARK, the embeddings and overrides, and the isolates.
 */
private val MOSAIC_BIDI_CONTROLS: Set<Int> =
    setOf(0x061C, 0x200E, 0x200F) + (0x202A..0x202E) + (0x2066..0x2069)

/** A MIME type a provider reports, when it is shaped like one (and short). */
private val MOSAIC_MIME_SHAPE = Regex("^[A-Za-z0-9][A-Za-z0-9!#$&^_.+-]{0,126}/[A-Za-z0-9][A-Za-z0-9!#$&^_.+-]{0,126}$")

/** A chosen document, read through its provider. */
private class MosaicContentDocument(
    private val resolver: ContentResolver,
    private val uri: Uri,
) : MosaicOpenedDocument {
    // Asked of the provider when first needed -- on the background thread,
    // after the read -- never on the main thread.
    override val name: String by lazy { mosaicDisplayName(resolver, uri) ?: "document" }
    override val mimeType: String? by lazy {
        try {
            resolver.getType(uri)?.takeIf { MOSAIC_MIME_SHAPE.matches(it) }
        } catch (error: Exception) {
            null
        }
    }

    override fun read(limit: Long): ByteArray? {
        val stream = resolver.openInputStream(uri) ?: throw MosaicFileFailure("couldn't read the selected file")
        return stream.use { mosaicReadBounded(it, limit) }
    }
}

/** A document the person created to save into, written through its provider. */
private class MosaicContentTarget(
    private val resolver: ContentResolver,
    private val uri: Uri,
) : MosaicSaveTarget {
    override val name: String by lazy { mosaicDisplayName(resolver, uri) ?: "document" }

    override fun write(bytes: ByteArray) {
        val stream = resolver.openOutputStream(uri, "wt") ?: throw MosaicFileFailure("couldn't save the file")
        stream.use {
            it.write(bytes)
            it.flush()
        }
    }
}

// One background thread for every read and write: requests are one at a time
// anyway, and a daemon thread never keeps the process alive.
private val mosaicFileEffectsThread: ExecutorService = Executors.newSingleThreadExecutor { work ->
    Thread(work, "mosaic-file-effects").apply { isDaemon = true }
}

/**
 * Install the platform library on [host], answering through [picker] (the
 * activity's). Package `[host_effects]` handlers are desktop-only for now
 * (UI89 §3.5), so the standard kinds always come here, and any other kind is
 * failed by the host as unanswered. Returns the router -- the one already
 * installed, when there is one -- so the activity can fail a request whose
 * picker can no longer answer.
 */
fun installMosaicPlatformEffects(
    host: MosaicPlatformEffectHost,
    picker: MosaicDocumentPicker,
): MosaicPlatformRouter {
    (host.effectHandler as? MosaicPlatformRouter)?.let { return it }
    val main = Handler(Looper.getMainLooper())
    val router = MosaicPlatformRouter(
        host,
        host.effectHandler,
        null,
        picker,
        { work -> main.post(work) },
        { work -> mosaicFileEffectsThread.execute(work) },
    )
    host.effectHandler = router
    return router
}
