"""sql_planner — structured SQL AST → LogicalPlan tree."""

from . import ast
from . import plan as plan_module
from .ast import (
    Assignment,
    CreateTableStmt,
    DeleteStmt,
    DropTableStmt,
    InsertValuesStmt,
    JoinClause,
    JoinKind,
    Limit,
    SelectItem,
    SelectStmt,
    SortKey,
    Statement,
    TableRef,
    UpdateStmt,
)
from .errors import (
    AmbiguousColumn,
    InternalError,
    InvalidAggregate,
    PlanError,
    UnknownColumn,
    UnknownTable,
    UnsupportedStatement,
)
from .expr import (
    AggFunc,
    AggregateExpr,
    Between,
    BinaryExpr,
    BinaryOp,
    Column,
    Expr,
    FuncArg,
    FunctionCall,
    In,
    IsNotNull,
    IsNull,
    Like,
    Literal,
    NotIn,
    NotLike,
    UnaryExpr,
    UnaryOp,
    Wildcard,
    collect_columns,
    contains_aggregate,
)
from .plan import (
    Aggregate,
    AggregateItem,
    CreateTable,
    Delete,
    Distinct,
    DropTable,
    EmptyResult,
    Filter,
    Having,
    Insert,
    InsertSource,
    Join,
    LogicalPlan,
    Project,
    ProjectionItem,
    Scan,
    Sort,
    Union,
    Update,
    children,
)
from .planner import plan, plan_all
from .schema_provider import InMemorySchemaProvider, SchemaProvider

__all__ = [
    # Planner core
    "plan",
    "plan_all",
    "plan_module",
    # Schema
    "InMemorySchemaProvider",
    "SchemaProvider",
    # AST (input)
    "ast",
    "Assignment",
    "CreateTableStmt",
    "DeleteStmt",
    "DropTableStmt",
    "InsertValuesStmt",
    "JoinClause",
    "JoinKind",
    "Limit",
    "SelectItem",
    "SelectStmt",
    "SortKey",
    "Statement",
    "TableRef",
    "UpdateStmt",
    # Expressions
    "AggFunc",
    "AggregateExpr",
    "Between",
    "BinaryExpr",
    "BinaryOp",
    "Column",
    "Expr",
    "FuncArg",
    "FunctionCall",
    "In",
    "IsNotNull",
    "IsNull",
    "Like",
    "Literal",
    "NotIn",
    "NotLike",
    "UnaryExpr",
    "UnaryOp",
    "Wildcard",
    "collect_columns",
    "contains_aggregate",
    # Logical plan (output)
    "Aggregate",
    "AggregateItem",
    "CreateTable",
    "Delete",
    "Distinct",
    "DropTable",
    "EmptyResult",
    "Filter",
    "Having",
    "Insert",
    "InsertSource",
    "Join",
    "LogicalPlan",
    "Project",
    "ProjectionItem",
    "Scan",
    "Sort",
    "Union",
    "Update",
    "children",
    # Errors
    "AmbiguousColumn",
    "InternalError",
    "InvalidAggregate",
    "PlanError",
    "UnknownColumn",
    "UnknownTable",
    "UnsupportedStatement",
]
