# frozen_string_literal: true
# AUTO-GENERATED FILE — DO NOT EDIT
# Source: ts2.0.tokens
# Regenerate with: grammar-tools compile-tokens ts2.0.tokens
#
# This file embeds a TokenGrammar as native Ruby data structures.
# Downstream packages require this file directly instead of reading
# and parsing the .tokens file at runtime.

require "coding_adventures_grammar_tools"

GT = CodingAdventures::GrammarTools unless defined?(GT)

TOKEN_GRAMMAR = GT::TokenGrammar.new(
  version: 1,
  case_insensitive: false,
  case_sensitive: true,
  definitions: [
      GT::TokenDefinition.new(
        name: "NAME",
        pattern: "[a-zA-Z_$][a-zA-Z0-9_$]*",
        is_regex: true,
        line_number: 68,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BINARY_NUMBER",
        pattern: "0[bB][01]+",
        is_regex: true,
        line_number: 74,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "OCTAL_NUMBER",
        pattern: "0[oO][0-7]+",
        is_regex: true,
        line_number: 75,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "HEX_NUMBER",
        pattern: "0[xX][0-9a-fA-F]+",
        is_regex: true,
        line_number: 76,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "FLOAT_NUMBER",
        pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?",
        is_regex: true,
        line_number: 77,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "LEADING_DOT_FLOAT",
        pattern: "\\.[0-9]+([eE][+-]?[0-9]+)?",
        is_regex: true,
        line_number: 78,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "SCI_NUMBER",
        pattern: "[0-9]+[eE][+-]?[0-9]+",
        is_regex: true,
        line_number: 79,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "INT_NUMBER",
        pattern: "[0-9]+",
        is_regex: true,
        line_number: 80,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "STRING_DQ",
        pattern: "\"([^\"\\\\]|\\\\.)*\"",
        is_regex: true,
        line_number: 84,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_SQ",
        pattern: "'([^'\\\\]|\\\\.)*'",
        is_regex: true,
        line_number: 85,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "REGEX",
        pattern: "\\/([^\\/\\\\\\n]|\\\\.)+\\/[gimu]*",
        is_regex: true,
        line_number: 90,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "TEMPLATE_NO_SUB",
        pattern: "`([^`\\\\$]|\\\\.|\\$[^{])*`",
        is_regex: true,
        line_number: 108,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "TEMPLATE_HEAD",
        pattern: "`([^`\\\\$]|\\\\.|\\$[^{])*\\$\\{",
        is_regex: true,
        line_number: 109,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "ARROW",
        pattern: "=>",
        is_regex: false,
        line_number: 129,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "ELLIPSIS",
        pattern: "...",
        is_regex: false,
        line_number: 130,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STRICT_EQUALS",
        pattern: "===",
        is_regex: false,
        line_number: 132,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STRICT_NOT_EQUALS",
        pattern: "!==",
        is_regex: false,
        line_number: 133,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "UNSIGNED_RIGHT_SHIFT_EQUALS",
        pattern: ">>>=",
        is_regex: false,
        line_number: 134,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "UNSIGNED_RIGHT_SHIFT",
        pattern: ">>>",
        is_regex: false,
        line_number: 135,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LEFT_SHIFT_EQUALS",
        pattern: "<<=",
        is_regex: false,
        line_number: 136,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RIGHT_SHIFT_EQUALS",
        pattern: ">>=",
        is_regex: false,
        line_number: 137,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQUALS_EQUALS",
        pattern: "==",
        is_regex: false,
        line_number: 138,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NOT_EQUALS",
        pattern: "!=",
        is_regex: false,
        line_number: 139,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_EQUALS",
        pattern: "<=",
        is_regex: false,
        line_number: 140,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_EQUALS",
        pattern: ">=",
        is_regex: false,
        line_number: 141,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS_EQUALS",
        pattern: "+=",
        is_regex: false,
        line_number: 142,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS_EQUALS",
        pattern: "-=",
        is_regex: false,
        line_number: 143,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR_EQUALS",
        pattern: "*=",
        is_regex: false,
        line_number: 144,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SLASH_EQUALS",
        pattern: "/=",
        is_regex: false,
        line_number: 145,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PERCENT_EQUALS",
        pattern: "%=",
        is_regex: false,
        line_number: 146,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AMPERSAND_EQUALS",
        pattern: "&=",
        is_regex: false,
        line_number: 147,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PIPE_EQUALS",
        pattern: "|=",
        is_regex: false,
        line_number: 148,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CARET_EQUALS",
        pattern: "^=",
        is_regex: false,
        line_number: 149,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LEFT_SHIFT",
        pattern: "<<",
        is_regex: false,
        line_number: 150,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RIGHT_SHIFT",
        pattern: ">>",
        is_regex: false,
        line_number: 151,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AND_AND",
        pattern: "&&",
        is_regex: false,
        line_number: 152,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "OR_OR",
        pattern: "||",
        is_regex: false,
        line_number: 153,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS_PLUS",
        pattern: "++",
        is_regex: false,
        line_number: 154,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS_MINUS",
        pattern: "--",
        is_regex: false,
        line_number: 155,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQUALS",
        pattern: "=",
        is_regex: false,
        line_number: 171,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS",
        pattern: "+",
        is_regex: false,
        line_number: 172,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS",
        pattern: "-",
        is_regex: false,
        line_number: 173,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR",
        pattern: "*",
        is_regex: false,
        line_number: 174,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SLASH",
        pattern: "/",
        is_regex: false,
        line_number: 175,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PERCENT",
        pattern: "%",
        is_regex: false,
        line_number: 176,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_THAN",
        pattern: "<",
        is_regex: false,
        line_number: 177,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_THAN",
        pattern: ">",
        is_regex: false,
        line_number: 178,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BANG",
        pattern: "!",
        is_regex: false,
        line_number: 179,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AMPERSAND",
        pattern: "&",
        is_regex: false,
        line_number: 180,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PIPE",
        pattern: "|",
        is_regex: false,
        line_number: 181,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CARET",
        pattern: "^",
        is_regex: false,
        line_number: 182,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "TILDE",
        pattern: "~",
        is_regex: false,
        line_number: 183,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "QUESTION",
        pattern: "?",
        is_regex: false,
        line_number: 184,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AT",
        pattern: "@",
        is_regex: false,
        line_number: 187,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LPAREN",
        pattern: "(",
        is_regex: false,
        line_number: 193,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RPAREN",
        pattern: ")",
        is_regex: false,
        line_number: 194,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACE",
        pattern: "{",
        is_regex: false,
        line_number: 195,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACE",
        pattern: "}",
        is_regex: false,
        line_number: 196,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACKET",
        pattern: "[",
        is_regex: false,
        line_number: 197,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACKET",
        pattern: "]",
        is_regex: false,
        line_number: 198,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SEMICOLON",
        pattern: ";",
        is_regex: false,
        line_number: 199,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COMMA",
        pattern: ",",
        is_regex: false,
        line_number: 200,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COLON",
        pattern: ":",
        is_regex: false,
        line_number: 201,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DOT",
        pattern: ".",
        is_regex: false,
        line_number: 202,
        alias_name: nil,
      ),
    ],
  keywords: ["break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "export", "extends", "finally", "for", "function", "if", "import", "in", "instanceof", "let", "new", "return", "super", "switch", "this", "throw", "try", "typeof", "var", "void", "while", "with", "yield", "true", "false", "null", "enum"],
  mode: nil,
  escape_mode: nil,
  skip_definitions: [
      GT::TokenDefinition.new(
        name: "WHITESPACE",
        pattern: "[ \\t\\r\\n\\v\\f]+",
        is_regex: true,
        line_number: 343,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LINE_COMMENT",
        pattern: "\\/\\/[^\\n]*",
        is_regex: true,
        line_number: 344,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BLOCK_COMMENT",
        pattern: "\\/\\*([^*]|\\*[^\\/])*\\*\\/",
        is_regex: true,
        line_number: 345,
        alias_name: nil,
      ),
    ],
  reserved_keywords: [],
  error_definitions: [
      GT::TokenDefinition.new(
        name: "BAD_STRING_DQ",
        pattern: "\"[^\"]*$",
        is_regex: true,
        line_number: 352,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BAD_STRING_SQ",
        pattern: "'[^']*$",
        is_regex: true,
        line_number: 353,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BAD_REGEX",
        pattern: "\\/([^\\/\\\\\\n]|\\\\.)*$",
        is_regex: true,
        line_number: 354,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BAD_TEMPLATE",
        pattern: "`([^`\\\\$]|\\\\.|\\$[^{])*$",
        is_regex: true,
        line_number: 355,
        alias_name: nil,
      ),
    ],
  groups: {
      "template" => GT::PatternGroup.new(
        name: "template",
        definitions: [
          GT::TokenDefinition.new(
            name: "TEMPLATE_MIDDLE",
            pattern: "\\}([^`\\\\$]|\\\\.|\\$[^{])*\\$\\{",
            is_regex: true,
            line_number: 335,
            alias_name: nil,
          ),
          GT::TokenDefinition.new(
            name: "TEMPLATE_TAIL",
            pattern: "\\}([^`\\\\$]|\\\\.|\\$[^{])*`",
            is_regex: true,
            line_number: 336,
            alias_name: nil,
          ),
        ],
      ),
    },
  layout_keywords: [],
  context_keywords: ["as", "from", "of", "get", "set", "static", "type", "interface", "namespace", "module", "declare", "abstract", "readonly", "is", "keyof", "asserts", "unique", "never", "infer"],
  soft_keywords: [],
)
