// Code generated by grammar-tools. DO NOT EDIT.
// Source: starlark.tokens
// Regenerate with: grammar-tools compile-tokens starlark.tokens
//
// This file embeds a TokenGrammar as native Go data structures.
// Downstream packages use TokenGrammarData directly instead of reading
// and parsing the .tokens file at runtime.

package starlarklexer

import gt "github.com/adhithyan15/coding-adventures/code/packages/go/grammar-tools"

// TokenGrammarData is the embedded token grammar.
var TokenGrammarData = &gt.TokenGrammar{
	Version:          1,
	CaseInsensitive:  false,
	CaseSensitive:    true,
	Definitions:      []gt.TokenDefinition{
			gt.TokenDefinition{Name: `STRING_RAW_TRIPLE_DQ`, Pattern: `[rR][bB]?"""([^"\\]|\\.|\n)*"""|[bB][rR]"""([^"\\]|\\.|\n)*"""`, IsRegex: true, LineNumber: 84, Alias: `STRING`},
			gt.TokenDefinition{Name: `STRING_RAW_TRIPLE_SQ`, Pattern: `[rR][bB]?'''([^'\\]|\\.|\n)*'''|[bB][rR]'''([^'\\]|\\.|\n)*'''`, IsRegex: true, LineNumber: 85, Alias: `STRING`},
			gt.TokenDefinition{Name: `STRING_TRIPLE_DQ`, Pattern: `[bB]?"""([^"\\]|\\.|\n)*"""`, IsRegex: true, LineNumber: 86, Alias: `STRING`},
			gt.TokenDefinition{Name: `STRING_TRIPLE_SQ`, Pattern: `[bB]?'''([^'\\]|\\.|\n)*'''`, IsRegex: true, LineNumber: 87, Alias: `STRING`},
			gt.TokenDefinition{Name: `STRING_RAW_DQ`, Pattern: `[rR][bB]?"([^"\\]|\\.)*"|[bB][rR]"([^"\\]|\\.)*"`, IsRegex: true, LineNumber: 90, Alias: `STRING`},
			gt.TokenDefinition{Name: `STRING_RAW_SQ`, Pattern: `[rR][bB]?'([^'\\]|\\.)*'|[bB][rR]'([^'\\]|\\.)*'`, IsRegex: true, LineNumber: 91, Alias: `STRING`},
			gt.TokenDefinition{Name: `STRING_DQ`, Pattern: `[bB]?"([^"\\]|\\.)*"`, IsRegex: true, LineNumber: 92, Alias: `STRING`},
			gt.TokenDefinition{Name: `STRING_SQ`, Pattern: `[bB]?'([^'\\]|\\.)*'`, IsRegex: true, LineNumber: 93, Alias: `STRING`},
			gt.TokenDefinition{Name: `FLOAT_EXP`, Pattern: `[0-9]+[eE][+-]?[0-9]+`, IsRegex: true, LineNumber: 110, Alias: `FLOAT`},
			gt.TokenDefinition{Name: `FLOAT_DOT`, Pattern: `\.[0-9]+([eE][+-]?[0-9]+)?`, IsRegex: true, LineNumber: 111, Alias: `FLOAT`},
			gt.TokenDefinition{Name: `FLOAT`, Pattern: `[0-9]+\.[0-9]*([eE][+-]?[0-9]+)?`, IsRegex: true, LineNumber: 112, Alias: `FLOAT`},
			gt.TokenDefinition{Name: `INT_HEX`, Pattern: `0[xX][0-9a-fA-F]+`, IsRegex: true, LineNumber: 115, Alias: `INT`},
			gt.TokenDefinition{Name: `INT_OCT`, Pattern: `0[oO][0-7]+`, IsRegex: true, LineNumber: 116, Alias: `INT`},
			gt.TokenDefinition{Name: `INT`, Pattern: `[0-9]+`, IsRegex: true, LineNumber: 117, Alias: ``},
			gt.TokenDefinition{Name: `NAME`, Pattern: `[a-zA-Z_][a-zA-Z0-9_]*`, IsRegex: true, LineNumber: 127, Alias: ``},
			gt.TokenDefinition{Name: `DOUBLE_STAR_EQUALS`, Pattern: `**=`, IsRegex: false, LineNumber: 136, Alias: ``},
			gt.TokenDefinition{Name: `LEFT_SHIFT_EQUALS`, Pattern: `<<=`, IsRegex: false, LineNumber: 137, Alias: ``},
			gt.TokenDefinition{Name: `RIGHT_SHIFT_EQUALS`, Pattern: `>>=`, IsRegex: false, LineNumber: 138, Alias: ``},
			gt.TokenDefinition{Name: `FLOOR_DIV_EQUALS`, Pattern: `//=`, IsRegex: false, LineNumber: 139, Alias: ``},
			gt.TokenDefinition{Name: `DOUBLE_STAR`, Pattern: `**`, IsRegex: false, LineNumber: 148, Alias: ``},
			gt.TokenDefinition{Name: `FLOOR_DIV`, Pattern: `//`, IsRegex: false, LineNumber: 149, Alias: ``},
			gt.TokenDefinition{Name: `LEFT_SHIFT`, Pattern: `<<`, IsRegex: false, LineNumber: 150, Alias: ``},
			gt.TokenDefinition{Name: `RIGHT_SHIFT`, Pattern: `>>`, IsRegex: false, LineNumber: 151, Alias: ``},
			gt.TokenDefinition{Name: `EQUALS_EQUALS`, Pattern: `==`, IsRegex: false, LineNumber: 152, Alias: ``},
			gt.TokenDefinition{Name: `NOT_EQUALS`, Pattern: `!=`, IsRegex: false, LineNumber: 153, Alias: ``},
			gt.TokenDefinition{Name: `LESS_EQUALS`, Pattern: `<=`, IsRegex: false, LineNumber: 154, Alias: ``},
			gt.TokenDefinition{Name: `GREATER_EQUALS`, Pattern: `>=`, IsRegex: false, LineNumber: 155, Alias: ``},
			gt.TokenDefinition{Name: `PLUS_EQUALS`, Pattern: `+=`, IsRegex: false, LineNumber: 156, Alias: ``},
			gt.TokenDefinition{Name: `MINUS_EQUALS`, Pattern: `-=`, IsRegex: false, LineNumber: 157, Alias: ``},
			gt.TokenDefinition{Name: `STAR_EQUALS`, Pattern: `*=`, IsRegex: false, LineNumber: 158, Alias: ``},
			gt.TokenDefinition{Name: `SLASH_EQUALS`, Pattern: `/=`, IsRegex: false, LineNumber: 159, Alias: ``},
			gt.TokenDefinition{Name: `PERCENT_EQUALS`, Pattern: `%=`, IsRegex: false, LineNumber: 160, Alias: ``},
			gt.TokenDefinition{Name: `AMP_EQUALS`, Pattern: `&=`, IsRegex: false, LineNumber: 161, Alias: ``},
			gt.TokenDefinition{Name: `PIPE_EQUALS`, Pattern: `|=`, IsRegex: false, LineNumber: 162, Alias: ``},
			gt.TokenDefinition{Name: `CARET_EQUALS`, Pattern: `^=`, IsRegex: false, LineNumber: 163, Alias: ``},
			gt.TokenDefinition{Name: `PLUS`, Pattern: `+`, IsRegex: false, LineNumber: 169, Alias: ``},
			gt.TokenDefinition{Name: `MINUS`, Pattern: `-`, IsRegex: false, LineNumber: 170, Alias: ``},
			gt.TokenDefinition{Name: `STAR`, Pattern: `*`, IsRegex: false, LineNumber: 171, Alias: ``},
			gt.TokenDefinition{Name: `SLASH`, Pattern: `/`, IsRegex: false, LineNumber: 172, Alias: ``},
			gt.TokenDefinition{Name: `PERCENT`, Pattern: `%`, IsRegex: false, LineNumber: 173, Alias: ``},
			gt.TokenDefinition{Name: `EQUALS`, Pattern: `=`, IsRegex: false, LineNumber: 174, Alias: ``},
			gt.TokenDefinition{Name: `LESS_THAN`, Pattern: `<`, IsRegex: false, LineNumber: 175, Alias: ``},
			gt.TokenDefinition{Name: `GREATER_THAN`, Pattern: `>`, IsRegex: false, LineNumber: 176, Alias: ``},
			gt.TokenDefinition{Name: `AMP`, Pattern: `&`, IsRegex: false, LineNumber: 177, Alias: ``},
			gt.TokenDefinition{Name: `PIPE`, Pattern: `|`, IsRegex: false, LineNumber: 178, Alias: ``},
			gt.TokenDefinition{Name: `CARET`, Pattern: `^`, IsRegex: false, LineNumber: 179, Alias: ``},
			gt.TokenDefinition{Name: `TILDE`, Pattern: `~`, IsRegex: false, LineNumber: 180, Alias: ``},
			gt.TokenDefinition{Name: `LPAREN`, Pattern: `(`, IsRegex: false, LineNumber: 186, Alias: ``},
			gt.TokenDefinition{Name: `RPAREN`, Pattern: `)`, IsRegex: false, LineNumber: 187, Alias: ``},
			gt.TokenDefinition{Name: `LBRACKET`, Pattern: `[`, IsRegex: false, LineNumber: 188, Alias: ``},
			gt.TokenDefinition{Name: `RBRACKET`, Pattern: `]`, IsRegex: false, LineNumber: 189, Alias: ``},
			gt.TokenDefinition{Name: `LBRACE`, Pattern: `{`, IsRegex: false, LineNumber: 190, Alias: ``},
			gt.TokenDefinition{Name: `RBRACE`, Pattern: `}`, IsRegex: false, LineNumber: 191, Alias: ``},
			gt.TokenDefinition{Name: `COMMA`, Pattern: `,`, IsRegex: false, LineNumber: 192, Alias: ``},
			gt.TokenDefinition{Name: `COLON`, Pattern: `:`, IsRegex: false, LineNumber: 193, Alias: ``},
			gt.TokenDefinition{Name: `SEMICOLON`, Pattern: `;`, IsRegex: false, LineNumber: 194, Alias: ``},
			gt.TokenDefinition{Name: `DOT`, Pattern: `.`, IsRegex: false, LineNumber: 195, Alias: ``},
		},
	Keywords:         []string{`and`, `break`, `continue`, `def`, `elif`, `else`, `for`, `if`, `in`, `lambda`, `load`, `not`, `or`, `pass`, `return`, `True`, `False`, `None`},
	Mode:             `indentation`,
	EscapeMode:       ``,
	SkipDefinitions:  []gt.TokenDefinition{
			gt.TokenDefinition{Name: `COMMENT`, Pattern: `#[^\n]*`, IsRegex: true, LineNumber: 65, Alias: ``},
			gt.TokenDefinition{Name: `WHITESPACE`, Pattern: `[ \t]+`, IsRegex: true, LineNumber: 66, Alias: ``},
		},
	ReservedKeywords: []string{`as`, `assert`, `async`, `await`, `class`, `del`, `except`, `finally`, `from`, `global`, `import`, `is`, `nonlocal`, `raise`, `try`, `while`, `with`, `yield`},
	ErrorDefinitions: []gt.TokenDefinition{},
	Groups:           map[string]*gt.PatternGroup{},
	LayoutKeywords:   []string{},
}
