// AUTO-GENERATED FILE - DO NOT EDIT
package starlarklexer

import (
	grammartools "github.com/adhithyan15/coding-adventures/code/packages/go/grammar-tools"
)

var StarlarkTokens = &grammartools.TokenGrammar{
	Version: 1,
	CaseInsensitive: false,
	CaseSensitive: true,
	Mode: "indentation",
	Definitions: []grammartools.TokenDefinition{
		grammartools.TokenDefinition{Name: "STRING_RAW_TRIPLE_DQ", Pattern: "[rR][bB]?\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"|[bB][rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"", IsRegex: true, LineNumber: 70, Alias: "STRING"},
		grammartools.TokenDefinition{Name: "STRING_RAW_TRIPLE_SQ", Pattern: "[rR][bB]?'''([^'\\\\]|\\\\.|\\n)*'''|[bB][rR]'''([^'\\\\]|\\\\.|\\n)*'''", IsRegex: true, LineNumber: 71, Alias: "STRING"},
		grammartools.TokenDefinition{Name: "STRING_TRIPLE_DQ", Pattern: "[bB]?\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"", IsRegex: true, LineNumber: 72, Alias: "STRING"},
		grammartools.TokenDefinition{Name: "STRING_TRIPLE_SQ", Pattern: "[bB]?'''([^'\\\\]|\\\\.|\\n)*'''", IsRegex: true, LineNumber: 73, Alias: "STRING"},
		grammartools.TokenDefinition{Name: "STRING_RAW_DQ", Pattern: "[rR][bB]?\"([^\"\\\\]|\\\\.)*\"|[bB][rR]\"([^\"\\\\]|\\\\.)*\"", IsRegex: true, LineNumber: 76, Alias: "STRING"},
		grammartools.TokenDefinition{Name: "STRING_RAW_SQ", Pattern: "[rR][bB]?'([^'\\\\]|\\\\.)*'|[bB][rR]'([^'\\\\]|\\\\.)*'", IsRegex: true, LineNumber: 77, Alias: "STRING"},
		grammartools.TokenDefinition{Name: "STRING_DQ", Pattern: "[bB]?\"([^\"\\\\]|\\\\.)*\"", IsRegex: true, LineNumber: 78, Alias: "STRING"},
		grammartools.TokenDefinition{Name: "STRING_SQ", Pattern: "[bB]?'([^'\\\\]|\\\\.)*'", IsRegex: true, LineNumber: 79, Alias: "STRING"},
		grammartools.TokenDefinition{Name: "FLOAT", Pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?|\\.[0-9]+([eE][+-]?[0-9]+)?|[0-9]+[eE][+-]?[0-9]+", IsRegex: true, LineNumber: 92, Alias: ""},
		grammartools.TokenDefinition{Name: "INT_HEX", Pattern: "0[xX][0-9a-fA-F]+", IsRegex: true, LineNumber: 95, Alias: "INT"},
		grammartools.TokenDefinition{Name: "INT_OCT", Pattern: "0[oO][0-7]+", IsRegex: true, LineNumber: 96, Alias: "INT"},
		grammartools.TokenDefinition{Name: "INT", Pattern: "[0-9]+", IsRegex: true, LineNumber: 97, Alias: ""},
		grammartools.TokenDefinition{Name: "NAME", Pattern: "[a-zA-Z_][a-zA-Z0-9_]*", IsRegex: true, LineNumber: 107, Alias: ""},
		grammartools.TokenDefinition{Name: "DOUBLE_STAR_EQUALS", Pattern: "**=", IsRegex: false, LineNumber: 116, Alias: ""},
		grammartools.TokenDefinition{Name: "LEFT_SHIFT_EQUALS", Pattern: "<<=", IsRegex: false, LineNumber: 117, Alias: ""},
		grammartools.TokenDefinition{Name: "RIGHT_SHIFT_EQUALS", Pattern: ">>=", IsRegex: false, LineNumber: 118, Alias: ""},
		grammartools.TokenDefinition{Name: "FLOOR_DIV_EQUALS", Pattern: "//=", IsRegex: false, LineNumber: 119, Alias: ""},
		grammartools.TokenDefinition{Name: "DOUBLE_STAR", Pattern: "**", IsRegex: false, LineNumber: 128, Alias: ""},
		grammartools.TokenDefinition{Name: "FLOOR_DIV", Pattern: "//", IsRegex: false, LineNumber: 129, Alias: ""},
		grammartools.TokenDefinition{Name: "LEFT_SHIFT", Pattern: "<<", IsRegex: false, LineNumber: 130, Alias: ""},
		grammartools.TokenDefinition{Name: "RIGHT_SHIFT", Pattern: ">>", IsRegex: false, LineNumber: 131, Alias: ""},
		grammartools.TokenDefinition{Name: "EQUALS_EQUALS", Pattern: "==", IsRegex: false, LineNumber: 132, Alias: ""},
		grammartools.TokenDefinition{Name: "NOT_EQUALS", Pattern: "!=", IsRegex: false, LineNumber: 133, Alias: ""},
		grammartools.TokenDefinition{Name: "LESS_EQUALS", Pattern: "<=", IsRegex: false, LineNumber: 134, Alias: ""},
		grammartools.TokenDefinition{Name: "GREATER_EQUALS", Pattern: ">=", IsRegex: false, LineNumber: 135, Alias: ""},
		grammartools.TokenDefinition{Name: "PLUS_EQUALS", Pattern: "+=", IsRegex: false, LineNumber: 136, Alias: ""},
		grammartools.TokenDefinition{Name: "MINUS_EQUALS", Pattern: "-=", IsRegex: false, LineNumber: 137, Alias: ""},
		grammartools.TokenDefinition{Name: "STAR_EQUALS", Pattern: "*=", IsRegex: false, LineNumber: 138, Alias: ""},
		grammartools.TokenDefinition{Name: "SLASH_EQUALS", Pattern: "/=", IsRegex: false, LineNumber: 139, Alias: ""},
		grammartools.TokenDefinition{Name: "PERCENT_EQUALS", Pattern: "%=", IsRegex: false, LineNumber: 140, Alias: ""},
		grammartools.TokenDefinition{Name: "AMP_EQUALS", Pattern: "&=", IsRegex: false, LineNumber: 141, Alias: ""},
		grammartools.TokenDefinition{Name: "PIPE_EQUALS", Pattern: "|=", IsRegex: false, LineNumber: 142, Alias: ""},
		grammartools.TokenDefinition{Name: "CARET_EQUALS", Pattern: "^=", IsRegex: false, LineNumber: 143, Alias: ""},
		grammartools.TokenDefinition{Name: "PLUS", Pattern: "+", IsRegex: false, LineNumber: 149, Alias: ""},
		grammartools.TokenDefinition{Name: "MINUS", Pattern: "-", IsRegex: false, LineNumber: 150, Alias: ""},
		grammartools.TokenDefinition{Name: "STAR", Pattern: "*", IsRegex: false, LineNumber: 151, Alias: ""},
		grammartools.TokenDefinition{Name: "SLASH", Pattern: "/", IsRegex: false, LineNumber: 152, Alias: ""},
		grammartools.TokenDefinition{Name: "PERCENT", Pattern: "%", IsRegex: false, LineNumber: 153, Alias: ""},
		grammartools.TokenDefinition{Name: "EQUALS", Pattern: "=", IsRegex: false, LineNumber: 154, Alias: ""},
		grammartools.TokenDefinition{Name: "LESS_THAN", Pattern: "<", IsRegex: false, LineNumber: 155, Alias: ""},
		grammartools.TokenDefinition{Name: "GREATER_THAN", Pattern: ">", IsRegex: false, LineNumber: 156, Alias: ""},
		grammartools.TokenDefinition{Name: "AMP", Pattern: "&", IsRegex: false, LineNumber: 157, Alias: ""},
		grammartools.TokenDefinition{Name: "PIPE", Pattern: "|", IsRegex: false, LineNumber: 158, Alias: ""},
		grammartools.TokenDefinition{Name: "CARET", Pattern: "^", IsRegex: false, LineNumber: 159, Alias: ""},
		grammartools.TokenDefinition{Name: "TILDE", Pattern: "~", IsRegex: false, LineNumber: 160, Alias: ""},
		grammartools.TokenDefinition{Name: "LPAREN", Pattern: "(", IsRegex: false, LineNumber: 166, Alias: ""},
		grammartools.TokenDefinition{Name: "RPAREN", Pattern: ")", IsRegex: false, LineNumber: 167, Alias: ""},
		grammartools.TokenDefinition{Name: "LBRACKET", Pattern: "[", IsRegex: false, LineNumber: 168, Alias: ""},
		grammartools.TokenDefinition{Name: "RBRACKET", Pattern: "]", IsRegex: false, LineNumber: 169, Alias: ""},
		grammartools.TokenDefinition{Name: "LBRACE", Pattern: "{", IsRegex: false, LineNumber: 170, Alias: ""},
		grammartools.TokenDefinition{Name: "RBRACE", Pattern: "}", IsRegex: false, LineNumber: 171, Alias: ""},
		grammartools.TokenDefinition{Name: "COMMA", Pattern: ",", IsRegex: false, LineNumber: 172, Alias: ""},
		grammartools.TokenDefinition{Name: "COLON", Pattern: ":", IsRegex: false, LineNumber: 173, Alias: ""},
		grammartools.TokenDefinition{Name: "SEMICOLON", Pattern: ";", IsRegex: false, LineNumber: 174, Alias: ""},
		grammartools.TokenDefinition{Name: "DOT", Pattern: ".", IsRegex: false, LineNumber: 175, Alias: ""},
	},
	Keywords: []string{"and", "break", "continue", "def", "elif", "else", "for", "if", "in", "lambda", "load", "not", "or", "pass", "return", "True", "False", "None", },
	ReservedKeywords: []string{"as", "assert", "async", "await", "class", "del", "except", "finally", "from", "global", "import", "is", "nonlocal", "raise", "try", "while", "with", "yield", },
	SkipDefinitions: []grammartools.TokenDefinition{
		grammartools.TokenDefinition{Name: "COMMENT", Pattern: "#[^\\n]*", IsRegex: true, LineNumber: 51, Alias: ""},
		grammartools.TokenDefinition{Name: "WHITESPACE", Pattern: "[ \\t]+", IsRegex: true, LineNumber: 52, Alias: ""},
	},
}
