// AUTO-GENERATED FILE - DO NOT EDIT
package veriloglexer

import (
	grammartools "github.com/adhithyan15/coding-adventures/code/packages/go/grammar-tools"
)

var VerilogTokens = &grammartools.TokenGrammar{
	Version: 0,
	CaseInsensitive: false,
	CaseSensitive: true,
	Definitions: []grammartools.TokenDefinition{
		grammartools.TokenDefinition{Name: "STRING", Pattern: "\"([^\"\\\\]|\\\\.)*\"", IsRegex: true, LineNumber: 46, Alias: ""},
		grammartools.TokenDefinition{Name: "SIZED_NUMBER", Pattern: "[0-9]*'[sS]?[bBoOdDhH][0-9a-fA-F_xXzZ]+", IsRegex: true, LineNumber: 73, Alias: ""},
		grammartools.TokenDefinition{Name: "REAL_NUMBER", Pattern: "[0-9]+\\.[0-9]+([eE][+-]?[0-9]+)?", IsRegex: true, LineNumber: 77, Alias: ""},
		grammartools.TokenDefinition{Name: "NUMBER", Pattern: "[0-9][0-9_]*", IsRegex: true, LineNumber: 81, Alias: ""},
		grammartools.TokenDefinition{Name: "SYSTEM_ID", Pattern: "\\$[a-zA-Z_][a-zA-Z0-9_$]*", IsRegex: true, LineNumber: 109, Alias: ""},
		grammartools.TokenDefinition{Name: "DIRECTIVE", Pattern: "`[a-zA-Z_][a-zA-Z0-9_]*", IsRegex: true, LineNumber: 110, Alias: ""},
		grammartools.TokenDefinition{Name: "ESCAPED_IDENT", Pattern: "\\\\[^ \\t\\r\\n]+", IsRegex: true, LineNumber: 111, Alias: ""},
		grammartools.TokenDefinition{Name: "NAME", Pattern: "[a-zA-Z_][a-zA-Z0-9_$]*", IsRegex: true, LineNumber: 114, Alias: ""},
		grammartools.TokenDefinition{Name: "ARITH_LEFT_SHIFT", Pattern: "<<<", IsRegex: false, LineNumber: 126, Alias: ""},
		grammartools.TokenDefinition{Name: "ARITH_RIGHT_SHIFT", Pattern: ">>>", IsRegex: false, LineNumber: 127, Alias: ""},
		grammartools.TokenDefinition{Name: "CASE_EQ", Pattern: "===", IsRegex: false, LineNumber: 136, Alias: ""},
		grammartools.TokenDefinition{Name: "CASE_NEQ", Pattern: "!==", IsRegex: false, LineNumber: 137, Alias: ""},
		grammartools.TokenDefinition{Name: "LOGIC_AND", Pattern: "&&", IsRegex: false, LineNumber: 145, Alias: ""},
		grammartools.TokenDefinition{Name: "LOGIC_OR", Pattern: "||", IsRegex: false, LineNumber: 146, Alias: ""},
		grammartools.TokenDefinition{Name: "LEFT_SHIFT", Pattern: "<<", IsRegex: false, LineNumber: 147, Alias: ""},
		grammartools.TokenDefinition{Name: "RIGHT_SHIFT", Pattern: ">>", IsRegex: false, LineNumber: 148, Alias: ""},
		grammartools.TokenDefinition{Name: "EQUALS_EQUALS", Pattern: "==", IsRegex: false, LineNumber: 149, Alias: ""},
		grammartools.TokenDefinition{Name: "NOT_EQUALS", Pattern: "!=", IsRegex: false, LineNumber: 150, Alias: ""},
		grammartools.TokenDefinition{Name: "LESS_EQUALS", Pattern: "<=", IsRegex: false, LineNumber: 151, Alias: ""},
		grammartools.TokenDefinition{Name: "GREATER_EQUALS", Pattern: ">=", IsRegex: false, LineNumber: 152, Alias: ""},
		grammartools.TokenDefinition{Name: "POWER", Pattern: "**", IsRegex: false, LineNumber: 153, Alias: ""},
		grammartools.TokenDefinition{Name: "TRIGGER", Pattern: "->", IsRegex: false, LineNumber: 154, Alias: ""},
		grammartools.TokenDefinition{Name: "PLUS", Pattern: "+", IsRegex: false, LineNumber: 168, Alias: ""},
		grammartools.TokenDefinition{Name: "MINUS", Pattern: "-", IsRegex: false, LineNumber: 169, Alias: ""},
		grammartools.TokenDefinition{Name: "STAR", Pattern: "*", IsRegex: false, LineNumber: 170, Alias: ""},
		grammartools.TokenDefinition{Name: "SLASH", Pattern: "/", IsRegex: false, LineNumber: 171, Alias: ""},
		grammartools.TokenDefinition{Name: "PERCENT", Pattern: "%", IsRegex: false, LineNumber: 172, Alias: ""},
		grammartools.TokenDefinition{Name: "AMP", Pattern: "&", IsRegex: false, LineNumber: 173, Alias: ""},
		grammartools.TokenDefinition{Name: "PIPE", Pattern: "|", IsRegex: false, LineNumber: 174, Alias: ""},
		grammartools.TokenDefinition{Name: "CARET", Pattern: "^", IsRegex: false, LineNumber: 175, Alias: ""},
		grammartools.TokenDefinition{Name: "TILDE", Pattern: "~", IsRegex: false, LineNumber: 176, Alias: ""},
		grammartools.TokenDefinition{Name: "BANG", Pattern: "!", IsRegex: false, LineNumber: 177, Alias: ""},
		grammartools.TokenDefinition{Name: "LESS_THAN", Pattern: "<", IsRegex: false, LineNumber: 178, Alias: ""},
		grammartools.TokenDefinition{Name: "GREATER_THAN", Pattern: ">", IsRegex: false, LineNumber: 179, Alias: ""},
		grammartools.TokenDefinition{Name: "EQUALS", Pattern: "=", IsRegex: false, LineNumber: 180, Alias: ""},
		grammartools.TokenDefinition{Name: "QUESTION", Pattern: "?", IsRegex: false, LineNumber: 181, Alias: ""},
		grammartools.TokenDefinition{Name: "COLON", Pattern: ":", IsRegex: false, LineNumber: 182, Alias: ""},
		grammartools.TokenDefinition{Name: "LPAREN", Pattern: "(", IsRegex: false, LineNumber: 194, Alias: ""},
		grammartools.TokenDefinition{Name: "RPAREN", Pattern: ")", IsRegex: false, LineNumber: 195, Alias: ""},
		grammartools.TokenDefinition{Name: "LBRACKET", Pattern: "[", IsRegex: false, LineNumber: 196, Alias: ""},
		grammartools.TokenDefinition{Name: "RBRACKET", Pattern: "]", IsRegex: false, LineNumber: 197, Alias: ""},
		grammartools.TokenDefinition{Name: "LBRACE", Pattern: "{", IsRegex: false, LineNumber: 198, Alias: ""},
		grammartools.TokenDefinition{Name: "RBRACE", Pattern: "}", IsRegex: false, LineNumber: 199, Alias: ""},
		grammartools.TokenDefinition{Name: "SEMICOLON", Pattern: ";", IsRegex: false, LineNumber: 200, Alias: ""},
		grammartools.TokenDefinition{Name: "COMMA", Pattern: ",", IsRegex: false, LineNumber: 201, Alias: ""},
		grammartools.TokenDefinition{Name: "DOT", Pattern: ".", IsRegex: false, LineNumber: 202, Alias: ""},
		grammartools.TokenDefinition{Name: "HASH", Pattern: "#", IsRegex: false, LineNumber: 203, Alias: ""},
		grammartools.TokenDefinition{Name: "AT", Pattern: "@", IsRegex: false, LineNumber: 204, Alias: ""},
	},
	Keywords: []string{"always", "and", "assign", "begin", "buf", "case", "casex", "casez", "default", "defparam", "else", "end", "endcase", "endfunction", "endgenerate", "endmodule", "endtask", "for", "function", "generate", "genvar", "if", "initial", "inout", "input", "integer", "localparam", "module", "nand", "negedge", "nor", "not", "or", "output", "parameter", "posedge", "real", "reg", "signed", "supply0", "supply1", "task", "tri", "unsigned", "wire", "xnor", "xor", },
	SkipDefinitions: []grammartools.TokenDefinition{
		grammartools.TokenDefinition{Name: "LINE_COMMENT", Pattern: "\\/\\/[^\\n]*", IsRegex: true, LineNumber: 31, Alias: ""},
		grammartools.TokenDefinition{Name: "BLOCK_COMMENT", Pattern: "\\/\\*([^*]|\\*[^/])*\\*\\/", IsRegex: true, LineNumber: 32, Alias: ""},
		grammartools.TokenDefinition{Name: "WHITESPACE", Pattern: "[ \\t\\r\\n]+", IsRegex: true, LineNumber: 33, Alias: ""},
	},
}
