-- AUTO-GENERATED FILE — DO NOT EDIT
-- Source: excel.tokens
-- Regenerate with: grammar-tools compile-tokens excel.tokens
--
-- This file embeds a TokenGrammar as native Lua data structures.
-- Call token_grammar() instead of reading and parsing the .tokens file.

local gt = require("coding_adventures.grammar_tools")

local function token_grammar()
  local g = gt.TokenGrammar.new()
  g.definitions = {
        {
          name="SPACE",
          pattern=" +",
          is_regex=true,
          line_number=13,
          alias="",
        },
        {
          name="REF_PREFIX_QUOTED",
          pattern="(\\[[^\\]]+\\])?'([^']|'')*'!",
          is_regex=true,
          line_number=15,
          alias="REF_PREFIX",
        },
        {
          name="REF_PREFIX_WB_BARE",
          pattern="\\[[^\\]]+\\][A-Za-z_][A-Za-z0-9_.:]*!",
          is_regex=true,
          line_number=16,
          alias="REF_PREFIX",
        },
        {
          name="REF_PREFIX_BARE",
          pattern="[A-Za-z_][A-Za-z0-9_.:]*!",
          is_regex=true,
          line_number=17,
          alias="REF_PREFIX",
        },
        {
          name="STRING",
          pattern="\"([^\"]|\"\")*\"",
          is_regex=true,
          line_number=19,
          alias="",
        },
        {
          name="ERROR_CONSTANT",
          pattern="#[a-z0-9\\/\\?!]*[a-z0-9\\?!]",
          is_regex=true,
          line_number=20,
          alias="",
        },
        {
          name="NUMBER_DOT_EXP",
          pattern="\\.[0-9]+[eE][-+]?[0-9]+",
          is_regex=true,
          line_number=26,
          alias="NUMBER",
        },
        {
          name="NUMBER_DOT",
          pattern="\\.[0-9]+",
          is_regex=true,
          line_number=27,
          alias="NUMBER",
        },
        {
          name="NUMBER_EXP",
          pattern="[0-9]+\\.?[0-9]*[eE][-+]?[0-9]+",
          is_regex=true,
          line_number=28,
          alias="NUMBER",
        },
        {
          name="NUMBER",
          pattern="[0-9]+\\.?[0-9]*",
          is_regex=true,
          line_number=29,
          alias="",
        },
        {
          name="STRUCTURED_KEYWORD",
          pattern="\\[#[a-z ]+\\]",
          is_regex=true,
          line_number=31,
          alias="",
        },
        {
          name="STRUCTURED_COLUMN",
          pattern="\\[[^\\[\\]]+\\]",
          is_regex=true,
          line_number=32,
          alias="",
        },
        {
          name="CELL",
          pattern="\\$?[A-Za-z]{1,3}\\$?[0-9]{1,7}",
          is_regex=true,
          line_number=35,
          alias="",
        },
        {
          name="NOT_EQUALS",
          pattern="<>",
          is_regex=false,
          line_number=37,
          alias="",
        },
        {
          name="LESS_EQUALS",
          pattern="<=",
          is_regex=false,
          line_number=38,
          alias="",
        },
        {
          name="GREATER_EQUALS",
          pattern=">=",
          is_regex=false,
          line_number=39,
          alias="",
        },
        {
          name="PLUS",
          pattern="+",
          is_regex=false,
          line_number=41,
          alias="",
        },
        {
          name="MINUS",
          pattern="-",
          is_regex=false,
          line_number=42,
          alias="",
        },
        {
          name="STAR",
          pattern="*",
          is_regex=false,
          line_number=43,
          alias="",
        },
        {
          name="SLASH",
          pattern="/",
          is_regex=false,
          line_number=44,
          alias="",
        },
        {
          name="CARET",
          pattern="^",
          is_regex=false,
          line_number=45,
          alias="",
        },
        {
          name="AMP",
          pattern="&",
          is_regex=false,
          line_number=46,
          alias="",
        },
        {
          name="PERCENT",
          pattern="%",
          is_regex=false,
          line_number=47,
          alias="",
        },
        {
          name="EQUALS",
          pattern="=",
          is_regex=false,
          line_number=48,
          alias="",
        },
        {
          name="LESS_THAN",
          pattern="<",
          is_regex=false,
          line_number=49,
          alias="",
        },
        {
          name="GREATER_THAN",
          pattern=">",
          is_regex=false,
          line_number=50,
          alias="",
        },
        {
          name="BANG",
          pattern="!",
          is_regex=false,
          line_number=51,
          alias="",
        },
        {
          name="DOLLAR",
          pattern="$",
          is_regex=false,
          line_number=52,
          alias="",
        },
        {
          name="LPAREN",
          pattern="(",
          is_regex=false,
          line_number=53,
          alias="",
        },
        {
          name="RPAREN",
          pattern=")",
          is_regex=false,
          line_number=54,
          alias="",
        },
        {
          name="LBRACE",
          pattern="{",
          is_regex=false,
          line_number=55,
          alias="",
        },
        {
          name="RBRACE",
          pattern="}",
          is_regex=false,
          line_number=56,
          alias="",
        },
        {
          name="LBRACKET",
          pattern="[",
          is_regex=false,
          line_number=57,
          alias="",
        },
        {
          name="RBRACKET",
          pattern="]",
          is_regex=false,
          line_number=58,
          alias="",
        },
        {
          name="COMMA",
          pattern=",",
          is_regex=false,
          line_number=59,
          alias="",
        },
        {
          name="SEMICOLON",
          pattern=";",
          is_regex=false,
          line_number=60,
          alias="",
        },
        {
          name="COLON",
          pattern=":",
          is_regex=false,
          line_number=61,
          alias="",
        },
        {
          name="AT",
          pattern="@",
          is_regex=false,
          line_number=62,
          alias="",
        },
        {
          name="NAME",
          pattern="[A-Za-z_\\\\][A-Za-z0-9_\\.]*",
          is_regex=true,
          line_number=64,
          alias="",
        },
        {
          name="FUNCTION_NAME",
          pattern="[^\\s\\S]",
          is_regex=true,
          line_number=70,
          alias="",
        },
        {
          name="TABLE_NAME",
          pattern="[^\\s\\S]",
          is_regex=true,
          line_number=71,
          alias="",
        },
        {
          name="COLUMN_REF",
          pattern="[^\\s\\S]",
          is_regex=true,
          line_number=72,
          alias="",
        },
        {
          name="ROW_REF",
          pattern="[^\\s\\S]",
          is_regex=true,
          line_number=73,
          alias="",
        },
      }
  g.keywords = {"true", "false"}
  g.mode = ""
  g.escape_mode = ""
  g.skip_definitions = {
        {
          name="NONSPACE_WHITESPACE",
          pattern="[\\t\\r\\n]+",
          is_regex=true,
          line_number=11,
          alias="",
        },
      }
  g.reserved_keywords = {}
  g.context_keywords = {}
  g.layout_keywords = {}
  g.soft_keywords = {}
  g.error_definitions = {}
  g.groups = {}
  g.case_sensitive = true
  g.version = 0
  g.case_insensitive = false
  return g
end

return { token_grammar = token_grammar }
