// AUTO-GENERATED FILE - DO NOT EDIT
// Source: code/grammars/mosaic/mosaic.tokens
// Regenerate with: grammar-tools compile-tokens <source.tokens>
import 'package:coding_adventures_grammar_tools/grammar_tools.dart';

final tokenGrammar = TokenGrammar(
  version: 1,
  caseInsensitive: false,
  definitions: [
    TokenDefinition(
      name: "STRING",
      pattern: "\"([^\"\\\\\\n]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 23,
      alias: null,
    ),
    TokenDefinition(
      name: "DIMENSION",
      pattern: "-?[0-9]*\\.?[0-9]+[a-zA-Z%]+",
      isRegex: true,
      lineNumber: 31,
      alias: null,
    ),
    TokenDefinition(
      name: "NUMBER",
      pattern: "-?[0-9]*\\.?[0-9]+",
      isRegex: true,
      lineNumber: 32,
      alias: null,
    ),
    TokenDefinition(
      name: "COLOR_HEX",
      pattern: "#[0-9a-fA-F]{3,8}",
      isRegex: true,
      lineNumber: 39,
      alias: null,
    ),
    TokenDefinition(
      name: "NAME",
      pattern: "[a-zA-Z_][a-zA-Z0-9_-]*",
      isRegex: true,
      lineNumber: 70,
      alias: null,
    ),
    TokenDefinition(
      name: "LBRACE",
      pattern: "{",
      isRegex: false,
      lineNumber: 76,
      alias: null,
    ),
    TokenDefinition(
      name: "RBRACE",
      pattern: "}",
      isRegex: false,
      lineNumber: 77,
      alias: null,
    ),
    TokenDefinition(
      name: "LANGLE",
      pattern: "<",
      isRegex: false,
      lineNumber: 78,
      alias: null,
    ),
    TokenDefinition(
      name: "RANGLE",
      pattern: ">",
      isRegex: false,
      lineNumber: 79,
      alias: null,
    ),
    TokenDefinition(
      name: "COLON",
      pattern: ":",
      isRegex: false,
      lineNumber: 80,
      alias: null,
    ),
    TokenDefinition(
      name: "SEMICOLON",
      pattern: ";",
      isRegex: false,
      lineNumber: 81,
      alias: null,
    ),
    TokenDefinition(
      name: "COMMA",
      pattern: ",",
      isRegex: false,
      lineNumber: 82,
      alias: null,
    ),
    TokenDefinition(
      name: "DOT",
      pattern: ".",
      isRegex: false,
      lineNumber: 83,
      alias: null,
    ),
    TokenDefinition(
      name: "EQUALS",
      pattern: "=",
      isRegex: false,
      lineNumber: 84,
      alias: null,
    ),
    TokenDefinition(
      name: "AT",
      pattern: "@",
      isRegex: false,
      lineNumber: 85,
      alias: null,
    ),
  ],
  keywords: [
    "component",
    "slot",
    "import",
    "from",
    "as",
    "text",
    "number",
    "bool",
    "image",
    "color",
    "node",
    "list",
    "true",
    "false",
    "when",
    "each",
  ],
  mode: null,
  skipDefinitions: [
    TokenDefinition(
      name: "LINE_COMMENT",
      pattern: "\\/\\/[^\\n]*",
      isRegex: true,
      lineNumber: 15,
      alias: null,
    ),
    TokenDefinition(
      name: "BLOCK_COMMENT",
      pattern: "\\/\\*[\\s\\S]*?\\*\\/",
      isRegex: true,
      lineNumber: 16,
      alias: null,
    ),
    TokenDefinition(
      name: "WHITESPACE",
      pattern: "[ \\t\\r\\n]+",
      isRegex: true,
      lineNumber: 17,
      alias: null,
    ),
  ],
  reservedKeywords: const [],
  escapeMode: "standard",
  errorDefinitions: const [],
  groups: const {},
  caseSensitive: true,
  layoutKeywords: const [],
  contextKeywords: const [],
  softKeywords: const [],
);
