-- AUTO-GENERATED FILE — DO NOT EDIT
-- Source: ts1.0.tokens
-- Regenerate with: grammar-tools compile-tokens ts1.0.tokens
--
-- This file embeds a TokenGrammar as native Lua data structures.
-- Call token_grammar() instead of reading and parsing the .tokens file.

local gt = require("coding_adventures.grammar_tools")

local function token_grammar()
  local g = gt.TokenGrammar.new()
  g.definitions = {
        {
          name="NAME",
          pattern="[a-zA-Z_$][a-zA-Z0-9_$]*",
          is_regex=true,
          line_number=49,
          alias="",
        },
        {
          name="HEX_NUMBER",
          pattern="0[xX][0-9a-fA-F]+",
          is_regex=true,
          line_number=55,
          alias="NUMBER",
        },
        {
          name="FLOAT_NUMBER",
          pattern="[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?",
          is_regex=true,
          line_number=56,
          alias="NUMBER",
        },
        {
          name="LEADING_DOT_FLOAT",
          pattern="\\.[0-9]+([eE][+-]?[0-9]+)?",
          is_regex=true,
          line_number=57,
          alias="NUMBER",
        },
        {
          name="SCI_NUMBER",
          pattern="[0-9]+[eE][+-]?[0-9]+",
          is_regex=true,
          line_number=58,
          alias="NUMBER",
        },
        {
          name="INT_NUMBER",
          pattern="[0-9]+",
          is_regex=true,
          line_number=59,
          alias="NUMBER",
        },
        {
          name="STRING_DQ",
          pattern="\"([^\"\\\\]|\\\\.)*\"",
          is_regex=true,
          line_number=65,
          alias="STRING",
        },
        {
          name="STRING_SQ",
          pattern="'([^'\\\\]|\\\\.)*'",
          is_regex=true,
          line_number=66,
          alias="STRING",
        },
        {
          name="REGEX",
          pattern="\\/([^\\/\\\\\\n]|\\\\.)+\\/[gim]*",
          is_regex=true,
          line_number=71,
          alias="",
        },
        {
          name="STRICT_EQUALS",
          pattern="===",
          is_regex=false,
          line_number=85,
          alias="",
        },
        {
          name="STRICT_NOT_EQUALS",
          pattern="!==",
          is_regex=false,
          line_number=86,
          alias="",
        },
        {
          name="UNSIGNED_RIGHT_SHIFT_EQUALS",
          pattern=">>>=",
          is_regex=false,
          line_number=87,
          alias="",
        },
        {
          name="UNSIGNED_RIGHT_SHIFT",
          pattern=">>>",
          is_regex=false,
          line_number=88,
          alias="",
        },
        {
          name="LEFT_SHIFT_EQUALS",
          pattern="<<=",
          is_regex=false,
          line_number=89,
          alias="",
        },
        {
          name="RIGHT_SHIFT_EQUALS",
          pattern=">>=",
          is_regex=false,
          line_number=90,
          alias="",
        },
        {
          name="EQUALS_EQUALS",
          pattern="==",
          is_regex=false,
          line_number=91,
          alias="",
        },
        {
          name="NOT_EQUALS",
          pattern="!=",
          is_regex=false,
          line_number=92,
          alias="",
        },
        {
          name="LESS_EQUALS",
          pattern="<=",
          is_regex=false,
          line_number=93,
          alias="",
        },
        {
          name="GREATER_EQUALS",
          pattern=">=",
          is_regex=false,
          line_number=94,
          alias="",
        },
        {
          name="PLUS_EQUALS",
          pattern="+=",
          is_regex=false,
          line_number=95,
          alias="",
        },
        {
          name="MINUS_EQUALS",
          pattern="-=",
          is_regex=false,
          line_number=96,
          alias="",
        },
        {
          name="STAR_EQUALS",
          pattern="*=",
          is_regex=false,
          line_number=97,
          alias="",
        },
        {
          name="SLASH_EQUALS",
          pattern="/=",
          is_regex=false,
          line_number=98,
          alias="",
        },
        {
          name="PERCENT_EQUALS",
          pattern="%=",
          is_regex=false,
          line_number=99,
          alias="",
        },
        {
          name="AMPERSAND_EQUALS",
          pattern="&=",
          is_regex=false,
          line_number=100,
          alias="",
        },
        {
          name="PIPE_EQUALS",
          pattern="|=",
          is_regex=false,
          line_number=101,
          alias="",
        },
        {
          name="CARET_EQUALS",
          pattern="^=",
          is_regex=false,
          line_number=102,
          alias="",
        },
        {
          name="LEFT_SHIFT",
          pattern="<<",
          is_regex=false,
          line_number=103,
          alias="",
        },
        {
          name="RIGHT_SHIFT",
          pattern=">>",
          is_regex=false,
          line_number=104,
          alias="",
        },
        {
          name="AND_AND",
          pattern="&&",
          is_regex=false,
          line_number=105,
          alias="",
        },
        {
          name="OR_OR",
          pattern="||",
          is_regex=false,
          line_number=106,
          alias="",
        },
        {
          name="PLUS_PLUS",
          pattern="++",
          is_regex=false,
          line_number=107,
          alias="",
        },
        {
          name="MINUS_MINUS",
          pattern="--",
          is_regex=false,
          line_number=108,
          alias="",
        },
        {
          name="ARROW",
          pattern="=>",
          is_regex=false,
          line_number=123,
          alias="",
        },
        {
          name="ELLIPSIS",
          pattern="...",
          is_regex=false,
          line_number=124,
          alias="",
        },
        {
          name="EQUALS",
          pattern="=",
          is_regex=false,
          line_number=141,
          alias="",
        },
        {
          name="PLUS",
          pattern="+",
          is_regex=false,
          line_number=142,
          alias="",
        },
        {
          name="MINUS",
          pattern="-",
          is_regex=false,
          line_number=143,
          alias="",
        },
        {
          name="STAR",
          pattern="*",
          is_regex=false,
          line_number=144,
          alias="",
        },
        {
          name="SLASH",
          pattern="/",
          is_regex=false,
          line_number=145,
          alias="",
        },
        {
          name="PERCENT",
          pattern="%",
          is_regex=false,
          line_number=146,
          alias="",
        },
        {
          name="LESS_THAN",
          pattern="<",
          is_regex=false,
          line_number=147,
          alias="",
        },
        {
          name="GREATER_THAN",
          pattern=">",
          is_regex=false,
          line_number=148,
          alias="",
        },
        {
          name="BANG",
          pattern="!",
          is_regex=false,
          line_number=149,
          alias="",
        },
        {
          name="AMPERSAND",
          pattern="&",
          is_regex=false,
          line_number=150,
          alias="",
        },
        {
          name="PIPE",
          pattern="|",
          is_regex=false,
          line_number=151,
          alias="",
        },
        {
          name="CARET",
          pattern="^",
          is_regex=false,
          line_number=152,
          alias="",
        },
        {
          name="TILDE",
          pattern="~",
          is_regex=false,
          line_number=153,
          alias="",
        },
        {
          name="QUESTION",
          pattern="?",
          is_regex=false,
          line_number=154,
          alias="",
        },
        {
          name="AT",
          pattern="@",
          is_regex=false,
          line_number=157,
          alias="",
        },
        {
          name="LPAREN",
          pattern="(",
          is_regex=false,
          line_number=163,
          alias="",
        },
        {
          name="RPAREN",
          pattern=")",
          is_regex=false,
          line_number=164,
          alias="",
        },
        {
          name="LBRACE",
          pattern="{",
          is_regex=false,
          line_number=165,
          alias="",
        },
        {
          name="RBRACE",
          pattern="}",
          is_regex=false,
          line_number=166,
          alias="",
        },
        {
          name="LBRACKET",
          pattern="[",
          is_regex=false,
          line_number=167,
          alias="",
        },
        {
          name="RBRACKET",
          pattern="]",
          is_regex=false,
          line_number=168,
          alias="",
        },
        {
          name="SEMICOLON",
          pattern=";",
          is_regex=false,
          line_number=169,
          alias="",
        },
        {
          name="COMMA",
          pattern=",",
          is_regex=false,
          line_number=170,
          alias="",
        },
        {
          name="COLON",
          pattern=":",
          is_regex=false,
          line_number=171,
          alias="",
        },
        {
          name="DOT",
          pattern=".",
          is_regex=false,
          line_number=172,
          alias="",
        },
      }
  g.keywords = {"break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "finally", "for", "function", "if", "import", "in", "instanceof", "new", "return", "super", "switch", "this", "throw", "try", "typeof", "var", "void", "while", "with", "true", "false", "null"}
  g.mode = ""
  g.escape_mode = ""
  g.skip_definitions = {
        {
          name="WHITESPACE",
          pattern="[ \\t\\r\\n\\v\\f]+",
          is_regex=true,
          line_number=323,
          alias="",
        },
        {
          name="LINE_COMMENT",
          pattern="\\/\\/[^\\n]*",
          is_regex=true,
          line_number=324,
          alias="",
        },
        {
          name="BLOCK_COMMENT",
          pattern="\\/\\*([^*]|\\*[^\\/])*\\*\\/",
          is_regex=true,
          line_number=325,
          alias="",
        },
      }
  g.reserved_keywords = {}
  g.context_keywords = {"get", "set", "type", "interface", "namespace", "module", "declare", "abstract", "readonly", "is", "keyof", "asserts", "unique"}
  g.layout_keywords = {}
  g.soft_keywords = {}
  g.error_definitions = {
        {
          name="BAD_STRING_DQ",
          pattern="\"[^\"]*$",
          is_regex=true,
          line_number=332,
          alias="",
        },
        {
          name="BAD_STRING_SQ",
          pattern="'[^']*$",
          is_regex=true,
          line_number=333,
          alias="",
        },
        {
          name="BAD_REGEX",
          pattern="\\/([^\\/\\\\\\n]|\\\\.)*$",
          is_regex=true,
          line_number=334,
          alias="",
        },
      }
  g.groups = {}
  g.case_sensitive = true
  g.version = 0
  g.case_insensitive = false
  return g
end

return { token_grammar = token_grammar }
