// AUTO-GENERATED FILE — DO NOT EDIT
// Source: r.tokens
// Regenerate with: grammar-tools compile-tokens r.tokens
//
// This file embeds a TokenGrammar as native Rust data structures.
// Call `token_grammar()` instead of reading and parsing the .tokens file.

#[allow(unused_imports)]
use grammar_tools::token_grammar::{
    ModeTransition, PatternGroup, TokenDefinition, TokenGrammar, TransitionAction,
};
#[allow(unused_imports)]
use std::collections::HashMap;

pub fn token_grammar() -> TokenGrammar {
    TokenGrammar {
        definitions: vec![
            TokenDefinition {
                name: r#"SUPER_ASSIGN"#.to_string(),
                pattern: r#"<<-"#.to_string(),
                is_regex: false,
                line_number: 30,
                alias: None,
            },
            TokenDefinition {
                name: r#"ASSIGN"#.to_string(),
                pattern: r#"<-"#.to_string(),
                is_regex: false,
                line_number: 31,
                alias: None,
            },
            TokenDefinition {
                name: r#"LE"#.to_string(),
                pattern: r#"<="#.to_string(),
                is_regex: false,
                line_number: 32,
                alias: None,
            },
            TokenDefinition {
                name: r#"GE"#.to_string(),
                pattern: r#">="#.to_string(),
                is_regex: false,
                line_number: 33,
                alias: None,
            },
            TokenDefinition {
                name: r#"EQEQ"#.to_string(),
                pattern: r#"=="#.to_string(),
                is_regex: false,
                line_number: 34,
                alias: None,
            },
            TokenDefinition {
                name: r#"NE"#.to_string(),
                pattern: r#"!="#.to_string(),
                is_regex: false,
                line_number: 35,
                alias: None,
            },
            TokenDefinition {
                name: r#"RIGHT_SUPER_ASSIGN"#.to_string(),
                pattern: r#"->>"#.to_string(),
                is_regex: false,
                line_number: 36,
                alias: None,
            },
            TokenDefinition {
                name: r#"RIGHT_ASSIGN"#.to_string(),
                pattern: r#"->"#.to_string(),
                is_regex: false,
                line_number: 37,
                alias: None,
            },
            TokenDefinition {
                name: r#"PIPE_OP"#.to_string(),
                pattern: r#"|>"#.to_string(),
                is_regex: false,
                line_number: 41,
                alias: None,
            },
            TokenDefinition {
                name: r#"PERCENT_OP"#.to_string(),
                pattern: r#"%[^%]*%"#.to_string(),
                is_regex: true,
                line_number: 45,
                alias: None,
            },
            TokenDefinition {
                name: r#"HEX_LIT"#.to_string(),
                pattern: r#"0[xX][0-9a-fA-F]+L?"#.to_string(),
                is_regex: true,
                line_number: 63,
                alias: None,
            },
            TokenDefinition {
                name: r#"COMPLEX_LIT"#.to_string(),
                pattern: r#"[0-9]*\.?[0-9]+([eE][+-]?[0-9]+)?i"#.to_string(),
                is_regex: true,
                line_number: 64,
                alias: None,
            },
            TokenDefinition {
                name: r#"INT_LIT"#.to_string(),
                pattern: r#"[0-9]*\.?[0-9]+([eE][+-]?[0-9]+)?L"#.to_string(),
                is_regex: true,
                line_number: 65,
                alias: None,
            },
            TokenDefinition {
                name: r#"NUMBER"#.to_string(),
                pattern: r#"[0-9]*\.?[0-9]+([eE][+-]?[0-9]+)?"#.to_string(),
                is_regex: true,
                line_number: 66,
                alias: None,
            },
            TokenDefinition {
                name: r#"DQ_STRING"#.to_string(),
                pattern: r#""[^"]*""#.to_string(),
                is_regex: true,
                line_number: 72,
                alias: Some(r#"STRING"#.to_string()),
            },
            TokenDefinition {
                name: r#"SQ_STRING"#.to_string(),
                pattern: r#"'[^']*'"#.to_string(),
                is_regex: true,
                line_number: 73,
                alias: Some(r#"STRING"#.to_string()),
            },
            TokenDefinition {
                name: r#"NAME"#.to_string(),
                pattern: r#"[A-Za-z.][A-Za-z0-9._]*"#.to_string(),
                is_regex: true,
                line_number: 85,
                alias: None,
            },
            TokenDefinition {
                name: r#"LT"#.to_string(),
                pattern: r#"<"#.to_string(),
                is_regex: false,
                line_number: 119,
                alias: None,
            },
            TokenDefinition {
                name: r#"GT"#.to_string(),
                pattern: r#">"#.to_string(),
                is_regex: false,
                line_number: 120,
                alias: None,
            },
            TokenDefinition {
                name: r#"EQ"#.to_string(),
                pattern: r#"="#.to_string(),
                is_regex: false,
                line_number: 121,
                alias: None,
            },
            TokenDefinition {
                name: r#"PLUS"#.to_string(),
                pattern: r#"+"#.to_string(),
                is_regex: false,
                line_number: 122,
                alias: None,
            },
            TokenDefinition {
                name: r#"MINUS"#.to_string(),
                pattern: r#"-"#.to_string(),
                is_regex: false,
                line_number: 123,
                alias: None,
            },
            TokenDefinition {
                name: r#"STAR"#.to_string(),
                pattern: r#"*"#.to_string(),
                is_regex: false,
                line_number: 124,
                alias: None,
            },
            TokenDefinition {
                name: r#"SLASH"#.to_string(),
                pattern: r#"/"#.to_string(),
                is_regex: false,
                line_number: 125,
                alias: None,
            },
            TokenDefinition {
                name: r#"CARET"#.to_string(),
                pattern: r#"^"#.to_string(),
                is_regex: false,
                line_number: 126,
                alias: None,
            },
            TokenDefinition {
                name: r#"COLON"#.to_string(),
                pattern: r#":"#.to_string(),
                is_regex: false,
                line_number: 127,
                alias: None,
            },
            TokenDefinition {
                name: r#"BACKSLASH"#.to_string(),
                pattern: r#"\\"#.to_string(),
                is_regex: true,
                line_number: 129,
                alias: None,
            },
            TokenDefinition {
                name: r#"LPAREN"#.to_string(),
                pattern: r#"("#.to_string(),
                is_regex: false,
                line_number: 130,
                alias: None,
            },
            TokenDefinition {
                name: r#"RPAREN"#.to_string(),
                pattern: r#")"#.to_string(),
                is_regex: false,
                line_number: 131,
                alias: None,
            },
            TokenDefinition {
                name: r#"LBRACE"#.to_string(),
                pattern: r#"{"#.to_string(),
                is_regex: false,
                line_number: 132,
                alias: None,
            },
            TokenDefinition {
                name: r#"RBRACE"#.to_string(),
                pattern: r#"}"#.to_string(),
                is_regex: false,
                line_number: 133,
                alias: None,
            },
            TokenDefinition {
                name: r#"LBRACKET"#.to_string(),
                pattern: r#"["#.to_string(),
                is_regex: false,
                line_number: 134,
                alias: None,
            },
            TokenDefinition {
                name: r#"RBRACKET"#.to_string(),
                pattern: r#"]"#.to_string(),
                is_regex: false,
                line_number: 135,
                alias: None,
            },
            TokenDefinition {
                name: r#"COMMA"#.to_string(),
                pattern: r#","#.to_string(),
                is_regex: false,
                line_number: 136,
                alias: None,
            },
            TokenDefinition {
                name: r#"SEMICOLON"#.to_string(),
                pattern: r#";"#.to_string(),
                is_regex: false,
                line_number: 137,
                alias: None,
            },
            TokenDefinition {
                name: r#"DOLLAR"#.to_string(),
                pattern: r#"$"#.to_string(),
                is_regex: false,
                line_number: 138,
                alias: None,
            },
            TokenDefinition {
                name: r#"NEWLINE"#.to_string(),
                pattern: r#"\r?\n"#.to_string(),
                is_regex: true,
                line_number: 148,
                alias: None,
            },
        ],
        keywords: vec![
            r#"if"#.to_string(),
            r#"else"#.to_string(),
            r#"for"#.to_string(),
            r#"while"#.to_string(),
            r#"repeat"#.to_string(),
            r#"function"#.to_string(),
            r#"break"#.to_string(),
            r#"next"#.to_string(),
            r#"in"#.to_string(),
            r#"TRUE"#.to_string(),
            r#"FALSE"#.to_string(),
            r#"T"#.to_string(),
            r#"F"#.to_string(),
            r#"NULL"#.to_string(),
            r#"NA"#.to_string(),
            r#"NA_integer_"#.to_string(),
            r#"NA_real_"#.to_string(),
            r#"NA_character_"#.to_string(),
            r#"Inf"#.to_string(),
            r#"NaN"#.to_string(),
        ],
        mode: None,
        skip_definitions: vec![
            TokenDefinition {
                name: r#"WHITESPACE"#.to_string(),
                pattern: r#"[ \t]+"#.to_string(),
                is_regex: true,
                line_number: 155,
                alias: None,
            },
            TokenDefinition {
                name: r#"COMMENT"#.to_string(),
                pattern: r#"#[^\n]*"#.to_string(),
                is_regex: true,
                line_number: 156,
                alias: None,
            },
        ],
        reserved_keywords: vec![],
        escapes: None,
        error_definitions: vec![TokenDefinition {
            name: r#"UNKNOWN"#.to_string(),
            pattern: r#"."#.to_string(),
            is_regex: true,
            line_number: 163,
            alias: None,
        }],
        groups: HashMap::new(),
        case_sensitive: true,
        version: 0,
        case_insensitive: false,
        context_keywords: vec![],
        soft_keywords: vec![],
        layout_keywords: vec![],
        start_mode: None,
        transitions: vec![],
    }
}
