// ContentView.swift — the VisiCalc UI host shell (VC2-swiftui), computing on
// the shared Rust spreadsheet engine through its C ABI.
//
// The grid and formula bar are the auto-generated mosaic views (GridView /
// FormulaBarView from `bash scripts/build.sh`). The formula bar is now a
// genuinely EDITABLE TextField (the SwiftUI emitter lowers an input with an
// `onChange` handler to a writable `Binding`): type a value or a formula and
// press Enter, and the edit goes through `model.setSelected`, which writes to
// the Rust engine and recomputes. Cell selection uses arrow buttons (the
// generated GridView is display-only — it renders the engine's values and the
// selection highlight, but emits no tap events).

import SwiftUI

struct ContentView: View {
    @StateObject private var model = SpreadsheetModel()
    // The engine-backed model for the virtualized infinite-sheet view.
    @StateObject private var windowed = WindowedSheetModel()
    // Which view is on screen: the fixed 5×5 parity grid, or the infinite sheet.
    @State private var showInfinite = false
    // The formula bar's text. Bound as the FormulaBarView's `formula` input, so
    // it reflects keystrokes; synced to the selected cell's source on select.
    @State private var formulaText: String = ""

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            HStack {
                Text("VISICALC · MOSAIC SWIFTUI DEMO · RUST ENGINE")
                    .font(.system(size: 11))
                    .tracking(1.0)
                    .foregroundColor(Color(hex: 0x9D9D9D))
                    // On a narrow phone the title would otherwise be wider than
                    // the screen; shrink/truncate it rather than force the whole
                    // VStack wide (which clips both edges).
                    .lineLimit(1)
                    .minimumScaleFactor(0.6)
                Spacer()
                // Flip between the 5×5 parity grid and the virtualized infinite
                // sheet — both compute on the same Rust engine; the infinite one
                // adds the viewport primitive (windowed reads).
                Button(showInfinite ? "‹ 5×5 grid" : "Infinite sheet ›") {
                    showInfinite.toggle()
                }
                .font(.system(size: 11, design: .monospaced))
            }
            .padding([.top, .leading, .trailing], 16)
            .padding(.bottom, 8)

            if showInfinite {
                InfiniteGridView(model: windowed)
                    .padding([.leading, .trailing, .bottom], 16)
            } else {
            // FormulaBar — generated by mosaic-compile; now editable. Typing
            // dispatches .formulaChange; Enter dispatches .commit.
            FormulaBarView(
                cellAddress: model.selectedAddress,
                formula: formulaText,
                readOnly: false,
                dispatch: handleFormulaBarEvent
            )

            // Grid — generated by mosaic-compile, rendered from the engine's
            // computed values. The grid is a fixed 528pt wide (48 + 5×96); on a
            // phone that's wider than the screen, so wrap it in a horizontal
            // ScrollView there (it would otherwise force the whole VStack wider
            // than the display and clip the title / nav row on both edges). On
            // the desktop the 720pt window already fits it, so render directly.
            #if os(iOS)
            ScrollView(.horizontal, showsIndicators: true) {
                parityGrid
            }
            .padding([.leading, .trailing, .top], 16)
            #else
            parityGrid
                .padding([.leading, .trailing, .top], 16)
            #endif

            // Selection controls (the generated GridView emits no tap events).
            navControls
                .padding(16)
            } // end: parity-grid branch

            Spacer()
        }
        // Desktop is a fixed-width window; on a phone we fill the full width so
        // the (vertically-stacked, touch-layout) formula bar and grid use the
        // whole screen instead of being pinned to a 720pt column.
        #if os(iOS)
        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
        #else
        .frame(maxWidth: 720, maxHeight: .infinity, alignment: .topLeading)
        #endif
        .background(Color(hex: 0x1E1E1E))
        .preferredColorScheme(.dark)
        .onAppear { formulaText = model.selectedRaw }
    }

    // The fixed 5×5 parity grid (generated by mosaic-compile), rendered from the
    // engine's computed values. Extracted so the iOS branch can wrap it in a
    // horizontal ScrollView without duplicating the argument list.
    private var parityGrid: some View {
        GridView(
            columnHeaders: ["", "A", "B", "C", "D", "E"],
            viewportRows: model.viewportRows,
            columnWidths: [48, 96, 96, 96, 96, 96],
            totalHeight: 0,
            selectedRow: model.selectedRow,
            selectedCol: model.selectedCol,
            editRow: -1,
            editCol: -1,
            editContent: "",
            dispatch: { _ in }
        )
    }

    private var navControls: some View {
        VStack(alignment: .leading, spacing: 6) {
            HStack(spacing: 6) {
                Text("Move:")
                    .font(.system(size: 11))
                    .foregroundColor(Color(hex: 0x6D6D6D))
                navButton("◀") { move(0, -1) }
                navButton("▲") { move(-1, 0) }
                navButton("▼") { move(1, 0) }
                navButton("▶") { move(0, 1) }
                Text("Selected: \(model.selectedAddress)")
                    .font(.system(size: 11, design: .monospaced))
                    .foregroundColor(Color(hex: 0x9D9D9D))
            }
            Text("Edit the formula bar above (e.g. 100 or =SUM(A1:A4)) and press Enter — every dependent cell recomputes on the Rust engine.")
                .font(.system(size: 10))
                .foregroundColor(Color(hex: 0x6D6D6D))
        }
    }

    private func navButton(_ label: String, _ action: @escaping () -> Void) -> some View {
        Button(label, action: action).font(.system(size: 12, design: .monospaced))
    }

    private func move(_ dr: Int, _ dc: Int) {
        model.select(row: Int(model.selectedRow) + dr, col: Int(model.selectedCol) + dc)
        formulaText = model.selectedRaw // show the newly-selected cell's source
    }

    private func handleFormulaBarEvent(_ event: FormulaBarEvent) {
        switch event {
        case .formulaChange(let value):
            // Per-keystroke: keep the field's text in sync.
            formulaText = value
        case .commit:
            // Enter: write the edit to the engine and recompute, then show the
            // cell's (possibly canonicalised) source.
            model.setSelected(formulaText)
            formulaText = model.selectedRaw
        case .cancel:
            // Esc: discard the edit, restore the cell's source.
            formulaText = model.selectedRaw
        }
    }
}

// Helper init for hex colours so we don't have to write
// `Color(red:, green:, blue:)` everywhere.
extension Color {
    init(hex: UInt32) {
        let r = Double((hex >> 16) & 0xFF) / 255.0
        let g = Double((hex >> 8) & 0xFF) / 255.0
        let b = Double(hex & 0xFF) / 255.0
        self.init(red: r, green: g, blue: b)
    }
}
