# AUTO-GENERATED FILE — DO NOT EDIT
# Source: java10.tokens
# Regenerate with: perl code/programs/perl/grammar-tools/grammar-tools.pl compile-tokens java10.tokens
#
# This file embeds a TokenGrammar as native Perl data structures.
# Call token_grammar() instead of reading and parsing the .tokens file.

package CodingAdventures::JavaLexer::_Grammar_10;
use strict;
use warnings;

sub token_grammar {
    return bless {
        definitions => [
            bless({
                name => 'NAME',
                pattern => '[a-zA-Z_$][a-zA-Z0-9_$]*',
                is_regex => 1,
                line_number => 101,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BINARY_NUMBER',
                pattern => '0[bB][01][01_]*[01][lL]?',
                is_regex => 1,
                line_number => 143,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BINARY_SHORT',
                pattern => '0[bB][01][lL]?',
                is_regex => 1,
                line_number => 144,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'HEX_NUMBER',
                pattern => '0[xX][0-9a-fA-F][0-9a-fA-F_]*[0-9a-fA-F][lL]?',
                is_regex => 1,
                line_number => 145,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'HEX_SHORT',
                pattern => '0[xX][0-9a-fA-F][lL]?',
                is_regex => 1,
                line_number => 146,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'OCTAL_NUMBER',
                pattern => '0[0-7_]*[0-7]+[lL]?',
                is_regex => 1,
                line_number => 147,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOAT_NUMBER',
                pattern => '[0-9][0-9_]*\\.[0-9_]*([eE][+-]?[0-9_]+)?[fFdD]?',
                is_regex => 1,
                line_number => 148,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEADING_DOT_FLOAT',
                pattern => '\\.[0-9][0-9_]*([eE][+-]?[0-9_]+)?[fFdD]?',
                is_regex => 1,
                line_number => 149,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SCI_NUMBER',
                pattern => '[0-9][0-9_]*[eE][+-]?[0-9_]+[fFdD]?',
                is_regex => 1,
                line_number => 150,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LONG_NUMBER',
                pattern => '[0-9][0-9_]*[lL]',
                is_regex => 1,
                line_number => 151,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOAT_SUFFIX',
                pattern => '[0-9][0-9_]*[fFdD]',
                is_regex => 1,
                line_number => 152,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'INT_NUMBER',
                pattern => '[0-9][0-9_]*',
                is_regex => 1,
                line_number => 153,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING',
                pattern => '"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 174,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'CHAR',
                pattern => '\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 175,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'ELLIPSIS',
                pattern => '...',
                is_regex => 0,
                line_number => 205,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'ARROW',
                pattern => '->',
                is_regex => 0,
                line_number => 206,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'DOUBLE_COLON',
                pattern => '::',
                is_regex => 0,
                line_number => 207,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'UNSIGNED_RIGHT_SHIFT_EQUALS',
                pattern => '>>>=',
                is_regex => 0,
                line_number => 208,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'UNSIGNED_RIGHT_SHIFT',
                pattern => '>>>',
                is_regex => 0,
                line_number => 209,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEFT_SHIFT_EQUALS',
                pattern => '<<=',
                is_regex => 0,
                line_number => 210,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RIGHT_SHIFT_EQUALS',
                pattern => '>>=',
                is_regex => 0,
                line_number => 211,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'EQUALS_EQUALS',
                pattern => '==',
                is_regex => 0,
                line_number => 212,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NOT_EQUALS',
                pattern => '!=',
                is_regex => 0,
                line_number => 213,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LESS_EQUALS',
                pattern => '<=',
                is_regex => 0,
                line_number => 214,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'GREATER_EQUALS',
                pattern => '>=',
                is_regex => 0,
                line_number => 215,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AND_AND',
                pattern => '&&',
                is_regex => 0,
                line_number => 216,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'OR_OR',
                pattern => '||',
                is_regex => 0,
                line_number => 217,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS_PLUS',
                pattern => '++',
                is_regex => 0,
                line_number => 218,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS_MINUS',
                pattern => '--',
                is_regex => 0,
                line_number => 219,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS_EQUALS',
                pattern => '+=',
                is_regex => 0,
                line_number => 220,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS_EQUALS',
                pattern => '-=',
                is_regex => 0,
                line_number => 221,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STAR_EQUALS',
                pattern => '*=',
                is_regex => 0,
                line_number => 222,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SLASH_EQUALS',
                pattern => '/=',
                is_regex => 0,
                line_number => 223,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PERCENT_EQUALS',
                pattern => '%=',
                is_regex => 0,
                line_number => 224,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AMPERSAND_EQUALS',
                pattern => '&=',
                is_regex => 0,
                line_number => 225,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PIPE_EQUALS',
                pattern => '|=',
                is_regex => 0,
                line_number => 226,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'CARET_EQUALS',
                pattern => '^=',
                is_regex => 0,
                line_number => 227,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEFT_SHIFT',
                pattern => '<<',
                is_regex => 0,
                line_number => 228,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RIGHT_SHIFT',
                pattern => '>>',
                is_regex => 0,
                line_number => 229,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AT',
                pattern => '@',
                is_regex => 0,
                line_number => 243,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'EQUALS',
                pattern => '=',
                is_regex => 0,
                line_number => 244,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS',
                pattern => '+',
                is_regex => 0,
                line_number => 245,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS',
                pattern => '-',
                is_regex => 0,
                line_number => 246,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STAR',
                pattern => '*',
                is_regex => 0,
                line_number => 247,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SLASH',
                pattern => '/',
                is_regex => 0,
                line_number => 248,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PERCENT',
                pattern => '%',
                is_regex => 0,
                line_number => 249,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LESS_THAN',
                pattern => '<',
                is_regex => 0,
                line_number => 250,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'GREATER_THAN',
                pattern => '>',
                is_regex => 0,
                line_number => 251,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BANG',
                pattern => '!',
                is_regex => 0,
                line_number => 252,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AMPERSAND',
                pattern => '&',
                is_regex => 0,
                line_number => 253,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PIPE',
                pattern => '|',
                is_regex => 0,
                line_number => 254,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'CARET',
                pattern => '^',
                is_regex => 0,
                line_number => 255,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'TILDE',
                pattern => '~',
                is_regex => 0,
                line_number => 256,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'QUESTION',
                pattern => '?',
                is_regex => 0,
                line_number => 257,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LPAREN',
                pattern => '(',
                is_regex => 0,
                line_number => 266,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RPAREN',
                pattern => ')',
                is_regex => 0,
                line_number => 267,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LBRACE',
                pattern => '{',
                is_regex => 0,
                line_number => 268,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RBRACE',
                pattern => '}',
                is_regex => 0,
                line_number => 269,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LBRACKET',
                pattern => '[',
                is_regex => 0,
                line_number => 270,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RBRACKET',
                pattern => ']',
                is_regex => 0,
                line_number => 271,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SEMICOLON',
                pattern => ';',
                is_regex => 0,
                line_number => 272,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COMMA',
                pattern => ',',
                is_regex => 0,
                line_number => 273,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'DOT',
                pattern => '.',
                is_regex => 0,
                line_number => 274,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COLON',
                pattern => ':',
                is_regex => 0,
                line_number => 275,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        keywords => [
            'abstract',
            'assert',
            'boolean',
            'break',
            'byte',
            'case',
            'catch',
            'char',
            'class',
            'continue',
            'default',
            'do',
            'double',
            'else',
            'enum',
            'extends',
            'final',
            'finally',
            'float',
            'for',
            'if',
            'implements',
            'import',
            'instanceof',
            'int',
            'interface',
            'long',
            'native',
            'new',
            'package',
            'private',
            'protected',
            'public',
            'return',
            'short',
            'static',
            'strictfp',
            'super',
            'switch',
            'synchronized',
            'this',
            'throw',
            'throws',
            'transient',
            'try',
            'void',
            'volatile',
            'while',
            'true',
            'false',
            'null',
        ],
        context_keywords => [],
        layout_keywords => [],
        soft_keywords => [],
        mode => '',
        escape_mode => '',
        skip_definitions => [
            bless({
                name => 'WHITESPACE',
                pattern => '[ \\t\\r\\n\\v\\f]+',
                is_regex => 1,
                line_number => 390,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LINE_COMMENT',
                pattern => '\\/\\/[^\\n]*',
                is_regex => 1,
                line_number => 391,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BLOCK_COMMENT',
                pattern => '\\/\\*([^*]|\\*[^\\/])*\\*\\/',
                is_regex => 1,
                line_number => 392,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        error_definitions => [
            bless({
                name => 'BAD_STRING',
                pattern => '"[^"]*$',
                is_regex => 1,
                line_number => 401,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BAD_CHAR',
                pattern => '\'[^\']*$',
                is_regex => 1,
                line_number => 402,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        reserved_keywords => [
            'const',
            'goto',
        ],
        groups => {},
        start_mode => '',
        transitions => [],
    }, 'CodingAdventures::GrammarTools::TokenGrammar';
}

1;
