# AUTO-GENERATED FILE — DO NOT EDIT
# Source: java21.tokens
# Regenerate with: perl code/programs/perl/grammar-tools/grammar-tools.pl compile-tokens java21.tokens
#
# This file embeds a TokenGrammar as native Perl data structures.
# Call token_grammar() instead of reading and parsing the .tokens file.

package CodingAdventures::JavaLexer::_Grammar_21;
use strict;
use warnings;

sub token_grammar {
    return bless {
        definitions => [
            bless({
                name => 'NAME',
                pattern => '[a-zA-Z_$][a-zA-Z0-9_$]*',
                is_regex => 1,
                line_number => 137,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BINARY_NUMBER',
                pattern => '0[bB][01][01_]*[01][lL]?',
                is_regex => 1,
                line_number => 168,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BINARY_SHORT',
                pattern => '0[bB][01][lL]?',
                is_regex => 1,
                line_number => 169,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'HEX_NUMBER',
                pattern => '0[xX][0-9a-fA-F][0-9a-fA-F_]*[0-9a-fA-F][lL]?',
                is_regex => 1,
                line_number => 170,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'HEX_SHORT',
                pattern => '0[xX][0-9a-fA-F][lL]?',
                is_regex => 1,
                line_number => 171,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'OCTAL_NUMBER',
                pattern => '0[0-7_]*[0-7]+[lL]?',
                is_regex => 1,
                line_number => 172,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOAT_NUMBER',
                pattern => '[0-9][0-9_]*\\.[0-9_]*([eE][+-]?[0-9_]+)?[fFdD]?',
                is_regex => 1,
                line_number => 173,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEADING_DOT_FLOAT',
                pattern => '\\.[0-9][0-9_]*([eE][+-]?[0-9_]+)?[fFdD]?',
                is_regex => 1,
                line_number => 174,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SCI_NUMBER',
                pattern => '[0-9][0-9_]*[eE][+-]?[0-9_]+[fFdD]?',
                is_regex => 1,
                line_number => 175,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LONG_NUMBER',
                pattern => '[0-9][0-9_]*[lL]',
                is_regex => 1,
                line_number => 176,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOAT_SUFFIX',
                pattern => '[0-9][0-9_]*[fFdD]',
                is_regex => 1,
                line_number => 177,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'INT_NUMBER',
                pattern => '[0-9][0-9_]*',
                is_regex => 1,
                line_number => 178,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'TEXT_BLOCK',
                pattern => '"""[ \\t]*\\n([^"\\\\]|\\\\.|"[^"\\\\]|""[^"\\\\])*"""',
                is_regex => 1,
                line_number => 252,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING',
                pattern => '"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 253,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'CHAR',
                pattern => '\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 254,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'ELLIPSIS',
                pattern => '...',
                is_regex => 0,
                line_number => 281,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'ARROW',
                pattern => '->',
                is_regex => 0,
                line_number => 282,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'DOUBLE_COLON',
                pattern => '::',
                is_regex => 0,
                line_number => 283,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'UNSIGNED_RIGHT_SHIFT_EQUALS',
                pattern => '>>>=',
                is_regex => 0,
                line_number => 284,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'UNSIGNED_RIGHT_SHIFT',
                pattern => '>>>',
                is_regex => 0,
                line_number => 285,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEFT_SHIFT_EQUALS',
                pattern => '<<=',
                is_regex => 0,
                line_number => 286,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RIGHT_SHIFT_EQUALS',
                pattern => '>>=',
                is_regex => 0,
                line_number => 287,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'EQUALS_EQUALS',
                pattern => '==',
                is_regex => 0,
                line_number => 288,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NOT_EQUALS',
                pattern => '!=',
                is_regex => 0,
                line_number => 289,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LESS_EQUALS',
                pattern => '<=',
                is_regex => 0,
                line_number => 290,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'GREATER_EQUALS',
                pattern => '>=',
                is_regex => 0,
                line_number => 291,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AND_AND',
                pattern => '&&',
                is_regex => 0,
                line_number => 292,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'OR_OR',
                pattern => '||',
                is_regex => 0,
                line_number => 293,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS_PLUS',
                pattern => '++',
                is_regex => 0,
                line_number => 294,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS_MINUS',
                pattern => '--',
                is_regex => 0,
                line_number => 295,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS_EQUALS',
                pattern => '+=',
                is_regex => 0,
                line_number => 296,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS_EQUALS',
                pattern => '-=',
                is_regex => 0,
                line_number => 297,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STAR_EQUALS',
                pattern => '*=',
                is_regex => 0,
                line_number => 298,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SLASH_EQUALS',
                pattern => '/=',
                is_regex => 0,
                line_number => 299,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PERCENT_EQUALS',
                pattern => '%=',
                is_regex => 0,
                line_number => 300,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AMPERSAND_EQUALS',
                pattern => '&=',
                is_regex => 0,
                line_number => 301,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PIPE_EQUALS',
                pattern => '|=',
                is_regex => 0,
                line_number => 302,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'CARET_EQUALS',
                pattern => '^=',
                is_regex => 0,
                line_number => 303,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEFT_SHIFT',
                pattern => '<<',
                is_regex => 0,
                line_number => 304,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RIGHT_SHIFT',
                pattern => '>>',
                is_regex => 0,
                line_number => 305,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AT',
                pattern => '@',
                is_regex => 0,
                line_number => 318,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'EQUALS',
                pattern => '=',
                is_regex => 0,
                line_number => 319,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS',
                pattern => '+',
                is_regex => 0,
                line_number => 320,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS',
                pattern => '-',
                is_regex => 0,
                line_number => 321,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STAR',
                pattern => '*',
                is_regex => 0,
                line_number => 322,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SLASH',
                pattern => '/',
                is_regex => 0,
                line_number => 323,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PERCENT',
                pattern => '%',
                is_regex => 0,
                line_number => 324,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LESS_THAN',
                pattern => '<',
                is_regex => 0,
                line_number => 325,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'GREATER_THAN',
                pattern => '>',
                is_regex => 0,
                line_number => 326,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BANG',
                pattern => '!',
                is_regex => 0,
                line_number => 327,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AMPERSAND',
                pattern => '&',
                is_regex => 0,
                line_number => 328,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PIPE',
                pattern => '|',
                is_regex => 0,
                line_number => 329,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'CARET',
                pattern => '^',
                is_regex => 0,
                line_number => 330,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'TILDE',
                pattern => '~',
                is_regex => 0,
                line_number => 331,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'QUESTION',
                pattern => '?',
                is_regex => 0,
                line_number => 332,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LPAREN',
                pattern => '(',
                is_regex => 0,
                line_number => 341,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RPAREN',
                pattern => ')',
                is_regex => 0,
                line_number => 342,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LBRACE',
                pattern => '{',
                is_regex => 0,
                line_number => 343,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RBRACE',
                pattern => '}',
                is_regex => 0,
                line_number => 344,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LBRACKET',
                pattern => '[',
                is_regex => 0,
                line_number => 345,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RBRACKET',
                pattern => ']',
                is_regex => 0,
                line_number => 346,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SEMICOLON',
                pattern => ';',
                is_regex => 0,
                line_number => 347,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COMMA',
                pattern => ',',
                is_regex => 0,
                line_number => 348,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'DOT',
                pattern => '.',
                is_regex => 0,
                line_number => 349,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COLON',
                pattern => ':',
                is_regex => 0,
                line_number => 350,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        keywords => [
            'abstract',
            'assert',
            'boolean',
            'break',
            'byte',
            'case',
            'catch',
            'char',
            'class',
            'continue',
            'default',
            'do',
            'double',
            'else',
            'enum',
            'extends',
            'final',
            'finally',
            'float',
            'for',
            'if',
            'implements',
            'import',
            'instanceof',
            'int',
            'interface',
            'long',
            'native',
            'new',
            'package',
            'private',
            'protected',
            'public',
            'return',
            'short',
            'static',
            'strictfp',
            'super',
            'switch',
            'synchronized',
            'this',
            'throw',
            'throws',
            'transient',
            'try',
            'void',
            'volatile',
            'while',
            'true',
            'false',
            'null',
        ],
        context_keywords => [],
        layout_keywords => [],
        soft_keywords => [],
        mode => '',
        escape_mode => '',
        skip_definitions => [
            bless({
                name => 'WHITESPACE',
                pattern => '[ \\t\\r\\n\\v\\f]+',
                is_regex => 1,
                line_number => 474,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LINE_COMMENT',
                pattern => '\\/\\/[^\\n]*',
                is_regex => 1,
                line_number => 475,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BLOCK_COMMENT',
                pattern => '\\/\\*([^*]|\\*[^\\/])*\\*\\/',
                is_regex => 1,
                line_number => 476,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        error_definitions => [
            bless({
                name => 'BAD_STRING',
                pattern => '"[^"]*$',
                is_regex => 1,
                line_number => 487,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BAD_CHAR',
                pattern => '\'[^\']*$',
                is_regex => 1,
                line_number => 488,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        reserved_keywords => [
            'const',
            'goto',
        ],
        groups => {},
        start_mode => '',
        transitions => [],
    }, 'CodingAdventures::GrammarTools::TokenGrammar';
}

1;
