defmodule CodingAdventures.ExcelLexer.Grammar do
  # AUTO-GENERATED FILE — DO NOT EDIT
  # Source: excel.tokens
  # Regenerate with: grammar-tools compile-tokens excel.tokens
  #
  # This file embeds a TokenGrammar as native Elixir data structures.
  # Call token_grammar/0 instead of reading and parsing the .tokens file.
  
  alias CodingAdventures.GrammarTools.TokenGrammar
  
  def token_grammar do
    %TokenGrammar{
      definitions: [
          %{
            name: "SPACE",
            pattern: " +",
            is_regex: true,
            line_number: 13,
            alias: nil,
          },
          %{
            name: "REF_PREFIX_QUOTED",
            pattern: "(\\[[^\\]]+\\])?'([^']|'')*'!",
            is_regex: true,
            line_number: 15,
            alias: "REF_PREFIX",
          },
          %{
            name: "REF_PREFIX_WB_BARE",
            pattern: "\\[[^\\]]+\\][A-Za-z_][A-Za-z0-9_.:]*!",
            is_regex: true,
            line_number: 16,
            alias: "REF_PREFIX",
          },
          %{
            name: "REF_PREFIX_BARE",
            pattern: "[A-Za-z_][A-Za-z0-9_.:]*!",
            is_regex: true,
            line_number: 17,
            alias: "REF_PREFIX",
          },
          %{
            name: "STRING",
            pattern: "\"([^\"]|\"\")*\"",
            is_regex: true,
            line_number: 19,
            alias: nil,
          },
          %{
            name: "ERROR_CONSTANT",
            pattern: "#[a-z0-9\\/\\?!]*[a-z0-9\\?!]",
            is_regex: true,
            line_number: 20,
            alias: nil,
          },
          %{
            name: "NUMBER_DOT_EXP",
            pattern: "\\.[0-9]+[eE][-+]?[0-9]+",
            is_regex: true,
            line_number: 26,
            alias: "NUMBER",
          },
          %{
            name: "NUMBER_DOT",
            pattern: "\\.[0-9]+",
            is_regex: true,
            line_number: 27,
            alias: "NUMBER",
          },
          %{
            name: "NUMBER_EXP",
            pattern: "[0-9]+\\.?[0-9]*[eE][-+]?[0-9]+",
            is_regex: true,
            line_number: 28,
            alias: "NUMBER",
          },
          %{
            name: "NUMBER",
            pattern: "[0-9]+\\.?[0-9]*",
            is_regex: true,
            line_number: 29,
            alias: nil,
          },
          %{
            name: "STRUCTURED_KEYWORD",
            pattern: "\\[#[a-z ]+\\]",
            is_regex: true,
            line_number: 31,
            alias: nil,
          },
          %{
            name: "STRUCTURED_COLUMN",
            pattern: "\\[[^\\[\\]]+\\]",
            is_regex: true,
            line_number: 32,
            alias: nil,
          },
          %{
            name: "CELL",
            pattern: "\\$?[A-Za-z]{1,3}\\$?[0-9]{1,7}",
            is_regex: true,
            line_number: 35,
            alias: nil,
          },
          %{
            name: "NOT_EQUALS",
            pattern: "<>",
            is_regex: false,
            line_number: 37,
            alias: nil,
          },
          %{
            name: "LESS_EQUALS",
            pattern: "<=",
            is_regex: false,
            line_number: 38,
            alias: nil,
          },
          %{
            name: "GREATER_EQUALS",
            pattern: ">=",
            is_regex: false,
            line_number: 39,
            alias: nil,
          },
          %{
            name: "PLUS",
            pattern: "+",
            is_regex: false,
            line_number: 41,
            alias: nil,
          },
          %{
            name: "MINUS",
            pattern: "-",
            is_regex: false,
            line_number: 42,
            alias: nil,
          },
          %{
            name: "STAR",
            pattern: "*",
            is_regex: false,
            line_number: 43,
            alias: nil,
          },
          %{
            name: "SLASH",
            pattern: "/",
            is_regex: false,
            line_number: 44,
            alias: nil,
          },
          %{
            name: "CARET",
            pattern: "^",
            is_regex: false,
            line_number: 45,
            alias: nil,
          },
          %{
            name: "AMP",
            pattern: "&",
            is_regex: false,
            line_number: 46,
            alias: nil,
          },
          %{
            name: "PERCENT",
            pattern: "%",
            is_regex: false,
            line_number: 47,
            alias: nil,
          },
          %{
            name: "EQUALS",
            pattern: "=",
            is_regex: false,
            line_number: 48,
            alias: nil,
          },
          %{
            name: "LESS_THAN",
            pattern: "<",
            is_regex: false,
            line_number: 49,
            alias: nil,
          },
          %{
            name: "GREATER_THAN",
            pattern: ">",
            is_regex: false,
            line_number: 50,
            alias: nil,
          },
          %{
            name: "BANG",
            pattern: "!",
            is_regex: false,
            line_number: 51,
            alias: nil,
          },
          %{
            name: "DOLLAR",
            pattern: "$",
            is_regex: false,
            line_number: 52,
            alias: nil,
          },
          %{
            name: "LPAREN",
            pattern: "(",
            is_regex: false,
            line_number: 53,
            alias: nil,
          },
          %{
            name: "RPAREN",
            pattern: ")",
            is_regex: false,
            line_number: 54,
            alias: nil,
          },
          %{
            name: "LBRACE",
            pattern: "{",
            is_regex: false,
            line_number: 55,
            alias: nil,
          },
          %{
            name: "RBRACE",
            pattern: "}",
            is_regex: false,
            line_number: 56,
            alias: nil,
          },
          %{
            name: "LBRACKET",
            pattern: "[",
            is_regex: false,
            line_number: 57,
            alias: nil,
          },
          %{
            name: "RBRACKET",
            pattern: "]",
            is_regex: false,
            line_number: 58,
            alias: nil,
          },
          %{
            name: "COMMA",
            pattern: ",",
            is_regex: false,
            line_number: 59,
            alias: nil,
          },
          %{
            name: "SEMICOLON",
            pattern: ";",
            is_regex: false,
            line_number: 60,
            alias: nil,
          },
          %{
            name: "COLON",
            pattern: ":",
            is_regex: false,
            line_number: 61,
            alias: nil,
          },
          %{
            name: "AT",
            pattern: "@",
            is_regex: false,
            line_number: 62,
            alias: nil,
          },
          %{
            name: "NAME",
            pattern: "[A-Za-z_\\\\][A-Za-z0-9_\\.]*",
            is_regex: true,
            line_number: 64,
            alias: nil,
          },
          %{
            name: "FUNCTION_NAME",
            pattern: "[^\\s\\S]",
            is_regex: true,
            line_number: 70,
            alias: nil,
          },
          %{
            name: "TABLE_NAME",
            pattern: "[^\\s\\S]",
            is_regex: true,
            line_number: 71,
            alias: nil,
          },
          %{
            name: "COLUMN_REF",
            pattern: "[^\\s\\S]",
            is_regex: true,
            line_number: 72,
            alias: nil,
          },
          %{
            name: "ROW_REF",
            pattern: "[^\\s\\S]",
            is_regex: true,
            line_number: 73,
            alias: nil,
          },
        ],
      keywords: ["true", "false"],
      mode: nil,
      escape_mode: nil,
      skip_definitions: [
          %{
            name: "NONSPACE_WHITESPACE",
            pattern: "[\\t\\r\\n]+",
            is_regex: true,
            line_number: 11,
            alias: nil,
          },
        ],
      reserved_keywords: [],
      error_definitions: [],
      groups: %{},
      layout_keywords: [],
      case_sensitive: true,
      version: 1,
      case_insensitive: true,
      start_mode: nil,
      transitions: [],
    }
  end
end
