cargo build --manifest-path ../../../packages/rust/irc-proto/Cargo.toml
cargo build --manifest-path ../../../packages/rust/irc-framing/Cargo.toml
cargo build --manifest-path ../../../packages/rust/irc-server/Cargo.toml
cargo build --manifest-path ../../../packages/rust/irc-net-stdlib/Cargo.toml
cargo test -- --nocapture
