name:                 coding-adventures-directed-graph
version:              0.1.0
visibility:           public
id:                   coding-adventures-directed-graph-0.1.0-inplace
key:                  coding-adventures-directed-graph-0.1.0-inplace
license:              MIT
maintainer:           Adhithya Rajasekaran
author:               Adhithya Rajasekaran
abi:                  inplace
exposed:              True
exposed-modules:      DirectedGraph LabeledGraph
import-dirs:
    /Users/adhithya/Downloads/antigravity/coding-adventures/code/packages/haskell/directed-graph/dist-newstyle/build/aarch64-osx/ghc-9.6.7/coding-adventures-directed-graph-0.1.0/build

library-dirs:
    /Users/adhithya/Downloads/antigravity/coding-adventures/code/packages/haskell/directed-graph/dist-newstyle/build/aarch64-osx/ghc-9.6.7/coding-adventures-directed-graph-0.1.0/build

library-dirs-static:
    /Users/adhithya/Downloads/antigravity/coding-adventures/code/packages/haskell/directed-graph/dist-newstyle/build/aarch64-osx/ghc-9.6.7/coding-adventures-directed-graph-0.1.0/build

dynamic-library-dirs:
    /Users/adhithya/Downloads/antigravity/coding-adventures/code/packages/haskell/directed-graph/dist-newstyle/build/aarch64-osx/ghc-9.6.7/coding-adventures-directed-graph-0.1.0/build

data-dir:
    /Users/adhithya/Downloads/antigravity/coding-adventures/code/packages/haskell/directed-graph/.

hs-libraries:         HScoding-adventures-directed-graph-0.1.0-inplace
depends:              base-4.18.3.0 containers-0.6.7
haddock-interfaces:
    /Users/adhithya/Downloads/antigravity/coding-adventures/code/packages/haskell/directed-graph/dist-newstyle/build/aarch64-osx/ghc-9.6.7/coding-adventures-directed-graph-0.1.0/doc/html/coding-adventures-directed-graph/coding-adventures-directed-graph.haddock

haddock-html:
    /Users/adhithya/Downloads/antigravity/coding-adventures/code/packages/haskell/directed-graph/dist-newstyle/build/aarch64-osx/ghc-9.6.7/coding-adventures-directed-graph-0.1.0/doc/html/coding-adventures-directed-graph
