# frozen_string_literal: true
# AUTO-GENERATED FILE — DO NOT EDIT
# Source: starlark.tokens
# Regenerate with: grammar-tools compile-tokens starlark.tokens
#
# This file embeds a TokenGrammar as native Ruby data structures.
# Downstream packages require this file directly instead of reading
# and parsing the .tokens file at runtime.

require "coding_adventures_grammar_tools"

GT = CodingAdventures::GrammarTools unless defined?(GT)

TOKEN_GRAMMAR = GT::TokenGrammar.new(
  version: 1,
  case_insensitive: false,
  case_sensitive: true,
  definitions: [
      GT::TokenDefinition.new(
        name: "STRING_RAW_TRIPLE_DQ",
        pattern: "[rR][bB]?\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"|[bB][rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
        is_regex: true,
        line_number: 84,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_RAW_TRIPLE_SQ",
        pattern: "[rR][bB]?'''([^'\\\\]|\\\\.|\\n)*'''|[bB][rR]'''([^'\\\\]|\\\\.|\\n)*'''",
        is_regex: true,
        line_number: 85,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_TRIPLE_DQ",
        pattern: "[bB]?\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
        is_regex: true,
        line_number: 86,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_TRIPLE_SQ",
        pattern: "[bB]?'''([^'\\\\]|\\\\.|\\n)*'''",
        is_regex: true,
        line_number: 87,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_RAW_DQ",
        pattern: "[rR][bB]?\"([^\"\\\\]|\\\\.)*\"|[bB][rR]\"([^\"\\\\]|\\\\.)*\"",
        is_regex: true,
        line_number: 90,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_RAW_SQ",
        pattern: "[rR][bB]?'([^'\\\\]|\\\\.)*'|[bB][rR]'([^'\\\\]|\\\\.)*'",
        is_regex: true,
        line_number: 91,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_DQ",
        pattern: "[bB]?\"([^\"\\\\]|\\\\.)*\"",
        is_regex: true,
        line_number: 92,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_SQ",
        pattern: "[bB]?'([^'\\\\]|\\\\.)*'",
        is_regex: true,
        line_number: 93,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "FLOAT_EXP",
        pattern: "[0-9]+[eE][+-]?[0-9]+",
        is_regex: true,
        line_number: 110,
        alias_name: "FLOAT",
      ),
      GT::TokenDefinition.new(
        name: "FLOAT_DOT",
        pattern: "\\.[0-9]+([eE][+-]?[0-9]+)?",
        is_regex: true,
        line_number: 111,
        alias_name: "FLOAT",
      ),
      GT::TokenDefinition.new(
        name: "FLOAT",
        pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?",
        is_regex: true,
        line_number: 112,
        alias_name: "FLOAT",
      ),
      GT::TokenDefinition.new(
        name: "INT_HEX",
        pattern: "0[xX][0-9a-fA-F]+",
        is_regex: true,
        line_number: 115,
        alias_name: "INT",
      ),
      GT::TokenDefinition.new(
        name: "INT_OCT",
        pattern: "0[oO][0-7]+",
        is_regex: true,
        line_number: 116,
        alias_name: "INT",
      ),
      GT::TokenDefinition.new(
        name: "INT",
        pattern: "[0-9]+",
        is_regex: true,
        line_number: 117,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NAME",
        pattern: "[a-zA-Z_][a-zA-Z0-9_]*",
        is_regex: true,
        line_number: 127,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DOUBLE_STAR_EQUALS",
        pattern: "**=",
        is_regex: false,
        line_number: 136,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LEFT_SHIFT_EQUALS",
        pattern: "<<=",
        is_regex: false,
        line_number: 137,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RIGHT_SHIFT_EQUALS",
        pattern: ">>=",
        is_regex: false,
        line_number: 138,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "FLOOR_DIV_EQUALS",
        pattern: "//=",
        is_regex: false,
        line_number: 139,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DOUBLE_STAR",
        pattern: "**",
        is_regex: false,
        line_number: 148,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "FLOOR_DIV",
        pattern: "//",
        is_regex: false,
        line_number: 149,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LEFT_SHIFT",
        pattern: "<<",
        is_regex: false,
        line_number: 150,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RIGHT_SHIFT",
        pattern: ">>",
        is_regex: false,
        line_number: 151,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQUALS_EQUALS",
        pattern: "==",
        is_regex: false,
        line_number: 152,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NOT_EQUALS",
        pattern: "!=",
        is_regex: false,
        line_number: 153,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_EQUALS",
        pattern: "<=",
        is_regex: false,
        line_number: 154,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_EQUALS",
        pattern: ">=",
        is_regex: false,
        line_number: 155,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS_EQUALS",
        pattern: "+=",
        is_regex: false,
        line_number: 156,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS_EQUALS",
        pattern: "-=",
        is_regex: false,
        line_number: 157,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR_EQUALS",
        pattern: "*=",
        is_regex: false,
        line_number: 158,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SLASH_EQUALS",
        pattern: "/=",
        is_regex: false,
        line_number: 159,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PERCENT_EQUALS",
        pattern: "%=",
        is_regex: false,
        line_number: 160,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AMP_EQUALS",
        pattern: "&=",
        is_regex: false,
        line_number: 161,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PIPE_EQUALS",
        pattern: "|=",
        is_regex: false,
        line_number: 162,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CARET_EQUALS",
        pattern: "^=",
        is_regex: false,
        line_number: 163,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS",
        pattern: "+",
        is_regex: false,
        line_number: 169,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS",
        pattern: "-",
        is_regex: false,
        line_number: 170,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR",
        pattern: "*",
        is_regex: false,
        line_number: 171,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SLASH",
        pattern: "/",
        is_regex: false,
        line_number: 172,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PERCENT",
        pattern: "%",
        is_regex: false,
        line_number: 173,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQUALS",
        pattern: "=",
        is_regex: false,
        line_number: 174,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_THAN",
        pattern: "<",
        is_regex: false,
        line_number: 175,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_THAN",
        pattern: ">",
        is_regex: false,
        line_number: 176,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AMP",
        pattern: "&",
        is_regex: false,
        line_number: 177,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PIPE",
        pattern: "|",
        is_regex: false,
        line_number: 178,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CARET",
        pattern: "^",
        is_regex: false,
        line_number: 179,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "TILDE",
        pattern: "~",
        is_regex: false,
        line_number: 180,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LPAREN",
        pattern: "(",
        is_regex: false,
        line_number: 186,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RPAREN",
        pattern: ")",
        is_regex: false,
        line_number: 187,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACKET",
        pattern: "[",
        is_regex: false,
        line_number: 188,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACKET",
        pattern: "]",
        is_regex: false,
        line_number: 189,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACE",
        pattern: "{",
        is_regex: false,
        line_number: 190,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACE",
        pattern: "}",
        is_regex: false,
        line_number: 191,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COMMA",
        pattern: ",",
        is_regex: false,
        line_number: 192,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COLON",
        pattern: ":",
        is_regex: false,
        line_number: 193,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SEMICOLON",
        pattern: ";",
        is_regex: false,
        line_number: 194,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DOT",
        pattern: ".",
        is_regex: false,
        line_number: 195,
        alias_name: nil,
      ),
    ],
  keywords: ["and", "break", "continue", "def", "elif", "else", "for", "if", "in", "lambda", "load", "not", "or", "pass", "return", "True", "False", "None"],
  mode: "indentation",
  escape_mode: nil,
  skip_definitions: [
      GT::TokenDefinition.new(
        name: "COMMENT",
        pattern: "#[^\\n]*",
        is_regex: true,
        line_number: 65,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "WHITESPACE",
        pattern: "[ \\t]+",
        is_regex: true,
        line_number: 66,
        alias_name: nil,
      ),
    ],
  reserved_keywords: ["as", "assert", "async", "await", "class", "del", "except", "finally", "from", "global", "import", "is", "nonlocal", "raise", "try", "while", "with", "yield"],
  error_definitions: [],
  groups: {},
  layout_keywords: [],
  context_keywords: [],
  soft_keywords: [],
)
