cd ../../../packages/typescript/indexeddb && npm install --quiet
cd ../../../packages/typescript/store && npm install --quiet
cd ../../../packages/typescript/ui-components && npm install --quiet
cd ../engram-app && npm install --quiet && npm run build
cd ../engram-electron && npm install
npx tsc -p electron/tsconfig.json
