cd ../../../packages/typescript/indexeddb && npm install
cd ../../../packages/typescript/store && npm install
cd ../../../packages/typescript/ui-components && npm install
cd ../../../programs/typescript/engram-app && npm install && npm run build
cd ../engram-electron && npm install
npx tsc -p electron/tsconfig.json
