name: coding_adventures_single_layer_network
version: 0.1.0
description: Single-layer multi-input multi-output neural network primitives.
repository: https://github.com/adhithyan15/coding-adventures

environment:
  sdk: ^3.0.0

dependencies: {}

dev_dependencies:
  test: ^1.25.0
