# frozen_string_literal: true
# AUTO-GENERATED FILE — DO NOT EDIT
# Source: excel.tokens
# Regenerate with: grammar-tools compile-tokens excel.tokens
#
# This file embeds a TokenGrammar as native Ruby data structures.
# Downstream packages require this file directly instead of reading
# and parsing the .tokens file at runtime.

require "coding_adventures_grammar_tools"

GT = CodingAdventures::GrammarTools unless defined?(GT)

TOKEN_GRAMMAR = GT::TokenGrammar.new(
  version: 1,
  case_insensitive: true,
  case_sensitive: true,
  definitions: [
      GT::TokenDefinition.new(
        name: "SPACE",
        pattern: " +",
        is_regex: true,
        line_number: 13,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "REF_PREFIX_QUOTED",
        pattern: "(\\[[^\\]]+\\])?'([^']|'')*'!",
        is_regex: true,
        line_number: 15,
        alias_name: "REF_PREFIX",
      ),
      GT::TokenDefinition.new(
        name: "REF_PREFIX_BARE",
        pattern: "(\\[[^\\]]+\\])?[A-Za-z_\\\\][A-Za-z0-9_\\.]*(?::[A-Za-z_\\\\][A-Za-z0-9_\\.]*)*!",
        is_regex: true,
        line_number: 16,
        alias_name: "REF_PREFIX",
      ),
      GT::TokenDefinition.new(
        name: "STRING",
        pattern: "\"([^\"]|\"\")*\"",
        is_regex: true,
        line_number: 18,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "ERROR_CONSTANT",
        pattern: "#NULL!|#DIV\\/0!|#VALUE!|#REF!|#NAME\\?|#NUM!|#N\\/A|#SPILL!|#CALC!|#GETTING_DATA",
        is_regex: true,
        line_number: 19,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NUMBER",
        pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?|\\.[0-9]+([eE][+-]?[0-9]+)?|[0-9]+([eE][+-]?[0-9]+)?",
        is_regex: true,
        line_number: 20,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STRUCTURED_KEYWORD",
        pattern: "\\[#(?:All|Data|Headers|Totals|This Row)\\]",
        is_regex: true,
        line_number: 22,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STRUCTURED_COLUMN",
        pattern: "\\[(?:[^\\[\\]]|\\]\\])+\\]",
        is_regex: true,
        line_number: 23,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CELL",
        pattern: "\\$?[A-Za-z]{1,3}\\$?[0-9]{1,7}",
        is_regex: true,
        line_number: 26,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NOT_EQUALS",
        pattern: "<>",
        is_regex: false,
        line_number: 28,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_EQUALS",
        pattern: "<=",
        is_regex: false,
        line_number: 29,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_EQUALS",
        pattern: ">=",
        is_regex: false,
        line_number: 30,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS",
        pattern: "+",
        is_regex: false,
        line_number: 32,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS",
        pattern: "-",
        is_regex: false,
        line_number: 33,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR",
        pattern: "*",
        is_regex: false,
        line_number: 34,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SLASH",
        pattern: "/",
        is_regex: false,
        line_number: 35,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CARET",
        pattern: "^",
        is_regex: false,
        line_number: 36,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AMP",
        pattern: "&",
        is_regex: false,
        line_number: 37,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PERCENT",
        pattern: "%",
        is_regex: false,
        line_number: 38,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQUALS",
        pattern: "=",
        is_regex: false,
        line_number: 39,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_THAN",
        pattern: "<",
        is_regex: false,
        line_number: 40,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_THAN",
        pattern: ">",
        is_regex: false,
        line_number: 41,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BANG",
        pattern: "!",
        is_regex: false,
        line_number: 42,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DOLLAR",
        pattern: "$",
        is_regex: false,
        line_number: 43,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LPAREN",
        pattern: "(",
        is_regex: false,
        line_number: 44,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RPAREN",
        pattern: ")",
        is_regex: false,
        line_number: 45,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACE",
        pattern: "{",
        is_regex: false,
        line_number: 46,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACE",
        pattern: "}",
        is_regex: false,
        line_number: 47,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACKET",
        pattern: "[",
        is_regex: false,
        line_number: 48,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACKET",
        pattern: "]",
        is_regex: false,
        line_number: 49,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COMMA",
        pattern: ",",
        is_regex: false,
        line_number: 50,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SEMICOLON",
        pattern: ";",
        is_regex: false,
        line_number: 51,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COLON",
        pattern: ":",
        is_regex: false,
        line_number: 52,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AT",
        pattern: "@",
        is_regex: false,
        line_number: 53,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NAME",
        pattern: "[A-Za-z_\\\\][A-Za-z0-9_\\.]*",
        is_regex: true,
        line_number: 55,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "FUNCTION_NAME",
        pattern: "(?!.)",
        is_regex: true,
        line_number: 61,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "TABLE_NAME",
        pattern: "(?!.)",
        is_regex: true,
        line_number: 62,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COLUMN_REF",
        pattern: "(?!.)",
        is_regex: true,
        line_number: 63,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "ROW_REF",
        pattern: "(?!.)",
        is_regex: true,
        line_number: 64,
        alias_name: nil,
      ),
    ],
  keywords: ["TRUE", "FALSE"],
  mode: nil,
  escape_mode: nil,
  skip_definitions: [
      GT::TokenDefinition.new(
        name: "NONSPACE_WHITESPACE",
        pattern: "[\\t\\r\\n]+",
        is_regex: true,
        line_number: 11,
        alias_name: nil,
      ),
    ],
  reserved_keywords: [],
  error_definitions: [],
  groups: {},
)
