// Code generated by capability-cage-generator. DO NOT EDIT.
//
// Source: required_capabilities.json
// Regenerate:
//   go run github.com/adhithyan15/coding-adventures/code/programs/go/capability-cage-generator \
//     --manifest=/Users/adhithya/Downloads/Codex/coding-adventures-go-native-renderer/code/packages/go/paint-codec-png-native/required_capabilities.json
//
// The JSON file is a development-time artifact; this file is what the
// runtime enforces. Edit required_capabilities.json and re-run the
// generator to change capabilities — never edit this file directly.

package paintcodecpngnative

import (
	"fmt"
)

// ─────────────────────────────────────────────────────────────────────────────
// _FfiCapabilities — op.Ffi capability namespace
//
// Accessible via op.Ffi inside any Operation callback. The field only
// exists when ffi capabilities are declared in required_capabilities.json.
// Undeclared categories produce a compile error at the call site.
// ─────────────────────────────────────────────────────────────────────────────

type _FfiCapabilities struct{}

// TODO: implement capability method for ffi:call

// ─────────────────────────────────────────────────────────────────────────────
// OperationResult — three-state outcome
//
// Every Operation callback returns one of three outcomes:
//   Success:             DidSucceed=true,  DidFailUnexpectedly=false
//   Expected failure:    DidSucceed=false, DidFailUnexpectedly=false
//   Unexpected failure:  DidSucceed=false, DidFailUnexpectedly=true
//
// "Expected failure" means the operation ran normally but produced a
// negative result (e.g. node not found, permission denied).
// "Unexpected failure" means the callback panicked; fallback value used.
//
// Err carries a typed error for expected failures. When set, GetResult
// returns it directly — preserving its type for errors.As checks.
// ─────────────────────────────────────────────────────────────────────────────

type OperationResult[T any] struct {
	DidSucceed          bool
	DidFailUnexpectedly bool
	ReturnValue         T
	Err                 error // if non-nil, returned as-is by GetResult for expected failures
}

// ─────────────────────────────────────────────────────────────────────────────
// ResultFactory — creates OperationResult values inside callbacks
// ─────────────────────────────────────────────────────────────────────────────

type ResultFactory[T any] struct{}

// Generate creates an OperationResult for the common case.
// Pass didSucceed=true for success, false for failure.
// Set didFailUnexpectedly=true only to signal internal programming errors;
// prefer letting the Operation framework catch panics automatically.
func (f *ResultFactory[T]) Generate(didSucceed bool, didFailUnexpectedly bool, value T) *OperationResult[T] {
	return &OperationResult[T]{
		DidSucceed:          didSucceed,
		DidFailUnexpectedly: didFailUnexpectedly,
		ReturnValue:         value,
	}
}

// Fail creates an expected-failure OperationResult with a specific error.
// Use this when the failure has a typed error (e.g., NodeNotFoundError)
// that callers may inspect with errors.As. The error is returned unchanged
// by GetResult, preserving its dynamic type for type assertions.
func (f *ResultFactory[T]) Fail(value T, err error) *OperationResult[T] {
	return &OperationResult[T]{
		DidSucceed:          false,
		DidFailUnexpectedly: false,
		ReturnValue:         value,
		Err:                 err,
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Operation — the unit of work
// ─────────────────────────────────────────────────────────────────────────────

type Operation[T any] struct {
	name        string
	callback    func(*Operation[T], *ResultFactory[T]) *OperationResult[T]
	fallback    T
	propertyBag map[string]any
	rePanic     bool // if true, panics from the callback are re-panicked rather than caught
	Ffi          *_FfiCapabilities
}

// AddProperty attaches a named piece of metadata to this operation.
// Properties appear in the structured log emitted by GetResult.
// Record contextual information useful for debugging: node IDs, paths, etc.
func (op *Operation[T]) AddProperty(name string, value any) {
	op.propertyBag[name] = value
}

// PanicOnUnexpected configures this operation to re-panic when the callback
// panics, rather than catching the panic and returning the fallback value.
// Use this for operations that signal programming errors through panics
// (e.g., adding a self-loop to a graph that prohibits them).
func (op *Operation[T]) PanicOnUnexpected() *Operation[T] {
	op.rePanic = true
	return op
}

// GetResult executes the operation callback and returns (value, error).
//
// Execution model:
//  1. Call the callback with this Operation and a ResultFactory.
//  2. Recover any panic from the callback.
//     - If PanicOnUnexpected() was set: re-panic.
//     - Otherwise: use the fallback value, mark as unexpected failure.
//  3. Return (ReturnValue, nil) on success; (ReturnValue, error) on failure.
//     Expected failures with a typed Err field return that error directly
//     (preserving the type for errors.As checks).
func (op *Operation[T]) GetResult() (T, error) {
	rf := &ResultFactory[T]{}

	var result *OperationResult[T]
	encounteredPanic := false
	var panicValue any

	func() {
		defer func() {
			if r := recover(); r != nil {
				encounteredPanic = true
				panicValue = r
			}
		}()
		result = op.callback(op, rf)
	}()

	if encounteredPanic {
		result = &OperationResult[T]{
			DidSucceed:          false,
			DidFailUnexpectedly: true,
			ReturnValue:         op.fallback,
		}
	}

	if !result.DidSucceed {
		if result.DidFailUnexpectedly || encounteredPanic {
			if op.rePanic && encounteredPanic {
				panic(panicValue)
			}
			return result.ReturnValue, fmt.Errorf("operation %q failed unexpectedly (see log for details)", op.name)
		}
		if result.Err != nil {
			return result.ReturnValue, result.Err
		}
		return result.ReturnValue, fmt.Errorf("operation %q failed", op.name)
	}
	return result.ReturnValue, nil
}

// ─────────────────────────────────────────────────────────────────────────────
// StartNew — creates an Operation (does not run it yet)
//
// Call GetResult() on the returned Operation to execute the callback.
// Chain PanicOnUnexpected() before GetResult() to let panics propagate
// instead of being caught and converted to errors.
//
// Parameters:
//   name     — Human-readable name for logging. Use "package.Function" format.
//   fallback — Returned if the callback panics (and PanicOnUnexpected is false).
//              Use the zero value for T: nil, 0, "", false, etc.
//   fn       — The callback. Receives:
//                op — the operation (op.File, op.Net, etc. for OS access;
//                     op.AddProperty for metadata)
//                rf — the result factory (rf.Generate or rf.Fail)
// ─────────────────────────────────────────────────────────────────────────────

func StartNew[T any](
	name string,
	fallback T,
	fn func(op *Operation[T], rf *ResultFactory[T]) *OperationResult[T],
) *Operation[T] {
	return &Operation[T]{
		name:        name,
		callback:    fn,
		fallback:    fallback,
		propertyBag: make(map[string]any),
		Ffi:         &_FfiCapabilities{},
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// _capabilityViolationError — returned when an undeclared OS op is attempted
// ─────────────────────────────────────────────────────────────────────────────

type _capabilityViolationError struct {
	category  string
	action    string
	requested string
}

func (e *_capabilityViolationError) Error() string {
	return fmt.Sprintf(
		"capability violation: %s:%s — %q is not declared in required_capabilities.json.\n"+
			"To add: edit required_capabilities.json and re-run capability-cage-generator.",
		e.category, e.action, e.requested,
	)
}
