// AUTO-GENERATED by Mosaic. Edits will be overwritten on next emit.
import 'dart:async';
import 'dart:convert';
import 'dart:ffi';
import 'dart:io';

import 'package:ffi/ffi.dart';

final class _MosaicBytes extends Struct {
  external Pointer<Uint8> ptr;

  @UintPtr()
  external int len;
}

final class _MosaicBuffer extends Struct {
  external Pointer<Uint8> ptr;

  @UintPtr()
  external int len;

  @UintPtr()
  external int capacity;
}

typedef _CreateNative =
    Uint32 Function(
      _MosaicBytes,
      Pointer<Pointer<Void>>,
      Pointer<_MosaicBuffer>,
    );
typedef _Create =
    int Function(_MosaicBytes, Pointer<Pointer<Void>>, Pointer<_MosaicBuffer>);
typedef _DispatchNative =
    Uint32 Function(Pointer<Void>, _MosaicBytes, Pointer<_MosaicBuffer>);
typedef _Dispatch =
    int Function(Pointer<Void>, _MosaicBytes, Pointer<_MosaicBuffer>);
typedef _SnapshotNative =
    Uint32 Function(Pointer<Void>, Pointer<_MosaicBuffer>);
typedef _Snapshot = int Function(Pointer<Void>, Pointer<_MosaicBuffer>);
typedef _RestoreNative =
    Uint32 Function(Pointer<Void>, _MosaicBytes, Pointer<_MosaicBuffer>);
typedef _Restore =
    int Function(Pointer<Void>, _MosaicBytes, Pointer<_MosaicBuffer>);
typedef _BufferFreeNative = Void Function(_MosaicBuffer);
typedef _BufferFree = void Function(_MosaicBuffer);
typedef _DestroyNative = Void Function(Pointer<Void>);
typedef _Destroy = void Function(Pointer<Void>);
typedef _InputOperation = int Function(_MosaicBytes, Pointer<_MosaicBuffer>);
typedef _OutputOperation = int Function(Pointer<_MosaicBuffer>);
typedef _MoveFileExNative = Int32 Function(
  Pointer<Utf16>,
  Pointer<Utf16>,
  Uint32,
);
typedef _MoveFileEx = int Function(Pointer<Utf16>, Pointer<Utf16>, int);

@Native<_CreateNative>(symbol: 'mosaic_app_create')
external int _bundledCreate(
  _MosaicBytes input,
  Pointer<Pointer<Void>> appOut,
  Pointer<_MosaicBuffer> output,
);

@Native<_DispatchNative>(symbol: 'mosaic_app_dispatch')
external int _bundledDispatch(
  Pointer<Void> app,
  _MosaicBytes input,
  Pointer<_MosaicBuffer> output,
);

@Native<_SnapshotNative>(symbol: 'mosaic_app_snapshot')
external int _bundledSnapshot(
  Pointer<Void> app,
  Pointer<_MosaicBuffer> output,
);

@Native<_RestoreNative>(symbol: 'mosaic_app_restore')
external int _bundledRestore(
  Pointer<Void> app,
  _MosaicBytes input,
  Pointer<_MosaicBuffer> output,
);

@Native<_BufferFreeNative>(symbol: 'mosaic_buffer_free')
external void _bundledBufferFree(_MosaicBuffer buffer);

@Native<_DestroyNative>(symbol: 'mosaic_app_destroy')
external void _bundledDestroy(Pointer<Void> app);

/// Package-independent Flutter host for the fixed Mosaic Rust application ABI.
///
/// The public const constructor remains available for injected test and
/// package-owned hosts. Generated applications call [load], which installs the
/// standard Rust runtime whenever its dynamic library is available.
class MosaicHost {
  const MosaicHost() : _runtime = null;

  const MosaicHost._(this._runtime);

  final _MosaicRuntime? _runtime;

  static MosaicHost? load() {
    try {
      return MosaicHost._(_MosaicRuntime.load());
    } on Object catch (error, stackTrace) {
      stderr.writeln('Mosaic Rust runtime unavailable: $error\n$stackTrace');
      return null;
    }
  }

  static MosaicHost loadRequired() {
    final host = load();
    if (host == null) {
      throw StateError(
        'native-complete requires the Mosaic Rust application runtime',
      );
    }
    return host;
  }

  FutureOr<Map<String, Object?>?> props() => _runtime?.latestUpdate;

  FutureOr<Map<String, Object?>?> handleEvent(Map<String, Object?> event) =>
      _runtime?.dispatch(event);

  void setPropsChangedHandler(void Function()? handler) {
    _runtime?.propsChangedHandler = handler;
  }

  Map<String, Object?>? snapshot() => _runtime?.snapshot();

  Map<String, Object?>? restore(Map<String, Object?> snapshot) =>
      _runtime?.restore(snapshot);

  void dispose() => _runtime?.dispose();
}

final class _MosaicRuntime {
  _MosaicRuntime(DynamicLibrary library)
    : this._(
        library.lookupFunction<_CreateNative, _Create>('mosaic_app_create'),
        library.lookupFunction<_DispatchNative, _Dispatch>(
          'mosaic_app_dispatch',
        ),
        library.lookupFunction<_SnapshotNative, _Snapshot>(
          'mosaic_app_snapshot',
        ),
        library.lookupFunction<_RestoreNative, _Restore>('mosaic_app_restore'),
        library.lookupFunction<_BufferFreeNative, _BufferFree>(
          'mosaic_buffer_free',
        ),
        library.lookupFunction<_DestroyNative, _Destroy>('mosaic_app_destroy'),
      );

  _MosaicRuntime.bundled()
    : this._(
        _bundledCreate,
        _bundledDispatch,
        _bundledSnapshot,
        _bundledRestore,
        _bundledBufferFree,
        _bundledDestroy,
      );

  _MosaicRuntime._(
    this._create,
    this._dispatch,
    this._snapshot,
    this._restore,
    this._bufferFree,
    this._destroy,
  ) {
    final appOut = calloc<Pointer<Void>>();
    try {
      final persisted = _loadPersistedSnapshot();
      _persistenceWarning = persisted.warning;
      Map<String, Object?> create(Map<String, Object?>? restoredSnapshot) =>
          _requireMap(
            _invokeInput(<String, Object?>{
          'protocolVersion': _protocolVersion,
          'locale': Platform.localeName,
          'colorScheme': 'system',
          'textScale': 1.0,
          'platform': _platformName(),
          'restoredSnapshot': restoredSnapshot,
        }, (input, output) => _create(input, appOut, output)), 'startup update');
      try {
        latestUpdate = create(persisted.snapshot);
      } on Object catch (error) {
        if (persisted.snapshot == null) rethrow;
        final created = appOut.value;
        if (created != nullptr) _destroy(created);
        appOut.value = nullptr;
        _persistenceWarning = _quarantinePersistedState(
          'Mosaic runtime rejected persisted state: $error',
        );
        latestUpdate = create(null);
      }
      latestUpdate = _withPersistenceWarning(latestUpdate);
      _app = appOut.value;
      if (_app == nullptr) {
        throw StateError('Mosaic runtime returned a null application handle');
      }
    } on Object {
      final created = appOut.value;
      if (created != nullptr) _destroy(created);
      rethrow;
    } finally {
      calloc.free(appOut);
    }
  }

  static const int _protocolVersion = __MOSAIC_PROTOCOL_VERSION__;
  static const bool _hasBundledRuntime = __MOSAIC_BUNDLED_RUNTIME__;
  static const bool _persistenceEnabled = __MOSAIC_PERSISTENCE_ENABLED__;
  static const String _applicationId = '__MOSAIC_APPLICATION_ID__';
  static const String _stateFileName = 'mosaic-state.v1.json';

  final _Create _create;
  final _Dispatch _dispatch;
  final _Snapshot _snapshot;
  final _Restore _restore;
  final _BufferFree _bufferFree;
  final _Destroy _destroy;
  Pointer<Void> _app = nullptr;
  int _sequence = 0;
  late Map<String, Object?> latestUpdate;
  String? _persistenceWarning;
  void Function()? propsChangedHandler;

  static _MosaicRuntime load() {
    final requested = Platform.environment['MOSAIC_APP_LIBRARY'];
    if (requested != null && requested.trim().isNotEmpty) {
      return _MosaicRuntime(DynamicLibrary.open(requested));
    }

    if (_hasBundledRuntime) return _MosaicRuntime.bundled();

    final candidates = <DynamicLibrary Function()>[
      DynamicLibrary.process,
      for (final name in _libraryNames()) () => DynamicLibrary.open(name),
    ];
    Object? lastError;
    for (final open in candidates) {
      try {
        return _MosaicRuntime(open());
      } on Object catch (error) {
        lastError = error;
      }
    }
    throw StateError(
      'Unable to load the Mosaic application library: $lastError',
    );
  }

  Map<String, Object?> dispatch(Map<String, Object?> event) {
    _ensureOpen();
    final name = event['name'] ?? event['event'];
    if (name is! String || name.isEmpty) {
      throw ArgumentError.value(event, 'event', 'missing Mosaic event name');
    }
    if (_sequence == 0x7fffffffffffffff) {
      throw StateError('Mosaic event sequence overflow');
    }
    final nextSequence = _sequence + 1;
    final explicitPayload = event['payload'];
    final payload = explicitPayload is Map
        ? _stringMap(explicitPayload)
        : <String, Object?>{
            for (final entry in event.entries)
              if (entry.key != 'name' &&
                  entry.key != 'event' &&
                  entry.key != 'payload')
                entry.key: entry.value,
          };
    final update = _requireMap(
      _invokeInput(<String, Object?>{
        'protocolVersion': _protocolVersion,
        'sequence': nextSequence,
        'name': name,
        'payload': payload,
      }, (input, output) => _dispatch(_app, input, output)),
      'event update',
    );
    _sequence = nextSequence;
    _persistSnapshot();
    latestUpdate = _withPersistenceWarning(update);
    return latestUpdate;
  }

  Map<String, Object?>? snapshot() {
    _ensureOpen();
    final value = _invokeOutput((output) => _snapshot(_app, output));
    if (value == null) return null;
    return _requireMap(value, 'snapshot');
  }

  Map<String, Object?> restore(Map<String, Object?> snapshot) {
    _ensureOpen();
    latestUpdate = _requireMap(
      _invokeInput(snapshot, (input, output) => _restore(_app, input, output)),
      'restore update',
    );
    propsChangedHandler?.call();
    return latestUpdate;
  }

  void dispose() {
    if (_app == nullptr) return;
    _destroy(_app);
    _app = nullptr;
  }

  ({Map<String, Object?>? snapshot, String? warning})
  _loadPersistedSnapshot() {
    final path = _statePath();
    if (path == null) return (snapshot: null, warning: null);
    final file = File(path);
    if (!file.existsSync()) return (snapshot: null, warning: null);
    try {
      final value = jsonDecode(file.readAsStringSync());
      return (snapshot: _requireMap(value, 'persisted state'), warning: null);
    } on Object catch (error) {
      final warning = _quarantinePersistedState(
        'Ignored invalid Mosaic state: $error',
      );
      return (snapshot: null, warning: warning);
    }
  }

  String _quarantinePersistedState(String reason) {
    final path = _statePath();
    if (path == null) return reason;
    final file = File(path);
    final corrupt = File('$path.corrupt');
    try {
      if (corrupt.existsSync()) corrupt.deleteSync();
      if (file.existsSync()) file.renameSync(corrupt.path);
    } on Object catch (moveError) {
      stderr.writeln('Could not quarantine invalid Mosaic state: $moveError');
    }
    final warning = '$reason ($path)';
    stderr.writeln(warning);
    return warning;
  }

  void _persistSnapshot() {
    final path = _statePath();
    if (path == null) return;
    try {
      final value = _invokeOutput((output) => _snapshot(_app, output));
      final file = File(path);
      if (value == null) {
        if (file.existsSync()) file.deleteSync();
        _persistenceWarning = null;
        return;
      }
      file.parent.createSync(recursive: true);
      final temporary = File('$path.tmp');
      temporary.writeAsStringSync(jsonEncode(value), flush: true);
      _replaceAtomically(temporary, file);
      _persistenceWarning = null;
    } on Object catch (error) {
      _persistenceWarning = 'Could not persist Mosaic state: $error';
      stderr.writeln(_persistenceWarning);
    }
  }

  String? _statePath() {
    if (!_persistenceEnabled) return null;
    final requested = Platform.environment['MOSAIC_APP_STATE_PATH'];
    if (requested != null && requested.trim().isNotEmpty) return requested;
    final environment = Platform.environment;
    late final String root;
    if (Platform.isWindows) {
      root = environment['LOCALAPPDATA'] ?? '';
    } else if (Platform.isMacOS || Platform.isIOS) {
      final home = environment['HOME'] ?? '';
      root = home.isEmpty ? '' : _joinPath(home, 'Library/Application Support');
    } else {
      final home = environment['HOME'] ?? '';
      root = environment['XDG_DATA_HOME'] ??
          (home.isEmpty ? '' : _joinPath(home, '.local/share'));
    }
    if (root.isEmpty) return null;
    return _joinPath(_joinPath(root, _applicationId), _stateFileName);
  }

  Map<String, Object?> _withPersistenceWarning(Map<String, Object?> update) {
    final warning = _persistenceWarning;
    if (warning == null) return update;
    final augmented = <String, Object?>{...update, 'persistenceWarning': warning};
    final props = update['props'];
    if (props is Map && props.containsKey('storage-warning')) {
      augmented['props'] = <String, Object?>{
        ...props.cast<String, Object?>(),
        'storage-warning': warning,
      };
    }
    return augmented;
  }

  static void _replaceAtomically(File temporary, File target) {
    if (!Platform.isWindows) {
      temporary.renameSync(target.path);
      return;
    }
    final moveFileEx = DynamicLibrary.open('kernel32.dll')
        .lookupFunction<_MoveFileExNative, _MoveFileEx>('MoveFileExW');
    final source = temporary.path.toNativeUtf16();
    final destination = target.path.toNativeUtf16();
    try {
      const moveFileReplaceExisting = 0x1;
      const moveFileWriteThrough = 0x8;
      final moved = moveFileEx(
        source,
        destination,
        moveFileReplaceExisting | moveFileWriteThrough,
      );
      if (moved == 0) {
        throw FileSystemException(
          'MoveFileExW could not atomically replace Mosaic state',
          target.path,
        );
      }
    } finally {
      calloc.free(destination);
      calloc.free(source);
    }
  }

  Object? _invokeInput(Object? value, _InputOperation operation) {
    final encoded = utf8.encode(jsonEncode(value));
    final bytes = calloc<Uint8>(encoded.length);
    final input = calloc<_MosaicBytes>();
    final output = calloc<_MosaicBuffer>();
    try {
      if (encoded.isNotEmpty) {
        bytes.asTypedList(encoded.length).setAll(0, encoded);
      }
      input.ref
        ..ptr = encoded.isEmpty ? nullptr : bytes
        ..len = encoded.length;
      final status = operation(input.ref, output);
      return _consume(status, output.ref);
    } finally {
      calloc.free(output);
      calloc.free(input);
      calloc.free(bytes);
    }
  }

  Object? _invokeOutput(_OutputOperation operation) {
    final output = calloc<_MosaicBuffer>();
    try {
      final status = operation(output);
      return _consume(status, output.ref);
    } finally {
      calloc.free(output);
    }
  }

  Object? _consume(int status, _MosaicBuffer buffer) {
    try {
      final bytes = buffer.len == 0
          ? const <int>[]
          : buffer.ptr.asTypedList(buffer.len).toList(growable: false);
      final text = utf8.decode(bytes);
      if (status != 0) throw MosaicRuntimeException(status, text);
      return jsonDecode(text);
    } finally {
      _bufferFree(buffer);
    }
  }

  void _ensureOpen() {
    if (_app == nullptr) throw StateError('Mosaic runtime is closed');
  }

  static List<String> _libraryNames() {
    if (Platform.isWindows) return const <String>['mosaic_app.dll'];
    if (Platform.isMacOS || Platform.isIOS) {
      return const <String>['libmosaic_app.dylib', 'mosaic_app.dylib'];
    }
    return const <String>['libmosaic_app.so', 'mosaic_app.so'];
  }

  static String _platformName() {
    if (Platform.isAndroid) return 'android';
    if (Platform.isWindows) return 'windows';
    if (Platform.isMacOS || Platform.isIOS) return 'apple';
    if (Platform.isLinux) return 'linux';
    return 'web';
  }

  static Map<String, Object?> _stringMap(Map value) =>
      Map<String, Object?>.fromEntries(
        value.entries
            .where((entry) => entry.key is String)
            .map((entry) => MapEntry(entry.key as String, entry.value)),
      );

  static Map<String, Object?> _requireMap(Object? value, String kind) {
    if (value is Map) return _stringMap(value);
    throw FormatException('Mosaic runtime returned a non-object $kind');
  }

  static String _joinPath(String parent, String child) {
    final separator = Platform.pathSeparator;
    return parent.endsWith(separator) ? '$parent$child' : '$parent$separator$child';
  }
}

final class MosaicRuntimeException implements Exception {
  const MosaicRuntimeException(this.status, this.message);

  final int status;
  final String message;

  @override
  String toString() => 'Mosaic runtime error $status: $message';
}
