// AUTO-GENERATED by Mosaic. Edits will be overwritten on next emit.
//
// mosaic_platform_effects_core.dart -- the operating-system capabilities
// Mosaic provides on Flutter, shared by every generated app (UI87 §7, §7.7).
//
// Generated by mosaic-app-bindings; do not edit in a generated project. An app
// that needs different behaviour for a standard kind claims that kind in its
// own `[host_effects]` handler instead (UI87 §7.2).
//
// What it answers
// ---------------
//
//   files.open  { accept: [MIME...] }
//               -> ok { name, mimeType, bytes (base64) } | cancelled {} | failed { message }
//   files.save  { suggestedName, accept: [MIME...], bytes (base64) }
//               -> ok { name } | cancelled {} | failed { message }
//
// These are UI59's and UI87's contracts, answered exactly as the Compose,
// SwiftUI, Qt and XAML libraries answer them: the same limits, MIME table,
// plain-name rule, executable list and failure messages. A name is returned,
// never a path: a path would tell the app (and anything it logs) where the
// person keeps files.
//
// Routing
// -------
//
// The generated main.dart installs the app's own handler first, then this,
// which wraps it. Each effect is routed by kind:
//
//   kind the app claims ........ the app's handler
//   files.open / files.save .... this library
//   anything else .............. the app's handler if it claimed nothing
//                                (the original meaning), otherwise nobody --
//                                and the host fails an unanswered Await
//                                rather than leaving it pending.
//
// Threading
// ---------
//
// A Dart isolate is single-threaded, so there is no lock to hold and no
// thread to marshal an answer onto: the host calls the handler inside its
// settle, and an answer given later arrives on a later turn of the same
// isolate's event loop. What remains is ordering and cost:
//
//   1. The handler DEFERS each standard effect before anything asynchronous
//      starts. A handler cannot wait for a dialog -- it is a synchronous
//      callback -- and an effect that is neither answered nor deferred by
//      the time it returns is swept and failed by the host.
//   2. The dialog is started from a microtask, after the settle has returned,
//      as XAML starts its picker from the DispatcherQueue: nothing the
//      dialog does can reach the host half-way through a settle.
//   3. The file itself is read (up to 50 MiB, then base64-encoded) or written
//      and flushed in a short-lived background isolate (`Isolate.run`), so a
//      large file never stalls the frame the UI isolate is drawing. The
//      outcome comes back to the UI isolate, which gives the answer.
//
// Nothing may escape that work. Once deferred, an effect is out of the host's
// fail sweep, so an exception that ended the future would leave the Await
// pending for the life of the process -- and the runtime refuses to snapshot
// while anything is pending. Every path ends in `completeEffect`, with
// `failed` when nothing better is known.
//
// The answer goes to the runtime that asked. The router holds the host
// INSTANCE it was installed on (never a static facade), and the generated
// shell's retried start disposes that host and loads a new one with its own
// router. A late answer therefore meets the disposed host, whose
// `completeEffect` throws, and is dropped; it can never settle the new
// runtime's effect that happens to reuse the id (the XAML library had to add
// `EffectScope` to get the same property, UI87 §7.6).
//
// What compiles where
// -------------------
//
// This file is plain Dart (dart:io, dart:ffi, package:ffi), so the headless
// conformance harness runs it on the Dart VM with a fake host and fake
// dialogs. The dialogs themselves need the Flutter engine: they live in
// `mosaic_platform_effects.dart`, which re-exports this file and is the one
// the generated main.dart imports. Dart has no conditional compilation, so
// the split is two files rather than XAML's one fenced file.

import 'dart:async';
import 'dart:convert';
import 'dart:ffi';
import 'dart:io';
import 'dart:isolate';
import 'dart:math';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

import 'mosaic_host.dart';

/// The shape of a host's effect handler: `(id, kind, payload, delivery)`.
typedef MosaicEffectHandler =
    void Function(int id, String kind, Object? payload, String delivery);

/// The effect kinds this library answers unless an app claims them.
const Set<String> mosaicStandardEffectKinds = <String>{
  'files.open',
  'files.save',
};

/// The largest file `files.open` reads (UI59 parity with every other host).
const int mosaicMaxOpenBytes = 50 * 1024 * 1024;

/// The largest payload `files.save` writes (UI87 §3.1).
const int mosaicMaxSaveBytes = 16 * 1024 * 1024;

/// Whether this platform has the file dialogs this library drives.
///
/// `file_selector` shows native dialogs on Linux, macOS and Windows. Android
/// and iOS need a document picker and a share sheet (UI87 §7.1, UI89), which
/// this library does not have yet; there each request fails with a message
/// rather than pretending the person cancelled.
bool get mosaicPlatformHasFileDialogs =>
    Platform.isLinux || Platform.isMacOS || Platform.isWindows;

/// The two dialogs, behind an interface so a test can answer them without a
/// display. Each returns the chosen file's full path, or null when the person
/// cancelled. Asynchronous because every Flutter plugin call is.
abstract interface class MosaicFileDialogs {
  Future<String?> chooseFileToOpen(List<String> extensions);

  Future<String?> chooseFileToSave(
    String suggestedName,
    List<String> extensions,
  );
}

/// What the router needs from a host: the handler slot, deferral and the
/// answer. [MosaicHostEffects] adapts the generated [MosaicHost]; a test
/// supplies a fake, so routing and deferral run without a Rust runtime.
abstract interface class MosaicPlatformEffectHost {
  MosaicEffectHandler? get effectHandler;

  set effectHandler(MosaicEffectHandler? handler);

  /// Take ownership of an awaited effect; false when it is not awaited.
  bool deferEffect(int id);

  /// Answer an effect. Throws when the host can no longer take the answer
  /// (disposed, or no runtime at all); the router drops it then.
  void completeEffect(int id, Map<String, Object?> result);
}

/// The generated [MosaicHost], seen through [MosaicPlatformEffectHost].
///
/// Bound to the ONE host it wraps, which owns one runtime: after
/// `dispose()` that runtime's `completeEffect` throws, so an answer that
/// arrives after a retried start is refused rather than delivered to the
/// runtime that replaced it.
final class MosaicHostEffects implements MosaicPlatformEffectHost {
  MosaicHostEffects(this.host);

  final MosaicHost host;

  @override
  MosaicEffectHandler? get effectHandler => host.effectHandler;

  @override
  set effectHandler(MosaicEffectHandler? handler) {
    host.effectHandler = handler;
  }

  @override
  bool deferEffect(int id) => host.deferEffect(id);

  @override
  void completeEffect(int id, Map<String, Object?> result) {
    // `MosaicHost.completeEffect` returns null only when there is no runtime
    // behind the host: nothing can take the answer.
    if (host.completeEffect(id, result) == null) {
      throw StateError('this Mosaic host has no runtime to answer');
    }
  }
}

// ── The contract's tables ─────────────────────────────────────────────────
//
// The MIME types an app names, and the extensions a dialog filters on -- the
// same table, in the same order, as the Compose library (a Rust test pins the
// two together). A type this table does not know is dropped rather than
// failing the request (UI59 §3). Extensions are bare, with no leading dot:
// `file_selector` turns `json` into the Linux and Windows filter `*.json`,
// and a leading dot would make it `*..json`.
const List<(String, List<String>)> _mosaicMimeExtensions =
    <(String, List<String>)>[
      ('application/json', <String>['json']),
      ('text/plain', <String>['txt']),
      ('text/markdown', <String>['md', 'markdown']),
      ('text/csv', <String>['csv']),
      ('application/pdf', <String>['pdf']),
      ('application/zip', <String>['zip']),
      ('image/jpeg', <String>['jpg', 'jpeg']),
      ('image/png', <String>['png']),
      ('image/webp', <String>['webp']),
      ('image/gif', <String>['gif']),
      ('image/bmp', <String>['bmp']),
      ('image/tiff', <String>['tif', 'tiff']),
      ('image/svg+xml', <String>['svg']),
    ];

/// Extensions that run when the file is opened, on some platform: when an app
/// names no type (`accept` empty) a save may not end in one of these, so a
/// `files.save` cannot drop a launcher next to the person's documents. When
/// the app does name types, the name must already end in one of theirs. One
/// list on every host (a Rust test pins it to the Compose library's).
const Set<String> mosaicExecutableExtensions = <String>{
  // macOS: Terminal scripts, Finder location files and installers open
  // with no prompt, or install.
  'command', 'terminal', 'tool', 'webloc', 'inetloc', 'fileloc', 'afploc', 'ftploc',
  'mailloc', 'newsloc', 'atloc', 'app', 'pkg', 'mpkg', 'dmg', 'mobileconfig', 'scpt',
  'applescript', 'workflow',
  // Windows: run, install, or leak credentials when merely browsed.
  'exe', 'com', 'bat', 'cmd', 'scr', 'pif', 'msi', 'msp', 'msc', 'lnk', 'url', 'hta',
  'cpl', 'chm', 'inf', 'vbs', 'vbe', 'js', 'jse', 'wsf', 'wsh', 'ws', 'wsc', 'sct',
  'ps1', 'psm1', 'reg', 'jar', 'jnlp', 'gadget', 'xll', 'appref-ms', 'application',
  'settingcontent-ms', 'appx', 'msix', 'appinstaller', 'diagcab', 'scf',
  'library-ms', 'searchconnector-ms', 'iso', 'img', 'vhd', 'vhdx',
  // Linux desktops.
  'desktop', 'sh', 'run', 'appimage', 'deb', 'rpm', 'flatpakref',
};

// ── Outcomes ──────────────────────────────────────────────────────────────
//
// Plain maps, which the host encodes as JSON:
// `{"ok": {...}}`, `{"cancelled": {}}`, `{"failed": {"message": ...}}`.

Map<String, Object?> _mosaicOk(Map<String, Object?> value) =>
    <String, Object?>{'ok': value};

Map<String, Object?> _mosaicCancelled() => <String, Object?>{
  'cancelled': <String, Object?>{},
};

/// The `failed` outcome with [message], which the app sees.
Map<String, Object?> mosaicFailed(String message) => <String, Object?>{
  'failed': <String, Object?>{'message': message},
};

// ── Reading the payload ───────────────────────────────────────────────────
//
// The payload is whatever the app sent. Anything that is not the expected
// shape reads as absent, never as an exception: `files.open` with no `accept`
// is "any file", and `files.save` with no `suggestedName` fails the
// plain-name rule like an empty one.

String? _mosaicText(Object? payload, String key) {
  final value = payload is Map ? payload[key] : null;
  return value is String ? value : null;
}

/// The extensions for the accepted MIME types, deduplicated, in order.
List<String> mosaicExtensionsFor(Object? payload) {
  final accept = payload is Map ? payload['accept'] : null;
  final extensions = <String>[];
  if (accept is! List) return extensions;
  for (final mime in accept) {
    if (mime is! String) continue;
    for (final (rowMime, rowExtensions) in _mosaicMimeExtensions) {
      if (rowMime != mime) continue;
      for (final extension in rowExtensions) {
        if (!extensions.contains(extension)) extensions.add(extension);
      }
    }
  }
  return extensions;
}

/// The text after the last `.` of a file name, or empty.
String _mosaicExtensionOf(String name) {
  final dot = name.lastIndexOf('.');
  return dot < 0 ? '' : name.substring(dot + 1);
}

String _mosaicMimeTypeFor(String name) {
  final extension = _mosaicExtensionOf(name).toLowerCase();
  for (final (mime, extensions) in _mosaicMimeExtensions) {
    if (extensions.contains(extension)) return mime;
  }
  return 'application/octet-stream';
}

/// The last component of [path]: the name the app is told, never the path.
String _mosaicBaseName(String path) {
  final separators = Platform.isWindows ? RegExp(r'[\\/]') : RegExp('/');
  return path.split(separators).last;
}

/// A deep copy of a JSON-shaped value: maps and lists are copied, strings,
/// numbers, booleans and null are immutable and shared.
///
/// The payload belongs to the host's parsed update, which the host is free to
/// keep, change or drop once the handler returns; the dialog answers long
/// after that. XAML's harness proved the request fails without its copy there
/// (UI87 §7.6), so the same discipline is kept here.
Object? _mosaicCopyJson(Object? value) {
  if (value is Map) {
    return <Object?, Object?>{
      for (final entry in value.entries)
        entry.key: _mosaicCopyJson(entry.value),
    };
  }
  if (value is List) {
    return <Object?>[for (final item in value) _mosaicCopyJson(item)];
  }
  return value;
}

// ── The plain-name rule ───────────────────────────────────────────────────
//
// Dart has no Unicode general-category API, but its regular expressions do,
// in Unicode mode: `\p{Cf}` is "format", `\p{Cn}` "unassigned", and so on.
// The tables are the Dart VM's own, as the Compose rule's are the JDK's.

/// Control, format, line and paragraph separators, surrogates, unassigned and
/// private-use code points: none belongs in a file name.
final RegExp _mosaicRefusedCharacter = RegExp(
  r'^[\p{Cc}\p{Cf}\p{Zl}\p{Zp}\p{Cs}\p{Cn}\p{Co}]$',
  unicode: true,
);

/// Unicode's space, line and paragraph separators (no-break spaces included).
final RegExp _mosaicSeparatorCharacter = RegExp(
  r'^[\p{Zs}\p{Zl}\p{Zp}]$',
  unicode: true,
);

/// A suggested name is a plain file name (UI87 §3.1), so an app cannot steer
/// the dialog, or disguise what it is saving -- the same rule as the Compose
/// library:
///
/// - no directory separators, and not `.` or `..` -- no other directory;
/// - no leading `.` -- a hidden dot-file such as `.zshrc` is configuration a
///   shell or tool runs, not a document;
/// - no `:` -- on Windows `D:x` names another drive, and `x:y` an alternate
///   data stream;
/// - no control, format, line- or paragraph-separator characters -- a
///   right-to-left override can make `invoice<RLO>fdp.exe` read as a PDF in
///   the dialog, and a separator breaks the name across lines;
/// - no lone surrogate, unassigned or private-use code point -- they mean
///   different things to different runtimes' Unicode tables;
/// - no leading or trailing whitespace of any kind (a no-break space
///   included), no run of two or more, and no trailing dot, which Windows
///   silently strips -- `report.pdf` padded out and ending `.command` hides
///   its real extension. Blank-rendering characters (Hangul fillers, BRAILLE
///   PATTERN BLANK) count as whitespace, and invisible (default-ignorable)
///   characters are dropped before these padding and dot rules;
/// - at most 255 UTF-16 units.
///
/// Checked by code point, so a format character outside the BMP (the tag
/// characters, U+E0000..) is caught as well as one inside it.
bool mosaicIsPlainFileName(String name) {
  if (name.isEmpty || name.length > 255 || name == '.' || name == '..') {
    return false;
  }
  final points = _mosaicCodePoints(name);
  if (points == null) return false;
  for (final point in points) {
    if (point == 0x2F || point == 0x5C || point == 0x3A) return false; // / \ :
    if (_mosaicRefusedCharacter.hasMatch(String.fromCharCode(point))) {
      return false;
    }
  }
  // The padding and dot rules look at what is visible: invisible characters
  // cannot split a run of spaces or hide a leading or trailing dot.
  final visible = <int>[
    for (final point in points)
      if (!_mosaicIsInvisible(point)) point,
  ];
  if (visible.isEmpty) return false;
  if (visible.first == 0x2E || visible.last == 0x2E) return false; // .
  if (_mosaicIsSpace(visible.first) || _mosaicIsSpace(visible.last)) {
    return false;
  }
  for (var index = 1; index < visible.length; index += 1) {
    if (_mosaicIsSpace(visible[index - 1]) && _mosaicIsSpace(visible[index])) {
      return false;
    }
  }
  return true;
}

/// The code points of [name], or null when it holds a lone surrogate (which
/// cannot be a file name). Walked by hand over UTF-16 units: `String.runes`
/// would hand a lone surrogate back as if it were a code point, and a JSON
/// payload can carry one (`"\ud800"`).
List<int>? _mosaicCodePoints(String name) {
  final points = <int>[];
  for (var index = 0; index < name.length; index += 1) {
    final unit = name.codeUnitAt(index);
    if (unit >= 0xD800 && unit <= 0xDBFF) {
      if (index + 1 >= name.length) return null;
      final next = name.codeUnitAt(index + 1);
      if (next < 0xDC00 || next > 0xDFFF) return null;
      points.add(0x10000 + ((unit - 0xD800) << 10) + (next - 0xDC00));
      index += 1;
    } else if (unit >= 0xDC00 && unit <= 0xDFFF) {
      return null;
    } else {
      points.add(unit);
    }
  }
  return points;
}

/// Characters that are not whitespace to Unicode but render as a wide blank,
/// so they pad a name just as well: the Hangul fillers and BRAILLE PATTERN
/// BLANK. Whitespace for the padding rules.
bool _mosaicIsBlank(int point) =>
    point == 0x115F ||
    point == 0x1160 ||
    point == 0x2800 ||
    point == 0x3164 ||
    point == 0xFFA0;

/// Whitespace as the Compose library means it: Java's
/// `isWhitespace || isSpaceChar` -- every space, line and paragraph
/// separator (no-break spaces included), the ASCII whitespace controls --
/// plus the blanks above.
bool _mosaicIsSpace(int point) =>
    (point >= 0x09 && point <= 0x0D) ||
    (point >= 0x1C && point <= 0x1F) ||
    _mosaicIsBlank(point) ||
    _mosaicSeparatorCharacter.hasMatch(String.fromCharCode(point));

/// Unicode's Default_Ignorable_Code_Point, minus the blanks above: variation
/// selectors, COMBINING GRAPHEME JOINER and the like -- the same ranges as the
/// Compose library. Dropped before the padding and dot rules, so
/// `<space><VS1><space>` is still a run while an emoji's own selector
/// (`❤️ list.txt`) is fine.
bool _mosaicIsInvisible(int point) =>
    !_mosaicIsBlank(point) &&
    (point == 0x00AD ||
        point == 0x034F ||
        point == 0x061C ||
        (point >= 0x115F && point <= 0x1160) ||
        (point >= 0x17B4 && point <= 0x17B5) ||
        (point >= 0x180B && point <= 0x180F) ||
        (point >= 0x200B && point <= 0x200F) ||
        (point >= 0x202A && point <= 0x202E) ||
        (point >= 0x2060 && point <= 0x206F) ||
        point == 0x3164 ||
        (point >= 0xFE00 && point <= 0xFE0F) ||
        point == 0xFEFF ||
        point == 0xFFA0 ||
        (point >= 0xFFF0 && point <= 0xFFF8) ||
        (point >= 0x1BCA0 && point <= 0x1BCA3) ||
        (point >= 0x1D173 && point <= 0x1D17A) ||
        (point >= 0xE0000 && point <= 0xE0FFF));

/// True when [name] ends in an extension from [mosaicExecutableExtensions].
bool mosaicHasExecutableExtension(String name) {
  // Folded through upper case first: `ſ` (LONG S) lowercases to itself but
  // is `S` to a case-insensitive file system.
  return name.contains('.') &&
      mosaicExecutableExtensions.contains(
        _mosaicExtensionOf(name).toUpperCase().toLowerCase(),
      );
}

// ── files.open ────────────────────────────────────────────────────────────

/// `files.open`: the outcome map, never an exception from the file. (A
/// dialog that throws is the router's to answer, as on every other host.)
Future<Map<String, Object?>> mosaicRunFilesOpen(
  Object? payload,
  MosaicFileDialogs dialogs,
) async {
  final chosen = await dialogs.chooseFileToOpen(mosaicExtensionsFor(payload));
  if (chosen == null) return _mosaicCancelled();
  // Up to 50 MiB read and base64-encoded: in a background isolate, not the
  // UI isolate that is drawing frames.
  return _mosaicReadInBackground(chosen);
}

/// [_mosaicReadOpened] in a short-lived isolate.
///
/// A top-level function whose closure captures only [path]: `Isolate.run`
/// copies what its closure captures into the new isolate, and a closure made
/// inside a method that touched `this` could capture the router -- and with
/// it a host holding native pointers, which cannot be sent. The result (the
/// base64 text) comes back without a copy (`Isolate.exit`).
Future<Map<String, Object?>> _mosaicReadInBackground(String path) =>
    Isolate.run(() => _mosaicReadOpened(path));

/// The `files.open` outcome for a chosen path: read, typed, encoded.
///
/// Read at most [mosaicMaxOpenBytes], bounded while reading, not by checking
/// the length first: a file can grow between a check and a read, which is
/// the TOCTOU the first XAML handler's review found (#15218).
///
/// The type is checked on the path, following a link the person chose: a
/// directory, a missing file, a pipe or a device is "not a regular file".
/// Dart has neither `O_NONBLOCK` nor `fstat`, so unlike the SwiftUI and Qt
/// libraries this cannot re-check the type on the opened descriptor; a FIFO
/// swapped in between the check and the open would block this background
/// isolate (never the UI) until something writes to it (UI87 §7.7).
Map<String, Object?> _mosaicReadOpened(String path) {
  if (FileSystemEntity.typeSync(path) != FileSystemEntityType.file) {
    return mosaicFailed('that is not a regular file');
  }
  RandomAccessFile? handle;
  try {
    handle = File(path).openSync();
    final builder = BytesBuilder(copy: false);
    while (true) {
      final chunk = handle.readSync(64 * 1024);
      if (chunk.isEmpty) break;
      if (builder.length + chunk.length > mosaicMaxOpenBytes) {
        return mosaicFailed(
          'the selected file is larger than $mosaicMaxOpenBytes bytes',
        );
      }
      builder.add(chunk);
    }
    final name = _mosaicBaseName(path);
    return _mosaicOk(<String, Object?>{
      'name': name,
      'mimeType': _mosaicMimeTypeFor(name),
      'bytes': base64Encode(builder.takeBytes()),
    });
  } on Object {
    // Not the exception's own text: it can carry the full local path, and a
    // failure message is data the app sees.
    return mosaicFailed("couldn't read the selected file");
  } finally {
    try {
      handle?.closeSync();
    } on Object {
      // Closing a read-only handle has nothing left to lose.
    }
  }
}

// ── files.save ────────────────────────────────────────────────────────────

/// True when every character is in the base64 alphabet or is padding.
///
/// Checked before decoding because Dart's decoder also accepts the URL-safe
/// alphabet (`-`, `_`) and percent-encoded padding (`%3D`), which the Compose
/// and SwiftUI decoders refuse; the same payload should not save on one host
/// and fail on another.
bool _mosaicIsBase64Alphabet(String encoded) {
  for (final unit in encoded.codeUnits) {
    final ok =
        (unit >= 0x41 && unit <= 0x5A) || // A-Z
        (unit >= 0x61 && unit <= 0x7A) || // a-z
        (unit >= 0x30 && unit <= 0x39) || // 0-9
        unit == 0x2B || // +
        unit == 0x2F || // /
        unit == 0x3D; // =
    if (!ok) return false;
  }
  return true;
}

/// `files.save`: the outcome map, never an exception from the file.
Future<Map<String, Object?>> mosaicRunFilesSave(
  Object? payload,
  MosaicFileDialogs dialogs,
) async {
  final suggestedName = _mosaicText(payload, 'suggestedName') ?? '';
  if (!mosaicIsPlainFileName(suggestedName)) {
    return mosaicFailed('suggestedName must be a plain file name');
  }
  final encoded = _mosaicText(payload, 'bytes');
  if (encoded == null) return mosaicFailed('bytes must be base64 text');
  // Checked on the encoded length before decoding, so an oversized payload is
  // refused without allocating its decoded copy (4 base64 chars = 3 bytes).
  if (encoded.length > (mosaicMaxSaveBytes ~/ 3 + 1) * 4) {
    return mosaicFailed('the file is larger than $mosaicMaxSaveBytes bytes');
  }
  final Uint8List bytes;
  try {
    if (!_mosaicIsBase64Alphabet(encoded)) {
      return mosaicFailed('bytes must be base64 text');
    }
    bytes = base64Decode(encoded);
  } on FormatException {
    return mosaicFailed('bytes must be base64 text');
  }
  if (bytes.length > mosaicMaxSaveBytes) {
    return mosaicFailed('the file is larger than $mosaicMaxSaveBytes bytes');
  }
  // When the app says what it is saving, the name must agree: a JSON export
  // cannot be offered as `notes.exe`. Compared as Compose compares it (lower
  // case, no upper-case fold): the fold is for catching launchers, not for
  // widening what matches a type.
  final extensions = mosaicExtensionsFor(payload);
  final lowered = suggestedName.toLowerCase();
  if (extensions.isNotEmpty &&
      !extensions.any((extension) => lowered.endsWith('.$extension'))) {
    return mosaicFailed(
      'suggestedName must end in an extension of an accepted type',
    );
  }
  if (extensions.isEmpty && mosaicHasExecutableExtension(suggestedName)) {
    return mosaicFailed(
      'suggestedName must not end in an executable extension',
    );
  }
  final target = await dialogs.chooseFileToSave(suggestedName, extensions);
  if (target == null) return _mosaicCancelled();
  // Up to 16 MiB written and flushed to disk: in a background isolate, as the
  // read in files.open is. _mosaicWriteReplacing never throws.
  return _mosaicWriteInBackground(target, bytes);
}

/// [_mosaicWriteReplacing] in a short-lived isolate; see
/// [_mosaicReadInBackground] for why this is a top-level function.
Future<Map<String, Object?>> _mosaicWriteInBackground(
  String target,
  Uint8List bytes,
) => Isolate.run(() => _mosaicWriteReplacing(target, bytes));

/// Write [bytes] where the person chose and return the `files.save` outcome.
///
/// Written beside the target first and moved into place in one step, so an
/// interrupted save never leaves a half-written file where the person's old
/// one was.
Map<String, Object?> _mosaicWriteReplacing(String target, Uint8List bytes) {
  try {
    final full = File(target).absolute.path;
    final name = _mosaicBaseName(full);
    if (name.isEmpty) return mosaicFailed("couldn't save the file");
    final directory = File(full).parent.path;
    final saved = Platform.isWindows
        ? _mosaicSaveWindows(directory, full, bytes)
        : _mosaicSavePosix(directory, full, bytes);
    return saved
        ? _mosaicOk(<String, Object?>{'name': name})
        : mosaicFailed("couldn't save the file");
  } on Object {
    return mosaicFailed("couldn't save the file");
  }
}

/// A name nobody else will pick: `.mosaic-save-<32 hex>`.
String _mosaicTemporaryName() {
  final random = Random.secure();
  final hex = StringBuffer();
  for (var index = 0; index < 16; index += 1) {
    hex.write(random.nextInt(256).toRadixString(16).padLeft(2, '0'));
  }
  return '.mosaic-save-$hex.tmp';
}

/// Write [bytes] and flush them to disk (`fsync`) before anything moves.
void _mosaicWriteFlushed(File file, Uint8List bytes) {
  final handle = file.openSync(mode: FileMode.writeOnly);
  try {
    handle.writeFromSync(bytes);
    handle.flushSync();
  } finally {
    handle.closeSync();
  }
}

/// The POSIX save (Linux, macOS).
///
/// Dart creates files `0666 & ~umask` and has no way to create one owner-only
/// or to `fchmod` an open handle, so the owner-only step the Compose, Qt and
/// XAML libraries take on the temporary file is taken on a DIRECTORY instead:
///
///   1. `mkdir(<folder>/.mosaic-save-<random>.tmp, 0700)` through libc -- one
///      call, owner-only from the start, and it fails if the name exists, so
///      a planted directory or link is refused, not reused;
///   2. the bytes are written into a file inside it and flushed to disk --
///      nobody else can reach that file, whatever its own mode, because
///      nobody else can enter the directory;
///   3. that file is given the rwx bits of the regular file it replaces
///      (never setuid, setgid or sticky), or stays owner-only (0600) for a
///      new name, by `chmod` on a path inside the private directory, which
///      nobody else can swap;
///   4. it is renamed onto the chosen path (`rename(2)`: one step, on the same
///      file system), and the empty directory is removed.
bool _mosaicSavePosix(String directory, String full, Uint8List bytes) {
  // The replaced file's rwx bits -- only from a regular file, not a link.
  var mode = 0x180; // 0600
  if (FileSystemEntity.typeSync(full, followLinks: false) ==
      FileSystemEntityType.file) {
    mode = File(full).statSync().mode & 0x1FF; // user, group, other: rwx
  }
  final privateDirectory = '$directory/${_mosaicTemporaryName()}';
  if (_mosaicLibcPathMode('mkdir', privateDirectory, 0x1C0) != 0) return false; // 0700
  try {
    final written = File('$privateDirectory/contents');
    _mosaicWriteFlushed(written, bytes);
    if (_mosaicLibcPathMode('chmod', written.path, mode) != 0) return false;
    written.renameSync(full);
    return true;
  } finally {
    try {
      Directory(privateDirectory).deleteSync(recursive: true);
    } on Object {
      // Best effort: owner-only, and empty once the rename has happened.
    }
  }
}

/// Call a libc `int f(const char *path, mode_t mode)` -- `mkdir` or `chmod`.
///
/// `mode_t` is 32 bits on Linux and 16 on Apple platforms; the value always
/// fits in 16, and each signature is declared as the platform declares it.
int _mosaicLibcPathMode(String symbol, String path, int mode) {
  final libc = DynamicLibrary.process();
  final int Function(Pointer<Utf8>, int) call =
      Platform.isMacOS || Platform.isIOS
      ? libc.lookupFunction<
          Int32 Function(Pointer<Utf8>, Uint16),
          int Function(Pointer<Utf8>, int)
        >(symbol)
      : libc.lookupFunction<
          Int32 Function(Pointer<Utf8>, Uint32),
          int Function(Pointer<Utf8>, int)
        >(symbol);
  final native = path.toNativeUtf8();
  try {
    return call(native, mode);
  } finally {
    malloc.free(native);
  }
}

typedef _MosaicMoveFileExNative =
    Int32 Function(Pointer<Utf16>, Pointer<Utf16>, Uint32);
typedef _MosaicMoveFileEx = int Function(Pointer<Utf16>, Pointer<Utf16>, int);

/// The Windows save: a temporary created exclusively beside the target,
/// written and flushed, then `MoveFileExW(MOVEFILE_REPLACE_EXISTING |
/// MOVEFILE_WRITE_THROUGH)` -- the move the generated host uses for its own
/// state file. A new file inherits the folder's ACL, and so does a replaced
/// one, as with the Compose and Qt libraries (XAML's `File.Replace` keeps the
/// old file's ACL; that is recorded as the difference, UI87 §7.7).
bool _mosaicSaveWindows(String directory, String full, Uint8List bytes) {
  final temporary = File('$directory\\${_mosaicTemporaryName()}');
  var created = false;
  try {
    temporary.createSync(exclusive: true);
    created = true;
    _mosaicWriteFlushed(temporary, bytes);
    final moveFileEx = DynamicLibrary.open(
      'kernel32.dll',
    ).lookupFunction<_MosaicMoveFileExNative, _MosaicMoveFileEx>('MoveFileExW');
    final source = temporary.path.toNativeUtf16();
    final destination = full.toNativeUtf16();
    try {
      const moveFileReplaceExisting = 0x1;
      const moveFileWriteThrough = 0x8;
      final moved = moveFileEx(
        source,
        destination,
        moveFileReplaceExisting | moveFileWriteThrough,
      );
      if (moved == 0) return false;
      created = false;
      return true;
    } finally {
      malloc.free(destination);
      malloc.free(source);
    }
  } finally {
    if (created) {
      try {
        temporary.deleteSync();
      } on Object {
        // Best effort.
      }
    }
  }
}

// ── Routing and installation ──────────────────────────────────────────────

/// Route one effect (UI87 §7.2). True when this library takes it, false when
/// it belongs to the app's handler, and null when nobody should answer it
/// here (the host then fails an unanswered Await).
bool? mosaicRoutesToPlatform(String kind, Set<String>? appKinds) {
  if (appKinds != null && appKinds.contains(kind)) return false;
  if (mosaicStandardEffectKinds.contains(kind)) return true;
  if (appKinds == null) return false;
  return null;
}

/// The routers installed, keyed by the handler each one set, so a second
/// install recognises the first instead of wrapping it. An `Expando` rather
/// than a field on the host: the host is the generated `MosaicHost`, which
/// knows nothing of this library.
final Expando<MosaicPlatformRouter> _mosaicRouters =
    Expando<MosaicPlatformRouter>('MosaicPlatformRouter');

/// The handler this library installs: it routes each effect by kind (UI87
/// §7.2) and answers the standard kinds itself.
final class MosaicPlatformRouter {
  MosaicPlatformRouter._(
    this._host,
    this._appHandler,
    this._appKinds,
    this._dialogs,
    this._hasDialogs,
    this._runOnUi,
  );

  final MosaicPlatformEffectHost _host;
  final MosaicEffectHandler? _appHandler;
  final Set<String>? _appKinds;
  final MosaicFileDialogs _dialogs;
  final bool _hasDialogs;
  final void Function(void Function() work) _runOnUi;

  /// One file operation at a time (UI87 §3.1): a second request while a
  /// dialog is open is failed, not queued behind it. A plain bool: the
  /// isolate is single-threaded.
  bool _busy = false;

  void handle(int id, String kind, Object? payload, String delivery) {
    switch (mosaicRoutesToPlatform(kind, _appKinds)) {
      case false:
        // The app's, delivered as it was before the router existed. An
        // exception from it reaches the host's own catch, which fails the
        // effect with the reason -- exactly as it did then.
        _appHandler?.call(id, kind, payload, delivery);
      case null:
        return; // nobody: the host fails an unanswered Await
      case true:
        _answerStandard(id, kind, payload, delivery);
    }
  }

  void _answerStandard(int id, String kind, Object? payload, String delivery) {
    // Only an Await has someone waiting for the answer.
    if (delivery.toLowerCase() != 'await') return;
    // No dialogs here (Android, iOS): answer inline, which the host allows
    // inside its settle, instead of pretending the person cancelled.
    if (!_hasDialogs) {
      _host.completeEffect(
        id,
        mosaicFailed('$kind is not available on this platform yet'),
      );
      return;
    }
    // Copied BEFORE the router is marked busy: anything that can throw
    // between taking `_busy` and handing it to `_answer` must release it, and
    // the fewer such steps the better. (A throw here reaches the host's own
    // catch, which fails the effect with the reason -- it is not deferred.)
    final request = _mosaicCopyJson(payload);
    if (_busy) {
      _host.completeEffect(
        id,
        mosaicFailed('another file operation is in progress'),
      );
      return;
    }
    _busy = true;
    // Ownership first. False means the runtime is not waiting on this id,
    // and the right move is to open no dialog at all.
    final bool owned;
    try {
      owned = _host.deferEffect(id);
    } on Object {
      _busy = false;
      rethrow;
    }
    if (!owned) {
      _busy = false;
      return;
    }
    try {
      // `_answer` catches everything it can meet, so the discarded future
      // never completes with an error.
      _runOnUi(() => unawaited(_answer(id, kind, request)));
    } on Object {
      // The scheduler refused the work. Deferred, so the host will not fail
      // it: this is the last chance to answer.
      _busy = false;
      _tryComplete(id, mosaicFailed('the file dialog failed'));
    }
  }

  Future<void> _answer(int id, String kind, Object? request) async {
    Map<String, Object?> outcome;
    try {
      outcome = kind == 'files.open'
          ? await mosaicRunFilesOpen(request, _dialogs)
          : await mosaicRunFilesSave(request, _dialogs);
    } on Object {
      // A dialog that threw (no display, a sandbox without the file-access
      // entitlement, a file with no local path) -- not its text, which can
      // carry a path.
      outcome = mosaicFailed('the file dialog failed');
    } finally {
      _busy = false;
    }
    _tryComplete(id, outcome);
  }

  void _tryComplete(int id, Map<String, Object?> outcome) {
    try {
      _host.completeEffect(id, outcome);
    } on Object {
      // The host was disposed while the dialog was open (a retried start, or
      // the window closing). Nothing is waiting any more.
    }
  }
}

/// Install the platform library on [host], wrapping whatever handler the app
/// installed. [appKinds] is the app's `[host_effects]` `kinds`, or null when
/// it declared none (the original meaning: it receives every non-standard
/// kind). [dialogs], [hasDialogs] and [runOnUi] are replaceable for tests;
/// [runOnUi] runs the dialog work after the current settle, and a throw from
/// it counts as the work refused.
///
/// Idempotent: when the host's handler is already a router, the app did not
/// reinstall its own since, and nothing changes. A retried start disposes the
/// host and loads a new one, with no handler, so it gets a new router, as it
/// gets the app's handler again.
void installMosaicPlatformRouter(
  MosaicPlatformEffectHost host, {
  required Iterable<String>? appKinds,
  required MosaicFileDialogs dialogs,
  bool? hasDialogs,
  void Function(void Function() work) runOnUi = scheduleMicrotask,
}) {
  final current = host.effectHandler;
  if (current != null && _mosaicRouters[current] != null) return;
  final router = MosaicPlatformRouter._(
    host,
    current,
    appKinds?.toSet(),
    dialogs,
    hasDialogs ?? mosaicPlatformHasFileDialogs,
    runOnUi,
  );
  final MosaicEffectHandler handler = router.handle;
  _mosaicRouters[handler] = router;
  host.effectHandler = handler;
}
