-- Tests for coding_adventures.arc2d
package.path = "../src/?.lua;../src/?/init.lua;../../trig/src/?.lua;../../trig/src/?/init.lua;../../point2d/src/?.lua;../../point2d/src/?/init.lua;../../bezier2d/src/?.lua;../../bezier2d/src/?/init.lua;" .. package.path

local arc  = require("coding_adventures.arc2d")
local p2d  = require("coding_adventures.point2d")
local trig = require("coding_adventures.trig")

local DELTA = 1e-6
local function approx(a, b) return math.abs(a - b) < DELTA end
local function pt_approx(a, b) return approx(a.x, b.x) and approx(a.y, b.y) end

local unit_arc = arc.new_center_arc(p2d.new_point(0,0), 1, 1, 0, trig.PI/2, 0)

describe("center_arc", function()
    it("eval at 0", function()
        assert.is_true(pt_approx(arc.eval_arc(unit_arc, 0), p2d.new_point(1,0)))
    end)
    it("eval at 1", function()
        assert.is_true(pt_approx(arc.eval_arc(unit_arc, 1), p2d.new_point(0,1)))
    end)
    it("eval midpoint", function()
        local expected = 1.0 / math.sqrt(2)
        local mid = arc.eval_arc(unit_arc, 0.5)
        assert.is_true(approx(mid.x, expected) and approx(mid.y, expected))
    end)
    it("bbox full circle", function()
        local full = arc.new_center_arc(p2d.new_point(0,0), 1, 1, 0, trig.TWO_PI, 0)
        local bb = arc.bbox_arc(full)
        assert.is_true(bb.x <= -0.99 and bb.x + bb.width >= 0.99)
    end)
    it("to_cubic_beziers endpoints", function()
        local curves = arc.to_cubic_beziers(unit_arc)
        assert.is_true(#curves > 0)
        assert.is_true(pt_approx(curves[1].p0, p2d.new_point(1,0)))
        assert.is_true(pt_approx(curves[#curves].p3, p2d.new_point(0,1)))
    end)
end)

describe("svg_arc", function()
    it("degenerate same point", function()
        local s = arc.new_svg_arc(p2d.new_point(1,1), p2d.new_point(1,1), 1, 1, 0, false, false)
        assert.is_nil(arc.to_center_arc(s))
    end)
    it("degenerate zero radius", function()
        local s = arc.new_svg_arc(p2d.new_point(0,0), p2d.new_point(1,0), 0, 1, 0, false, false)
        assert.is_nil(arc.to_center_arc(s))
    end)
    it("semicircle center", function()
        local s = arc.new_svg_arc(p2d.new_point(1,0), p2d.new_point(-1,0), 1, 1, 0, false, true)
        local ca = arc.to_center_arc(s)
        assert.is_not_nil(ca)
        assert.is_true(approx(ca.center.x, 0) and approx(ca.center.y, 0))
    end)
    it("semicircle endpoints reproduced", function()
        local s = arc.new_svg_arc(p2d.new_point(1,0), p2d.new_point(-1,0), 1, 1, 0, false, true)
        local ca = arc.to_center_arc(s)
        assert.is_not_nil(ca)
        assert.is_true(pt_approx(arc.eval_arc(ca, 0), p2d.new_point(1,0)))
        assert.is_true(pt_approx(arc.eval_arc(ca, 1), p2d.new_point(-1,0)))
    end)
end)
