// AUTO-GENERATED FILE — DO NOT EDIT
// Source: verilog.tokens
// Regenerate with: grammar-tools compile-tokens verilog.tokens
//
// This file embeds a TokenGrammar as native Rust data structures.
// Call `token_grammar()` instead of reading and parsing the .tokens file.

#[allow(unused_imports)]
use grammar_tools::token_grammar::{PatternGroup, TokenDefinition, TokenGrammar};
#[allow(unused_imports)]
use std::collections::HashMap;

pub fn token_grammar() -> TokenGrammar {
    TokenGrammar {
        definitions: vec![
            TokenDefinition {
                name: r#"STRING"#.to_string(),
                pattern: r#""([^"\\]|\\.)*""#.to_string(),
                is_regex: true,
                line_number: 46,
                alias: None,
            },
            TokenDefinition {
                name: r#"SIZED_NUMBER"#.to_string(),
                pattern: r#"[0-9]*'[sS]?[bBoOdDhH][0-9a-fA-F_xXzZ]+"#.to_string(),
                is_regex: true,
                line_number: 73,
                alias: None,
            },
            TokenDefinition {
                name: r#"REAL_NUMBER"#.to_string(),
                pattern: r#"[0-9]+\.[0-9]+([eE][+-]?[0-9]+)?"#.to_string(),
                is_regex: true,
                line_number: 77,
                alias: None,
            },
            TokenDefinition {
                name: r#"NUMBER"#.to_string(),
                pattern: r#"[0-9][0-9_]*"#.to_string(),
                is_regex: true,
                line_number: 81,
                alias: None,
            },
            TokenDefinition {
                name: r#"SYSTEM_ID"#.to_string(),
                pattern: r#"\$[a-zA-Z_][a-zA-Z0-9_$]*"#.to_string(),
                is_regex: true,
                line_number: 109,
                alias: None,
            },
            TokenDefinition {
                name: r#"DIRECTIVE"#.to_string(),
                pattern: r#"`[a-zA-Z_][a-zA-Z0-9_]*"#.to_string(),
                is_regex: true,
                line_number: 110,
                alias: None,
            },
            TokenDefinition {
                name: r#"ESCAPED_IDENT"#.to_string(),
                pattern: r#"\\[^ \t\r\n]+"#.to_string(),
                is_regex: true,
                line_number: 111,
                alias: None,
            },
            TokenDefinition {
                name: r#"NAME"#.to_string(),
                pattern: r#"[a-zA-Z_][a-zA-Z0-9_$]*"#.to_string(),
                is_regex: true,
                line_number: 114,
                alias: None,
            },
            TokenDefinition {
                name: r#"ARITH_LEFT_SHIFT"#.to_string(),
                pattern: r#"<<<"#.to_string(),
                is_regex: false,
                line_number: 126,
                alias: None,
            },
            TokenDefinition {
                name: r#"ARITH_RIGHT_SHIFT"#.to_string(),
                pattern: r#">>>"#.to_string(),
                is_regex: false,
                line_number: 127,
                alias: None,
            },
            TokenDefinition {
                name: r#"CASE_EQ"#.to_string(),
                pattern: r#"==="#.to_string(),
                is_regex: false,
                line_number: 136,
                alias: None,
            },
            TokenDefinition {
                name: r#"CASE_NEQ"#.to_string(),
                pattern: r#"!=="#.to_string(),
                is_regex: false,
                line_number: 137,
                alias: None,
            },
            TokenDefinition {
                name: r#"LOGIC_AND"#.to_string(),
                pattern: r#"&&"#.to_string(),
                is_regex: false,
                line_number: 145,
                alias: None,
            },
            TokenDefinition {
                name: r#"LOGIC_OR"#.to_string(),
                pattern: r#"||"#.to_string(),
                is_regex: false,
                line_number: 146,
                alias: None,
            },
            TokenDefinition {
                name: r#"LEFT_SHIFT"#.to_string(),
                pattern: r#"<<"#.to_string(),
                is_regex: false,
                line_number: 147,
                alias: None,
            },
            TokenDefinition {
                name: r#"RIGHT_SHIFT"#.to_string(),
                pattern: r#">>"#.to_string(),
                is_regex: false,
                line_number: 148,
                alias: None,
            },
            TokenDefinition {
                name: r#"EQUALS_EQUALS"#.to_string(),
                pattern: r#"=="#.to_string(),
                is_regex: false,
                line_number: 149,
                alias: None,
            },
            TokenDefinition {
                name: r#"NOT_EQUALS"#.to_string(),
                pattern: r#"!="#.to_string(),
                is_regex: false,
                line_number: 150,
                alias: None,
            },
            TokenDefinition {
                name: r#"LESS_EQUALS"#.to_string(),
                pattern: r#"<="#.to_string(),
                is_regex: false,
                line_number: 151,
                alias: None,
            },
            TokenDefinition {
                name: r#"GREATER_EQUALS"#.to_string(),
                pattern: r#">="#.to_string(),
                is_regex: false,
                line_number: 152,
                alias: None,
            },
            TokenDefinition {
                name: r#"POWER"#.to_string(),
                pattern: r#"**"#.to_string(),
                is_regex: false,
                line_number: 153,
                alias: None,
            },
            TokenDefinition {
                name: r#"TRIGGER"#.to_string(),
                pattern: r#"->"#.to_string(),
                is_regex: false,
                line_number: 154,
                alias: None,
            },
            TokenDefinition {
                name: r#"PLUS"#.to_string(),
                pattern: r#"+"#.to_string(),
                is_regex: false,
                line_number: 168,
                alias: None,
            },
            TokenDefinition {
                name: r#"MINUS"#.to_string(),
                pattern: r#"-"#.to_string(),
                is_regex: false,
                line_number: 169,
                alias: None,
            },
            TokenDefinition {
                name: r#"STAR"#.to_string(),
                pattern: r#"*"#.to_string(),
                is_regex: false,
                line_number: 170,
                alias: None,
            },
            TokenDefinition {
                name: r#"SLASH"#.to_string(),
                pattern: r#"/"#.to_string(),
                is_regex: false,
                line_number: 171,
                alias: None,
            },
            TokenDefinition {
                name: r#"PERCENT"#.to_string(),
                pattern: r#"%"#.to_string(),
                is_regex: false,
                line_number: 172,
                alias: None,
            },
            TokenDefinition {
                name: r#"AMP"#.to_string(),
                pattern: r#"&"#.to_string(),
                is_regex: false,
                line_number: 173,
                alias: None,
            },
            TokenDefinition {
                name: r#"PIPE"#.to_string(),
                pattern: r#"|"#.to_string(),
                is_regex: false,
                line_number: 174,
                alias: None,
            },
            TokenDefinition {
                name: r#"CARET"#.to_string(),
                pattern: r#"^"#.to_string(),
                is_regex: false,
                line_number: 175,
                alias: None,
            },
            TokenDefinition {
                name: r#"TILDE"#.to_string(),
                pattern: r#"~"#.to_string(),
                is_regex: false,
                line_number: 176,
                alias: None,
            },
            TokenDefinition {
                name: r#"BANG"#.to_string(),
                pattern: r#"!"#.to_string(),
                is_regex: false,
                line_number: 177,
                alias: None,
            },
            TokenDefinition {
                name: r#"LESS_THAN"#.to_string(),
                pattern: r#"<"#.to_string(),
                is_regex: false,
                line_number: 178,
                alias: None,
            },
            TokenDefinition {
                name: r#"GREATER_THAN"#.to_string(),
                pattern: r#">"#.to_string(),
                is_regex: false,
                line_number: 179,
                alias: None,
            },
            TokenDefinition {
                name: r#"EQUALS"#.to_string(),
                pattern: r#"="#.to_string(),
                is_regex: false,
                line_number: 180,
                alias: None,
            },
            TokenDefinition {
                name: r#"QUESTION"#.to_string(),
                pattern: r#"?"#.to_string(),
                is_regex: false,
                line_number: 181,
                alias: None,
            },
            TokenDefinition {
                name: r#"COLON"#.to_string(),
                pattern: r#":"#.to_string(),
                is_regex: false,
                line_number: 182,
                alias: None,
            },
            TokenDefinition {
                name: r#"LPAREN"#.to_string(),
                pattern: r#"("#.to_string(),
                is_regex: false,
                line_number: 194,
                alias: None,
            },
            TokenDefinition {
                name: r#"RPAREN"#.to_string(),
                pattern: r#")"#.to_string(),
                is_regex: false,
                line_number: 195,
                alias: None,
            },
            TokenDefinition {
                name: r#"LBRACKET"#.to_string(),
                pattern: r#"["#.to_string(),
                is_regex: false,
                line_number: 196,
                alias: None,
            },
            TokenDefinition {
                name: r#"RBRACKET"#.to_string(),
                pattern: r#"]"#.to_string(),
                is_regex: false,
                line_number: 197,
                alias: None,
            },
            TokenDefinition {
                name: r#"LBRACE"#.to_string(),
                pattern: r#"{"#.to_string(),
                is_regex: false,
                line_number: 198,
                alias: None,
            },
            TokenDefinition {
                name: r#"RBRACE"#.to_string(),
                pattern: r#"}"#.to_string(),
                is_regex: false,
                line_number: 199,
                alias: None,
            },
            TokenDefinition {
                name: r#"SEMICOLON"#.to_string(),
                pattern: r#";"#.to_string(),
                is_regex: false,
                line_number: 200,
                alias: None,
            },
            TokenDefinition {
                name: r#"COMMA"#.to_string(),
                pattern: r#","#.to_string(),
                is_regex: false,
                line_number: 201,
                alias: None,
            },
            TokenDefinition {
                name: r#"DOT"#.to_string(),
                pattern: r#"."#.to_string(),
                is_regex: false,
                line_number: 202,
                alias: None,
            },
            TokenDefinition {
                name: r#"HASH"#.to_string(),
                pattern: r#"#"#.to_string(),
                is_regex: false,
                line_number: 203,
                alias: None,
            },
            TokenDefinition {
                name: r#"AT"#.to_string(),
                pattern: r#"@"#.to_string(),
                is_regex: false,
                line_number: 204,
                alias: None,
            },
        ],
        keywords: vec![r#"always"#.to_string(), r#"and"#.to_string(), r#"assign"#.to_string(), r#"begin"#.to_string(), r#"buf"#.to_string(), r#"case"#.to_string(), r#"casex"#.to_string(), r#"casez"#.to_string(), r#"default"#.to_string(), r#"defparam"#.to_string(), r#"else"#.to_string(), r#"end"#.to_string(), r#"endcase"#.to_string(), r#"endfunction"#.to_string(), r#"endgenerate"#.to_string(), r#"endmodule"#.to_string(), r#"endtask"#.to_string(), r#"for"#.to_string(), r#"function"#.to_string(), r#"generate"#.to_string(), r#"genvar"#.to_string(), r#"if"#.to_string(), r#"initial"#.to_string(), r#"inout"#.to_string(), r#"input"#.to_string(), r#"integer"#.to_string(), r#"localparam"#.to_string(), r#"module"#.to_string(), r#"nand"#.to_string(), r#"negedge"#.to_string(), r#"nor"#.to_string(), r#"not"#.to_string(), r#"or"#.to_string(), r#"output"#.to_string(), r#"parameter"#.to_string(), r#"posedge"#.to_string(), r#"real"#.to_string(), r#"reg"#.to_string(), r#"signed"#.to_string(), r#"supply0"#.to_string(), r#"supply1"#.to_string(), r#"task"#.to_string(), r#"tri"#.to_string(), r#"unsigned"#.to_string(), r#"wire"#.to_string(), r#"xnor"#.to_string(), r#"xor"#.to_string()],
        mode: None,
        skip_definitions: vec![
            TokenDefinition {
                name: r#"LINE_COMMENT"#.to_string(),
                pattern: r#"\/\/[^\n]*"#.to_string(),
                is_regex: true,
                line_number: 31,
                alias: None,
            },
            TokenDefinition {
                name: r#"BLOCK_COMMENT"#.to_string(),
                pattern: r#"\/\*([^*]|\*[^/])*\*\/"#.to_string(),
                is_regex: true,
                line_number: 32,
                alias: None,
            },
            TokenDefinition {
                name: r#"WHITESPACE"#.to_string(),
                pattern: r#"[ \t\r\n]+"#.to_string(),
                is_regex: true,
                line_number: 33,
                alias: None,
            },
        ],
        reserved_keywords: vec![],
        escapes: None,
        error_definitions: vec![],
        groups: HashMap::new(),
        case_sensitive: true,
        version: 0,
        case_insensitive: false,
            layout_keywords: vec![],
        context_keywords: vec![],
        soft_keywords: vec![],
    }
}
