// AUTO-GENERATED FILE - DO NOT EDIT
#![allow(clippy::all)]
use std::collections::HashMap;
use grammar_tools::token_grammar::{TokenGrammar, TokenDefinition, PatternGroup};

pub fn VerilogTokens() -> TokenGrammar {
    let groups = HashMap::new();
    TokenGrammar {
        version: 0,
        case_insensitive: false,
        case_sensitive: true,
        mode: None,
        escapes: None,
        keywords: vec!["always".to_string(), "and".to_string(), "assign".to_string(), "begin".to_string(), "buf".to_string(), "case".to_string(), "casex".to_string(), "casez".to_string(), "default".to_string(), "defparam".to_string(), "else".to_string(), "end".to_string(), "endcase".to_string(), "endfunction".to_string(), "endgenerate".to_string(), "endmodule".to_string(), "endtask".to_string(), "for".to_string(), "function".to_string(), "generate".to_string(), "genvar".to_string(), "if".to_string(), "initial".to_string(), "inout".to_string(), "input".to_string(), "integer".to_string(), "localparam".to_string(), "module".to_string(), "nand".to_string(), "negedge".to_string(), "nor".to_string(), "not".to_string(), "or".to_string(), "output".to_string(), "parameter".to_string(), "posedge".to_string(), "real".to_string(), "reg".to_string(), "signed".to_string(), "supply0".to_string(), "supply1".to_string(), "task".to_string(), "tri".to_string(), "unsigned".to_string(), "wire".to_string(), "xnor".to_string(), "xor".to_string()],
        reserved_keywords: vec![],
        definitions: vec![
            TokenDefinition { name: "STRING".to_string(), pattern: "\"([^\"\\\\]|\\\\.)*\"".to_string(), is_regex: true, line_number: 46, alias: None },
            TokenDefinition { name: "SIZED_NUMBER".to_string(), pattern: "[0-9]*'[sS]?[bBoOdDhH][0-9a-fA-F_xXzZ]+".to_string(), is_regex: true, line_number: 73, alias: None },
            TokenDefinition { name: "REAL_NUMBER".to_string(), pattern: "[0-9]+\\.[0-9]+([eE][+-]?[0-9]+)?".to_string(), is_regex: true, line_number: 77, alias: None },
            TokenDefinition { name: "NUMBER".to_string(), pattern: "[0-9][0-9_]*".to_string(), is_regex: true, line_number: 81, alias: None },
            TokenDefinition { name: "SYSTEM_ID".to_string(), pattern: "\\$[a-zA-Z_][a-zA-Z0-9_$]*".to_string(), is_regex: true, line_number: 109, alias: None },
            TokenDefinition { name: "DIRECTIVE".to_string(), pattern: "`[a-zA-Z_][a-zA-Z0-9_]*".to_string(), is_regex: true, line_number: 110, alias: None },
            TokenDefinition { name: "ESCAPED_IDENT".to_string(), pattern: "\\\\[^ \\t\\r\\n]+".to_string(), is_regex: true, line_number: 111, alias: None },
            TokenDefinition { name: "NAME".to_string(), pattern: "[a-zA-Z_][a-zA-Z0-9_$]*".to_string(), is_regex: true, line_number: 114, alias: None },
            TokenDefinition { name: "ARITH_LEFT_SHIFT".to_string(), pattern: "<<<".to_string(), is_regex: false, line_number: 126, alias: None },
            TokenDefinition { name: "ARITH_RIGHT_SHIFT".to_string(), pattern: ">>>".to_string(), is_regex: false, line_number: 127, alias: None },
            TokenDefinition { name: "CASE_EQ".to_string(), pattern: "===".to_string(), is_regex: false, line_number: 136, alias: None },
            TokenDefinition { name: "CASE_NEQ".to_string(), pattern: "!==".to_string(), is_regex: false, line_number: 137, alias: None },
            TokenDefinition { name: "LOGIC_AND".to_string(), pattern: "&&".to_string(), is_regex: false, line_number: 145, alias: None },
            TokenDefinition { name: "LOGIC_OR".to_string(), pattern: "||".to_string(), is_regex: false, line_number: 146, alias: None },
            TokenDefinition { name: "LEFT_SHIFT".to_string(), pattern: "<<".to_string(), is_regex: false, line_number: 147, alias: None },
            TokenDefinition { name: "RIGHT_SHIFT".to_string(), pattern: ">>".to_string(), is_regex: false, line_number: 148, alias: None },
            TokenDefinition { name: "EQUALS_EQUALS".to_string(), pattern: "==".to_string(), is_regex: false, line_number: 149, alias: None },
            TokenDefinition { name: "NOT_EQUALS".to_string(), pattern: "!=".to_string(), is_regex: false, line_number: 150, alias: None },
            TokenDefinition { name: "LESS_EQUALS".to_string(), pattern: "<=".to_string(), is_regex: false, line_number: 151, alias: None },
            TokenDefinition { name: "GREATER_EQUALS".to_string(), pattern: ">=".to_string(), is_regex: false, line_number: 152, alias: None },
            TokenDefinition { name: "POWER".to_string(), pattern: "**".to_string(), is_regex: false, line_number: 153, alias: None },
            TokenDefinition { name: "TRIGGER".to_string(), pattern: "->".to_string(), is_regex: false, line_number: 154, alias: None },
            TokenDefinition { name: "PLUS".to_string(), pattern: "+".to_string(), is_regex: false, line_number: 168, alias: None },
            TokenDefinition { name: "MINUS".to_string(), pattern: "-".to_string(), is_regex: false, line_number: 169, alias: None },
            TokenDefinition { name: "STAR".to_string(), pattern: "*".to_string(), is_regex: false, line_number: 170, alias: None },
            TokenDefinition { name: "SLASH".to_string(), pattern: "/".to_string(), is_regex: false, line_number: 171, alias: None },
            TokenDefinition { name: "PERCENT".to_string(), pattern: "%".to_string(), is_regex: false, line_number: 172, alias: None },
            TokenDefinition { name: "AMP".to_string(), pattern: "&".to_string(), is_regex: false, line_number: 173, alias: None },
            TokenDefinition { name: "PIPE".to_string(), pattern: "|".to_string(), is_regex: false, line_number: 174, alias: None },
            TokenDefinition { name: "CARET".to_string(), pattern: "^".to_string(), is_regex: false, line_number: 175, alias: None },
            TokenDefinition { name: "TILDE".to_string(), pattern: "~".to_string(), is_regex: false, line_number: 176, alias: None },
            TokenDefinition { name: "BANG".to_string(), pattern: "!".to_string(), is_regex: false, line_number: 177, alias: None },
            TokenDefinition { name: "LESS_THAN".to_string(), pattern: "<".to_string(), is_regex: false, line_number: 178, alias: None },
            TokenDefinition { name: "GREATER_THAN".to_string(), pattern: ">".to_string(), is_regex: false, line_number: 179, alias: None },
            TokenDefinition { name: "EQUALS".to_string(), pattern: "=".to_string(), is_regex: false, line_number: 180, alias: None },
            TokenDefinition { name: "QUESTION".to_string(), pattern: "?".to_string(), is_regex: false, line_number: 181, alias: None },
            TokenDefinition { name: "COLON".to_string(), pattern: ":".to_string(), is_regex: false, line_number: 182, alias: None },
            TokenDefinition { name: "LPAREN".to_string(), pattern: "(".to_string(), is_regex: false, line_number: 194, alias: None },
            TokenDefinition { name: "RPAREN".to_string(), pattern: ")".to_string(), is_regex: false, line_number: 195, alias: None },
            TokenDefinition { name: "LBRACKET".to_string(), pattern: "[".to_string(), is_regex: false, line_number: 196, alias: None },
            TokenDefinition { name: "RBRACKET".to_string(), pattern: "]".to_string(), is_regex: false, line_number: 197, alias: None },
            TokenDefinition { name: "LBRACE".to_string(), pattern: "{".to_string(), is_regex: false, line_number: 198, alias: None },
            TokenDefinition { name: "RBRACE".to_string(), pattern: "}".to_string(), is_regex: false, line_number: 199, alias: None },
            TokenDefinition { name: "SEMICOLON".to_string(), pattern: ";".to_string(), is_regex: false, line_number: 200, alias: None },
            TokenDefinition { name: "COMMA".to_string(), pattern: ",".to_string(), is_regex: false, line_number: 201, alias: None },
            TokenDefinition { name: "DOT".to_string(), pattern: ".".to_string(), is_regex: false, line_number: 202, alias: None },
            TokenDefinition { name: "HASH".to_string(), pattern: "#".to_string(), is_regex: false, line_number: 203, alias: None },
            TokenDefinition { name: "AT".to_string(), pattern: "@".to_string(), is_regex: false, line_number: 204, alias: None },
        ],
        skip_definitions: vec![
            TokenDefinition { name: "LINE_COMMENT".to_string(), pattern: "\\/\\/[^\\n]*".to_string(), is_regex: true, line_number: 31, alias: None },
            TokenDefinition { name: "BLOCK_COMMENT".to_string(), pattern: "\\/\\*([^*]|\\*[^/])*\\*\\/".to_string(), is_regex: true, line_number: 32, alias: None },
            TokenDefinition { name: "WHITESPACE".to_string(), pattern: "[ \\t\\r\\n]+".to_string(), is_regex: true, line_number: 33, alias: None },
        ],
        error_definitions: vec![
        ],
        groups,
    }
}
