# AUTO-GENERATED FILE — DO NOT EDIT
# Source: python3.6.tokens
# Regenerate with: perl code/programs/perl/grammar-tools/grammar-tools.pl compile-tokens python3.6.tokens
#
# This file embeds a TokenGrammar as native Perl data structures.
# Call token_grammar() instead of reading and parsing the .tokens file.

package CodingAdventures::PythonLexer::_Grammar_3_6;
use strict;
use warnings;

sub token_grammar {
    return bless {
        definitions => [
            bless({
                name => 'STRING_RAW_FSTR_TRIPLE_DQ',
                pattern => '[rR][fF]"""([^"\\\\]|\\\\.|\\n)*"""|[fF][rR]"""([^"\\\\]|\\\\.|\\n)*"""',
                is_regex => 1,
                line_number => 198,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_FSTR_TRIPLE_SQ',
                pattern => '[rR][fF]\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'|[fF][rR]\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'',
                is_regex => 1,
                line_number => 199,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_TRIPLE_DQ',
                pattern => '[rR][bB]?"""([^"\\\\]|\\\\.|\\n)*"""|[bB][rR]"""([^"\\\\]|\\\\.|\\n)*"""',
                is_regex => 1,
                line_number => 200,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_TRIPLE_SQ',
                pattern => '[rR][bB]?\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'|[bB][rR]\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'',
                is_regex => 1,
                line_number => 201,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_FSTR_TRIPLE_DQ',
                pattern => '[fF]"""([^"\\\\]|\\\\.|\\n)*"""',
                is_regex => 1,
                line_number => 203,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_FSTR_TRIPLE_SQ',
                pattern => '[fF]\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'',
                is_regex => 1,
                line_number => 204,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_TRIPLE_DQ',
                pattern => '[bB]?"""([^"\\\\]|\\\\.|\\n)*"""',
                is_regex => 1,
                line_number => 205,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_TRIPLE_SQ',
                pattern => '[bB]?\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'',
                is_regex => 1,
                line_number => 206,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_FSTR_DQ',
                pattern => '[rR][fF]"([^"\\\\]|\\\\.)*"|[fF][rR]"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 210,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_FSTR_SQ',
                pattern => '[rR][fF]\'([^\'\\\\]|\\\\.)*\'|[fF][rR]\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 211,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_DQ',
                pattern => '[rR][bB]?"([^"\\\\]|\\\\.)*"|[bB][rR]"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 212,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_SQ',
                pattern => '[rR][bB]?\'([^\'\\\\]|\\\\.)*\'|[bB][rR]\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 213,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_FSTR_DQ',
                pattern => '[fF]"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 215,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_FSTR_SQ',
                pattern => '[fF]\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 216,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_DQ',
                pattern => '[bB]?"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 217,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_SQ',
                pattern => '[bB]?\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 218,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOAT_EXP',
                pattern => '[0-9](_?[0-9])*[eE][+-]?[0-9](_?[0-9])*',
                is_regex => 1,
                line_number => 251,
                alias => 'FLOAT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOAT_DOT',
                pattern => '\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?\\b',
                is_regex => 1,
                line_number => 252,
                alias => 'FLOAT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOAT',
                pattern => '[0-9](_?[0-9])*\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?',
                is_regex => 1,
                line_number => 253,
                alias => 'FLOAT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOAT_TRAIL',
                pattern => '[0-9](_?[0-9])*\\.([eE][+-]?[0-9](_?[0-9])*)?\\b',
                is_regex => 1,
                line_number => 254,
                alias => 'FLOAT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'IMAG_FLOAT',
                pattern => '[0-9](_?[0-9])*\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?[jJ]',
                is_regex => 1,
                line_number => 259,
                alias => 'IMAGINARY',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'IMAG_DOT',
                pattern => '\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?[jJ]',
                is_regex => 1,
                line_number => 260,
                alias => 'IMAGINARY',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'IMAG_EXP',
                pattern => '[0-9](_?[0-9])*[eE][+-]?[0-9](_?[0-9])*[jJ]',
                is_regex => 1,
                line_number => 261,
                alias => 'IMAGINARY',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'IMAG_INT',
                pattern => '[0-9](_?[0-9])*[jJ]',
                is_regex => 1,
                line_number => 262,
                alias => 'IMAGINARY',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'INT_HEX',
                pattern => '0[xX](_?[0-9a-fA-F])+',
                is_regex => 1,
                line_number => 272,
                alias => 'INT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'INT_OCT',
                pattern => '0[oO](_?[0-7])+',
                is_regex => 1,
                line_number => 273,
                alias => 'INT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'INT_BIN',
                pattern => '0[bB](_?[01])+',
                is_regex => 1,
                line_number => 274,
                alias => 'INT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'INT',
                pattern => '[0-9](_?[0-9])*',
                is_regex => 1,
                line_number => 275,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NAME',
                pattern => '[a-zA-Z_][a-zA-Z0-9_]*',
                is_regex => 1,
                line_number => 285,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AT',
                pattern => '@',
                is_regex => 0,
                line_number => 297,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'DOUBLE_STAR_EQUALS',
                pattern => '**=',
                is_regex => 0,
                line_number => 306,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEFT_SHIFT_EQUALS',
                pattern => '<<=',
                is_regex => 0,
                line_number => 307,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RIGHT_SHIFT_EQUALS',
                pattern => '>>=',
                is_regex => 0,
                line_number => 308,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOOR_DIV_EQUALS',
                pattern => '//=',
                is_regex => 0,
                line_number => 309,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AT_EQUALS',
                pattern => '@=',
                is_regex => 0,
                line_number => 310,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'DOUBLE_STAR',
                pattern => '**',
                is_regex => 0,
                line_number => 318,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOOR_DIV',
                pattern => '//',
                is_regex => 0,
                line_number => 319,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEFT_SHIFT',
                pattern => '<<',
                is_regex => 0,
                line_number => 320,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RIGHT_SHIFT',
                pattern => '>>',
                is_regex => 0,
                line_number => 321,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'EQUALS_EQUALS',
                pattern => '==',
                is_regex => 0,
                line_number => 322,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NOT_EQUALS',
                pattern => '!=',
                is_regex => 0,
                line_number => 323,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LESS_EQUALS',
                pattern => '<=',
                is_regex => 0,
                line_number => 324,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'GREATER_EQUALS',
                pattern => '>=',
                is_regex => 0,
                line_number => 325,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS_EQUALS',
                pattern => '+=',
                is_regex => 0,
                line_number => 326,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS_EQUALS',
                pattern => '-=',
                is_regex => 0,
                line_number => 327,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STAR_EQUALS',
                pattern => '*=',
                is_regex => 0,
                line_number => 328,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SLASH_EQUALS',
                pattern => '/=',
                is_regex => 0,
                line_number => 329,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PERCENT_EQUALS',
                pattern => '%=',
                is_regex => 0,
                line_number => 330,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AMP_EQUALS',
                pattern => '&=',
                is_regex => 0,
                line_number => 331,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PIPE_EQUALS',
                pattern => '|=',
                is_regex => 0,
                line_number => 332,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'CARET_EQUALS',
                pattern => '^=',
                is_regex => 0,
                line_number => 333,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'ARROW',
                pattern => '->',
                is_regex => 0,
                line_number => 334,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS',
                pattern => '+',
                is_regex => 0,
                line_number => 340,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS',
                pattern => '-',
                is_regex => 0,
                line_number => 341,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STAR',
                pattern => '*',
                is_regex => 0,
                line_number => 342,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SLASH',
                pattern => '/',
                is_regex => 0,
                line_number => 343,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PERCENT',
                pattern => '%',
                is_regex => 0,
                line_number => 344,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'EQUALS',
                pattern => '=',
                is_regex => 0,
                line_number => 345,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LESS_THAN',
                pattern => '<',
                is_regex => 0,
                line_number => 346,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'GREATER_THAN',
                pattern => '>',
                is_regex => 0,
                line_number => 347,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AMP',
                pattern => '&',
                is_regex => 0,
                line_number => 348,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PIPE',
                pattern => '|',
                is_regex => 0,
                line_number => 349,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'CARET',
                pattern => '^',
                is_regex => 0,
                line_number => 350,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'TILDE',
                pattern => '~',
                is_regex => 0,
                line_number => 351,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LPAREN',
                pattern => '(',
                is_regex => 0,
                line_number => 357,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RPAREN',
                pattern => ')',
                is_regex => 0,
                line_number => 358,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LBRACKET',
                pattern => '[',
                is_regex => 0,
                line_number => 359,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RBRACKET',
                pattern => ']',
                is_regex => 0,
                line_number => 360,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LBRACE',
                pattern => '{',
                is_regex => 0,
                line_number => 361,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RBRACE',
                pattern => '}',
                is_regex => 0,
                line_number => 362,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COMMA',
                pattern => ',',
                is_regex => 0,
                line_number => 363,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COLON',
                pattern => ':',
                is_regex => 0,
                line_number => 364,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SEMICOLON',
                pattern => ';',
                is_regex => 0,
                line_number => 365,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'DOT',
                pattern => '.',
                is_regex => 0,
                line_number => 366,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'ELLIPSIS',
                pattern => '...',
                is_regex => 0,
                line_number => 367,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        keywords => [
            'False',
            'None',
            'True',
            'and',
            'as',
            'assert',
            'async',
            'await',
            'break',
            'class',
            'continue',
            'def',
            'del',
            'elif',
            'else',
            'except',
            'finally',
            'for',
            'from',
            'global',
            'if',
            'import',
            'in',
            'is',
            'lambda',
            'nonlocal',
            'not',
            'or',
            'pass',
            'raise',
            'return',
            'try',
            'while',
            'with',
            'yield',
        ],
        context_keywords => [],
        layout_keywords => [],
        soft_keywords => [],
        mode => 'indentation',
        escape_mode => '',
        skip_definitions => [
            bless({
                name => 'COMMENT',
                pattern => '#[^\\n]*',
                is_regex => 1,
                line_number => 55,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'WHITESPACE',
                pattern => '[ \\t]+',
                is_regex => 1,
                line_number => 56,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        error_definitions => [],
        reserved_keywords => [],
        groups => {},
        start_mode => '',
        transitions => [],
    }, 'CodingAdventures::GrammarTools::TokenGrammar';
}

1;
