# AUTO-GENERATED FILE — DO NOT EDIT
# Source: python3.12.tokens
# Regenerate with: perl code/programs/perl/grammar-tools/grammar-tools.pl compile-tokens python3.12.tokens
#
# This file embeds a TokenGrammar as native Perl data structures.
# Call token_grammar() instead of reading and parsing the .tokens file.

package CodingAdventures::PythonLexer::_Grammar_3_12;
use strict;
use warnings;

sub token_grammar {
    return bless {
        definitions => [
            bless({
                name => 'STRING_RAW_FSTRING_TRIPLE_DQ',
                pattern => '[rR][fF]"""([^"\\\\]|\\\\.|\\n)*"""|[fF][rR]"""([^"\\\\]|\\\\.|\\n)*"""',
                is_regex => 1,
                line_number => 107,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_FSTRING_TRIPLE_SQ',
                pattern => '[rR][fF]\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'|[fF][rR]\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'',
                is_regex => 1,
                line_number => 108,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_BYTES_TRIPLE_DQ',
                pattern => '[bB][rR]"""([^"\\\\]|\\\\.|\\n)*"""|[rR][bB]"""([^"\\\\]|\\\\.|\\n)*"""',
                is_regex => 1,
                line_number => 109,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_BYTES_TRIPLE_SQ',
                pattern => '[bB][rR]\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'|[rR][bB]\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'',
                is_regex => 1,
                line_number => 110,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_FSTRING_TRIPLE_DQ',
                pattern => '[fF]"""([^"\\\\]|\\\\.|\\n)*"""',
                is_regex => 1,
                line_number => 112,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_FSTRING_TRIPLE_SQ',
                pattern => '[fF]\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'',
                is_regex => 1,
                line_number => 113,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_UNICODE_TRIPLE_DQ',
                pattern => '[uU]"""([^"\\\\]|\\\\.|\\n)*"""',
                is_regex => 1,
                line_number => 114,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_UNICODE_TRIPLE_SQ',
                pattern => '[uU]\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'',
                is_regex => 1,
                line_number => 115,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_TRIPLE_DQ',
                pattern => '[rR]"""([^"\\\\]|\\\\.|\\n)*"""',
                is_regex => 1,
                line_number => 116,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_TRIPLE_SQ',
                pattern => '[rR]\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'',
                is_regex => 1,
                line_number => 117,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_BYTES_TRIPLE_DQ',
                pattern => '[bB]"""([^"\\\\]|\\\\.|\\n)*"""',
                is_regex => 1,
                line_number => 118,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_BYTES_TRIPLE_SQ',
                pattern => '[bB]\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'',
                is_regex => 1,
                line_number => 119,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_TRIPLE_DQ',
                pattern => '"""([^"\\\\]|\\\\.|\\n)*"""',
                is_regex => 1,
                line_number => 120,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_TRIPLE_SQ',
                pattern => '\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'',
                is_regex => 1,
                line_number => 121,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_FSTRING_DQ',
                pattern => '[rR][fF]"([^"\\\\]|\\\\.)*"|[fF][rR]"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 124,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_FSTRING_SQ',
                pattern => '[rR][fF]\'([^\'\\\\]|\\\\.)*\'|[fF][rR]\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 125,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_BYTES_DQ',
                pattern => '[bB][rR]"([^"\\\\]|\\\\.)*"|[rR][bB]"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 126,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_BYTES_SQ',
                pattern => '[bB][rR]\'([^\'\\\\]|\\\\.)*\'|[rR][bB]\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 127,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_FSTRING_DQ',
                pattern => '[fF]"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 129,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_FSTRING_SQ',
                pattern => '[fF]\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 130,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_UNICODE_DQ',
                pattern => '[uU]"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 131,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_UNICODE_SQ',
                pattern => '[uU]\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 132,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_DQ',
                pattern => '[rR]"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 133,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_SQ',
                pattern => '[rR]\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 134,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_BYTES_DQ',
                pattern => '[bB]"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 135,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_BYTES_SQ',
                pattern => '[bB]\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 136,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_DQ',
                pattern => '"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 137,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_SQ',
                pattern => '\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 138,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'IMAG_FLOAT_EXP',
                pattern => '[0-9](_?[0-9])*[eE][+-]?[0-9](_?[0-9])*[jJ]',
                is_regex => 1,
                line_number => 149,
                alias => 'IMAG',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'IMAG_FLOAT_DOT',
                pattern => '\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?[jJ]',
                is_regex => 1,
                line_number => 150,
                alias => 'IMAG',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'IMAG_FLOAT',
                pattern => '[0-9](_?[0-9])*\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?[jJ]',
                is_regex => 1,
                line_number => 151,
                alias => 'IMAG',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'IMAG_INT',
                pattern => '[0-9](_?[0-9])*[jJ]',
                is_regex => 1,
                line_number => 152,
                alias => 'IMAG',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOAT_EXP',
                pattern => '[0-9](_?[0-9])*[eE][+-]?[0-9](_?[0-9])*',
                is_regex => 1,
                line_number => 154,
                alias => 'FLOAT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOAT_DOT',
                pattern => '\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?',
                is_regex => 1,
                line_number => 155,
                alias => 'FLOAT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOAT',
                pattern => '[0-9](_?[0-9])*\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?',
                is_regex => 1,
                line_number => 156,
                alias => 'FLOAT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'INT_HEX',
                pattern => '0[xX](_?[0-9a-fA-F])+',
                is_regex => 1,
                line_number => 158,
                alias => 'INT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'INT_BIN',
                pattern => '0[bB](_?[01])+',
                is_regex => 1,
                line_number => 159,
                alias => 'INT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'INT_OCT',
                pattern => '0[oO](_?[0-7])+',
                is_regex => 1,
                line_number => 160,
                alias => 'INT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'INT',
                pattern => '[0-9](_?[0-9])*',
                is_regex => 1,
                line_number => 161,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NAME',
                pattern => '[a-zA-Z_][a-zA-Z0-9_]*',
                is_regex => 1,
                line_number => 170,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'DOUBLE_STAR_EQUALS',
                pattern => '**=',
                is_regex => 0,
                line_number => 176,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEFT_SHIFT_EQUALS',
                pattern => '<<=',
                is_regex => 0,
                line_number => 177,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RIGHT_SHIFT_EQUALS',
                pattern => '>>=',
                is_regex => 0,
                line_number => 178,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOOR_DIV_EQUALS',
                pattern => '//=',
                is_regex => 0,
                line_number => 179,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'DOUBLE_STAR',
                pattern => '**',
                is_regex => 0,
                line_number => 188,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOOR_DIV',
                pattern => '//',
                is_regex => 0,
                line_number => 189,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEFT_SHIFT',
                pattern => '<<',
                is_regex => 0,
                line_number => 190,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RIGHT_SHIFT',
                pattern => '>>',
                is_regex => 0,
                line_number => 191,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'EQUALS_EQUALS',
                pattern => '==',
                is_regex => 0,
                line_number => 192,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NOT_EQUALS',
                pattern => '!=',
                is_regex => 0,
                line_number => 193,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LESS_EQUALS',
                pattern => '<=',
                is_regex => 0,
                line_number => 194,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'GREATER_EQUALS',
                pattern => '>=',
                is_regex => 0,
                line_number => 195,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'WALRUS',
                pattern => ':=',
                is_regex => 0,
                line_number => 196,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'ARROW',
                pattern => '->',
                is_regex => 0,
                line_number => 197,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS_EQUALS',
                pattern => '+=',
                is_regex => 0,
                line_number => 198,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS_EQUALS',
                pattern => '-=',
                is_regex => 0,
                line_number => 199,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STAR_EQUALS',
                pattern => '*=',
                is_regex => 0,
                line_number => 200,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SLASH_EQUALS',
                pattern => '/=',
                is_regex => 0,
                line_number => 201,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PERCENT_EQUALS',
                pattern => '%=',
                is_regex => 0,
                line_number => 202,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AMP_EQUALS',
                pattern => '&=',
                is_regex => 0,
                line_number => 203,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PIPE_EQUALS',
                pattern => '|=',
                is_regex => 0,
                line_number => 204,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'CARET_EQUALS',
                pattern => '^=',
                is_regex => 0,
                line_number => 205,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AT_EQUALS',
                pattern => '@=',
                is_regex => 0,
                line_number => 206,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS',
                pattern => '+',
                is_regex => 0,
                line_number => 215,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS',
                pattern => '-',
                is_regex => 0,
                line_number => 216,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STAR',
                pattern => '*',
                is_regex => 0,
                line_number => 217,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SLASH',
                pattern => '/',
                is_regex => 0,
                line_number => 218,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PERCENT',
                pattern => '%',
                is_regex => 0,
                line_number => 219,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'EQUALS',
                pattern => '=',
                is_regex => 0,
                line_number => 220,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LESS_THAN',
                pattern => '<',
                is_regex => 0,
                line_number => 221,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'GREATER_THAN',
                pattern => '>',
                is_regex => 0,
                line_number => 222,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AMP',
                pattern => '&',
                is_regex => 0,
                line_number => 223,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PIPE',
                pattern => '|',
                is_regex => 0,
                line_number => 224,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'CARET',
                pattern => '^',
                is_regex => 0,
                line_number => 225,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'TILDE',
                pattern => '~',
                is_regex => 0,
                line_number => 226,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AT',
                pattern => '@',
                is_regex => 0,
                line_number => 227,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'ELLIPSIS',
                pattern => '...',
                is_regex => 0,
                line_number => 237,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LPAREN',
                pattern => '(',
                is_regex => 0,
                line_number => 238,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RPAREN',
                pattern => ')',
                is_regex => 0,
                line_number => 239,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LBRACKET',
                pattern => '[',
                is_regex => 0,
                line_number => 240,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RBRACKET',
                pattern => ']',
                is_regex => 0,
                line_number => 241,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LBRACE',
                pattern => '{',
                is_regex => 0,
                line_number => 242,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RBRACE',
                pattern => '}',
                is_regex => 0,
                line_number => 243,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COMMA',
                pattern => ',',
                is_regex => 0,
                line_number => 244,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COLON',
                pattern => ':',
                is_regex => 0,
                line_number => 245,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SEMICOLON',
                pattern => ';',
                is_regex => 0,
                line_number => 246,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'DOT',
                pattern => '.',
                is_regex => 0,
                line_number => 247,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        keywords => [
            'False',
            'None',
            'True',
            'and',
            'as',
            'assert',
            'async',
            'await',
            'break',
            'class',
            'continue',
            'def',
            'del',
            'elif',
            'else',
            'except',
            'finally',
            'for',
            'from',
            'global',
            'if',
            'import',
            'in',
            'is',
            'lambda',
            'nonlocal',
            'not',
            'or',
            'pass',
            'raise',
            'return',
            'try',
            'while',
            'with',
            'yield',
        ],
        context_keywords => [],
        layout_keywords => [],
        soft_keywords => [
            'match',
            'case',
            '_',
            'type',
        ],
        mode => 'indentation',
        escape_mode => '',
        skip_definitions => [
            bless({
                name => 'COMMENT',
                pattern => '#[^\\n]*',
                is_regex => 1,
                line_number => 41,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'WHITESPACE',
                pattern => '[ \\t]+',
                is_regex => 1,
                line_number => 42,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LINE_CONTINUATION',
                pattern => '\\\\[ \\t]*\\n',
                is_regex => 1,
                line_number => 45,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        error_definitions => [],
        reserved_keywords => [],
        groups => {},
        start_mode => '',
        transitions => [],
    }, 'CodingAdventures::GrammarTools::TokenGrammar';
}

1;
