# AUTO-GENERATED FILE — DO NOT EDIT
# Source: python3.8.tokens
# Regenerate with: perl code/programs/perl/grammar-tools/grammar-tools.pl compile-tokens python3.8.tokens
#
# This file embeds a TokenGrammar as native Perl data structures.
# Call token_grammar() instead of reading and parsing the .tokens file.

package CodingAdventures::PythonLexer::_Grammar_3_8;
use strict;
use warnings;

sub token_grammar {
    return bless {
        definitions => [
            bless({
                name => 'STRING_RAW_BYTES_TRIPLE_DQ',
                pattern => '[rR][bB]"""([^"\\\\]|\\\\.|\\n)*"""|[bB][rR]"""([^"\\\\]|\\\\.|\\n)*"""',
                is_regex => 1,
                line_number => 129,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_BYTES_TRIPLE_SQ',
                pattern => '[rR][bB]?\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'|[bB][rR]\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'',
                is_regex => 1,
                line_number => 130,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_FSTR_TRIPLE_DQ',
                pattern => '[rR][fF]"""([^"\\\\]|\\\\.|\\n)*"""|[fF][rR]"""([^"\\\\]|\\\\.|\\n)*"""',
                is_regex => 1,
                line_number => 133,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_FSTR_TRIPLE_SQ',
                pattern => '[rR][fF]\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'|[fF][rR]\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'',
                is_regex => 1,
                line_number => 134,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_FSTR_TRIPLE_DQ',
                pattern => '[fF]"""([^"\\\\]|\\\\.|\\n)*"""',
                is_regex => 1,
                line_number => 137,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_FSTR_TRIPLE_SQ',
                pattern => '[fF]\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'',
                is_regex => 1,
                line_number => 138,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_BYTES_TRIPLE_DQ',
                pattern => '[bB]"""([^"\\\\]|\\\\.|\\n)*"""',
                is_regex => 1,
                line_number => 141,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_BYTES_TRIPLE_SQ',
                pattern => '[bB]\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'',
                is_regex => 1,
                line_number => 142,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_TRIPLE_DQ',
                pattern => '[rR]"""([^"\\\\]|\\\\.|\\n)*"""',
                is_regex => 1,
                line_number => 145,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_TRIPLE_SQ',
                pattern => '[rR]\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'',
                is_regex => 1,
                line_number => 146,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_TRIPLE_DQ',
                pattern => '"""([^"\\\\]|\\\\.|\\n)*"""',
                is_regex => 1,
                line_number => 149,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_TRIPLE_SQ',
                pattern => '\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'',
                is_regex => 1,
                line_number => 150,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_BYTES_DQ',
                pattern => '[rR][bB]"([^"\\\\]|\\\\.)*"|[bB][rR]"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 155,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_BYTES_SQ',
                pattern => '[rR][bB]?\'([^\'\\\\]|\\\\.)*\'|[bB][rR]\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 156,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_FSTR_DQ',
                pattern => '[rR][fF]"([^"\\\\]|\\\\.)*"|[fF][rR]"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 159,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_FSTR_SQ',
                pattern => '[rR][fF]\'([^\'\\\\]|\\\\.)*\'|[fF][rR]\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 160,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_FSTR_DQ',
                pattern => '[fF]"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 163,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_FSTR_SQ',
                pattern => '[fF]\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 164,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_BYTES_DQ',
                pattern => '[bB]"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 167,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_BYTES_SQ',
                pattern => '[bB]\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 168,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_DQ',
                pattern => '[rR]"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 171,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_SQ',
                pattern => '[rR]\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 172,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_DQ',
                pattern => '"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 175,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_SQ',
                pattern => '\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 176,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'IMAG_FLOAT_EXP',
                pattern => '[0-9](_?[0-9])*[eE][+-]?[0-9](_?[0-9])*[jJ]',
                is_regex => 1,
                line_number => 194,
                alias => 'IMAG',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'IMAG_FLOAT_DOT',
                pattern => '\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?[jJ]',
                is_regex => 1,
                line_number => 195,
                alias => 'IMAG',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'IMAG_FLOAT',
                pattern => '[0-9](_?[0-9])*\\.[0-9]*(_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?[jJ]',
                is_regex => 1,
                line_number => 196,
                alias => 'IMAG',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'IMAG_INT',
                pattern => '[0-9](_?[0-9])*[jJ]',
                is_regex => 1,
                line_number => 197,
                alias => 'IMAG',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOAT_EXP',
                pattern => '[0-9](_?[0-9])*[eE][+-]?[0-9](_?[0-9])*',
                is_regex => 1,
                line_number => 204,
                alias => 'FLOAT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOAT_DOT',
                pattern => '\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?',
                is_regex => 1,
                line_number => 205,
                alias => 'FLOAT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOAT',
                pattern => '[0-9](_?[0-9])*\\.[0-9]*(_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?',
                is_regex => 1,
                line_number => 206,
                alias => 'FLOAT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'INT_HEX',
                pattern => '0[xX](_?[0-9a-fA-F])+',
                is_regex => 1,
                line_number => 213,
                alias => 'INT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'INT_OCT',
                pattern => '0[oO](_?[0-7])+',
                is_regex => 1,
                line_number => 214,
                alias => 'INT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'INT_BIN',
                pattern => '0[bB](_?[01])+',
                is_regex => 1,
                line_number => 215,
                alias => 'INT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'INT',
                pattern => '[0-9](_?[0-9])*',
                is_regex => 1,
                line_number => 216,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NAME',
                pattern => '[a-zA-Z_][a-zA-Z0-9_]*',
                is_regex => 1,
                line_number => 231,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'DOUBLE_STAR_EQUALS',
                pattern => '**=',
                is_regex => 0,
                line_number => 246,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEFT_SHIFT_EQUALS',
                pattern => '<<=',
                is_regex => 0,
                line_number => 247,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RIGHT_SHIFT_EQUALS',
                pattern => '>>=',
                is_regex => 0,
                line_number => 248,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOOR_DIV_EQUALS',
                pattern => '//=',
                is_regex => 0,
                line_number => 249,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COLONEQUALS',
                pattern => ':=',
                is_regex => 0,
                line_number => 279,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'DOUBLE_STAR',
                pattern => '**',
                is_regex => 0,
                line_number => 280,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOOR_DIV',
                pattern => '//',
                is_regex => 0,
                line_number => 281,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEFT_SHIFT',
                pattern => '<<',
                is_regex => 0,
                line_number => 282,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RIGHT_SHIFT',
                pattern => '>>',
                is_regex => 0,
                line_number => 283,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'EQUALS_EQUALS',
                pattern => '==',
                is_regex => 0,
                line_number => 284,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NOT_EQUALS',
                pattern => '!=',
                is_regex => 0,
                line_number => 285,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LESS_EQUALS',
                pattern => '<=',
                is_regex => 0,
                line_number => 286,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'GREATER_EQUALS',
                pattern => '>=',
                is_regex => 0,
                line_number => 287,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'ARROW',
                pattern => '->',
                is_regex => 0,
                line_number => 288,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'ELLIPSIS',
                pattern => '...',
                is_regex => 0,
                line_number => 289,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS_EQUALS',
                pattern => '+=',
                is_regex => 0,
                line_number => 290,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS_EQUALS',
                pattern => '-=',
                is_regex => 0,
                line_number => 291,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STAR_EQUALS',
                pattern => '*=',
                is_regex => 0,
                line_number => 292,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SLASH_EQUALS',
                pattern => '/=',
                is_regex => 0,
                line_number => 293,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PERCENT_EQUALS',
                pattern => '%=',
                is_regex => 0,
                line_number => 294,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AMP_EQUALS',
                pattern => '&=',
                is_regex => 0,
                line_number => 295,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PIPE_EQUALS',
                pattern => '|=',
                is_regex => 0,
                line_number => 296,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'CARET_EQUALS',
                pattern => '^=',
                is_regex => 0,
                line_number => 297,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AT_EQUALS',
                pattern => '@=',
                is_regex => 0,
                line_number => 298,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS',
                pattern => '+',
                is_regex => 0,
                line_number => 307,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS',
                pattern => '-',
                is_regex => 0,
                line_number => 308,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STAR',
                pattern => '*',
                is_regex => 0,
                line_number => 309,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SLASH',
                pattern => '/',
                is_regex => 0,
                line_number => 310,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PERCENT',
                pattern => '%',
                is_regex => 0,
                line_number => 311,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'EQUALS',
                pattern => '=',
                is_regex => 0,
                line_number => 312,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LESS_THAN',
                pattern => '<',
                is_regex => 0,
                line_number => 313,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'GREATER_THAN',
                pattern => '>',
                is_regex => 0,
                line_number => 314,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AMP',
                pattern => '&',
                is_regex => 0,
                line_number => 315,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PIPE',
                pattern => '|',
                is_regex => 0,
                line_number => 316,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'CARET',
                pattern => '^',
                is_regex => 0,
                line_number => 317,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'TILDE',
                pattern => '~',
                is_regex => 0,
                line_number => 318,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AT',
                pattern => '@',
                is_regex => 0,
                line_number => 319,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LPAREN',
                pattern => '(',
                is_regex => 0,
                line_number => 336,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RPAREN',
                pattern => ')',
                is_regex => 0,
                line_number => 337,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LBRACKET',
                pattern => '[',
                is_regex => 0,
                line_number => 338,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RBRACKET',
                pattern => ']',
                is_regex => 0,
                line_number => 339,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LBRACE',
                pattern => '{',
                is_regex => 0,
                line_number => 340,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RBRACE',
                pattern => '}',
                is_regex => 0,
                line_number => 341,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COMMA',
                pattern => ',',
                is_regex => 0,
                line_number => 342,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COLON',
                pattern => ':',
                is_regex => 0,
                line_number => 343,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SEMICOLON',
                pattern => ';',
                is_regex => 0,
                line_number => 344,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'DOT',
                pattern => '.',
                is_regex => 0,
                line_number => 345,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        keywords => [
            'False',
            'None',
            'True',
            'and',
            'as',
            'assert',
            'async',
            'await',
            'break',
            'class',
            'continue',
            'def',
            'del',
            'elif',
            'else',
            'except',
            'finally',
            'for',
            'from',
            'global',
            'if',
            'import',
            'in',
            'is',
            'lambda',
            'nonlocal',
            'not',
            'or',
            'pass',
            'raise',
            'return',
            'try',
            'while',
            'with',
            'yield',
        ],
        context_keywords => [],
        layout_keywords => [],
        soft_keywords => [],
        mode => 'indentation',
        escape_mode => '',
        skip_definitions => [
            bless({
                name => 'COMMENT',
                pattern => '#[^\\n]*',
                is_regex => 1,
                line_number => 88,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'WHITESPACE',
                pattern => '[ \\t]+',
                is_regex => 1,
                line_number => 89,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        error_definitions => [],
        reserved_keywords => [],
        groups => {},
        start_mode => '',
        transitions => [],
    }, 'CodingAdventures::GrammarTools::TokenGrammar';
}

1;
