name:                 coding-adventures-build-tool
version:              0.1.0
visibility:           public
id:                   coding-adventures-build-tool-0.1.0-inplace
key:                  coding-adventures-build-tool-0.1.0-inplace
license:              MIT
maintainer:           Adhithya Rajasekaran
author:               Adhithya Rajasekaran
synopsis:             Haskell implementation of the monorepo build tool
abi:                  inplace
exposed:              True
exposed-modules:      BuildTool
import-dirs:
    /Users/adhithya/Downloads/antigravity/coding-adventures/code/programs/haskell/build-tool/dist-newstyle/build/aarch64-osx/ghc-9.6.7/coding-adventures-build-tool-0.1.0/build

library-dirs:
    /Users/adhithya/Downloads/antigravity/coding-adventures/code/programs/haskell/build-tool/dist-newstyle/build/aarch64-osx/ghc-9.6.7/coding-adventures-build-tool-0.1.0/build

library-dirs-static:
    /Users/adhithya/Downloads/antigravity/coding-adventures/code/programs/haskell/build-tool/dist-newstyle/build/aarch64-osx/ghc-9.6.7/coding-adventures-build-tool-0.1.0/build

dynamic-library-dirs:
    /Users/adhithya/Downloads/antigravity/coding-adventures/code/programs/haskell/build-tool/dist-newstyle/build/aarch64-osx/ghc-9.6.7/coding-adventures-build-tool-0.1.0/build

data-dir:
    /Users/adhithya/Downloads/antigravity/coding-adventures/code/programs/haskell/build-tool/.

hs-libraries:         HScoding-adventures-build-tool-0.1.0-inplace
depends:              base-4.18.3.0
haddock-interfaces:
    /Users/adhithya/Downloads/antigravity/coding-adventures/code/programs/haskell/build-tool/dist-newstyle/build/aarch64-osx/ghc-9.6.7/coding-adventures-build-tool-0.1.0/doc/html/coding-adventures-build-tool/coding-adventures-build-tool.haddock

haddock-html:
    /Users/adhithya/Downloads/antigravity/coding-adventures/code/programs/haskell/build-tool/dist-newstyle/build/aarch64-osx/ghc-9.6.7/coding-adventures-build-tool-0.1.0/doc/html/coding-adventures-build-tool
