# AUTO-GENERATED FILE — DO NOT EDIT
# Source: toml.tokens
# Regenerate with: grammar-tools compile-tokens <source.tokens>
#
# This file embeds a TokenGrammar as native Python data structures.
# Downstream packages import TOKEN_GRAMMAR directly instead of
# reading and parsing the .tokens file at runtime.

from grammar_tools.token_grammar import PatternGroup, TokenDefinition, TokenGrammar

# fmt: off  # noqa: E501 — generated code may have long lines

TOKEN_GRAMMAR = TokenGrammar(
    version=1,
    case_insensitive=False,
    case_sensitive=True,
    definitions=[
        TokenDefinition(
            name='ML_BASIC_STRING',
            pattern='"""([^\\\\]|\\\\(.|\\n)|\\n)*?"""',
            is_regex=True,
            line_number=60,
            alias=None,
        ),
        TokenDefinition(
            name='ML_LITERAL_STRING',
            pattern="'''[\\s\\S]*?'''",
            is_regex=True,
            line_number=61,
            alias=None,
        ),
        TokenDefinition(
            name='BASIC_STRING',
            pattern='"([^"\\\\\\n]|\\\\.)*"',
            is_regex=True,
            line_number=70,
            alias=None,
        ),
        TokenDefinition(
            name='LITERAL_STRING',
            pattern="'[^'\\n]*'",
            is_regex=True,
            line_number=71,
            alias=None,
        ),
        TokenDefinition(
            name='OFFSET_DATETIME',
            pattern='\\d{4}-\\d{2}-\\d{2}[T ]\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?(Z|[+-]\\d{2}:\\d{2})',
            is_regex=True,
            line_number=91,
            alias=None,
        ),
        TokenDefinition(
            name='LOCAL_DATETIME',
            pattern='\\d{4}-\\d{2}-\\d{2}[T ]\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?',
            is_regex=True,
            line_number=92,
            alias=None,
        ),
        TokenDefinition(
            name='LOCAL_DATE',
            pattern='\\d{4}-\\d{2}-\\d{2}',
            is_regex=True,
            line_number=93,
            alias=None,
        ),
        TokenDefinition(
            name='LOCAL_TIME',
            pattern='\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?',
            is_regex=True,
            line_number=94,
            alias=None,
        ),
        TokenDefinition(
            name='FLOAT_SPECIAL',
            pattern='[+-]?(inf|nan)',
            is_regex=True,
            line_number=109,
            alias='FLOAT',
        ),
        TokenDefinition(
            name='FLOAT_EXP',
            pattern='[+-]?([0-9](_?[0-9])*)(\\.[0-9](_?[0-9])*)?[eE][+-]?[0-9](_?[0-9])*',
            is_regex=True,
            line_number=110,
            alias='FLOAT',
        ),
        TokenDefinition(
            name='FLOAT_DEC',
            pattern='[+-]?([0-9](_?[0-9])*)\\.([0-9](_?[0-9])*)',
            is_regex=True,
            line_number=111,
            alias='FLOAT',
        ),
        TokenDefinition(
            name='HEX_INTEGER',
            pattern='0x[0-9a-fA-F](_?[0-9a-fA-F])*',
            is_regex=True,
            line_number=123,
            alias='INTEGER',
        ),
        TokenDefinition(
            name='OCT_INTEGER',
            pattern='0o[0-7](_?[0-7])*',
            is_regex=True,
            line_number=124,
            alias='INTEGER',
        ),
        TokenDefinition(
            name='BIN_INTEGER',
            pattern='0b[01](_?[01])*',
            is_regex=True,
            line_number=125,
            alias='INTEGER',
        ),
        TokenDefinition(
            name='INTEGER',
            pattern='[+-]?[0-9](_?[0-9])*',
            is_regex=True,
            line_number=126,
            alias=None,
        ),
        TokenDefinition(
            name='TRUE',
            pattern='true',
            is_regex=False,
            line_number=137,
            alias=None,
        ),
        TokenDefinition(
            name='FALSE',
            pattern='false',
            is_regex=False,
            line_number=138,
            alias=None,
        ),
        TokenDefinition(
            name='BARE_KEY',
            pattern='[A-Za-z0-9_-]+',
            is_regex=True,
            line_number=152,
            alias=None,
        ),
        TokenDefinition(
            name='EQUALS',
            pattern='=',
            is_regex=False,
            line_number=162,
            alias=None,
        ),
        TokenDefinition(
            name='DOT',
            pattern='.',
            is_regex=False,
            line_number=163,
            alias=None,
        ),
        TokenDefinition(
            name='COMMA',
            pattern=',',
            is_regex=False,
            line_number=164,
            alias=None,
        ),
        TokenDefinition(
            name='LBRACKET',
            pattern='[',
            is_regex=False,
            line_number=165,
            alias=None,
        ),
        TokenDefinition(
            name='RBRACKET',
            pattern=']',
            is_regex=False,
            line_number=166,
            alias=None,
        ),
        TokenDefinition(
            name='LBRACE',
            pattern='{',
            is_regex=False,
            line_number=167,
            alias=None,
        ),
        TokenDefinition(
            name='RBRACE',
            pattern='}',
            is_regex=False,
            line_number=168,
            alias=None,
        ),
    ],
    keywords=[],
    mode=None,
    escape_mode='none',
    skip_definitions=[
        TokenDefinition(
            name='COMMENT',
            pattern='#[^\\n]*',
            is_regex=True,
            line_number=28,
            alias=None,
        ),
        TokenDefinition(
            name='WHITESPACE',
            pattern='[ \\t]+',
            is_regex=True,
            line_number=29,
            alias=None,
        ),
    ],
    reserved_keywords=[],
    error_definitions=[],
    groups={},
)
