// AUTO-GENERATED FILE — DO NOT EDIT
// Source: verilog.tokens
// Regenerate with: grammar-tools compile-tokens verilog.tokens
//
// This file embeds a TokenGrammar as native TypeScript object literals.
// Import it directly instead of reading and parsing the .tokens file at
// runtime.

import type { TokenGrammar } from "@coding-adventures/grammar-tools";

export const TOKEN_GRAMMAR: TokenGrammar = {
  version: 0,
  caseInsensitive: false,
  caseSensitive: true,
  definitions: [
    {
      name: "STRING",
      pattern: "\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 49,
    },
    {
      name: "SIZED_NUMBER",
      pattern: "[0-9]*'[sS]?[bBoOdDhH][0-9a-fA-F_xXzZ]+",
      isRegex: true,
      lineNumber: 76,
    },
    {
      name: "REAL_NUMBER",
      pattern: "[0-9]+\\.[0-9]+([eE][+-]?[0-9]+)?",
      isRegex: true,
      lineNumber: 80,
    },
    {
      name: "NUMBER",
      pattern: "[0-9][0-9_]*",
      isRegex: true,
      lineNumber: 84,
    },
    {
      name: "SYSTEM_ID",
      pattern: "\\$[a-zA-Z_][a-zA-Z0-9_$]*",
      isRegex: true,
      lineNumber: 112,
    },
    {
      name: "DIRECTIVE",
      pattern: "`[a-zA-Z_][a-zA-Z0-9_]*",
      isRegex: true,
      lineNumber: 113,
    },
    {
      name: "ESCAPED_IDENT",
      pattern: "\\\\[^ \\t\\r\\n]+",
      isRegex: true,
      lineNumber: 114,
    },
    {
      name: "NAME",
      pattern: "[a-zA-Z_][a-zA-Z0-9_$]*",
      isRegex: true,
      lineNumber: 117,
    },
    {
      name: "ARITH_LEFT_SHIFT",
      pattern: "<<<",
      isRegex: false,
      lineNumber: 129,
    },
    {
      name: "ARITH_RIGHT_SHIFT",
      pattern: ">>>",
      isRegex: false,
      lineNumber: 130,
    },
    {
      name: "CASE_EQ",
      pattern: "===",
      isRegex: false,
      lineNumber: 139,
    },
    {
      name: "CASE_NEQ",
      pattern: "!==",
      isRegex: false,
      lineNumber: 140,
    },
    {
      name: "LOGIC_AND",
      pattern: "&&",
      isRegex: false,
      lineNumber: 148,
    },
    {
      name: "LOGIC_OR",
      pattern: "||",
      isRegex: false,
      lineNumber: 149,
    },
    {
      name: "LEFT_SHIFT",
      pattern: "<<",
      isRegex: false,
      lineNumber: 150,
    },
    {
      name: "RIGHT_SHIFT",
      pattern: ">>",
      isRegex: false,
      lineNumber: 151,
    },
    {
      name: "EQUALS_EQUALS",
      pattern: "==",
      isRegex: false,
      lineNumber: 152,
    },
    {
      name: "NOT_EQUALS",
      pattern: "!=",
      isRegex: false,
      lineNumber: 153,
    },
    {
      name: "LESS_EQUALS",
      pattern: "<=",
      isRegex: false,
      lineNumber: 154,
    },
    {
      name: "GREATER_EQUALS",
      pattern: ">=",
      isRegex: false,
      lineNumber: 155,
    },
    {
      name: "POWER",
      pattern: "**",
      isRegex: false,
      lineNumber: 156,
    },
    {
      name: "TRIGGER",
      pattern: "->",
      isRegex: false,
      lineNumber: 157,
    },
    {
      name: "PLUS",
      pattern: "+",
      isRegex: false,
      lineNumber: 171,
    },
    {
      name: "MINUS",
      pattern: "-",
      isRegex: false,
      lineNumber: 172,
    },
    {
      name: "STAR",
      pattern: "*",
      isRegex: false,
      lineNumber: 173,
    },
    {
      name: "SLASH",
      pattern: "/",
      isRegex: false,
      lineNumber: 174,
    },
    {
      name: "PERCENT",
      pattern: "%",
      isRegex: false,
      lineNumber: 175,
    },
    {
      name: "AMP",
      pattern: "&",
      isRegex: false,
      lineNumber: 176,
    },
    {
      name: "PIPE",
      pattern: "|",
      isRegex: false,
      lineNumber: 177,
    },
    {
      name: "CARET",
      pattern: "^",
      isRegex: false,
      lineNumber: 178,
    },
    {
      name: "TILDE",
      pattern: "~",
      isRegex: false,
      lineNumber: 179,
    },
    {
      name: "BANG",
      pattern: "!",
      isRegex: false,
      lineNumber: 180,
    },
    {
      name: "LESS_THAN",
      pattern: "<",
      isRegex: false,
      lineNumber: 181,
    },
    {
      name: "GREATER_THAN",
      pattern: ">",
      isRegex: false,
      lineNumber: 182,
    },
    {
      name: "EQUALS",
      pattern: "=",
      isRegex: false,
      lineNumber: 183,
    },
    {
      name: "QUESTION",
      pattern: "?",
      isRegex: false,
      lineNumber: 184,
    },
    {
      name: "COLON",
      pattern: ":",
      isRegex: false,
      lineNumber: 185,
    },
    {
      name: "LPAREN",
      pattern: "(",
      isRegex: false,
      lineNumber: 197,
    },
    {
      name: "RPAREN",
      pattern: ")",
      isRegex: false,
      lineNumber: 198,
    },
    {
      name: "LBRACKET",
      pattern: "[",
      isRegex: false,
      lineNumber: 199,
    },
    {
      name: "RBRACKET",
      pattern: "]",
      isRegex: false,
      lineNumber: 200,
    },
    {
      name: "LBRACE",
      pattern: "{",
      isRegex: false,
      lineNumber: 201,
    },
    {
      name: "RBRACE",
      pattern: "}",
      isRegex: false,
      lineNumber: 202,
    },
    {
      name: "SEMICOLON",
      pattern: ";",
      isRegex: false,
      lineNumber: 203,
    },
    {
      name: "COMMA",
      pattern: ",",
      isRegex: false,
      lineNumber: 204,
    },
    {
      name: "DOT",
      pattern: ".",
      isRegex: false,
      lineNumber: 205,
    },
    {
      name: "HASH",
      pattern: "#",
      isRegex: false,
      lineNumber: 206,
    },
    {
      name: "AT",
      pattern: "@",
      isRegex: false,
      lineNumber: 207,
    },
  ],
  keywords: ["always","and","assign","begin","buf","case","casex","casez","default","defparam","else","end","endcase","endfunction","endgenerate","endmodule","endtask","for","function","generate","genvar","if","initial","inout","input","integer","localparam","module","nand","negedge","nor","not","or","output","parameter","posedge","real","reg","signed","supply0","supply1","task","tri","unsigned","wire","xnor","xor"],
  mode: undefined,
  escapeMode: undefined,
  skipDefinitions: [
    {
      name: "LINE_COMMENT",
      pattern: "\\/\\/[^\\n]*",
      isRegex: true,
      lineNumber: 34,
    },
    {
      name: "BLOCK_COMMENT",
      pattern: "\\/\\*([^*]|\\*[^/])*\\*\\/",
      isRegex: true,
      lineNumber: 35,
    },
    {
      name: "WHITESPACE",
      pattern: "[ \\t\\r\\n]+",
      isRegex: true,
      lineNumber: 36,
    },
  ],
  reservedKeywords: [],
  layoutKeywords: [],
  contextKeywords: [],
  errorDefinitions: [],
  groups: {},
};
