// AUTO-GENERATED FILE — DO NOT EDIT
// Source: starlark.tokens
// Regenerate with: grammar-tools compile-tokens starlark.tokens
//
// This file embeds a TokenGrammar as native Rust data structures.
// Call `token_grammar()` instead of reading and parsing the .tokens file.

use grammar_tools::token_grammar::{PatternGroup, TokenDefinition, TokenGrammar};
use std::collections::HashMap;

pub fn token_grammar() -> TokenGrammar {
    TokenGrammar {
        definitions: vec![
            TokenDefinition {
                name: r#"STRING_RAW_TRIPLE_DQ"#.to_string(),
                pattern: r#"[rR][bB]?"""([^"\\]|\\.|\n)*"""|[bB][rR]"""([^"\\]|\\.|\n)*""""#.to_string(),
                is_regex: true,
                line_number: 70,
                alias: Some(r#"STRING"#.to_string()),
            },
            TokenDefinition {
                name: r#"STRING_RAW_TRIPLE_SQ"#.to_string(),
                pattern: r#"[rR][bB]?'''([^'\\]|\\.|\n)*'''|[bB][rR]'''([^'\\]|\\.|\n)*'''"#.to_string(),
                is_regex: true,
                line_number: 71,
                alias: Some(r#"STRING"#.to_string()),
            },
            TokenDefinition {
                name: r#"STRING_TRIPLE_DQ"#.to_string(),
                pattern: r#"[bB]?"""([^"\\]|\\.|\n)*""""#.to_string(),
                is_regex: true,
                line_number: 72,
                alias: Some(r#"STRING"#.to_string()),
            },
            TokenDefinition {
                name: r#"STRING_TRIPLE_SQ"#.to_string(),
                pattern: r#"[bB]?'''([^'\\]|\\.|\n)*'''"#.to_string(),
                is_regex: true,
                line_number: 73,
                alias: Some(r#"STRING"#.to_string()),
            },
            TokenDefinition {
                name: r#"STRING_RAW_DQ"#.to_string(),
                pattern: r#"[rR][bB]?"([^"\\]|\\.)*"|[bB][rR]"([^"\\]|\\.)*""#.to_string(),
                is_regex: true,
                line_number: 76,
                alias: Some(r#"STRING"#.to_string()),
            },
            TokenDefinition {
                name: r#"STRING_RAW_SQ"#.to_string(),
                pattern: r#"[rR][bB]?'([^'\\]|\\.)*'|[bB][rR]'([^'\\]|\\.)*'"#.to_string(),
                is_regex: true,
                line_number: 77,
                alias: Some(r#"STRING"#.to_string()),
            },
            TokenDefinition {
                name: r#"STRING_DQ"#.to_string(),
                pattern: r#"[bB]?"([^"\\]|\\.)*""#.to_string(),
                is_regex: true,
                line_number: 78,
                alias: Some(r#"STRING"#.to_string()),
            },
            TokenDefinition {
                name: r#"STRING_SQ"#.to_string(),
                pattern: r#"[bB]?'([^'\\]|\\.)*'"#.to_string(),
                is_regex: true,
                line_number: 79,
                alias: Some(r#"STRING"#.to_string()),
            },
            TokenDefinition {
                name: r#"FLOAT"#.to_string(),
                pattern: r#"[0-9]+\.[0-9]*([eE][+-]?[0-9]+)?|\.[0-9]+([eE][+-]?[0-9]+)?|[0-9]+[eE][+-]?[0-9]+"#.to_string(),
                is_regex: true,
                line_number: 92,
                alias: None,
            },
            TokenDefinition {
                name: r#"INT_HEX"#.to_string(),
                pattern: r#"0[xX][0-9a-fA-F]+"#.to_string(),
                is_regex: true,
                line_number: 95,
                alias: Some(r#"INT"#.to_string()),
            },
            TokenDefinition {
                name: r#"INT_OCT"#.to_string(),
                pattern: r#"0[oO][0-7]+"#.to_string(),
                is_regex: true,
                line_number: 96,
                alias: Some(r#"INT"#.to_string()),
            },
            TokenDefinition {
                name: r#"INT"#.to_string(),
                pattern: r#"[0-9]+"#.to_string(),
                is_regex: true,
                line_number: 97,
                alias: None,
            },
            TokenDefinition {
                name: r#"NAME"#.to_string(),
                pattern: r#"[a-zA-Z_][a-zA-Z0-9_]*"#.to_string(),
                is_regex: true,
                line_number: 107,
                alias: None,
            },
            TokenDefinition {
                name: r#"DOUBLE_STAR_EQUALS"#.to_string(),
                pattern: r#"**="#.to_string(),
                is_regex: false,
                line_number: 116,
                alias: None,
            },
            TokenDefinition {
                name: r#"LEFT_SHIFT_EQUALS"#.to_string(),
                pattern: r#"<<="#.to_string(),
                is_regex: false,
                line_number: 117,
                alias: None,
            },
            TokenDefinition {
                name: r#"RIGHT_SHIFT_EQUALS"#.to_string(),
                pattern: r#">>="#.to_string(),
                is_regex: false,
                line_number: 118,
                alias: None,
            },
            TokenDefinition {
                name: r#"FLOOR_DIV_EQUALS"#.to_string(),
                pattern: r#"//="#.to_string(),
                is_regex: false,
                line_number: 119,
                alias: None,
            },
            TokenDefinition {
                name: r#"DOUBLE_STAR"#.to_string(),
                pattern: r#"**"#.to_string(),
                is_regex: false,
                line_number: 128,
                alias: None,
            },
            TokenDefinition {
                name: r#"FLOOR_DIV"#.to_string(),
                pattern: r#"//"#.to_string(),
                is_regex: false,
                line_number: 129,
                alias: None,
            },
            TokenDefinition {
                name: r#"LEFT_SHIFT"#.to_string(),
                pattern: r#"<<"#.to_string(),
                is_regex: false,
                line_number: 130,
                alias: None,
            },
            TokenDefinition {
                name: r#"RIGHT_SHIFT"#.to_string(),
                pattern: r#">>"#.to_string(),
                is_regex: false,
                line_number: 131,
                alias: None,
            },
            TokenDefinition {
                name: r#"EQUALS_EQUALS"#.to_string(),
                pattern: r#"=="#.to_string(),
                is_regex: false,
                line_number: 132,
                alias: None,
            },
            TokenDefinition {
                name: r#"NOT_EQUALS"#.to_string(),
                pattern: r#"!="#.to_string(),
                is_regex: false,
                line_number: 133,
                alias: None,
            },
            TokenDefinition {
                name: r#"LESS_EQUALS"#.to_string(),
                pattern: r#"<="#.to_string(),
                is_regex: false,
                line_number: 134,
                alias: None,
            },
            TokenDefinition {
                name: r#"GREATER_EQUALS"#.to_string(),
                pattern: r#">="#.to_string(),
                is_regex: false,
                line_number: 135,
                alias: None,
            },
            TokenDefinition {
                name: r#"PLUS_EQUALS"#.to_string(),
                pattern: r#"+="#.to_string(),
                is_regex: false,
                line_number: 136,
                alias: None,
            },
            TokenDefinition {
                name: r#"MINUS_EQUALS"#.to_string(),
                pattern: r#"-="#.to_string(),
                is_regex: false,
                line_number: 137,
                alias: None,
            },
            TokenDefinition {
                name: r#"STAR_EQUALS"#.to_string(),
                pattern: r#"*="#.to_string(),
                is_regex: false,
                line_number: 138,
                alias: None,
            },
            TokenDefinition {
                name: r#"SLASH_EQUALS"#.to_string(),
                pattern: r#"/="#.to_string(),
                is_regex: false,
                line_number: 139,
                alias: None,
            },
            TokenDefinition {
                name: r#"PERCENT_EQUALS"#.to_string(),
                pattern: r#"%="#.to_string(),
                is_regex: false,
                line_number: 140,
                alias: None,
            },
            TokenDefinition {
                name: r#"AMP_EQUALS"#.to_string(),
                pattern: r#"&="#.to_string(),
                is_regex: false,
                line_number: 141,
                alias: None,
            },
            TokenDefinition {
                name: r#"PIPE_EQUALS"#.to_string(),
                pattern: r#"|="#.to_string(),
                is_regex: false,
                line_number: 142,
                alias: None,
            },
            TokenDefinition {
                name: r#"CARET_EQUALS"#.to_string(),
                pattern: r#"^="#.to_string(),
                is_regex: false,
                line_number: 143,
                alias: None,
            },
            TokenDefinition {
                name: r#"PLUS"#.to_string(),
                pattern: r#"+"#.to_string(),
                is_regex: false,
                line_number: 149,
                alias: None,
            },
            TokenDefinition {
                name: r#"MINUS"#.to_string(),
                pattern: r#"-"#.to_string(),
                is_regex: false,
                line_number: 150,
                alias: None,
            },
            TokenDefinition {
                name: r#"STAR"#.to_string(),
                pattern: r#"*"#.to_string(),
                is_regex: false,
                line_number: 151,
                alias: None,
            },
            TokenDefinition {
                name: r#"SLASH"#.to_string(),
                pattern: r#"/"#.to_string(),
                is_regex: false,
                line_number: 152,
                alias: None,
            },
            TokenDefinition {
                name: r#"PERCENT"#.to_string(),
                pattern: r#"%"#.to_string(),
                is_regex: false,
                line_number: 153,
                alias: None,
            },
            TokenDefinition {
                name: r#"EQUALS"#.to_string(),
                pattern: r#"="#.to_string(),
                is_regex: false,
                line_number: 154,
                alias: None,
            },
            TokenDefinition {
                name: r#"LESS_THAN"#.to_string(),
                pattern: r#"<"#.to_string(),
                is_regex: false,
                line_number: 155,
                alias: None,
            },
            TokenDefinition {
                name: r#"GREATER_THAN"#.to_string(),
                pattern: r#">"#.to_string(),
                is_regex: false,
                line_number: 156,
                alias: None,
            },
            TokenDefinition {
                name: r#"AMP"#.to_string(),
                pattern: r#"&"#.to_string(),
                is_regex: false,
                line_number: 157,
                alias: None,
            },
            TokenDefinition {
                name: r#"PIPE"#.to_string(),
                pattern: r#"|"#.to_string(),
                is_regex: false,
                line_number: 158,
                alias: None,
            },
            TokenDefinition {
                name: r#"CARET"#.to_string(),
                pattern: r#"^"#.to_string(),
                is_regex: false,
                line_number: 159,
                alias: None,
            },
            TokenDefinition {
                name: r#"TILDE"#.to_string(),
                pattern: r#"~"#.to_string(),
                is_regex: false,
                line_number: 160,
                alias: None,
            },
            TokenDefinition {
                name: r#"LPAREN"#.to_string(),
                pattern: r#"("#.to_string(),
                is_regex: false,
                line_number: 166,
                alias: None,
            },
            TokenDefinition {
                name: r#"RPAREN"#.to_string(),
                pattern: r#")"#.to_string(),
                is_regex: false,
                line_number: 167,
                alias: None,
            },
            TokenDefinition {
                name: r#"LBRACKET"#.to_string(),
                pattern: r#"["#.to_string(),
                is_regex: false,
                line_number: 168,
                alias: None,
            },
            TokenDefinition {
                name: r#"RBRACKET"#.to_string(),
                pattern: r#"]"#.to_string(),
                is_regex: false,
                line_number: 169,
                alias: None,
            },
            TokenDefinition {
                name: r#"LBRACE"#.to_string(),
                pattern: r#"{"#.to_string(),
                is_regex: false,
                line_number: 170,
                alias: None,
            },
            TokenDefinition {
                name: r#"RBRACE"#.to_string(),
                pattern: r#"}"#.to_string(),
                is_regex: false,
                line_number: 171,
                alias: None,
            },
            TokenDefinition {
                name: r#"COMMA"#.to_string(),
                pattern: r#","#.to_string(),
                is_regex: false,
                line_number: 172,
                alias: None,
            },
            TokenDefinition {
                name: r#"COLON"#.to_string(),
                pattern: r#":"#.to_string(),
                is_regex: false,
                line_number: 173,
                alias: None,
            },
            TokenDefinition {
                name: r#"SEMICOLON"#.to_string(),
                pattern: r#";"#.to_string(),
                is_regex: false,
                line_number: 174,
                alias: None,
            },
            TokenDefinition {
                name: r#"DOT"#.to_string(),
                pattern: r#"."#.to_string(),
                is_regex: false,
                line_number: 175,
                alias: None,
            },
        ],
        keywords: vec![r#"and"#.to_string(), r#"break"#.to_string(), r#"continue"#.to_string(), r#"def"#.to_string(), r#"elif"#.to_string(), r#"else"#.to_string(), r#"for"#.to_string(), r#"if"#.to_string(), r#"in"#.to_string(), r#"lambda"#.to_string(), r#"load"#.to_string(), r#"not"#.to_string(), r#"or"#.to_string(), r#"pass"#.to_string(), r#"return"#.to_string(), r#"True"#.to_string(), r#"False"#.to_string(), r#"None"#.to_string()],
        mode: Some(r#"indentation"#.to_string()),
        skip_definitions: vec![
            TokenDefinition {
                name: r#"COMMENT"#.to_string(),
                pattern: r#"#[^\n]*"#.to_string(),
                is_regex: true,
                line_number: 51,
                alias: None,
            },
            TokenDefinition {
                name: r#"WHITESPACE"#.to_string(),
                pattern: r#"[ \t]+"#.to_string(),
                is_regex: true,
                line_number: 52,
                alias: None,
            },
        ],
        reserved_keywords: vec![r#"as"#.to_string(), r#"assert"#.to_string(), r#"async"#.to_string(), r#"await"#.to_string(), r#"class"#.to_string(), r#"del"#.to_string(), r#"except"#.to_string(), r#"finally"#.to_string(), r#"from"#.to_string(), r#"global"#.to_string(), r#"import"#.to_string(), r#"is"#.to_string(), r#"nonlocal"#.to_string(), r#"raise"#.to_string(), r#"try"#.to_string(), r#"while"#.to_string(), r#"with"#.to_string(), r#"yield"#.to_string()],
        escapes: None,
        error_definitions: vec![],
        groups: HashMap::new(),
        case_sensitive: true,
        version: 1,
        case_insensitive: false,
            context_keywords: Vec::new(),
    }
}
