// AUTO-GENERATED FILE - DO NOT EDIT
#![allow(clippy::all)]
use std::collections::HashMap;
use grammar_tools::token_grammar::{TokenGrammar, TokenDefinition, PatternGroup};

pub fn StarlarkTokens() -> TokenGrammar {
    let groups = HashMap::new();
    TokenGrammar {
        version: 1,
        case_insensitive: false,
        case_sensitive: true,
        mode: Some("indentation".to_string()),
        escapes: None,
        keywords: vec!["and".to_string(), "break".to_string(), "continue".to_string(), "def".to_string(), "elif".to_string(), "else".to_string(), "for".to_string(), "if".to_string(), "in".to_string(), "lambda".to_string(), "load".to_string(), "not".to_string(), "or".to_string(), "pass".to_string(), "return".to_string(), "True".to_string(), "False".to_string(), "None".to_string()],
        reserved_keywords: vec!["as".to_string(), "assert".to_string(), "async".to_string(), "await".to_string(), "class".to_string(), "del".to_string(), "except".to_string(), "finally".to_string(), "from".to_string(), "global".to_string(), "import".to_string(), "is".to_string(), "nonlocal".to_string(), "raise".to_string(), "try".to_string(), "while".to_string(), "with".to_string(), "yield".to_string()],
        definitions: vec![
            TokenDefinition { name: "STRING_RAW_TRIPLE_DQ".to_string(), pattern: "[rR][bB]?\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"|[bB][rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"".to_string(), is_regex: true, line_number: 70, alias: Some("STRING".to_string()) },
            TokenDefinition { name: "STRING_RAW_TRIPLE_SQ".to_string(), pattern: "[rR][bB]?'''([^'\\\\]|\\\\.|\\n)*'''|[bB][rR]'''([^'\\\\]|\\\\.|\\n)*'''".to_string(), is_regex: true, line_number: 71, alias: Some("STRING".to_string()) },
            TokenDefinition { name: "STRING_TRIPLE_DQ".to_string(), pattern: "[bB]?\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"".to_string(), is_regex: true, line_number: 72, alias: Some("STRING".to_string()) },
            TokenDefinition { name: "STRING_TRIPLE_SQ".to_string(), pattern: "[bB]?'''([^'\\\\]|\\\\.|\\n)*'''".to_string(), is_regex: true, line_number: 73, alias: Some("STRING".to_string()) },
            TokenDefinition { name: "STRING_RAW_DQ".to_string(), pattern: "[rR][bB]?\"([^\"\\\\]|\\\\.)*\"|[bB][rR]\"([^\"\\\\]|\\\\.)*\"".to_string(), is_regex: true, line_number: 76, alias: Some("STRING".to_string()) },
            TokenDefinition { name: "STRING_RAW_SQ".to_string(), pattern: "[rR][bB]?'([^'\\\\]|\\\\.)*'|[bB][rR]'([^'\\\\]|\\\\.)*'".to_string(), is_regex: true, line_number: 77, alias: Some("STRING".to_string()) },
            TokenDefinition { name: "STRING_DQ".to_string(), pattern: "[bB]?\"([^\"\\\\]|\\\\.)*\"".to_string(), is_regex: true, line_number: 78, alias: Some("STRING".to_string()) },
            TokenDefinition { name: "STRING_SQ".to_string(), pattern: "[bB]?'([^'\\\\]|\\\\.)*'".to_string(), is_regex: true, line_number: 79, alias: Some("STRING".to_string()) },
            TokenDefinition { name: "FLOAT".to_string(), pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?|\\.[0-9]+([eE][+-]?[0-9]+)?|[0-9]+[eE][+-]?[0-9]+".to_string(), is_regex: true, line_number: 92, alias: None },
            TokenDefinition { name: "INT_HEX".to_string(), pattern: "0[xX][0-9a-fA-F]+".to_string(), is_regex: true, line_number: 95, alias: Some("INT".to_string()) },
            TokenDefinition { name: "INT_OCT".to_string(), pattern: "0[oO][0-7]+".to_string(), is_regex: true, line_number: 96, alias: Some("INT".to_string()) },
            TokenDefinition { name: "INT".to_string(), pattern: "[0-9]+".to_string(), is_regex: true, line_number: 97, alias: None },
            TokenDefinition { name: "NAME".to_string(), pattern: "[a-zA-Z_][a-zA-Z0-9_]*".to_string(), is_regex: true, line_number: 107, alias: None },
            TokenDefinition { name: "DOUBLE_STAR_EQUALS".to_string(), pattern: "**=".to_string(), is_regex: false, line_number: 116, alias: None },
            TokenDefinition { name: "LEFT_SHIFT_EQUALS".to_string(), pattern: "<<=".to_string(), is_regex: false, line_number: 117, alias: None },
            TokenDefinition { name: "RIGHT_SHIFT_EQUALS".to_string(), pattern: ">>=".to_string(), is_regex: false, line_number: 118, alias: None },
            TokenDefinition { name: "FLOOR_DIV_EQUALS".to_string(), pattern: "//=".to_string(), is_regex: false, line_number: 119, alias: None },
            TokenDefinition { name: "DOUBLE_STAR".to_string(), pattern: "**".to_string(), is_regex: false, line_number: 128, alias: None },
            TokenDefinition { name: "FLOOR_DIV".to_string(), pattern: "//".to_string(), is_regex: false, line_number: 129, alias: None },
            TokenDefinition { name: "LEFT_SHIFT".to_string(), pattern: "<<".to_string(), is_regex: false, line_number: 130, alias: None },
            TokenDefinition { name: "RIGHT_SHIFT".to_string(), pattern: ">>".to_string(), is_regex: false, line_number: 131, alias: None },
            TokenDefinition { name: "EQUALS_EQUALS".to_string(), pattern: "==".to_string(), is_regex: false, line_number: 132, alias: None },
            TokenDefinition { name: "NOT_EQUALS".to_string(), pattern: "!=".to_string(), is_regex: false, line_number: 133, alias: None },
            TokenDefinition { name: "LESS_EQUALS".to_string(), pattern: "<=".to_string(), is_regex: false, line_number: 134, alias: None },
            TokenDefinition { name: "GREATER_EQUALS".to_string(), pattern: ">=".to_string(), is_regex: false, line_number: 135, alias: None },
            TokenDefinition { name: "PLUS_EQUALS".to_string(), pattern: "+=".to_string(), is_regex: false, line_number: 136, alias: None },
            TokenDefinition { name: "MINUS_EQUALS".to_string(), pattern: "-=".to_string(), is_regex: false, line_number: 137, alias: None },
            TokenDefinition { name: "STAR_EQUALS".to_string(), pattern: "*=".to_string(), is_regex: false, line_number: 138, alias: None },
            TokenDefinition { name: "SLASH_EQUALS".to_string(), pattern: "/=".to_string(), is_regex: false, line_number: 139, alias: None },
            TokenDefinition { name: "PERCENT_EQUALS".to_string(), pattern: "%=".to_string(), is_regex: false, line_number: 140, alias: None },
            TokenDefinition { name: "AMP_EQUALS".to_string(), pattern: "&=".to_string(), is_regex: false, line_number: 141, alias: None },
            TokenDefinition { name: "PIPE_EQUALS".to_string(), pattern: "|=".to_string(), is_regex: false, line_number: 142, alias: None },
            TokenDefinition { name: "CARET_EQUALS".to_string(), pattern: "^=".to_string(), is_regex: false, line_number: 143, alias: None },
            TokenDefinition { name: "PLUS".to_string(), pattern: "+".to_string(), is_regex: false, line_number: 149, alias: None },
            TokenDefinition { name: "MINUS".to_string(), pattern: "-".to_string(), is_regex: false, line_number: 150, alias: None },
            TokenDefinition { name: "STAR".to_string(), pattern: "*".to_string(), is_regex: false, line_number: 151, alias: None },
            TokenDefinition { name: "SLASH".to_string(), pattern: "/".to_string(), is_regex: false, line_number: 152, alias: None },
            TokenDefinition { name: "PERCENT".to_string(), pattern: "%".to_string(), is_regex: false, line_number: 153, alias: None },
            TokenDefinition { name: "EQUALS".to_string(), pattern: "=".to_string(), is_regex: false, line_number: 154, alias: None },
            TokenDefinition { name: "LESS_THAN".to_string(), pattern: "<".to_string(), is_regex: false, line_number: 155, alias: None },
            TokenDefinition { name: "GREATER_THAN".to_string(), pattern: ">".to_string(), is_regex: false, line_number: 156, alias: None },
            TokenDefinition { name: "AMP".to_string(), pattern: "&".to_string(), is_regex: false, line_number: 157, alias: None },
            TokenDefinition { name: "PIPE".to_string(), pattern: "|".to_string(), is_regex: false, line_number: 158, alias: None },
            TokenDefinition { name: "CARET".to_string(), pattern: "^".to_string(), is_regex: false, line_number: 159, alias: None },
            TokenDefinition { name: "TILDE".to_string(), pattern: "~".to_string(), is_regex: false, line_number: 160, alias: None },
            TokenDefinition { name: "LPAREN".to_string(), pattern: "(".to_string(), is_regex: false, line_number: 166, alias: None },
            TokenDefinition { name: "RPAREN".to_string(), pattern: ")".to_string(), is_regex: false, line_number: 167, alias: None },
            TokenDefinition { name: "LBRACKET".to_string(), pattern: "[".to_string(), is_regex: false, line_number: 168, alias: None },
            TokenDefinition { name: "RBRACKET".to_string(), pattern: "]".to_string(), is_regex: false, line_number: 169, alias: None },
            TokenDefinition { name: "LBRACE".to_string(), pattern: "{".to_string(), is_regex: false, line_number: 170, alias: None },
            TokenDefinition { name: "RBRACE".to_string(), pattern: "}".to_string(), is_regex: false, line_number: 171, alias: None },
            TokenDefinition { name: "COMMA".to_string(), pattern: ",".to_string(), is_regex: false, line_number: 172, alias: None },
            TokenDefinition { name: "COLON".to_string(), pattern: ":".to_string(), is_regex: false, line_number: 173, alias: None },
            TokenDefinition { name: "SEMICOLON".to_string(), pattern: ";".to_string(), is_regex: false, line_number: 174, alias: None },
            TokenDefinition { name: "DOT".to_string(), pattern: ".".to_string(), is_regex: false, line_number: 175, alias: None },
        ],
        skip_definitions: vec![
            TokenDefinition { name: "COMMENT".to_string(), pattern: "#[^\\n]*".to_string(), is_regex: true, line_number: 51, alias: None },
            TokenDefinition { name: "WHITESPACE".to_string(), pattern: "[ \\t]+".to_string(), is_regex: true, line_number: 52, alias: None },
        ],
        error_definitions: vec![
        ],
        groups,
    }
}
