# frozen_string_literal: true
# AUTO-GENERATED FILE — DO NOT EDIT
# Source: es2019.tokens
# Regenerate with: grammar-tools compile-tokens es2019.tokens
#
# This file embeds a TokenGrammar as native Ruby data structures.
# Downstream packages require this file directly instead of reading
# and parsing the .tokens file at runtime.

require "coding_adventures_grammar_tools"

GT = CodingAdventures::GrammarTools unless defined?(GT)

TOKEN_GRAMMAR = GT::TokenGrammar.new(
  version: 1,
  case_insensitive: false,
  case_sensitive: true,
  definitions: [
      GT::TokenDefinition.new(
        name: "NAME",
        pattern: "[a-zA-Z_$][a-zA-Z0-9_$]*",
        is_regex: true,
        line_number: 30,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BINARY_NUMBER",
        pattern: "0[bB][01]+",
        is_regex: true,
        line_number: 34,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "OCTAL_NUMBER",
        pattern: "0[oO][0-7]+",
        is_regex: true,
        line_number: 35,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "HEX_NUMBER",
        pattern: "0[xX][0-9a-fA-F]+",
        is_regex: true,
        line_number: 36,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "FLOAT_NUMBER",
        pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?",
        is_regex: true,
        line_number: 37,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "LEADING_DOT_FLOAT",
        pattern: "\\.[0-9]+([eE][+-]?[0-9]+)?",
        is_regex: true,
        line_number: 38,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "SCI_NUMBER",
        pattern: "[0-9]+[eE][+-]?[0-9]+",
        is_regex: true,
        line_number: 39,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "INT_NUMBER",
        pattern: "[0-9]+",
        is_regex: true,
        line_number: 40,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "STRING_DQ",
        pattern: "\"([^\"\\\\]|\\\\.)*\"",
        is_regex: true,
        line_number: 60,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_SQ",
        pattern: "'([^'\\\\]|\\\\.)*'",
        is_regex: true,
        line_number: 61,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "TEMPLATE_HEAD",
        pattern: "`([^`\\\\$]|\\\\.|\\$[^{])*\\$\\{",
        is_regex: true,
        line_number: 65,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "TEMPLATE_NO_SUB",
        pattern: "`([^`\\\\$]|\\\\.|\\$[^{])*`",
        is_regex: true,
        line_number: 66,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "REGEX",
        pattern: "\\/([^\\/\\\\\\n]|\\\\.)+\\/[gimsuy]*",
        is_regex: true,
        line_number: 70,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR_STAR_EQUALS",
        pattern: "**=",
        is_regex: false,
        line_number: 76,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR_STAR",
        pattern: "**",
        is_regex: false,
        line_number: 77,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STRICT_EQUALS",
        pattern: "===",
        is_regex: false,
        line_number: 78,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STRICT_NOT_EQUALS",
        pattern: "!==",
        is_regex: false,
        line_number: 79,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "UNSIGNED_RIGHT_SHIFT_EQUALS",
        pattern: ">>>=",
        is_regex: false,
        line_number: 80,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "UNSIGNED_RIGHT_SHIFT",
        pattern: ">>>",
        is_regex: false,
        line_number: 81,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LEFT_SHIFT_EQUALS",
        pattern: "<<=",
        is_regex: false,
        line_number: 82,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RIGHT_SHIFT_EQUALS",
        pattern: ">>=",
        is_regex: false,
        line_number: 83,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQUALS_EQUALS",
        pattern: "==",
        is_regex: false,
        line_number: 84,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NOT_EQUALS",
        pattern: "!=",
        is_regex: false,
        line_number: 85,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_EQUALS",
        pattern: "<=",
        is_regex: false,
        line_number: 86,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_EQUALS",
        pattern: ">=",
        is_regex: false,
        line_number: 87,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS_EQUALS",
        pattern: "+=",
        is_regex: false,
        line_number: 88,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS_EQUALS",
        pattern: "-=",
        is_regex: false,
        line_number: 89,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR_EQUALS",
        pattern: "*=",
        is_regex: false,
        line_number: 90,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SLASH_EQUALS",
        pattern: "/=",
        is_regex: false,
        line_number: 91,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PERCENT_EQUALS",
        pattern: "%=",
        is_regex: false,
        line_number: 92,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AMPERSAND_EQUALS",
        pattern: "&=",
        is_regex: false,
        line_number: 93,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PIPE_EQUALS",
        pattern: "|=",
        is_regex: false,
        line_number: 94,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CARET_EQUALS",
        pattern: "^=",
        is_regex: false,
        line_number: 95,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LEFT_SHIFT",
        pattern: "<<",
        is_regex: false,
        line_number: 96,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RIGHT_SHIFT",
        pattern: ">>",
        is_regex: false,
        line_number: 97,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AND_AND",
        pattern: "&&",
        is_regex: false,
        line_number: 98,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "OR_OR",
        pattern: "||",
        is_regex: false,
        line_number: 99,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS_PLUS",
        pattern: "++",
        is_regex: false,
        line_number: 100,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS_MINUS",
        pattern: "--",
        is_regex: false,
        line_number: 101,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "ARROW",
        pattern: "=>",
        is_regex: false,
        line_number: 102,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "ELLIPSIS",
        pattern: "...",
        is_regex: false,
        line_number: 103,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQUALS",
        pattern: "=",
        is_regex: false,
        line_number: 109,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS",
        pattern: "+",
        is_regex: false,
        line_number: 110,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS",
        pattern: "-",
        is_regex: false,
        line_number: 111,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR",
        pattern: "*",
        is_regex: false,
        line_number: 112,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SLASH",
        pattern: "/",
        is_regex: false,
        line_number: 113,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PERCENT",
        pattern: "%",
        is_regex: false,
        line_number: 114,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_THAN",
        pattern: "<",
        is_regex: false,
        line_number: 115,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_THAN",
        pattern: ">",
        is_regex: false,
        line_number: 116,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BANG",
        pattern: "!",
        is_regex: false,
        line_number: 117,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AMPERSAND",
        pattern: "&",
        is_regex: false,
        line_number: 118,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PIPE",
        pattern: "|",
        is_regex: false,
        line_number: 119,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CARET",
        pattern: "^",
        is_regex: false,
        line_number: 120,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "TILDE",
        pattern: "~",
        is_regex: false,
        line_number: 121,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "QUESTION",
        pattern: "?",
        is_regex: false,
        line_number: 122,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LPAREN",
        pattern: "(",
        is_regex: false,
        line_number: 128,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RPAREN",
        pattern: ")",
        is_regex: false,
        line_number: 129,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACE",
        pattern: "{",
        is_regex: false,
        line_number: 130,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACE",
        pattern: "}",
        is_regex: false,
        line_number: 131,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACKET",
        pattern: "[",
        is_regex: false,
        line_number: 132,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACKET",
        pattern: "]",
        is_regex: false,
        line_number: 133,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SEMICOLON",
        pattern: ";",
        is_regex: false,
        line_number: 134,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COMMA",
        pattern: ",",
        is_regex: false,
        line_number: 135,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COLON",
        pattern: ":",
        is_regex: false,
        line_number: 136,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DOT",
        pattern: ".",
        is_regex: false,
        line_number: 137,
        alias_name: nil,
      ),
    ],
  keywords: ["break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "export", "extends", "finally", "for", "function", "if", "import", "in", "instanceof", "let", "new", "return", "super", "switch", "this", "throw", "try", "typeof", "var", "void", "while", "with", "yield", "true", "false", "null"],
  mode: nil,
  escape_mode: nil,
  skip_definitions: [
      GT::TokenDefinition.new(
        name: "WHITESPACE",
        pattern: "[ \\t\\r\\n\\v\\f]+",
        is_regex: true,
        line_number: 216,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LINE_COMMENT",
        pattern: "\\/\\/[^\\n]*",
        is_regex: true,
        line_number: 217,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BLOCK_COMMENT",
        pattern: "\\/\\*([^*]|\\*[^\\/])*\\*\\/",
        is_regex: true,
        line_number: 218,
        alias_name: nil,
      ),
    ],
  reserved_keywords: ["enum"],
  error_definitions: [
      GT::TokenDefinition.new(
        name: "BAD_STRING_DQ",
        pattern: "\"[^\"]*$",
        is_regex: true,
        line_number: 225,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BAD_STRING_SQ",
        pattern: "'[^']*$",
        is_regex: true,
        line_number: 226,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BAD_REGEX",
        pattern: "\\/([^\\/\\\\\\n]|\\\\.)*$",
        is_regex: true,
        line_number: 227,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BAD_TEMPLATE",
        pattern: "`([^`\\\\$]|\\\\.|\\$[^{])*$",
        is_regex: true,
        line_number: 228,
        alias_name: nil,
      ),
    ],
  groups: {
      "template" => GT::PatternGroup.new(
        name: "template",
        definitions: [
          GT::TokenDefinition.new(
            name: "TEMPLATE_MIDDLE",
            pattern: "\\}([^`\\\\$]|\\\\.|\\$[^{])*\\$\\{",
            is_regex: true,
            line_number: 208,
            alias_name: nil,
          ),
          GT::TokenDefinition.new(
            name: "TEMPLATE_TAIL",
            pattern: "\\}([^`\\\\$]|\\\\.|\\$[^{])*`",
            is_regex: true,
            line_number: 209,
            alias_name: nil,
          ),
        ],
      ),
    },
  layout_keywords: [],
  context_keywords: ["as", "async", "await", "from", "of", "get", "set", "static"],
  soft_keywords: [],
)
