load("code/packages/starlark/program-rules/go_binary.star", "go_binary")

_targets = [
    go_binary(
        name = "celsius-to-fahrenheit-predictor",
        srcs = ["**/*.go"],
        deps = [],
    ),
]
