name: coding_adventures_lexer
description: >
  Generic hand-written tokenizer for Dart with a formal tokenizer dispatch DFA.
version: 0.1.0
repository: https://github.com/adhithyan15/coding-adventures
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  coding_adventures_grammar_tools:
    path: ../grammar-tools
  coding_adventures_state_machine:
    path: ../state-machine

dev_dependencies:
  test: ^1.25.0
