defmodule CodingAdventures.TomlLexer.Grammar do
  # AUTO-GENERATED FILE — DO NOT EDIT
  # Source: toml.tokens
  # Regenerate with: grammar-tools compile-tokens toml.tokens
  #
  # This file embeds a TokenGrammar as native Elixir data structures.
  # Call token_grammar/0 instead of reading and parsing the .tokens file.
  
  alias CodingAdventures.GrammarTools.TokenGrammar
  
  def token_grammar do
    %TokenGrammar{
      definitions: [
          %{
            name: "ML_BASIC_STRING",
            pattern: "\"\"\"([^\\\\]|\\\\(.|\\n)|\\n)*?\"\"\"",
            is_regex: true,
            line_number: 60,
            alias: nil,
          },
          %{
            name: "ML_LITERAL_STRING",
            pattern: "'''[\\s\\S]*?'''",
            is_regex: true,
            line_number: 61,
            alias: nil,
          },
          %{
            name: "BASIC_STRING",
            pattern: "\"([^\"\\\\\\n]|\\\\.)*\"",
            is_regex: true,
            line_number: 70,
            alias: nil,
          },
          %{
            name: "LITERAL_STRING",
            pattern: "'[^'\\n]*'",
            is_regex: true,
            line_number: 71,
            alias: nil,
          },
          %{
            name: "OFFSET_DATETIME_FRAC_TZ",
            pattern: "\\d{4}-\\d{2}-\\d{2}[T ]\\d{2}:\\d{2}:\\d{2}\\.\\d+[+-]\\d{2}:\\d{2}",
            is_regex: true,
            line_number: 91,
            alias: "OFFSET_DATETIME",
          },
          %{
            name: "OFFSET_DATETIME_FRAC_Z",
            pattern: "\\d{4}-\\d{2}-\\d{2}[T ]\\d{2}:\\d{2}:\\d{2}\\.\\d+Z",
            is_regex: true,
            line_number: 92,
            alias: "OFFSET_DATETIME",
          },
          %{
            name: "OFFSET_DATETIME_TZ",
            pattern: "\\d{4}-\\d{2}-\\d{2}[T ]\\d{2}:\\d{2}:\\d{2}[+-]\\d{2}:\\d{2}",
            is_regex: true,
            line_number: 93,
            alias: "OFFSET_DATETIME",
          },
          %{
            name: "OFFSET_DATETIME_Z",
            pattern: "\\d{4}-\\d{2}-\\d{2}[T ]\\d{2}:\\d{2}:\\d{2}Z",
            is_regex: true,
            line_number: 94,
            alias: "OFFSET_DATETIME",
          },
          %{
            name: "LOCAL_DATETIME_FRAC",
            pattern: "\\d{4}-\\d{2}-\\d{2}[T ]\\d{2}:\\d{2}:\\d{2}\\.\\d+",
            is_regex: true,
            line_number: 95,
            alias: "LOCAL_DATETIME",
          },
          %{
            name: "LOCAL_DATETIME",
            pattern: "\\d{4}-\\d{2}-\\d{2}[T ]\\d{2}:\\d{2}:\\d{2}",
            is_regex: true,
            line_number: 96,
            alias: nil,
          },
          %{
            name: "LOCAL_DATE",
            pattern: "\\d{4}-\\d{2}-\\d{2}",
            is_regex: true,
            line_number: 97,
            alias: nil,
          },
          %{
            name: "LOCAL_TIME_FRAC",
            pattern: "\\d{2}:\\d{2}:\\d{2}\\.\\d+",
            is_regex: true,
            line_number: 98,
            alias: "LOCAL_TIME",
          },
          %{
            name: "LOCAL_TIME",
            pattern: "\\d{2}:\\d{2}:\\d{2}",
            is_regex: true,
            line_number: 99,
            alias: nil,
          },
          %{
            name: "FLOAT_INF",
            pattern: "[+-]?inf",
            is_regex: true,
            line_number: 114,
            alias: "FLOAT",
          },
          %{
            name: "FLOAT_NAN",
            pattern: "[+-]?nan",
            is_regex: true,
            line_number: 115,
            alias: "FLOAT",
          },
          %{
            name: "FLOAT_EXP",
            pattern: "[+-]?[0-9][0-9_]*\\.?[0-9_]*[eE][+-]?[0-9][0-9_]*",
            is_regex: true,
            line_number: 116,
            alias: "FLOAT",
          },
          %{
            name: "FLOAT_DEC",
            pattern: "[+-]?[0-9][0-9_]*\\.[0-9][0-9_]*",
            is_regex: true,
            line_number: 117,
            alias: "FLOAT",
          },
          %{
            name: "HEX_INTEGER",
            pattern: "0x[0-9a-fA-F][0-9a-fA-F_]*",
            is_regex: true,
            line_number: 129,
            alias: "INTEGER",
          },
          %{
            name: "OCT_INTEGER",
            pattern: "0o[0-7][0-7_]*",
            is_regex: true,
            line_number: 130,
            alias: "INTEGER",
          },
          %{
            name: "BIN_INTEGER",
            pattern: "0b[01][01_]*",
            is_regex: true,
            line_number: 131,
            alias: "INTEGER",
          },
          %{
            name: "INTEGER",
            pattern: "[+-]?[0-9][0-9_]*",
            is_regex: true,
            line_number: 132,
            alias: nil,
          },
          %{
            name: "TRUE",
            pattern: "true",
            is_regex: false,
            line_number: 143,
            alias: nil,
          },
          %{
            name: "FALSE",
            pattern: "false",
            is_regex: false,
            line_number: 144,
            alias: nil,
          },
          %{
            name: "BARE_KEY",
            pattern: "[A-Za-z0-9_-]+",
            is_regex: true,
            line_number: 158,
            alias: nil,
          },
          %{
            name: "EQUALS",
            pattern: "=",
            is_regex: false,
            line_number: 168,
            alias: nil,
          },
          %{
            name: "DOT",
            pattern: ".",
            is_regex: false,
            line_number: 169,
            alias: nil,
          },
          %{
            name: "COMMA",
            pattern: ",",
            is_regex: false,
            line_number: 170,
            alias: nil,
          },
          %{
            name: "LBRACKET",
            pattern: "[",
            is_regex: false,
            line_number: 171,
            alias: nil,
          },
          %{
            name: "RBRACKET",
            pattern: "]",
            is_regex: false,
            line_number: 172,
            alias: nil,
          },
          %{
            name: "LBRACE",
            pattern: "{",
            is_regex: false,
            line_number: 173,
            alias: nil,
          },
          %{
            name: "RBRACE",
            pattern: "}",
            is_regex: false,
            line_number: 174,
            alias: nil,
          },
          %{
            name: "NEWLINE",
            pattern: "\\r?\\n",
            is_regex: true,
            line_number: 175,
            alias: nil,
          },
        ],
      keywords: [],
      mode: nil,
      escape_mode: "none",
      skip_definitions: [
          %{
            name: "COMMENT",
            pattern: "#[^\\n]*",
            is_regex: true,
            line_number: 28,
            alias: nil,
          },
          %{
            name: "WHITESPACE",
            pattern: "[ \\t]+",
            is_regex: true,
            line_number: 29,
            alias: nil,
          },
        ],
      reserved_keywords: [],
      error_definitions: [],
      groups: %{},
      layout_keywords: [],
      case_sensitive: true,
      version: 1,
      case_insensitive: false,
      start_mode: nil,
      transitions: [],
    }
  end
end
