name: coding_adventures_parser
description: >
  Recursive-descent parser for the generic token stream produced by the Dart lexer package.
version: 0.1.0
repository: https://github.com/adhithyan15/coding-adventures
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  coding_adventures_grammar_tools:
    path: ../grammar-tools
  coding_adventures_lexer:
    path: ../lexer

dev_dependencies:
  test: ^1.25.0
