# AUTO-GENERATED FILE — DO NOT EDIT
# Source: sql.tokens
# Regenerate with: perl code/programs/perl/grammar-tools/grammar-tools.pl compile-tokens sql.tokens
#
# This file embeds a TokenGrammar as native Perl data structures.
# Call token_grammar() instead of reading and parsing the .tokens file.

package CodingAdventures::SqlLexer::_Grammar;
use strict;
use warnings;

sub token_grammar {
    return bless {
        definitions => [
            bless({
                name => 'BLOB_HEX',
                pattern => '[xX]\'[0-9A-Fa-f]*\'',
                is_regex => 1,
                line_number => 23,
                alias => 'BLOB',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'HEX_INT',
                pattern => '0[xX][0-9A-Fa-f]+',
                is_regex => 1,
                line_number => 29,
                alias => 'NUMBER',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NAME',
                pattern => '[a-zA-Z_][a-zA-Z0-9_]*',
                is_regex => 1,
                line_number => 30,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NUMBER',
                pattern => '[0-9]+\\.?[0-9]*',
                is_regex => 1,
                line_number => 31,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_SQ',
                pattern => '\'(\'\'|[^\'])*\'',
                is_regex => 1,
                line_number => 32,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'QUOTED_ID',
                pattern => '`[^`]+`',
                is_regex => 1,
                line_number => 33,
                alias => 'NAME',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'QUOTED_ID_DQ',
                pattern => '"([^"]|"")*"',
                is_regex => 1,
                line_number => 38,
                alias => 'NAME',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LESS_EQUALS',
                pattern => '<=',
                is_regex => 0,
                line_number => 40,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'GREATER_EQUALS',
                pattern => '>=',
                is_regex => 0,
                line_number => 41,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NOT_EQUALS',
                pattern => '!=',
                is_regex => 0,
                line_number => 42,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NEQ_ANSI',
                pattern => '<>',
                is_regex => 0,
                line_number => 43,
                alias => 'NOT_EQUALS',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'CONCAT_OP',
                pattern => '||',
                is_regex => 0,
                line_number => 44,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SHIFT_LEFT',
                pattern => '<<',
                is_regex => 0,
                line_number => 48,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SHIFT_RIGHT',
                pattern => '>>',
                is_regex => 0,
                line_number => 49,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'JSON_ARROW_TEXT',
                pattern => '->>',
                is_regex => 0,
                line_number => 56,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'JSON_ARROW',
                pattern => '->',
                is_regex => 0,
                line_number => 57,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'EQUALS',
                pattern => '=',
                is_regex => 0,
                line_number => 59,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LESS_THAN',
                pattern => '<',
                is_regex => 0,
                line_number => 60,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'GREATER_THAN',
                pattern => '>',
                is_regex => 0,
                line_number => 61,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS',
                pattern => '+',
                is_regex => 0,
                line_number => 62,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS',
                pattern => '-',
                is_regex => 0,
                line_number => 63,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STAR',
                pattern => '*',
                is_regex => 0,
                line_number => 64,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SLASH',
                pattern => '/',
                is_regex => 0,
                line_number => 65,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PERCENT',
                pattern => '%',
                is_regex => 0,
                line_number => 66,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BIT_AND_OP',
                pattern => '&',
                is_regex => 0,
                line_number => 70,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BIT_OR_OP',
                pattern => '|',
                is_regex => 0,
                line_number => 71,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BIT_NOT_OP',
                pattern => '~',
                is_regex => 0,
                line_number => 72,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LPAREN',
                pattern => '(',
                is_regex => 0,
                line_number => 74,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RPAREN',
                pattern => ')',
                is_regex => 0,
                line_number => 75,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COMMA',
                pattern => ',',
                is_regex => 0,
                line_number => 76,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SEMICOLON',
                pattern => ';',
                is_regex => 0,
                line_number => 77,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'DOT',
                pattern => '.',
                is_regex => 0,
                line_number => 78,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        keywords => [
            'WITH',
            'RECURSIVE',
            'SELECT',
            'FROM',
            'WHERE',
            'GROUP',
            'BY',
            'HAVING',
            'ORDER',
            'LIMIT',
            'OFFSET',
            'INSERT',
            'INTO',
            'VALUES',
            'UPDATE',
            'SET',
            'DELETE',
            'ALTER',
            'ADD',
            'COLUMN',
            'CREATE',
            'DROP',
            'RENAME',
            'TABLE',
            'IF',
            'EXISTS',
            'NOT',
            'AND',
            'OR',
            'NULL',
            'IS',
            'IN',
            'BETWEEN',
            'LIKE',
            'ESCAPE',
            'AS',
            'DISTINCT',
            'ALL',
            'UNION',
            'INTERSECT',
            'EXCEPT',
            'JOIN',
            'INNER',
            'LEFT',
            'RIGHT',
            'OUTER',
            'CROSS',
            'FULL',
            'ON',
            'ASC',
            'DESC',
            'TRUE',
            'FALSE',
            'CASE',
            'WHEN',
            'THEN',
            'ELSE',
            'END',
            'PRIMARY',
            'KEY',
            'AUTOINCREMENT',
            'UNIQUE',
            'INDEX',
            'INDEXED',
            'CHECK',
            'REFERENCES',
            'DEFAULT',
            'COLLATE',
            'ATTACH',
            'DETACH',
            'DATABASE',
            'STRICT',
            'WITHOUT',
            'VIEW',
            'BEGIN',
            'COMMIT',
            'ROLLBACK',
            'TRANSACTION',
            'SAVEPOINT',
            'RELEASE',
            'TO',
            'OVER',
            'PARTITION',
            'WINDOW',
            'TRIGGER',
            'BEFORE',
            'AFTER',
            'FOR',
            'EACH',
            'ROW',
            'RETURNING',
            'CAST',
            'GLOB',
            'NATURAL',
            'USING',
            'REPLACE',
            'IGNORE',
            'ABORT',
            'FAIL',
            'CONFLICT',
            'DO',
            'NOTHING',
            'ROWS',
            'RANGE',
            'GROUPS',
            'PRECEDING',
            'FOLLOWING',
            'UNBOUNDED',
            'CURRENT',
            'MATERIALIZED',
            'NULLS',
        ],
        context_keywords => [],
        layout_keywords => [],
        soft_keywords => [],
        mode => '',
        escape_mode => 'none',
        skip_definitions => [
            bless({
                name => 'WHITESPACE',
                pattern => '[ \\t\\r\\n]+',
                is_regex => 1,
                line_number => 194,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LINE_COMMENT',
                pattern => '--[^\\n]*',
                is_regex => 1,
                line_number => 195,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'BLOCK_COMMENT',
                pattern => '\\x2f\\*([^*]|\\*[^\\x2f])*\\*\\x2f',
                is_regex => 1,
                line_number => 196,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        error_definitions => [],
        reserved_keywords => [],
        groups => {},
        start_mode => '',
        transitions => [],
    }, 'CodingAdventures::GrammarTools::TokenGrammar';
}

1;
