# AUTO-GENERATED FILE - DO NOT EDIT
from grammar_tools.token_grammar import TokenGrammar, TokenDefinition, PatternGroup

VerilogTokens = TokenGrammar(
    version=0,
    case_insensitive=False,
    case_sensitive=True,
    keywords=["always", "and", "assign", "begin", "buf", "case", "casex", "casez", "default", "defparam", "else", "end", "endcase", "endfunction", "endgenerate", "endmodule", "endtask", "for", "function", "generate", "genvar", "if", "initial", "inout", "input", "integer", "localparam", "module", "nand", "negedge", "nor", "not", "or", "output", "parameter", "posedge", "real", "reg", "signed", "supply0", "supply1", "task", "tri", "unsigned", "wire", "xnor", "xor"],
    definitions=[
        TokenDefinition(name="STRING", pattern="\"([^\"\\\\]|\\\\.)*\"", is_regex=True, line_number=46),
        TokenDefinition(name="SIZED_NUMBER", pattern="[0-9]*'[sS]?[bBoOdDhH][0-9a-fA-F_xXzZ]+", is_regex=True, line_number=73),
        TokenDefinition(name="REAL_NUMBER", pattern="[0-9]+\\.[0-9]+([eE][+-]?[0-9]+)?", is_regex=True, line_number=77),
        TokenDefinition(name="NUMBER", pattern="[0-9][0-9_]*", is_regex=True, line_number=81),
        TokenDefinition(name="SYSTEM_ID", pattern="\\$[a-zA-Z_][a-zA-Z0-9_$]*", is_regex=True, line_number=109),
        TokenDefinition(name="DIRECTIVE", pattern="`[a-zA-Z_][a-zA-Z0-9_]*", is_regex=True, line_number=110),
        TokenDefinition(name="ESCAPED_IDENT", pattern="\\\\[^ \\t\\r\\n]+", is_regex=True, line_number=111),
        TokenDefinition(name="NAME", pattern="[a-zA-Z_][a-zA-Z0-9_$]*", is_regex=True, line_number=114),
        TokenDefinition(name="ARITH_LEFT_SHIFT", pattern="<<<", is_regex=False, line_number=126),
        TokenDefinition(name="ARITH_RIGHT_SHIFT", pattern=">>>", is_regex=False, line_number=127),
        TokenDefinition(name="CASE_EQ", pattern="===", is_regex=False, line_number=136),
        TokenDefinition(name="CASE_NEQ", pattern="!==", is_regex=False, line_number=137),
        TokenDefinition(name="LOGIC_AND", pattern="&&", is_regex=False, line_number=145),
        TokenDefinition(name="LOGIC_OR", pattern="||", is_regex=False, line_number=146),
        TokenDefinition(name="LEFT_SHIFT", pattern="<<", is_regex=False, line_number=147),
        TokenDefinition(name="RIGHT_SHIFT", pattern=">>", is_regex=False, line_number=148),
        TokenDefinition(name="EQUALS_EQUALS", pattern="==", is_regex=False, line_number=149),
        TokenDefinition(name="NOT_EQUALS", pattern="!=", is_regex=False, line_number=150),
        TokenDefinition(name="LESS_EQUALS", pattern="<=", is_regex=False, line_number=151),
        TokenDefinition(name="GREATER_EQUALS", pattern=">=", is_regex=False, line_number=152),
        TokenDefinition(name="POWER", pattern="**", is_regex=False, line_number=153),
        TokenDefinition(name="TRIGGER", pattern="->", is_regex=False, line_number=154),
        TokenDefinition(name="PLUS", pattern="+", is_regex=False, line_number=168),
        TokenDefinition(name="MINUS", pattern="-", is_regex=False, line_number=169),
        TokenDefinition(name="STAR", pattern="*", is_regex=False, line_number=170),
        TokenDefinition(name="SLASH", pattern="/", is_regex=False, line_number=171),
        TokenDefinition(name="PERCENT", pattern="%", is_regex=False, line_number=172),
        TokenDefinition(name="AMP", pattern="&", is_regex=False, line_number=173),
        TokenDefinition(name="PIPE", pattern="|", is_regex=False, line_number=174),
        TokenDefinition(name="CARET", pattern="^", is_regex=False, line_number=175),
        TokenDefinition(name="TILDE", pattern="~", is_regex=False, line_number=176),
        TokenDefinition(name="BANG", pattern="!", is_regex=False, line_number=177),
        TokenDefinition(name="LESS_THAN", pattern="<", is_regex=False, line_number=178),
        TokenDefinition(name="GREATER_THAN", pattern=">", is_regex=False, line_number=179),
        TokenDefinition(name="EQUALS", pattern="=", is_regex=False, line_number=180),
        TokenDefinition(name="QUESTION", pattern="?", is_regex=False, line_number=181),
        TokenDefinition(name="COLON", pattern=":", is_regex=False, line_number=182),
        TokenDefinition(name="LPAREN", pattern="(", is_regex=False, line_number=194),
        TokenDefinition(name="RPAREN", pattern=")", is_regex=False, line_number=195),
        TokenDefinition(name="LBRACKET", pattern="[", is_regex=False, line_number=196),
        TokenDefinition(name="RBRACKET", pattern="]", is_regex=False, line_number=197),
        TokenDefinition(name="LBRACE", pattern="{", is_regex=False, line_number=198),
        TokenDefinition(name="RBRACE", pattern="}", is_regex=False, line_number=199),
        TokenDefinition(name="SEMICOLON", pattern=";", is_regex=False, line_number=200),
        TokenDefinition(name="COMMA", pattern=",", is_regex=False, line_number=201),
        TokenDefinition(name="DOT", pattern=".", is_regex=False, line_number=202),
        TokenDefinition(name="HASH", pattern="#", is_regex=False, line_number=203),
        TokenDefinition(name="AT", pattern="@", is_regex=False, line_number=204),
    ],
    skip_definitions=[
        TokenDefinition(name="LINE_COMMENT", pattern="\\/\\/[^\\n]*", is_regex=True, line_number=31),
        TokenDefinition(name="BLOCK_COMMENT", pattern="\\/\\*([^*]|\\*[^/])*\\*\\/", is_regex=True, line_number=32),
        TokenDefinition(name="WHITESPACE", pattern="[ \\t\\r\\n]+", is_regex=True, line_number=33),
    ],
)
