// Code generated by grammar-tools. DO NOT EDIT.
// Source: excel.grammar
// Regenerate with: grammar-tools compile-grammar excel.grammar
//
// This file embeds a ParserGrammar as native Go data structures.
// Downstream packages use ParserGrammarData directly instead of reading
// and parsing the .grammar file at runtime.

package excelparser

import gt "github.com/adhithyan15/coding-adventures/code/packages/go/grammar-tools"

// ParserGrammarData is the embedded parser grammar.
var ParserGrammarData = &gt.ParserGrammar{
	Version: 1,
	Rules:   []gt.GrammarRule{
		{Name: `formula`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.RuleReference{Name: `ws`, IsToken: false},
					gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
							gt.RuleReference{Name: `EQUALS`, IsToken: true},
							gt.RuleReference{Name: `ws`, IsToken: false},
						}}},
					gt.RuleReference{Name: `expression`, IsToken: false},
					gt.RuleReference{Name: `ws`, IsToken: false},
				}}, LineNumber: 15},
		{Name: `ws`, Body: gt.Repetition{Element: gt.RuleReference{Name: `SPACE`, IsToken: true}}, LineNumber: 17},
		{Name: `req_space`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.RuleReference{Name: `SPACE`, IsToken: true},
					gt.Repetition{Element: gt.RuleReference{Name: `SPACE`, IsToken: true}},
				}}, LineNumber: 18},
		{Name: `expression`, Body: gt.RuleReference{Name: `comparison_expr`, IsToken: false}, LineNumber: 20},
		{Name: `comparison_expr`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.RuleReference{Name: `concat_expr`, IsToken: false},
					gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `comparison_op`, IsToken: false},
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `concat_expr`, IsToken: false},
						}}},
				}}, LineNumber: 22},
		{Name: `comparison_op`, Body: gt.Alternation{Choices: []gt.GrammarElement{
					gt.RuleReference{Name: `EQUALS`, IsToken: true},
					gt.RuleReference{Name: `NOT_EQUALS`, IsToken: true},
					gt.RuleReference{Name: `LESS_THAN`, IsToken: true},
					gt.RuleReference{Name: `LESS_EQUALS`, IsToken: true},
					gt.RuleReference{Name: `GREATER_THAN`, IsToken: true},
					gt.RuleReference{Name: `GREATER_EQUALS`, IsToken: true},
				}}, LineNumber: 23},
		{Name: `concat_expr`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.RuleReference{Name: `additive_expr`, IsToken: false},
					gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `AMP`, IsToken: true},
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `additive_expr`, IsToken: false},
						}}},
				}}, LineNumber: 26},
		{Name: `additive_expr`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.RuleReference{Name: `multiplicative_expr`, IsToken: false},
					gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.Group{Element: gt.Alternation{Choices: []gt.GrammarElement{
									gt.RuleReference{Name: `PLUS`, IsToken: true},
									gt.RuleReference{Name: `MINUS`, IsToken: true},
								}}},
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `multiplicative_expr`, IsToken: false},
						}}},
				}}, LineNumber: 27},
		{Name: `multiplicative_expr`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.RuleReference{Name: `power_expr`, IsToken: false},
					gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.Group{Element: gt.Alternation{Choices: []gt.GrammarElement{
									gt.RuleReference{Name: `STAR`, IsToken: true},
									gt.RuleReference{Name: `SLASH`, IsToken: true},
								}}},
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `power_expr`, IsToken: false},
						}}},
				}}, LineNumber: 28},
		{Name: `power_expr`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.RuleReference{Name: `unary_expr`, IsToken: false},
					gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `CARET`, IsToken: true},
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `unary_expr`, IsToken: false},
						}}},
				}}, LineNumber: 29},
		{Name: `unary_expr`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
							gt.RuleReference{Name: `prefix_op`, IsToken: false},
							gt.RuleReference{Name: `ws`, IsToken: false},
						}}},
					gt.RuleReference{Name: `postfix_expr`, IsToken: false},
				}}, LineNumber: 30},
		{Name: `prefix_op`, Body: gt.Alternation{Choices: []gt.GrammarElement{
					gt.RuleReference{Name: `PLUS`, IsToken: true},
					gt.RuleReference{Name: `MINUS`, IsToken: true},
				}}, LineNumber: 31},
		{Name: `postfix_expr`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.RuleReference{Name: `primary`, IsToken: false},
					gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `PERCENT`, IsToken: true},
						}}},
				}}, LineNumber: 32},
		{Name: `primary`, Body: gt.Alternation{Choices: []gt.GrammarElement{
					gt.RuleReference{Name: `parenthesized_expression`, IsToken: false},
					gt.RuleReference{Name: `constant`, IsToken: false},
					gt.RuleReference{Name: `function_call`, IsToken: false},
					gt.RuleReference{Name: `structure_reference`, IsToken: false},
					gt.RuleReference{Name: `reference_expression`, IsToken: false},
					gt.RuleReference{Name: `bang_reference`, IsToken: false},
					gt.RuleReference{Name: `bang_name`, IsToken: false},
					gt.RuleReference{Name: `name_reference`, IsToken: false},
				}}, LineNumber: 34},
		{Name: `parenthesized_expression`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.RuleReference{Name: `LPAREN`, IsToken: true},
					gt.RuleReference{Name: `ws`, IsToken: false},
					gt.RuleReference{Name: `expression`, IsToken: false},
					gt.RuleReference{Name: `ws`, IsToken: false},
					gt.RuleReference{Name: `RPAREN`, IsToken: true},
				}}, LineNumber: 43},
		{Name: `constant`, Body: gt.Alternation{Choices: []gt.GrammarElement{
					gt.RuleReference{Name: `NUMBER`, IsToken: true},
					gt.RuleReference{Name: `STRING`, IsToken: true},
					gt.RuleReference{Name: `KEYWORD`, IsToken: true},
					gt.RuleReference{Name: `ERROR_CONSTANT`, IsToken: true},
					gt.RuleReference{Name: `array_constant`, IsToken: false},
				}}, LineNumber: 45},
		{Name: `array_constant`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.RuleReference{Name: `LBRACE`, IsToken: true},
					gt.RuleReference{Name: `ws`, IsToken: false},
					gt.RuleReference{Name: `array_row`, IsToken: false},
					gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `SEMICOLON`, IsToken: true},
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `array_row`, IsToken: false},
						}}},
					gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `SEMICOLON`, IsToken: true},
						}}},
					gt.RuleReference{Name: `ws`, IsToken: false},
					gt.RuleReference{Name: `RBRACE`, IsToken: true},
				}}, LineNumber: 47},
		{Name: `array_row`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.RuleReference{Name: `array_item`, IsToken: false},
					gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `COMMA`, IsToken: true},
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `array_item`, IsToken: false},
						}}},
					gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `COMMA`, IsToken: true},
						}}},
				}}, LineNumber: 48},
		{Name: `array_item`, Body: gt.Alternation{Choices: []gt.GrammarElement{
					gt.RuleReference{Name: `NUMBER`, IsToken: true},
					gt.RuleReference{Name: `STRING`, IsToken: true},
					gt.RuleReference{Name: `KEYWORD`, IsToken: true},
					gt.RuleReference{Name: `ERROR_CONSTANT`, IsToken: true},
				}}, LineNumber: 49},
		{Name: `function_call`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.RuleReference{Name: `function_name`, IsToken: false},
					gt.RuleReference{Name: `LPAREN`, IsToken: true},
					gt.RuleReference{Name: `ws`, IsToken: false},
					gt.Optional{Element: gt.RuleReference{Name: `function_argument_list`, IsToken: false}},
					gt.RuleReference{Name: `ws`, IsToken: false},
					gt.RuleReference{Name: `RPAREN`, IsToken: true},
				}}, LineNumber: 51},
		{Name: `function_name`, Body: gt.Alternation{Choices: []gt.GrammarElement{
					gt.RuleReference{Name: `FUNCTION_NAME`, IsToken: true},
					gt.RuleReference{Name: `NAME`, IsToken: true},
				}}, LineNumber: 52},
		{Name: `function_argument_list`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.RuleReference{Name: `function_argument`, IsToken: false},
					gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `COMMA`, IsToken: true},
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `function_argument`, IsToken: false},
						}}},
					gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `COMMA`, IsToken: true},
						}}},
				}}, LineNumber: 53},
		{Name: `function_argument`, Body: gt.Optional{Element: gt.RuleReference{Name: `expression`, IsToken: false}}, LineNumber: 54},
		{Name: `reference_expression`, Body: gt.RuleReference{Name: `union_reference`, IsToken: false}, LineNumber: 56},
		{Name: `union_reference`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.RuleReference{Name: `intersection_reference`, IsToken: false},
					gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `COMMA`, IsToken: true},
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `intersection_reference`, IsToken: false},
						}}},
				}}, LineNumber: 57},
		{Name: `intersection_reference`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.RuleReference{Name: `range_reference`, IsToken: false},
					gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
							gt.RuleReference{Name: `req_space`, IsToken: false},
							gt.RuleReference{Name: `range_reference`, IsToken: false},
						}}},
				}}, LineNumber: 58},
		{Name: `range_reference`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.RuleReference{Name: `reference_primary`, IsToken: false},
					gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `COLON`, IsToken: true},
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `reference_primary`, IsToken: false},
						}}},
				}}, LineNumber: 59},
		{Name: `reference_primary`, Body: gt.Alternation{Choices: []gt.GrammarElement{
					gt.RuleReference{Name: `parenthesized_reference`, IsToken: false},
					gt.RuleReference{Name: `prefixed_reference`, IsToken: false},
					gt.RuleReference{Name: `external_reference`, IsToken: false},
					gt.RuleReference{Name: `structure_reference`, IsToken: false},
					gt.RuleReference{Name: `a1_reference`, IsToken: false},
					gt.RuleReference{Name: `bang_reference`, IsToken: false},
					gt.RuleReference{Name: `bang_name`, IsToken: false},
					gt.RuleReference{Name: `name_reference`, IsToken: false},
				}}, LineNumber: 61},
		{Name: `parenthesized_reference`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.RuleReference{Name: `LPAREN`, IsToken: true},
					gt.RuleReference{Name: `ws`, IsToken: false},
					gt.RuleReference{Name: `reference_expression`, IsToken: false},
					gt.RuleReference{Name: `ws`, IsToken: false},
					gt.RuleReference{Name: `RPAREN`, IsToken: true},
				}}, LineNumber: 70},
		{Name: `prefixed_reference`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.RuleReference{Name: `REF_PREFIX`, IsToken: true},
					gt.Group{Element: gt.Alternation{Choices: []gt.GrammarElement{
							gt.RuleReference{Name: `a1_reference`, IsToken: false},
							gt.RuleReference{Name: `name_reference`, IsToken: false},
							gt.RuleReference{Name: `structure_reference`, IsToken: false},
						}}},
				}}, LineNumber: 71},
		{Name: `external_reference`, Body: gt.RuleReference{Name: `REF_PREFIX`, IsToken: true}, LineNumber: 72},
		{Name: `bang_reference`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.RuleReference{Name: `BANG`, IsToken: true},
					gt.Group{Element: gt.Alternation{Choices: []gt.GrammarElement{
							gt.RuleReference{Name: `CELL`, IsToken: true},
							gt.RuleReference{Name: `COLUMN_REF`, IsToken: true},
							gt.RuleReference{Name: `ROW_REF`, IsToken: true},
							gt.RuleReference{Name: `NUMBER`, IsToken: true},
						}}},
				}}, LineNumber: 73},
		{Name: `bang_name`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.RuleReference{Name: `BANG`, IsToken: true},
					gt.RuleReference{Name: `name_reference`, IsToken: false},
				}}, LineNumber: 74},
		{Name: `name_reference`, Body: gt.RuleReference{Name: `NAME`, IsToken: true}, LineNumber: 75},
		{Name: `column_reference`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.Optional{Element: gt.RuleReference{Name: `DOLLAR`, IsToken: true}},
					gt.Group{Element: gt.Alternation{Choices: []gt.GrammarElement{
							gt.RuleReference{Name: `COLUMN_REF`, IsToken: true},
							gt.RuleReference{Name: `NAME`, IsToken: true},
						}}},
				}}, LineNumber: 77},
		{Name: `row_reference`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.Optional{Element: gt.RuleReference{Name: `DOLLAR`, IsToken: true}},
					gt.Group{Element: gt.Alternation{Choices: []gt.GrammarElement{
							gt.RuleReference{Name: `ROW_REF`, IsToken: true},
							gt.RuleReference{Name: `NUMBER`, IsToken: true},
						}}},
				}}, LineNumber: 78},
		{Name: `a1_reference`, Body: gt.Alternation{Choices: []gt.GrammarElement{
					gt.RuleReference{Name: `CELL`, IsToken: true},
					gt.RuleReference{Name: `column_reference`, IsToken: false},
					gt.RuleReference{Name: `row_reference`, IsToken: false},
					gt.RuleReference{Name: `COLUMN_REF`, IsToken: true},
					gt.RuleReference{Name: `ROW_REF`, IsToken: true},
					gt.RuleReference{Name: `NAME`, IsToken: true},
					gt.RuleReference{Name: `NUMBER`, IsToken: true},
				}}, LineNumber: 80},
		{Name: `structure_reference`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.Optional{Element: gt.RuleReference{Name: `table_name`, IsToken: false}},
					gt.RuleReference{Name: `intra_table_reference`, IsToken: false},
				}}, LineNumber: 82},
		{Name: `table_name`, Body: gt.Alternation{Choices: []gt.GrammarElement{
					gt.RuleReference{Name: `TABLE_NAME`, IsToken: true},
					gt.RuleReference{Name: `NAME`, IsToken: true},
				}}, LineNumber: 83},
		{Name: `intra_table_reference`, Body: gt.Alternation{Choices: []gt.GrammarElement{
					gt.RuleReference{Name: `STRUCTURED_KEYWORD`, IsToken: true},
					gt.RuleReference{Name: `structured_column_range`, IsToken: false},
					gt.Sequence{Elements: []gt.GrammarElement{
						gt.RuleReference{Name: `LBRACKET`, IsToken: true},
						gt.RuleReference{Name: `ws`, IsToken: false},
						gt.Optional{Element: gt.RuleReference{Name: `inner_structure_reference`, IsToken: false}},
						gt.RuleReference{Name: `ws`, IsToken: false},
						gt.RuleReference{Name: `RBRACKET`, IsToken: true},
					}},
				}}, LineNumber: 84},
		{Name: `inner_structure_reference`, Body: gt.Alternation{Choices: []gt.GrammarElement{
					gt.Sequence{Elements: []gt.GrammarElement{
						gt.RuleReference{Name: `structured_keyword_list`, IsToken: false},
						gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
								gt.RuleReference{Name: `ws`, IsToken: false},
								gt.RuleReference{Name: `COMMA`, IsToken: true},
								gt.RuleReference{Name: `ws`, IsToken: false},
								gt.RuleReference{Name: `structured_column_range`, IsToken: false},
							}}},
					}},
					gt.RuleReference{Name: `structured_column_range`, IsToken: false},
				}}, LineNumber: 87},
		{Name: `structured_keyword_list`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.RuleReference{Name: `STRUCTURED_KEYWORD`, IsToken: true},
					gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `COMMA`, IsToken: true},
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `STRUCTURED_KEYWORD`, IsToken: true},
						}}},
				}}, LineNumber: 89},
		{Name: `structured_column_range`, Body: gt.Sequence{Elements: []gt.GrammarElement{
					gt.RuleReference{Name: `structured_column`, IsToken: false},
					gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `COLON`, IsToken: true},
							gt.RuleReference{Name: `ws`, IsToken: false},
							gt.RuleReference{Name: `structured_column`, IsToken: false},
						}}},
				}}, LineNumber: 90},
		{Name: `structured_column`, Body: gt.Alternation{Choices: []gt.GrammarElement{
					gt.RuleReference{Name: `STRUCTURED_COLUMN`, IsToken: true},
					gt.Sequence{Elements: []gt.GrammarElement{
						gt.RuleReference{Name: `AT`, IsToken: true},
						gt.RuleReference{Name: `STRUCTURED_COLUMN`, IsToken: true},
					}},
				}}, LineNumber: 91},
	},
}
