param(
    [string]$OutputPath
)

$ErrorActionPreference = "Stop"

$packageRoot = Split-Path -Parent $PSScriptRoot
$repositoryRoot = (Resolve-Path (Join-Path $packageRoot "../../../..")).Path
$fixtureRoot = Join-Path $repositoryRoot "code/specs/fixtures/build-tool-v1"

if (-not $OutputPath) {
    $OutputPath = Join-Path $packageRoot "SourceInputRegistries.Generated.cs"
}

$languagePath = Join-Path $fixtureRoot "language-source-input-registry.json"
$boundaryPath = Join-Path $fixtureRoot "repository-source-input-boundary.json"
$languageJson = (Get-Content -Raw -LiteralPath $languagePath).TrimEnd("`r", "`n")
$boundaryJson = (Get-Content -Raw -LiteralPath $boundaryPath).TrimEnd("`r", "`n")

# Parse both authorities before emitting source. Runtime never reads these files;
# this generator is the checked bridge from neutral JSON to immutable source.
$null = $languageJson | ConvertFrom-Json
$null = $boundaryJson | ConvertFrom-Json

if ($languageJson.Contains('"""') -or $boundaryJson.Contains('"""')) {
    throw "A registry contains the C# raw-string delimiter. Increase the generated delimiter length."
}

$content = @"
// Generated by tools/generate-source-input-registries.ps1.
// Do not edit this projection by hand; edit the checked neutral registries and
// regenerate it so the production selector and conformance authorities cannot drift.

namespace CodingAdventures.BuildTool.CSharp;

internal static class SourceInputRegistryProjection
{
    internal const string LanguageJson = """
$languageJson
""";

    internal const string RepositoryBoundaryJson = """
$boundaryJson
""";
}
"@

$normalized = $content.Replace("`r`n", "`n")
[System.IO.File]::WriteAllText(
    [System.IO.Path]::GetFullPath($OutputPath),
    $normalized,
    [System.Text.UTF8Encoding]::new($false))
