using System.Collections.ObjectModel;

namespace CodingAdventures.WasmOpcodes;

public static class WasmOpcodesVersion
{
    public const string VERSION = "0.1.0";
}

public sealed record OpcodeInfo(string Name, byte Opcode, string Category, IReadOnlyList<string> Immediates, int StackPop, int StackPush);

public static class WasmOpcodes
{
    private static readonly OpcodeInfo[] All =
    [
        new OpcodeInfo("unreachable", 0x00, "control", Array.Empty<string>(), 0, 0),
        new OpcodeInfo("nop", 0x01, "control", Array.Empty<string>(), 0, 0),
        new OpcodeInfo("block", 0x02, "control", new[] { "blocktype" }, 0, 0),
        new OpcodeInfo("loop", 0x03, "control", new[] { "blocktype" }, 0, 0),
        new OpcodeInfo("if", 0x04, "control", new[] { "blocktype" }, 1, 0),
        new OpcodeInfo("else", 0x05, "control", Array.Empty<string>(), 0, 0),
        new OpcodeInfo("end", 0x0B, "control", Array.Empty<string>(), 0, 0),
        new OpcodeInfo("br", 0x0C, "control", new[] { "labelidx" }, 0, 0),
        new OpcodeInfo("br_if", 0x0D, "control", new[] { "labelidx" }, 1, 0),
        new OpcodeInfo("br_table", 0x0E, "control", new[] { "vec_labelidx" }, 1, 0),
        new OpcodeInfo("return", 0x0F, "control", Array.Empty<string>(), 0, 0),
        new OpcodeInfo("call", 0x10, "control", new[] { "funcidx" }, 0, 0),
        new OpcodeInfo("call_indirect", 0x11, "control", new[] { "typeidx", "tableidx" }, 1, 0),
        new OpcodeInfo("drop", 0x1A, "parametric", Array.Empty<string>(), 1, 0),
        new OpcodeInfo("select", 0x1B, "parametric", Array.Empty<string>(), 3, 1),
        new OpcodeInfo("local.get", 0x20, "variable", new[] { "localidx" }, 0, 1),
        new OpcodeInfo("local.set", 0x21, "variable", new[] { "localidx" }, 1, 0),
        new OpcodeInfo("local.tee", 0x22, "variable", new[] { "localidx" }, 1, 1),
        new OpcodeInfo("global.get", 0x23, "variable", new[] { "globalidx" }, 0, 1),
        new OpcodeInfo("global.set", 0x24, "variable", new[] { "globalidx" }, 1, 0),
        new OpcodeInfo("i32.load", 0x28, "memory", new[] { "memarg" }, 1, 1),
        new OpcodeInfo("i64.load", 0x29, "memory", new[] { "memarg" }, 1, 1),
        new OpcodeInfo("f32.load", 0x2A, "memory", new[] { "memarg" }, 1, 1),
        new OpcodeInfo("f64.load", 0x2B, "memory", new[] { "memarg" }, 1, 1),
        new OpcodeInfo("i32.load8_s", 0x2C, "memory", new[] { "memarg" }, 1, 1),
        new OpcodeInfo("i32.load8_u", 0x2D, "memory", new[] { "memarg" }, 1, 1),
        new OpcodeInfo("i32.load16_s", 0x2E, "memory", new[] { "memarg" }, 1, 1),
        new OpcodeInfo("i32.load16_u", 0x2F, "memory", new[] { "memarg" }, 1, 1),
        new OpcodeInfo("i64.load8_s", 0x30, "memory", new[] { "memarg" }, 1, 1),
        new OpcodeInfo("i64.load8_u", 0x31, "memory", new[] { "memarg" }, 1, 1),
        new OpcodeInfo("i64.load16_s", 0x32, "memory", new[] { "memarg" }, 1, 1),
        new OpcodeInfo("i64.load16_u", 0x33, "memory", new[] { "memarg" }, 1, 1),
        new OpcodeInfo("i64.load32_s", 0x34, "memory", new[] { "memarg" }, 1, 1),
        new OpcodeInfo("i64.load32_u", 0x35, "memory", new[] { "memarg" }, 1, 1),
        new OpcodeInfo("i32.store", 0x36, "memory", new[] { "memarg" }, 2, 0),
        new OpcodeInfo("i64.store", 0x37, "memory", new[] { "memarg" }, 2, 0),
        new OpcodeInfo("f32.store", 0x38, "memory", new[] { "memarg" }, 2, 0),
        new OpcodeInfo("f64.store", 0x39, "memory", new[] { "memarg" }, 2, 0),
        new OpcodeInfo("i32.store8", 0x3A, "memory", new[] { "memarg" }, 2, 0),
        new OpcodeInfo("i32.store16", 0x3B, "memory", new[] { "memarg" }, 2, 0),
        new OpcodeInfo("i64.store8", 0x3C, "memory", new[] { "memarg" }, 2, 0),
        new OpcodeInfo("i64.store16", 0x3D, "memory", new[] { "memarg" }, 2, 0),
        new OpcodeInfo("i64.store32", 0x3E, "memory", new[] { "memarg" }, 2, 0),
        new OpcodeInfo("memory.size", 0x3F, "memory", new[] { "memidx" }, 0, 1),
        new OpcodeInfo("memory.grow", 0x40, "memory", new[] { "memidx" }, 1, 1),
        new OpcodeInfo("i32.const", 0x41, "numeric_i32", new[] { "i32" }, 0, 1),
        new OpcodeInfo("i32.eqz", 0x45, "numeric_i32", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("i32.eq", 0x46, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.ne", 0x47, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.lt_s", 0x48, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.lt_u", 0x49, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.gt_s", 0x4A, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.gt_u", 0x4B, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.le_s", 0x4C, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.le_u", 0x4D, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.ge_s", 0x4E, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.ge_u", 0x4F, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.clz", 0x67, "numeric_i32", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("i32.ctz", 0x68, "numeric_i32", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("i32.popcnt", 0x69, "numeric_i32", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("i32.add", 0x6A, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.sub", 0x6B, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.mul", 0x6C, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.div_s", 0x6D, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.div_u", 0x6E, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.rem_s", 0x6F, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.rem_u", 0x70, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.and", 0x71, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.or", 0x72, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.xor", 0x73, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.shl", 0x74, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.shr_s", 0x75, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.shr_u", 0x76, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.rotl", 0x77, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.rotr", 0x78, "numeric_i32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.const", 0x42, "numeric_i64", new[] { "i64" }, 0, 1),
        new OpcodeInfo("i64.eqz", 0x50, "numeric_i64", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("i64.eq", 0x51, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.ne", 0x52, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.lt_s", 0x53, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.lt_u", 0x54, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.gt_s", 0x55, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.gt_u", 0x56, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.le_s", 0x57, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.le_u", 0x58, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.ge_s", 0x59, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.ge_u", 0x5A, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.clz", 0x79, "numeric_i64", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("i64.ctz", 0x7A, "numeric_i64", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("i64.popcnt", 0x7B, "numeric_i64", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("i64.add", 0x7C, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.sub", 0x7D, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.mul", 0x7E, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.div_s", 0x7F, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.div_u", 0x80, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.rem_s", 0x81, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.rem_u", 0x82, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.and", 0x83, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.or", 0x84, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.xor", 0x85, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.shl", 0x86, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.shr_s", 0x87, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.shr_u", 0x88, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.rotl", 0x89, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i64.rotr", 0x8A, "numeric_i64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f32.const", 0x43, "numeric_f32", new[] { "f32" }, 0, 1),
        new OpcodeInfo("f32.eq", 0x5B, "numeric_f32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f32.ne", 0x5C, "numeric_f32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f32.lt", 0x5D, "numeric_f32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f32.gt", 0x5E, "numeric_f32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f32.le", 0x5F, "numeric_f32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f32.ge", 0x60, "numeric_f32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f32.abs", 0x8B, "numeric_f32", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f32.neg", 0x8C, "numeric_f32", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f32.ceil", 0x8D, "numeric_f32", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f32.floor", 0x8E, "numeric_f32", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f32.trunc", 0x8F, "numeric_f32", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f32.nearest", 0x90, "numeric_f32", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f32.sqrt", 0x91, "numeric_f32", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f32.add", 0x92, "numeric_f32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f32.sub", 0x93, "numeric_f32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f32.mul", 0x94, "numeric_f32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f32.div", 0x95, "numeric_f32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f32.min", 0x96, "numeric_f32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f32.max", 0x97, "numeric_f32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f32.copysign", 0x98, "numeric_f32", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f64.const", 0x44, "numeric_f64", new[] { "f64" }, 0, 1),
        new OpcodeInfo("f64.eq", 0x61, "numeric_f64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f64.ne", 0x62, "numeric_f64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f64.lt", 0x63, "numeric_f64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f64.gt", 0x64, "numeric_f64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f64.le", 0x65, "numeric_f64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f64.ge", 0x66, "numeric_f64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f64.abs", 0x99, "numeric_f64", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f64.neg", 0x9A, "numeric_f64", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f64.ceil", 0x9B, "numeric_f64", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f64.floor", 0x9C, "numeric_f64", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f64.trunc", 0x9D, "numeric_f64", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f64.nearest", 0x9E, "numeric_f64", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f64.sqrt", 0x9F, "numeric_f64", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f64.add", 0xA0, "numeric_f64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f64.sub", 0xA1, "numeric_f64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f64.mul", 0xA2, "numeric_f64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f64.div", 0xA3, "numeric_f64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f64.min", 0xA4, "numeric_f64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f64.max", 0xA5, "numeric_f64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("f64.copysign", 0xA6, "numeric_f64", Array.Empty<string>(), 2, 1),
        new OpcodeInfo("i32.wrap_i64", 0xA7, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("i32.trunc_f32_s", 0xA8, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("i32.trunc_f32_u", 0xA9, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("i32.trunc_f64_s", 0xAA, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("i32.trunc_f64_u", 0xAB, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("i64.extend_i32_s", 0xAC, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("i64.extend_i32_u", 0xAD, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("i64.trunc_f32_s", 0xAE, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("i64.trunc_f32_u", 0xAF, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("i64.trunc_f64_s", 0xB0, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("i64.trunc_f64_u", 0xB1, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f32.convert_i32_s", 0xB2, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f32.convert_i32_u", 0xB3, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f32.convert_i64_s", 0xB4, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f32.convert_i64_u", 0xB5, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f32.demote_f64", 0xB6, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f64.convert_i32_s", 0xB7, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f64.convert_i32_u", 0xB8, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f64.convert_i64_s", 0xB9, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f64.convert_i64_u", 0xBA, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f64.promote_f32", 0xBB, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("i32.reinterpret_f32", 0xBC, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("i64.reinterpret_f64", 0xBD, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f32.reinterpret_i32", 0xBE, "conversion", Array.Empty<string>(), 1, 1),
        new OpcodeInfo("f64.reinterpret_i64", 0xBF, "conversion", Array.Empty<string>(), 1, 1),
    ];

    public static IReadOnlyDictionary<byte, OpcodeInfo> OPCODES { get; } =
        new ReadOnlyDictionary<byte, OpcodeInfo>(All.ToDictionary(info => info.Opcode));

    public static IReadOnlyDictionary<string, OpcodeInfo> OPCODES_BY_NAME { get; } =
        new ReadOnlyDictionary<string, OpcodeInfo>(All.ToDictionary(info => info.Name, StringComparer.Ordinal));

    public static OpcodeInfo? GetOpcode(byte opcode) => OPCODES.TryGetValue(opcode, out var info) ? info : null;

    public static OpcodeInfo? GetOpcode(int opcode) =>
        opcode >= byte.MinValue && opcode <= byte.MaxValue ? GetOpcode((byte)opcode) : null;

    public static OpcodeInfo? GetOpcodeByName(string name) =>
        OPCODES_BY_NAME.TryGetValue(name, out var info) ? info : null;
}
