// AUTO-GENERATED FILE — DO NOT EDIT
// Source: macronib.tokens
// Regenerate with: grammar-tools compile-tokens macronib.tokens
//
// This file embeds a TokenGrammar as native Rust data structures.
// Call `token_grammar()` instead of reading and parsing the .tokens file.

#[allow(unused_imports)]
use grammar_tools::token_grammar::{
    ModeTransition, PatternGroup, TokenDefinition, TokenGrammar, TransitionAction,
};
#[allow(unused_imports)]
use std::collections::HashMap;

pub fn token_grammar() -> TokenGrammar {
    TokenGrammar {
        definitions: vec![
            TokenDefinition {
                name: r#"DOT_INCLUDE"#.to_string(),
                pattern: r#".include"#.to_string(),
                is_regex: false,
                line_number: 5,
                alias: None,
            },
            TokenDefinition {
                name: r#"DOT_IFDEF"#.to_string(),
                pattern: r#".ifdef"#.to_string(),
                is_regex: false,
                line_number: 6,
                alias: None,
            },
            TokenDefinition {
                name: r#"DOT_ENDIF"#.to_string(),
                pattern: r#".endif"#.to_string(),
                is_regex: false,
                line_number: 7,
                alias: None,
            },
            TokenDefinition {
                name: r#"DOT_ELSE"#.to_string(),
                pattern: r#".else"#.to_string(),
                is_regex: false,
                line_number: 8,
                alias: None,
            },
            TokenDefinition {
                name: r#"DOT_SET"#.to_string(),
                pattern: r#".set"#.to_string(),
                is_regex: false,
                line_number: 9,
                alias: None,
            },
            TokenDefinition {
                name: r#"STR_LIT"#.to_string(),
                pattern: r#""[^"\n]*""#.to_string(),
                is_regex: true,
                line_number: 10,
                alias: None,
            },
            TokenDefinition {
                name: r#"WRAP_ADD"#.to_string(),
                pattern: r#"+%"#.to_string(),
                is_regex: false,
                line_number: 67,
                alias: None,
            },
            TokenDefinition {
                name: r#"SAT_ADD"#.to_string(),
                pattern: r#"+?"#.to_string(),
                is_regex: false,
                line_number: 74,
                alias: None,
            },
            TokenDefinition {
                name: r#"RANGE"#.to_string(),
                pattern: r#".."#.to_string(),
                is_regex: false,
                line_number: 84,
                alias: None,
            },
            TokenDefinition {
                name: r#"ARROW"#.to_string(),
                pattern: r#"->"#.to_string(),
                is_regex: false,
                line_number: 90,
                alias: None,
            },
            TokenDefinition {
                name: r#"EQ_EQ"#.to_string(),
                pattern: r#"=="#.to_string(),
                is_regex: false,
                line_number: 98,
                alias: None,
            },
            TokenDefinition {
                name: r#"NEQ"#.to_string(),
                pattern: r#"!="#.to_string(),
                is_regex: false,
                line_number: 104,
                alias: None,
            },
            TokenDefinition {
                name: r#"LEQ"#.to_string(),
                pattern: r#"<="#.to_string(),
                is_regex: false,
                line_number: 108,
                alias: None,
            },
            TokenDefinition {
                name: r#"GEQ"#.to_string(),
                pattern: r#">="#.to_string(),
                is_regex: false,
                line_number: 112,
                alias: None,
            },
            TokenDefinition {
                name: r#"LAND"#.to_string(),
                pattern: r#"&&"#.to_string(),
                is_regex: false,
                line_number: 119,
                alias: None,
            },
            TokenDefinition {
                name: r#"LOR"#.to_string(),
                pattern: r#"||"#.to_string(),
                is_regex: false,
                line_number: 126,
                alias: None,
            },
            TokenDefinition {
                name: r#"SHL"#.to_string(),
                pattern: r#"<<"#.to_string(),
                is_regex: false,
                line_number: 130,
                alias: None,
            },
            TokenDefinition {
                name: r#"SHR"#.to_string(),
                pattern: r#">>"#.to_string(),
                is_regex: false,
                line_number: 131,
                alias: None,
            },
            TokenDefinition {
                name: r#"PLUS"#.to_string(),
                pattern: r#"+"#.to_string(),
                is_regex: false,
                line_number: 139,
                alias: None,
            },
            TokenDefinition {
                name: r#"MINUS"#.to_string(),
                pattern: r#"-"#.to_string(),
                is_regex: false,
                line_number: 142,
                alias: None,
            },
            TokenDefinition {
                name: r#"STAR"#.to_string(),
                pattern: r#"*"#.to_string(),
                is_regex: false,
                line_number: 148,
                alias: None,
            },
            TokenDefinition {
                name: r#"SLASH"#.to_string(),
                pattern: r#"/"#.to_string(),
                is_regex: false,
                line_number: 152,
                alias: None,
            },
            TokenDefinition {
                name: r#"PERCENT"#.to_string(),
                pattern: r#"%"#.to_string(),
                is_regex: false,
                line_number: 157,
                alias: None,
            },
            TokenDefinition {
                name: r#"AMP"#.to_string(),
                pattern: r#"&"#.to_string(),
                is_regex: false,
                line_number: 165,
                alias: None,
            },
            TokenDefinition {
                name: r#"PIPE"#.to_string(),
                pattern: r#"|"#.to_string(),
                is_regex: false,
                line_number: 169,
                alias: None,
            },
            TokenDefinition {
                name: r#"CARET"#.to_string(),
                pattern: r#"^"#.to_string(),
                is_regex: false,
                line_number: 172,
                alias: None,
            },
            TokenDefinition {
                name: r#"TILDE"#.to_string(),
                pattern: r#"~"#.to_string(),
                is_regex: false,
                line_number: 176,
                alias: None,
            },
            TokenDefinition {
                name: r#"BANG"#.to_string(),
                pattern: r#"!"#.to_string(),
                is_regex: false,
                line_number: 185,
                alias: None,
            },
            TokenDefinition {
                name: r#"LT"#.to_string(),
                pattern: r#"<"#.to_string(),
                is_regex: false,
                line_number: 188,
                alias: None,
            },
            TokenDefinition {
                name: r#"GT"#.to_string(),
                pattern: r#">"#.to_string(),
                is_regex: false,
                line_number: 191,
                alias: None,
            },
            TokenDefinition {
                name: r#"EQ"#.to_string(),
                pattern: r#"="#.to_string(),
                is_regex: false,
                line_number: 201,
                alias: None,
            },
            TokenDefinition {
                name: r#"LBRACE"#.to_string(),
                pattern: r#"{"#.to_string(),
                is_regex: false,
                line_number: 208,
                alias: None,
            },
            TokenDefinition {
                name: r#"RBRACE"#.to_string(),
                pattern: r#"}"#.to_string(),
                is_regex: false,
                line_number: 209,
                alias: None,
            },
            TokenDefinition {
                name: r#"LPAREN"#.to_string(),
                pattern: r#"("#.to_string(),
                is_regex: false,
                line_number: 212,
                alias: None,
            },
            TokenDefinition {
                name: r#"RPAREN"#.to_string(),
                pattern: r#")"#.to_string(),
                is_regex: false,
                line_number: 213,
                alias: None,
            },
            TokenDefinition {
                name: r#"COLON"#.to_string(),
                pattern: r#":"#.to_string(),
                is_regex: false,
                line_number: 217,
                alias: None,
            },
            TokenDefinition {
                name: r#"SEMICOLON"#.to_string(),
                pattern: r#";"#.to_string(),
                is_regex: false,
                line_number: 222,
                alias: None,
            },
            TokenDefinition {
                name: r#"COMMA"#.to_string(),
                pattern: r#","#.to_string(),
                is_regex: false,
                line_number: 225,
                alias: None,
            },
            TokenDefinition {
                name: r#"HEX_LIT"#.to_string(),
                pattern: r#"0x[0-9A-Fa-f]+"#.to_string(),
                is_regex: true,
                line_number: 238,
                alias: None,
            },
            TokenDefinition {
                name: r#"INT_LIT"#.to_string(),
                pattern: r#"[0-9]+"#.to_string(),
                is_regex: true,
                line_number: 242,
                alias: None,
            },
            TokenDefinition {
                name: r#"NAME"#.to_string(),
                pattern: r#"[a-zA-Z_][a-zA-Z0-9_]*"#.to_string(),
                is_regex: true,
                line_number: 250,
                alias: None,
            },
        ],
        keywords: vec![
            r#"fn"#.to_string(),
            r#"let"#.to_string(),
            r#"static"#.to_string(),
            r#"const"#.to_string(),
            r#"return"#.to_string(),
            r#"for"#.to_string(),
            r#"while"#.to_string(),
            r#"in"#.to_string(),
            r#"if"#.to_string(),
            r#"else"#.to_string(),
            r#"true"#.to_string(),
            r#"false"#.to_string(),
        ],
        mode: None,
        skip_definitions: vec![
            TokenDefinition {
                name: r#"WHITESPACE"#.to_string(),
                pattern: r#"[ \t\r\n]+"#.to_string(),
                is_regex: true,
                line_number: 320,
                alias: None,
            },
            TokenDefinition {
                name: r#"LINE_COMMENT"#.to_string(),
                pattern: r#"\/\/[^\n]*"#.to_string(),
                is_regex: true,
                line_number: 328,
                alias: None,
            },
        ],
        reserved_keywords: vec![],
        escapes: None,
        error_definitions: vec![],
        groups: HashMap::new(),
        case_sensitive: true,
        version: 1,
        case_insensitive: false,
        context_keywords: vec![],
        soft_keywords: vec![],
        layout_keywords: vec![],
        start_mode: None,
        transitions: vec![],
    }
}
