// AUTO-GENERATED by Mosaic. Edits will be overwritten on next emit.
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;

namespace __MOSAIC_NAMESPACE__;

public sealed record MosaicRuntimeResult(string Status, object? HostIntent = null);

public static class MosaicRuntimeHost
{
    private const int ProtocolVersion = __MOSAIC_PROTOCOL_VERSION__;
    private static readonly Lazy<Runtime?> State = new(Load);

    public static bool IsAvailable => State.Value is not null;

    public static void LoadRequired() => _ = RequiredRuntime();

    public static string? ApplyProps(object component)
    {
        var runtime = State.Value;
        if (runtime is null) return null;
        runtime.ApplyProps(component);
        return "Status: Mosaic runtime props loaded";
    }

    public static string ApplyRequiredProps(object component, params string[] requiredProps)
    {
        RequiredRuntime().ApplyProps(component, requiredProps, strict: true);
        return "Status: Mosaic runtime props loaded";
    }

    public static Task<MosaicRuntimeResult?> HandleEvent(object component, object mosaicEvent)
    {
        var runtime = State.Value;
        if (runtime is null) return Task.FromResult<MosaicRuntimeResult?>(null);
        try
        {
            var eventType = mosaicEvent.GetType();
            var name = eventType.GetProperty("MosaicName")?.GetValue(mosaicEvent) as string
                ?? throw new InvalidOperationException("Mosaic event has no MosaicName");
            var payload = eventType.GetProperty("MosaicPayload")?.GetValue(mosaicEvent)
                ?? new Dictionary<string, object?>();
            runtime.Dispatch(name, payload);
            runtime.ApplyProps(component);
            return Task.FromResult<MosaicRuntimeResult?>(
                new($"Status: Mosaic runtime handled {name}"));
        }
        catch (Exception error)
        {
            return Task.FromResult<MosaicRuntimeResult?>(
                new($"Mosaic runtime failed: {error.GetType().Name}: {error.Message}"));
        }
    }

    public static Task<MosaicRuntimeResult> HandleRequiredEvent(
        object component,
        object mosaicEvent,
        params string[] requiredProps)
    {
        var runtime = RequiredRuntime();
        var eventType = mosaicEvent.GetType();
        var name = eventType.GetProperty("MosaicName")?.GetValue(mosaicEvent) as string
            ?? throw new InvalidOperationException("Mosaic event has no MosaicName");
        var payload = eventType.GetProperty("MosaicPayload")?.GetValue(mosaicEvent)
            ?? new Dictionary<string, object?>();
        runtime.Dispatch(name, payload);
        runtime.ApplyProps(component, requiredProps, strict: true);
        return Task.FromResult(
            new MosaicRuntimeResult($"Status: Mosaic runtime handled {name}"));
    }

    public static void Close() => State.Value?.Dispose();

    private static Runtime RequiredRuntime() => State.Value
        ?? throw new InvalidOperationException(
            "native-complete requires the Mosaic Rust application runtime; " +
            "set MOSAIC_APP_LIBRARY or package mosaic_app.dll beside the application");

    private static Runtime? Load()
    {
        try
        {
            var runtime = Runtime.Load();
            AppDomain.CurrentDomain.ProcessExit += (_, _) => runtime.Dispose();
            return runtime;
        }
        catch (Exception error)
        {
            Debug.WriteLine($"Mosaic Rust runtime unavailable: {error}");
            return null;
        }
    }

    [StructLayout(LayoutKind.Sequential)]
    private readonly struct MosaicBytes
    {
        public readonly IntPtr Ptr;
        public readonly UIntPtr Len;

        public MosaicBytes(IntPtr ptr, int len)
        {
            Ptr = ptr;
            Len = (UIntPtr)(uint)len;
        }
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct MosaicBuffer
    {
        public IntPtr Ptr;
        public UIntPtr Len;
        public UIntPtr Capacity;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate uint Create(MosaicBytes start, out IntPtr app, out MosaicBuffer update);
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate uint Dispatch(IntPtr app, MosaicBytes mosaicEvent, out MosaicBuffer update);
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate uint Snapshot(IntPtr app, out MosaicBuffer snapshot);
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate uint Restore(IntPtr app, MosaicBytes snapshot, out MosaicBuffer update);
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void BufferFree(MosaicBuffer buffer);
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Destroy(IntPtr app);
    private delegate uint InputOperation(MosaicBytes input, out MosaicBuffer output);
    private delegate uint OutputOperation(out MosaicBuffer output);

    private sealed class Runtime : IDisposable
    {
        private readonly object gate = new();
        private IntPtr library;
        private IntPtr app;
        private ulong sequence;
        private JsonElement latestUpdate;
        private readonly Create create;
        private readonly Dispatch dispatch;
        private readonly Snapshot snapshot;
        private readonly Restore restore;
        private readonly BufferFree bufferFree;
        private readonly Destroy destroy;

        private Runtime(IntPtr library)
        {
            this.library = library;
            create = Symbol<Create>(library, "mosaic_app_create");
            dispatch = Symbol<Dispatch>(library, "mosaic_app_dispatch");
            snapshot = Symbol<Snapshot>(library, "mosaic_app_snapshot");
            restore = Symbol<Restore>(library, "mosaic_app_restore");
            bufferFree = Symbol<BufferFree>(library, "mosaic_buffer_free");
            destroy = Symbol<Destroy>(library, "mosaic_app_destroy");

            var start = new Dictionary<string, object?>
            {
                ["protocolVersion"] = ProtocolVersion,
                ["locale"] = CultureInfo.CurrentCulture.Name,
                ["colorScheme"] = "system",
                ["textScale"] = 1.0,
                ["platform"] = "windows",
                ["restoredSnapshot"] = null,
            };
            try
            {
                latestUpdate = Invoke(start, delegate(MosaicBytes input, out MosaicBuffer output)
                {
                    return create(input, out app, out output);
                });
                if (app == IntPtr.Zero)
                    throw new InvalidOperationException("Mosaic runtime returned a null application handle");
            }
            catch
            {
                if (app != IntPtr.Zero) destroy(app);
                app = IntPtr.Zero;
                throw;
            }
        }

        public static Runtime Load()
        {
            var requested = Environment.GetEnvironmentVariable("MOSAIC_APP_LIBRARY");
            var candidates = string.IsNullOrWhiteSpace(requested)
                ? new[]
                {
                    Path.Combine(AppContext.BaseDirectory, "mosaic_app.dll"),
                    "mosaic_app",
                    "mosaic_app.dll",
                }
                : new[] { requested };
            foreach (var candidate in candidates)
                if (NativeLibrary.TryLoad(candidate, out var library))
                    try { return new Runtime(library); }
                    catch { NativeLibrary.Free(library); throw; }
            throw new DllNotFoundException(
                $"Unable to load Mosaic application library ({string.Join(", ", candidates)})");
        }

        public void Dispatch(string name, object payload)
        {
            lock (gate)
            {
                EnsureOpen();
                var nextSequence = checked(sequence + 1);
                var envelope = new Dictionary<string, object?>
                {
                    ["protocolVersion"] = ProtocolVersion,
                    ["sequence"] = nextSequence,
                    ["name"] = name,
                    ["payload"] = payload,
                };
                var update = Invoke(envelope, delegate(MosaicBytes input, out MosaicBuffer output)
                {
                    return dispatch(app, input, out output);
                });
                sequence = nextSequence;
                latestUpdate = update;
            }
        }

        public JsonElement? Snapshot()
        {
            lock (gate)
            {
                EnsureOpen();
                var value = Invoke(delegate(out MosaicBuffer output)
                {
                    return snapshot(app, out output);
                });
                return value.ValueKind == JsonValueKind.Null ? null : value;
            }
        }

        public void Restore(JsonElement value)
        {
            lock (gate)
            {
                EnsureOpen();
                latestUpdate = Invoke(value, delegate(MosaicBytes input, out MosaicBuffer output)
                {
                    return restore(app, input, out output);
                });
            }
        }

        public void ApplyProps(
            object component,
            IReadOnlyCollection<string>? requiredProps = null,
            bool strict = false)
        {
            lock (gate)
            {
                EnsureOpen();
                if (!latestUpdate.TryGetProperty("props", out var props)
                    || props.ValueKind != JsonValueKind.Object)
                {
                    if (strict)
                        throw new InvalidOperationException(
                            "Mosaic runtime response did not include a props object");
                    return;
                }
                var values = props.EnumerateObject().ToDictionary(
                    property => Normalize(property.Name),
                    property => property.Value,
                    StringComparer.OrdinalIgnoreCase);
                var componentProperties = component.GetType().GetProperties(
                    BindingFlags.Instance | BindingFlags.Public)
                    .Where(property => property.CanWrite)
                    .ToDictionary(
                        property => Normalize(property.Name),
                        property => property,
                        StringComparer.OrdinalIgnoreCase);
                foreach (var requiredProp in requiredProps ?? Array.Empty<string>())
                {
                    var normalized = Normalize(requiredProp);
                    if (!values.ContainsKey(normalized))
                        throw new InvalidOperationException(
                            $"Mosaic runtime props are missing required value '{requiredProp}'");
                    if (!componentProperties.ContainsKey(normalized))
                        throw new InvalidOperationException(
                            $"Mosaic component has no writable property for required value '{requiredProp}'");
                }
                foreach (var (normalized, property) in componentProperties)
                {
                    if (!values.TryGetValue(normalized, out var value))
                        continue;
                    var converted = ConvertValue(value, property.PropertyType);
                    if (!converted.converted)
                    {
                        if (strict)
                            throw new InvalidOperationException(
                                $"Mosaic runtime prop '{property.Name}' is not valid for {property.PropertyType.Name}");
                        continue;
                    }
                    property.SetValue(component, converted.value);
                }
            }
        }

        public void Dispose()
        {
            lock (gate)
            {
                if (app != IntPtr.Zero) destroy(app);
                app = IntPtr.Zero;
                if (library != IntPtr.Zero) NativeLibrary.Free(library);
                library = IntPtr.Zero;
            }
        }

        private JsonElement Invoke(object value, InputOperation operation)
        {
            var encoded = JsonSerializer.SerializeToUtf8Bytes(value);
            var pinned = GCHandle.Alloc(encoded, GCHandleType.Pinned);
            try
            {
                var input = new MosaicBytes(
                    encoded.Length == 0 ? IntPtr.Zero : pinned.AddrOfPinnedObject(),
                    encoded.Length);
                var status = operation(input, out var output);
                return Consume(status, output);
            }
            finally { pinned.Free(); }
        }

        private JsonElement Invoke(OutputOperation operation)
        {
            var status = operation(out var output);
            return Consume(status, output);
        }

        private JsonElement Consume(uint status, MosaicBuffer buffer)
        {
            try
            {
                var length = checked((int)buffer.Len.ToUInt64());
                var bytes = new byte[length];
                if (length > 0) Marshal.Copy(buffer.Ptr, bytes, 0, length);
                if (status != 0)
                    throw new MosaicRuntimeException(status, Encoding.UTF8.GetString(bytes));
                using var document = JsonDocument.Parse(bytes);
                return document.RootElement.Clone();
            }
            finally { bufferFree(buffer); }
        }

        private static T Symbol<T>(IntPtr library, string name) where T : Delegate =>
            Marshal.GetDelegateForFunctionPointer<T>(NativeLibrary.GetExport(library, name));

        private static string Normalize(string value) =>
            new(value.Where(char.IsLetterOrDigit).Select(char.ToLowerInvariant).ToArray());

        private static (bool converted, object? value) ConvertValue(JsonElement value, Type type)
        {
            if (value.ValueKind == JsonValueKind.Null)
                return (!type.IsValueType || Nullable.GetUnderlyingType(type) is not null, null);
            try
            {
                if (type == typeof(string)) return (true, value.ToString());
                if (type == typeof(double)) return (true, value.GetDouble());
                if (type == typeof(bool)) return (true, value.GetBoolean());
                if (type == typeof(Windows.UI.Color) && value.ValueKind == JsonValueKind.String)
                    return (true, ParseColor(value.GetString()!));
                var converted = JsonSerializer.Deserialize(value.GetRawText(), type);
                return (converted is not null, converted);
            }
            catch (Exception error)
            {
                Debug.WriteLine($"Mosaic prop conversion failed for {type}: {error.Message}");
                return (false, null);
            }
        }

        private static Windows.UI.Color ParseColor(string value)
        {
            var hex = value.TrimStart('#');
            if (hex.Length == 6) hex = "FF" + hex;
            if (hex.Length != 8) throw new FormatException($"Invalid Mosaic color: {value}");
            return Windows.UI.Color.FromArgb(
                byte.Parse(hex[..2], NumberStyles.HexNumber),
                byte.Parse(hex.Substring(2, 2), NumberStyles.HexNumber),
                byte.Parse(hex.Substring(4, 2), NumberStyles.HexNumber),
                byte.Parse(hex.Substring(6, 2), NumberStyles.HexNumber));
        }

        private void EnsureOpen()
        {
            if (library == IntPtr.Zero || app == IntPtr.Zero)
                throw new ObjectDisposedException(nameof(MosaicRuntimeHost));
        }
    }
}

public sealed class MosaicRuntimeException(uint status, string message)
    : Exception(message)
{
    public uint Status { get; } = status;
}
