defmodule CodingAdventures.NibLexer.Grammar do
  # AUTO-GENERATED FILE — DO NOT EDIT
  # Source: nib.tokens
  # Regenerate with: grammar-tools compile-tokens nib.tokens
  #
  # This file embeds a TokenGrammar as native Elixir data structures.
  # Call token_grammar/0 instead of reading and parsing the .tokens file.
  
  alias CodingAdventures.GrammarTools.TokenGrammar
  
  def token_grammar do
    %TokenGrammar{
      definitions: [
          %{
            name: "WRAP_ADD",
            pattern: "+%",
            is_regex: false,
            line_number: 56,
            alias: nil,
          },
          %{
            name: "SAT_ADD",
            pattern: "+?",
            is_regex: false,
            line_number: 63,
            alias: nil,
          },
          %{
            name: "RANGE",
            pattern: "..",
            is_regex: false,
            line_number: 73,
            alias: nil,
          },
          %{
            name: "ARROW",
            pattern: "->",
            is_regex: false,
            line_number: 79,
            alias: nil,
          },
          %{
            name: "EQ_EQ",
            pattern: "==",
            is_regex: false,
            line_number: 87,
            alias: nil,
          },
          %{
            name: "NEQ",
            pattern: "!=",
            is_regex: false,
            line_number: 93,
            alias: nil,
          },
          %{
            name: "LEQ",
            pattern: "<=",
            is_regex: false,
            line_number: 97,
            alias: nil,
          },
          %{
            name: "GEQ",
            pattern: ">=",
            is_regex: false,
            line_number: 101,
            alias: nil,
          },
          %{
            name: "LAND",
            pattern: "&&",
            is_regex: false,
            line_number: 108,
            alias: nil,
          },
          %{
            name: "LOR",
            pattern: "||",
            is_regex: false,
            line_number: 115,
            alias: nil,
          },
          %{
            name: "SHL",
            pattern: "<<",
            is_regex: false,
            line_number: 119,
            alias: nil,
          },
          %{
            name: "SHR",
            pattern: ">>",
            is_regex: false,
            line_number: 120,
            alias: nil,
          },
          %{
            name: "PLUS",
            pattern: "+",
            is_regex: false,
            line_number: 128,
            alias: nil,
          },
          %{
            name: "MINUS",
            pattern: "-",
            is_regex: false,
            line_number: 131,
            alias: nil,
          },
          %{
            name: "STAR",
            pattern: "*",
            is_regex: false,
            line_number: 137,
            alias: nil,
          },
          %{
            name: "SLASH",
            pattern: "/",
            is_regex: false,
            line_number: 141,
            alias: nil,
          },
          %{
            name: "PERCENT",
            pattern: "%",
            is_regex: false,
            line_number: 146,
            alias: nil,
          },
          %{
            name: "AMP",
            pattern: "&",
            is_regex: false,
            line_number: 154,
            alias: nil,
          },
          %{
            name: "PIPE",
            pattern: "|",
            is_regex: false,
            line_number: 158,
            alias: nil,
          },
          %{
            name: "CARET",
            pattern: "^",
            is_regex: false,
            line_number: 161,
            alias: nil,
          },
          %{
            name: "TILDE",
            pattern: "~",
            is_regex: false,
            line_number: 165,
            alias: nil,
          },
          %{
            name: "BANG",
            pattern: "!",
            is_regex: false,
            line_number: 174,
            alias: nil,
          },
          %{
            name: "LT",
            pattern: "<",
            is_regex: false,
            line_number: 177,
            alias: nil,
          },
          %{
            name: "GT",
            pattern: ">",
            is_regex: false,
            line_number: 180,
            alias: nil,
          },
          %{
            name: "EQ",
            pattern: "=",
            is_regex: false,
            line_number: 190,
            alias: nil,
          },
          %{
            name: "LBRACE",
            pattern: "{",
            is_regex: false,
            line_number: 197,
            alias: nil,
          },
          %{
            name: "RBRACE",
            pattern: "}",
            is_regex: false,
            line_number: 198,
            alias: nil,
          },
          %{
            name: "LPAREN",
            pattern: "(",
            is_regex: false,
            line_number: 201,
            alias: nil,
          },
          %{
            name: "RPAREN",
            pattern: ")",
            is_regex: false,
            line_number: 202,
            alias: nil,
          },
          %{
            name: "COLON",
            pattern: ":",
            is_regex: false,
            line_number: 206,
            alias: nil,
          },
          %{
            name: "SEMICOLON",
            pattern: ";",
            is_regex: false,
            line_number: 211,
            alias: nil,
          },
          %{
            name: "COMMA",
            pattern: ",",
            is_regex: false,
            line_number: 214,
            alias: nil,
          },
          %{
            name: "HEX_LIT",
            pattern: "0x[0-9A-Fa-f]+",
            is_regex: true,
            line_number: 227,
            alias: nil,
          },
          %{
            name: "INT_LIT",
            pattern: "[0-9]+",
            is_regex: true,
            line_number: 231,
            alias: nil,
          },
          %{
            name: "NAME",
            pattern: "[a-zA-Z_][a-zA-Z0-9_]*",
            is_regex: true,
            line_number: 239,
            alias: nil,
          },
        ],
      keywords: ["fn", "let", "static", "const", "return", "for", "while", "in", "if", "else", "true", "false"],
      mode: nil,
      escape_mode: nil,
      skip_definitions: [
          %{
            name: "WHITESPACE",
            pattern: "[ \\t\\r\\n]+",
            is_regex: true,
            line_number: 309,
            alias: nil,
          },
          %{
            name: "LINE_COMMENT",
            pattern: "\\/\\/[^\\n]*",
            is_regex: true,
            line_number: 317,
            alias: nil,
          },
        ],
      reserved_keywords: [],
      error_definitions: [],
      groups: %{},
      layout_keywords: [],
      case_sensitive: true,
      version: 1,
      case_insensitive: false,
      start_mode: nil,
      transitions: [],
    }
  end
end
