"""hdl-ir — Hardware IR.

The unified intermediate representation that every HDL front-end (Verilog,
VHDL, Ruby DSL) elaborates into and every back-end (simulation, synthesis,
FPGA mapping, ASIC tools) consumes. See ``code/specs/hdl-ir.md`` for the
complete design.
"""

from hdl_ir.expr import (
    BINARY_OPS,
    UNARY_OPS,
    Attribute,
    BinaryOp,
    Concat,
    Expr,
    FunCall,
    Lit,
    NetRef,
    PortRef,
    Replication,
    Slice,
    SystemCall,
    Ternary,
    UnaryOp,
    VarRef,
    expr_from_dict,
)
from hdl_ir.hir import HIR, SCHEMA_VERSION, HIRStats
from hdl_ir.module import (
    ContAssign,
    Direction,
    Instance,
    Level,
    Library,
    Module,
    Net,
    NetKind,
    Parameter,
    Port,
    Process,
    ProcessKind,
    SensitivityItem,
    Variable,
)
from hdl_ir.provenance import Provenance, SourceLang, SourceLocation
from hdl_ir.stmt import (
    AssertStmt,
    BlockingAssign,
    CaseItem,
    CaseStmt,
    DelayStmt,
    DisableStmt,
    Event,
    EventStmt,
    ExprStmt,
    ForeverStmt,
    ForStmt,
    IfStmt,
    NonblockingAssign,
    NullStmt,
    RepeatStmt,
    ReportStmt,
    ReturnStmt,
    Stmt,
    WaitStmt,
    WhileStmt,
    stmt_from_dict,
)
from hdl_ir.types import (
    Ty,
    TyArray,
    TyBit,
    TyEnum,
    TyFile,
    TyInteger,
    TyLogic,
    TyReal,
    TyRecord,
    TyStdLogic,
    TyString,
    TyTime,
    TyVector,
    ty_from_dict,
    width,
)
from hdl_ir.validate import ValidationReport, validate

__version__ = "0.1.0"

__all__ = [
    # Top-level
    "HIR",
    "HIRStats",
    "SCHEMA_VERSION",
    "__version__",
    # Provenance
    "Provenance",
    "SourceLang",
    "SourceLocation",
    # Types
    "Ty",
    "TyArray",
    "TyBit",
    "TyEnum",
    "TyFile",
    "TyInteger",
    "TyLogic",
    "TyReal",
    "TyRecord",
    "TyStdLogic",
    "TyString",
    "TyTime",
    "TyVector",
    "ty_from_dict",
    "width",
    # Expressions
    "Attribute",
    "BinaryOp",
    "Concat",
    "Expr",
    "FunCall",
    "Lit",
    "NetRef",
    "PortRef",
    "Replication",
    "Slice",
    "SystemCall",
    "Ternary",
    "UnaryOp",
    "VarRef",
    "BINARY_OPS",
    "UNARY_OPS",
    "expr_from_dict",
    # Statements
    "AssertStmt",
    "BlockingAssign",
    "CaseItem",
    "CaseStmt",
    "DelayStmt",
    "DisableStmt",
    "Event",
    "EventStmt",
    "ExprStmt",
    "ForeverStmt",
    "ForStmt",
    "IfStmt",
    "NonblockingAssign",
    "NullStmt",
    "RepeatStmt",
    "ReportStmt",
    "ReturnStmt",
    "Stmt",
    "WaitStmt",
    "WhileStmt",
    "stmt_from_dict",
    # Module-level
    "ContAssign",
    "Direction",
    "Instance",
    "Level",
    "Library",
    "Module",
    "Net",
    "NetKind",
    "Parameter",
    "Port",
    "Process",
    "ProcessKind",
    "SensitivityItem",
    "Variable",
    # Validation
    "ValidationReport",
    "validate",
]
