cd ../../../packages/typescript/directed-graph && npm ci --quiet
cd ../../../packages/typescript/state-machine && npm ci --quiet
cd ../../../packages/typescript/cli-builder && npm install --silent
npm ci --quiet
npx vitest run --coverage
