cd ../../../packages/typescript/directed-graph && npm install --silent && cd ../state-machine && npm install --silent && cd ../cli-builder && npm install --silent
cd ../../../programs/typescript/pwd && npm install --silent && npx tsx src/index.ts
