requires 'CodingAdventures::CliBuilder';
requires 'CodingAdventures::PaintInstructions';
requires 'CodingAdventures::PaintVmAscii';
requires 'JSON::PP', '2.00';

on test => sub {
    requires 'Test2::V0';
    requires 'File::Temp';
};
