// AUTO-GENERATED FILE — DO NOT EDIT
// Source: matlab.tokens
// Regenerate with: grammar-tools compile-tokens matlab.tokens
//
// This file embeds a TokenGrammar as native Rust data structures.
// Call `token_grammar()` instead of reading and parsing the .tokens file.

#[allow(unused_imports)]
use grammar_tools::token_grammar::{
    ModeTransition, PatternGroup, TokenDefinition, TokenGrammar, TransitionAction,
};
#[allow(unused_imports)]
use std::collections::HashMap;

pub fn token_grammar() -> TokenGrammar {
    TokenGrammar {
        definitions: vec![
            TokenDefinition {
                name: r#"ELEM_POW"#.to_string(),
                pattern: r#".^"#.to_string(),
                is_regex: false,
                line_number: 32,
                alias: None,
            },
            TokenDefinition {
                name: r#"ELEM_MUL"#.to_string(),
                pattern: r#".*"#.to_string(),
                is_regex: false,
                line_number: 33,
                alias: None,
            },
            TokenDefinition {
                name: r#"ELEM_RDIV"#.to_string(),
                pattern: r#"./"#.to_string(),
                is_regex: false,
                line_number: 34,
                alias: None,
            },
            TokenDefinition {
                name: r#"ELEM_LDIV"#.to_string(),
                pattern: r#"\.\\"#.to_string(),
                is_regex: true,
                line_number: 35,
                alias: None,
            },
            TokenDefinition {
                name: r#"ELEM_TRANSPOSE"#.to_string(),
                pattern: r#".'"#.to_string(),
                is_regex: false,
                line_number: 36,
                alias: None,
            },
            TokenDefinition {
                name: r#"EQ_EQ"#.to_string(),
                pattern: r#"=="#.to_string(),
                is_regex: false,
                line_number: 38,
                alias: None,
            },
            TokenDefinition {
                name: r#"NE"#.to_string(),
                pattern: r#"~="#.to_string(),
                is_regex: false,
                line_number: 39,
                alias: None,
            },
            TokenDefinition {
                name: r#"LE"#.to_string(),
                pattern: r#"<="#.to_string(),
                is_regex: false,
                line_number: 40,
                alias: None,
            },
            TokenDefinition {
                name: r#"GE"#.to_string(),
                pattern: r#">="#.to_string(),
                is_regex: false,
                line_number: 41,
                alias: None,
            },
            TokenDefinition {
                name: r#"AND_AND"#.to_string(),
                pattern: r#"&&"#.to_string(),
                is_regex: false,
                line_number: 42,
                alias: None,
            },
            TokenDefinition {
                name: r#"OR_OR"#.to_string(),
                pattern: r#"||"#.to_string(),
                is_regex: false,
                line_number: 43,
                alias: None,
            },
            TokenDefinition {
                name: r#"CHARARRAY"#.to_string(),
                pattern: r#"`[0-9]+`"#.to_string(),
                is_regex: true,
                line_number: 54,
                alias: Some(r#"STRING"#.to_string()),
            },
            TokenDefinition {
                name: r#"DQ_STRING"#.to_string(),
                pattern: r#""([^"]|"")*""#.to_string(),
                is_regex: true,
                line_number: 55,
                alias: Some(r#"STRING"#.to_string()),
            },
            TokenDefinition {
                name: r#"NUMBER"#.to_string(),
                pattern: r#"([0-9]+(\.[0-9]+)?|\.[0-9]+)([eE][+-]?[0-9]+)?"#.to_string(),
                is_regex: true,
                line_number: 65,
                alias: None,
            },
            TokenDefinition {
                name: r#"NAME"#.to_string(),
                pattern: r#"[A-Za-z_][A-Za-z0-9_]*"#.to_string(),
                is_regex: true,
                line_number: 76,
                alias: None,
            },
            TokenDefinition {
                name: r#"TRANSPOSE"#.to_string(),
                pattern: r#"'"#.to_string(),
                is_regex: false,
                line_number: 108,
                alias: None,
            },
            TokenDefinition {
                name: r#"PLUS"#.to_string(),
                pattern: r#"+"#.to_string(),
                is_regex: false,
                line_number: 109,
                alias: None,
            },
            TokenDefinition {
                name: r#"MINUS"#.to_string(),
                pattern: r#"-"#.to_string(),
                is_regex: false,
                line_number: 110,
                alias: None,
            },
            TokenDefinition {
                name: r#"STAR"#.to_string(),
                pattern: r#"*"#.to_string(),
                is_regex: false,
                line_number: 111,
                alias: None,
            },
            TokenDefinition {
                name: r#"SLASH"#.to_string(),
                pattern: r#"/"#.to_string(),
                is_regex: false,
                line_number: 112,
                alias: None,
            },
            TokenDefinition {
                name: r#"BACKSLASH"#.to_string(),
                pattern: r#"\\"#.to_string(),
                is_regex: true,
                line_number: 113,
                alias: None,
            },
            TokenDefinition {
                name: r#"CARET"#.to_string(),
                pattern: r#"^"#.to_string(),
                is_regex: false,
                line_number: 114,
                alias: None,
            },
            TokenDefinition {
                name: r#"LT"#.to_string(),
                pattern: r#"<"#.to_string(),
                is_regex: false,
                line_number: 115,
                alias: None,
            },
            TokenDefinition {
                name: r#"GT"#.to_string(),
                pattern: r#">"#.to_string(),
                is_regex: false,
                line_number: 116,
                alias: None,
            },
            TokenDefinition {
                name: r#"EQ"#.to_string(),
                pattern: r#"="#.to_string(),
                is_regex: false,
                line_number: 117,
                alias: None,
            },
            TokenDefinition {
                name: r#"TILDE"#.to_string(),
                pattern: r#"~"#.to_string(),
                is_regex: false,
                line_number: 118,
                alias: None,
            },
            TokenDefinition {
                name: r#"AMP"#.to_string(),
                pattern: r#"&"#.to_string(),
                is_regex: false,
                line_number: 119,
                alias: None,
            },
            TokenDefinition {
                name: r#"PIPE"#.to_string(),
                pattern: r#"|"#.to_string(),
                is_regex: false,
                line_number: 120,
                alias: None,
            },
            TokenDefinition {
                name: r#"COLON"#.to_string(),
                pattern: r#":"#.to_string(),
                is_regex: false,
                line_number: 121,
                alias: None,
            },
            TokenDefinition {
                name: r#"DOT"#.to_string(),
                pattern: r#"."#.to_string(),
                is_regex: false,
                line_number: 122,
                alias: None,
            },
            TokenDefinition {
                name: r#"AT"#.to_string(),
                pattern: r#"@"#.to_string(),
                is_regex: false,
                line_number: 123,
                alias: None,
            },
            TokenDefinition {
                name: r#"LPAREN"#.to_string(),
                pattern: r#"("#.to_string(),
                is_regex: false,
                line_number: 124,
                alias: None,
            },
            TokenDefinition {
                name: r#"RPAREN"#.to_string(),
                pattern: r#")"#.to_string(),
                is_regex: false,
                line_number: 125,
                alias: None,
            },
            TokenDefinition {
                name: r#"LBRACKET"#.to_string(),
                pattern: r#"["#.to_string(),
                is_regex: false,
                line_number: 126,
                alias: None,
            },
            TokenDefinition {
                name: r#"RBRACKET"#.to_string(),
                pattern: r#"]"#.to_string(),
                is_regex: false,
                line_number: 127,
                alias: None,
            },
            TokenDefinition {
                name: r#"LBRACE"#.to_string(),
                pattern: r#"{"#.to_string(),
                is_regex: false,
                line_number: 128,
                alias: None,
            },
            TokenDefinition {
                name: r#"RBRACE"#.to_string(),
                pattern: r#"}"#.to_string(),
                is_regex: false,
                line_number: 129,
                alias: None,
            },
            TokenDefinition {
                name: r#"COMMA"#.to_string(),
                pattern: r#","#.to_string(),
                is_regex: false,
                line_number: 130,
                alias: None,
            },
            TokenDefinition {
                name: r#"SEMICOLON"#.to_string(),
                pattern: r#";"#.to_string(),
                is_regex: false,
                line_number: 131,
                alias: None,
            },
            TokenDefinition {
                name: r#"NEWLINE"#.to_string(),
                pattern: r#"\r?\n"#.to_string(),
                is_regex: true,
                line_number: 142,
                alias: None,
            },
        ],
        keywords: vec![
            r#"if"#.to_string(),
            r#"elseif"#.to_string(),
            r#"else"#.to_string(),
            r#"end"#.to_string(),
            r#"for"#.to_string(),
            r#"while"#.to_string(),
            r#"break"#.to_string(),
            r#"continue"#.to_string(),
            r#"switch"#.to_string(),
            r#"case"#.to_string(),
            r#"otherwise"#.to_string(),
            r#"function"#.to_string(),
            r#"return"#.to_string(),
            r#"global"#.to_string(),
            r#"persistent"#.to_string(),
            r#"try"#.to_string(),
            r#"catch"#.to_string(),
        ],
        mode: None,
        skip_definitions: vec![
            TokenDefinition {
                name: r#"WHITESPACE"#.to_string(),
                pattern: r#"[ \t]+"#.to_string(),
                is_regex: true,
                line_number: 150,
                alias: None,
            },
            TokenDefinition {
                name: r#"COMMENT"#.to_string(),
                pattern: r#"%[^\n]*"#.to_string(),
                is_regex: true,
                line_number: 151,
                alias: None,
            },
        ],
        reserved_keywords: vec![],
        escapes: None,
        error_definitions: vec![TokenDefinition {
            name: r#"UNKNOWN"#.to_string(),
            pattern: r#"."#.to_string(),
            is_regex: true,
            line_number: 158,
            alias: None,
        }],
        groups: HashMap::new(),
        case_sensitive: true,
        version: 0,
        case_insensitive: false,
        context_keywords: vec![],
        soft_keywords: vec![],
        layout_keywords: vec![],
        start_mode: None,
        transitions: vec![],
    }
}
