uv pip install --system -e ../../../packages/python/irc-proto -e ../../../packages/python/irc-framing -e ../../../packages/python/irc-server -e ../../../packages/python/irc-net-selectors -e .[dev] --quiet
python -m pytest tests/ -v
