python -m pip install -e ../../../packages/python/irc-proto -e ../../../packages/python/irc-framing -e ../../../packages/python/irc-server -e ../../../packages/python/irc-net-stdlib -e .[dev] --quiet
python -m pytest tests/ -v
