load("code/packages/starlark/program-rules/typescript_binary.star", "ts_binary")

_targets = [
    ts_binary(
        name = "unix-tools",
        srcs = ["src/**/*.ts", "*.ts"],
        deps = [],
    ),
]
