cd ../../../packages/typescript/directed-graph && npm install --silent && cd ../state-machine && npm install --silent && cd ../cli-builder && npm install --silent
cd ../../../programs/typescript/unix-tools && npm install --silent && npx tsx src/pwd.ts
