(cd ../../../packages/python/single-layer-network && python -m pytest tests)
(cd ../../../packages/python/two-layer-network && python -m pytest tests)
PYTHONPATH=../../../packages/python/two-layer-network/src:../../../packages/python/single-layer-network/src python main.py
