// ContentView.swift — the VisiCalc UI host shell (VC2-swiftui).
//
// Mounts the auto-generated FormulaBarView above the auto-generated
// GridView.  Both come from `bash scripts/build.sh` which runs
// `mosaic-compile --backend swiftui` against the shared
// `demo/visicalc/mosaic/{FormulaBar,Grid}.{mil,desktop.mll,dark.msl}`
// triples.  Grid.desktop.mll is itself a UI34
// `pkg::mosaic-pkg-grid::Grid` one-liner, so the SwiftUI view comes
// from the authoritative `mosaic-pkg-grid` composition.  No
// hand-written widgets in this file.
//
// Same hard-coded 5×5 sample data as the other VC2-* demos so the
// SwiftUI render matches React / HTML / WebComponent visually.

import SwiftUI

struct ContentView: View {
    // 5×5 sample spreadsheet, same data as VC2-react / -html / -webcomp.
    // The leading column on every row is the row-label ("1".."5") —
    // exactly the shape the web demos feed their Grid, so the SwiftUI
    // render carries row numbers down the left edge like a real
    // spreadsheet (and the column count lines up with columnWidths and
    // columnHeaders below).
    static let sampleRows: [[String]] = [
        ["1", "15", "3",  "12", "8",  "5"],
        ["2", "8",  "14", "7",  "22", "11"],
        ["3", "12", "9",  "18", "6",  "25"],
        ["4", "4",  "11", "3",  "17", "9"],
        ["5", "7",  "5",  "13", "10", "19"],
    ]

    // The generated GridView's slot signature uses Double for every
    // numeric coordinate (the `number` slot type lowers to Double in
    // the SwiftUI emitter).  We mirror that here so the SwiftUI
    // type-checker sees a clean pass-through; arithmetic / display
    // logic that wants integer indices can re-cast at the use site.
    // Column 0 is the row-label gutter, so the first *data* cell is at
    // column 1.  Start with A1 (data column 1, row 0) selected.
    @State private var selectedRow: Double = 0
    @State private var selectedCol: Double = 1
    @State private var editRow:     Double = -1
    @State private var editCol:     Double = -1
    @State private var editContent: String = ""
    @State private var formula:     String = "=SUM(B1:B5)"

    private var cellAddress: String {
        let colIdx = Int(selectedCol)
        let rowIdx = Int(selectedRow)
        // colIdx 1 → "A" (column 0 is the row-label gutter, which has no
        // spreadsheet address).  Clicking the gutter just shows the row.
        guard colIdx >= 1 else { return "\(rowIdx + 1)" }
        let colLetter = Character(UnicodeScalar(65 + UInt32(colIdx - 1))!)
        return "\(colLetter)\(rowIdx + 1)"
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            Text("VISICALC · MOSAIC SWIFTUI DEMO")
                .font(.system(size: 11))
                .tracking(1.0)
                .foregroundColor(Color(hex: 0x9D9D9D))
                .padding([.top, .leading, .trailing], 16)
                .padding(.bottom, 8)

            // FormulaBar — generated by mosaic-compile.
            FormulaBarView(
                cellAddress: cellAddress,
                formula: formula,
                readOnly: false,
                dispatch: handleFormulaBarEvent
            )

            // Grid — also generated by mosaic-compile, from the same
            // demo/visicalc/mosaic/Grid.* triple the React + HTML +
            // WebComponent demos consume.  Grid.desktop.mll is a UI34
            // `pkg::mosaic-pkg-grid::Grid` one-liner; the SwiftUI
            // emitter substitutes the package's full composition at
            // build time and lowers it to a SwiftUI `View` struct.
            GridView(
                // Leading "" is the empty corner above the row-label
                // column; A–E label the five data columns.  Six entries
                // line up 1:1 with columnWidths and each row's six cells.
                columnHeaders: ["", "A", "B", "C", "D", "E"],
                viewportRows: ContentView.sampleRows,
                // First column is the 48px row-label gutter; the five
                // data columns are 96px each (visicalc convention).
                columnWidths: [48, 96, 96, 96, 96, 96],
                totalHeight: 0,  // Sticky-header viewport size — not
                                 // exercised by VC2; the package's
                                 // Grid v0.2.0 deferred sticky-header
                                 // support per its README.
                selectedRow: selectedRow,
                selectedCol: selectedCol,
                editRow: editRow,
                editCol: editCol,
                editContent: editContent,
                dispatch: handleGridEvent
            )
            .padding(16)

            Spacer()
        }
        .frame(maxWidth: 720, maxHeight: .infinity, alignment: .topLeading)
        .background(Color(hex: 0x1E1E1E))
        .preferredColorScheme(.dark)
    }

    private func handleFormulaBarEvent(_ event: FormulaBarEvent) {
        switch event {
        case .formulaChange(let value):
            formula = value
        case .commit:
            break // no-op for v1
        case .cancel:
            let r = Int(selectedRow)
            let c = Int(selectedCol)
            if r >= 0 && r < ContentView.sampleRows.count {
                let row = ContentView.sampleRows[r]
                if c >= 0 && c < row.count {
                    formula = row[c]
                }
            }
        }
    }

    private func handleGridEvent(_ event: GridEvent) {
        switch event {
        case .navigate(let row, let col):
            selectedRow = row
            selectedCol = col
            let r = Int(row)
            let c = Int(col)
            if r >= 0 && r < ContentView.sampleRows.count {
                let rowData = ContentView.sampleRows[r]
                if c >= 0 && c < rowData.count {
                    formula = rowData[c]
                }
            }
        case .formulaChange(let value):
            editContent = value
        case .editCommit:
            editRow = -1
            editCol = -1
        case .editCancel:
            editRow = -1
            editCol = -1
            editContent = ""
        }
    }
}

// Helper init for hex colours so we don't have to write
// `Color(red:, green:, blue:)` everywhere.
extension Color {
    init(hex: UInt32) {
        let r = Double((hex >> 16) & 0xFF) / 255.0
        let g = Double((hex >> 8) & 0xFF) / 255.0
        let b = Double(hex & 0xFF) / 255.0
        self.init(red: r, green: g, blue: b)
    }
}
