load("code/packages/starlark/program-rules/rust_binary.star", "rust_binary")

_targets = [
    rust_binary(
        name = "scaffold-generator",
        srcs = ["src/**/*.rs"],
        deps = [],
    ),
]
