# AUTO-GENERATED FILE — DO NOT EDIT
# Source: algol60.tokens
# Regenerate with: perl code/programs/perl/grammar-tools/grammar-tools.pl compile-tokens algol60.tokens
#
# This file embeds a TokenGrammar as native Perl data structures.
# Call token_grammar() instead of reading and parsing the .tokens file.

package CodingAdventures::AlgolLexer::_Grammar;
use strict;
use warnings;

sub token_grammar {
    return bless {
        definitions => [
            bless({
                name => 'REAL_LIT',
                pattern => '[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?|[0-9]+[eE][+-]?[0-9]+',
                is_regex => 1,
                line_number => 38,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'INTEGER_LIT',
                pattern => '[0-9]+',
                is_regex => 1,
                line_number => 41,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_LIT',
                pattern => '\'[^\']*\'|"[^"]*"',
                is_regex => 1,
                line_number => 46,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NAME',
                pattern => '[a-zA-Z][a-zA-Z0-9]*',
                is_regex => 1,
                line_number => 53,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'ASSIGN',
                pattern => ':=',
                is_regex => 0,
                line_number => 61,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'POWER',
                pattern => '**',
                is_regex => 0,
                line_number => 66,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEQ',
                pattern => '<=|≤',
                is_regex => 1,
                line_number => 70,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'GEQ',
                pattern => '>=|≥',
                is_regex => 1,
                line_number => 71,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NEQ',
                pattern => '!=|<>|≠',
                is_regex => 1,
                line_number => 72,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NOT_SYM',
                pattern => '¬',
                is_regex => 0,
                line_number => 76,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AND_SYM',
                pattern => '∧',
                is_regex => 0,
                line_number => 77,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'OR_SYM',
                pattern => '∨',
                is_regex => 0,
                line_number => 78,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'IMPL_SYM',
                pattern => '⊃',
                is_regex => 0,
                line_number => 79,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'EQV_SYM',
                pattern => '≡',
                is_regex => 0,
                line_number => 80,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS',
                pattern => '+',
                is_regex => 0,
                line_number => 86,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS',
                pattern => '-',
                is_regex => 0,
                line_number => 87,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STAR',
                pattern => '\\*|×',
                is_regex => 1,
                line_number => 90,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SLASH',
                pattern => '\\/|÷',
                is_regex => 1,
                line_number => 91,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'CARET',
                pattern => '\\^|↑',
                is_regex => 1,
                line_number => 95,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'EQ',
                pattern => '=',
                is_regex => 0,
                line_number => 98,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LT',
                pattern => '<',
                is_regex => 0,
                line_number => 100,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'GT',
                pattern => '>',
                is_regex => 0,
                line_number => 101,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LPAREN',
                pattern => '(',
                is_regex => 0,
                line_number => 107,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RPAREN',
                pattern => ')',
                is_regex => 0,
                line_number => 108,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LBRACKET',
                pattern => '[',
                is_regex => 0,
                line_number => 109,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RBRACKET',
                pattern => ']',
                is_regex => 0,
                line_number => 110,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SEMICOLON',
                pattern => ';',
                is_regex => 0,
                line_number => 111,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COMMA',
                pattern => ',',
                is_regex => 0,
                line_number => 112,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COLON',
                pattern => ':',
                is_regex => 0,
                line_number => 116,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        keywords => [
            'begin',
            'end',
            'if',
            'then',
            'else',
            'for',
            'do',
            'step',
            'until',
            'while',
            'goto',
            'switch',
            'procedure',
            'own',
            'array',
            'label',
            'value',
            'integer',
            'real',
            'boolean',
            'string',
            'true',
            'false',
            'not',
            'and',
            'or',
            'impl',
            'eqv',
            'div',
            'mod',
            'comment',
        ],
        context_keywords => [],
        layout_keywords => [],
        soft_keywords => [],
        mode => '',
        escape_mode => '',
        skip_definitions => [
            bless({
                name => 'WHITESPACE',
                pattern => '[ \\t\\r\\n]+',
                is_regex => 1,
                line_number => 183,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COMMENT',
                pattern => 'comment[^a-zA-Z0-9_][^;]*;',
                is_regex => 1,
                line_number => 192,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        error_definitions => [],
        reserved_keywords => [],
        groups => {},
        start_mode => '',
        transitions => [],
    }, 'CodingAdventures::GrammarTools::TokenGrammar';
}

1;
