// AUTO-GENERATED FILE — DO NOT EDIT
// Source: excel.tokens
// Regenerate with: grammar-tools compile-tokens excel.tokens
//
// This file embeds a TokenGrammar as native Rust data structures.
// Call `token_grammar()` instead of reading and parsing the .tokens file.

#[allow(unused_imports)]
use grammar_tools::token_grammar::{PatternGroup, TokenDefinition, TokenGrammar};
#[allow(unused_imports)]
use std::collections::HashMap;

pub fn token_grammar() -> TokenGrammar {
    TokenGrammar {
        definitions: vec![
            TokenDefinition {
                name: r#"SPACE"#.to_string(),
                pattern: r#" +"#.to_string(),
                is_regex: true,
                line_number: 13,
                alias: None,
            },
            TokenDefinition {
                name: r#"REF_PREFIX_QUOTED"#.to_string(),
                pattern: r#"(\[[^\]]+\])?'([^']|'')*'!"#.to_string(),
                is_regex: true,
                line_number: 15,
                alias: Some(r#"REF_PREFIX"#.to_string()),
            },
            TokenDefinition {
                name: r#"REF_PREFIX_WB_BARE"#.to_string(),
                pattern: r#"\[[^\]]+\][A-Za-z_][A-Za-z0-9_.:]*!"#.to_string(),
                is_regex: true,
                line_number: 16,
                alias: Some(r#"REF_PREFIX"#.to_string()),
            },
            TokenDefinition {
                name: r#"REF_PREFIX_BARE"#.to_string(),
                pattern: r#"[A-Za-z_][A-Za-z0-9_.:]*!"#.to_string(),
                is_regex: true,
                line_number: 17,
                alias: Some(r#"REF_PREFIX"#.to_string()),
            },
            TokenDefinition {
                name: r#"STRING"#.to_string(),
                pattern: r#""([^"]|"")*""#.to_string(),
                is_regex: true,
                line_number: 19,
                alias: None,
            },
            TokenDefinition {
                name: r#"ERROR_CONSTANT"#.to_string(),
                pattern: r#"#[a-z0-9\/\?!]*[a-z0-9\?!]"#.to_string(),
                is_regex: true,
                line_number: 20,
                alias: None,
            },
            TokenDefinition {
                name: r#"NUMBER_DOT_EXP"#.to_string(),
                pattern: r#"\.[0-9]+[eE][-+]?[0-9]+"#.to_string(),
                is_regex: true,
                line_number: 26,
                alias: Some(r#"NUMBER"#.to_string()),
            },
            TokenDefinition {
                name: r#"NUMBER_DOT"#.to_string(),
                pattern: r#"\.[0-9]+"#.to_string(),
                is_regex: true,
                line_number: 27,
                alias: Some(r#"NUMBER"#.to_string()),
            },
            TokenDefinition {
                name: r#"NUMBER_EXP"#.to_string(),
                pattern: r#"[0-9]+\.?[0-9]*[eE][-+]?[0-9]+"#.to_string(),
                is_regex: true,
                line_number: 28,
                alias: Some(r#"NUMBER"#.to_string()),
            },
            TokenDefinition {
                name: r#"NUMBER"#.to_string(),
                pattern: r#"[0-9]+\.?[0-9]*"#.to_string(),
                is_regex: true,
                line_number: 29,
                alias: None,
            },
            TokenDefinition {
                name: r#"STRUCTURED_KEYWORD"#.to_string(),
                pattern: r#"\[#[a-z ]+\]"#.to_string(),
                is_regex: true,
                line_number: 31,
                alias: None,
            },
            TokenDefinition {
                name: r#"STRUCTURED_COLUMN"#.to_string(),
                pattern: r#"\[[^\[\]]+\]"#.to_string(),
                is_regex: true,
                line_number: 32,
                alias: None,
            },
            TokenDefinition {
                name: r#"CELL"#.to_string(),
                pattern: r#"\$?[A-Za-z]{1,3}\$?[0-9]{1,7}"#.to_string(),
                is_regex: true,
                line_number: 35,
                alias: None,
            },
            TokenDefinition {
                name: r#"NOT_EQUALS"#.to_string(),
                pattern: r#"<>"#.to_string(),
                is_regex: false,
                line_number: 37,
                alias: None,
            },
            TokenDefinition {
                name: r#"LESS_EQUALS"#.to_string(),
                pattern: r#"<="#.to_string(),
                is_regex: false,
                line_number: 38,
                alias: None,
            },
            TokenDefinition {
                name: r#"GREATER_EQUALS"#.to_string(),
                pattern: r#">="#.to_string(),
                is_regex: false,
                line_number: 39,
                alias: None,
            },
            TokenDefinition {
                name: r#"PLUS"#.to_string(),
                pattern: r#"+"#.to_string(),
                is_regex: false,
                line_number: 41,
                alias: None,
            },
            TokenDefinition {
                name: r#"MINUS"#.to_string(),
                pattern: r#"-"#.to_string(),
                is_regex: false,
                line_number: 42,
                alias: None,
            },
            TokenDefinition {
                name: r#"STAR"#.to_string(),
                pattern: r#"*"#.to_string(),
                is_regex: false,
                line_number: 43,
                alias: None,
            },
            TokenDefinition {
                name: r#"SLASH"#.to_string(),
                pattern: r#"/"#.to_string(),
                is_regex: false,
                line_number: 44,
                alias: None,
            },
            TokenDefinition {
                name: r#"CARET"#.to_string(),
                pattern: r#"^"#.to_string(),
                is_regex: false,
                line_number: 45,
                alias: None,
            },
            TokenDefinition {
                name: r#"AMP"#.to_string(),
                pattern: r#"&"#.to_string(),
                is_regex: false,
                line_number: 46,
                alias: None,
            },
            TokenDefinition {
                name: r#"PERCENT"#.to_string(),
                pattern: r#"%"#.to_string(),
                is_regex: false,
                line_number: 47,
                alias: None,
            },
            TokenDefinition {
                name: r#"EQUALS"#.to_string(),
                pattern: r#"="#.to_string(),
                is_regex: false,
                line_number: 48,
                alias: None,
            },
            TokenDefinition {
                name: r#"LESS_THAN"#.to_string(),
                pattern: r#"<"#.to_string(),
                is_regex: false,
                line_number: 49,
                alias: None,
            },
            TokenDefinition {
                name: r#"GREATER_THAN"#.to_string(),
                pattern: r#">"#.to_string(),
                is_regex: false,
                line_number: 50,
                alias: None,
            },
            TokenDefinition {
                name: r#"BANG"#.to_string(),
                pattern: r#"!"#.to_string(),
                is_regex: false,
                line_number: 51,
                alias: None,
            },
            TokenDefinition {
                name: r#"DOLLAR"#.to_string(),
                pattern: r#"$"#.to_string(),
                is_regex: false,
                line_number: 52,
                alias: None,
            },
            TokenDefinition {
                name: r#"LPAREN"#.to_string(),
                pattern: r#"("#.to_string(),
                is_regex: false,
                line_number: 53,
                alias: None,
            },
            TokenDefinition {
                name: r#"RPAREN"#.to_string(),
                pattern: r#")"#.to_string(),
                is_regex: false,
                line_number: 54,
                alias: None,
            },
            TokenDefinition {
                name: r#"LBRACE"#.to_string(),
                pattern: r#"{"#.to_string(),
                is_regex: false,
                line_number: 55,
                alias: None,
            },
            TokenDefinition {
                name: r#"RBRACE"#.to_string(),
                pattern: r#"}"#.to_string(),
                is_regex: false,
                line_number: 56,
                alias: None,
            },
            TokenDefinition {
                name: r#"LBRACKET"#.to_string(),
                pattern: r#"["#.to_string(),
                is_regex: false,
                line_number: 57,
                alias: None,
            },
            TokenDefinition {
                name: r#"RBRACKET"#.to_string(),
                pattern: r#"]"#.to_string(),
                is_regex: false,
                line_number: 58,
                alias: None,
            },
            TokenDefinition {
                name: r#"COMMA"#.to_string(),
                pattern: r#","#.to_string(),
                is_regex: false,
                line_number: 59,
                alias: None,
            },
            TokenDefinition {
                name: r#"SEMICOLON"#.to_string(),
                pattern: r#";"#.to_string(),
                is_regex: false,
                line_number: 60,
                alias: None,
            },
            TokenDefinition {
                name: r#"COLON"#.to_string(),
                pattern: r#":"#.to_string(),
                is_regex: false,
                line_number: 61,
                alias: None,
            },
            TokenDefinition {
                name: r#"AT"#.to_string(),
                pattern: r#"@"#.to_string(),
                is_regex: false,
                line_number: 62,
                alias: None,
            },
            TokenDefinition {
                name: r#"NAME"#.to_string(),
                pattern: r#"[A-Za-z_\\][A-Za-z0-9_\.]*"#.to_string(),
                is_regex: true,
                line_number: 64,
                alias: None,
            },
            TokenDefinition {
                name: r#"FUNCTION_NAME"#.to_string(),
                pattern: r#"[^\s\S]"#.to_string(),
                is_regex: true,
                line_number: 70,
                alias: None,
            },
            TokenDefinition {
                name: r#"TABLE_NAME"#.to_string(),
                pattern: r#"[^\s\S]"#.to_string(),
                is_regex: true,
                line_number: 71,
                alias: None,
            },
            TokenDefinition {
                name: r#"COLUMN_REF"#.to_string(),
                pattern: r#"[^\s\S]"#.to_string(),
                is_regex: true,
                line_number: 72,
                alias: None,
            },
            TokenDefinition {
                name: r#"ROW_REF"#.to_string(),
                pattern: r#"[^\s\S]"#.to_string(),
                is_regex: true,
                line_number: 73,
                alias: None,
            },
        ],
        keywords: vec![r#"true"#.to_string(), r#"false"#.to_string()],
        mode: None,
        skip_definitions: vec![
            TokenDefinition {
                name: r#"NONSPACE_WHITESPACE"#.to_string(),
                pattern: r#"[\t\r\n]+"#.to_string(),
                is_regex: true,
                line_number: 11,
                alias: None,
            },
        ],
        reserved_keywords: vec![],
        escapes: None,
        error_definitions: vec![],
        groups: HashMap::new(),
        case_sensitive: true,
        version: 1,
        case_insensitive: true,
        context_keywords: vec![],
        soft_keywords: vec![],
        layout_keywords: vec![],
    }
}
