defmodule CodingAdventures.VhdlLexer.Grammar.V1987 do
  # AUTO-GENERATED FILE — DO NOT EDIT
  # Source: vhdl1987.tokens
  # Regenerate with: grammar-tools compile-tokens vhdl1987.tokens
  #
  # This file embeds a TokenGrammar as native Elixir data structures.
  # Call token_grammar/0 instead of reading and parsing the .tokens file.
  
  alias CodingAdventures.GrammarTools.TokenGrammar
  
  def token_grammar do
    %TokenGrammar{
      definitions: [
          %{
            name: "STRING",
            pattern: "\"([^\"]|\"\")*\"",
            is_regex: true,
            line_number: 66,
            alias: nil,
          },
          %{
            name: "BIT_STRING",
            pattern: "[bBoOxXdD]\"[0-9a-fA-F_]+\"",
            is_regex: true,
            line_number: 85,
            alias: nil,
          },
          %{
            name: "CHAR_LITERAL",
            pattern: "'[^']'",
            is_regex: true,
            line_number: 103,
            alias: nil,
          },
          %{
            name: "BASED_LITERAL",
            pattern: "[0-9]+#[0-9a-fA-F_]+(\\.[0-9a-fA-F_]+)?#([eE][+-]?[0-9_]+)?",
            is_regex: true,
            line_number: 119,
            alias: nil,
          },
          %{
            name: "REAL_NUMBER",
            pattern: "[0-9][0-9_]*\\.[0-9_]+([eE][+-]?[0-9_]+)?",
            is_regex: true,
            line_number: 123,
            alias: nil,
          },
          %{
            name: "NUMBER",
            pattern: "[0-9][0-9_]*",
            is_regex: true,
            line_number: 127,
            alias: nil,
          },
          %{
            name: "EXTENDED_IDENT",
            pattern: "\\\\[^\\\\]+\\\\",
            is_regex: true,
            line_number: 146,
            alias: nil,
          },
          %{
            name: "NAME",
            pattern: "[a-zA-Z][a-zA-Z0-9_]*",
            is_regex: true,
            line_number: 147,
            alias: nil,
          },
          %{
            name: "VAR_ASSIGN",
            pattern: ":=",
            is_regex: false,
            line_number: 168,
            alias: nil,
          },
          %{
            name: "LESS_EQUALS",
            pattern: "<=",
            is_regex: false,
            line_number: 169,
            alias: nil,
          },
          %{
            name: "GREATER_EQUALS",
            pattern: ">=",
            is_regex: false,
            line_number: 170,
            alias: nil,
          },
          %{
            name: "ARROW",
            pattern: "=>",
            is_regex: false,
            line_number: 171,
            alias: nil,
          },
          %{
            name: "NOT_EQUALS",
            pattern: "/=",
            is_regex: false,
            line_number: 172,
            alias: nil,
          },
          %{
            name: "POWER",
            pattern: "**",
            is_regex: false,
            line_number: 173,
            alias: nil,
          },
          %{
            name: "BOX",
            pattern: "<>",
            is_regex: false,
            line_number: 174,
            alias: nil,
          },
          %{
            name: "PLUS",
            pattern: "+",
            is_regex: false,
            line_number: 187,
            alias: nil,
          },
          %{
            name: "MINUS",
            pattern: "-",
            is_regex: false,
            line_number: 188,
            alias: nil,
          },
          %{
            name: "STAR",
            pattern: "*",
            is_regex: false,
            line_number: 189,
            alias: nil,
          },
          %{
            name: "SLASH",
            pattern: "/",
            is_regex: false,
            line_number: 190,
            alias: nil,
          },
          %{
            name: "AMPERSAND",
            pattern: "&",
            is_regex: false,
            line_number: 191,
            alias: nil,
          },
          %{
            name: "LESS_THAN",
            pattern: "<",
            is_regex: false,
            line_number: 192,
            alias: nil,
          },
          %{
            name: "GREATER_THAN",
            pattern: ">",
            is_regex: false,
            line_number: 193,
            alias: nil,
          },
          %{
            name: "EQUALS",
            pattern: "=",
            is_regex: false,
            line_number: 194,
            alias: nil,
          },
          %{
            name: "TICK",
            pattern: "'",
            is_regex: false,
            line_number: 195,
            alias: nil,
          },
          %{
            name: "PIPE",
            pattern: "|",
            is_regex: false,
            line_number: 196,
            alias: nil,
          },
          %{
            name: "LPAREN",
            pattern: "(",
            is_regex: false,
            line_number: 202,
            alias: nil,
          },
          %{
            name: "RPAREN",
            pattern: ")",
            is_regex: false,
            line_number: 203,
            alias: nil,
          },
          %{
            name: "LBRACKET",
            pattern: "[",
            is_regex: false,
            line_number: 204,
            alias: nil,
          },
          %{
            name: "RBRACKET",
            pattern: "]",
            is_regex: false,
            line_number: 205,
            alias: nil,
          },
          %{
            name: "SEMICOLON",
            pattern: ";",
            is_regex: false,
            line_number: 206,
            alias: nil,
          },
          %{
            name: "COMMA",
            pattern: ",",
            is_regex: false,
            line_number: 207,
            alias: nil,
          },
          %{
            name: "DOT",
            pattern: ".",
            is_regex: false,
            line_number: 208,
            alias: nil,
          },
          %{
            name: "COLON",
            pattern: ":",
            is_regex: false,
            line_number: 209,
            alias: nil,
          },
        ],
      keywords: ["abs", "access", "after", "alias", "all", "and", "architecture", "array", "assert", "attribute", "begin", "block", "body", "buffer", "bus", "case", "component", "configuration", "constant", "disconnect", "downto", "else", "elsif", "end", "entity", "exit", "file", "for", "function", "generate", "generic", "group", "guarded", "if", "impure", "in", "inout", "is", "label", "library", "linkage", "literal", "loop", "map", "mod", "nand", "new", "next", "nor", "not", "null", "of", "on", "open", "or", "others", "out", "package", "port", "postponed", "procedure", "process", "pure", "range", "record", "register", "reject", "rem", "report", "return", "rol", "ror", "select", "severity", "signal", "shared", "sla", "sll", "sra", "srl", "subtype", "then", "to", "transport", "type", "unaffected", "units", "until", "use", "variable", "wait", "when", "while", "with", "xnor", "xor"],
      mode: nil,
      escape_mode: "none",
      skip_definitions: [
          %{
            name: "COMMENT",
            pattern: "--[^\\n]*",
            is_regex: true,
            line_number: 53,
            alias: nil,
          },
          %{
            name: "WHITESPACE",
            pattern: "[ \\t\\r\\n]+",
            is_regex: true,
            line_number: 54,
            alias: nil,
          },
        ],
      reserved_keywords: [],
      error_definitions: [],
      groups: %{},
      case_sensitive: false,
      version: 0,
      case_insensitive: false,
    }
  end
end
