defmodule CodingAdventures.JavaLexer.Grammar.V14 do
  # AUTO-GENERATED FILE — DO NOT EDIT
  # Source: java14.tokens
  # Regenerate with: grammar-tools compile-tokens java14.tokens
  #
  # This file embeds a TokenGrammar as native Elixir data structures.
  # Call token_grammar/0 instead of reading and parsing the .tokens file.
  
  alias CodingAdventures.GrammarTools.TokenGrammar
  
  def token_grammar do
    %TokenGrammar{
      definitions: [
          %{
            name: "NAME",
            pattern: "[a-zA-Z_$][a-zA-Z0-9_$]*",
            is_regex: true,
            line_number: 134,
            alias: nil,
          },
          %{
            name: "BINARY_NUMBER",
            pattern: "0[bB][01][01_]*[01][lL]?",
            is_regex: true,
            line_number: 164,
            alias: "NUMBER",
          },
          %{
            name: "BINARY_SHORT",
            pattern: "0[bB][01][lL]?",
            is_regex: true,
            line_number: 165,
            alias: "NUMBER",
          },
          %{
            name: "HEX_NUMBER",
            pattern: "0[xX][0-9a-fA-F][0-9a-fA-F_]*[0-9a-fA-F][lL]?",
            is_regex: true,
            line_number: 166,
            alias: "NUMBER",
          },
          %{
            name: "HEX_SHORT",
            pattern: "0[xX][0-9a-fA-F][lL]?",
            is_regex: true,
            line_number: 167,
            alias: "NUMBER",
          },
          %{
            name: "OCTAL_NUMBER",
            pattern: "0[0-7_]*[0-7]+[lL]?",
            is_regex: true,
            line_number: 168,
            alias: "NUMBER",
          },
          %{
            name: "FLOAT_NUMBER",
            pattern: "[0-9][0-9_]*\\.[0-9_]*([eE][+-]?[0-9_]+)?[fFdD]?",
            is_regex: true,
            line_number: 169,
            alias: "NUMBER",
          },
          %{
            name: "LEADING_DOT_FLOAT",
            pattern: "\\.[0-9][0-9_]*([eE][+-]?[0-9_]+)?[fFdD]?",
            is_regex: true,
            line_number: 170,
            alias: "NUMBER",
          },
          %{
            name: "SCI_NUMBER",
            pattern: "[0-9][0-9_]*[eE][+-]?[0-9_]+[fFdD]?",
            is_regex: true,
            line_number: 171,
            alias: "NUMBER",
          },
          %{
            name: "LONG_NUMBER",
            pattern: "[0-9][0-9_]*[lL]",
            is_regex: true,
            line_number: 172,
            alias: "NUMBER",
          },
          %{
            name: "FLOAT_SUFFIX",
            pattern: "[0-9][0-9_]*[fFdD]",
            is_regex: true,
            line_number: 173,
            alias: "NUMBER",
          },
          %{
            name: "INT_NUMBER",
            pattern: "[0-9][0-9_]*",
            is_regex: true,
            line_number: 174,
            alias: "NUMBER",
          },
          %{
            name: "TEXT_BLOCK",
            pattern: "\"\"\"[ \\t]*\\n([^\"\\\\]|\\\\.|\"[^\"\\\\]|\"\"[^\"\\\\])*\"\"\"",
            is_regex: true,
            line_number: 229,
            alias: "STRING",
          },
          %{
            name: "STRING",
            pattern: "\"([^\"\\\\]|\\\\.)*\"",
            is_regex: true,
            line_number: 231,
            alias: nil,
          },
          %{
            name: "CHAR",
            pattern: "'([^'\\\\]|\\\\.)*'",
            is_regex: true,
            line_number: 232,
            alias: nil,
          },
          %{
            name: "ELLIPSIS",
            pattern: "...",
            is_regex: false,
            line_number: 263,
            alias: nil,
          },
          %{
            name: "ARROW",
            pattern: "->",
            is_regex: false,
            line_number: 264,
            alias: nil,
          },
          %{
            name: "DOUBLE_COLON",
            pattern: "::",
            is_regex: false,
            line_number: 265,
            alias: nil,
          },
          %{
            name: "UNSIGNED_RIGHT_SHIFT_EQUALS",
            pattern: ">>>=",
            is_regex: false,
            line_number: 266,
            alias: nil,
          },
          %{
            name: "UNSIGNED_RIGHT_SHIFT",
            pattern: ">>>",
            is_regex: false,
            line_number: 267,
            alias: nil,
          },
          %{
            name: "LEFT_SHIFT_EQUALS",
            pattern: "<<=",
            is_regex: false,
            line_number: 268,
            alias: nil,
          },
          %{
            name: "RIGHT_SHIFT_EQUALS",
            pattern: ">>=",
            is_regex: false,
            line_number: 269,
            alias: nil,
          },
          %{
            name: "EQUALS_EQUALS",
            pattern: "==",
            is_regex: false,
            line_number: 270,
            alias: nil,
          },
          %{
            name: "NOT_EQUALS",
            pattern: "!=",
            is_regex: false,
            line_number: 271,
            alias: nil,
          },
          %{
            name: "LESS_EQUALS",
            pattern: "<=",
            is_regex: false,
            line_number: 272,
            alias: nil,
          },
          %{
            name: "GREATER_EQUALS",
            pattern: ">=",
            is_regex: false,
            line_number: 273,
            alias: nil,
          },
          %{
            name: "AND_AND",
            pattern: "&&",
            is_regex: false,
            line_number: 274,
            alias: nil,
          },
          %{
            name: "OR_OR",
            pattern: "||",
            is_regex: false,
            line_number: 275,
            alias: nil,
          },
          %{
            name: "PLUS_PLUS",
            pattern: "++",
            is_regex: false,
            line_number: 276,
            alias: nil,
          },
          %{
            name: "MINUS_MINUS",
            pattern: "--",
            is_regex: false,
            line_number: 277,
            alias: nil,
          },
          %{
            name: "PLUS_EQUALS",
            pattern: "+=",
            is_regex: false,
            line_number: 278,
            alias: nil,
          },
          %{
            name: "MINUS_EQUALS",
            pattern: "-=",
            is_regex: false,
            line_number: 279,
            alias: nil,
          },
          %{
            name: "STAR_EQUALS",
            pattern: "*=",
            is_regex: false,
            line_number: 280,
            alias: nil,
          },
          %{
            name: "SLASH_EQUALS",
            pattern: "/=",
            is_regex: false,
            line_number: 281,
            alias: nil,
          },
          %{
            name: "PERCENT_EQUALS",
            pattern: "%=",
            is_regex: false,
            line_number: 282,
            alias: nil,
          },
          %{
            name: "AMPERSAND_EQUALS",
            pattern: "&=",
            is_regex: false,
            line_number: 283,
            alias: nil,
          },
          %{
            name: "PIPE_EQUALS",
            pattern: "|=",
            is_regex: false,
            line_number: 284,
            alias: nil,
          },
          %{
            name: "CARET_EQUALS",
            pattern: "^=",
            is_regex: false,
            line_number: 285,
            alias: nil,
          },
          %{
            name: "LEFT_SHIFT",
            pattern: "<<",
            is_regex: false,
            line_number: 286,
            alias: nil,
          },
          %{
            name: "RIGHT_SHIFT",
            pattern: ">>",
            is_regex: false,
            line_number: 287,
            alias: nil,
          },
          %{
            name: "AT",
            pattern: "@",
            is_regex: false,
            line_number: 297,
            alias: nil,
          },
          %{
            name: "EQUALS",
            pattern: "=",
            is_regex: false,
            line_number: 298,
            alias: nil,
          },
          %{
            name: "PLUS",
            pattern: "+",
            is_regex: false,
            line_number: 299,
            alias: nil,
          },
          %{
            name: "MINUS",
            pattern: "-",
            is_regex: false,
            line_number: 300,
            alias: nil,
          },
          %{
            name: "STAR",
            pattern: "*",
            is_regex: false,
            line_number: 301,
            alias: nil,
          },
          %{
            name: "SLASH",
            pattern: "/",
            is_regex: false,
            line_number: 302,
            alias: nil,
          },
          %{
            name: "PERCENT",
            pattern: "%",
            is_regex: false,
            line_number: 303,
            alias: nil,
          },
          %{
            name: "LESS_THAN",
            pattern: "<",
            is_regex: false,
            line_number: 304,
            alias: nil,
          },
          %{
            name: "GREATER_THAN",
            pattern: ">",
            is_regex: false,
            line_number: 305,
            alias: nil,
          },
          %{
            name: "BANG",
            pattern: "!",
            is_regex: false,
            line_number: 306,
            alias: nil,
          },
          %{
            name: "AMPERSAND",
            pattern: "&",
            is_regex: false,
            line_number: 307,
            alias: nil,
          },
          %{
            name: "PIPE",
            pattern: "|",
            is_regex: false,
            line_number: 308,
            alias: nil,
          },
          %{
            name: "CARET",
            pattern: "^",
            is_regex: false,
            line_number: 309,
            alias: nil,
          },
          %{
            name: "TILDE",
            pattern: "~",
            is_regex: false,
            line_number: 310,
            alias: nil,
          },
          %{
            name: "QUESTION",
            pattern: "?",
            is_regex: false,
            line_number: 311,
            alias: nil,
          },
          %{
            name: "LPAREN",
            pattern: "(",
            is_regex: false,
            line_number: 320,
            alias: nil,
          },
          %{
            name: "RPAREN",
            pattern: ")",
            is_regex: false,
            line_number: 321,
            alias: nil,
          },
          %{
            name: "LBRACE",
            pattern: "{",
            is_regex: false,
            line_number: 322,
            alias: nil,
          },
          %{
            name: "RBRACE",
            pattern: "}",
            is_regex: false,
            line_number: 323,
            alias: nil,
          },
          %{
            name: "LBRACKET",
            pattern: "[",
            is_regex: false,
            line_number: 324,
            alias: nil,
          },
          %{
            name: "RBRACKET",
            pattern: "]",
            is_regex: false,
            line_number: 325,
            alias: nil,
          },
          %{
            name: "SEMICOLON",
            pattern: ";",
            is_regex: false,
            line_number: 326,
            alias: nil,
          },
          %{
            name: "COMMA",
            pattern: ",",
            is_regex: false,
            line_number: 327,
            alias: nil,
          },
          %{
            name: "DOT",
            pattern: ".",
            is_regex: false,
            line_number: 328,
            alias: nil,
          },
          %{
            name: "COLON",
            pattern: ":",
            is_regex: false,
            line_number: 329,
            alias: nil,
          },
        ],
      keywords: ["abstract", "assert", "boolean", "break", "byte", "case", "catch", "char", "class", "continue", "default", "do", "double", "else", "enum", "extends", "final", "finally", "float", "for", "if", "implements", "import", "instanceof", "int", "interface", "long", "native", "new", "package", "private", "protected", "public", "return", "short", "static", "strictfp", "super", "switch", "synchronized", "this", "throw", "throws", "transient", "try", "void", "volatile", "while", "yield", "true", "false", "null"],
      mode: nil,
      escape_mode: nil,
      skip_definitions: [
          %{
            name: "WHITESPACE",
            pattern: "[ \\t\\r\\n\\v\\f]+",
            is_regex: true,
            line_number: 438,
            alias: nil,
          },
          %{
            name: "LINE_COMMENT",
            pattern: "\\/\\/[^\\n]*",
            is_regex: true,
            line_number: 439,
            alias: nil,
          },
          %{
            name: "BLOCK_COMMENT",
            pattern: "\\/\\*([^*]|\\*[^\\/])*\\*\\/",
            is_regex: true,
            line_number: 440,
            alias: nil,
          },
        ],
      reserved_keywords: ["const", "goto"],
      error_definitions: [
          %{
            name: "BAD_TEXT_BLOCK",
            pattern: "\"\"\"[ \\t]*\\n([^\"\\\\]|\\\\.|\"[^\"\\\\]|\"\"[^\"\\\\])*$",
            is_regex: true,
            line_number: 451,
            alias: nil,
          },
          %{
            name: "BAD_STRING",
            pattern: "\"[^\"]*$",
            is_regex: true,
            line_number: 452,
            alias: nil,
          },
          %{
            name: "BAD_CHAR",
            pattern: "'[^']*$",
            is_regex: true,
            line_number: 453,
            alias: nil,
          },
        ],
      groups: %{},
      layout_keywords: [],
      case_sensitive: true,
      version: 1,
      case_insensitive: false,
      start_mode: nil,
      transitions: [],
    }
  end
  end
