defmodule CodingAdventures.JavaLexer.Grammar.V1_1 do
  # AUTO-GENERATED FILE — DO NOT EDIT
  # Source: java1.1.tokens
  # Regenerate with: grammar-tools compile-tokens java1.1.tokens
  #
  # This file embeds a TokenGrammar as native Elixir data structures.
  # Call token_grammar/0 instead of reading and parsing the .tokens file.
  
  alias CodingAdventures.GrammarTools.TokenGrammar
  
  def token_grammar do
    %TokenGrammar{
      definitions: [
          %{
            name: "NAME",
            pattern: "[a-zA-Z_$][a-zA-Z0-9_$]*",
            is_regex: true,
            line_number: 75,
            alias: nil,
          },
          %{
            name: "HEX_NUMBER",
            pattern: "0[xX][0-9a-fA-F]+[lL]?",
            is_regex: true,
            line_number: 99,
            alias: "NUMBER",
          },
          %{
            name: "OCTAL_NUMBER",
            pattern: "0[0-7]+[lL]?",
            is_regex: true,
            line_number: 100,
            alias: "NUMBER",
          },
          %{
            name: "FLOAT_NUMBER",
            pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?[fFdD]?",
            is_regex: true,
            line_number: 101,
            alias: "NUMBER",
          },
          %{
            name: "LEADING_DOT_FLOAT",
            pattern: "\\.[0-9]+([eE][+-]?[0-9]+)?[fFdD]?",
            is_regex: true,
            line_number: 102,
            alias: "NUMBER",
          },
          %{
            name: "SCI_NUMBER",
            pattern: "[0-9]+[eE][+-]?[0-9]+[fFdD]?",
            is_regex: true,
            line_number: 103,
            alias: "NUMBER",
          },
          %{
            name: "LONG_NUMBER",
            pattern: "[0-9]+[lL]",
            is_regex: true,
            line_number: 104,
            alias: "NUMBER",
          },
          %{
            name: "FLOAT_SUFFIX",
            pattern: "[0-9]+[fFdD]",
            is_regex: true,
            line_number: 105,
            alias: "NUMBER",
          },
          %{
            name: "INT_NUMBER",
            pattern: "[0-9]+",
            is_regex: true,
            line_number: 106,
            alias: "NUMBER",
          },
          %{
            name: "STRING",
            pattern: "\"([^\"\\\\]|\\\\.)*\"",
            is_regex: true,
            line_number: 136,
            alias: nil,
          },
          %{
            name: "CHAR",
            pattern: "'([^'\\\\]|\\\\.)*'",
            is_regex: true,
            line_number: 137,
            alias: nil,
          },
          %{
            name: "UNSIGNED_RIGHT_SHIFT_EQUALS",
            pattern: ">>>=",
            is_regex: false,
            line_number: 150,
            alias: nil,
          },
          %{
            name: "UNSIGNED_RIGHT_SHIFT",
            pattern: ">>>",
            is_regex: false,
            line_number: 151,
            alias: nil,
          },
          %{
            name: "LEFT_SHIFT_EQUALS",
            pattern: "<<=",
            is_regex: false,
            line_number: 152,
            alias: nil,
          },
          %{
            name: "RIGHT_SHIFT_EQUALS",
            pattern: ">>=",
            is_regex: false,
            line_number: 153,
            alias: nil,
          },
          %{
            name: "EQUALS_EQUALS",
            pattern: "==",
            is_regex: false,
            line_number: 154,
            alias: nil,
          },
          %{
            name: "NOT_EQUALS",
            pattern: "!=",
            is_regex: false,
            line_number: 155,
            alias: nil,
          },
          %{
            name: "LESS_EQUALS",
            pattern: "<=",
            is_regex: false,
            line_number: 156,
            alias: nil,
          },
          %{
            name: "GREATER_EQUALS",
            pattern: ">=",
            is_regex: false,
            line_number: 157,
            alias: nil,
          },
          %{
            name: "AND_AND",
            pattern: "&&",
            is_regex: false,
            line_number: 158,
            alias: nil,
          },
          %{
            name: "OR_OR",
            pattern: "||",
            is_regex: false,
            line_number: 159,
            alias: nil,
          },
          %{
            name: "PLUS_PLUS",
            pattern: "++",
            is_regex: false,
            line_number: 160,
            alias: nil,
          },
          %{
            name: "MINUS_MINUS",
            pattern: "--",
            is_regex: false,
            line_number: 161,
            alias: nil,
          },
          %{
            name: "PLUS_EQUALS",
            pattern: "+=",
            is_regex: false,
            line_number: 162,
            alias: nil,
          },
          %{
            name: "MINUS_EQUALS",
            pattern: "-=",
            is_regex: false,
            line_number: 163,
            alias: nil,
          },
          %{
            name: "STAR_EQUALS",
            pattern: "*=",
            is_regex: false,
            line_number: 164,
            alias: nil,
          },
          %{
            name: "SLASH_EQUALS",
            pattern: "/=",
            is_regex: false,
            line_number: 165,
            alias: nil,
          },
          %{
            name: "PERCENT_EQUALS",
            pattern: "%=",
            is_regex: false,
            line_number: 166,
            alias: nil,
          },
          %{
            name: "AMPERSAND_EQUALS",
            pattern: "&=",
            is_regex: false,
            line_number: 167,
            alias: nil,
          },
          %{
            name: "PIPE_EQUALS",
            pattern: "|=",
            is_regex: false,
            line_number: 168,
            alias: nil,
          },
          %{
            name: "CARET_EQUALS",
            pattern: "^=",
            is_regex: false,
            line_number: 169,
            alias: nil,
          },
          %{
            name: "LEFT_SHIFT",
            pattern: "<<",
            is_regex: false,
            line_number: 170,
            alias: nil,
          },
          %{
            name: "RIGHT_SHIFT",
            pattern: ">>",
            is_regex: false,
            line_number: 171,
            alias: nil,
          },
          %{
            name: "EQUALS",
            pattern: "=",
            is_regex: false,
            line_number: 183,
            alias: nil,
          },
          %{
            name: "PLUS",
            pattern: "+",
            is_regex: false,
            line_number: 184,
            alias: nil,
          },
          %{
            name: "MINUS",
            pattern: "-",
            is_regex: false,
            line_number: 185,
            alias: nil,
          },
          %{
            name: "STAR",
            pattern: "*",
            is_regex: false,
            line_number: 186,
            alias: nil,
          },
          %{
            name: "SLASH",
            pattern: "/",
            is_regex: false,
            line_number: 187,
            alias: nil,
          },
          %{
            name: "PERCENT",
            pattern: "%",
            is_regex: false,
            line_number: 188,
            alias: nil,
          },
          %{
            name: "LESS_THAN",
            pattern: "<",
            is_regex: false,
            line_number: 189,
            alias: nil,
          },
          %{
            name: "GREATER_THAN",
            pattern: ">",
            is_regex: false,
            line_number: 190,
            alias: nil,
          },
          %{
            name: "BANG",
            pattern: "!",
            is_regex: false,
            line_number: 191,
            alias: nil,
          },
          %{
            name: "AMPERSAND",
            pattern: "&",
            is_regex: false,
            line_number: 192,
            alias: nil,
          },
          %{
            name: "PIPE",
            pattern: "|",
            is_regex: false,
            line_number: 193,
            alias: nil,
          },
          %{
            name: "CARET",
            pattern: "^",
            is_regex: false,
            line_number: 194,
            alias: nil,
          },
          %{
            name: "TILDE",
            pattern: "~",
            is_regex: false,
            line_number: 195,
            alias: nil,
          },
          %{
            name: "QUESTION",
            pattern: "?",
            is_regex: false,
            line_number: 196,
            alias: nil,
          },
          %{
            name: "LPAREN",
            pattern: "(",
            is_regex: false,
            line_number: 209,
            alias: nil,
          },
          %{
            name: "RPAREN",
            pattern: ")",
            is_regex: false,
            line_number: 210,
            alias: nil,
          },
          %{
            name: "LBRACE",
            pattern: "{",
            is_regex: false,
            line_number: 211,
            alias: nil,
          },
          %{
            name: "RBRACE",
            pattern: "}",
            is_regex: false,
            line_number: 212,
            alias: nil,
          },
          %{
            name: "LBRACKET",
            pattern: "[",
            is_regex: false,
            line_number: 213,
            alias: nil,
          },
          %{
            name: "RBRACKET",
            pattern: "]",
            is_regex: false,
            line_number: 214,
            alias: nil,
          },
          %{
            name: "SEMICOLON",
            pattern: ";",
            is_regex: false,
            line_number: 215,
            alias: nil,
          },
          %{
            name: "COMMA",
            pattern: ",",
            is_regex: false,
            line_number: 216,
            alias: nil,
          },
          %{
            name: "DOT",
            pattern: ".",
            is_regex: false,
            line_number: 217,
            alias: nil,
          },
          %{
            name: "COLON",
            pattern: ":",
            is_regex: false,
            line_number: 218,
            alias: nil,
          },
        ],
      keywords: ["abstract", "boolean", "break", "byte", "case", "catch", "char", "class", "continue", "default", "do", "double", "else", "extends", "final", "finally", "float", "for", "if", "implements", "import", "instanceof", "int", "interface", "long", "native", "new", "package", "private", "protected", "public", "return", "short", "static", "super", "switch", "synchronized", "this", "throw", "throws", "transient", "try", "void", "volatile", "while", "true", "false", "null"],
      mode: nil,
      escape_mode: nil,
      skip_definitions: [
          %{
            name: "WHITESPACE",
            pattern: "[ \\t\\r\\n\\v\\f]+",
            is_regex: true,
            line_number: 350,
            alias: nil,
          },
          %{
            name: "LINE_COMMENT",
            pattern: "\\/\\/[^\\n]*",
            is_regex: true,
            line_number: 351,
            alias: nil,
          },
          %{
            name: "BLOCK_COMMENT",
            pattern: "\\/\\*([^*]|\\*[^\\/])*\\*\\/",
            is_regex: true,
            line_number: 352,
            alias: nil,
          },
        ],
      reserved_keywords: ["const", "goto"],
      error_definitions: [
          %{
            name: "BAD_STRING",
            pattern: "\"[^\"]*$",
            is_regex: true,
            line_number: 363,
            alias: nil,
          },
          %{
            name: "BAD_CHAR",
            pattern: "'[^']*$",
            is_regex: true,
            line_number: 364,
            alias: nil,
          },
        ],
      groups: %{},
      layout_keywords: [],
      case_sensitive: true,
      version: 1,
      case_insensitive: false,
      start_mode: nil,
      transitions: [],
    }
  end
  end
