defmodule CodingAdventures.JavaLexer.Grammar.V7 do
  # AUTO-GENERATED FILE — DO NOT EDIT
  # Source: java7.tokens
  # Regenerate with: grammar-tools compile-tokens java7.tokens
  #
  # This file embeds a TokenGrammar as native Elixir data structures.
  # Call token_grammar/0 instead of reading and parsing the .tokens file.
  
  alias CodingAdventures.GrammarTools.TokenGrammar
  
  def token_grammar do
    %TokenGrammar{
      definitions: [
          %{
            name: "NAME",
            pattern: "[a-zA-Z_$][a-zA-Z0-9_$]*",
            is_regex: true,
            line_number: 90,
            alias: nil,
          },
          %{
            name: "BINARY_NUMBER",
            pattern: "0[bB][01](_*[01])*[lL]?",
            is_regex: true,
            line_number: 138,
            alias: "NUMBER",
          },
          %{
            name: "HEX_NUMBER",
            pattern: "0[xX][0-9a-fA-F](_*[0-9a-fA-F])*[lL]?",
            is_regex: true,
            line_number: 139,
            alias: "NUMBER",
          },
          %{
            name: "OCTAL_NUMBER",
            pattern: "0[0-7](_*[0-7])*[lL]?",
            is_regex: true,
            line_number: 140,
            alias: "NUMBER",
          },
          %{
            name: "FLOAT_NUMBER",
            pattern: "[0-9](_*[0-9])*\\.[0-9](_*[0-9])*([eE][+-]?[0-9](_*[0-9])*)?[fFdD]?",
            is_regex: true,
            line_number: 141,
            alias: "NUMBER",
          },
          %{
            name: "LEADING_DOT_FLOAT",
            pattern: "\\.[0-9](_*[0-9])*([eE][+-]?[0-9](_*[0-9])*)?[fFdD]?",
            is_regex: true,
            line_number: 142,
            alias: "NUMBER",
          },
          %{
            name: "SCI_NUMBER",
            pattern: "[0-9](_*[0-9])*[eE][+-]?[0-9](_*[0-9])*[fFdD]?",
            is_regex: true,
            line_number: 143,
            alias: "NUMBER",
          },
          %{
            name: "LONG_NUMBER",
            pattern: "[0-9](_*[0-9])*[lL]",
            is_regex: true,
            line_number: 144,
            alias: "NUMBER",
          },
          %{
            name: "FLOAT_SUFFIX",
            pattern: "[0-9](_*[0-9])*[fFdD]",
            is_regex: true,
            line_number: 145,
            alias: "NUMBER",
          },
          %{
            name: "INT_NUMBER",
            pattern: "[0-9](_*[0-9])*",
            is_regex: true,
            line_number: 146,
            alias: "NUMBER",
          },
          %{
            name: "STRING",
            pattern: "\"([^\"\\\\]|\\\\.)*\"",
            is_regex: true,
            line_number: 165,
            alias: nil,
          },
          %{
            name: "CHAR",
            pattern: "'([^'\\\\]|\\\\.)*'",
            is_regex: true,
            line_number: 166,
            alias: nil,
          },
          %{
            name: "ELLIPSIS",
            pattern: "...",
            is_regex: false,
            line_number: 187,
            alias: nil,
          },
          %{
            name: "UNSIGNED_RIGHT_SHIFT_EQUALS",
            pattern: ">>>=",
            is_regex: false,
            line_number: 188,
            alias: nil,
          },
          %{
            name: "UNSIGNED_RIGHT_SHIFT",
            pattern: ">>>",
            is_regex: false,
            line_number: 189,
            alias: nil,
          },
          %{
            name: "LEFT_SHIFT_EQUALS",
            pattern: "<<=",
            is_regex: false,
            line_number: 190,
            alias: nil,
          },
          %{
            name: "RIGHT_SHIFT_EQUALS",
            pattern: ">>=",
            is_regex: false,
            line_number: 191,
            alias: nil,
          },
          %{
            name: "EQUALS_EQUALS",
            pattern: "==",
            is_regex: false,
            line_number: 192,
            alias: nil,
          },
          %{
            name: "NOT_EQUALS",
            pattern: "!=",
            is_regex: false,
            line_number: 193,
            alias: nil,
          },
          %{
            name: "LESS_EQUALS",
            pattern: "<=",
            is_regex: false,
            line_number: 194,
            alias: nil,
          },
          %{
            name: "GREATER_EQUALS",
            pattern: ">=",
            is_regex: false,
            line_number: 195,
            alias: nil,
          },
          %{
            name: "AND_AND",
            pattern: "&&",
            is_regex: false,
            line_number: 196,
            alias: nil,
          },
          %{
            name: "OR_OR",
            pattern: "||",
            is_regex: false,
            line_number: 197,
            alias: nil,
          },
          %{
            name: "PLUS_PLUS",
            pattern: "++",
            is_regex: false,
            line_number: 198,
            alias: nil,
          },
          %{
            name: "MINUS_MINUS",
            pattern: "--",
            is_regex: false,
            line_number: 199,
            alias: nil,
          },
          %{
            name: "PLUS_EQUALS",
            pattern: "+=",
            is_regex: false,
            line_number: 200,
            alias: nil,
          },
          %{
            name: "MINUS_EQUALS",
            pattern: "-=",
            is_regex: false,
            line_number: 201,
            alias: nil,
          },
          %{
            name: "STAR_EQUALS",
            pattern: "*=",
            is_regex: false,
            line_number: 202,
            alias: nil,
          },
          %{
            name: "SLASH_EQUALS",
            pattern: "/=",
            is_regex: false,
            line_number: 203,
            alias: nil,
          },
          %{
            name: "PERCENT_EQUALS",
            pattern: "%=",
            is_regex: false,
            line_number: 204,
            alias: nil,
          },
          %{
            name: "AMPERSAND_EQUALS",
            pattern: "&=",
            is_regex: false,
            line_number: 205,
            alias: nil,
          },
          %{
            name: "PIPE_EQUALS",
            pattern: "|=",
            is_regex: false,
            line_number: 206,
            alias: nil,
          },
          %{
            name: "CARET_EQUALS",
            pattern: "^=",
            is_regex: false,
            line_number: 207,
            alias: nil,
          },
          %{
            name: "LEFT_SHIFT",
            pattern: "<<",
            is_regex: false,
            line_number: 208,
            alias: nil,
          },
          %{
            name: "RIGHT_SHIFT",
            pattern: ">>",
            is_regex: false,
            line_number: 209,
            alias: nil,
          },
          %{
            name: "AT",
            pattern: "@",
            is_regex: false,
            line_number: 229,
            alias: nil,
          },
          %{
            name: "EQUALS",
            pattern: "=",
            is_regex: false,
            line_number: 230,
            alias: nil,
          },
          %{
            name: "PLUS",
            pattern: "+",
            is_regex: false,
            line_number: 231,
            alias: nil,
          },
          %{
            name: "MINUS",
            pattern: "-",
            is_regex: false,
            line_number: 232,
            alias: nil,
          },
          %{
            name: "STAR",
            pattern: "*",
            is_regex: false,
            line_number: 233,
            alias: nil,
          },
          %{
            name: "SLASH",
            pattern: "/",
            is_regex: false,
            line_number: 234,
            alias: nil,
          },
          %{
            name: "PERCENT",
            pattern: "%",
            is_regex: false,
            line_number: 235,
            alias: nil,
          },
          %{
            name: "LESS_THAN",
            pattern: "<",
            is_regex: false,
            line_number: 236,
            alias: nil,
          },
          %{
            name: "GREATER_THAN",
            pattern: ">",
            is_regex: false,
            line_number: 237,
            alias: nil,
          },
          %{
            name: "BANG",
            pattern: "!",
            is_regex: false,
            line_number: 238,
            alias: nil,
          },
          %{
            name: "AMPERSAND",
            pattern: "&",
            is_regex: false,
            line_number: 239,
            alias: nil,
          },
          %{
            name: "PIPE",
            pattern: "|",
            is_regex: false,
            line_number: 240,
            alias: nil,
          },
          %{
            name: "CARET",
            pattern: "^",
            is_regex: false,
            line_number: 241,
            alias: nil,
          },
          %{
            name: "TILDE",
            pattern: "~",
            is_regex: false,
            line_number: 242,
            alias: nil,
          },
          %{
            name: "QUESTION",
            pattern: "?",
            is_regex: false,
            line_number: 243,
            alias: nil,
          },
          %{
            name: "LPAREN",
            pattern: "(",
            is_regex: false,
            line_number: 251,
            alias: nil,
          },
          %{
            name: "RPAREN",
            pattern: ")",
            is_regex: false,
            line_number: 252,
            alias: nil,
          },
          %{
            name: "LBRACE",
            pattern: "{",
            is_regex: false,
            line_number: 253,
            alias: nil,
          },
          %{
            name: "RBRACE",
            pattern: "}",
            is_regex: false,
            line_number: 254,
            alias: nil,
          },
          %{
            name: "LBRACKET",
            pattern: "[",
            is_regex: false,
            line_number: 255,
            alias: nil,
          },
          %{
            name: "RBRACKET",
            pattern: "]",
            is_regex: false,
            line_number: 256,
            alias: nil,
          },
          %{
            name: "SEMICOLON",
            pattern: ";",
            is_regex: false,
            line_number: 257,
            alias: nil,
          },
          %{
            name: "COMMA",
            pattern: ",",
            is_regex: false,
            line_number: 258,
            alias: nil,
          },
          %{
            name: "DOT",
            pattern: ".",
            is_regex: false,
            line_number: 259,
            alias: nil,
          },
          %{
            name: "COLON",
            pattern: ":",
            is_regex: false,
            line_number: 260,
            alias: nil,
          },
        ],
      keywords: ["abstract", "assert", "boolean", "break", "byte", "case", "catch", "char", "class", "continue", "default", "do", "double", "else", "enum", "extends", "final", "finally", "float", "for", "if", "implements", "import", "instanceof", "int", "interface", "long", "native", "new", "package", "private", "protected", "public", "return", "short", "static", "strictfp", "super", "switch", "synchronized", "this", "throw", "throws", "transient", "try", "void", "volatile", "while", "true", "false", "null"],
      mode: nil,
      escape_mode: nil,
      skip_definitions: [
          %{
            name: "WHITESPACE",
            pattern: "[ \\t\\r\\n\\v\\f]+",
            is_regex: true,
            line_number: 367,
            alias: nil,
          },
          %{
            name: "LINE_COMMENT",
            pattern: "\\/\\/[^\\n]*",
            is_regex: true,
            line_number: 368,
            alias: nil,
          },
          %{
            name: "BLOCK_COMMENT",
            pattern: "\\/\\*([^*]|\\*[^\\/])*\\*\\/",
            is_regex: true,
            line_number: 369,
            alias: nil,
          },
        ],
      reserved_keywords: ["const", "goto"],
      error_definitions: [
          %{
            name: "BAD_STRING",
            pattern: "\"[^\"]*$",
            is_regex: true,
            line_number: 380,
            alias: nil,
          },
          %{
            name: "BAD_CHAR",
            pattern: "'[^']*$",
            is_regex: true,
            line_number: 381,
            alias: nil,
          },
        ],
      groups: %{},
      layout_keywords: [],
      case_sensitive: true,
      version: 1,
      case_insensitive: false,
      start_mode: nil,
      transitions: [],
    }
  end
  end
