-- AUTO-GENERATED FILE — DO NOT EDIT
-- Source: css.tokens
-- Regenerate with: grammar-tools compile-tokens css.tokens
--
-- This file embeds a TokenGrammar as native Lua data structures.
-- Call token_grammar() instead of reading and parsing the .tokens file.

local gt = require("coding_adventures.grammar_tools")

local function token_grammar()
  local g = gt.TokenGrammar.new()
  g.definitions = {
        {
          name="STRING_DQ",
          pattern="\"([^\"\\\\\\n]|\\\\.)*\"",
          is_regex=true,
          line_number=67,
          alias="STRING",
        },
        {
          name="STRING_SQ",
          pattern="'([^'\\\\\\n]|\\\\.)*'",
          is_regex=true,
          line_number=68,
          alias="STRING",
        },
        {
          name="DIMENSION",
          pattern="-?[0-9]*\\.?[0-9]+([eE][+-]?[0-9]+)?[a-zA-Z]+",
          is_regex=true,
          line_number=94,
          alias="",
        },
        {
          name="PERCENTAGE",
          pattern="-?[0-9]*\\.?[0-9]+([eE][+-]?[0-9]+)?%",
          is_regex=true,
          line_number=95,
          alias="",
        },
        {
          name="NUMBER",
          pattern="-?[0-9]*\\.?[0-9]+([eE][+-]?[0-9]+)?",
          is_regex=true,
          line_number=96,
          alias="",
        },
        {
          name="HASH",
          pattern="#[a-zA-Z0-9_-]+",
          is_regex=true,
          line_number=109,
          alias="",
        },
        {
          name="AT_KEYWORD",
          pattern="@-?[a-zA-Z][a-zA-Z0-9-]*",
          is_regex=true,
          line_number=123,
          alias="",
        },
        {
          name="URL_TOKEN",
          pattern="url\\([^)'\"]*\\)",
          is_regex=true,
          line_number=136,
          alias="",
        },
        {
          name="FUNCTION",
          pattern="-?[a-zA-Z_][a-zA-Z0-9_-]*\\(",
          is_regex=true,
          line_number=149,
          alias="",
        },
        {
          name="CDO",
          pattern="<!--",
          is_regex=false,
          line_number=162,
          alias="",
        },
        {
          name="CDC",
          pattern="-->",
          is_regex=false,
          line_number=163,
          alias="",
        },
        {
          name="UNICODE_RANGE",
          pattern="[Uu]\\+[0-9a-fA-F?]{1,6}(-[0-9a-fA-F]{1,6})?",
          is_regex=true,
          line_number=190,
          alias="",
        },
        {
          name="CUSTOM_PROPERTY",
          pattern="--[a-zA-Z_][a-zA-Z0-9_-]*",
          is_regex=true,
          line_number=192,
          alias="",
        },
        {
          name="IDENT",
          pattern="-?[a-zA-Z_][a-zA-Z0-9_-]*",
          is_regex=true,
          line_number=193,
          alias="",
        },
        {
          name="COLON_COLON",
          pattern="::",
          is_regex=false,
          line_number=202,
          alias="",
        },
        {
          name="TILDE_EQUALS",
          pattern="~=",
          is_regex=false,
          line_number=203,
          alias="",
        },
        {
          name="PIPE_EQUALS",
          pattern="|=",
          is_regex=false,
          line_number=204,
          alias="",
        },
        {
          name="CARET_EQUALS",
          pattern="^=",
          is_regex=false,
          line_number=205,
          alias="",
        },
        {
          name="DOLLAR_EQUALS",
          pattern="$=",
          is_regex=false,
          line_number=206,
          alias="",
        },
        {
          name="STAR_EQUALS",
          pattern="*=",
          is_regex=false,
          line_number=207,
          alias="",
        },
        {
          name="LBRACE",
          pattern="{",
          is_regex=false,
          line_number=216,
          alias="",
        },
        {
          name="RBRACE",
          pattern="}",
          is_regex=false,
          line_number=217,
          alias="",
        },
        {
          name="LPAREN",
          pattern="(",
          is_regex=false,
          line_number=218,
          alias="",
        },
        {
          name="RPAREN",
          pattern=")",
          is_regex=false,
          line_number=219,
          alias="",
        },
        {
          name="LBRACKET",
          pattern="[",
          is_regex=false,
          line_number=220,
          alias="",
        },
        {
          name="RBRACKET",
          pattern="]",
          is_regex=false,
          line_number=221,
          alias="",
        },
        {
          name="SEMICOLON",
          pattern=";",
          is_regex=false,
          line_number=222,
          alias="",
        },
        {
          name="COLON",
          pattern=":",
          is_regex=false,
          line_number=223,
          alias="",
        },
        {
          name="COMMA",
          pattern=",",
          is_regex=false,
          line_number=224,
          alias="",
        },
        {
          name="DOT",
          pattern=".",
          is_regex=false,
          line_number=225,
          alias="",
        },
        {
          name="PLUS",
          pattern="+",
          is_regex=false,
          line_number=226,
          alias="",
        },
        {
          name="GREATER",
          pattern=">",
          is_regex=false,
          line_number=227,
          alias="",
        },
        {
          name="TILDE",
          pattern="~",
          is_regex=false,
          line_number=228,
          alias="",
        },
        {
          name="STAR",
          pattern="*",
          is_regex=false,
          line_number=229,
          alias="",
        },
        {
          name="PIPE",
          pattern="|",
          is_regex=false,
          line_number=230,
          alias="",
        },
        {
          name="BANG",
          pattern="!",
          is_regex=false,
          line_number=231,
          alias="",
        },
        {
          name="SLASH",
          pattern="/",
          is_regex=false,
          line_number=232,
          alias="",
        },
        {
          name="EQUALS",
          pattern="=",
          is_regex=false,
          line_number=233,
          alias="",
        },
        {
          name="AMPERSAND",
          pattern="&",
          is_regex=false,
          line_number=234,
          alias="",
        },
        {
          name="MINUS",
          pattern="-",
          is_regex=false,
          line_number=235,
          alias="",
        },
      }
  g.keywords = {}
  g.mode = ""
  g.escape_mode = "none"
  g.skip_definitions = {
        {
          name="COMMENT",
          pattern="\\/\\*[\\s\\S]*?\\*\\/",
          is_regex=true,
          line_number=51,
          alias="",
        },
        {
          name="WHITESPACE",
          pattern="[ \\t\\r\\n]+",
          is_regex=true,
          line_number=52,
          alias="",
        },
      }
  g.reserved_keywords = {}
  g.context_keywords = {}
  g.layout_keywords = {}
  g.soft_keywords = {}
  g.error_definitions = {
        {
          name="BAD_STRING",
          pattern="\"[^\"]*$",
          is_regex=true,
          line_number=251,
          alias="",
        },
        {
          name="BAD_URL",
          pattern="url\\([^)]*$",
          is_regex=true,
          line_number=252,
          alias="",
        },
      }
  g.groups = {}
  g.case_sensitive = true
  g.version = 0
  g.case_insensitive = false
  return g
end

return { token_grammar = token_grammar }
