// AUTO-GENERATED FILE — DO NOT EDIT
// Source: scilab.tokens
// Regenerate with: grammar-tools compile-tokens scilab.tokens
//
// This file embeds a TokenGrammar as native Rust data structures.
// Call `token_grammar()` instead of reading and parsing the .tokens file.

#[allow(unused_imports)]
use grammar_tools::token_grammar::{ModeTransition, PatternGroup, TokenDefinition, TokenGrammar, TransitionAction};
#[allow(unused_imports)]
use std::collections::HashMap;

pub fn token_grammar() -> TokenGrammar {
    TokenGrammar {
        definitions: vec![
            TokenDefinition {
                name: r#"ELEM_POW"#.to_string(),
                pattern: r#".^"#.to_string(),
                is_regex: false,
                line_number: 105,
                alias: None,
            },
            TokenDefinition {
                name: r#"ELEM_MUL"#.to_string(),
                pattern: r#".*"#.to_string(),
                is_regex: false,
                line_number: 106,
                alias: None,
            },
            TokenDefinition {
                name: r#"ELEM_RDIV"#.to_string(),
                pattern: r#"./"#.to_string(),
                is_regex: false,
                line_number: 107,
                alias: None,
            },
            TokenDefinition {
                name: r#"ELEM_LDIV"#.to_string(),
                pattern: r#"\.\\"#.to_string(),
                is_regex: true,
                line_number: 108,
                alias: None,
            },
            TokenDefinition {
                name: r#"ELEM_TRANSPOSE"#.to_string(),
                pattern: r#".'"#.to_string(),
                is_regex: false,
                line_number: 109,
                alias: None,
            },
            TokenDefinition {
                name: r#"EQ_EQ"#.to_string(),
                pattern: r#"=="#.to_string(),
                is_regex: false,
                line_number: 111,
                alias: None,
            },
            TokenDefinition {
                name: r#"NE"#.to_string(),
                pattern: r#"~="#.to_string(),
                is_regex: false,
                line_number: 112,
                alias: None,
            },
            TokenDefinition {
                name: r#"NE_ALT"#.to_string(),
                pattern: r#"<>"#.to_string(),
                is_regex: false,
                line_number: 121,
                alias: None,
            },
            TokenDefinition {
                name: r#"LE"#.to_string(),
                pattern: r#"<="#.to_string(),
                is_regex: false,
                line_number: 123,
                alias: None,
            },
            TokenDefinition {
                name: r#"GE"#.to_string(),
                pattern: r#">="#.to_string(),
                is_regex: false,
                line_number: 124,
                alias: None,
            },
            TokenDefinition {
                name: r#"AND_AND"#.to_string(),
                pattern: r#"&&"#.to_string(),
                is_regex: false,
                line_number: 125,
                alias: None,
            },
            TokenDefinition {
                name: r#"OR_OR"#.to_string(),
                pattern: r#"||"#.to_string(),
                is_regex: false,
                line_number: 126,
                alias: None,
            },
            TokenDefinition {
                name: r#"STRING_PLACEHOLDER"#.to_string(),
                pattern: r#"`[0-9]+`"#.to_string(),
                is_regex: true,
                line_number: 166,
                alias: None,
            },
            TokenDefinition {
                name: r#"DQ_STRING"#.to_string(),
                pattern: r#""([^"]|"")*""#.to_string(),
                is_regex: true,
                line_number: 167,
                alias: None,
            },
            TokenDefinition {
                name: r#"PERCENT_CONST"#.to_string(),
                pattern: r#"%(inf|nan|eps|pi|i|e|t|f)"#.to_string(),
                is_regex: true,
                line_number: 184,
                alias: None,
            },
            TokenDefinition {
                name: r#"DOLLAR"#.to_string(),
                pattern: r#"$"#.to_string(),
                is_regex: false,
                line_number: 194,
                alias: None,
            },
            TokenDefinition {
                name: r#"NUMBER"#.to_string(),
                pattern: r#"([0-9]+(\.[0-9]+)?|\.[0-9]+)([eE][+-]?[0-9]+)?"#.to_string(),
                is_regex: true,
                line_number: 204,
                alias: None,
            },
            TokenDefinition {
                name: r#"NAME"#.to_string(),
                pattern: r#"[A-Za-z_][A-Za-z0-9_]*"#.to_string(),
                is_regex: true,
                line_number: 246,
                alias: None,
            },
            TokenDefinition {
                name: r#"TRANSPOSE"#.to_string(),
                pattern: r#"'"#.to_string(),
                is_regex: false,
                line_number: 277,
                alias: None,
            },
            TokenDefinition {
                name: r#"PLUS"#.to_string(),
                pattern: r#"+"#.to_string(),
                is_regex: false,
                line_number: 278,
                alias: None,
            },
            TokenDefinition {
                name: r#"MINUS"#.to_string(),
                pattern: r#"-"#.to_string(),
                is_regex: false,
                line_number: 279,
                alias: None,
            },
            TokenDefinition {
                name: r#"STAR"#.to_string(),
                pattern: r#"*"#.to_string(),
                is_regex: false,
                line_number: 280,
                alias: None,
            },
            TokenDefinition {
                name: r#"SLASH"#.to_string(),
                pattern: r#"/"#.to_string(),
                is_regex: false,
                line_number: 281,
                alias: None,
            },
            TokenDefinition {
                name: r#"BACKSLASH"#.to_string(),
                pattern: r#"\\"#.to_string(),
                is_regex: true,
                line_number: 282,
                alias: None,
            },
            TokenDefinition {
                name: r#"CARET"#.to_string(),
                pattern: r#"^"#.to_string(),
                is_regex: false,
                line_number: 283,
                alias: None,
            },
            TokenDefinition {
                name: r#"LT"#.to_string(),
                pattern: r#"<"#.to_string(),
                is_regex: false,
                line_number: 284,
                alias: None,
            },
            TokenDefinition {
                name: r#"GT"#.to_string(),
                pattern: r#">"#.to_string(),
                is_regex: false,
                line_number: 285,
                alias: None,
            },
            TokenDefinition {
                name: r#"EQ"#.to_string(),
                pattern: r#"="#.to_string(),
                is_regex: false,
                line_number: 286,
                alias: None,
            },
            TokenDefinition {
                name: r#"TILDE"#.to_string(),
                pattern: r#"~"#.to_string(),
                is_regex: false,
                line_number: 287,
                alias: None,
            },
            TokenDefinition {
                name: r#"AMP"#.to_string(),
                pattern: r#"&"#.to_string(),
                is_regex: false,
                line_number: 288,
                alias: None,
            },
            TokenDefinition {
                name: r#"PIPE"#.to_string(),
                pattern: r#"|"#.to_string(),
                is_regex: false,
                line_number: 289,
                alias: None,
            },
            TokenDefinition {
                name: r#"COLON"#.to_string(),
                pattern: r#":"#.to_string(),
                is_regex: false,
                line_number: 290,
                alias: None,
            },
            TokenDefinition {
                name: r#"DOT"#.to_string(),
                pattern: r#"."#.to_string(),
                is_regex: false,
                line_number: 291,
                alias: None,
            },
            TokenDefinition {
                name: r#"LPAREN"#.to_string(),
                pattern: r#"("#.to_string(),
                is_regex: false,
                line_number: 292,
                alias: None,
            },
            TokenDefinition {
                name: r#"RPAREN"#.to_string(),
                pattern: r#")"#.to_string(),
                is_regex: false,
                line_number: 293,
                alias: None,
            },
            TokenDefinition {
                name: r#"LBRACKET"#.to_string(),
                pattern: r#"["#.to_string(),
                is_regex: false,
                line_number: 294,
                alias: None,
            },
            TokenDefinition {
                name: r#"RBRACKET"#.to_string(),
                pattern: r#"]"#.to_string(),
                is_regex: false,
                line_number: 295,
                alias: None,
            },
            TokenDefinition {
                name: r#"LBRACE"#.to_string(),
                pattern: r#"{"#.to_string(),
                is_regex: false,
                line_number: 296,
                alias: None,
            },
            TokenDefinition {
                name: r#"RBRACE"#.to_string(),
                pattern: r#"}"#.to_string(),
                is_regex: false,
                line_number: 297,
                alias: None,
            },
            TokenDefinition {
                name: r#"COMMA"#.to_string(),
                pattern: r#","#.to_string(),
                is_regex: false,
                line_number: 298,
                alias: None,
            },
            TokenDefinition {
                name: r#"SEMICOLON"#.to_string(),
                pattern: r#";"#.to_string(),
                is_regex: false,
                line_number: 299,
                alias: None,
            },
            TokenDefinition {
                name: r#"NEWLINE"#.to_string(),
                pattern: r#"\r?\n"#.to_string(),
                is_regex: true,
                line_number: 313,
                alias: None,
            },
        ],
        keywords: vec![r#"if"#.to_string(), r#"elseif"#.to_string(), r#"else"#.to_string(), r#"end"#.to_string(), r#"select"#.to_string(), r#"case"#.to_string(), r#"then"#.to_string(), r#"while"#.to_string(), r#"do"#.to_string(), r#"for"#.to_string(), r#"break"#.to_string(), r#"continue"#.to_string(), r#"function"#.to_string(), r#"endfunction"#.to_string()],
        mode: None,
        skip_definitions: vec![
            TokenDefinition {
                name: r#"WHITESPACE"#.to_string(),
                pattern: r#"[ \t]+"#.to_string(),
                is_regex: true,
                line_number: 327,
                alias: None,
            },
            TokenDefinition {
                name: r#"LINE_COMMENT"#.to_string(),
                pattern: r#"\/\/[^\n]*"#.to_string(),
                is_regex: true,
                line_number: 328,
                alias: None,
            },
            TokenDefinition {
                name: r#"BLOCK_COMMENT"#.to_string(),
                pattern: r#"\/\*[\s\S]*?\*\/"#.to_string(),
                is_regex: true,
                line_number: 329,
                alias: None,
            },
        ],
        reserved_keywords: vec![],
        escapes: None,
        error_definitions: vec![
            TokenDefinition {
                name: r#"UNKNOWN"#.to_string(),
                pattern: r#"."#.to_string(),
                is_regex: true,
                line_number: 336,
                alias: None,
            },
        ],
        groups: HashMap::new(),
        case_sensitive: true,
        version: 1,
        case_insensitive: false,
        context_keywords: vec![],
        soft_keywords: vec![],
        layout_keywords: vec![],
        start_mode: None,
        transitions: vec![],
    }
}
