cd ../../../packages/typescript/indexeddb && npm install
cd ../../../packages/typescript/store && npm install
cd ../../../packages/typescript/ui-components && npm install
cd ../../../programs/typescript/engram-app && npm install
npx vitest run
