cd ../../../packages/typescript/directed-graph && npm install --quiet
cd ../../../packages/typescript/grammar-tools && npm install --quiet
cd ../../../packages/typescript/lexer && npm install --quiet
cd ../../../packages/typescript/state-machine && npm install --quiet
cd ../../../packages/typescript/parser && npm install --quiet
cd ../../../packages/typescript/sql-lexer && npm install --quiet
cd ../../../packages/typescript/sql-parser && npm install --quiet
cd ../../../packages/typescript/sql-execution-engine && npm install --quiet
cd ../../../packages/typescript/storage && npm install --quiet
cd ../../../packages/typescript/indexeddb && npm install --quiet
cd ../../../packages/typescript/store && npm install --quiet
cd ../../../packages/typescript/pixel-container && npm install --quiet
cd ../../../packages/typescript/paint-instructions && npm install --quiet
cd ../../../packages/typescript/paint-vm && npm install --quiet
cd ../../../packages/typescript/paint-vm-canvas && npm install --quiet
cd ../../../packages/typescript/ui-components && npm install --quiet
npm install --quiet
npx vitest run
