cd ../../../packages/typescript/indexeddb && npm install --quiet
cd ../../../packages/typescript/store && npm install --quiet
cd ../../../packages/typescript/ui-components && npm install --quiet
npm install --quiet
npx vitest run
