// Code generated by grammar-tools. DO NOT EDIT.
// Source: sql.grammar
// Regenerate with: grammar-tools compile-grammar sql.grammar
//
// This file embeds a ParserGrammar as native Go data structures.
// Downstream packages use ParserGrammarData directly instead of reading
// and parsing the .grammar file at runtime.

package sqlparser

import gt "github.com/adhithyan15/coding-adventures/code/packages/go/grammar-tools"

// ParserGrammarData is the embedded parser grammar.
var ParserGrammarData = &gt.ParserGrammar{
	Version: 2,
	Rules: []gt.GrammarRule{
		{Name: `program`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.RuleReference{Name: `statement`, IsToken: false},
			gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `;`},
				gt.RuleReference{Name: `statement`, IsToken: false},
			}}},
			gt.Optional{Element: gt.Literal{Value: `;`}},
		}}, LineNumber: 10},
		{Name: `statement`, Body: gt.Alternation{Choices: []gt.GrammarElement{
			gt.RuleReference{Name: `query_stmt`, IsToken: false},
			gt.RuleReference{Name: `insert_stmt`, IsToken: false},
			gt.RuleReference{Name: `replace_stmt`, IsToken: false},
			gt.RuleReference{Name: `update_stmt`, IsToken: false},
			gt.RuleReference{Name: `delete_stmt`, IsToken: false},
			gt.RuleReference{Name: `create_table_stmt`, IsToken: false},
			gt.RuleReference{Name: `drop_table_stmt`, IsToken: false},
			gt.RuleReference{Name: `alter_table_stmt`, IsToken: false},
			gt.RuleReference{Name: `create_index_stmt`, IsToken: false},
			gt.RuleReference{Name: `drop_index_stmt`, IsToken: false},
			gt.RuleReference{Name: `create_view_stmt`, IsToken: false},
			gt.RuleReference{Name: `drop_view_stmt`, IsToken: false},
			gt.RuleReference{Name: `create_trigger_stmt`, IsToken: false},
			gt.RuleReference{Name: `drop_trigger_stmt`, IsToken: false},
			gt.RuleReference{Name: `begin_stmt`, IsToken: false},
			gt.RuleReference{Name: `commit_stmt`, IsToken: false},
			gt.RuleReference{Name: `rollback_to_stmt`, IsToken: false},
			gt.RuleReference{Name: `rollback_stmt`, IsToken: false},
			gt.RuleReference{Name: `savepoint_stmt`, IsToken: false},
			gt.RuleReference{Name: `release_stmt`, IsToken: false},
			gt.RuleReference{Name: `attach_stmt`, IsToken: false},
			gt.RuleReference{Name: `detach_stmt`, IsToken: false},
		}}, LineNumber: 12},
		{Name: `attach_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `ATTACH`},
			gt.Optional{Element: gt.Literal{Value: `DATABASE`}},
			gt.RuleReference{Name: `expr`, IsToken: false},
			gt.Literal{Value: `AS`},
			gt.RuleReference{Name: `NAME`, IsToken: true},
		}}, LineNumber: 25},
		{Name: `detach_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `DETACH`},
			gt.Optional{Element: gt.Literal{Value: `DATABASE`}},
			gt.RuleReference{Name: `NAME`, IsToken: true},
		}}, LineNumber: 26},
		{Name: `query_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Optional{Element: gt.RuleReference{Name: `with_clause`, IsToken: false}},
			gt.Group{Element: gt.Alternation{Choices: []gt.GrammarElement{
				gt.RuleReference{Name: `values_stmt`, IsToken: false},
				gt.RuleReference{Name: `select_stmt`, IsToken: false},
			}}},
			gt.Repetition{Element: gt.RuleReference{Name: `set_op_clause`, IsToken: false}},
		}}, LineNumber: 48},
		{Name: `values_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `VALUES`},
			gt.RuleReference{Name: `row_value`, IsToken: false},
			gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `,`},
				gt.RuleReference{Name: `row_value`, IsToken: false},
			}}},
		}}, LineNumber: 55},
		{Name: `with_clause`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `WITH`},
			gt.Optional{Element: gt.Literal{Value: `RECURSIVE`}},
			gt.RuleReference{Name: `cte_def`, IsToken: false},
			gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `,`},
				gt.RuleReference{Name: `cte_def`, IsToken: false},
			}}},
		}}, LineNumber: 56},
		{Name: `cte_def`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.RuleReference{Name: `NAME`, IsToken: true},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `(`},
				gt.RuleReference{Name: `NAME`, IsToken: true},
				gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
					gt.Literal{Value: `,`},
					gt.RuleReference{Name: `NAME`, IsToken: true},
				}}},
				gt.Literal{Value: `)`},
			}}},
			gt.Literal{Value: `AS`},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Optional{Element: gt.Literal{Value: `NOT`}},
				gt.Literal{Value: `MATERIALIZED`},
			}}},
			gt.Literal{Value: `(`},
			gt.RuleReference{Name: `query_stmt`, IsToken: false},
			gt.Literal{Value: `)`},
		}}, LineNumber: 61},
		{Name: `set_op_clause`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Group{Element: gt.Alternation{Choices: []gt.GrammarElement{
				gt.Literal{Value: `UNION`},
				gt.Literal{Value: `INTERSECT`},
				gt.Literal{Value: `EXCEPT`},
			}}},
			gt.Optional{Element: gt.Literal{Value: `ALL`}},
			gt.Group{Element: gt.Alternation{Choices: []gt.GrammarElement{
				gt.RuleReference{Name: `values_stmt`, IsToken: false},
				gt.RuleReference{Name: `select_stmt`, IsToken: false},
			}}},
		}}, LineNumber: 68},
		{Name: `select_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `SELECT`},
			gt.Optional{Element: gt.Alternation{Choices: []gt.GrammarElement{
				gt.Literal{Value: `DISTINCT`},
				gt.Literal{Value: `ALL`},
			}}},
			gt.RuleReference{Name: `select_list`, IsToken: false},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `FROM`},
				gt.RuleReference{Name: `table_ref`, IsToken: false},
				gt.Repetition{Element: gt.RuleReference{Name: `join_clause`, IsToken: false}},
			}}},
			gt.Optional{Element: gt.RuleReference{Name: `where_clause`, IsToken: false}},
			gt.Optional{Element: gt.RuleReference{Name: `group_clause`, IsToken: false}},
			gt.Optional{Element: gt.RuleReference{Name: `having_clause`, IsToken: false}},
			gt.Optional{Element: gt.RuleReference{Name: `window_clause`, IsToken: false}},
			gt.Optional{Element: gt.RuleReference{Name: `order_clause`, IsToken: false}},
			gt.Optional{Element: gt.RuleReference{Name: `limit_clause`, IsToken: false}},
		}}, LineNumber: 73},
		{Name: `select_list`, Body: gt.Alternation{Choices: []gt.GrammarElement{
			gt.RuleReference{Name: `STAR`, IsToken: true},
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.RuleReference{Name: `select_item`, IsToken: false},
				gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
					gt.Literal{Value: `,`},
					gt.RuleReference{Name: `select_item`, IsToken: false},
				}}},
			}},
		}}, LineNumber: 78},
		{Name: `select_item`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.RuleReference{Name: `expr`, IsToken: false},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Optional{Element: gt.Literal{Value: `AS`}},
				gt.RuleReference{Name: `NAME`, IsToken: true},
			}}},
		}}, LineNumber: 79},
		{Name: `table_ref`, Body: gt.Alternation{Choices: []gt.GrammarElement{
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `(`},
				gt.RuleReference{Name: `query_stmt`, IsToken: false},
				gt.Literal{Value: `)`},
				gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
					gt.Optional{Element: gt.Literal{Value: `AS`}},
					gt.RuleReference{Name: `NAME`, IsToken: true},
				}}},
			}},
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.RuleReference{Name: `table_name`, IsToken: false},
				gt.Optional{Element: gt.Alternation{Choices: []gt.GrammarElement{
					gt.Sequence{Elements: []gt.GrammarElement{
						gt.Literal{Value: `AS`},
						gt.RuleReference{Name: `NAME`, IsToken: true},
					}},
					gt.RuleReference{Name: `NAME`, IsToken: true},
				}}},
				gt.Optional{Element: gt.RuleReference{Name: `index_hint`, IsToken: false}},
			}},
		}}, LineNumber: 100},
		{Name: `table_name`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.RuleReference{Name: `NAME`, IsToken: true},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `.`},
				gt.RuleReference{Name: `NAME`, IsToken: true},
			}}},
		}}, LineNumber: 102},
		{Name: `index_hint`, Body: gt.Alternation{Choices: []gt.GrammarElement{
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `INDEXED`},
				gt.Literal{Value: `BY`},
				gt.RuleReference{Name: `NAME`, IsToken: true},
			}},
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `NOT`},
				gt.Literal{Value: `INDEXED`},
			}},
		}}, LineNumber: 103},
		{Name: `join_clause`, Body: gt.Alternation{Choices: []gt.GrammarElement{
			gt.Group{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Optional{Element: gt.RuleReference{Name: `join_type`, IsToken: false}},
				gt.Literal{Value: `JOIN`},
				gt.RuleReference{Name: `table_ref`, IsToken: false},
				gt.Optional{Element: gt.Alternation{Choices: []gt.GrammarElement{
					gt.Sequence{Elements: []gt.GrammarElement{
						gt.Literal{Value: `ON`},
						gt.RuleReference{Name: `expr`, IsToken: false},
					}},
					gt.Sequence{Elements: []gt.GrammarElement{
						gt.Literal{Value: `USING`},
						gt.Literal{Value: `(`},
						gt.RuleReference{Name: `NAME`, IsToken: true},
						gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
							gt.Literal{Value: `,`},
							gt.RuleReference{Name: `NAME`, IsToken: true},
						}}},
						gt.Literal{Value: `)`},
					}},
				}}},
			}}},
			gt.Group{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `,`},
				gt.RuleReference{Name: `table_ref`, IsToken: false},
			}}},
		}}, LineNumber: 111},
		{Name: `join_type`, Body: gt.Alternation{Choices: []gt.GrammarElement{
			gt.Literal{Value: `CROSS`},
			gt.Literal{Value: `INNER`},
			gt.Literal{Value: `NATURAL`},
			gt.Group{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `LEFT`},
				gt.Optional{Element: gt.Literal{Value: `OUTER`}},
			}}},
			gt.Group{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `RIGHT`},
				gt.Optional{Element: gt.Literal{Value: `OUTER`}},
			}}},
			gt.Group{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `FULL`},
				gt.Optional{Element: gt.Literal{Value: `OUTER`}},
			}}},
		}}, LineNumber: 113},
		{Name: `where_clause`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `WHERE`},
			gt.RuleReference{Name: `expr`, IsToken: false},
		}}, LineNumber: 117},
		{Name: `group_clause`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `GROUP`},
			gt.Literal{Value: `BY`},
			gt.RuleReference{Name: `column_ref`, IsToken: false},
			gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `,`},
				gt.RuleReference{Name: `column_ref`, IsToken: false},
			}}},
		}}, LineNumber: 118},
		{Name: `having_clause`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `HAVING`},
			gt.RuleReference{Name: `expr`, IsToken: false},
		}}, LineNumber: 119},
		{Name: `order_clause`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `ORDER`},
			gt.Literal{Value: `BY`},
			gt.RuleReference{Name: `order_item`, IsToken: false},
			gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `,`},
				gt.RuleReference{Name: `order_item`, IsToken: false},
			}}},
		}}, LineNumber: 120},
		{Name: `order_item`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.RuleReference{Name: `expr`, IsToken: false},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `COLLATE`},
				gt.RuleReference{Name: `NAME`, IsToken: true},
			}}},
			gt.Optional{Element: gt.Alternation{Choices: []gt.GrammarElement{
				gt.Literal{Value: `ASC`},
				gt.Literal{Value: `DESC`},
			}}},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `NULLS`},
				gt.RuleReference{Name: `NAME`, IsToken: true},
			}}},
		}}, LineNumber: 141},
		{Name: `limit_clause`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `LIMIT`},
			gt.RuleReference{Name: `signed_number`, IsToken: false},
			gt.Optional{Element: gt.Alternation{Choices: []gt.GrammarElement{
				gt.Sequence{Elements: []gt.GrammarElement{
					gt.Literal{Value: `OFFSET`},
					gt.RuleReference{Name: `signed_number`, IsToken: false},
				}},
				gt.Sequence{Elements: []gt.GrammarElement{
					gt.Literal{Value: `,`},
					gt.RuleReference{Name: `signed_number`, IsToken: false},
				}},
			}}},
		}}, LineNumber: 143},
		{Name: `signed_number`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Optional{Element: gt.Literal{Value: `-`}},
			gt.RuleReference{Name: `NUMBER`, IsToken: true},
		}}, LineNumber: 158},
		{Name: `conflict_clause`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `OR`},
			gt.Group{Element: gt.Alternation{Choices: []gt.GrammarElement{
				gt.Literal{Value: `REPLACE`},
				gt.Literal{Value: `IGNORE`},
				gt.Literal{Value: `ABORT`},
				gt.Literal{Value: `FAIL`},
				gt.Literal{Value: `ROLLBACK`},
			}}},
		}}, LineNumber: 180},
		{Name: `insert_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `INSERT`},
			gt.Optional{Element: gt.RuleReference{Name: `conflict_clause`, IsToken: false}},
			gt.Literal{Value: `INTO`},
			gt.RuleReference{Name: `NAME`, IsToken: true},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `(`},
				gt.RuleReference{Name: `NAME`, IsToken: true},
				gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
					gt.Literal{Value: `,`},
					gt.RuleReference{Name: `NAME`, IsToken: true},
				}}},
				gt.Literal{Value: `)`},
			}}},
			gt.RuleReference{Name: `insert_body`, IsToken: false},
			gt.Optional{Element: gt.RuleReference{Name: `upsert_clause`, IsToken: false}},
			gt.Optional{Element: gt.RuleReference{Name: `returning_clause`, IsToken: false}},
		}}, LineNumber: 182},
		{Name: `upsert_clause`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `ON`},
			gt.Literal{Value: `CONFLICT`},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `(`},
				gt.RuleReference{Name: `NAME`, IsToken: true},
				gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
					gt.Literal{Value: `,`},
					gt.RuleReference{Name: `NAME`, IsToken: true},
				}}},
				gt.Literal{Value: `)`},
			}}},
			gt.Group{Element: gt.Alternation{Choices: []gt.GrammarElement{
				gt.Sequence{Elements: []gt.GrammarElement{
					gt.Literal{Value: `DO`},
					gt.Literal{Value: `NOTHING`},
				}},
				gt.Sequence{Elements: []gt.GrammarElement{
					gt.Literal{Value: `DO`},
					gt.Literal{Value: `UPDATE`},
					gt.Literal{Value: `SET`},
					gt.RuleReference{Name: `upsert_assignment`, IsToken: false},
					gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
						gt.Literal{Value: `,`},
						gt.RuleReference{Name: `upsert_assignment`, IsToken: false},
					}}},
					gt.Optional{Element: gt.RuleReference{Name: `where_clause`, IsToken: false}},
				}},
			}}},
		}}, LineNumber: 199},
		{Name: `upsert_assignment`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.RuleReference{Name: `NAME`, IsToken: true},
			gt.Literal{Value: `=`},
			gt.RuleReference{Name: `expr`, IsToken: false},
		}}, LineNumber: 205},
		{Name: `replace_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `REPLACE`},
			gt.Literal{Value: `INTO`},
			gt.RuleReference{Name: `NAME`, IsToken: true},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `(`},
				gt.RuleReference{Name: `NAME`, IsToken: true},
				gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
					gt.Literal{Value: `,`},
					gt.RuleReference{Name: `NAME`, IsToken: true},
				}}},
				gt.Literal{Value: `)`},
			}}},
			gt.RuleReference{Name: `insert_body`, IsToken: false},
			gt.Optional{Element: gt.RuleReference{Name: `returning_clause`, IsToken: false}},
		}}, LineNumber: 206},
		{Name: `insert_body`, Body: gt.Alternation{Choices: []gt.GrammarElement{
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `VALUES`},
				gt.RuleReference{Name: `row_value`, IsToken: false},
				gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
					gt.Literal{Value: `,`},
					gt.RuleReference{Name: `row_value`, IsToken: false},
				}}},
			}},
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `DEFAULT`},
				gt.Literal{Value: `VALUES`},
			}},
			gt.RuleReference{Name: `query_stmt`, IsToken: false},
		}}, LineNumber: 210},
		{Name: `row_value`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `(`},
			gt.RuleReference{Name: `expr`, IsToken: false},
			gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `,`},
				gt.RuleReference{Name: `expr`, IsToken: false},
			}}},
			gt.Literal{Value: `)`},
		}}, LineNumber: 217},
		{Name: `row_value_list`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.RuleReference{Name: `row_value`, IsToken: false},
			gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `,`},
				gt.RuleReference{Name: `row_value`, IsToken: false},
			}}},
		}}, LineNumber: 219},
		{Name: `update_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `UPDATE`},
			gt.Optional{Element: gt.RuleReference{Name: `conflict_clause`, IsToken: false}},
			gt.RuleReference{Name: `NAME`, IsToken: true},
			gt.Literal{Value: `SET`},
			gt.RuleReference{Name: `assignment`, IsToken: false},
			gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `,`},
				gt.RuleReference{Name: `assignment`, IsToken: false},
			}}},
			gt.Optional{Element: gt.RuleReference{Name: `where_clause`, IsToken: false}},
			gt.Optional{Element: gt.RuleReference{Name: `returning_clause`, IsToken: false}},
		}}, LineNumber: 228},
		{Name: `assignment`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.RuleReference{Name: `NAME`, IsToken: true},
			gt.Literal{Value: `=`},
			gt.RuleReference{Name: `expr`, IsToken: false},
		}}, LineNumber: 230},
		{Name: `delete_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `DELETE`},
			gt.Literal{Value: `FROM`},
			gt.RuleReference{Name: `NAME`, IsToken: true},
			gt.Optional{Element: gt.RuleReference{Name: `where_clause`, IsToken: false}},
			gt.Optional{Element: gt.RuleReference{Name: `returning_clause`, IsToken: false}},
		}}, LineNumber: 232},
		{Name: `returning_clause`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `RETURNING`},
			gt.RuleReference{Name: `returning_item`, IsToken: false},
			gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `,`},
				gt.RuleReference{Name: `returning_item`, IsToken: false},
			}}},
		}}, LineNumber: 234},
		{Name: `returning_item`, Body: gt.Alternation{Choices: []gt.GrammarElement{
			gt.Literal{Value: `*`},
			gt.RuleReference{Name: `expr`, IsToken: false},
		}}, LineNumber: 238},
		{Name: `create_table_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `CREATE`},
			gt.Literal{Value: `TABLE`},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `IF`},
				gt.Literal{Value: `NOT`},
				gt.Literal{Value: `EXISTS`},
			}}},
			gt.RuleReference{Name: `NAME`, IsToken: true},
			gt.Literal{Value: `(`},
			gt.RuleReference{Name: `col_def`, IsToken: false},
			gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `,`},
				gt.RuleReference{Name: `col_def`, IsToken: false},
			}}},
			gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `,`},
				gt.RuleReference{Name: `table_constraint`, IsToken: false},
			}}},
			gt.Literal{Value: `)`},
			gt.Optional{Element: gt.RuleReference{Name: `table_options`, IsToken: false}},
		}}, LineNumber: 242},
		{Name: `table_constraint`, Body: gt.Alternation{Choices: []gt.GrammarElement{
			gt.Group{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `PRIMARY`},
				gt.Literal{Value: `KEY`},
				gt.Literal{Value: `(`},
				gt.RuleReference{Name: `NAME`, IsToken: true},
				gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
					gt.Literal{Value: `,`},
					gt.RuleReference{Name: `NAME`, IsToken: true},
				}}},
				gt.Literal{Value: `)`},
			}}},
			gt.Group{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `UNIQUE`},
				gt.Literal{Value: `(`},
				gt.RuleReference{Name: `NAME`, IsToken: true},
				gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
					gt.Literal{Value: `,`},
					gt.RuleReference{Name: `NAME`, IsToken: true},
				}}},
				gt.Literal{Value: `)`},
			}}},
			gt.Group{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `CHECK`},
				gt.Literal{Value: `(`},
				gt.RuleReference{Name: `expr`, IsToken: false},
				gt.Literal{Value: `)`},
			}}},
			gt.Group{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `FOREIGN`},
				gt.Literal{Value: `KEY`},
				gt.Literal{Value: `(`},
				gt.RuleReference{Name: `NAME`, IsToken: true},
				gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
					gt.Literal{Value: `,`},
					gt.RuleReference{Name: `NAME`, IsToken: true},
				}}},
				gt.Literal{Value: `)`},
				gt.Literal{Value: `REFERENCES`},
				gt.RuleReference{Name: `NAME`, IsToken: true},
				gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
					gt.Literal{Value: `(`},
					gt.RuleReference{Name: `NAME`, IsToken: true},
					gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
						gt.Literal{Value: `,`},
						gt.RuleReference{Name: `NAME`, IsToken: true},
					}}},
					gt.Literal{Value: `)`},
				}}},
			}}},
		}}, LineNumber: 250},
		{Name: `table_options`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.RuleReference{Name: `table_option`, IsToken: false},
			gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `,`},
				gt.RuleReference{Name: `table_option`, IsToken: false},
			}}},
		}}, LineNumber: 261},
		{Name: `table_option`, Body: gt.Alternation{Choices: []gt.GrammarElement{
			gt.Literal{Value: `STRICT`},
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `WITHOUT`},
				gt.RuleReference{Name: `NAME`, IsToken: true},
			}},
		}}, LineNumber: 262},
		{Name: `col_def`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.NegativeLookahead{Element: gt.Group{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `FOREIGN`},
				gt.Literal{Value: `KEY`},
			}}}},
			gt.RuleReference{Name: `NAME`, IsToken: true},
			gt.Optional{Element: gt.RuleReference{Name: `col_type`, IsToken: false}},
			gt.Repetition{Element: gt.RuleReference{Name: `col_constraint`, IsToken: false}},
		}}, LineNumber: 267},
		{Name: `col_type`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.RuleReference{Name: `NAME`, IsToken: true},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `(`},
				gt.RuleReference{Name: `NUMBER`, IsToken: true},
				gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
					gt.Literal{Value: `,`},
					gt.RuleReference{Name: `NUMBER`, IsToken: true},
				}}},
				gt.Literal{Value: `)`},
			}}},
		}}, LineNumber: 279},
		{Name: `col_constraint`, Body: gt.Alternation{Choices: []gt.GrammarElement{
			gt.Group{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `NOT`},
				gt.Literal{Value: `NULL`},
				gt.Optional{Element: gt.RuleReference{Name: `col_conflict_clause`, IsToken: false}},
			}}},
			gt.Literal{Value: `NULL`},
			gt.Group{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `PRIMARY`},
				gt.Literal{Value: `KEY`},
				gt.Optional{Element: gt.Literal{Value: `AUTOINCREMENT`}},
				gt.Optional{Element: gt.RuleReference{Name: `col_conflict_clause`, IsToken: false}},
			}}},
			gt.Group{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `UNIQUE`},
				gt.Optional{Element: gt.RuleReference{Name: `col_conflict_clause`, IsToken: false}},
			}}},
			gt.Group{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `DEFAULT`},
				gt.RuleReference{Name: `primary`, IsToken: false},
			}}},
			gt.Group{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `CHECK`},
				gt.Literal{Value: `(`},
				gt.RuleReference{Name: `expr`, IsToken: false},
				gt.Literal{Value: `)`},
			}}},
			gt.Group{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `COLLATE`},
				gt.RuleReference{Name: `NAME`, IsToken: true},
			}}},
			gt.Group{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `REFERENCES`},
				gt.RuleReference{Name: `NAME`, IsToken: true},
				gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
					gt.Literal{Value: `(`},
					gt.RuleReference{Name: `NAME`, IsToken: true},
					gt.Literal{Value: `)`},
				}}},
			}}},
		}}, LineNumber: 280},
		{Name: `col_conflict_clause`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `ON`},
			gt.Literal{Value: `CONFLICT`},
			gt.Group{Element: gt.Alternation{Choices: []gt.GrammarElement{
				gt.Literal{Value: `ROLLBACK`},
				gt.Literal{Value: `ABORT`},
				gt.Literal{Value: `FAIL`},
				gt.Literal{Value: `IGNORE`},
				gt.Literal{Value: `REPLACE`},
			}}},
		}}, LineNumber: 296},
		{Name: `drop_table_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `DROP`},
			gt.Literal{Value: `TABLE`},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `IF`},
				gt.Literal{Value: `EXISTS`},
			}}},
			gt.RuleReference{Name: `NAME`, IsToken: true},
		}}, LineNumber: 304},
		{Name: `alter_table_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `ALTER`},
			gt.Literal{Value: `TABLE`},
			gt.RuleReference{Name: `NAME`, IsToken: true},
			gt.Group{Element: gt.Alternation{Choices: []gt.GrammarElement{
				gt.Sequence{Elements: []gt.GrammarElement{
					gt.Literal{Value: `ADD`},
					gt.Optional{Element: gt.Literal{Value: `COLUMN`}},
					gt.RuleReference{Name: `col_def`, IsToken: false},
				}},
				gt.Sequence{Elements: []gt.GrammarElement{
					gt.Literal{Value: `RENAME`},
					gt.Literal{Value: `TO`},
					gt.RuleReference{Name: `NAME`, IsToken: true},
				}},
				gt.Sequence{Elements: []gt.GrammarElement{
					gt.Literal{Value: `RENAME`},
					gt.Optional{Element: gt.Literal{Value: `COLUMN`}},
					gt.RuleReference{Name: `NAME`, IsToken: true},
					gt.Literal{Value: `TO`},
					gt.RuleReference{Name: `NAME`, IsToken: true},
				}},
				gt.Sequence{Elements: []gt.GrammarElement{
					gt.Literal{Value: `DROP`},
					gt.Optional{Element: gt.Literal{Value: `COLUMN`}},
					gt.RuleReference{Name: `NAME`, IsToken: true},
				}},
			}}},
		}}, LineNumber: 313},
		{Name: `create_index_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `CREATE`},
			gt.Optional{Element: gt.Literal{Value: `UNIQUE`}},
			gt.Literal{Value: `INDEX`},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `IF`},
				gt.Literal{Value: `NOT`},
				gt.Literal{Value: `EXISTS`},
			}}},
			gt.RuleReference{Name: `NAME`, IsToken: true},
			gt.Literal{Value: `ON`},
			gt.RuleReference{Name: `NAME`, IsToken: true},
			gt.Literal{Value: `(`},
			gt.RuleReference{Name: `index_col`, IsToken: false},
			gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `,`},
				gt.RuleReference{Name: `index_col`, IsToken: false},
			}}},
			gt.Literal{Value: `)`},
			gt.Optional{Element: gt.RuleReference{Name: `where_clause`, IsToken: false}},
		}}, LineNumber: 327},
		{Name: `index_col`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.RuleReference{Name: `expr`, IsToken: false},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `COLLATE`},
				gt.RuleReference{Name: `NAME`, IsToken: true},
			}}},
			gt.Optional{Element: gt.Alternation{Choices: []gt.GrammarElement{
				gt.Literal{Value: `ASC`},
				gt.Literal{Value: `DESC`},
			}}},
		}}, LineNumber: 344},
		{Name: `drop_index_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `DROP`},
			gt.Literal{Value: `INDEX`},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `IF`},
				gt.Literal{Value: `EXISTS`},
			}}},
			gt.RuleReference{Name: `NAME`, IsToken: true},
		}}, LineNumber: 346},
		{Name: `create_view_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `CREATE`},
			gt.Literal{Value: `VIEW`},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `IF`},
				gt.Literal{Value: `NOT`},
				gt.Literal{Value: `EXISTS`},
			}}},
			gt.RuleReference{Name: `NAME`, IsToken: true},
			gt.Literal{Value: `AS`},
			gt.RuleReference{Name: `query_stmt`, IsToken: false},
		}}, LineNumber: 354},
		{Name: `drop_view_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `DROP`},
			gt.Literal{Value: `VIEW`},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `IF`},
				gt.Literal{Value: `EXISTS`},
			}}},
			gt.RuleReference{Name: `NAME`, IsToken: true},
		}}, LineNumber: 356},
		{Name: `begin_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `BEGIN`},
			gt.Optional{Element: gt.Literal{Value: `TRANSACTION`}},
		}}, LineNumber: 362},
		{Name: `commit_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `COMMIT`},
			gt.Optional{Element: gt.Literal{Value: `TRANSACTION`}},
		}}, LineNumber: 363},
		{Name: `rollback_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `ROLLBACK`},
			gt.Optional{Element: gt.Literal{Value: `TRANSACTION`}},
		}}, LineNumber: 364},
		{Name: `savepoint_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `SAVEPOINT`},
			gt.RuleReference{Name: `NAME`, IsToken: true},
		}}, LineNumber: 380},
		{Name: `release_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `RELEASE`},
			gt.Optional{Element: gt.Literal{Value: `SAVEPOINT`}},
			gt.RuleReference{Name: `NAME`, IsToken: true},
		}}, LineNumber: 381},
		{Name: `rollback_to_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `ROLLBACK`},
			gt.Literal{Value: `TO`},
			gt.Optional{Element: gt.Literal{Value: `SAVEPOINT`}},
			gt.RuleReference{Name: `NAME`, IsToken: true},
		}}, LineNumber: 382},
		{Name: `expr`, Body: gt.RuleReference{Name: `or_expr`, IsToken: false}, LineNumber: 386},
		{Name: `or_expr`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.RuleReference{Name: `and_expr`, IsToken: false},
			gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `OR`},
				gt.RuleReference{Name: `and_expr`, IsToken: false},
			}}},
		}}, LineNumber: 387},
		{Name: `and_expr`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.RuleReference{Name: `not_expr`, IsToken: false},
			gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `AND`},
				gt.RuleReference{Name: `not_expr`, IsToken: false},
			}}},
		}}, LineNumber: 388},
		{Name: `not_expr`, Body: gt.Alternation{Choices: []gt.GrammarElement{
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `NOT`},
				gt.RuleReference{Name: `not_expr`, IsToken: false},
			}},
			gt.RuleReference{Name: `comparison`, IsToken: false},
		}}, LineNumber: 389},
		{Name: `collated`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.RuleReference{Name: `bitwise`, IsToken: false},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `COLLATE`},
				gt.RuleReference{Name: `NAME`, IsToken: true},
			}}},
		}}, LineNumber: 402},
		{Name: `comparison`, Body: gt.Alternation{Choices: []gt.GrammarElement{
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.RuleReference{Name: `row_value`, IsToken: false},
				gt.RuleReference{Name: `cmp_op`, IsToken: false},
				gt.RuleReference{Name: `row_value`, IsToken: false},
			}},
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.RuleReference{Name: `row_value`, IsToken: false},
				gt.Literal{Value: `NOT`},
				gt.Literal{Value: `IN`},
				gt.Literal{Value: `(`},
				gt.RuleReference{Name: `row_value_list`, IsToken: false},
				gt.Literal{Value: `)`},
			}},
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.RuleReference{Name: `row_value`, IsToken: false},
				gt.Literal{Value: `IN`},
				gt.Literal{Value: `(`},
				gt.RuleReference{Name: `row_value_list`, IsToken: false},
				gt.Literal{Value: `)`},
			}},
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.RuleReference{Name: `collated`, IsToken: false},
				gt.Optional{Element: gt.Alternation{Choices: []gt.GrammarElement{
					gt.Sequence{Elements: []gt.GrammarElement{
						gt.RuleReference{Name: `cmp_op`, IsToken: false},
						gt.RuleReference{Name: `collated`, IsToken: false},
					}},
					gt.Sequence{Elements: []gt.GrammarElement{
						gt.Literal{Value: `BETWEEN`},
						gt.RuleReference{Name: `collated`, IsToken: false},
						gt.Literal{Value: `AND`},
						gt.RuleReference{Name: `collated`, IsToken: false},
					}},
					gt.Sequence{Elements: []gt.GrammarElement{
						gt.Literal{Value: `NOT`},
						gt.Literal{Value: `BETWEEN`},
						gt.RuleReference{Name: `collated`, IsToken: false},
						gt.Literal{Value: `AND`},
						gt.RuleReference{Name: `collated`, IsToken: false},
					}},
					gt.Sequence{Elements: []gt.GrammarElement{
						gt.Literal{Value: `IN`},
						gt.Literal{Value: `(`},
						gt.Optional{Element: gt.RuleReference{Name: `in_expr`, IsToken: false}},
						gt.Literal{Value: `)`},
					}},
					gt.Sequence{Elements: []gt.GrammarElement{
						gt.Literal{Value: `NOT`},
						gt.Literal{Value: `IN`},
						gt.Literal{Value: `(`},
						gt.Optional{Element: gt.RuleReference{Name: `in_expr`, IsToken: false}},
						gt.Literal{Value: `)`},
					}},
					gt.Sequence{Elements: []gt.GrammarElement{
						gt.Literal{Value: `LIKE`},
						gt.RuleReference{Name: `collated`, IsToken: false},
						gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
							gt.Literal{Value: `ESCAPE`},
							gt.RuleReference{Name: `collated`, IsToken: false},
						}}},
					}},
					gt.Sequence{Elements: []gt.GrammarElement{
						gt.Literal{Value: `NOT`},
						gt.Literal{Value: `LIKE`},
						gt.RuleReference{Name: `collated`, IsToken: false},
						gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
							gt.Literal{Value: `ESCAPE`},
							gt.RuleReference{Name: `collated`, IsToken: false},
						}}},
					}},
					gt.Sequence{Elements: []gt.GrammarElement{
						gt.Literal{Value: `GLOB`},
						gt.RuleReference{Name: `collated`, IsToken: false},
					}},
					gt.Sequence{Elements: []gt.GrammarElement{
						gt.Literal{Value: `NOT`},
						gt.Literal{Value: `GLOB`},
						gt.RuleReference{Name: `collated`, IsToken: false},
					}},
					gt.Sequence{Elements: []gt.GrammarElement{
						gt.Literal{Value: `IS`},
						gt.Literal{Value: `NULL`},
					}},
					gt.Sequence{Elements: []gt.GrammarElement{
						gt.Literal{Value: `IS`},
						gt.Literal{Value: `NOT`},
						gt.Literal{Value: `NULL`},
					}},
					gt.Sequence{Elements: []gt.GrammarElement{
						gt.Literal{Value: `IS`},
						gt.Literal{Value: `DISTINCT`},
						gt.Literal{Value: `FROM`},
						gt.RuleReference{Name: `collated`, IsToken: false},
					}},
					gt.Sequence{Elements: []gt.GrammarElement{
						gt.Literal{Value: `IS`},
						gt.Literal{Value: `NOT`},
						gt.Literal{Value: `DISTINCT`},
						gt.Literal{Value: `FROM`},
						gt.RuleReference{Name: `collated`, IsToken: false},
					}},
					gt.Sequence{Elements: []gt.GrammarElement{
						gt.Literal{Value: `IS`},
						gt.Literal{Value: `NOT`},
						gt.RuleReference{Name: `collated`, IsToken: false},
					}},
					gt.Sequence{Elements: []gt.GrammarElement{
						gt.Literal{Value: `IS`},
						gt.RuleReference{Name: `collated`, IsToken: false},
					}},
				}}},
			}},
		}}, LineNumber: 407},
		{Name: `in_expr`, Body: gt.Alternation{Choices: []gt.GrammarElement{
			gt.RuleReference{Name: `query_stmt`, IsToken: false},
			gt.RuleReference{Name: `value_list`, IsToken: false},
		}}, LineNumber: 435},
		{Name: `cmp_op`, Body: gt.Alternation{Choices: []gt.GrammarElement{
			gt.Literal{Value: `=`},
			gt.RuleReference{Name: `NOT_EQUALS`, IsToken: true},
			gt.Literal{Value: `<`},
			gt.Literal{Value: `>`},
			gt.Literal{Value: `<=`},
			gt.Literal{Value: `>=`},
		}}, LineNumber: 437},
		{Name: `bitwise`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.RuleReference{Name: `additive`, IsToken: false},
			gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Group{Element: gt.Alternation{Choices: []gt.GrammarElement{
					gt.Literal{Value: `&`},
					gt.Literal{Value: `|`},
					gt.Literal{Value: `<<`},
					gt.Literal{Value: `>>`},
				}}},
				gt.RuleReference{Name: `additive`, IsToken: false},
			}}},
		}}, LineNumber: 451},
		{Name: `additive`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.RuleReference{Name: `multiplicative`, IsToken: false},
			gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Group{Element: gt.Alternation{Choices: []gt.GrammarElement{
					gt.Literal{Value: `+`},
					gt.Literal{Value: `-`},
					gt.Literal{Value: `||`},
					gt.RuleReference{Name: `JSON_ARROW`, IsToken: true},
					gt.RuleReference{Name: `JSON_ARROW_TEXT`, IsToken: true},
				}}},
				gt.RuleReference{Name: `multiplicative`, IsToken: false},
			}}},
		}}, LineNumber: 452},
		{Name: `multiplicative`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.RuleReference{Name: `unary`, IsToken: false},
			gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Group{Element: gt.Alternation{Choices: []gt.GrammarElement{
					gt.RuleReference{Name: `STAR`, IsToken: true},
					gt.Literal{Value: `/`},
					gt.Literal{Value: `%`},
				}}},
				gt.RuleReference{Name: `unary`, IsToken: false},
			}}},
		}}, LineNumber: 453},
		{Name: `unary`, Body: gt.Alternation{Choices: []gt.GrammarElement{
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.Group{Element: gt.Alternation{Choices: []gt.GrammarElement{
					gt.Literal{Value: `-`},
					gt.Literal{Value: `~`},
					gt.Literal{Value: `+`},
				}}},
				gt.RuleReference{Name: `unary`, IsToken: false},
			}},
			gt.RuleReference{Name: `primary`, IsToken: false},
		}}, LineNumber: 459},
		{Name: `primary`, Body: gt.Alternation{Choices: []gt.GrammarElement{
			gt.RuleReference{Name: `NUMBER`, IsToken: true},
			gt.RuleReference{Name: `STRING`, IsToken: true},
			gt.RuleReference{Name: `BLOB`, IsToken: true},
			gt.Literal{Value: `NULL`},
			gt.Literal{Value: `TRUE`},
			gt.Literal{Value: `FALSE`},
			gt.RuleReference{Name: `case_expr`, IsToken: false},
			gt.RuleReference{Name: `cast_expr`, IsToken: false},
			gt.RuleReference{Name: `window_func_call`, IsToken: false},
			gt.RuleReference{Name: `function_call`, IsToken: false},
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `EXISTS`},
				gt.Literal{Value: `(`},
				gt.RuleReference{Name: `query_stmt`, IsToken: false},
				gt.Literal{Value: `)`},
			}},
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `(`},
				gt.RuleReference{Name: `query_stmt`, IsToken: false},
				gt.Literal{Value: `)`},
			}},
			gt.RuleReference{Name: `column_ref`, IsToken: false},
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `(`},
				gt.RuleReference{Name: `expr`, IsToken: false},
				gt.Literal{Value: `)`},
			}},
		}}, LineNumber: 479},
		{Name: `column_ref`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.RuleReference{Name: `NAME`, IsToken: true},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `.`},
				gt.RuleReference{Name: `NAME`, IsToken: true},
			}}},
		}}, LineNumber: 489},
		{Name: `function_call`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Group{Element: gt.Alternation{Choices: []gt.GrammarElement{
				gt.RuleReference{Name: `NAME`, IsToken: true},
				gt.Literal{Value: `REPLACE`},
			}}},
			gt.Literal{Value: `(`},
			gt.Group{Element: gt.Alternation{Choices: []gt.GrammarElement{
				gt.RuleReference{Name: `STAR`, IsToken: true},
				gt.Sequence{Elements: []gt.GrammarElement{
					gt.Literal{Value: `DISTINCT`},
					gt.RuleReference{Name: `value_list`, IsToken: false},
				}},
				gt.Optional{Element: gt.RuleReference{Name: `value_list`, IsToken: false}},
			}}},
			gt.Literal{Value: `)`},
			gt.Optional{Element: gt.RuleReference{Name: `filter_clause`, IsToken: false}},
		}}, LineNumber: 503},
		{Name: `filter_clause`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `FILTER`},
			gt.Literal{Value: `(`},
			gt.Literal{Value: `WHERE`},
			gt.RuleReference{Name: `expr`, IsToken: false},
			gt.Literal{Value: `)`},
		}}, LineNumber: 507},
		{Name: `cast_expr`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `CAST`},
			gt.Literal{Value: `(`},
			gt.RuleReference{Name: `expr`, IsToken: false},
			gt.Literal{Value: `AS`},
			gt.RuleReference{Name: `NAME`, IsToken: true},
			gt.Literal{Value: `)`},
		}}, LineNumber: 513},
		{Name: `window_func_call`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.RuleReference{Name: `NAME`, IsToken: true},
			gt.Literal{Value: `(`},
			gt.Group{Element: gt.Alternation{Choices: []gt.GrammarElement{
				gt.RuleReference{Name: `STAR`, IsToken: true},
				gt.Optional{Element: gt.RuleReference{Name: `value_list`, IsToken: false}},
			}}},
			gt.Literal{Value: `)`},
			gt.Literal{Value: `OVER`},
			gt.Group{Element: gt.Alternation{Choices: []gt.GrammarElement{
				gt.Sequence{Elements: []gt.GrammarElement{
					gt.Literal{Value: `(`},
					gt.RuleReference{Name: `window_spec`, IsToken: false},
					gt.Literal{Value: `)`},
				}},
				gt.RuleReference{Name: `window_name_ref`, IsToken: false},
			}}},
		}}, LineNumber: 542},
		{Name: `window_name_ref`, Body: gt.RuleReference{Name: `NAME`, IsToken: true}, LineNumber: 543},
		{Name: `window_spec`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Optional{Element: gt.RuleReference{Name: `partition_clause`, IsToken: false}},
			gt.Optional{Element: gt.RuleReference{Name: `order_clause`, IsToken: false}},
			gt.Optional{Element: gt.RuleReference{Name: `frame_clause`, IsToken: false}},
		}}, LineNumber: 544},
		{Name: `window_clause`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `WINDOW`},
			gt.RuleReference{Name: `NAME`, IsToken: true},
			gt.Literal{Value: `AS`},
			gt.Literal{Value: `(`},
			gt.RuleReference{Name: `window_spec`, IsToken: false},
			gt.Literal{Value: `)`},
			gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `,`},
				gt.RuleReference{Name: `NAME`, IsToken: true},
				gt.Literal{Value: `AS`},
				gt.Literal{Value: `(`},
				gt.RuleReference{Name: `window_spec`, IsToken: false},
				gt.Literal{Value: `)`},
			}}},
		}}, LineNumber: 545},
		{Name: `partition_clause`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `PARTITION`},
			gt.Literal{Value: `BY`},
			gt.RuleReference{Name: `expr`, IsToken: false},
			gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `,`},
				gt.RuleReference{Name: `expr`, IsToken: false},
			}}},
		}}, LineNumber: 546},
		{Name: `value_list`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.RuleReference{Name: `expr`, IsToken: false},
			gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `,`},
				gt.RuleReference{Name: `expr`, IsToken: false},
			}}},
		}}, LineNumber: 547},
		{Name: `frame_clause`, Body: gt.Alternation{Choices: []gt.GrammarElement{
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.RuleReference{Name: `frame_unit`, IsToken: false},
				gt.Literal{Value: `BETWEEN`},
				gt.RuleReference{Name: `frame_bound`, IsToken: false},
				gt.Literal{Value: `AND`},
				gt.RuleReference{Name: `frame_bound`, IsToken: false},
			}},
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.RuleReference{Name: `frame_unit`, IsToken: false},
				gt.RuleReference{Name: `frame_bound`, IsToken: false},
			}},
		}}, LineNumber: 569},
		{Name: `frame_unit`, Body: gt.Alternation{Choices: []gt.GrammarElement{
			gt.Literal{Value: `ROWS`},
			gt.Literal{Value: `RANGE`},
			gt.Literal{Value: `GROUPS`},
		}}, LineNumber: 571},
		{Name: `frame_bound`, Body: gt.Alternation{Choices: []gt.GrammarElement{
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `UNBOUNDED`},
				gt.Literal{Value: `PRECEDING`},
			}},
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `UNBOUNDED`},
				gt.Literal{Value: `FOLLOWING`},
			}},
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `CURRENT`},
				gt.Literal{Value: `ROW`},
			}},
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.RuleReference{Name: `expr`, IsToken: false},
				gt.Literal{Value: `PRECEDING`},
			}},
			gt.Sequence{Elements: []gt.GrammarElement{
				gt.RuleReference{Name: `expr`, IsToken: false},
				gt.Literal{Value: `FOLLOWING`},
			}},
		}}, LineNumber: 572},
		{Name: `create_trigger_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `CREATE`},
			gt.Literal{Value: `TRIGGER`},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `IF`},
				gt.Literal{Value: `NOT`},
				gt.Literal{Value: `EXISTS`},
			}}},
			gt.RuleReference{Name: `NAME`, IsToken: true},
			gt.Group{Element: gt.Alternation{Choices: []gt.GrammarElement{
				gt.Literal{Value: `BEFORE`},
				gt.Literal{Value: `AFTER`},
			}}},
			gt.Group{Element: gt.Alternation{Choices: []gt.GrammarElement{
				gt.Literal{Value: `INSERT`},
				gt.Literal{Value: `UPDATE`},
				gt.Literal{Value: `DELETE`},
			}}},
			gt.Literal{Value: `ON`},
			gt.RuleReference{Name: `NAME`, IsToken: true},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `FOR`},
				gt.Literal{Value: `EACH`},
				gt.Literal{Value: `ROW`},
			}}},
			gt.Literal{Value: `BEGIN`},
			gt.RuleReference{Name: `trigger_body_stmt`, IsToken: false},
			gt.Literal{Value: `;`},
			gt.Repetition{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.RuleReference{Name: `trigger_body_stmt`, IsToken: false},
				gt.Literal{Value: `;`},
			}}},
			gt.Literal{Value: `END`},
		}}, LineNumber: 598},
		{Name: `trigger_body_stmt`, Body: gt.Alternation{Choices: []gt.GrammarElement{
			gt.RuleReference{Name: `insert_stmt`, IsToken: false},
			gt.RuleReference{Name: `replace_stmt`, IsToken: false},
			gt.RuleReference{Name: `update_stmt`, IsToken: false},
			gt.RuleReference{Name: `delete_stmt`, IsToken: false},
			gt.RuleReference{Name: `query_stmt`, IsToken: false},
		}}, LineNumber: 603},
		{Name: `drop_trigger_stmt`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `DROP`},
			gt.Literal{Value: `TRIGGER`},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `IF`},
				gt.Literal{Value: `EXISTS`},
			}}},
			gt.RuleReference{Name: `NAME`, IsToken: true},
		}}, LineNumber: 605},
		{Name: `case_expr`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `CASE`},
			gt.Optional{Element: gt.RuleReference{Name: `case_operand`, IsToken: false}},
			gt.RuleReference{Name: `case_when`, IsToken: false},
			gt.Repetition{Element: gt.RuleReference{Name: `case_when`, IsToken: false}},
			gt.Optional{Element: gt.Sequence{Elements: []gt.GrammarElement{
				gt.Literal{Value: `ELSE`},
				gt.RuleReference{Name: `expr`, IsToken: false},
			}}},
			gt.Literal{Value: `END`},
		}}, LineNumber: 620},
		{Name: `case_operand`, Body: gt.RuleReference{Name: `expr`, IsToken: false}, LineNumber: 621},
		{Name: `case_when`, Body: gt.Sequence{Elements: []gt.GrammarElement{
			gt.Literal{Value: `WHEN`},
			gt.RuleReference{Name: `expr`, IsToken: false},
			gt.Literal{Value: `THEN`},
			gt.RuleReference{Name: `expr`, IsToken: false},
		}}, LineNumber: 622},
	},
}
