# AUTO-GENERATED FILE - DO NOT EDIT
from grammar_tools.token_grammar import TokenGrammar, TokenDefinition, PatternGroup

ExcelTokens = TokenGrammar(
    version=1,
    case_insensitive=True,
    case_sensitive=True,
    keywords=["TRUE", "FALSE"],
    definitions=[
        TokenDefinition(name="SPACE", pattern=" +", is_regex=True, line_number=13),
        TokenDefinition(name="REF_PREFIX_QUOTED", pattern="(\\[[^\\]]+\\])?'([^']|'')*'!", is_regex=True, line_number=15, alias="REF_PREFIX"),
        TokenDefinition(name="REF_PREFIX_BARE", pattern="(\\[[^\\]]+\\])?[A-Za-z_\\\\][A-Za-z0-9_\\.]*(?::[A-Za-z_\\\\][A-Za-z0-9_\\.]*)*!", is_regex=True, line_number=16, alias="REF_PREFIX"),
        TokenDefinition(name="STRING", pattern="\"([^\"]|\"\")*\"", is_regex=True, line_number=18),
        TokenDefinition(name="ERROR_CONSTANT", pattern="#NULL!|#DIV\\/0!|#VALUE!|#REF!|#NAME\\?|#NUM!|#N\\/A|#SPILL!|#CALC!|#GETTING_DATA", is_regex=True, line_number=19),
        TokenDefinition(name="NUMBER", pattern="[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?|\\.[0-9]+([eE][+-]?[0-9]+)?|[0-9]+([eE][+-]?[0-9]+)?", is_regex=True, line_number=20),
        TokenDefinition(name="STRUCTURED_KEYWORD", pattern="\\[#(?:All|Data|Headers|Totals|This Row)\\]", is_regex=True, line_number=22),
        TokenDefinition(name="STRUCTURED_COLUMN", pattern="\\[(?:[^\\[\\]]|\\]\\])+\\]", is_regex=True, line_number=23),
        TokenDefinition(name="CELL", pattern="\\$?[A-Za-z]{1,3}\\$?[0-9]{1,7}", is_regex=True, line_number=26),
        TokenDefinition(name="NOT_EQUALS", pattern="<>", is_regex=False, line_number=28),
        TokenDefinition(name="LESS_EQUALS", pattern="<=", is_regex=False, line_number=29),
        TokenDefinition(name="GREATER_EQUALS", pattern=">=", is_regex=False, line_number=30),
        TokenDefinition(name="PLUS", pattern="+", is_regex=False, line_number=32),
        TokenDefinition(name="MINUS", pattern="-", is_regex=False, line_number=33),
        TokenDefinition(name="STAR", pattern="*", is_regex=False, line_number=34),
        TokenDefinition(name="SLASH", pattern="/", is_regex=False, line_number=35),
        TokenDefinition(name="CARET", pattern="^", is_regex=False, line_number=36),
        TokenDefinition(name="AMP", pattern="&", is_regex=False, line_number=37),
        TokenDefinition(name="PERCENT", pattern="%", is_regex=False, line_number=38),
        TokenDefinition(name="EQUALS", pattern="=", is_regex=False, line_number=39),
        TokenDefinition(name="LESS_THAN", pattern="<", is_regex=False, line_number=40),
        TokenDefinition(name="GREATER_THAN", pattern=">", is_regex=False, line_number=41),
        TokenDefinition(name="BANG", pattern="!", is_regex=False, line_number=42),
        TokenDefinition(name="DOLLAR", pattern="$", is_regex=False, line_number=43),
        TokenDefinition(name="LPAREN", pattern="(", is_regex=False, line_number=44),
        TokenDefinition(name="RPAREN", pattern=")", is_regex=False, line_number=45),
        TokenDefinition(name="LBRACE", pattern="{", is_regex=False, line_number=46),
        TokenDefinition(name="RBRACE", pattern="}", is_regex=False, line_number=47),
        TokenDefinition(name="LBRACKET", pattern="[", is_regex=False, line_number=48),
        TokenDefinition(name="RBRACKET", pattern="]", is_regex=False, line_number=49),
        TokenDefinition(name="COMMA", pattern=",", is_regex=False, line_number=50),
        TokenDefinition(name="SEMICOLON", pattern=";", is_regex=False, line_number=51),
        TokenDefinition(name="COLON", pattern=":", is_regex=False, line_number=52),
        TokenDefinition(name="AT", pattern="@", is_regex=False, line_number=53),
        TokenDefinition(name="NAME", pattern="[A-Za-z_\\\\][A-Za-z0-9_\\.]*", is_regex=True, line_number=55),
        TokenDefinition(name="FUNCTION_NAME", pattern="(?!.)", is_regex=True, line_number=61),
        TokenDefinition(name="TABLE_NAME", pattern="(?!.)", is_regex=True, line_number=62),
        TokenDefinition(name="COLUMN_REF", pattern="(?!.)", is_regex=True, line_number=63),
        TokenDefinition(name="ROW_REF", pattern="(?!.)", is_regex=True, line_number=64),
    ],
    skip_definitions=[
        TokenDefinition(name="NONSPACE_WHITESPACE", pattern="[\\t\\r\\n]+", is_regex=True, line_number=11),
    ],
)
