# GENERATED by code/scripts/generate_scytale_fixture_consumers.py.
# Source SHA-256: efd6c3a85a0c1d0676c31bf709d7c3d7eb5f4aef6b31ac2f904ebad6d76ad02c
# Do not edit by hand.

# frozen_string_literal: true

require "minitest/autorun"
require "coding_adventures_scytale_cipher"

class TestGeneratedClassicalCipherFixture < Minitest::Test
  def test_all_normative_scytale_cases
    cipher = CodingAdventures::ScytaleCipher
    # classical-ciphers-v1-scytale-worked-encrypt
    assert_equal "HLWLEOODL R ", cipher.encrypt("HELLO WORLD", 3)
    # classical-ciphers-v1-scytale-worked-decrypt
    assert_equal "HELLO WORLD", cipher.decrypt("HLWLEOODL R ", 3)
    # classical-ciphers-v1-scytale-ragged-decrypt
    assert_equal "ACEFBD", cipher.decrypt("ABCDEF", 4)
    # classical-ciphers-v1-scytale-unicode-encrypt
    assert_equal "Aé😀 B ", cipher.encrypt("A😀Bé", 3)
    # classical-ciphers-v1-scytale-unicode-decrypt
    assert_equal "A😀Bé", cipher.decrypt("Aé😀 B ", 3)
    # classical-ciphers-v1-scytale-combining-scalar-encrypt
    assert_equal "ABe ́ ", cipher.encrypt("AéB", 3)
    # classical-ciphers-v1-scytale-combining-scalar-decrypt
    assert_equal "AéB", cipher.decrypt("ABe ́ ", 3)
    # classical-ciphers-v1-scytale-genuine-trailing-space-encrypt
    assert_equal "E N D ", cipher.encrypt("END ", 3)
    # classical-ciphers-v1-scytale-genuine-trailing-space-loss
    assert_equal "END", cipher.decrypt("E N D ", 3)
    # classical-ciphers-v1-scytale-trailing-tab-retained
    assert_equal "AB\t", cipher.decrypt("A\tB ", 2)
    # classical-ciphers-v1-scytale-newline-nbsp-retained
    assert_equal "A\t\n ", cipher.decrypt("A \t \n ", 3)
    # classical-ciphers-v1-scytale-empty-before-low-key
    assert_equal "", cipher.encrypt("", -1)
    # classical-ciphers-v1-scytale-empty-before-high-key
    assert_equal "", cipher.decrypt("", 8194)
    # classical-ciphers-v1-scytale-invalid-low-key
    assert_raises(ArgumentError) { cipher.encrypt("A", 1) }
    # classical-ciphers-v1-scytale-invalid-high-key
    assert_raises(ArgumentError) { cipher.decrypt("ABC", 4) }
    # classical-ciphers-v1-scytale-brute-force-ascending
    assert_equal [{ key: 2, text: "HOLDWLL ERO" }, { key: 3, text: "HELLO WORLD" }, { key: 4, text: "HLO LEDRWOL" }, { key: 5, text: "HLOLRLED  WO" }, { key: 6, text: "HWEOLRLLOD" }], cipher.brute_force("HLWLEOODL R ")
    # classical-ciphers-v1-scytale-brute-force-short
    assert_equal [], cipher.brute_force("ABC")
    # classical-ciphers-v1-scytale-brute-force-preflight-limit
    error = assert_raises(ArgumentError) { cipher.brute_force("A" * 4097) }
    assert_equal "scytale-brute-force-limit", error.message
  end
end
