# AUTO-GENERATED FILE - DO NOT EDIT
from grammar_tools.token_grammar import TokenGrammar, TokenDefinition, PatternGroup

CssTokens = TokenGrammar(
    version=1,
    case_insensitive=False,
    case_sensitive=True,
    escape_mode="none",
    definitions=[
        TokenDefinition(name="STRING_DQ", pattern="\"([^\"\\\\\\n]|\\\\.)*\"", is_regex=True, line_number=67, alias="STRING"),
        TokenDefinition(name="STRING_SQ", pattern="'([^'\\\\\\n]|\\\\.)*'", is_regex=True, line_number=68, alias="STRING"),
        TokenDefinition(name="DIMENSION", pattern="-?[0-9]*\\.?[0-9]+([eE][+-]?[0-9]+)?[a-zA-Z]+", is_regex=True, line_number=94),
        TokenDefinition(name="PERCENTAGE", pattern="-?[0-9]*\\.?[0-9]+([eE][+-]?[0-9]+)?%", is_regex=True, line_number=95),
        TokenDefinition(name="NUMBER", pattern="-?[0-9]*\\.?[0-9]+([eE][+-]?[0-9]+)?", is_regex=True, line_number=96),
        TokenDefinition(name="HASH", pattern="#[a-zA-Z0-9_-]+", is_regex=True, line_number=109),
        TokenDefinition(name="AT_KEYWORD", pattern="@-?[a-zA-Z][a-zA-Z0-9-]*", is_regex=True, line_number=123),
        TokenDefinition(name="URL_TOKEN", pattern="url\\([^)'\"]*\\)", is_regex=True, line_number=136),
        TokenDefinition(name="FUNCTION", pattern="-?[a-zA-Z_][a-zA-Z0-9_-]*\\(", is_regex=True, line_number=149),
        TokenDefinition(name="CDO", pattern="<!--", is_regex=False, line_number=162),
        TokenDefinition(name="CDC", pattern="-->", is_regex=False, line_number=163),
        TokenDefinition(name="UNICODE_RANGE", pattern="[Uu]\\+[0-9a-fA-F?]{1,6}(-[0-9a-fA-F]{1,6})?", is_regex=True, line_number=190),
        TokenDefinition(name="CUSTOM_PROPERTY", pattern="--[a-zA-Z_][a-zA-Z0-9_-]*", is_regex=True, line_number=192),
        TokenDefinition(name="IDENT", pattern="-?[a-zA-Z_][a-zA-Z0-9_-]*", is_regex=True, line_number=193),
        TokenDefinition(name="COLON_COLON", pattern="::", is_regex=False, line_number=202),
        TokenDefinition(name="TILDE_EQUALS", pattern="~=", is_regex=False, line_number=203),
        TokenDefinition(name="PIPE_EQUALS", pattern="|=", is_regex=False, line_number=204),
        TokenDefinition(name="CARET_EQUALS", pattern="^=", is_regex=False, line_number=205),
        TokenDefinition(name="DOLLAR_EQUALS", pattern="$=", is_regex=False, line_number=206),
        TokenDefinition(name="STAR_EQUALS", pattern="*=", is_regex=False, line_number=207),
        TokenDefinition(name="LBRACE", pattern="{", is_regex=False, line_number=216),
        TokenDefinition(name="RBRACE", pattern="}", is_regex=False, line_number=217),
        TokenDefinition(name="LPAREN", pattern="(", is_regex=False, line_number=218),
        TokenDefinition(name="RPAREN", pattern=")", is_regex=False, line_number=219),
        TokenDefinition(name="LBRACKET", pattern="[", is_regex=False, line_number=220),
        TokenDefinition(name="RBRACKET", pattern="]", is_regex=False, line_number=221),
        TokenDefinition(name="SEMICOLON", pattern=";", is_regex=False, line_number=222),
        TokenDefinition(name="COLON", pattern=":", is_regex=False, line_number=223),
        TokenDefinition(name="COMMA", pattern=",", is_regex=False, line_number=224),
        TokenDefinition(name="DOT", pattern=".", is_regex=False, line_number=225),
        TokenDefinition(name="PLUS", pattern="+", is_regex=False, line_number=226),
        TokenDefinition(name="GREATER", pattern=">", is_regex=False, line_number=227),
        TokenDefinition(name="TILDE", pattern="~", is_regex=False, line_number=228),
        TokenDefinition(name="STAR", pattern="*", is_regex=False, line_number=229),
        TokenDefinition(name="PIPE", pattern="|", is_regex=False, line_number=230),
        TokenDefinition(name="BANG", pattern="!", is_regex=False, line_number=231),
        TokenDefinition(name="SLASH", pattern="/", is_regex=False, line_number=232),
        TokenDefinition(name="EQUALS", pattern="=", is_regex=False, line_number=233),
        TokenDefinition(name="AMPERSAND", pattern="&", is_regex=False, line_number=234),
        TokenDefinition(name="MINUS", pattern="-", is_regex=False, line_number=235),
    ],
    skip_definitions=[
        TokenDefinition(name="COMMENT", pattern="\\/\\*[\\s\\S]*?\\*\\/", is_regex=True, line_number=51),
        TokenDefinition(name="WHITESPACE", pattern="[ \\t\\r\\n]+", is_regex=True, line_number=52),
    ],
    error_definitions=[
        TokenDefinition(name="BAD_STRING", pattern="\"[^\"]*$", is_regex=True, line_number=251),
        TokenDefinition(name="BAD_URL", pattern="url\\([^)]*$", is_regex=True, line_number=252),
    ],
)
