local af = require("src.activation_functions")

describe("activation_functions", function()
  it("sigmoid", function()
    assert.is_true(math.abs(af.sigmoid(0) - 0.5) < 0.0001)
  end)
  it("relu", function()
    assert.are.equal(5.0, af.relu(5))
    assert.are.equal(0.0, af.relu(-5))
  end)
  it("tanh", function()
    assert.is_true(math.abs(af.tanh(0) - 0.0) < 0.0001)
  end)
end)
