"""logic-builtins — Prolog-inspired control and term predicates.

The functions in this package return ordinary `logic-engine` goals. They are
the first state-aware builtins layer for the library-first Prolog path.
"""

from logic_builtins.builtins import (
    add,
    argo,
    atomico,
    atomo,
    bagofo,
    callableo,
    callo,
    clauseo,
    compoundo,
    copytermo,
    div,
    failo,
    findallo,
    floordiv,
    forallo,
    functoro,
    geqo,
    groundo,
    gto,
    ifthenelseo,
    iftheno,
    iso,
    leqo,
    lto,
    mod,
    mul,
    neg,
    nonvaro,
    noto,
    numbero,
    numeqo,
    numneqo,
    onceo,
    same_termo,
    setofo,
    stringo,
    sub,
    trueo,
    univo,
    varo,
)

__all__ = [
    "__version__",
    "add",
    "argo",
    "atomico",
    "atomo",
    "bagofo",
    "callo",
    "callableo",
    "clauseo",
    "compoundo",
    "copytermo",
    "div",
    "failo",
    "findallo",
    "floordiv",
    "forallo",
    "functoro",
    "geqo",
    "gto",
    "groundo",
    "ifthenelseo",
    "iftheno",
    "iso",
    "leqo",
    "lto",
    "mod",
    "mul",
    "neg",
    "nonvaro",
    "noto",
    "numeqo",
    "numneqo",
    "numbero",
    "onceo",
    "same_termo",
    "setofo",
    "stringo",
    "sub",
    "trueo",
    "univo",
    "varo",
]

__version__ = "0.6.0"
