// AUTO-GENERATED FILE — DO NOT EDIT
// Source: lattice.tokens
// Regenerate with: grammar-tools compile-tokens lattice.tokens
//
// This file embeds a TokenGrammar as native TypeScript object literals.
// Import it directly instead of reading and parsing the .tokens file at
// runtime.

import type { TokenGrammar } from "@coding-adventures/grammar-tools";

export const TOKEN_GRAMMAR: TokenGrammar = {
  version: 1,
  caseInsensitive: false,
  caseSensitive: true,
  definitions: [
    {
      name: "STRING_DQ",
      pattern: "\"([^\"\\\\\\n]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 66,
      alias: "STRING",
    },
    {
      name: "STRING_SQ",
      pattern: "'([^'\\\\\\n]|\\\\.)*'",
      isRegex: true,
      lineNumber: 67,
      alias: "STRING",
    },
    {
      name: "VARIABLE",
      pattern: "\\$[a-zA-Z_][a-zA-Z0-9_-]*",
      isRegex: true,
      lineNumber: 83,
    },
    {
      name: "PLACEHOLDER",
      pattern: "%[a-zA-Z_][a-zA-Z0-9_-]*",
      isRegex: true,
      lineNumber: 93,
    },
    {
      name: "DIMENSION",
      pattern: "-?[0-9]*\\.?[0-9]+([eE][+-]?[0-9]+)?[a-zA-Z]+",
      isRegex: true,
      lineNumber: 102,
    },
    {
      name: "PERCENTAGE",
      pattern: "-?[0-9]*\\.?[0-9]+([eE][+-]?[0-9]+)?%",
      isRegex: true,
      lineNumber: 103,
    },
    {
      name: "NUMBER",
      pattern: "-?[0-9]*\\.?[0-9]+([eE][+-]?[0-9]+)?",
      isRegex: true,
      lineNumber: 104,
    },
    {
      name: "HASH",
      pattern: "#[a-zA-Z0-9_-]+",
      isRegex: true,
      lineNumber: 110,
    },
    {
      name: "AT_KEYWORD",
      pattern: "@-?[a-zA-Z][a-zA-Z0-9-]*",
      isRegex: true,
      lineNumber: 127,
    },
    {
      name: "URL_TOKEN",
      pattern: "url\\([^)'\"]*\\)",
      isRegex: true,
      lineNumber: 133,
    },
    {
      name: "FUNCTION",
      pattern: "-?[a-zA-Z_][a-zA-Z0-9_-]*\\(",
      isRegex: true,
      lineNumber: 139,
    },
    {
      name: "CDO",
      pattern: "<!--",
      isRegex: false,
      lineNumber: 145,
    },
    {
      name: "CDC",
      pattern: "-->",
      isRegex: false,
      lineNumber: 146,
    },
    {
      name: "UNICODE_RANGE",
      pattern: "[Uu]\\+[0-9a-fA-F?]{1,6}(-[0-9a-fA-F]{1,6})?",
      isRegex: true,
      lineNumber: 152,
    },
    {
      name: "CUSTOM_PROPERTY",
      pattern: "--[a-zA-Z_][a-zA-Z0-9_-]*",
      isRegex: true,
      lineNumber: 153,
    },
    {
      name: "IDENT",
      pattern: "-?[a-zA-Z_][a-zA-Z0-9_-]*",
      isRegex: true,
      lineNumber: 154,
    },
    {
      name: "COLON_COLON",
      pattern: "::",
      isRegex: false,
      lineNumber: 163,
    },
    {
      name: "TILDE_EQUALS",
      pattern: "~=",
      isRegex: false,
      lineNumber: 164,
    },
    {
      name: "PIPE_EQUALS",
      pattern: "|=",
      isRegex: false,
      lineNumber: 165,
    },
    {
      name: "CARET_EQUALS",
      pattern: "^=",
      isRegex: false,
      lineNumber: 166,
    },
    {
      name: "DOLLAR_EQUALS",
      pattern: "$=",
      isRegex: false,
      lineNumber: 167,
    },
    {
      name: "STAR_EQUALS",
      pattern: "*=",
      isRegex: false,
      lineNumber: 168,
    },
    {
      name: "EQUALS_EQUALS",
      pattern: "==",
      isRegex: false,
      lineNumber: 171,
    },
    {
      name: "NOT_EQUALS",
      pattern: "!=",
      isRegex: false,
      lineNumber: 172,
    },
    {
      name: "GREATER_EQUALS",
      pattern: ">=",
      isRegex: false,
      lineNumber: 173,
    },
    {
      name: "LESS_EQUALS",
      pattern: "<=",
      isRegex: false,
      lineNumber: 174,
    },
    {
      name: "LBRACE",
      pattern: "{",
      isRegex: false,
      lineNumber: 180,
    },
    {
      name: "RBRACE",
      pattern: "}",
      isRegex: false,
      lineNumber: 181,
    },
    {
      name: "LPAREN",
      pattern: "(",
      isRegex: false,
      lineNumber: 182,
    },
    {
      name: "RPAREN",
      pattern: ")",
      isRegex: false,
      lineNumber: 183,
    },
    {
      name: "LBRACKET",
      pattern: "[",
      isRegex: false,
      lineNumber: 184,
    },
    {
      name: "RBRACKET",
      pattern: "]",
      isRegex: false,
      lineNumber: 185,
    },
    {
      name: "SEMICOLON",
      pattern: ";",
      isRegex: false,
      lineNumber: 186,
    },
    {
      name: "COLON",
      pattern: ":",
      isRegex: false,
      lineNumber: 187,
    },
    {
      name: "COMMA",
      pattern: ",",
      isRegex: false,
      lineNumber: 188,
    },
    {
      name: "DOT",
      pattern: ".",
      isRegex: false,
      lineNumber: 189,
    },
    {
      name: "PLUS",
      pattern: "+",
      isRegex: false,
      lineNumber: 190,
    },
    {
      name: "GREATER",
      pattern: ">",
      isRegex: false,
      lineNumber: 191,
    },
    {
      name: "LESS",
      pattern: "<",
      isRegex: false,
      lineNumber: 192,
    },
    {
      name: "TILDE",
      pattern: "~",
      isRegex: false,
      lineNumber: 193,
    },
    {
      name: "STAR",
      pattern: "*",
      isRegex: false,
      lineNumber: 194,
    },
    {
      name: "PIPE",
      pattern: "|",
      isRegex: false,
      lineNumber: 195,
    },
    {
      name: "BANG_DEFAULT",
      pattern: "!default",
      isRegex: false,
      lineNumber: 198,
    },
    {
      name: "BANG_GLOBAL",
      pattern: "!global",
      isRegex: false,
      lineNumber: 199,
    },
    {
      name: "BANG",
      pattern: "!",
      isRegex: false,
      lineNumber: 200,
    },
    {
      name: "SLASH",
      pattern: "/",
      isRegex: false,
      lineNumber: 201,
    },
    {
      name: "EQUALS",
      pattern: "=",
      isRegex: false,
      lineNumber: 202,
    },
    {
      name: "AMPERSAND",
      pattern: "&",
      isRegex: false,
      lineNumber: 203,
    },
    {
      name: "MINUS",
      pattern: "-",
      isRegex: false,
      lineNumber: 204,
    },
  ],
  keywords: [],
  mode: undefined,
  escapeMode: "none",
  skipDefinitions: [
    {
      name: "LINE_COMMENT",
      pattern: "\\/\\/[^\\n]*",
      isRegex: true,
      lineNumber: 55,
    },
    {
      name: "COMMENT",
      pattern: "\\/\\*[\\s\\S]*?\\*\\/",
      isRegex: true,
      lineNumber: 56,
    },
    {
      name: "WHITESPACE",
      pattern: "[ \\t\\r\\n]+",
      isRegex: true,
      lineNumber: 57,
    },
  ],
  reservedKeywords: [],
  layoutKeywords: [],
  contextKeywords: [],
  errorDefinitions: [],
  groups: {},
};
