# AUTO-GENERATED FILE - DO NOT EDIT
defmodule ExcelGrammar do
  alias CodingAdventures.GrammarTools.ParserGrammar

  def grammar do
    %ParserGrammar{
      version: 1,
      rules: [
        %{name: "formula", line_number: 15, body: {:sequence, [{:rule_reference, "ws", false}, {:optional, {:sequence, [{:rule_reference, "EQUALS", true}, {:rule_reference, "ws", false}]}}, {:rule_reference, "expression", false}, {:rule_reference, "ws", false}]}},
        %{name: "ws", line_number: 17, body: {:repetition, {:rule_reference, "SPACE", true}}},
        %{name: "req_space", line_number: 18, body: {:sequence, [{:rule_reference, "SPACE", true}, {:repetition, {:rule_reference, "SPACE", true}}]}},
        %{name: "expression", line_number: 20, body: {:rule_reference, "comparison_expr", false}},
        %{name: "comparison_expr", line_number: 22, body: {:sequence, [{:rule_reference, "concat_expr", false}, {:repetition, {:sequence, [{:rule_reference, "ws", false}, {:rule_reference, "comparison_op", false}, {:rule_reference, "ws", false}, {:rule_reference, "concat_expr", false}]}}]}},
        %{name: "comparison_op", line_number: 23, body: {:alternation, [{:rule_reference, "EQUALS", true}, {:rule_reference, "NOT_EQUALS", true}, {:rule_reference, "LESS_THAN", true}, {:rule_reference, "LESS_EQUALS", true}, {:rule_reference, "GREATER_THAN", true}, {:rule_reference, "GREATER_EQUALS", true}]}},
        %{name: "concat_expr", line_number: 26, body: {:sequence, [{:rule_reference, "additive_expr", false}, {:repetition, {:sequence, [{:rule_reference, "ws", false}, {:rule_reference, "AMP", true}, {:rule_reference, "ws", false}, {:rule_reference, "additive_expr", false}]}}]}},
        %{name: "additive_expr", line_number: 27, body: {:sequence, [{:rule_reference, "multiplicative_expr", false}, {:repetition, {:sequence, [{:rule_reference, "ws", false}, {:group, {:alternation, [{:rule_reference, "PLUS", true}, {:rule_reference, "MINUS", true}]}}, {:rule_reference, "ws", false}, {:rule_reference, "multiplicative_expr", false}]}}]}},
        %{name: "multiplicative_expr", line_number: 28, body: {:sequence, [{:rule_reference, "power_expr", false}, {:repetition, {:sequence, [{:rule_reference, "ws", false}, {:group, {:alternation, [{:rule_reference, "STAR", true}, {:rule_reference, "SLASH", true}]}}, {:rule_reference, "ws", false}, {:rule_reference, "power_expr", false}]}}]}},
        %{name: "power_expr", line_number: 29, body: {:sequence, [{:rule_reference, "unary_expr", false}, {:repetition, {:sequence, [{:rule_reference, "ws", false}, {:rule_reference, "CARET", true}, {:rule_reference, "ws", false}, {:rule_reference, "unary_expr", false}]}}]}},
        %{name: "unary_expr", line_number: 30, body: {:sequence, [{:repetition, {:sequence, [{:rule_reference, "prefix_op", false}, {:rule_reference, "ws", false}]}}, {:rule_reference, "postfix_expr", false}]}},
        %{name: "prefix_op", line_number: 31, body: {:alternation, [{:rule_reference, "PLUS", true}, {:rule_reference, "MINUS", true}]}},
        %{name: "postfix_expr", line_number: 32, body: {:sequence, [{:rule_reference, "primary", false}, {:repetition, {:sequence, [{:rule_reference, "ws", false}, {:rule_reference, "PERCENT", true}]}}]}},
        %{name: "primary", line_number: 34, body: {:alternation, [{:rule_reference, "parenthesized_expression", false}, {:rule_reference, "constant", false}, {:rule_reference, "function_call", false}, {:rule_reference, "structure_reference", false}, {:rule_reference, "reference_expression", false}, {:rule_reference, "bang_reference", false}, {:rule_reference, "bang_name", false}, {:rule_reference, "name_reference", false}]}},
        %{name: "parenthesized_expression", line_number: 43, body: {:sequence, [{:rule_reference, "LPAREN", true}, {:rule_reference, "ws", false}, {:rule_reference, "expression", false}, {:rule_reference, "ws", false}, {:rule_reference, "RPAREN", true}]}},
        %{name: "constant", line_number: 45, body: {:alternation, [{:rule_reference, "NUMBER", true}, {:rule_reference, "STRING", true}, {:rule_reference, "KEYWORD", true}, {:rule_reference, "ERROR_CONSTANT", true}, {:rule_reference, "array_constant", false}]}},
        %{name: "array_constant", line_number: 47, body: {:sequence, [{:rule_reference, "LBRACE", true}, {:rule_reference, "ws", false}, {:rule_reference, "array_row", false}, {:repetition, {:sequence, [{:rule_reference, "ws", false}, {:rule_reference, "SEMICOLON", true}, {:rule_reference, "ws", false}, {:rule_reference, "array_row", false}]}}, {:optional, {:sequence, [{:rule_reference, "ws", false}, {:rule_reference, "SEMICOLON", true}]}}, {:rule_reference, "ws", false}, {:rule_reference, "RBRACE", true}]}},
        %{name: "array_row", line_number: 48, body: {:sequence, [{:rule_reference, "array_item", false}, {:repetition, {:sequence, [{:rule_reference, "ws", false}, {:rule_reference, "COMMA", true}, {:rule_reference, "ws", false}, {:rule_reference, "array_item", false}]}}, {:optional, {:sequence, [{:rule_reference, "ws", false}, {:rule_reference, "COMMA", true}]}}]}},
        %{name: "array_item", line_number: 49, body: {:alternation, [{:rule_reference, "NUMBER", true}, {:rule_reference, "STRING", true}, {:rule_reference, "KEYWORD", true}, {:rule_reference, "ERROR_CONSTANT", true}]}},
        %{name: "function_call", line_number: 51, body: {:sequence, [{:rule_reference, "function_name", false}, {:rule_reference, "LPAREN", true}, {:rule_reference, "ws", false}, {:optional, {:rule_reference, "function_argument_list", false}}, {:rule_reference, "ws", false}, {:rule_reference, "RPAREN", true}]}},
        %{name: "function_name", line_number: 52, body: {:alternation, [{:rule_reference, "FUNCTION_NAME", true}, {:rule_reference, "NAME", true}]}},
        %{name: "function_argument_list", line_number: 53, body: {:sequence, [{:rule_reference, "function_argument", false}, {:repetition, {:sequence, [{:rule_reference, "ws", false}, {:rule_reference, "COMMA", true}, {:rule_reference, "ws", false}, {:rule_reference, "function_argument", false}]}}, {:optional, {:sequence, [{:rule_reference, "ws", false}, {:rule_reference, "COMMA", true}]}}]}},
        %{name: "function_argument", line_number: 54, body: {:optional, {:rule_reference, "expression", false}}},
        %{name: "reference_expression", line_number: 56, body: {:rule_reference, "union_reference", false}},
        %{name: "union_reference", line_number: 57, body: {:sequence, [{:rule_reference, "intersection_reference", false}, {:repetition, {:sequence, [{:rule_reference, "ws", false}, {:rule_reference, "COMMA", true}, {:rule_reference, "ws", false}, {:rule_reference, "intersection_reference", false}]}}]}},
        %{name: "intersection_reference", line_number: 58, body: {:sequence, [{:rule_reference, "range_reference", false}, {:repetition, {:sequence, [{:rule_reference, "req_space", false}, {:rule_reference, "range_reference", false}]}}]}},
        %{name: "range_reference", line_number: 59, body: {:sequence, [{:rule_reference, "reference_primary", false}, {:optional, {:sequence, [{:rule_reference, "ws", false}, {:rule_reference, "COLON", true}, {:rule_reference, "ws", false}, {:rule_reference, "reference_primary", false}]}}]}},
        %{name: "reference_primary", line_number: 61, body: {:alternation, [{:rule_reference, "parenthesized_reference", false}, {:rule_reference, "prefixed_reference", false}, {:rule_reference, "external_reference", false}, {:rule_reference, "structure_reference", false}, {:rule_reference, "a1_reference", false}, {:rule_reference, "bang_reference", false}, {:rule_reference, "bang_name", false}, {:rule_reference, "name_reference", false}]}},
        %{name: "parenthesized_reference", line_number: 70, body: {:sequence, [{:rule_reference, "LPAREN", true}, {:rule_reference, "ws", false}, {:rule_reference, "reference_expression", false}, {:rule_reference, "ws", false}, {:rule_reference, "RPAREN", true}]}},
        %{name: "prefixed_reference", line_number: 71, body: {:sequence, [{:rule_reference, "REF_PREFIX", true}, {:group, {:alternation, [{:rule_reference, "a1_reference", false}, {:rule_reference, "name_reference", false}, {:rule_reference, "structure_reference", false}]}}]}},
        %{name: "external_reference", line_number: 72, body: {:rule_reference, "REF_PREFIX", true}},
        %{name: "bang_reference", line_number: 73, body: {:sequence, [{:rule_reference, "BANG", true}, {:group, {:alternation, [{:rule_reference, "CELL", true}, {:rule_reference, "COLUMN_REF", true}, {:rule_reference, "ROW_REF", true}, {:rule_reference, "NUMBER", true}]}}]}},
        %{name: "bang_name", line_number: 74, body: {:sequence, [{:rule_reference, "BANG", true}, {:rule_reference, "name_reference", false}]}},
        %{name: "name_reference", line_number: 75, body: {:rule_reference, "NAME", true}},
        %{name: "column_reference", line_number: 77, body: {:sequence, [{:optional, {:rule_reference, "DOLLAR", true}}, {:group, {:alternation, [{:rule_reference, "COLUMN_REF", true}, {:rule_reference, "NAME", true}]}}]}},
        %{name: "row_reference", line_number: 78, body: {:sequence, [{:optional, {:rule_reference, "DOLLAR", true}}, {:group, {:alternation, [{:rule_reference, "ROW_REF", true}, {:rule_reference, "NUMBER", true}]}}]}},
        %{name: "a1_reference", line_number: 80, body: {:alternation, [{:rule_reference, "CELL", true}, {:rule_reference, "column_reference", false}, {:rule_reference, "row_reference", false}, {:rule_reference, "COLUMN_REF", true}, {:rule_reference, "ROW_REF", true}, {:rule_reference, "NAME", true}, {:rule_reference, "NUMBER", true}]}},
        %{name: "structure_reference", line_number: 82, body: {:sequence, [{:optional, {:rule_reference, "table_name", false}}, {:rule_reference, "intra_table_reference", false}]}},
        %{name: "table_name", line_number: 83, body: {:alternation, [{:rule_reference, "TABLE_NAME", true}, {:rule_reference, "NAME", true}]}},
        %{name: "intra_table_reference", line_number: 84, body: {:alternation, [{:rule_reference, "STRUCTURED_KEYWORD", true}, {:rule_reference, "structured_column_range", false}, {:sequence, [{:rule_reference, "LBRACKET", true}, {:rule_reference, "ws", false}, {:optional, {:rule_reference, "inner_structure_reference", false}}, {:rule_reference, "ws", false}, {:rule_reference, "RBRACKET", true}]}]}},
        %{name: "inner_structure_reference", line_number: 87, body: {:alternation, [{:sequence, [{:rule_reference, "structured_keyword_list", false}, {:optional, {:sequence, [{:rule_reference, "ws", false}, {:rule_reference, "COMMA", true}, {:rule_reference, "ws", false}, {:rule_reference, "structured_column_range", false}]}}]}, {:rule_reference, "structured_column_range", false}]}},
        %{name: "structured_keyword_list", line_number: 89, body: {:sequence, [{:rule_reference, "STRUCTURED_KEYWORD", true}, {:repetition, {:sequence, [{:rule_reference, "ws", false}, {:rule_reference, "COMMA", true}, {:rule_reference, "ws", false}, {:rule_reference, "STRUCTURED_KEYWORD", true}]}}]}},
        %{name: "structured_column_range", line_number: 90, body: {:sequence, [{:rule_reference, "structured_column", false}, {:optional, {:sequence, [{:rule_reference, "ws", false}, {:rule_reference, "COLON", true}, {:rule_reference, "ws", false}, {:rule_reference, "structured_column", false}]}}]}},
        %{name: "structured_column", line_number: 91, body: {:alternation, [{:rule_reference, "STRUCTURED_COLUMN", true}, {:sequence, [{:rule_reference, "AT", true}, {:rule_reference, "STRUCTURED_COLUMN", true}]}]}}
      ]
    }
  end
end
