# frozen_string_literal: true
# AUTO-GENERATED FILE — DO NOT EDIT
# Source: algol60.tokens
# Regenerate with: grammar-tools compile-tokens algol60.tokens
#
# This file embeds a TokenGrammar as native Ruby data structures.
# Downstream packages require this file directly instead of reading
# and parsing the .tokens file at runtime.

require "coding_adventures_grammar_tools"

GT = CodingAdventures::GrammarTools unless defined?(GT)

TOKEN_GRAMMAR = GT::TokenGrammar.new(
  version: 1,
  case_insensitive: false,
  case_sensitive: true,
  definitions: [
      GT::TokenDefinition.new(
        name: "REAL_LIT",
        pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?|[0-9]+[eE][+-]?[0-9]+",
        is_regex: true,
        line_number: 38,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "INTEGER_LIT",
        pattern: "[0-9]+",
        is_regex: true,
        line_number: 41,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STRING_LIT",
        pattern: "'[^']*'|\"[^\"]*\"",
        is_regex: true,
        line_number: 46,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NAME",
        pattern: "[a-zA-Z][a-zA-Z0-9]*",
        is_regex: true,
        line_number: 53,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "ASSIGN",
        pattern: ":=",
        is_regex: false,
        line_number: 61,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "POWER",
        pattern: "**",
        is_regex: false,
        line_number: 66,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LEQ",
        pattern: "<=|≤",
        is_regex: true,
        line_number: 70,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GEQ",
        pattern: ">=|≥",
        is_regex: true,
        line_number: 71,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NEQ",
        pattern: "!=|<>|≠",
        is_regex: true,
        line_number: 72,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NOT_SYM",
        pattern: "¬",
        is_regex: false,
        line_number: 76,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AND_SYM",
        pattern: "∧",
        is_regex: false,
        line_number: 77,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "OR_SYM",
        pattern: "∨",
        is_regex: false,
        line_number: 78,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "IMPL_SYM",
        pattern: "⊃",
        is_regex: false,
        line_number: 79,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQV_SYM",
        pattern: "≡",
        is_regex: false,
        line_number: 80,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS",
        pattern: "+",
        is_regex: false,
        line_number: 86,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS",
        pattern: "-",
        is_regex: false,
        line_number: 87,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR",
        pattern: "\\*|×",
        is_regex: true,
        line_number: 90,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SLASH",
        pattern: "\\/|÷",
        is_regex: true,
        line_number: 91,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CARET",
        pattern: "\\^|↑",
        is_regex: true,
        line_number: 95,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQ",
        pattern: "=",
        is_regex: false,
        line_number: 98,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LT",
        pattern: "<",
        is_regex: false,
        line_number: 100,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GT",
        pattern: ">",
        is_regex: false,
        line_number: 101,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LPAREN",
        pattern: "(",
        is_regex: false,
        line_number: 107,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RPAREN",
        pattern: ")",
        is_regex: false,
        line_number: 108,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACKET",
        pattern: "[",
        is_regex: false,
        line_number: 109,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACKET",
        pattern: "]",
        is_regex: false,
        line_number: 110,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SEMICOLON",
        pattern: ";",
        is_regex: false,
        line_number: 111,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COMMA",
        pattern: ",",
        is_regex: false,
        line_number: 112,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COLON",
        pattern: ":",
        is_regex: false,
        line_number: 116,
        alias_name: nil,
      ),
    ],
  keywords: ["begin", "end", "if", "then", "else", "for", "do", "step", "until", "while", "goto", "switch", "procedure", "own", "array", "label", "value", "integer", "real", "boolean", "string", "true", "false", "not", "and", "or", "impl", "eqv", "div", "mod", "comment"],
  mode: nil,
  escape_mode: nil,
  skip_definitions: [
      GT::TokenDefinition.new(
        name: "WHITESPACE",
        pattern: "[ \\t\\r\\n]+",
        is_regex: true,
        line_number: 183,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COMMENT",
        pattern: "comment[^a-zA-Z0-9_][^;]*;",
        is_regex: true,
        line_number: 192,
        alias_name: nil,
      ),
    ],
  reserved_keywords: [],
  error_definitions: [],
  groups: {},
  layout_keywords: [],
  context_keywords: [],
  soft_keywords: [],
)
