name: coding_adventures_zstd
description: >
  ZStd (RFC 8878) lossless compression algorithm from scratch — CMP07.
version: 0.1.0
repository: https://github.com/adhithyan15/coding-adventures
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  coding_adventures_lzss:
    path: ../lzss

dev_dependencies:
  test: ^1.25.0
