// Code generated by grammar-tools. DO NOT EDIT.
// Source: code/grammars/xml/xml.tokens
//
// Embeds the grammar(s) as native Swift so the lexer/parser never reads
// code/grammars/** at run time. Regenerate from swift/grammar-tools with:
//   swift run grammar-tools-embed tokens <output> EmbeddedGrammar <label>=<file> ...

import GrammarTools

enum EmbeddedGrammar {
    /// Embedded grammars keyed by the version label the loader passes.
    static let tokenGrammars: [String: TokenGrammar] = [
        "xml": xml,
    ]

    static let xml: TokenGrammar = TokenGrammar(
    definitions: [
        TokenDefinition(name: "TEXT", pattern: "[^<&]+", isRegex: true, lineNumber: 77, alias: nil),
        TokenDefinition(name: "ENTITY_REF", pattern: "&[a-zA-Z][a-zA-Z0-9]*;", isRegex: true, lineNumber: 78, alias: nil),
        TokenDefinition(name: "CHAR_REF_HEX", pattern: "&#x[0-9a-fA-F]+;", isRegex: true, lineNumber: 85, alias: "CHAR_REF"),
        TokenDefinition(name: "CHAR_REF_DEC", pattern: "&#[0-9]+;", isRegex: true, lineNumber: 86, alias: "CHAR_REF"),
        TokenDefinition(name: "COMMENT_START", pattern: "<!--", isRegex: false, lineNumber: 88, alias: nil),
        TokenDefinition(name: "CDATA_START", pattern: "<![CDATA[", isRegex: false, lineNumber: 89, alias: nil),
        TokenDefinition(name: "PI_START", pattern: "<?", isRegex: false, lineNumber: 90, alias: nil),
        TokenDefinition(name: "CLOSE_TAG_START", pattern: "</", isRegex: false, lineNumber: 91, alias: nil),
        TokenDefinition(name: "OPEN_TAG_START", pattern: "<", isRegex: false, lineNumber: 92, alias: nil),
    ],
    keywords: [],
    mode: nil,
    escapeMode: "none",
    skipDefinitions: [
        TokenDefinition(name: "WHITESPACE", pattern: "[ \\t\\r\\n]+", isRegex: true, lineNumber: 62, alias: nil),
    ],
    reservedKeywords: nil,
    contextKeywords: nil,
    layoutKeywords: nil,
    groups: [
        "cdata": PatternGroup(
            name: "cdata",
            definitions: [
                TokenDefinition(name: "CDATA_END", pattern: "]]>", isRegex: false, lineNumber: 150, alias: nil),
                TokenDefinition(name: "CDATA_TEXT", pattern: "[^\\]]+", isRegex: true, lineNumber: 151, alias: nil),
                TokenDefinition(name: "CDATA_BRACK", pattern: "]", isRegex: true, lineNumber: 152, alias: "CDATA_TEXT"),
            ]),
        "comment": PatternGroup(
            name: "comment",
            definitions: [
                TokenDefinition(name: "COMMENT_END", pattern: "-->", isRegex: false, lineNumber: 133, alias: nil),
                TokenDefinition(name: "COMMENT_TEXT", pattern: "[^-]+", isRegex: true, lineNumber: 134, alias: nil),
                TokenDefinition(name: "COMMENT_DASH", pattern: "-", isRegex: true, lineNumber: 135, alias: "COMMENT_TEXT"),
            ]),
        "pi": PatternGroup(
            name: "pi",
            definitions: [
                TokenDefinition(name: "PI_END", pattern: "?>", isRegex: false, lineNumber: 184, alias: nil),
                TokenDefinition(name: "PI_TARGET", pattern: "[a-zA-Z_][a-zA-Z0-9_:.-]*", isRegex: true, lineNumber: 185, alias: nil),
            ]),
        "pi_body": PatternGroup(
            name: "pi_body",
            definitions: [
                TokenDefinition(name: "PI_END", pattern: "?>", isRegex: false, lineNumber: 188, alias: nil),
                TokenDefinition(name: "PI_TEXT", pattern: "[^?]+", isRegex: true, lineNumber: 189, alias: nil),
                TokenDefinition(name: "PI_QMARK", pattern: "\\?", isRegex: true, lineNumber: 190, alias: "PI_TEXT"),
            ]),
        "tag": PatternGroup(
            name: "tag",
            definitions: [
                TokenDefinition(name: "TAG_NAME", pattern: "[a-zA-Z_][a-zA-Z0-9_:.-]*", isRegex: true, lineNumber: 107, alias: nil),
                TokenDefinition(name: "ATTR_EQUALS", pattern: "=", isRegex: false, lineNumber: 108, alias: nil),
                TokenDefinition(name: "ATTR_VALUE_DQ", pattern: "\"[^\"]*\"", isRegex: true, lineNumber: 109, alias: "ATTR_VALUE"),
                TokenDefinition(name: "ATTR_VALUE_SQ", pattern: "'[^']*'", isRegex: true, lineNumber: 110, alias: "ATTR_VALUE"),
                TokenDefinition(name: "TAG_CLOSE", pattern: ">", isRegex: false, lineNumber: 111, alias: nil),
                TokenDefinition(name: "SELF_CLOSE", pattern: "/>", isRegex: false, lineNumber: 112, alias: nil),
                TokenDefinition(name: "SLASH", pattern: "/", isRegex: false, lineNumber: 113, alias: nil),
            ]),
    ],
    caseSensitive: nil,
    version: 1,
    caseInsensitive: false)
}
