"""Symbolic IR — the universal expression tree for computer algebra systems.

Every CAS frontend (MACSYMA, Mathematica, Maple, REDUCE, SymPy syntax)
compiles to this single IR. Every CAS backend (strict evaluation,
symbolic rewriting, LaTeX rendering, transpilation) consumes this IR.

The IR has exactly six node types:

- ``IRSymbol(name)``        — an identifier: ``x``, ``%pi``, ``Add``.
- ``IRInteger(value)``      — an arbitrary-precision integer.
- ``IRRational(n, d)``      — an exact fraction, always reduced.
- ``IRFloat(value)``        — a double-precision float.
- ``IRString(value)``       — a string literal.
- ``IRApply(head, args)``   — an operation: head(args...).

All nodes are immutable and hashable. The compound form is always
``IRApply`` — there are no `BinaryOp` or `FunctionCall` sub-types. The
head of an ``IRApply`` is always an ``IRSymbol`` (by convention), which
keeps the structure uniformly Lisp-like.

Example::

    from symbolic_ir import IRSymbol, IRInteger, IRApply, ADD, POW

    # Represent x^2 + 1
    x = IRSymbol("x")
    expr = IRApply(ADD, (IRApply(POW, (x, IRInteger(2))), IRInteger(1)))
"""

from symbolic_ir.nodes import (
    ACOS,
    ACOSH,
    ADD,
    ALG_FACTOR,
    AND,
    APPLY1,
    APPLY2,
    ASIN,
    ASINH,
    ASSIGN,
    ASSUME,
    ATAN,
    ATANH,
    BETA_FUNC,
    BLOCK,
    C1,
    C2,
    C_CONST,
    CHI,
    CI,
    COS,
    COSH,
    COTH,
    CSCH,
    DEFINE,
    DEFRULE,
    DEMOIVRE,
    DIRAC_DELTA,
    DIV,
    EQUAL,
    ERF,
    ERFC,
    ERFI,
    EXP,
    EXPONENTIALIZE,
    FOR_EACH,
    FOR_RANGE,
    FORGET,
    FREE_INTEGER,
    FOURIER,
    FRESNEL_C,
    FRESNEL_S,
    GAMMA_FUNC,
    GREATER,
    GREATER_EQUAL,
    GROEBNER,
    IDEAL_SOLVE,
    IF,
    IFOURIER,
    ILT,
    INTEGRATE,
    INV,
    IS,
    LAMBERT_W,
    LAPLACE,
    LESS,
    LESS_EQUAL,
    LI2,
    LIST,
    LOG,
    LOGCONTRACT,
    LOGEXPAND,
    MATCHDECLARE,
    MNEWTON,
    MUL,
    NEG,
    NOT,
    NOT_EQUAL,
    ODE2,
    OR,
    POLY_REDUCE,
    POW,
    RADCAN,
    RETURN,
    RULE,
    SECH,
    SHI,
    SI,
    SIGN,
    SIN,
    SINH,
    SQRT,
    SUB,
    TAN,
    TANH,
    TELLSIMP,
    FREE_INTEGER,
    LAMBERT_W,
    PRODUCT,
    SUM,
    UNIT_STEP,
    WHILE,
    D,
    IRApply,
    IRFloat,
    IRInteger,
    IRNode,
    IRRational,
    IRString,
    IRSymbol,
)

__all__ = [
    "IRNode",
    "IRSymbol",
    "IRInteger",
    "IRRational",
    "IRFloat",
    "IRString",
    "IRApply",
    # Standard head symbols
    "ACOS",
    "ALG_FACTOR",
    "ACOSH",
    "ASIN",
    "ASINH",
    "ATAN",
    "ATANH",
    "ADD",
    "SUB",
    "MUL",
    "DIV",
    "POW",
    "NEG",
    "INV",
    "EXP",
    "LOG",
    "SIN",
    "SINH",
    "COS",
    "COSH",
    "TAN",
    "TANH",
    # Reciprocal hyperbolic functions (Phase 15)
    "COTH",
    "SECH",
    "CSCH",
    "SQRT",
    "D",
    "INTEGRATE",
    "EQUAL",
    "NOT_EQUAL",
    "LESS",
    "GREATER",
    "LESS_EQUAL",
    "GREATER_EQUAL",
    "AND",
    "OR",
    "NOT",
    "IF",
    "LIST",
    "ASSIGN",
    "DEFINE",
    "RULE",
    # Control flow (Phase G)
    "WHILE",
    "FOR_RANGE",
    "FOR_EACH",
    "BLOCK",
    "RETURN",
    # Numeric root-finding
    "MNEWTON",
    # Laplace / Fourier transforms
    "DIRAC_DELTA",
    "UNIT_STEP",
    "LAPLACE",
    "ILT",
    "FOURIER",
    "IFOURIER",
    # ODE solving (cas-ode)
    "ODE2",
    "C_CONST",
    "C1",
    "C2",
    # Multivariate polynomial operations (cas-multivariate)
    "GROEBNER",
    "POLY_REDUCE",
    "IDEAL_SOLVE",
    # Simplification operations (Phase 21)
    "ASSUME",
    "FORGET",
    "IS",
    "SIGN",
    "RADCAN",
    "LOGCONTRACT",
    "LOGEXPAND",
    "EXPONENTIALIZE",
    "DEMOIVRE",
    # Pattern-matching operations (Phase 22)
    "MATCHDECLARE",
    "DEFRULE",
    "APPLY1",
    "APPLY2",
    "TELLSIMP",
    # Special functions (Phase 23)
    "ERF",
    "ERFC",
    "ERFI",
    "SI",
    "CI",
    "SHI",
    "CHI",
    "LI2",
    "GAMMA_FUNC",
    "BETA_FUNC",
    "FRESNEL_S",
    "FRESNEL_C",
    # Summation and product (Phase 25)
    "SUM",
    "PRODUCT",
    # Transcendental solving (Phase 26)
    "FREE_INTEGER",
    "LAMBERT_W",
]
