# frozen_string_literal: true

source "https://rubygems.org"

gem "coding_adventures_repl", path: "../../../packages/ruby/repl"

group :test do
  gem "minitest", "~> 5.0"
  gem "rake",     "~> 13.0"
end
