# AUTO-GENERATED FILE — DO NOT EDIT
# Source: xml.tokens
# Regenerate with: grammar-tools compile-tokens <source.tokens>
#
# This file embeds a TokenGrammar as native Python data structures.
# Downstream packages import TOKEN_GRAMMAR directly instead of
# reading and parsing the .tokens file at runtime.

from grammar_tools.token_grammar import PatternGroup, TokenDefinition, TokenGrammar

# fmt: off  # noqa: E501 — generated code may have long lines

TOKEN_GRAMMAR = TokenGrammar(
    version=1,
    case_insensitive=False,
    case_sensitive=True,
    definitions=[
        TokenDefinition(
            name='TEXT',
            pattern='[^<&]+',
            is_regex=True,
            line_number=57,
            alias=None,
        ),
        TokenDefinition(
            name='ENTITY_REF',
            pattern='&[a-zA-Z][a-zA-Z0-9]*;',
            is_regex=True,
            line_number=58,
            alias=None,
        ),
        TokenDefinition(
            name='CHAR_REF',
            pattern='&#[0-9]+;|&#x[0-9a-fA-F]+;',
            is_regex=True,
            line_number=59,
            alias=None,
        ),
        TokenDefinition(
            name='COMMENT_START',
            pattern='<!--',
            is_regex=False,
            line_number=60,
            alias=None,
        ),
        TokenDefinition(
            name='CDATA_START',
            pattern='<![CDATA[',
            is_regex=False,
            line_number=61,
            alias=None,
        ),
        TokenDefinition(
            name='PI_START',
            pattern='<?',
            is_regex=False,
            line_number=62,
            alias=None,
        ),
        TokenDefinition(
            name='CLOSE_TAG_START',
            pattern='</',
            is_regex=False,
            line_number=63,
            alias=None,
        ),
        TokenDefinition(
            name='OPEN_TAG_START',
            pattern='<',
            is_regex=False,
            line_number=64,
            alias=None,
        ),
    ],
    keywords=[],
    mode=None,
    escape_mode='none',
    skip_definitions=[
        TokenDefinition(
            name='WHITESPACE',
            pattern='[ \\t\\r\\n]+',
            is_regex=True,
            line_number=42,
            alias=None,
        ),
    ],
    reserved_keywords=[],
    error_definitions=[],
    groups={
        'tag': PatternGroup(
            name='tag',
            definitions=[
                TokenDefinition(
                    name='TAG_NAME',
                    pattern='[a-zA-Z_][a-zA-Z0-9_:.-]*',
                    is_regex=True,
                    line_number=79,
                    alias=None,
                ),
                TokenDefinition(
                    name='ATTR_EQUALS',
                    pattern='=',
                    is_regex=False,
                    line_number=80,
                    alias=None,
                ),
                TokenDefinition(
                    name='ATTR_VALUE_DQ',
                    pattern='"[^"]*"',
                    is_regex=True,
                    line_number=81,
                    alias='ATTR_VALUE',
                ),
                TokenDefinition(
                    name='ATTR_VALUE_SQ',
                    pattern="'[^']*'",
                    is_regex=True,
                    line_number=82,
                    alias='ATTR_VALUE',
                ),
                TokenDefinition(
                    name='TAG_CLOSE',
                    pattern='>',
                    is_regex=False,
                    line_number=83,
                    alias=None,
                ),
                TokenDefinition(
                    name='SELF_CLOSE',
                    pattern='/>',
                    is_regex=False,
                    line_number=84,
                    alias=None,
                ),
                TokenDefinition(
                    name='SLASH',
                    pattern='/',
                    is_regex=False,
                    line_number=85,
                    alias=None,
                ),
            ],
        ),,
        'comment': PatternGroup(
            name='comment',
            definitions=[
                TokenDefinition(
                    name='COMMENT_TEXT',
                    pattern='([^-]|-(?!->))+',
                    is_regex=True,
                    line_number=99,
                    alias=None,
                ),
                TokenDefinition(
                    name='COMMENT_END',
                    pattern='-->',
                    is_regex=False,
                    line_number=100,
                    alias=None,
                ),
            ],
        ),,
        'cdata': PatternGroup(
            name='cdata',
            definitions=[
                TokenDefinition(
                    name='CDATA_TEXT',
                    pattern='([^\\]]|\\](?!\\]>))+',
                    is_regex=True,
                    line_number=113,
                    alias=None,
                ),
                TokenDefinition(
                    name='CDATA_END',
                    pattern=']]>',
                    is_regex=False,
                    line_number=114,
                    alias=None,
                ),
            ],
        ),,
        'pi': PatternGroup(
            name='pi',
            definitions=[
                TokenDefinition(
                    name='PI_TARGET',
                    pattern='[a-zA-Z_][a-zA-Z0-9_:.-]*',
                    is_regex=True,
                    line_number=128,
                    alias=None,
                ),
                TokenDefinition(
                    name='PI_TEXT',
                    pattern='([^?]|\\?(?!>))+',
                    is_regex=True,
                    line_number=129,
                    alias=None,
                ),
                TokenDefinition(
                    name='PI_END',
                    pattern='?>',
                    is_regex=False,
                    line_number=130,
                    alias=None,
                ),
            ],
        ),
    },
    layout_keywords=[],
)
