# GENERATED by code/scripts/generate_atbash_fixture_consumers.py.
# Source SHA-256: efd6c3a85a0c1d0676c31bf709d7c3d7eb5f4aef6b31ac2f904ebad6d76ad02c
# Cases: classical-ciphers-v1-atbash-empty, classical-ciphers-v1-atbash-uppercase-alphabet, classical-ciphers-v1-atbash-lowercase-alphabet, classical-ciphers-v1-atbash-passthrough, classical-ciphers-v1-atbash-involution-forward, classical-ciphers-v1-atbash-involution-reverse

defmodule CodingAdventures.GeneratedAtbashFixtureTest do
  use ExUnit.Case
  alias CodingAdventures.AtbashCipher

  test "executes complete normative Atbash objects" do
    s = fn scalars -> List.to_string(scalars) end
    cases = [
      {"classical-ciphers-v1-atbash-empty", s.([]), s.([])},
      {"classical-ciphers-v1-atbash-uppercase-alphabet", s.([65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90]), s.([90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65])},
      {"classical-ciphers-v1-atbash-lowercase-alphabet", s.([97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122]), s.([122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112, 111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100, 99, 98, 97])},
      {"classical-ciphers-v1-atbash-passthrough", s.([72, 101, 108, 108, 111, 44, 32, 87, 111, 114, 108, 100, 33, 32, 49, 50, 51, 0, 32, 233, 128512]), s.([83, 118, 111, 111, 108, 44, 32, 68, 108, 105, 111, 119, 33, 32, 49, 50, 51, 0, 32, 233, 128512])},
      {"classical-ciphers-v1-atbash-involution-forward", s.([72, 69, 76, 76, 79]), s.([83, 86, 79, 79, 76])},
      {"classical-ciphers-v1-atbash-involution-reverse", s.([83, 86, 79, 79, 76]), s.([72, 69, 76, 76, 79])},
    ]

    for {id, input, expected} <- cases do
      assert AtbashCipher.encrypt(input) == expected, id
    end
  end
end
