cd ../../../packages/typescript/directed-graph && npm ci --quiet
cd ../../../packages/typescript/cli-builder && npm ci --quiet
cd ../../../packages/typescript/grammar-tools && npm ci --quiet
cd ../../../packages/typescript/state-machine && npm ci --quiet
cd ../../../packages/typescript/lexer && npm ci --quiet
cd ../../../packages/typescript/parser && npm ci --quiet
cd ../../../packages/typescript/symbolic-ir && npm ci --quiet
cd ../../../packages/typescript/symbolic-vm && npm ci --quiet
cd ../../../packages/typescript/macsyma-lexer && npm ci --quiet
cd ../../../packages/typescript/macsyma-parser && npm ci --quiet
cd ../../../packages/typescript/macsyma-compiler && npm ci --quiet
cd ../../../packages/typescript/cas-list-operations && npm ci --quiet
cd ../../../packages/typescript/cas-solve && npm ci --quiet
cd ../../../packages/typescript/cas-substitution && npm ci --quiet
cd ../../../packages/typescript/macsyma-runtime && npm ci --quiet
npm ci --quiet
npm run build
npx vitest run --coverage
