// main.qml — VisiCalc Qt host (VC2-qt).
//
// Mounts the auto-generated `FormulaBar` from build/ and a
// hand-written grid block below it. Hard-coded 5×5 sample
// spreadsheet matches the data in VC2-html / VC2-webcomp /
// VC2-flutter so all four demos look visually identical.
//
// Run:
//   qml main.qml          # one-shot QML viewer (Qt 6)
//   # or via CMake:
//   cmake -B build && cmake --build build && ./build/visicalc-qt

import QtQuick 2.15
import QtQuick.Window 2.15
import QtQuick.Controls 2.15
import QtQuick.Layouts 1.15

// FormulaBar.qml lives under `build/` (regenerated by
// scripts/build.sh). The relative import path picks it up
// because qmldir lists `FormulaBar 1.0 build/FormulaBar.qml`.
import "build"

Window {
    width: 720
    height: 520
    visible: true
    title: "VisiCalc — Mosaic Qt demo"
    color: "#1E1E1E"

    // Host state — mirrors the Flutter / React reducer pattern at
    // smaller scale. The 5×5 sample spreadsheet is hard-coded; tap
    // on a cell to select it and pull its value into the formula bar.
    property var sampleRows: [
        ["15", "3",  "12", "8",  "5"],
        ["8",  "14", "7",  "22", "11"],
        ["12", "9",  "18", "6",  "25"],
        ["4",  "11", "3",  "17", "9"],
        ["7",  "5",  "13", "10", "19"]
    ]
    property int selectedRow: 0
    property int selectedCol: 0
    property string formulaText: "=SUM(B1:B5)"

    function cellAddress() {
        return String.fromCharCode(65 + selectedCol) + (selectedRow + 1);
    }

    ColumnLayout {
        anchors.fill: parent
        spacing: 0

        // Title bar.
        Text {
            Layout.fillWidth: true
            Layout.leftMargin: 16
            Layout.topMargin: 16
            text: "VISICALC · MOSAIC QT DEMO"
            color: "#9D9D9D"
            font.pixelSize: 11
            font.letterSpacing: 1.0
        }

        // FormulaBar — the AUTO-GENERATED component from
        // build/FormulaBar.qml. Two-way wiring: the host pushes
        // `cellAddress` / `formula` into properties, and listens
        // for `formulaChange` / `commit` / `cancel` signals.
        FormulaBar {
            id: formulaBar
            Layout.fillWidth: true
            Layout.topMargin: 8
            cellAddress: window.cellAddress()
            formula: window.formulaText
            readOnly: false

            onFormulaChange: (value) => window.formulaText = value
            onCommit: { /* no-op for v1; keeps the formula text as-is */ }
            onCancel: { window.formulaText = window.sampleRows[window.selectedRow][window.selectedCol] }
        }

        // Grid — HAND-WRITTEN placeholder (mosaic-emit-qt's pipeline
        // doesn't yet support the `Grid` built-in primitive; only the
        // React emitter does). Visual contract matches Grid.dark.msl.
        Rectangle {
            id: gridContainer
            Layout.fillWidth: true
            Layout.fillHeight: true
            Layout.margins: 16
            color: "#1E1E1E"
            border.color: "#3F3F46"
            border.width: 1

            ColumnLayout {
                anchors.fill: parent
                spacing: 0

                // Header row: row-label cell + column-letter cells.
                RowLayout {
                    Layout.fillWidth: true
                    Layout.preferredHeight: 24
                    spacing: 0
                    Repeater {
                        model: ["", "A", "B", "C", "D", "E"]
                        Rectangle {
                            Layout.preferredWidth: 96
                            Layout.preferredHeight: 24
                            color: "#2D2D30"
                            border.color: "#3F3F46"
                            border.width: 1
                            Text {
                                anchors.centerIn: parent
                                text: modelData
                                color: "#9D9D9D"
                                font.family: "monospace"
                                font.pixelSize: 12
                            }
                        }
                    }
                }

                // Data rows. We loop 5×5 with nested Repeaters.
                Repeater {
                    model: window.sampleRows.length
                    RowLayout {
                        property int rowIdx: index
                        Layout.fillWidth: true
                        Layout.preferredHeight: 22
                        spacing: 0

                        // Leading row-label cell.
                        Rectangle {
                            Layout.preferredWidth: 96
                            Layout.preferredHeight: 22
                            color: "#2D2D30"
                            border.color: "#3F3F46"
                            border.width: 1
                            Text {
                                anchors.centerIn: parent
                                text: (rowIdx + 1).toString()
                                color: "#9D9D9D"
                                font.family: "monospace"
                                font.pixelSize: 12
                            }
                        }

                        // Data cells for this row.
                        Repeater {
                            model: window.sampleRows[rowIdx]
                            Rectangle {
                                property int colIdx: index
                                property bool isSelected:
                                    rowIdx === window.selectedRow &&
                                    colIdx === window.selectedCol
                                Layout.preferredWidth: 96
                                Layout.preferredHeight: 22
                                color: isSelected ? "#264F78" : (rowIdx % 2 === 0 ? "#1E1E1E" : "#252526")
                                border.color: isSelected ? "#007ACC" : "#3F3F46"
                                border.width: 1
                                Text {
                                    anchors.right: parent.right
                                    anchors.rightMargin: 4
                                    anchors.verticalCenter: parent.verticalCenter
                                    text: modelData
                                    color: isSelected ? "white" : "#CCCCCC"
                                    font.family: "monospace"
                                    font.pixelSize: 12
                                }
                                MouseArea {
                                    anchors.fill: parent
                                    onClicked: {
                                        window.selectedRow = rowIdx;
                                        window.selectedCol = colIdx;
                                        window.formulaText = window.sampleRows[rowIdx][colIdx];
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
