-- Tests for coding_adventures.point2d
package.path = "../src/?.lua;../src/?/init.lua;../../trig/src/?.lua;../../trig/src/?/init.lua;" .. package.path

local p2d = require("coding_adventures.point2d")

local DELTA = 1e-9
local function approx(a, b) return math.abs(a - b) < DELTA end
local function pt_approx(a, b) return approx(a.x, b.x) and approx(a.y, b.y) end

describe("point2d", function()
    it("add", function()
        local p = p2d.add(p2d.new_point(1, 2), p2d.new_point(3, 4))
        assert.is_true(pt_approx(p, p2d.new_point(4, 6)))
    end)
    it("subtract", function()
        local p = p2d.subtract(p2d.new_point(5, 3), p2d.new_point(2, 1))
        assert.is_true(pt_approx(p, p2d.new_point(3, 2)))
    end)
    it("scale", function()
        local p = p2d.scale(p2d.new_point(2, 3), 2)
        assert.is_true(pt_approx(p, p2d.new_point(4, 6)))
    end)
    it("negate", function()
        local p = p2d.negate(p2d.new_point(1, -2))
        assert.is_true(pt_approx(p, p2d.new_point(-1, 2)))
    end)
    it("dot", function()
        assert.is_true(approx(p2d.dot(p2d.new_point(1, 2), p2d.new_point(3, 4)), 11))
    end)
    it("cross", function()
        assert.is_true(approx(p2d.cross(p2d.new_point(1, 2), p2d.new_point(3, 4)), -2))
    end)
    it("magnitude", function()
        assert.is_true(approx(p2d.magnitude(p2d.new_point(3, 4)), 5))
    end)
    it("normalize", function()
        local n = p2d.normalize(p2d.new_point(3, 4))
        assert.is_true(approx(p2d.magnitude(n), 1))
    end)
    it("normalize zero", function()
        local n = p2d.normalize(p2d.new_point(0, 0))
        assert.is_true(approx(n.x, 0) and approx(n.y, 0))
    end)
    it("distance", function()
        assert.is_true(approx(p2d.distance(p2d.new_point(0, 0), p2d.new_point(3, 4)), 5))
    end)
    it("lerp mid", function()
        local p = p2d.lerp(p2d.new_point(0, 0), p2d.new_point(10, 0), 0.5)
        assert.is_true(approx(p.x, 5))
    end)
    it("perpendicular", function()
        local pp = p2d.perpendicular(p2d.new_point(1, 0))
        assert.is_true(pt_approx(pp, p2d.new_point(0, 1)))
    end)
    it("angle", function()
        local trig = require("coding_adventures.trig")
        assert.is_true(approx(p2d.angle(p2d.new_point(1, 1)), trig.PI / 4))
    end)
end)

describe("rect", function()
    local r = p2d.new_rect(0, 0, 10, 10)
    it("contains inside", function()
        assert.is_true(p2d.contains_point(r, p2d.new_point(5, 5)))
    end)
    it("contains outside", function()
        assert.is_false(p2d.contains_point(r, p2d.new_point(10, 5)))
    end)
    it("union", function()
        local r2 = p2d.new_rect(5, 5, 10, 10)
        local u = p2d.rect_union(r, r2)
        assert.is_true(approx(u.x, 0) and approx(u.width, 15))
    end)
    it("intersection exists", function()
        local r2 = p2d.new_rect(5, 5, 10, 10)
        local i = p2d.rect_intersection(r, r2)
        assert.is_not_nil(i)
        assert.is_true(approx(i.x, 5) and approx(i.width, 5))
    end)
    it("intersection disjoint", function()
        local r2 = p2d.new_rect(20, 20, 5, 5)
        assert.is_nil(p2d.rect_intersection(r, r2))
    end)
    it("expand", function()
        local e = p2d.rect_expand(r, 2)
        assert.is_true(approx(e.x, -2) and approx(e.width, 14))
    end)
end)
