cd ../../../packages/typescript/irc-proto && npm install --silent
cd ../../../packages/typescript/irc-framing && npm install --silent
cd ../../../packages/typescript/irc-server && npm install --silent
cd ../../../packages/typescript/irc-net-stdlib && npm install --silent
npm install --silent
npx tsc --noEmit
