// THIS FILE IS GENERATED.  Edit Grid.{mil,desktop.mll,dark.msl}
// and re-run scripts/build.sh to regenerate.

package com.example.visicalc

// Auto-generated by mosaic-emit-compose. Do not edit.

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.material.Button
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier

sealed class GridEvent {
    data class Navigate(val row: Double, val col: Double) : GridEvent()
    data class FormulaChange(val value: String) : GridEvent()
    data object EditCommit : GridEvent()
    data object EditCancel : GridEvent()
}

@Composable
fun Grid(
    columnHeaders: List<String>,
    viewportRows: List<List<String>>,
    columnWidths: List<Double>,
    totalHeight: Double,
    selectedRow: Double,
    selectedCol: Double,
    editRow: Double,
    editCol: Double,
    editContent: String,
    dispatch: (GridEvent) -> Unit,
) {
    Column(modifier = Modifier.fillMaxWidth()) {
        Column(modifier = Modifier.fillMaxWidth()) {
            columnWidths.forEachIndexed { _kotlinIdxcw, w ->
                val cw: Double = _kotlinIdxcw.toDouble()
                // Col (column-width hint — no Compose analog)
            }
        }
        Column(modifier = Modifier.fillMaxWidth()) {
            Row(modifier = Modifier.fillMaxWidth()) {
                columnHeaders.forEachIndexed { _kotlinIdxch, h ->
                    val ch: Double = _kotlinIdxch.toDouble()
                    Box(modifier = Modifier.fillMaxWidth()) {
                        Text(text = ( h ))
                    }
                }
            }
        }
        Column(modifier = Modifier.fillMaxWidth()) {
            viewportRows.forEachIndexed { _kotlinIdxr, row ->
                val r: Double = _kotlinIdxr.toDouble()
                Row(modifier = Modifier.fillMaxWidth()) {
                    row.forEachIndexed { _kotlinIdxc, v ->
                        val c: Double = _kotlinIdxc.toDouble()
                        Box(modifier = Modifier.fillMaxWidth()) {
                            if (( r == editRow && c == editCol )) {
                                BasicTextField(
                                    value = editContent,
                                    onValueChange = { v -> dispatch(GridEvent.FormulaChange(v)) },
                                )
                            } else {
                                Text(text = ( v ))
                            }
                        }
                    }
                }
            }
        }
    }
}
