// AUTO-GENERATED FILE - DO NOT EDIT
package latticelexer

import (
	grammartools "github.com/adhithyan15/coding-adventures/code/packages/go/grammar-tools"
)

var LatticeTokens = &grammartools.TokenGrammar{
	Version: 1,
	CaseInsensitive: false,
	CaseSensitive: true,
	EscapeMode: "none",
	Definitions: []grammartools.TokenDefinition{
		grammartools.TokenDefinition{Name: "STRING_DQ", Pattern: "\"([^\"\\\\\\n]|\\\\.)*\"", IsRegex: true, LineNumber: 66, Alias: "STRING"},
		grammartools.TokenDefinition{Name: "STRING_SQ", Pattern: "'([^'\\\\\\n]|\\\\.)*'", IsRegex: true, LineNumber: 67, Alias: "STRING"},
		grammartools.TokenDefinition{Name: "VARIABLE", Pattern: "\\$[a-zA-Z_][a-zA-Z0-9_-]*", IsRegex: true, LineNumber: 83, Alias: ""},
		grammartools.TokenDefinition{Name: "PLACEHOLDER", Pattern: "%[a-zA-Z_][a-zA-Z0-9_-]*", IsRegex: true, LineNumber: 93, Alias: ""},
		grammartools.TokenDefinition{Name: "DIMENSION", Pattern: "-?[0-9]*\\.?[0-9]+([eE][+-]?[0-9]+)?[a-zA-Z]+", IsRegex: true, LineNumber: 102, Alias: ""},
		grammartools.TokenDefinition{Name: "PERCENTAGE", Pattern: "-?[0-9]*\\.?[0-9]+([eE][+-]?[0-9]+)?%", IsRegex: true, LineNumber: 103, Alias: ""},
		grammartools.TokenDefinition{Name: "NUMBER", Pattern: "-?[0-9]*\\.?[0-9]+([eE][+-]?[0-9]+)?", IsRegex: true, LineNumber: 104, Alias: ""},
		grammartools.TokenDefinition{Name: "HASH", Pattern: "#[a-zA-Z0-9_-]+", IsRegex: true, LineNumber: 110, Alias: ""},
		grammartools.TokenDefinition{Name: "AT_KEYWORD", Pattern: "@-?[a-zA-Z][a-zA-Z0-9-]*", IsRegex: true, LineNumber: 127, Alias: ""},
		grammartools.TokenDefinition{Name: "URL_TOKEN", Pattern: "url\\([^)'\"]*\\)", IsRegex: true, LineNumber: 133, Alias: ""},
		grammartools.TokenDefinition{Name: "FUNCTION", Pattern: "-?[a-zA-Z_][a-zA-Z0-9_-]*\\(", IsRegex: true, LineNumber: 139, Alias: ""},
		grammartools.TokenDefinition{Name: "CDO", Pattern: "<!--", IsRegex: false, LineNumber: 145, Alias: ""},
		grammartools.TokenDefinition{Name: "CDC", Pattern: "-->", IsRegex: false, LineNumber: 146, Alias: ""},
		grammartools.TokenDefinition{Name: "UNICODE_RANGE", Pattern: "[Uu]\\+[0-9a-fA-F?]{1,6}(-[0-9a-fA-F]{1,6})?", IsRegex: true, LineNumber: 152, Alias: ""},
		grammartools.TokenDefinition{Name: "CUSTOM_PROPERTY", Pattern: "--[a-zA-Z_][a-zA-Z0-9_-]*", IsRegex: true, LineNumber: 153, Alias: ""},
		grammartools.TokenDefinition{Name: "IDENT", Pattern: "-?[a-zA-Z_][a-zA-Z0-9_-]*", IsRegex: true, LineNumber: 154, Alias: ""},
		grammartools.TokenDefinition{Name: "COLON_COLON", Pattern: "::", IsRegex: false, LineNumber: 163, Alias: ""},
		grammartools.TokenDefinition{Name: "TILDE_EQUALS", Pattern: "~=", IsRegex: false, LineNumber: 164, Alias: ""},
		grammartools.TokenDefinition{Name: "PIPE_EQUALS", Pattern: "|=", IsRegex: false, LineNumber: 165, Alias: ""},
		grammartools.TokenDefinition{Name: "CARET_EQUALS", Pattern: "^=", IsRegex: false, LineNumber: 166, Alias: ""},
		grammartools.TokenDefinition{Name: "DOLLAR_EQUALS", Pattern: "$=", IsRegex: false, LineNumber: 167, Alias: ""},
		grammartools.TokenDefinition{Name: "STAR_EQUALS", Pattern: "*=", IsRegex: false, LineNumber: 168, Alias: ""},
		grammartools.TokenDefinition{Name: "EQUALS_EQUALS", Pattern: "==", IsRegex: false, LineNumber: 171, Alias: ""},
		grammartools.TokenDefinition{Name: "NOT_EQUALS", Pattern: "!=", IsRegex: false, LineNumber: 172, Alias: ""},
		grammartools.TokenDefinition{Name: "GREATER_EQUALS", Pattern: ">=", IsRegex: false, LineNumber: 173, Alias: ""},
		grammartools.TokenDefinition{Name: "LESS_EQUALS", Pattern: "<=", IsRegex: false, LineNumber: 174, Alias: ""},
		grammartools.TokenDefinition{Name: "LBRACE", Pattern: "{", IsRegex: false, LineNumber: 180, Alias: ""},
		grammartools.TokenDefinition{Name: "RBRACE", Pattern: "}", IsRegex: false, LineNumber: 181, Alias: ""},
		grammartools.TokenDefinition{Name: "LPAREN", Pattern: "(", IsRegex: false, LineNumber: 182, Alias: ""},
		grammartools.TokenDefinition{Name: "RPAREN", Pattern: ")", IsRegex: false, LineNumber: 183, Alias: ""},
		grammartools.TokenDefinition{Name: "LBRACKET", Pattern: "[", IsRegex: false, LineNumber: 184, Alias: ""},
		grammartools.TokenDefinition{Name: "RBRACKET", Pattern: "]", IsRegex: false, LineNumber: 185, Alias: ""},
		grammartools.TokenDefinition{Name: "SEMICOLON", Pattern: ";", IsRegex: false, LineNumber: 186, Alias: ""},
		grammartools.TokenDefinition{Name: "COLON", Pattern: ":", IsRegex: false, LineNumber: 187, Alias: ""},
		grammartools.TokenDefinition{Name: "COMMA", Pattern: ",", IsRegex: false, LineNumber: 188, Alias: ""},
		grammartools.TokenDefinition{Name: "DOT", Pattern: ".", IsRegex: false, LineNumber: 189, Alias: ""},
		grammartools.TokenDefinition{Name: "PLUS", Pattern: "+", IsRegex: false, LineNumber: 190, Alias: ""},
		grammartools.TokenDefinition{Name: "GREATER", Pattern: ">", IsRegex: false, LineNumber: 191, Alias: ""},
		grammartools.TokenDefinition{Name: "LESS", Pattern: "<", IsRegex: false, LineNumber: 192, Alias: ""},
		grammartools.TokenDefinition{Name: "TILDE", Pattern: "~", IsRegex: false, LineNumber: 193, Alias: ""},
		grammartools.TokenDefinition{Name: "STAR", Pattern: "*", IsRegex: false, LineNumber: 194, Alias: ""},
		grammartools.TokenDefinition{Name: "PIPE", Pattern: "|", IsRegex: false, LineNumber: 195, Alias: ""},
		grammartools.TokenDefinition{Name: "BANG_DEFAULT", Pattern: "!default", IsRegex: false, LineNumber: 198, Alias: ""},
		grammartools.TokenDefinition{Name: "BANG_GLOBAL", Pattern: "!global", IsRegex: false, LineNumber: 199, Alias: ""},
		grammartools.TokenDefinition{Name: "BANG", Pattern: "!", IsRegex: false, LineNumber: 200, Alias: ""},
		grammartools.TokenDefinition{Name: "SLASH", Pattern: "/", IsRegex: false, LineNumber: 201, Alias: ""},
		grammartools.TokenDefinition{Name: "EQUALS", Pattern: "=", IsRegex: false, LineNumber: 202, Alias: ""},
		grammartools.TokenDefinition{Name: "AMPERSAND", Pattern: "&", IsRegex: false, LineNumber: 203, Alias: ""},
		grammartools.TokenDefinition{Name: "MINUS", Pattern: "-", IsRegex: false, LineNumber: 204, Alias: ""},
	},
	SkipDefinitions: []grammartools.TokenDefinition{
		grammartools.TokenDefinition{Name: "LINE_COMMENT", Pattern: "\\/\\/[^\\n]*", IsRegex: true, LineNumber: 55, Alias: ""},
		grammartools.TokenDefinition{Name: "COMMENT", Pattern: "\\/\\*[\\s\\S]*?\\*\\/", IsRegex: true, LineNumber: 56, Alias: ""},
		grammartools.TokenDefinition{Name: "WHITESPACE", Pattern: "[ \\t\\r\\n]+", IsRegex: true, LineNumber: 57, Alias: ""},
	},
}
