# extconf.rb -- Generate a Makefile that builds via cargo
# ======================================================
#
# Standard Ruby native extensions use mkmf to generate a Makefile that
# compiles C code. We skip mkmf entirely and generate a Makefile that
# invokes `cargo build --release` instead.
#
# The Makefile:
# 1. Runs cargo to produce a cdylib (.so on Linux, .dylib on macOS, .dll on Windows)
# 2. Copies the library to the gem's lib/ directory with the correct name
#
# Ruby expects the compiled extension at:
#   lib/commonmark_native.so     (Linux)
#   lib/commonmark_native.bundle (macOS)
#   lib/commonmark_native.dll    (Windows)

require "rbconfig"

# Determine the shared library extension for this platform
# (.so on Linux, .bundle on macOS, .dll on Windows)
dlext = RbConfig::CONFIG["DLEXT"]

# Determine cargo's output filename
# Cargo produces: libcommonmark_native.so (Linux), libcommonmark_native.dylib (macOS),
# commonmark_native.dll (Windows)
case RbConfig::CONFIG["host_os"]
when /darwin/
  cargo_lib = "libcommonmark_native.dylib"
when /mingw|mswin|cygwin/
  cargo_lib = "commonmark_native.dll"
else
  cargo_lib = "libcommonmark_native.so"
end

# The target filename Ruby will load
target = "commonmark_native.#{dlext}"

# Destination: the gem's lib/ directory (two levels up from ext/commonmark_native/)
lib_dir = File.expand_path("../../lib", __dir__)

# Write the Makefile
File.write("Makefile", <<~MAKEFILE)
  # Auto-generated by extconf.rb — do not edit.
  # This Makefile builds the Rust native extension via cargo.

  CARGO_DIR = #{File.expand_path(__dir__)}
  TARGET_DIR = $(CARGO_DIR)/target/release
  CARGO_LIB = $(TARGET_DIR)/#{cargo_lib}
  INSTALL_DIR = #{lib_dir}
  TARGET = $(INSTALL_DIR)/#{target}

  all: $(TARGET)

  $(TARGET): $(CARGO_LIB)
  \t@mkdir -p $(INSTALL_DIR)
  \tcp $(CARGO_LIB) $(TARGET)

  $(CARGO_LIB): src/lib.rs Cargo.toml
  \tcd $(CARGO_DIR) && cargo build --release

  clean:
  \tcd $(CARGO_DIR) && cargo clean
  \trm -f $(TARGET)

  install: $(TARGET)

  .PHONY: all clean install
MAKEFILE

puts "Makefile generated — will build via `cargo build --release`"
