// AUTO-GENERATED FILE - DO NOT EDIT
// Source: python3.0.tokens
// Regenerate with: grammar-tools compile-tokens python3.0.tokens
//
// This file embeds a TokenGrammar as native TypeScript object literals.
// Import it directly instead of reading and parsing the .tokens file at
// runtime.

import type { TokenGrammar } from "@coding-adventures/grammar-tools";

export const TOKEN_GRAMMAR: TokenGrammar = {
  version: 1,
  caseInsensitive: false,
  caseSensitive: true,
  definitions: [
    {
      name: "STRING_RAW_BYTES_TRIPLE_DQ",
      pattern: "[rR][bB]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"|[bB][rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 140,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_BYTES_TRIPLE_SQ",
      pattern: "[rR][bB]?'''([^'\\\\]|\\\\.|\\n)*'''|[bB][rR]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 141,
      alias: "STRING",
    },
    {
      name: "STRING_BYTES_TRIPLE_DQ",
      pattern: "[bB]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 144,
      alias: "STRING",
    },
    {
      name: "STRING_BYTES_TRIPLE_SQ",
      pattern: "[bB]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 145,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_TRIPLE_DQ",
      pattern: "[rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 148,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_TRIPLE_SQ",
      pattern: "[rR]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 149,
      alias: "STRING",
    },
    {
      name: "STRING_TRIPLE_DQ",
      pattern: "\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 152,
      alias: "STRING",
    },
    {
      name: "STRING_TRIPLE_SQ",
      pattern: "'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 153,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_BYTES_DQ",
      pattern: "[rR][bB]\"([^\"\\\\]|\\\\.)*\"|[bB][rR]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 158,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_BYTES_SQ",
      pattern: "[rR][bB]'([^'\\\\]|\\\\.)*'|[bB][rR]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 159,
      alias: "STRING",
    },
    {
      name: "STRING_BYTES_DQ",
      pattern: "[bB]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 162,
      alias: "STRING",
    },
    {
      name: "STRING_BYTES_SQ",
      pattern: "[bB]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 163,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_DQ",
      pattern: "[rR]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 166,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_SQ",
      pattern: "[rR]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 167,
      alias: "STRING",
    },
    {
      name: "STRING_DQ",
      pattern: "\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 170,
      alias: "STRING",
    },
    {
      name: "STRING_SQ",
      pattern: "'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 171,
      alias: "STRING",
    },
    {
      name: "IMAG_FLOAT_STD",
      pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?[jJ]",
      isRegex: true,
      lineNumber: 196,
      alias: "IMAG",
    },
    {
      name: "IMAG_FLOAT_DOT",
      pattern: "\\.[0-9]+([eE][+-]?[0-9]+)?[jJ]",
      isRegex: true,
      lineNumber: 197,
      alias: "IMAG",
    },
    {
      name: "IMAG_FLOAT_EXP",
      pattern: "[0-9]+[eE][+-]?[0-9]+[jJ]",
      isRegex: true,
      lineNumber: 198,
      alias: "IMAG",
    },
    {
      name: "IMAG_INT",
      pattern: "[0-9]+[jJ]",
      isRegex: true,
      lineNumber: 199,
      alias: "IMAG",
    },
    {
      name: "FLOAT_EXP",
      pattern: "[0-9]+[eE][+-]?[0-9]+",
      isRegex: true,
      lineNumber: 206,
      alias: "FLOAT",
    },
    {
      name: "FLOAT_DOT",
      pattern: "\\.[0-9]+([eE][+-]?[0-9]+)?",
      isRegex: true,
      lineNumber: 207,
      alias: "FLOAT",
    },
    {
      name: "FLOAT",
      pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?",
      isRegex: true,
      lineNumber: 208,
      alias: "FLOAT",
    },
    {
      name: "INT_HEX",
      pattern: "0[xX][0-9a-fA-F]+",
      isRegex: true,
      lineNumber: 213,
      alias: "INT",
    },
    {
      name: "INT_OCT",
      pattern: "0[oO][0-7]+",
      isRegex: true,
      lineNumber: 214,
      alias: "INT",
    },
    {
      name: "INT_BIN",
      pattern: "0[bB][01]+",
      isRegex: true,
      lineNumber: 215,
      alias: "INT",
    },
    {
      name: "INT",
      pattern: "[0-9]+",
      isRegex: true,
      lineNumber: 216,
    },
    {
      name: "ELLIPSIS",
      pattern: "...",
      isRegex: false,
      lineNumber: 237,
    },
    {
      name: "NAME",
      pattern: "[a-zA-Z_][a-zA-Z0-9_]*",
      isRegex: true,
      lineNumber: 252,
    },
    {
      name: "ARROW",
      pattern: "->",
      isRegex: false,
      lineNumber: 269,
    },
    {
      name: "DOUBLE_STAR_EQUALS",
      pattern: "**=",
      isRegex: false,
      lineNumber: 278,
    },
    {
      name: "LEFT_SHIFT_EQUALS",
      pattern: "<<=",
      isRegex: false,
      lineNumber: 279,
    },
    {
      name: "RIGHT_SHIFT_EQUALS",
      pattern: ">>=",
      isRegex: false,
      lineNumber: 280,
    },
    {
      name: "FLOOR_DIV_EQUALS",
      pattern: "//=",
      isRegex: false,
      lineNumber: 281,
    },
    {
      name: "DOUBLE_STAR",
      pattern: "**",
      isRegex: false,
      lineNumber: 298,
    },
    {
      name: "FLOOR_DIV",
      pattern: "//",
      isRegex: false,
      lineNumber: 299,
    },
    {
      name: "LEFT_SHIFT",
      pattern: "<<",
      isRegex: false,
      lineNumber: 300,
    },
    {
      name: "RIGHT_SHIFT",
      pattern: ">>",
      isRegex: false,
      lineNumber: 301,
    },
    {
      name: "EQUALS_EQUALS",
      pattern: "==",
      isRegex: false,
      lineNumber: 302,
    },
    {
      name: "NOT_EQUALS",
      pattern: "!=",
      isRegex: false,
      lineNumber: 303,
    },
    {
      name: "LESS_EQUALS",
      pattern: "<=",
      isRegex: false,
      lineNumber: 304,
    },
    {
      name: "GREATER_EQUALS",
      pattern: ">=",
      isRegex: false,
      lineNumber: 305,
    },
    {
      name: "PLUS_EQUALS",
      pattern: "+=",
      isRegex: false,
      lineNumber: 306,
    },
    {
      name: "MINUS_EQUALS",
      pattern: "-=",
      isRegex: false,
      lineNumber: 307,
    },
    {
      name: "STAR_EQUALS",
      pattern: "*=",
      isRegex: false,
      lineNumber: 308,
    },
    {
      name: "SLASH_EQUALS",
      pattern: "/=",
      isRegex: false,
      lineNumber: 309,
    },
    {
      name: "PERCENT_EQUALS",
      pattern: "%=",
      isRegex: false,
      lineNumber: 310,
    },
    {
      name: "AMP_EQUALS",
      pattern: "&=",
      isRegex: false,
      lineNumber: 311,
    },
    {
      name: "PIPE_EQUALS",
      pattern: "|=",
      isRegex: false,
      lineNumber: 312,
    },
    {
      name: "CARET_EQUALS",
      pattern: "^=",
      isRegex: false,
      lineNumber: 313,
    },
    {
      name: "PLUS",
      pattern: "+",
      isRegex: false,
      lineNumber: 325,
    },
    {
      name: "MINUS",
      pattern: "-",
      isRegex: false,
      lineNumber: 326,
    },
    {
      name: "STAR",
      pattern: "*",
      isRegex: false,
      lineNumber: 327,
    },
    {
      name: "SLASH",
      pattern: "/",
      isRegex: false,
      lineNumber: 328,
    },
    {
      name: "PERCENT",
      pattern: "%",
      isRegex: false,
      lineNumber: 329,
    },
    {
      name: "EQUALS",
      pattern: "=",
      isRegex: false,
      lineNumber: 330,
    },
    {
      name: "LESS_THAN",
      pattern: "<",
      isRegex: false,
      lineNumber: 331,
    },
    {
      name: "GREATER_THAN",
      pattern: ">",
      isRegex: false,
      lineNumber: 332,
    },
    {
      name: "AMP",
      pattern: "&",
      isRegex: false,
      lineNumber: 333,
    },
    {
      name: "PIPE",
      pattern: "|",
      isRegex: false,
      lineNumber: 334,
    },
    {
      name: "CARET",
      pattern: "^",
      isRegex: false,
      lineNumber: 335,
    },
    {
      name: "TILDE",
      pattern: "~",
      isRegex: false,
      lineNumber: 336,
    },
    {
      name: "AT",
      pattern: "@",
      isRegex: false,
      lineNumber: 337,
    },
    {
      name: "LPAREN",
      pattern: "(",
      isRegex: false,
      lineNumber: 351,
    },
    {
      name: "RPAREN",
      pattern: ")",
      isRegex: false,
      lineNumber: 352,
    },
    {
      name: "LBRACKET",
      pattern: "[",
      isRegex: false,
      lineNumber: 353,
    },
    {
      name: "RBRACKET",
      pattern: "]",
      isRegex: false,
      lineNumber: 354,
    },
    {
      name: "LBRACE",
      pattern: "{",
      isRegex: false,
      lineNumber: 355,
    },
    {
      name: "RBRACE",
      pattern: "}",
      isRegex: false,
      lineNumber: 356,
    },
    {
      name: "COMMA",
      pattern: ",",
      isRegex: false,
      lineNumber: 357,
    },
    {
      name: "COLON",
      pattern: ":",
      isRegex: false,
      lineNumber: 358,
    },
    {
      name: "SEMICOLON",
      pattern: ";",
      isRegex: false,
      lineNumber: 359,
    },
    {
      name: "DOT",
      pattern: ".",
      isRegex: false,
      lineNumber: 360,
    },
  ],
  keywords: ["False","None","True","and","as","assert","break","class","continue","def","del","elif","else","except","finally","for","from","global","if","import","in","is","lambda","nonlocal","not","or","pass","raise","return","try","while","with","yield"],
  mode: "indentation",
  escapeMode: undefined,
  skipDefinitions: [
    {
      name: "COMMENT",
      pattern: "#[^\\n]*",
      isRegex: true,
      lineNumber: 112,
    },
    {
      name: "WHITESPACE",
      pattern: "[ \\t]+",
      isRegex: true,
      lineNumber: 113,
    },
    {
      name: "LINE_CONTINUATION",
      pattern: "\\\\[ \\t]*\\n",
      isRegex: true,
      lineNumber: 114,
    },
  ],
  reservedKeywords: [],
  layoutKeywords: [],
  contextKeywords: [],
  errorDefinitions: [],
  groups: {},
  softKeywords: [],
};
