// AUTO-GENERATED FILE - DO NOT EDIT
// Source: python3.10.tokens
// Regenerate with: grammar-tools compile-tokens python3.10.tokens
//
// This file embeds a TokenGrammar as native TypeScript object literals.
// Import it directly instead of reading and parsing the .tokens file at
// runtime.

import type { TokenGrammar } from "@coding-adventures/grammar-tools";

export const TOKEN_GRAMMAR: TokenGrammar = {
  version: 1,
  caseInsensitive: false,
  caseSensitive: true,
  definitions: [
    {
      name: "STRING_RAW_FSTRING_TRIPLE_DQ",
      pattern: "[rR][fF]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"|[fF][rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 151,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_FSTRING_TRIPLE_SQ",
      pattern: "[rR][fF]'''([^'\\\\]|\\\\.|\\n)*'''|[fF][rR]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 152,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_BYTES_TRIPLE_DQ",
      pattern: "[rR][bB]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"|[bB][rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 155,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_BYTES_TRIPLE_SQ",
      pattern: "[rR][bB]'''([^'\\\\]|\\\\.|\\n)*'''|[bB][rR]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 156,
      alias: "STRING",
    },
    {
      name: "STRING_FSTRING_TRIPLE_DQ",
      pattern: "[fF]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 159,
      alias: "STRING",
    },
    {
      name: "STRING_FSTRING_TRIPLE_SQ",
      pattern: "[fF]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 160,
      alias: "STRING",
    },
    {
      name: "STRING_UNICODE_TRIPLE_DQ",
      pattern: "[uU]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 161,
      alias: "STRING",
    },
    {
      name: "STRING_UNICODE_TRIPLE_SQ",
      pattern: "[uU]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 162,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_TRIPLE_DQ",
      pattern: "[rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 163,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_TRIPLE_SQ",
      pattern: "[rR]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 164,
      alias: "STRING",
    },
    {
      name: "STRING_BYTES_TRIPLE_DQ",
      pattern: "[bB]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 165,
      alias: "STRING",
    },
    {
      name: "STRING_BYTES_TRIPLE_SQ",
      pattern: "[bB]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 166,
      alias: "STRING",
    },
    {
      name: "STRING_TRIPLE_DQ",
      pattern: "\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 169,
      alias: "STRING",
    },
    {
      name: "STRING_TRIPLE_SQ",
      pattern: "'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 170,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_FSTRING_DQ",
      pattern: "[rR][fF]\"([^\"\\\\]|\\\\.)*\"|[fF][rR]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 173,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_FSTRING_SQ",
      pattern: "[rR][fF]'([^'\\\\]|\\\\.)*'|[fF][rR]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 174,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_BYTES_DQ",
      pattern: "[rR][bB]\"([^\"\\\\]|\\\\.)*\"|[bB][rR]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 177,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_BYTES_SQ",
      pattern: "[rR][bB]'([^'\\\\]|\\\\.)*'|[bB][rR]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 178,
      alias: "STRING",
    },
    {
      name: "STRING_FSTRING_DQ",
      pattern: "[fF]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 181,
      alias: "STRING",
    },
    {
      name: "STRING_FSTRING_SQ",
      pattern: "[fF]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 182,
      alias: "STRING",
    },
    {
      name: "STRING_UNICODE_DQ",
      pattern: "[uU]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 183,
      alias: "STRING",
    },
    {
      name: "STRING_UNICODE_SQ",
      pattern: "[uU]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 184,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_DQ",
      pattern: "[rR]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 185,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_SQ",
      pattern: "[rR]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 186,
      alias: "STRING",
    },
    {
      name: "STRING_BYTES_DQ",
      pattern: "[bB]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 187,
      alias: "STRING",
    },
    {
      name: "STRING_BYTES_SQ",
      pattern: "[bB]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 188,
      alias: "STRING",
    },
    {
      name: "STRING_DQ",
      pattern: "\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 191,
      alias: "STRING",
    },
    {
      name: "STRING_SQ",
      pattern: "'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 192,
      alias: "STRING",
    },
    {
      name: "IMAG_FLOAT_EXP",
      pattern: "[0-9](_?[0-9])*[eE][+-]?[0-9](_?[0-9])*[jJ]",
      isRegex: true,
      lineNumber: 211,
      alias: "IMAG",
    },
    {
      name: "IMAG_FLOAT_DOT",
      pattern: "\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?[jJ]",
      isRegex: true,
      lineNumber: 212,
      alias: "IMAG",
    },
    {
      name: "IMAG_FLOAT",
      pattern: "[0-9](_?[0-9])*\\.[0-9]*(_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?[jJ]",
      isRegex: true,
      lineNumber: 213,
      alias: "IMAG",
    },
    {
      name: "IMAG_INT",
      pattern: "[0-9](_?[0-9])*[jJ]",
      isRegex: true,
      lineNumber: 214,
      alias: "IMAG",
    },
    {
      name: "FLOAT_EXP",
      pattern: "[0-9](_?[0-9])*[eE][+-]?[0-9](_?[0-9])*",
      isRegex: true,
      lineNumber: 221,
      alias: "FLOAT",
    },
    {
      name: "FLOAT_DOT",
      pattern: "\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?",
      isRegex: true,
      lineNumber: 222,
      alias: "FLOAT",
    },
    {
      name: "FLOAT",
      pattern: "[0-9](_?[0-9])*\\.[0-9]*(_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?",
      isRegex: true,
      lineNumber: 223,
      alias: "FLOAT",
    },
    {
      name: "INT_HEX",
      pattern: "0[xX](_?[0-9a-fA-F])+",
      isRegex: true,
      lineNumber: 229,
      alias: "INT",
    },
    {
      name: "INT_BIN",
      pattern: "0[bB](_?[01])+",
      isRegex: true,
      lineNumber: 230,
      alias: "INT",
    },
    {
      name: "INT_OCT",
      pattern: "0[oO](_?[0-7])+",
      isRegex: true,
      lineNumber: 231,
      alias: "INT",
    },
    {
      name: "INT",
      pattern: "[0-9](_?[0-9])*",
      isRegex: true,
      lineNumber: 232,
    },
    {
      name: "NAME",
      pattern: "[a-zA-Z_][a-zA-Z0-9_]*",
      isRegex: true,
      lineNumber: 246,
    },
    {
      name: "DOUBLE_STAR_EQUALS",
      pattern: "**=",
      isRegex: false,
      lineNumber: 255,
    },
    {
      name: "LEFT_SHIFT_EQUALS",
      pattern: "<<=",
      isRegex: false,
      lineNumber: 256,
    },
    {
      name: "RIGHT_SHIFT_EQUALS",
      pattern: ">>=",
      isRegex: false,
      lineNumber: 257,
    },
    {
      name: "FLOOR_DIV_EQUALS",
      pattern: "//=",
      isRegex: false,
      lineNumber: 258,
    },
    {
      name: "DOUBLE_STAR",
      pattern: "**",
      isRegex: false,
      lineNumber: 274,
    },
    {
      name: "FLOOR_DIV",
      pattern: "//",
      isRegex: false,
      lineNumber: 275,
    },
    {
      name: "LEFT_SHIFT",
      pattern: "<<",
      isRegex: false,
      lineNumber: 276,
    },
    {
      name: "RIGHT_SHIFT",
      pattern: ">>",
      isRegex: false,
      lineNumber: 277,
    },
    {
      name: "WALRUS",
      pattern: ":=",
      isRegex: false,
      lineNumber: 278,
    },
    {
      name: "EQUALS_EQUALS",
      pattern: "==",
      isRegex: false,
      lineNumber: 279,
    },
    {
      name: "NOT_EQUALS",
      pattern: "!=",
      isRegex: false,
      lineNumber: 280,
    },
    {
      name: "LESS_EQUALS",
      pattern: "<=",
      isRegex: false,
      lineNumber: 281,
    },
    {
      name: "GREATER_EQUALS",
      pattern: ">=",
      isRegex: false,
      lineNumber: 282,
    },
    {
      name: "PLUS_EQUALS",
      pattern: "+=",
      isRegex: false,
      lineNumber: 283,
    },
    {
      name: "MINUS_EQUALS",
      pattern: "-=",
      isRegex: false,
      lineNumber: 284,
    },
    {
      name: "STAR_EQUALS",
      pattern: "*=",
      isRegex: false,
      lineNumber: 285,
    },
    {
      name: "SLASH_EQUALS",
      pattern: "/=",
      isRegex: false,
      lineNumber: 286,
    },
    {
      name: "PERCENT_EQUALS",
      pattern: "%=",
      isRegex: false,
      lineNumber: 287,
    },
    {
      name: "AMP_EQUALS",
      pattern: "&=",
      isRegex: false,
      lineNumber: 288,
    },
    {
      name: "PIPE_EQUALS",
      pattern: "|=",
      isRegex: false,
      lineNumber: 289,
    },
    {
      name: "CARET_EQUALS",
      pattern: "^=",
      isRegex: false,
      lineNumber: 290,
    },
    {
      name: "AT_EQUALS",
      pattern: "@=",
      isRegex: false,
      lineNumber: 291,
    },
    {
      name: "ARROW",
      pattern: "->",
      isRegex: false,
      lineNumber: 292,
    },
    {
      name: "PLUS",
      pattern: "+",
      isRegex: false,
      lineNumber: 303,
    },
    {
      name: "MINUS",
      pattern: "-",
      isRegex: false,
      lineNumber: 304,
    },
    {
      name: "STAR",
      pattern: "*",
      isRegex: false,
      lineNumber: 305,
    },
    {
      name: "SLASH",
      pattern: "/",
      isRegex: false,
      lineNumber: 306,
    },
    {
      name: "PERCENT",
      pattern: "%",
      isRegex: false,
      lineNumber: 307,
    },
    {
      name: "EQUALS",
      pattern: "=",
      isRegex: false,
      lineNumber: 308,
    },
    {
      name: "LESS_THAN",
      pattern: "<",
      isRegex: false,
      lineNumber: 309,
    },
    {
      name: "GREATER_THAN",
      pattern: ">",
      isRegex: false,
      lineNumber: 310,
    },
    {
      name: "AMP",
      pattern: "&",
      isRegex: false,
      lineNumber: 311,
    },
    {
      name: "PIPE",
      pattern: "|",
      isRegex: false,
      lineNumber: 312,
    },
    {
      name: "CARET",
      pattern: "^",
      isRegex: false,
      lineNumber: 313,
    },
    {
      name: "TILDE",
      pattern: "~",
      isRegex: false,
      lineNumber: 314,
    },
    {
      name: "AT",
      pattern: "@",
      isRegex: false,
      lineNumber: 315,
    },
    {
      name: "ELLIPSIS",
      pattern: "...",
      isRegex: false,
      lineNumber: 328,
    },
    {
      name: "LPAREN",
      pattern: "(",
      isRegex: false,
      lineNumber: 329,
    },
    {
      name: "RPAREN",
      pattern: ")",
      isRegex: false,
      lineNumber: 330,
    },
    {
      name: "LBRACKET",
      pattern: "[",
      isRegex: false,
      lineNumber: 331,
    },
    {
      name: "RBRACKET",
      pattern: "]",
      isRegex: false,
      lineNumber: 332,
    },
    {
      name: "LBRACE",
      pattern: "{",
      isRegex: false,
      lineNumber: 333,
    },
    {
      name: "RBRACE",
      pattern: "}",
      isRegex: false,
      lineNumber: 334,
    },
    {
      name: "COMMA",
      pattern: ",",
      isRegex: false,
      lineNumber: 335,
    },
    {
      name: "COLON",
      pattern: ":",
      isRegex: false,
      lineNumber: 336,
    },
    {
      name: "SEMICOLON",
      pattern: ";",
      isRegex: false,
      lineNumber: 337,
    },
    {
      name: "DOT",
      pattern: ".",
      isRegex: false,
      lineNumber: 338,
    },
  ],
  keywords: ["False","None","True","and","as","assert","async","await","break","class","continue","def","del","elif","else","except","finally","for","from","global","if","import","in","is","lambda","nonlocal","not","or","pass","raise","return","try","while","with","yield"],
  mode: "indentation",
  escapeMode: undefined,
  skipDefinitions: [
    {
      name: "COMMENT",
      pattern: "#[^\\n]*",
      isRegex: true,
      lineNumber: 92,
    },
    {
      name: "WHITESPACE",
      pattern: "[ \\t]+",
      isRegex: true,
      lineNumber: 93,
    },
    {
      name: "LINE_CONTINUATION",
      pattern: "\\\\[ \\t]*\\n",
      isRegex: true,
      lineNumber: 109,
    },
  ],
  reservedKeywords: [],
  layoutKeywords: [],
  contextKeywords: [],
  errorDefinitions: [],
  groups: {},
  softKeywords: ["match","case","_"],
};
