// AUTO-GENERATED FILE - DO NOT EDIT
// Source: python3.8.tokens
// Regenerate with: grammar-tools compile-tokens python3.8.tokens
//
// This file embeds a TokenGrammar as native TypeScript object literals.
// Import it directly instead of reading and parsing the .tokens file at
// runtime.

import type { TokenGrammar } from "@coding-adventures/grammar-tools";

export const TOKEN_GRAMMAR: TokenGrammar = {
  version: 1,
  caseInsensitive: false,
  caseSensitive: true,
  definitions: [
    {
      name: "STRING_RAW_BYTES_TRIPLE_DQ",
      pattern: "[rR][bB]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"|[bB][rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 129,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_BYTES_TRIPLE_SQ",
      pattern: "[rR][bB]?'''([^'\\\\]|\\\\.|\\n)*'''|[bB][rR]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 130,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_FSTR_TRIPLE_DQ",
      pattern: "[rR][fF]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"|[fF][rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 133,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_FSTR_TRIPLE_SQ",
      pattern: "[rR][fF]'''([^'\\\\]|\\\\.|\\n)*'''|[fF][rR]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 134,
      alias: "STRING",
    },
    {
      name: "STRING_FSTR_TRIPLE_DQ",
      pattern: "[fF]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 137,
      alias: "STRING",
    },
    {
      name: "STRING_FSTR_TRIPLE_SQ",
      pattern: "[fF]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 138,
      alias: "STRING",
    },
    {
      name: "STRING_BYTES_TRIPLE_DQ",
      pattern: "[bB]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 141,
      alias: "STRING",
    },
    {
      name: "STRING_BYTES_TRIPLE_SQ",
      pattern: "[bB]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 142,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_TRIPLE_DQ",
      pattern: "[rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 145,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_TRIPLE_SQ",
      pattern: "[rR]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 146,
      alias: "STRING",
    },
    {
      name: "STRING_TRIPLE_DQ",
      pattern: "\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 149,
      alias: "STRING",
    },
    {
      name: "STRING_TRIPLE_SQ",
      pattern: "'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 150,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_BYTES_DQ",
      pattern: "[rR][bB]\"([^\"\\\\]|\\\\.)*\"|[bB][rR]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 155,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_BYTES_SQ",
      pattern: "[rR][bB]?'([^'\\\\]|\\\\.)*'|[bB][rR]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 156,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_FSTR_DQ",
      pattern: "[rR][fF]\"([^\"\\\\]|\\\\.)*\"|[fF][rR]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 159,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_FSTR_SQ",
      pattern: "[rR][fF]'([^'\\\\]|\\\\.)*'|[fF][rR]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 160,
      alias: "STRING",
    },
    {
      name: "STRING_FSTR_DQ",
      pattern: "[fF]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 163,
      alias: "STRING",
    },
    {
      name: "STRING_FSTR_SQ",
      pattern: "[fF]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 164,
      alias: "STRING",
    },
    {
      name: "STRING_BYTES_DQ",
      pattern: "[bB]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 167,
      alias: "STRING",
    },
    {
      name: "STRING_BYTES_SQ",
      pattern: "[bB]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 168,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_DQ",
      pattern: "[rR]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 171,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_SQ",
      pattern: "[rR]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 172,
      alias: "STRING",
    },
    {
      name: "STRING_DQ",
      pattern: "\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 175,
      alias: "STRING",
    },
    {
      name: "STRING_SQ",
      pattern: "'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 176,
      alias: "STRING",
    },
    {
      name: "IMAG_FLOAT_EXP",
      pattern: "[0-9](_?[0-9])*[eE][+-]?[0-9](_?[0-9])*[jJ]",
      isRegex: true,
      lineNumber: 194,
      alias: "IMAG",
    },
    {
      name: "IMAG_FLOAT_DOT",
      pattern: "\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?[jJ]",
      isRegex: true,
      lineNumber: 195,
      alias: "IMAG",
    },
    {
      name: "IMAG_FLOAT",
      pattern: "[0-9](_?[0-9])*\\.[0-9]*(_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?[jJ]",
      isRegex: true,
      lineNumber: 196,
      alias: "IMAG",
    },
    {
      name: "IMAG_INT",
      pattern: "[0-9](_?[0-9])*[jJ]",
      isRegex: true,
      lineNumber: 197,
      alias: "IMAG",
    },
    {
      name: "FLOAT_EXP",
      pattern: "[0-9](_?[0-9])*[eE][+-]?[0-9](_?[0-9])*",
      isRegex: true,
      lineNumber: 204,
      alias: "FLOAT",
    },
    {
      name: "FLOAT_DOT",
      pattern: "\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?",
      isRegex: true,
      lineNumber: 205,
      alias: "FLOAT",
    },
    {
      name: "FLOAT",
      pattern: "[0-9](_?[0-9])*\\.[0-9]*(_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?",
      isRegex: true,
      lineNumber: 206,
      alias: "FLOAT",
    },
    {
      name: "INT_HEX",
      pattern: "0[xX](_?[0-9a-fA-F])+",
      isRegex: true,
      lineNumber: 213,
      alias: "INT",
    },
    {
      name: "INT_OCT",
      pattern: "0[oO](_?[0-7])+",
      isRegex: true,
      lineNumber: 214,
      alias: "INT",
    },
    {
      name: "INT_BIN",
      pattern: "0[bB](_?[01])+",
      isRegex: true,
      lineNumber: 215,
      alias: "INT",
    },
    {
      name: "INT",
      pattern: "[0-9](_?[0-9])*",
      isRegex: true,
      lineNumber: 216,
    },
    {
      name: "NAME",
      pattern: "[a-zA-Z_][a-zA-Z0-9_]*",
      isRegex: true,
      lineNumber: 231,
    },
    {
      name: "DOUBLE_STAR_EQUALS",
      pattern: "**=",
      isRegex: false,
      lineNumber: 246,
    },
    {
      name: "LEFT_SHIFT_EQUALS",
      pattern: "<<=",
      isRegex: false,
      lineNumber: 247,
    },
    {
      name: "RIGHT_SHIFT_EQUALS",
      pattern: ">>=",
      isRegex: false,
      lineNumber: 248,
    },
    {
      name: "FLOOR_DIV_EQUALS",
      pattern: "//=",
      isRegex: false,
      lineNumber: 249,
    },
    {
      name: "COLONEQUALS",
      pattern: ":=",
      isRegex: false,
      lineNumber: 279,
    },
    {
      name: "DOUBLE_STAR",
      pattern: "**",
      isRegex: false,
      lineNumber: 280,
    },
    {
      name: "FLOOR_DIV",
      pattern: "//",
      isRegex: false,
      lineNumber: 281,
    },
    {
      name: "LEFT_SHIFT",
      pattern: "<<",
      isRegex: false,
      lineNumber: 282,
    },
    {
      name: "RIGHT_SHIFT",
      pattern: ">>",
      isRegex: false,
      lineNumber: 283,
    },
    {
      name: "EQUALS_EQUALS",
      pattern: "==",
      isRegex: false,
      lineNumber: 284,
    },
    {
      name: "NOT_EQUALS",
      pattern: "!=",
      isRegex: false,
      lineNumber: 285,
    },
    {
      name: "LESS_EQUALS",
      pattern: "<=",
      isRegex: false,
      lineNumber: 286,
    },
    {
      name: "GREATER_EQUALS",
      pattern: ">=",
      isRegex: false,
      lineNumber: 287,
    },
    {
      name: "ARROW",
      pattern: "->",
      isRegex: false,
      lineNumber: 288,
    },
    {
      name: "ELLIPSIS",
      pattern: "...",
      isRegex: false,
      lineNumber: 289,
    },
    {
      name: "PLUS_EQUALS",
      pattern: "+=",
      isRegex: false,
      lineNumber: 290,
    },
    {
      name: "MINUS_EQUALS",
      pattern: "-=",
      isRegex: false,
      lineNumber: 291,
    },
    {
      name: "STAR_EQUALS",
      pattern: "*=",
      isRegex: false,
      lineNumber: 292,
    },
    {
      name: "SLASH_EQUALS",
      pattern: "/=",
      isRegex: false,
      lineNumber: 293,
    },
    {
      name: "PERCENT_EQUALS",
      pattern: "%=",
      isRegex: false,
      lineNumber: 294,
    },
    {
      name: "AMP_EQUALS",
      pattern: "&=",
      isRegex: false,
      lineNumber: 295,
    },
    {
      name: "PIPE_EQUALS",
      pattern: "|=",
      isRegex: false,
      lineNumber: 296,
    },
    {
      name: "CARET_EQUALS",
      pattern: "^=",
      isRegex: false,
      lineNumber: 297,
    },
    {
      name: "AT_EQUALS",
      pattern: "@=",
      isRegex: false,
      lineNumber: 298,
    },
    {
      name: "PLUS",
      pattern: "+",
      isRegex: false,
      lineNumber: 307,
    },
    {
      name: "MINUS",
      pattern: "-",
      isRegex: false,
      lineNumber: 308,
    },
    {
      name: "STAR",
      pattern: "*",
      isRegex: false,
      lineNumber: 309,
    },
    {
      name: "SLASH",
      pattern: "/",
      isRegex: false,
      lineNumber: 310,
    },
    {
      name: "PERCENT",
      pattern: "%",
      isRegex: false,
      lineNumber: 311,
    },
    {
      name: "EQUALS",
      pattern: "=",
      isRegex: false,
      lineNumber: 312,
    },
    {
      name: "LESS_THAN",
      pattern: "<",
      isRegex: false,
      lineNumber: 313,
    },
    {
      name: "GREATER_THAN",
      pattern: ">",
      isRegex: false,
      lineNumber: 314,
    },
    {
      name: "AMP",
      pattern: "&",
      isRegex: false,
      lineNumber: 315,
    },
    {
      name: "PIPE",
      pattern: "|",
      isRegex: false,
      lineNumber: 316,
    },
    {
      name: "CARET",
      pattern: "^",
      isRegex: false,
      lineNumber: 317,
    },
    {
      name: "TILDE",
      pattern: "~",
      isRegex: false,
      lineNumber: 318,
    },
    {
      name: "AT",
      pattern: "@",
      isRegex: false,
      lineNumber: 319,
    },
    {
      name: "LPAREN",
      pattern: "(",
      isRegex: false,
      lineNumber: 336,
    },
    {
      name: "RPAREN",
      pattern: ")",
      isRegex: false,
      lineNumber: 337,
    },
    {
      name: "LBRACKET",
      pattern: "[",
      isRegex: false,
      lineNumber: 338,
    },
    {
      name: "RBRACKET",
      pattern: "]",
      isRegex: false,
      lineNumber: 339,
    },
    {
      name: "LBRACE",
      pattern: "{",
      isRegex: false,
      lineNumber: 340,
    },
    {
      name: "RBRACE",
      pattern: "}",
      isRegex: false,
      lineNumber: 341,
    },
    {
      name: "COMMA",
      pattern: ",",
      isRegex: false,
      lineNumber: 342,
    },
    {
      name: "COLON",
      pattern: ":",
      isRegex: false,
      lineNumber: 343,
    },
    {
      name: "SEMICOLON",
      pattern: ";",
      isRegex: false,
      lineNumber: 344,
    },
    {
      name: "DOT",
      pattern: ".",
      isRegex: false,
      lineNumber: 345,
    },
  ],
  keywords: ["False","None","True","and","as","assert","async","await","break","class","continue","def","del","elif","else","except","finally","for","from","global","if","import","in","is","lambda","nonlocal","not","or","pass","raise","return","try","while","with","yield"],
  mode: "indentation",
  escapeMode: undefined,
  skipDefinitions: [
    {
      name: "COMMENT",
      pattern: "#[^\\n]*",
      isRegex: true,
      lineNumber: 88,
    },
    {
      name: "WHITESPACE",
      pattern: "[ \\t]+",
      isRegex: true,
      lineNumber: 89,
    },
  ],
  reservedKeywords: [],
  layoutKeywords: [],
  contextKeywords: [],
  errorDefinitions: [],
  groups: {},
  softKeywords: [],
};
