// AUTO-GENERATED FILE - DO NOT EDIT
// Source: python3.6.tokens
// Regenerate with: grammar-tools compile-tokens python3.6.tokens
//
// This file embeds a TokenGrammar as native TypeScript object literals.
// Import it directly instead of reading and parsing the .tokens file at
// runtime.

import type { TokenGrammar } from "@coding-adventures/grammar-tools";

export const TOKEN_GRAMMAR: TokenGrammar = {
  version: 1,
  caseInsensitive: false,
  caseSensitive: true,
  definitions: [
    {
      name: "STRING_RAW_FSTR_TRIPLE_DQ",
      pattern: "[rR][fF]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"|[fF][rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 198,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_FSTR_TRIPLE_SQ",
      pattern: "[rR][fF]'''([^'\\\\]|\\\\.|\\n)*'''|[fF][rR]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 199,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_TRIPLE_DQ",
      pattern: "[rR][bB]?\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"|[bB][rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 200,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_TRIPLE_SQ",
      pattern: "[rR][bB]?'''([^'\\\\]|\\\\.|\\n)*'''|[bB][rR]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 201,
      alias: "STRING",
    },
    {
      name: "STRING_FSTR_TRIPLE_DQ",
      pattern: "[fF]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 203,
      alias: "STRING",
    },
    {
      name: "STRING_FSTR_TRIPLE_SQ",
      pattern: "[fF]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 204,
      alias: "STRING",
    },
    {
      name: "STRING_TRIPLE_DQ",
      pattern: "[bB]?\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 205,
      alias: "STRING",
    },
    {
      name: "STRING_TRIPLE_SQ",
      pattern: "[bB]?'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 206,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_FSTR_DQ",
      pattern: "[rR][fF]\"([^\"\\\\]|\\\\.)*\"|[fF][rR]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 210,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_FSTR_SQ",
      pattern: "[rR][fF]'([^'\\\\]|\\\\.)*'|[fF][rR]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 211,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_DQ",
      pattern: "[rR][bB]?\"([^\"\\\\]|\\\\.)*\"|[bB][rR]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 212,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_SQ",
      pattern: "[rR][bB]?'([^'\\\\]|\\\\.)*'|[bB][rR]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 213,
      alias: "STRING",
    },
    {
      name: "STRING_FSTR_DQ",
      pattern: "[fF]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 215,
      alias: "STRING",
    },
    {
      name: "STRING_FSTR_SQ",
      pattern: "[fF]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 216,
      alias: "STRING",
    },
    {
      name: "STRING_DQ",
      pattern: "[bB]?\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 217,
      alias: "STRING",
    },
    {
      name: "STRING_SQ",
      pattern: "[bB]?'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 218,
      alias: "STRING",
    },
    {
      name: "FLOAT_EXP",
      pattern: "[0-9](_?[0-9])*[eE][+-]?[0-9](_?[0-9])*",
      isRegex: true,
      lineNumber: 251,
      alias: "FLOAT",
    },
    {
      name: "FLOAT_DOT",
      pattern: "\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?\\b",
      isRegex: true,
      lineNumber: 252,
      alias: "FLOAT",
    },
    {
      name: "FLOAT",
      pattern: "[0-9](_?[0-9])*\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?",
      isRegex: true,
      lineNumber: 253,
      alias: "FLOAT",
    },
    {
      name: "FLOAT_TRAIL",
      pattern: "[0-9](_?[0-9])*\\.([eE][+-]?[0-9](_?[0-9])*)?\\b",
      isRegex: true,
      lineNumber: 254,
      alias: "FLOAT",
    },
    {
      name: "IMAG_FLOAT",
      pattern: "[0-9](_?[0-9])*\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?[jJ]",
      isRegex: true,
      lineNumber: 259,
      alias: "IMAGINARY",
    },
    {
      name: "IMAG_DOT",
      pattern: "\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?[jJ]",
      isRegex: true,
      lineNumber: 260,
      alias: "IMAGINARY",
    },
    {
      name: "IMAG_EXP",
      pattern: "[0-9](_?[0-9])*[eE][+-]?[0-9](_?[0-9])*[jJ]",
      isRegex: true,
      lineNumber: 261,
      alias: "IMAGINARY",
    },
    {
      name: "IMAG_INT",
      pattern: "[0-9](_?[0-9])*[jJ]",
      isRegex: true,
      lineNumber: 262,
      alias: "IMAGINARY",
    },
    {
      name: "INT_HEX",
      pattern: "0[xX](_?[0-9a-fA-F])+",
      isRegex: true,
      lineNumber: 272,
      alias: "INT",
    },
    {
      name: "INT_OCT",
      pattern: "0[oO](_?[0-7])+",
      isRegex: true,
      lineNumber: 273,
      alias: "INT",
    },
    {
      name: "INT_BIN",
      pattern: "0[bB](_?[01])+",
      isRegex: true,
      lineNumber: 274,
      alias: "INT",
    },
    {
      name: "INT",
      pattern: "[0-9](_?[0-9])*",
      isRegex: true,
      lineNumber: 275,
    },
    {
      name: "NAME",
      pattern: "[a-zA-Z_][a-zA-Z0-9_]*",
      isRegex: true,
      lineNumber: 285,
    },
    {
      name: "AT",
      pattern: "@",
      isRegex: false,
      lineNumber: 297,
    },
    {
      name: "DOUBLE_STAR_EQUALS",
      pattern: "**=",
      isRegex: false,
      lineNumber: 306,
    },
    {
      name: "LEFT_SHIFT_EQUALS",
      pattern: "<<=",
      isRegex: false,
      lineNumber: 307,
    },
    {
      name: "RIGHT_SHIFT_EQUALS",
      pattern: ">>=",
      isRegex: false,
      lineNumber: 308,
    },
    {
      name: "FLOOR_DIV_EQUALS",
      pattern: "//=",
      isRegex: false,
      lineNumber: 309,
    },
    {
      name: "AT_EQUALS",
      pattern: "@=",
      isRegex: false,
      lineNumber: 310,
    },
    {
      name: "DOUBLE_STAR",
      pattern: "**",
      isRegex: false,
      lineNumber: 318,
    },
    {
      name: "FLOOR_DIV",
      pattern: "//",
      isRegex: false,
      lineNumber: 319,
    },
    {
      name: "LEFT_SHIFT",
      pattern: "<<",
      isRegex: false,
      lineNumber: 320,
    },
    {
      name: "RIGHT_SHIFT",
      pattern: ">>",
      isRegex: false,
      lineNumber: 321,
    },
    {
      name: "EQUALS_EQUALS",
      pattern: "==",
      isRegex: false,
      lineNumber: 322,
    },
    {
      name: "NOT_EQUALS",
      pattern: "!=",
      isRegex: false,
      lineNumber: 323,
    },
    {
      name: "LESS_EQUALS",
      pattern: "<=",
      isRegex: false,
      lineNumber: 324,
    },
    {
      name: "GREATER_EQUALS",
      pattern: ">=",
      isRegex: false,
      lineNumber: 325,
    },
    {
      name: "PLUS_EQUALS",
      pattern: "+=",
      isRegex: false,
      lineNumber: 326,
    },
    {
      name: "MINUS_EQUALS",
      pattern: "-=",
      isRegex: false,
      lineNumber: 327,
    },
    {
      name: "STAR_EQUALS",
      pattern: "*=",
      isRegex: false,
      lineNumber: 328,
    },
    {
      name: "SLASH_EQUALS",
      pattern: "/=",
      isRegex: false,
      lineNumber: 329,
    },
    {
      name: "PERCENT_EQUALS",
      pattern: "%=",
      isRegex: false,
      lineNumber: 330,
    },
    {
      name: "AMP_EQUALS",
      pattern: "&=",
      isRegex: false,
      lineNumber: 331,
    },
    {
      name: "PIPE_EQUALS",
      pattern: "|=",
      isRegex: false,
      lineNumber: 332,
    },
    {
      name: "CARET_EQUALS",
      pattern: "^=",
      isRegex: false,
      lineNumber: 333,
    },
    {
      name: "ARROW",
      pattern: "->",
      isRegex: false,
      lineNumber: 334,
    },
    {
      name: "PLUS",
      pattern: "+",
      isRegex: false,
      lineNumber: 340,
    },
    {
      name: "MINUS",
      pattern: "-",
      isRegex: false,
      lineNumber: 341,
    },
    {
      name: "STAR",
      pattern: "*",
      isRegex: false,
      lineNumber: 342,
    },
    {
      name: "SLASH",
      pattern: "/",
      isRegex: false,
      lineNumber: 343,
    },
    {
      name: "PERCENT",
      pattern: "%",
      isRegex: false,
      lineNumber: 344,
    },
    {
      name: "EQUALS",
      pattern: "=",
      isRegex: false,
      lineNumber: 345,
    },
    {
      name: "LESS_THAN",
      pattern: "<",
      isRegex: false,
      lineNumber: 346,
    },
    {
      name: "GREATER_THAN",
      pattern: ">",
      isRegex: false,
      lineNumber: 347,
    },
    {
      name: "AMP",
      pattern: "&",
      isRegex: false,
      lineNumber: 348,
    },
    {
      name: "PIPE",
      pattern: "|",
      isRegex: false,
      lineNumber: 349,
    },
    {
      name: "CARET",
      pattern: "^",
      isRegex: false,
      lineNumber: 350,
    },
    {
      name: "TILDE",
      pattern: "~",
      isRegex: false,
      lineNumber: 351,
    },
    {
      name: "LPAREN",
      pattern: "(",
      isRegex: false,
      lineNumber: 357,
    },
    {
      name: "RPAREN",
      pattern: ")",
      isRegex: false,
      lineNumber: 358,
    },
    {
      name: "LBRACKET",
      pattern: "[",
      isRegex: false,
      lineNumber: 359,
    },
    {
      name: "RBRACKET",
      pattern: "]",
      isRegex: false,
      lineNumber: 360,
    },
    {
      name: "LBRACE",
      pattern: "{",
      isRegex: false,
      lineNumber: 361,
    },
    {
      name: "RBRACE",
      pattern: "}",
      isRegex: false,
      lineNumber: 362,
    },
    {
      name: "COMMA",
      pattern: ",",
      isRegex: false,
      lineNumber: 363,
    },
    {
      name: "COLON",
      pattern: ":",
      isRegex: false,
      lineNumber: 364,
    },
    {
      name: "SEMICOLON",
      pattern: ";",
      isRegex: false,
      lineNumber: 365,
    },
    {
      name: "DOT",
      pattern: ".",
      isRegex: false,
      lineNumber: 366,
    },
    {
      name: "ELLIPSIS",
      pattern: "...",
      isRegex: false,
      lineNumber: 367,
    },
  ],
  keywords: ["False","None","True","and","as","assert","async","await","break","class","continue","def","del","elif","else","except","finally","for","from","global","if","import","in","is","lambda","nonlocal","not","or","pass","raise","return","try","while","with","yield"],
  mode: "indentation",
  escapeMode: undefined,
  skipDefinitions: [
    {
      name: "COMMENT",
      pattern: "#[^\\n]*",
      isRegex: true,
      lineNumber: 55,
    },
    {
      name: "WHITESPACE",
      pattern: "[ \\t]+",
      isRegex: true,
      lineNumber: 56,
    },
  ],
  reservedKeywords: [],
  layoutKeywords: [],
  contextKeywords: [],
  errorDefinitions: [],
  groups: {},
  softKeywords: [],
};
