// AUTO-GENERATED FILE - DO NOT EDIT
// Source: python3.12.tokens
// Regenerate with: grammar-tools compile-tokens python3.12.tokens
//
// This file embeds a TokenGrammar as native TypeScript object literals.
// Import it directly instead of reading and parsing the .tokens file at
// runtime.

import type { TokenGrammar } from "@coding-adventures/grammar-tools";

export const TOKEN_GRAMMAR: TokenGrammar = {
  version: 1,
  caseInsensitive: false,
  caseSensitive: true,
  definitions: [
    {
      name: "STRING_RAW_FSTRING_TRIPLE_DQ",
      pattern: "[rR][fF]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"|[fF][rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 107,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_FSTRING_TRIPLE_SQ",
      pattern: "[rR][fF]'''([^'\\\\]|\\\\.|\\n)*'''|[fF][rR]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 108,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_BYTES_TRIPLE_DQ",
      pattern: "[bB][rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"|[rR][bB]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 109,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_BYTES_TRIPLE_SQ",
      pattern: "[bB][rR]'''([^'\\\\]|\\\\.|\\n)*'''|[rR][bB]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 110,
      alias: "STRING",
    },
    {
      name: "STRING_FSTRING_TRIPLE_DQ",
      pattern: "[fF]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 112,
      alias: "STRING",
    },
    {
      name: "STRING_FSTRING_TRIPLE_SQ",
      pattern: "[fF]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 113,
      alias: "STRING",
    },
    {
      name: "STRING_UNICODE_TRIPLE_DQ",
      pattern: "[uU]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 114,
      alias: "STRING",
    },
    {
      name: "STRING_UNICODE_TRIPLE_SQ",
      pattern: "[uU]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 115,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_TRIPLE_DQ",
      pattern: "[rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 116,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_TRIPLE_SQ",
      pattern: "[rR]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 117,
      alias: "STRING",
    },
    {
      name: "STRING_BYTES_TRIPLE_DQ",
      pattern: "[bB]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 118,
      alias: "STRING",
    },
    {
      name: "STRING_BYTES_TRIPLE_SQ",
      pattern: "[bB]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 119,
      alias: "STRING",
    },
    {
      name: "STRING_TRIPLE_DQ",
      pattern: "\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 120,
      alias: "STRING",
    },
    {
      name: "STRING_TRIPLE_SQ",
      pattern: "'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 121,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_FSTRING_DQ",
      pattern: "[rR][fF]\"([^\"\\\\]|\\\\.)*\"|[fF][rR]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 124,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_FSTRING_SQ",
      pattern: "[rR][fF]'([^'\\\\]|\\\\.)*'|[fF][rR]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 125,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_BYTES_DQ",
      pattern: "[bB][rR]\"([^\"\\\\]|\\\\.)*\"|[rR][bB]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 126,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_BYTES_SQ",
      pattern: "[bB][rR]'([^'\\\\]|\\\\.)*'|[rR][bB]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 127,
      alias: "STRING",
    },
    {
      name: "STRING_FSTRING_DQ",
      pattern: "[fF]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 129,
      alias: "STRING",
    },
    {
      name: "STRING_FSTRING_SQ",
      pattern: "[fF]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 130,
      alias: "STRING",
    },
    {
      name: "STRING_UNICODE_DQ",
      pattern: "[uU]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 131,
      alias: "STRING",
    },
    {
      name: "STRING_UNICODE_SQ",
      pattern: "[uU]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 132,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_DQ",
      pattern: "[rR]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 133,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_SQ",
      pattern: "[rR]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 134,
      alias: "STRING",
    },
    {
      name: "STRING_BYTES_DQ",
      pattern: "[bB]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 135,
      alias: "STRING",
    },
    {
      name: "STRING_BYTES_SQ",
      pattern: "[bB]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 136,
      alias: "STRING",
    },
    {
      name: "STRING_DQ",
      pattern: "\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 137,
      alias: "STRING",
    },
    {
      name: "STRING_SQ",
      pattern: "'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 138,
      alias: "STRING",
    },
    {
      name: "IMAG_FLOAT_EXP",
      pattern: "[0-9](_?[0-9])*[eE][+-]?[0-9](_?[0-9])*[jJ]",
      isRegex: true,
      lineNumber: 149,
      alias: "IMAG",
    },
    {
      name: "IMAG_FLOAT_DOT",
      pattern: "\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?[jJ]",
      isRegex: true,
      lineNumber: 150,
      alias: "IMAG",
    },
    {
      name: "IMAG_FLOAT",
      pattern: "[0-9](_?[0-9])*\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?[jJ]",
      isRegex: true,
      lineNumber: 151,
      alias: "IMAG",
    },
    {
      name: "IMAG_INT",
      pattern: "[0-9](_?[0-9])*[jJ]",
      isRegex: true,
      lineNumber: 152,
      alias: "IMAG",
    },
    {
      name: "FLOAT_EXP",
      pattern: "[0-9](_?[0-9])*[eE][+-]?[0-9](_?[0-9])*",
      isRegex: true,
      lineNumber: 154,
      alias: "FLOAT",
    },
    {
      name: "FLOAT_DOT",
      pattern: "\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?",
      isRegex: true,
      lineNumber: 155,
      alias: "FLOAT",
    },
    {
      name: "FLOAT",
      pattern: "[0-9](_?[0-9])*\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?",
      isRegex: true,
      lineNumber: 156,
      alias: "FLOAT",
    },
    {
      name: "INT_HEX",
      pattern: "0[xX](_?[0-9a-fA-F])+",
      isRegex: true,
      lineNumber: 158,
      alias: "INT",
    },
    {
      name: "INT_BIN",
      pattern: "0[bB](_?[01])+",
      isRegex: true,
      lineNumber: 159,
      alias: "INT",
    },
    {
      name: "INT_OCT",
      pattern: "0[oO](_?[0-7])+",
      isRegex: true,
      lineNumber: 160,
      alias: "INT",
    },
    {
      name: "INT",
      pattern: "[0-9](_?[0-9])*",
      isRegex: true,
      lineNumber: 161,
    },
    {
      name: "NAME",
      pattern: "[a-zA-Z_][a-zA-Z0-9_]*",
      isRegex: true,
      lineNumber: 170,
    },
    {
      name: "DOUBLE_STAR_EQUALS",
      pattern: "**=",
      isRegex: false,
      lineNumber: 176,
    },
    {
      name: "LEFT_SHIFT_EQUALS",
      pattern: "<<=",
      isRegex: false,
      lineNumber: 177,
    },
    {
      name: "RIGHT_SHIFT_EQUALS",
      pattern: ">>=",
      isRegex: false,
      lineNumber: 178,
    },
    {
      name: "FLOOR_DIV_EQUALS",
      pattern: "//=",
      isRegex: false,
      lineNumber: 179,
    },
    {
      name: "DOUBLE_STAR",
      pattern: "**",
      isRegex: false,
      lineNumber: 188,
    },
    {
      name: "FLOOR_DIV",
      pattern: "//",
      isRegex: false,
      lineNumber: 189,
    },
    {
      name: "LEFT_SHIFT",
      pattern: "<<",
      isRegex: false,
      lineNumber: 190,
    },
    {
      name: "RIGHT_SHIFT",
      pattern: ">>",
      isRegex: false,
      lineNumber: 191,
    },
    {
      name: "EQUALS_EQUALS",
      pattern: "==",
      isRegex: false,
      lineNumber: 192,
    },
    {
      name: "NOT_EQUALS",
      pattern: "!=",
      isRegex: false,
      lineNumber: 193,
    },
    {
      name: "LESS_EQUALS",
      pattern: "<=",
      isRegex: false,
      lineNumber: 194,
    },
    {
      name: "GREATER_EQUALS",
      pattern: ">=",
      isRegex: false,
      lineNumber: 195,
    },
    {
      name: "WALRUS",
      pattern: ":=",
      isRegex: false,
      lineNumber: 196,
    },
    {
      name: "ARROW",
      pattern: "->",
      isRegex: false,
      lineNumber: 197,
    },
    {
      name: "PLUS_EQUALS",
      pattern: "+=",
      isRegex: false,
      lineNumber: 198,
    },
    {
      name: "MINUS_EQUALS",
      pattern: "-=",
      isRegex: false,
      lineNumber: 199,
    },
    {
      name: "STAR_EQUALS",
      pattern: "*=",
      isRegex: false,
      lineNumber: 200,
    },
    {
      name: "SLASH_EQUALS",
      pattern: "/=",
      isRegex: false,
      lineNumber: 201,
    },
    {
      name: "PERCENT_EQUALS",
      pattern: "%=",
      isRegex: false,
      lineNumber: 202,
    },
    {
      name: "AMP_EQUALS",
      pattern: "&=",
      isRegex: false,
      lineNumber: 203,
    },
    {
      name: "PIPE_EQUALS",
      pattern: "|=",
      isRegex: false,
      lineNumber: 204,
    },
    {
      name: "CARET_EQUALS",
      pattern: "^=",
      isRegex: false,
      lineNumber: 205,
    },
    {
      name: "AT_EQUALS",
      pattern: "@=",
      isRegex: false,
      lineNumber: 206,
    },
    {
      name: "PLUS",
      pattern: "+",
      isRegex: false,
      lineNumber: 215,
    },
    {
      name: "MINUS",
      pattern: "-",
      isRegex: false,
      lineNumber: 216,
    },
    {
      name: "STAR",
      pattern: "*",
      isRegex: false,
      lineNumber: 217,
    },
    {
      name: "SLASH",
      pattern: "/",
      isRegex: false,
      lineNumber: 218,
    },
    {
      name: "PERCENT",
      pattern: "%",
      isRegex: false,
      lineNumber: 219,
    },
    {
      name: "EQUALS",
      pattern: "=",
      isRegex: false,
      lineNumber: 220,
    },
    {
      name: "LESS_THAN",
      pattern: "<",
      isRegex: false,
      lineNumber: 221,
    },
    {
      name: "GREATER_THAN",
      pattern: ">",
      isRegex: false,
      lineNumber: 222,
    },
    {
      name: "AMP",
      pattern: "&",
      isRegex: false,
      lineNumber: 223,
    },
    {
      name: "PIPE",
      pattern: "|",
      isRegex: false,
      lineNumber: 224,
    },
    {
      name: "CARET",
      pattern: "^",
      isRegex: false,
      lineNumber: 225,
    },
    {
      name: "TILDE",
      pattern: "~",
      isRegex: false,
      lineNumber: 226,
    },
    {
      name: "AT",
      pattern: "@",
      isRegex: false,
      lineNumber: 227,
    },
    {
      name: "ELLIPSIS",
      pattern: "...",
      isRegex: false,
      lineNumber: 237,
    },
    {
      name: "LPAREN",
      pattern: "(",
      isRegex: false,
      lineNumber: 238,
    },
    {
      name: "RPAREN",
      pattern: ")",
      isRegex: false,
      lineNumber: 239,
    },
    {
      name: "LBRACKET",
      pattern: "[",
      isRegex: false,
      lineNumber: 240,
    },
    {
      name: "RBRACKET",
      pattern: "]",
      isRegex: false,
      lineNumber: 241,
    },
    {
      name: "LBRACE",
      pattern: "{",
      isRegex: false,
      lineNumber: 242,
    },
    {
      name: "RBRACE",
      pattern: "}",
      isRegex: false,
      lineNumber: 243,
    },
    {
      name: "COMMA",
      pattern: ",",
      isRegex: false,
      lineNumber: 244,
    },
    {
      name: "COLON",
      pattern: ":",
      isRegex: false,
      lineNumber: 245,
    },
    {
      name: "SEMICOLON",
      pattern: ";",
      isRegex: false,
      lineNumber: 246,
    },
    {
      name: "DOT",
      pattern: ".",
      isRegex: false,
      lineNumber: 247,
    },
  ],
  keywords: ["False","None","True","and","as","assert","async","await","break","class","continue","def","del","elif","else","except","finally","for","from","global","if","import","in","is","lambda","nonlocal","not","or","pass","raise","return","try","while","with","yield"],
  mode: "indentation",
  escapeMode: undefined,
  skipDefinitions: [
    {
      name: "COMMENT",
      pattern: "#[^\\n]*",
      isRegex: true,
      lineNumber: 41,
    },
    {
      name: "WHITESPACE",
      pattern: "[ \\t]+",
      isRegex: true,
      lineNumber: 42,
    },
    {
      name: "LINE_CONTINUATION",
      pattern: "\\\\[ \\t]*\\n",
      isRegex: true,
      lineNumber: 45,
    },
  ],
  reservedKeywords: [],
  layoutKeywords: [],
  contextKeywords: [],
  errorDefinitions: [],
  groups: {},
  softKeywords: ["match","case","_","type"],
};
