cd ../../../packages/typescript/ui-components && npm install
cd ../../../packages/typescript/transistors && npm install
cd ../../../programs/typescript/transistor-visualizer && npm install
npx vitest run
