// Auto-generated by mosaic-emit-xaml. Do not edit.
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using System;
using System.Collections.Generic;

namespace Mosaic.Generated;

public sealed partial class Spinner : UserControl
{
    public Spinner()
    {
        this.InitializeComponent();
    }

    public string Size
    {
        get => (string)GetValue(SizeProperty);
        set => SetValue(SizeProperty, value);
    }
    public static readonly DependencyProperty SizeProperty =
        DependencyProperty.Register(nameof(Size), typeof(string), typeof(Spinner), new PropertyMetadata(default(string)));

    public string Variant
    {
        get => (string)GetValue(VariantProperty);
        set => SetValue(VariantProperty, value);
    }
    public static readonly DependencyProperty VariantProperty =
        DependencyProperty.Register(nameof(Variant), typeof(string), typeof(Spinner), new PropertyMetadata(default(string)));

    public string AriaLabel
    {
        get => (string)GetValue(AriaLabelProperty);
        set => SetValue(AriaLabelProperty, value);
    }
    public static readonly DependencyProperty AriaLabelProperty =
        DependencyProperty.Register(nameof(AriaLabel), typeof(string), typeof(Spinner), new PropertyMetadata(default(string)));

    /// <summary>Fires once for every emit declared in the .mil interface.</summary>
    public event EventHandler<SpinnerEvent>? Dispatch;

}
