# AUTO-GENERATED FILE — DO NOT EDIT
# ruff: noqa: E501, F401
# Source: prolog.tokens
# Regenerate with: grammar-tools compile-tokens <source.tokens>
#
# This file embeds a TokenGrammar as native Python data structures.
# Downstream packages import TOKEN_GRAMMAR directly instead of
# reading and parsing the .tokens file at runtime.

from grammar_tools.token_grammar import ModeTransition, PatternGroup, TokenDefinition, TokenGrammar, TransitionAction

# fmt: off  # noqa: E501 — generated code may have long lines

TOKEN_GRAMMAR = TokenGrammar(
    version=1,
    case_insensitive=False,
    case_sensitive=True,
    definitions=[
        TokenDefinition(
            name='DCG',
            pattern='-->',
            is_regex=False,
            line_number=20,
            alias=None,
        ),
        TokenDefinition(
            name='QUERY',
            pattern='?-',
            is_regex=False,
            line_number=21,
            alias=None,
        ),
        TokenDefinition(
            name='RULE',
            pattern=':-',
            is_regex=False,
            line_number=22,
            alias=None,
        ),
        TokenDefinition(
            name='LPAREN',
            pattern='(',
            is_regex=False,
            line_number=25,
            alias=None,
        ),
        TokenDefinition(
            name='RPAREN',
            pattern=')',
            is_regex=False,
            line_number=26,
            alias=None,
        ),
        TokenDefinition(
            name='LBRACKET',
            pattern='[',
            is_regex=False,
            line_number=27,
            alias=None,
        ),
        TokenDefinition(
            name='RBRACKET',
            pattern=']',
            is_regex=False,
            line_number=28,
            alias=None,
        ),
        TokenDefinition(
            name='LCURLY',
            pattern='{',
            is_regex=False,
            line_number=29,
            alias=None,
        ),
        TokenDefinition(
            name='RCURLY',
            pattern='}',
            is_regex=False,
            line_number=30,
            alias=None,
        ),
        TokenDefinition(
            name='BAR',
            pattern='|',
            is_regex=False,
            line_number=31,
            alias=None,
        ),
        TokenDefinition(
            name='COMMA',
            pattern=',',
            is_regex=False,
            line_number=32,
            alias=None,
        ),
        TokenDefinition(
            name='SEMICOLON',
            pattern=';',
            is_regex=False,
            line_number=33,
            alias=None,
        ),
        TokenDefinition(
            name='CUT',
            pattern='!',
            is_regex=False,
            line_number=34,
            alias=None,
        ),
        TokenDefinition(
            name='DOT',
            pattern='.',
            is_regex=False,
            line_number=35,
            alias=None,
        ),
        TokenDefinition(
            name='FLOAT',
            pattern='[0-9]+\\.[0-9]+([eE][-+]?[0-9]+)?',
            is_regex=True,
            line_number=38,
            alias=None,
        ),
        TokenDefinition(
            name='INTEGER',
            pattern='[0-9]+',
            is_regex=True,
            line_number=39,
            alias=None,
        ),
        TokenDefinition(
            name='STRING',
            pattern='"([^"\\\\]|\\\\.)*"',
            is_regex=True,
            line_number=42,
            alias=None,
        ),
        TokenDefinition(
            name='QUOTED_ATOM',
            pattern="'([^'\\\\]|\\\\.)*'",
            is_regex=True,
            line_number=43,
            alias='ATOM',
        ),
        TokenDefinition(
            name='ANON_VAR',
            pattern='_(?![A-Za-z0-9_])',
            is_regex=True,
            line_number=50,
            alias=None,
        ),
        TokenDefinition(
            name='VARIABLE',
            pattern='(?:[A-Z][A-Za-z0-9_]*|_[A-Za-z0-9_]+)',
            is_regex=True,
            line_number=51,
            alias=None,
        ),
        TokenDefinition(
            name='ATOM',
            pattern='[a-z][A-Za-z0-9_]*',
            is_regex=True,
            line_number=52,
            alias=None,
        ),
        TokenDefinition(
            name='ATOM_SYMBOLIC',
            pattern='[#$&*+\\-\\/:<=>?@\\\\^~]+',
            is_regex=True,
            line_number=57,
            alias='ATOM',
        ),
    ],
    keywords=[],
    mode=None,
    escape_mode=None,
    skip_definitions=[
        TokenDefinition(
            name='WHITESPACE',
            pattern='[ \\t\\r\\n]+',
            is_regex=True,
            line_number=16,
            alias=None,
        ),
        TokenDefinition(
            name='COMMENT',
            pattern='%[^\\n]*',
            is_regex=True,
            line_number=17,
            alias=None,
        ),
    ],
    reserved_keywords=[],
    error_definitions=[],
    groups={},
    start_mode=None,
    transitions=[],
    layout_keywords=[],
)
