// AUTO-GENERATED FILE - DO NOT EDIT
// Source: ts3.0.tokens
// Regenerate with: grammar-tools compile-tokens ts3.0.tokens
//
// This file embeds a TokenGrammar as native TypeScript object literals.
// Import it directly instead of reading and parsing the .tokens file at
// runtime.

import type { TokenGrammar } from "@coding-adventures/grammar-tools";

export const TOKEN_GRAMMAR: TokenGrammar = {
  version: 1,
  caseInsensitive: false,
  caseSensitive: true,
  definitions: [
    {
      name: "NAME",
      pattern: "[a-zA-Z_$][a-zA-Z0-9_$]*",
      isRegex: true,
      lineNumber: 51,
    },
    {
      name: "BINARY_NUMBER",
      pattern: "0[bB][01]+",
      isRegex: true,
      lineNumber: 55,
      alias: "NUMBER",
    },
    {
      name: "OCTAL_NUMBER",
      pattern: "0[oO][0-7]+",
      isRegex: true,
      lineNumber: 56,
      alias: "NUMBER",
    },
    {
      name: "HEX_NUMBER",
      pattern: "0[xX][0-9a-fA-F]+",
      isRegex: true,
      lineNumber: 57,
      alias: "NUMBER",
    },
    {
      name: "FLOAT_NUMBER",
      pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?",
      isRegex: true,
      lineNumber: 58,
      alias: "NUMBER",
    },
    {
      name: "LEADING_DOT_FLOAT",
      pattern: "\\.[0-9]+([eE][+-]?[0-9]+)?",
      isRegex: true,
      lineNumber: 59,
      alias: "NUMBER",
    },
    {
      name: "SCI_NUMBER",
      pattern: "[0-9]+[eE][+-]?[0-9]+",
      isRegex: true,
      lineNumber: 60,
      alias: "NUMBER",
    },
    {
      name: "INT_NUMBER",
      pattern: "[0-9]+",
      isRegex: true,
      lineNumber: 61,
      alias: "NUMBER",
    },
    {
      name: "STRING_DQ",
      pattern: "\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 65,
      alias: "STRING",
    },
    {
      name: "STRING_SQ",
      pattern: "'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 66,
      alias: "STRING",
    },
    {
      name: "TEMPLATE_HEAD",
      pattern: "`([^`\\\\$]|\\\\.|\\$[^{])*\\$\\{",
      isRegex: true,
      lineNumber: 74,
    },
    {
      name: "TEMPLATE_NO_SUB",
      pattern: "`([^`\\\\$]|\\\\.|\\$[^{])*`",
      isRegex: true,
      lineNumber: 75,
    },
    {
      name: "REGEX",
      pattern: "\\/([^\\/\\\\\\n]|\\\\.)+\\/[gimsuy]*",
      isRegex: true,
      lineNumber: 79,
    },
    {
      name: "STAR_STAR_EQUALS",
      pattern: "**=",
      isRegex: false,
      lineNumber: 85,
    },
    {
      name: "STAR_STAR",
      pattern: "**",
      isRegex: false,
      lineNumber: 86,
    },
    {
      name: "STRICT_EQUALS",
      pattern: "===",
      isRegex: false,
      lineNumber: 87,
    },
    {
      name: "STRICT_NOT_EQUALS",
      pattern: "!==",
      isRegex: false,
      lineNumber: 88,
    },
    {
      name: "UNSIGNED_RIGHT_SHIFT_EQUALS",
      pattern: ">>>=",
      isRegex: false,
      lineNumber: 89,
    },
    {
      name: "UNSIGNED_RIGHT_SHIFT",
      pattern: ">>>",
      isRegex: false,
      lineNumber: 90,
    },
    {
      name: "LEFT_SHIFT_EQUALS",
      pattern: "<<=",
      isRegex: false,
      lineNumber: 91,
    },
    {
      name: "RIGHT_SHIFT_EQUALS",
      pattern: ">>=",
      isRegex: false,
      lineNumber: 92,
    },
    {
      name: "EQUALS_EQUALS",
      pattern: "==",
      isRegex: false,
      lineNumber: 93,
    },
    {
      name: "NOT_EQUALS",
      pattern: "!=",
      isRegex: false,
      lineNumber: 94,
    },
    {
      name: "LESS_EQUALS",
      pattern: "<=",
      isRegex: false,
      lineNumber: 95,
    },
    {
      name: "GREATER_EQUALS",
      pattern: ">=",
      isRegex: false,
      lineNumber: 96,
    },
    {
      name: "PLUS_EQUALS",
      pattern: "+=",
      isRegex: false,
      lineNumber: 97,
    },
    {
      name: "MINUS_EQUALS",
      pattern: "-=",
      isRegex: false,
      lineNumber: 98,
    },
    {
      name: "STAR_EQUALS",
      pattern: "*=",
      isRegex: false,
      lineNumber: 99,
    },
    {
      name: "SLASH_EQUALS",
      pattern: "/=",
      isRegex: false,
      lineNumber: 100,
    },
    {
      name: "PERCENT_EQUALS",
      pattern: "%=",
      isRegex: false,
      lineNumber: 101,
    },
    {
      name: "AMPERSAND_EQUALS",
      pattern: "&=",
      isRegex: false,
      lineNumber: 102,
    },
    {
      name: "PIPE_EQUALS",
      pattern: "|=",
      isRegex: false,
      lineNumber: 103,
    },
    {
      name: "CARET_EQUALS",
      pattern: "^=",
      isRegex: false,
      lineNumber: 104,
    },
    {
      name: "LEFT_SHIFT",
      pattern: "<<",
      isRegex: false,
      lineNumber: 105,
    },
    {
      name: "RIGHT_SHIFT",
      pattern: ">>",
      isRegex: false,
      lineNumber: 106,
    },
    {
      name: "AND_AND",
      pattern: "&&",
      isRegex: false,
      lineNumber: 107,
    },
    {
      name: "OR_OR",
      pattern: "||",
      isRegex: false,
      lineNumber: 108,
    },
    {
      name: "PLUS_PLUS",
      pattern: "++",
      isRegex: false,
      lineNumber: 109,
    },
    {
      name: "MINUS_MINUS",
      pattern: "--",
      isRegex: false,
      lineNumber: 110,
    },
    {
      name: "ARROW",
      pattern: "=>",
      isRegex: false,
      lineNumber: 111,
    },
    {
      name: "ELLIPSIS",
      pattern: "...",
      isRegex: false,
      lineNumber: 112,
    },
    {
      name: "EQUALS",
      pattern: "=",
      isRegex: false,
      lineNumber: 118,
    },
    {
      name: "PLUS",
      pattern: "+",
      isRegex: false,
      lineNumber: 119,
    },
    {
      name: "MINUS",
      pattern: "-",
      isRegex: false,
      lineNumber: 120,
    },
    {
      name: "STAR",
      pattern: "*",
      isRegex: false,
      lineNumber: 121,
    },
    {
      name: "SLASH",
      pattern: "/",
      isRegex: false,
      lineNumber: 122,
    },
    {
      name: "PERCENT",
      pattern: "%",
      isRegex: false,
      lineNumber: 123,
    },
    {
      name: "LESS_THAN",
      pattern: "<",
      isRegex: false,
      lineNumber: 124,
    },
    {
      name: "GREATER_THAN",
      pattern: ">",
      isRegex: false,
      lineNumber: 125,
    },
    {
      name: "BANG",
      pattern: "!",
      isRegex: false,
      lineNumber: 126,
    },
    {
      name: "AMPERSAND",
      pattern: "&",
      isRegex: false,
      lineNumber: 127,
    },
    {
      name: "PIPE",
      pattern: "|",
      isRegex: false,
      lineNumber: 128,
    },
    {
      name: "CARET",
      pattern: "^",
      isRegex: false,
      lineNumber: 129,
    },
    {
      name: "TILDE",
      pattern: "~",
      isRegex: false,
      lineNumber: 130,
    },
    {
      name: "QUESTION",
      pattern: "?",
      isRegex: false,
      lineNumber: 131,
    },
    {
      name: "LPAREN",
      pattern: "(",
      isRegex: false,
      lineNumber: 137,
    },
    {
      name: "RPAREN",
      pattern: ")",
      isRegex: false,
      lineNumber: 138,
    },
    {
      name: "LBRACE",
      pattern: "{",
      isRegex: false,
      lineNumber: 139,
    },
    {
      name: "RBRACE",
      pattern: "}",
      isRegex: false,
      lineNumber: 140,
    },
    {
      name: "LBRACKET",
      pattern: "[",
      isRegex: false,
      lineNumber: 141,
    },
    {
      name: "RBRACKET",
      pattern: "]",
      isRegex: false,
      lineNumber: 142,
    },
    {
      name: "SEMICOLON",
      pattern: ";",
      isRegex: false,
      lineNumber: 143,
    },
    {
      name: "COMMA",
      pattern: ",",
      isRegex: false,
      lineNumber: 144,
    },
    {
      name: "COLON",
      pattern: ":",
      isRegex: false,
      lineNumber: 145,
    },
    {
      name: "DOT",
      pattern: ".",
      isRegex: false,
      lineNumber: 146,
    },
    {
      name: "AT",
      pattern: "@",
      isRegex: false,
      lineNumber: 167,
    },
  ],
  keywords: ["break","case","catch","class","const","continue","debugger","default","delete","do","else","export","extends","finally","for","function","if","import","in","instanceof","let","new","return","super","switch","this","throw","try","typeof","var","void","while","with","yield","true","false","null","enum","async","await"],
  mode: undefined,
  escapeMode: undefined,
  skipDefinitions: [
    {
      name: "WHITESPACE",
      pattern: "[ \\t\\r\\n\\v\\f]+",
      isRegex: true,
      lineNumber: 284,
    },
    {
      name: "LINE_COMMENT",
      pattern: "\\/\\/[^\\n]*",
      isRegex: true,
      lineNumber: 285,
    },
    {
      name: "BLOCK_COMMENT",
      pattern: "\\/\\*([^*]|\\*[^\\/])*\\*\\/",
      isRegex: true,
      lineNumber: 286,
    },
  ],
  reservedKeywords: [],
  layoutKeywords: [],
  contextKeywords: ["as","from","of","get","set","static","type","interface","namespace","module","declare","abstract","readonly","is","keyof","asserts","unique","infer","never","unknown","override","out","satisfies","accessor"],
  errorDefinitions: [],
  groups: {
    "template": {
      name: "template",
      definitions: [
        {
          name: "TEMPLATE_MIDDLE",
          pattern: "\\}([^`\\\\$]|\\\\.|\\$[^{])*\\$\\{",
          isRegex: true,
          lineNumber: 276,
        },
        {
          name: "TEMPLATE_TAIL",
          pattern: "\\}([^`\\\\$]|\\\\.|\\$[^{])*`",
          isRegex: true,
          lineNumber: 277,
        },
      ],
    },
  },
  softKeywords: [],
};
