// AUTO-GENERATED FILE - DO NOT EDIT
// Source: ts4.0.tokens
// Regenerate with: grammar-tools compile-tokens ts4.0.tokens
//
// This file embeds a TokenGrammar as native TypeScript object literals.
// Import it directly instead of reading and parsing the .tokens file at
// runtime.

import type { TokenGrammar } from "@coding-adventures/grammar-tools";

export const TOKEN_GRAMMAR: TokenGrammar = {
  version: 1,
  caseInsensitive: false,
  caseSensitive: true,
  definitions: [
    {
      name: "NAME",
      pattern: "[a-zA-Z_$][a-zA-Z0-9_$]*",
      isRegex: true,
      lineNumber: 57,
    },
    {
      name: "BIGINT_HEX",
      pattern: "0[xX][0-9a-fA-F]+n",
      isRegex: true,
      lineNumber: 64,
      alias: "BIGINT",
    },
    {
      name: "BIGINT_BINARY",
      pattern: "0[bB][01]+n",
      isRegex: true,
      lineNumber: 65,
      alias: "BIGINT",
    },
    {
      name: "BIGINT_OCTAL",
      pattern: "0[oO][0-7]+n",
      isRegex: true,
      lineNumber: 66,
      alias: "BIGINT",
    },
    {
      name: "BIGINT_DECIMAL",
      pattern: "[0-9]+n",
      isRegex: true,
      lineNumber: 67,
      alias: "BIGINT",
    },
    {
      name: "BINARY_NUMBER",
      pattern: "0[bB][01]+",
      isRegex: true,
      lineNumber: 71,
      alias: "NUMBER",
    },
    {
      name: "OCTAL_NUMBER",
      pattern: "0[oO][0-7]+",
      isRegex: true,
      lineNumber: 72,
      alias: "NUMBER",
    },
    {
      name: "HEX_NUMBER",
      pattern: "0[xX][0-9a-fA-F]+",
      isRegex: true,
      lineNumber: 73,
      alias: "NUMBER",
    },
    {
      name: "FLOAT_NUMBER",
      pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?",
      isRegex: true,
      lineNumber: 74,
      alias: "NUMBER",
    },
    {
      name: "LEADING_DOT_FLOAT",
      pattern: "\\.[0-9]+([eE][+-]?[0-9]+)?",
      isRegex: true,
      lineNumber: 75,
      alias: "NUMBER",
    },
    {
      name: "SCI_NUMBER",
      pattern: "[0-9]+[eE][+-]?[0-9]+",
      isRegex: true,
      lineNumber: 76,
      alias: "NUMBER",
    },
    {
      name: "INT_NUMBER",
      pattern: "[0-9]+",
      isRegex: true,
      lineNumber: 77,
      alias: "NUMBER",
    },
    {
      name: "STRING_DQ",
      pattern: "\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 81,
      alias: "STRING",
    },
    {
      name: "STRING_SQ",
      pattern: "'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 82,
      alias: "STRING",
    },
    {
      name: "TEMPLATE_HEAD",
      pattern: "`([^`\\\\$]|\\\\.|\\$[^{])*\\$\\{",
      isRegex: true,
      lineNumber: 91,
    },
    {
      name: "TEMPLATE_NO_SUB",
      pattern: "`([^`\\\\$]|\\\\.|\\$[^{])*`",
      isRegex: true,
      lineNumber: 92,
    },
    {
      name: "REGEX",
      pattern: "\\/([^\\/\\\\\\n]|\\\\.)+\\/[gimsuy]*",
      isRegex: true,
      lineNumber: 96,
    },
    {
      name: "OPTIONAL_CHAIN",
      pattern: "?.",
      isRegex: false,
      lineNumber: 107,
    },
    {
      name: "NULLISH_EQUALS",
      pattern: "??=",
      isRegex: false,
      lineNumber: 119,
    },
    {
      name: "NULLISH_COALESCE",
      pattern: "??",
      isRegex: false,
      lineNumber: 120,
    },
    {
      name: "AND_AND_EQUALS",
      pattern: "&&=",
      isRegex: false,
      lineNumber: 121,
    },
    {
      name: "OR_OR_EQUALS",
      pattern: "||=",
      isRegex: false,
      lineNumber: 122,
    },
    {
      name: "STAR_STAR_EQUALS",
      pattern: "**=",
      isRegex: false,
      lineNumber: 126,
    },
    {
      name: "STAR_STAR",
      pattern: "**",
      isRegex: false,
      lineNumber: 127,
    },
    {
      name: "STRICT_EQUALS",
      pattern: "===",
      isRegex: false,
      lineNumber: 128,
    },
    {
      name: "STRICT_NOT_EQUALS",
      pattern: "!==",
      isRegex: false,
      lineNumber: 129,
    },
    {
      name: "UNSIGNED_RIGHT_SHIFT_EQUALS",
      pattern: ">>>=",
      isRegex: false,
      lineNumber: 130,
    },
    {
      name: "UNSIGNED_RIGHT_SHIFT",
      pattern: ">>>",
      isRegex: false,
      lineNumber: 131,
    },
    {
      name: "LEFT_SHIFT_EQUALS",
      pattern: "<<=",
      isRegex: false,
      lineNumber: 132,
    },
    {
      name: "RIGHT_SHIFT_EQUALS",
      pattern: ">>=",
      isRegex: false,
      lineNumber: 133,
    },
    {
      name: "EQUALS_EQUALS",
      pattern: "==",
      isRegex: false,
      lineNumber: 134,
    },
    {
      name: "NOT_EQUALS",
      pattern: "!=",
      isRegex: false,
      lineNumber: 135,
    },
    {
      name: "LESS_EQUALS",
      pattern: "<=",
      isRegex: false,
      lineNumber: 136,
    },
    {
      name: "GREATER_EQUALS",
      pattern: ">=",
      isRegex: false,
      lineNumber: 137,
    },
    {
      name: "PLUS_EQUALS",
      pattern: "+=",
      isRegex: false,
      lineNumber: 138,
    },
    {
      name: "MINUS_EQUALS",
      pattern: "-=",
      isRegex: false,
      lineNumber: 139,
    },
    {
      name: "STAR_EQUALS",
      pattern: "*=",
      isRegex: false,
      lineNumber: 140,
    },
    {
      name: "SLASH_EQUALS",
      pattern: "/=",
      isRegex: false,
      lineNumber: 141,
    },
    {
      name: "PERCENT_EQUALS",
      pattern: "%=",
      isRegex: false,
      lineNumber: 142,
    },
    {
      name: "AMPERSAND_EQUALS",
      pattern: "&=",
      isRegex: false,
      lineNumber: 143,
    },
    {
      name: "PIPE_EQUALS",
      pattern: "|=",
      isRegex: false,
      lineNumber: 144,
    },
    {
      name: "CARET_EQUALS",
      pattern: "^=",
      isRegex: false,
      lineNumber: 145,
    },
    {
      name: "LEFT_SHIFT",
      pattern: "<<",
      isRegex: false,
      lineNumber: 146,
    },
    {
      name: "RIGHT_SHIFT",
      pattern: ">>",
      isRegex: false,
      lineNumber: 147,
    },
    {
      name: "AND_AND",
      pattern: "&&",
      isRegex: false,
      lineNumber: 148,
    },
    {
      name: "OR_OR",
      pattern: "||",
      isRegex: false,
      lineNumber: 149,
    },
    {
      name: "PLUS_PLUS",
      pattern: "++",
      isRegex: false,
      lineNumber: 150,
    },
    {
      name: "MINUS_MINUS",
      pattern: "--",
      isRegex: false,
      lineNumber: 151,
    },
    {
      name: "ARROW",
      pattern: "=>",
      isRegex: false,
      lineNumber: 152,
    },
    {
      name: "ELLIPSIS",
      pattern: "...",
      isRegex: false,
      lineNumber: 153,
    },
    {
      name: "EQUALS",
      pattern: "=",
      isRegex: false,
      lineNumber: 159,
    },
    {
      name: "PLUS",
      pattern: "+",
      isRegex: false,
      lineNumber: 160,
    },
    {
      name: "MINUS",
      pattern: "-",
      isRegex: false,
      lineNumber: 161,
    },
    {
      name: "STAR",
      pattern: "*",
      isRegex: false,
      lineNumber: 162,
    },
    {
      name: "SLASH",
      pattern: "/",
      isRegex: false,
      lineNumber: 163,
    },
    {
      name: "PERCENT",
      pattern: "%",
      isRegex: false,
      lineNumber: 164,
    },
    {
      name: "LESS_THAN",
      pattern: "<",
      isRegex: false,
      lineNumber: 165,
    },
    {
      name: "GREATER_THAN",
      pattern: ">",
      isRegex: false,
      lineNumber: 166,
    },
    {
      name: "BANG",
      pattern: "!",
      isRegex: false,
      lineNumber: 167,
    },
    {
      name: "AMPERSAND",
      pattern: "&",
      isRegex: false,
      lineNumber: 168,
    },
    {
      name: "PIPE",
      pattern: "|",
      isRegex: false,
      lineNumber: 169,
    },
    {
      name: "CARET",
      pattern: "^",
      isRegex: false,
      lineNumber: 170,
    },
    {
      name: "TILDE",
      pattern: "~",
      isRegex: false,
      lineNumber: 171,
    },
    {
      name: "QUESTION",
      pattern: "?",
      isRegex: false,
      lineNumber: 172,
    },
    {
      name: "LPAREN",
      pattern: "(",
      isRegex: false,
      lineNumber: 178,
    },
    {
      name: "RPAREN",
      pattern: ")",
      isRegex: false,
      lineNumber: 179,
    },
    {
      name: "LBRACE",
      pattern: "{",
      isRegex: false,
      lineNumber: 180,
    },
    {
      name: "RBRACE",
      pattern: "}",
      isRegex: false,
      lineNumber: 181,
    },
    {
      name: "LBRACKET",
      pattern: "[",
      isRegex: false,
      lineNumber: 182,
    },
    {
      name: "RBRACKET",
      pattern: "]",
      isRegex: false,
      lineNumber: 183,
    },
    {
      name: "SEMICOLON",
      pattern: ";",
      isRegex: false,
      lineNumber: 184,
    },
    {
      name: "COMMA",
      pattern: ",",
      isRegex: false,
      lineNumber: 185,
    },
    {
      name: "COLON",
      pattern: ":",
      isRegex: false,
      lineNumber: 186,
    },
    {
      name: "DOT",
      pattern: ".",
      isRegex: false,
      lineNumber: 187,
    },
    {
      name: "AT",
      pattern: "@",
      isRegex: false,
      lineNumber: 196,
    },
  ],
  keywords: ["break","case","catch","class","const","continue","debugger","default","delete","do","else","export","extends","finally","for","function","if","import","in","instanceof","let","new","return","super","switch","this","throw","try","typeof","var","void","while","with","yield","true","false","null","enum","async","await"],
  mode: undefined,
  escapeMode: undefined,
  skipDefinitions: [
    {
      name: "WHITESPACE",
      pattern: "[ \\t\\r\\n\\v\\f]+",
      isRegex: true,
      lineNumber: 303,
    },
    {
      name: "LINE_COMMENT",
      pattern: "\\/\\/[^\\n]*",
      isRegex: true,
      lineNumber: 304,
    },
    {
      name: "BLOCK_COMMENT",
      pattern: "\\/\\*([^*]|\\*[^\\/])*\\*\\/",
      isRegex: true,
      lineNumber: 305,
    },
  ],
  reservedKeywords: [],
  layoutKeywords: [],
  contextKeywords: ["as","from","of","get","set","static","type","interface","namespace","module","declare","abstract","readonly","is","keyof","asserts","unique","infer","never","unknown","override","out","satisfies","accessor"],
  errorDefinitions: [],
  groups: {
    "template": {
      name: "template",
      definitions: [
        {
          name: "TEMPLATE_MIDDLE",
          pattern: "\\}([^`\\\\$]|\\\\.|\\$[^{])*\\$\\{",
          isRegex: true,
          lineNumber: 295,
        },
        {
          name: "TEMPLATE_TAIL",
          pattern: "\\}([^`\\\\$]|\\\\.|\\$[^{])*`",
          isRegex: true,
          lineNumber: 296,
        },
      ],
    },
  },
  softKeywords: [],
};
