// AUTO-GENERATED FILE - DO NOT EDIT
// Source: ts5.8.tokens
// Regenerate with: grammar-tools compile-tokens ts5.8.tokens
//
// This file embeds a TokenGrammar as native TypeScript object literals.
// Import it directly instead of reading and parsing the .tokens file at
// runtime.

import type { TokenGrammar } from "@coding-adventures/grammar-tools";

export const TOKEN_GRAMMAR: TokenGrammar = {
  version: 1,
  caseInsensitive: false,
  caseSensitive: true,
  definitions: [
    {
      name: "HASHBANG",
      pattern: "^#![^\\n]*",
      isRegex: true,
      lineNumber: 87,
    },
    {
      name: "NAME",
      pattern: "[a-zA-Z_$][a-zA-Z0-9_$]*",
      isRegex: true,
      lineNumber: 89,
    },
    {
      name: "PRIVATE_NAME",
      pattern: "#[a-zA-Z_$][a-zA-Z0-9_$]*",
      isRegex: true,
      lineNumber: 93,
    },
    {
      name: "BIGINT_HEX",
      pattern: "0[xX][0-9a-fA-F]([0-9a-fA-F_]*[0-9a-fA-F])?n",
      isRegex: true,
      lineNumber: 97,
      alias: "BIGINT",
    },
    {
      name: "BIGINT_BINARY",
      pattern: "0[bB][01]([01_]*[01])?n",
      isRegex: true,
      lineNumber: 98,
      alias: "BIGINT",
    },
    {
      name: "BIGINT_OCTAL",
      pattern: "0[oO][0-7]([0-7_]*[0-7])?n",
      isRegex: true,
      lineNumber: 99,
      alias: "BIGINT",
    },
    {
      name: "BIGINT_DECIMAL",
      pattern: "[0-9]([0-9_]*[0-9])?n",
      isRegex: true,
      lineNumber: 100,
      alias: "BIGINT",
    },
    {
      name: "BINARY_NUMBER",
      pattern: "0[bB][01]([01_]*[01])?",
      isRegex: true,
      lineNumber: 102,
      alias: "NUMBER",
    },
    {
      name: "OCTAL_NUMBER",
      pattern: "0[oO][0-7]([0-7_]*[0-7])?",
      isRegex: true,
      lineNumber: 103,
      alias: "NUMBER",
    },
    {
      name: "HEX_NUMBER",
      pattern: "0[xX][0-9a-fA-F]([0-9a-fA-F_]*[0-9a-fA-F])?",
      isRegex: true,
      lineNumber: 104,
      alias: "NUMBER",
    },
    {
      name: "FLOAT_NUMBER",
      pattern: "[0-9]([0-9_]*[0-9])?\\.[0-9]([0-9_]*[0-9])?([eE][+-]?[0-9]([0-9_]*[0-9])?)?",
      isRegex: true,
      lineNumber: 105,
      alias: "NUMBER",
    },
    {
      name: "LEADING_DOT_FLOAT",
      pattern: "\\.[0-9]([0-9_]*[0-9])?([eE][+-]?[0-9]([0-9_]*[0-9])?)?",
      isRegex: true,
      lineNumber: 106,
      alias: "NUMBER",
    },
    {
      name: "SCI_NUMBER",
      pattern: "[0-9]([0-9_]*[0-9])?[eE][+-]?[0-9]([0-9_]*[0-9])?",
      isRegex: true,
      lineNumber: 107,
      alias: "NUMBER",
    },
    {
      name: "INT_NUMBER",
      pattern: "[0-9]([0-9_]*[0-9])?",
      isRegex: true,
      lineNumber: 108,
      alias: "NUMBER",
    },
    {
      name: "STRING_DQ",
      pattern: "\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 112,
      alias: "STRING",
    },
    {
      name: "STRING_SQ",
      pattern: "'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 113,
      alias: "STRING",
    },
    {
      name: "TEMPLATE_HEAD",
      pattern: "`([^`\\\\$]|\\\\.|\\$[^{])*\\$\\{",
      isRegex: true,
      lineNumber: 117,
    },
    {
      name: "TEMPLATE_NO_SUB",
      pattern: "`([^`\\\\$]|\\\\.|\\$[^{])*`",
      isRegex: true,
      lineNumber: 118,
    },
    {
      name: "REGEX",
      pattern: "\\/([^\\/\\\\\\n]|\\\\.)+\\/[dgimsvy]*",
      isRegex: true,
      lineNumber: 131,
    },
    {
      name: "OR_OR_EQUALS",
      pattern: "||=",
      isRegex: false,
      lineNumber: 137,
    },
    {
      name: "AND_AND_EQUALS",
      pattern: "&&=",
      isRegex: false,
      lineNumber: 138,
    },
    {
      name: "NULLISH_COALESCE_EQUALS",
      pattern: "??=",
      isRegex: false,
      lineNumber: 139,
    },
    {
      name: "OPTIONAL_CHAIN",
      pattern: "?.",
      isRegex: false,
      lineNumber: 140,
    },
    {
      name: "NULLISH_COALESCE",
      pattern: "??",
      isRegex: false,
      lineNumber: 141,
    },
    {
      name: "STAR_STAR_EQUALS",
      pattern: "**=",
      isRegex: false,
      lineNumber: 142,
    },
    {
      name: "STAR_STAR",
      pattern: "**",
      isRegex: false,
      lineNumber: 143,
    },
    {
      name: "STRICT_EQUALS",
      pattern: "===",
      isRegex: false,
      lineNumber: 144,
    },
    {
      name: "STRICT_NOT_EQUALS",
      pattern: "!==",
      isRegex: false,
      lineNumber: 145,
    },
    {
      name: "UNSIGNED_RIGHT_SHIFT_EQUALS",
      pattern: ">>>=",
      isRegex: false,
      lineNumber: 146,
    },
    {
      name: "UNSIGNED_RIGHT_SHIFT",
      pattern: ">>>",
      isRegex: false,
      lineNumber: 147,
    },
    {
      name: "LEFT_SHIFT_EQUALS",
      pattern: "<<=",
      isRegex: false,
      lineNumber: 148,
    },
    {
      name: "RIGHT_SHIFT_EQUALS",
      pattern: ">>=",
      isRegex: false,
      lineNumber: 149,
    },
    {
      name: "EQUALS_EQUALS",
      pattern: "==",
      isRegex: false,
      lineNumber: 150,
    },
    {
      name: "NOT_EQUALS",
      pattern: "!=",
      isRegex: false,
      lineNumber: 151,
    },
    {
      name: "LESS_EQUALS",
      pattern: "<=",
      isRegex: false,
      lineNumber: 152,
    },
    {
      name: "GREATER_EQUALS",
      pattern: ">=",
      isRegex: false,
      lineNumber: 153,
    },
    {
      name: "PLUS_EQUALS",
      pattern: "+=",
      isRegex: false,
      lineNumber: 154,
    },
    {
      name: "MINUS_EQUALS",
      pattern: "-=",
      isRegex: false,
      lineNumber: 155,
    },
    {
      name: "STAR_EQUALS",
      pattern: "*=",
      isRegex: false,
      lineNumber: 156,
    },
    {
      name: "SLASH_EQUALS",
      pattern: "/=",
      isRegex: false,
      lineNumber: 157,
    },
    {
      name: "PERCENT_EQUALS",
      pattern: "%=",
      isRegex: false,
      lineNumber: 158,
    },
    {
      name: "AMPERSAND_EQUALS",
      pattern: "&=",
      isRegex: false,
      lineNumber: 159,
    },
    {
      name: "PIPE_EQUALS",
      pattern: "|=",
      isRegex: false,
      lineNumber: 160,
    },
    {
      name: "CARET_EQUALS",
      pattern: "^=",
      isRegex: false,
      lineNumber: 161,
    },
    {
      name: "LEFT_SHIFT",
      pattern: "<<",
      isRegex: false,
      lineNumber: 162,
    },
    {
      name: "RIGHT_SHIFT",
      pattern: ">>",
      isRegex: false,
      lineNumber: 163,
    },
    {
      name: "AND_AND",
      pattern: "&&",
      isRegex: false,
      lineNumber: 164,
    },
    {
      name: "OR_OR",
      pattern: "||",
      isRegex: false,
      lineNumber: 165,
    },
    {
      name: "PLUS_PLUS",
      pattern: "++",
      isRegex: false,
      lineNumber: 166,
    },
    {
      name: "MINUS_MINUS",
      pattern: "--",
      isRegex: false,
      lineNumber: 167,
    },
    {
      name: "ARROW",
      pattern: "=>",
      isRegex: false,
      lineNumber: 168,
    },
    {
      name: "ELLIPSIS",
      pattern: "...",
      isRegex: false,
      lineNumber: 169,
    },
    {
      name: "EQUALS",
      pattern: "=",
      isRegex: false,
      lineNumber: 175,
    },
    {
      name: "PLUS",
      pattern: "+",
      isRegex: false,
      lineNumber: 176,
    },
    {
      name: "MINUS",
      pattern: "-",
      isRegex: false,
      lineNumber: 177,
    },
    {
      name: "STAR",
      pattern: "*",
      isRegex: false,
      lineNumber: 178,
    },
    {
      name: "SLASH",
      pattern: "/",
      isRegex: false,
      lineNumber: 179,
    },
    {
      name: "PERCENT",
      pattern: "%",
      isRegex: false,
      lineNumber: 180,
    },
    {
      name: "LESS_THAN",
      pattern: "<",
      isRegex: false,
      lineNumber: 181,
    },
    {
      name: "GREATER_THAN",
      pattern: ">",
      isRegex: false,
      lineNumber: 182,
    },
    {
      name: "BANG",
      pattern: "!",
      isRegex: false,
      lineNumber: 183,
    },
    {
      name: "AMPERSAND",
      pattern: "&",
      isRegex: false,
      lineNumber: 184,
    },
    {
      name: "PIPE",
      pattern: "|",
      isRegex: false,
      lineNumber: 185,
    },
    {
      name: "CARET",
      pattern: "^",
      isRegex: false,
      lineNumber: 186,
    },
    {
      name: "TILDE",
      pattern: "~",
      isRegex: false,
      lineNumber: 187,
    },
    {
      name: "QUESTION",
      pattern: "?",
      isRegex: false,
      lineNumber: 188,
    },
    {
      name: "AT",
      pattern: "@",
      isRegex: false,
      lineNumber: 200,
    },
    {
      name: "LPAREN",
      pattern: "(",
      isRegex: false,
      lineNumber: 206,
    },
    {
      name: "RPAREN",
      pattern: ")",
      isRegex: false,
      lineNumber: 207,
    },
    {
      name: "LBRACE",
      pattern: "{",
      isRegex: false,
      lineNumber: 208,
    },
    {
      name: "RBRACE",
      pattern: "}",
      isRegex: false,
      lineNumber: 209,
    },
    {
      name: "LBRACKET",
      pattern: "[",
      isRegex: false,
      lineNumber: 210,
    },
    {
      name: "RBRACKET",
      pattern: "]",
      isRegex: false,
      lineNumber: 211,
    },
    {
      name: "SEMICOLON",
      pattern: ";",
      isRegex: false,
      lineNumber: 212,
    },
    {
      name: "COMMA",
      pattern: ",",
      isRegex: false,
      lineNumber: 213,
    },
    {
      name: "COLON",
      pattern: ":",
      isRegex: false,
      lineNumber: 214,
    },
    {
      name: "DOT",
      pattern: ".",
      isRegex: false,
      lineNumber: 215,
    },
  ],
  keywords: ["break","case","catch","class","const","continue","debugger","default","delete","do","else","export","extends","finally","for","function","if","import","in","instanceof","let","new","return","super","switch","this","throw","try","typeof","var","void","while","with","yield","true","false","null","enum","async","await"],
  mode: undefined,
  escapeMode: undefined,
  skipDefinitions: [
    {
      name: "WHITESPACE",
      pattern: "[ \\t\\r\\n\\v\\f]+",
      isRegex: true,
      lineNumber: 322,
    },
    {
      name: "LINE_COMMENT",
      pattern: "\\/\\/[^\\n]*",
      isRegex: true,
      lineNumber: 323,
    },
    {
      name: "BLOCK_COMMENT",
      pattern: "\\/\\*([^*]|\\*[^\\/])*\\*\\/",
      isRegex: true,
      lineNumber: 324,
    },
  ],
  reservedKeywords: [],
  layoutKeywords: [],
  contextKeywords: ["as","from","of","get","set","static","using","type","interface","namespace","module","declare","abstract","readonly","is","keyof","asserts","unique","infer","never","unknown","override","out","satisfies","accessor"],
  errorDefinitions: [],
  groups: {
    "template": {
      name: "template",
      definitions: [
        {
          name: "TEMPLATE_MIDDLE",
          pattern: "\\}([^`\\\\$]|\\\\.|\\$[^{])*\\$\\{",
          isRegex: true,
          lineNumber: 314,
        },
        {
          name: "TEMPLATE_TAIL",
          pattern: "\\}([^`\\\\$]|\\\\.|\\$[^{])*`",
          isRegex: true,
          lineNumber: 315,
        },
      ],
    },
  },
  softKeywords: [],
};
