// GENERATED by code/scripts/generate_atbash_fixture_consumers.py.
// Source SHA-256: efd6c3a85a0c1d0676c31bf709d7c3d7eb5f4aef6b31ac2f904ebad6d76ad02c
// Cases: classical-ciphers-v1-atbash-empty, classical-ciphers-v1-atbash-uppercase-alphabet, classical-ciphers-v1-atbash-lowercase-alphabet, classical-ciphers-v1-atbash-passthrough, classical-ciphers-v1-atbash-involution-forward, classical-ciphers-v1-atbash-involution-reverse

namespace CodingAdventures.AtbashCipher.Tests;

public sealed class GeneratedClassicalCipherFixtureTests
{
    private static string S(params int[] codePoints)
    {
        var builder = new System.Text.StringBuilder();
        foreach (var codePoint in codePoints)
        {
            builder.Append(char.ConvertFromUtf32(codePoint));
        }
        return builder.ToString();
    }

    [Fact]
    public void ExecutesCompleteNormativeAtbashObjects()
    {
        var cases = new[]
        {
            (Id: "classical-ciphers-v1-atbash-empty", Input: S(), Expected: S()),
            (Id: "classical-ciphers-v1-atbash-uppercase-alphabet", Input: S(65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90), Expected: S(90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65)),
            (Id: "classical-ciphers-v1-atbash-lowercase-alphabet", Input: S(97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122), Expected: S(122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112, 111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100, 99, 98, 97)),
            (Id: "classical-ciphers-v1-atbash-passthrough", Input: S(72, 101, 108, 108, 111, 44, 32, 87, 111, 114, 108, 100, 33, 32, 49, 50, 51, 0, 32, 233, 128512), Expected: S(83, 118, 111, 111, 108, 44, 32, 68, 108, 105, 111, 119, 33, 32, 49, 50, 51, 0, 32, 233, 128512)),
            (Id: "classical-ciphers-v1-atbash-involution-forward", Input: S(72, 69, 76, 76, 79), Expected: S(83, 86, 79, 79, 76)),
            (Id: "classical-ciphers-v1-atbash-involution-reverse", Input: S(83, 86, 79, 79, 76), Expected: S(72, 69, 76, 76, 79)),
        };
        foreach (var fixtureCase in cases)
        {
            Assert.Equal(fixtureCase.Expected, AtbashCipher.Encrypt(fixtureCase.Input));
        }
    }
}
