defmodule CodingAdventures.PythonLexer.Grammar.V3_12 do
  # AUTO-GENERATED FILE — DO NOT EDIT
  # Source: python3.12.tokens
  # Regenerate with: grammar-tools compile-tokens python3.12.tokens
  #
  # This file embeds a TokenGrammar as native Elixir data structures.
  # Call token_grammar/0 instead of reading and parsing the .tokens file.
  
  alias CodingAdventures.GrammarTools.TokenGrammar
  
  def token_grammar do
    %TokenGrammar{
      definitions: [
          %{
            name: "STRING_RAW_FSTRING_TRIPLE_DQ",
            pattern: "[rR][fF]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"|[fF][rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
            is_regex: true,
            line_number: 107,
            alias: "STRING",
          },
          %{
            name: "STRING_RAW_FSTRING_TRIPLE_SQ",
            pattern: "[rR][fF]'''([^'\\\\]|\\\\.|\\n)*'''|[fF][rR]'''([^'\\\\]|\\\\.|\\n)*'''",
            is_regex: true,
            line_number: 108,
            alias: "STRING",
          },
          %{
            name: "STRING_RAW_BYTES_TRIPLE_DQ",
            pattern: "[bB][rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"|[rR][bB]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
            is_regex: true,
            line_number: 109,
            alias: "STRING",
          },
          %{
            name: "STRING_RAW_BYTES_TRIPLE_SQ",
            pattern: "[bB][rR]'''([^'\\\\]|\\\\.|\\n)*'''|[rR][bB]'''([^'\\\\]|\\\\.|\\n)*'''",
            is_regex: true,
            line_number: 110,
            alias: "STRING",
          },
          %{
            name: "STRING_FSTRING_TRIPLE_DQ",
            pattern: "[fF]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
            is_regex: true,
            line_number: 112,
            alias: "STRING",
          },
          %{
            name: "STRING_FSTRING_TRIPLE_SQ",
            pattern: "[fF]'''([^'\\\\]|\\\\.|\\n)*'''",
            is_regex: true,
            line_number: 113,
            alias: "STRING",
          },
          %{
            name: "STRING_UNICODE_TRIPLE_DQ",
            pattern: "[uU]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
            is_regex: true,
            line_number: 114,
            alias: "STRING",
          },
          %{
            name: "STRING_UNICODE_TRIPLE_SQ",
            pattern: "[uU]'''([^'\\\\]|\\\\.|\\n)*'''",
            is_regex: true,
            line_number: 115,
            alias: "STRING",
          },
          %{
            name: "STRING_RAW_TRIPLE_DQ",
            pattern: "[rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
            is_regex: true,
            line_number: 116,
            alias: "STRING",
          },
          %{
            name: "STRING_RAW_TRIPLE_SQ",
            pattern: "[rR]'''([^'\\\\]|\\\\.|\\n)*'''",
            is_regex: true,
            line_number: 117,
            alias: "STRING",
          },
          %{
            name: "STRING_BYTES_TRIPLE_DQ",
            pattern: "[bB]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
            is_regex: true,
            line_number: 118,
            alias: "STRING",
          },
          %{
            name: "STRING_BYTES_TRIPLE_SQ",
            pattern: "[bB]'''([^'\\\\]|\\\\.|\\n)*'''",
            is_regex: true,
            line_number: 119,
            alias: "STRING",
          },
          %{
            name: "STRING_TRIPLE_DQ",
            pattern: "\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
            is_regex: true,
            line_number: 120,
            alias: "STRING",
          },
          %{
            name: "STRING_TRIPLE_SQ",
            pattern: "'''([^'\\\\]|\\\\.|\\n)*'''",
            is_regex: true,
            line_number: 121,
            alias: "STRING",
          },
          %{
            name: "STRING_RAW_FSTRING_DQ",
            pattern: "[rR][fF]\"([^\"\\\\]|\\\\.)*\"|[fF][rR]\"([^\"\\\\]|\\\\.)*\"",
            is_regex: true,
            line_number: 124,
            alias: "STRING",
          },
          %{
            name: "STRING_RAW_FSTRING_SQ",
            pattern: "[rR][fF]'([^'\\\\]|\\\\.)*'|[fF][rR]'([^'\\\\]|\\\\.)*'",
            is_regex: true,
            line_number: 125,
            alias: "STRING",
          },
          %{
            name: "STRING_RAW_BYTES_DQ",
            pattern: "[bB][rR]\"([^\"\\\\]|\\\\.)*\"|[rR][bB]\"([^\"\\\\]|\\\\.)*\"",
            is_regex: true,
            line_number: 126,
            alias: "STRING",
          },
          %{
            name: "STRING_RAW_BYTES_SQ",
            pattern: "[bB][rR]'([^'\\\\]|\\\\.)*'|[rR][bB]'([^'\\\\]|\\\\.)*'",
            is_regex: true,
            line_number: 127,
            alias: "STRING",
          },
          %{
            name: "STRING_FSTRING_DQ",
            pattern: "[fF]\"([^\"\\\\]|\\\\.)*\"",
            is_regex: true,
            line_number: 129,
            alias: "STRING",
          },
          %{
            name: "STRING_FSTRING_SQ",
            pattern: "[fF]'([^'\\\\]|\\\\.)*'",
            is_regex: true,
            line_number: 130,
            alias: "STRING",
          },
          %{
            name: "STRING_UNICODE_DQ",
            pattern: "[uU]\"([^\"\\\\]|\\\\.)*\"",
            is_regex: true,
            line_number: 131,
            alias: "STRING",
          },
          %{
            name: "STRING_UNICODE_SQ",
            pattern: "[uU]'([^'\\\\]|\\\\.)*'",
            is_regex: true,
            line_number: 132,
            alias: "STRING",
          },
          %{
            name: "STRING_RAW_DQ",
            pattern: "[rR]\"([^\"\\\\]|\\\\.)*\"",
            is_regex: true,
            line_number: 133,
            alias: "STRING",
          },
          %{
            name: "STRING_RAW_SQ",
            pattern: "[rR]'([^'\\\\]|\\\\.)*'",
            is_regex: true,
            line_number: 134,
            alias: "STRING",
          },
          %{
            name: "STRING_BYTES_DQ",
            pattern: "[bB]\"([^\"\\\\]|\\\\.)*\"",
            is_regex: true,
            line_number: 135,
            alias: "STRING",
          },
          %{
            name: "STRING_BYTES_SQ",
            pattern: "[bB]'([^'\\\\]|\\\\.)*'",
            is_regex: true,
            line_number: 136,
            alias: "STRING",
          },
          %{
            name: "STRING_DQ",
            pattern: "\"([^\"\\\\]|\\\\.)*\"",
            is_regex: true,
            line_number: 137,
            alias: "STRING",
          },
          %{
            name: "STRING_SQ",
            pattern: "'([^'\\\\]|\\\\.)*'",
            is_regex: true,
            line_number: 138,
            alias: "STRING",
          },
          %{
            name: "IMAG_FLOAT_EXP",
            pattern: "[0-9](_?[0-9])*[eE][+-]?[0-9](_?[0-9])*[jJ]",
            is_regex: true,
            line_number: 149,
            alias: "IMAG",
          },
          %{
            name: "IMAG_FLOAT_DOT",
            pattern: "\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?[jJ]",
            is_regex: true,
            line_number: 150,
            alias: "IMAG",
          },
          %{
            name: "IMAG_FLOAT",
            pattern: "[0-9](_?[0-9])*\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?[jJ]",
            is_regex: true,
            line_number: 151,
            alias: "IMAG",
          },
          %{
            name: "IMAG_INT",
            pattern: "[0-9](_?[0-9])*[jJ]",
            is_regex: true,
            line_number: 152,
            alias: "IMAG",
          },
          %{
            name: "FLOAT_EXP",
            pattern: "[0-9](_?[0-9])*[eE][+-]?[0-9](_?[0-9])*",
            is_regex: true,
            line_number: 154,
            alias: "FLOAT",
          },
          %{
            name: "FLOAT_DOT",
            pattern: "\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?",
            is_regex: true,
            line_number: 155,
            alias: "FLOAT",
          },
          %{
            name: "FLOAT",
            pattern: "[0-9](_?[0-9])*\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?",
            is_regex: true,
            line_number: 156,
            alias: "FLOAT",
          },
          %{
            name: "INT_HEX",
            pattern: "0[xX](_?[0-9a-fA-F])+",
            is_regex: true,
            line_number: 158,
            alias: "INT",
          },
          %{
            name: "INT_BIN",
            pattern: "0[bB](_?[01])+",
            is_regex: true,
            line_number: 159,
            alias: "INT",
          },
          %{
            name: "INT_OCT",
            pattern: "0[oO](_?[0-7])+",
            is_regex: true,
            line_number: 160,
            alias: "INT",
          },
          %{
            name: "INT",
            pattern: "[0-9](_?[0-9])*",
            is_regex: true,
            line_number: 161,
            alias: nil,
          },
          %{
            name: "NAME",
            pattern: "[a-zA-Z_][a-zA-Z0-9_]*",
            is_regex: true,
            line_number: 170,
            alias: nil,
          },
          %{
            name: "DOUBLE_STAR_EQUALS",
            pattern: "**=",
            is_regex: false,
            line_number: 176,
            alias: nil,
          },
          %{
            name: "LEFT_SHIFT_EQUALS",
            pattern: "<<=",
            is_regex: false,
            line_number: 177,
            alias: nil,
          },
          %{
            name: "RIGHT_SHIFT_EQUALS",
            pattern: ">>=",
            is_regex: false,
            line_number: 178,
            alias: nil,
          },
          %{
            name: "FLOOR_DIV_EQUALS",
            pattern: "//=",
            is_regex: false,
            line_number: 179,
            alias: nil,
          },
          %{
            name: "DOUBLE_STAR",
            pattern: "**",
            is_regex: false,
            line_number: 188,
            alias: nil,
          },
          %{
            name: "FLOOR_DIV",
            pattern: "//",
            is_regex: false,
            line_number: 189,
            alias: nil,
          },
          %{
            name: "LEFT_SHIFT",
            pattern: "<<",
            is_regex: false,
            line_number: 190,
            alias: nil,
          },
          %{
            name: "RIGHT_SHIFT",
            pattern: ">>",
            is_regex: false,
            line_number: 191,
            alias: nil,
          },
          %{
            name: "EQUALS_EQUALS",
            pattern: "==",
            is_regex: false,
            line_number: 192,
            alias: nil,
          },
          %{
            name: "NOT_EQUALS",
            pattern: "!=",
            is_regex: false,
            line_number: 193,
            alias: nil,
          },
          %{
            name: "LESS_EQUALS",
            pattern: "<=",
            is_regex: false,
            line_number: 194,
            alias: nil,
          },
          %{
            name: "GREATER_EQUALS",
            pattern: ">=",
            is_regex: false,
            line_number: 195,
            alias: nil,
          },
          %{
            name: "WALRUS",
            pattern: ":=",
            is_regex: false,
            line_number: 196,
            alias: nil,
          },
          %{
            name: "ARROW",
            pattern: "->",
            is_regex: false,
            line_number: 197,
            alias: nil,
          },
          %{
            name: "PLUS_EQUALS",
            pattern: "+=",
            is_regex: false,
            line_number: 198,
            alias: nil,
          },
          %{
            name: "MINUS_EQUALS",
            pattern: "-=",
            is_regex: false,
            line_number: 199,
            alias: nil,
          },
          %{
            name: "STAR_EQUALS",
            pattern: "*=",
            is_regex: false,
            line_number: 200,
            alias: nil,
          },
          %{
            name: "SLASH_EQUALS",
            pattern: "/=",
            is_regex: false,
            line_number: 201,
            alias: nil,
          },
          %{
            name: "PERCENT_EQUALS",
            pattern: "%=",
            is_regex: false,
            line_number: 202,
            alias: nil,
          },
          %{
            name: "AMP_EQUALS",
            pattern: "&=",
            is_regex: false,
            line_number: 203,
            alias: nil,
          },
          %{
            name: "PIPE_EQUALS",
            pattern: "|=",
            is_regex: false,
            line_number: 204,
            alias: nil,
          },
          %{
            name: "CARET_EQUALS",
            pattern: "^=",
            is_regex: false,
            line_number: 205,
            alias: nil,
          },
          %{
            name: "AT_EQUALS",
            pattern: "@=",
            is_regex: false,
            line_number: 206,
            alias: nil,
          },
          %{
            name: "PLUS",
            pattern: "+",
            is_regex: false,
            line_number: 215,
            alias: nil,
          },
          %{
            name: "MINUS",
            pattern: "-",
            is_regex: false,
            line_number: 216,
            alias: nil,
          },
          %{
            name: "STAR",
            pattern: "*",
            is_regex: false,
            line_number: 217,
            alias: nil,
          },
          %{
            name: "SLASH",
            pattern: "/",
            is_regex: false,
            line_number: 218,
            alias: nil,
          },
          %{
            name: "PERCENT",
            pattern: "%",
            is_regex: false,
            line_number: 219,
            alias: nil,
          },
          %{
            name: "EQUALS",
            pattern: "=",
            is_regex: false,
            line_number: 220,
            alias: nil,
          },
          %{
            name: "LESS_THAN",
            pattern: "<",
            is_regex: false,
            line_number: 221,
            alias: nil,
          },
          %{
            name: "GREATER_THAN",
            pattern: ">",
            is_regex: false,
            line_number: 222,
            alias: nil,
          },
          %{
            name: "AMP",
            pattern: "&",
            is_regex: false,
            line_number: 223,
            alias: nil,
          },
          %{
            name: "PIPE",
            pattern: "|",
            is_regex: false,
            line_number: 224,
            alias: nil,
          },
          %{
            name: "CARET",
            pattern: "^",
            is_regex: false,
            line_number: 225,
            alias: nil,
          },
          %{
            name: "TILDE",
            pattern: "~",
            is_regex: false,
            line_number: 226,
            alias: nil,
          },
          %{
            name: "AT",
            pattern: "@",
            is_regex: false,
            line_number: 227,
            alias: nil,
          },
          %{
            name: "ELLIPSIS",
            pattern: "...",
            is_regex: false,
            line_number: 237,
            alias: nil,
          },
          %{
            name: "LPAREN",
            pattern: "(",
            is_regex: false,
            line_number: 238,
            alias: nil,
          },
          %{
            name: "RPAREN",
            pattern: ")",
            is_regex: false,
            line_number: 239,
            alias: nil,
          },
          %{
            name: "LBRACKET",
            pattern: "[",
            is_regex: false,
            line_number: 240,
            alias: nil,
          },
          %{
            name: "RBRACKET",
            pattern: "]",
            is_regex: false,
            line_number: 241,
            alias: nil,
          },
          %{
            name: "LBRACE",
            pattern: "{",
            is_regex: false,
            line_number: 242,
            alias: nil,
          },
          %{
            name: "RBRACE",
            pattern: "}",
            is_regex: false,
            line_number: 243,
            alias: nil,
          },
          %{
            name: "COMMA",
            pattern: ",",
            is_regex: false,
            line_number: 244,
            alias: nil,
          },
          %{
            name: "COLON",
            pattern: ":",
            is_regex: false,
            line_number: 245,
            alias: nil,
          },
          %{
            name: "SEMICOLON",
            pattern: ";",
            is_regex: false,
            line_number: 246,
            alias: nil,
          },
          %{
            name: "DOT",
            pattern: ".",
            is_regex: false,
            line_number: 247,
            alias: nil,
          },
        ],
      keywords: ["False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue", "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import", "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while", "with", "yield"],
      mode: "indentation",
      escape_mode: nil,
      skip_definitions: [
          %{
            name: "COMMENT",
            pattern: "#[^\\n]*",
            is_regex: true,
            line_number: 41,
            alias: nil,
          },
          %{
            name: "WHITESPACE",
            pattern: "[ \\t]+",
            is_regex: true,
            line_number: 42,
            alias: nil,
          },
          %{
            name: "LINE_CONTINUATION",
            pattern: "\\\\[ \\t]*\\n",
            is_regex: true,
            line_number: 45,
            alias: nil,
          },
        ],
      reserved_keywords: [],
      error_definitions: [],
      groups: %{},
      layout_keywords: [],
      case_sensitive: true,
      version: 1,
      case_insensitive: false,
      start_mode: nil,
      transitions: [],
    }
  end
  end
