defmodule CodingAdventures.PythonLexer.Grammar.V3_6 do
  # AUTO-GENERATED FILE — DO NOT EDIT
  # Source: python3.6.tokens
  # Regenerate with: grammar-tools compile-tokens python3.6.tokens
  #
  # This file embeds a TokenGrammar as native Elixir data structures.
  # Call token_grammar/0 instead of reading and parsing the .tokens file.
  
  alias CodingAdventures.GrammarTools.TokenGrammar
  
  def token_grammar do
    %TokenGrammar{
      definitions: [
          %{
            name: "STRING_RAW_FSTR_TRIPLE_DQ",
            pattern: "[rR][fF]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"|[fF][rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
            is_regex: true,
            line_number: 198,
            alias: "STRING",
          },
          %{
            name: "STRING_RAW_FSTR_TRIPLE_SQ",
            pattern: "[rR][fF]'''([^'\\\\]|\\\\.|\\n)*'''|[fF][rR]'''([^'\\\\]|\\\\.|\\n)*'''",
            is_regex: true,
            line_number: 199,
            alias: "STRING",
          },
          %{
            name: "STRING_RAW_TRIPLE_DQ",
            pattern: "[rR][bB]?\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"|[bB][rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
            is_regex: true,
            line_number: 200,
            alias: "STRING",
          },
          %{
            name: "STRING_RAW_TRIPLE_SQ",
            pattern: "[rR][bB]?'''([^'\\\\]|\\\\.|\\n)*'''|[bB][rR]'''([^'\\\\]|\\\\.|\\n)*'''",
            is_regex: true,
            line_number: 201,
            alias: "STRING",
          },
          %{
            name: "STRING_FSTR_TRIPLE_DQ",
            pattern: "[fF]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
            is_regex: true,
            line_number: 203,
            alias: "STRING",
          },
          %{
            name: "STRING_FSTR_TRIPLE_SQ",
            pattern: "[fF]'''([^'\\\\]|\\\\.|\\n)*'''",
            is_regex: true,
            line_number: 204,
            alias: "STRING",
          },
          %{
            name: "STRING_TRIPLE_DQ",
            pattern: "[bB]?\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
            is_regex: true,
            line_number: 205,
            alias: "STRING",
          },
          %{
            name: "STRING_TRIPLE_SQ",
            pattern: "[bB]?'''([^'\\\\]|\\\\.|\\n)*'''",
            is_regex: true,
            line_number: 206,
            alias: "STRING",
          },
          %{
            name: "STRING_RAW_FSTR_DQ",
            pattern: "[rR][fF]\"([^\"\\\\]|\\\\.)*\"|[fF][rR]\"([^\"\\\\]|\\\\.)*\"",
            is_regex: true,
            line_number: 210,
            alias: "STRING",
          },
          %{
            name: "STRING_RAW_FSTR_SQ",
            pattern: "[rR][fF]'([^'\\\\]|\\\\.)*'|[fF][rR]'([^'\\\\]|\\\\.)*'",
            is_regex: true,
            line_number: 211,
            alias: "STRING",
          },
          %{
            name: "STRING_RAW_DQ",
            pattern: "[rR][bB]?\"([^\"\\\\]|\\\\.)*\"|[bB][rR]\"([^\"\\\\]|\\\\.)*\"",
            is_regex: true,
            line_number: 212,
            alias: "STRING",
          },
          %{
            name: "STRING_RAW_SQ",
            pattern: "[rR][bB]?'([^'\\\\]|\\\\.)*'|[bB][rR]'([^'\\\\]|\\\\.)*'",
            is_regex: true,
            line_number: 213,
            alias: "STRING",
          },
          %{
            name: "STRING_FSTR_DQ",
            pattern: "[fF]\"([^\"\\\\]|\\\\.)*\"",
            is_regex: true,
            line_number: 215,
            alias: "STRING",
          },
          %{
            name: "STRING_FSTR_SQ",
            pattern: "[fF]'([^'\\\\]|\\\\.)*'",
            is_regex: true,
            line_number: 216,
            alias: "STRING",
          },
          %{
            name: "STRING_DQ",
            pattern: "[bB]?\"([^\"\\\\]|\\\\.)*\"",
            is_regex: true,
            line_number: 217,
            alias: "STRING",
          },
          %{
            name: "STRING_SQ",
            pattern: "[bB]?'([^'\\\\]|\\\\.)*'",
            is_regex: true,
            line_number: 218,
            alias: "STRING",
          },
          %{
            name: "FLOAT_EXP",
            pattern: "[0-9](_?[0-9])*[eE][+-]?[0-9](_?[0-9])*",
            is_regex: true,
            line_number: 251,
            alias: "FLOAT",
          },
          %{
            name: "FLOAT_DOT",
            pattern: "\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?\\b",
            is_regex: true,
            line_number: 252,
            alias: "FLOAT",
          },
          %{
            name: "FLOAT",
            pattern: "[0-9](_?[0-9])*\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?",
            is_regex: true,
            line_number: 253,
            alias: "FLOAT",
          },
          %{
            name: "FLOAT_TRAIL",
            pattern: "[0-9](_?[0-9])*\\.([eE][+-]?[0-9](_?[0-9])*)?\\b",
            is_regex: true,
            line_number: 254,
            alias: "FLOAT",
          },
          %{
            name: "IMAG_FLOAT",
            pattern: "[0-9](_?[0-9])*\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?[jJ]",
            is_regex: true,
            line_number: 259,
            alias: "IMAGINARY",
          },
          %{
            name: "IMAG_DOT",
            pattern: "\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?[jJ]",
            is_regex: true,
            line_number: 260,
            alias: "IMAGINARY",
          },
          %{
            name: "IMAG_EXP",
            pattern: "[0-9](_?[0-9])*[eE][+-]?[0-9](_?[0-9])*[jJ]",
            is_regex: true,
            line_number: 261,
            alias: "IMAGINARY",
          },
          %{
            name: "IMAG_INT",
            pattern: "[0-9](_?[0-9])*[jJ]",
            is_regex: true,
            line_number: 262,
            alias: "IMAGINARY",
          },
          %{
            name: "INT_HEX",
            pattern: "0[xX](_?[0-9a-fA-F])+",
            is_regex: true,
            line_number: 272,
            alias: "INT",
          },
          %{
            name: "INT_OCT",
            pattern: "0[oO](_?[0-7])+",
            is_regex: true,
            line_number: 273,
            alias: "INT",
          },
          %{
            name: "INT_BIN",
            pattern: "0[bB](_?[01])+",
            is_regex: true,
            line_number: 274,
            alias: "INT",
          },
          %{
            name: "INT",
            pattern: "[0-9](_?[0-9])*",
            is_regex: true,
            line_number: 275,
            alias: nil,
          },
          %{
            name: "NAME",
            pattern: "[a-zA-Z_][a-zA-Z0-9_]*",
            is_regex: true,
            line_number: 285,
            alias: nil,
          },
          %{
            name: "AT",
            pattern: "@",
            is_regex: false,
            line_number: 297,
            alias: nil,
          },
          %{
            name: "DOUBLE_STAR_EQUALS",
            pattern: "**=",
            is_regex: false,
            line_number: 306,
            alias: nil,
          },
          %{
            name: "LEFT_SHIFT_EQUALS",
            pattern: "<<=",
            is_regex: false,
            line_number: 307,
            alias: nil,
          },
          %{
            name: "RIGHT_SHIFT_EQUALS",
            pattern: ">>=",
            is_regex: false,
            line_number: 308,
            alias: nil,
          },
          %{
            name: "FLOOR_DIV_EQUALS",
            pattern: "//=",
            is_regex: false,
            line_number: 309,
            alias: nil,
          },
          %{
            name: "AT_EQUALS",
            pattern: "@=",
            is_regex: false,
            line_number: 310,
            alias: nil,
          },
          %{
            name: "DOUBLE_STAR",
            pattern: "**",
            is_regex: false,
            line_number: 318,
            alias: nil,
          },
          %{
            name: "FLOOR_DIV",
            pattern: "//",
            is_regex: false,
            line_number: 319,
            alias: nil,
          },
          %{
            name: "LEFT_SHIFT",
            pattern: "<<",
            is_regex: false,
            line_number: 320,
            alias: nil,
          },
          %{
            name: "RIGHT_SHIFT",
            pattern: ">>",
            is_regex: false,
            line_number: 321,
            alias: nil,
          },
          %{
            name: "EQUALS_EQUALS",
            pattern: "==",
            is_regex: false,
            line_number: 322,
            alias: nil,
          },
          %{
            name: "NOT_EQUALS",
            pattern: "!=",
            is_regex: false,
            line_number: 323,
            alias: nil,
          },
          %{
            name: "LESS_EQUALS",
            pattern: "<=",
            is_regex: false,
            line_number: 324,
            alias: nil,
          },
          %{
            name: "GREATER_EQUALS",
            pattern: ">=",
            is_regex: false,
            line_number: 325,
            alias: nil,
          },
          %{
            name: "PLUS_EQUALS",
            pattern: "+=",
            is_regex: false,
            line_number: 326,
            alias: nil,
          },
          %{
            name: "MINUS_EQUALS",
            pattern: "-=",
            is_regex: false,
            line_number: 327,
            alias: nil,
          },
          %{
            name: "STAR_EQUALS",
            pattern: "*=",
            is_regex: false,
            line_number: 328,
            alias: nil,
          },
          %{
            name: "SLASH_EQUALS",
            pattern: "/=",
            is_regex: false,
            line_number: 329,
            alias: nil,
          },
          %{
            name: "PERCENT_EQUALS",
            pattern: "%=",
            is_regex: false,
            line_number: 330,
            alias: nil,
          },
          %{
            name: "AMP_EQUALS",
            pattern: "&=",
            is_regex: false,
            line_number: 331,
            alias: nil,
          },
          %{
            name: "PIPE_EQUALS",
            pattern: "|=",
            is_regex: false,
            line_number: 332,
            alias: nil,
          },
          %{
            name: "CARET_EQUALS",
            pattern: "^=",
            is_regex: false,
            line_number: 333,
            alias: nil,
          },
          %{
            name: "ARROW",
            pattern: "->",
            is_regex: false,
            line_number: 334,
            alias: nil,
          },
          %{
            name: "PLUS",
            pattern: "+",
            is_regex: false,
            line_number: 340,
            alias: nil,
          },
          %{
            name: "MINUS",
            pattern: "-",
            is_regex: false,
            line_number: 341,
            alias: nil,
          },
          %{
            name: "STAR",
            pattern: "*",
            is_regex: false,
            line_number: 342,
            alias: nil,
          },
          %{
            name: "SLASH",
            pattern: "/",
            is_regex: false,
            line_number: 343,
            alias: nil,
          },
          %{
            name: "PERCENT",
            pattern: "%",
            is_regex: false,
            line_number: 344,
            alias: nil,
          },
          %{
            name: "EQUALS",
            pattern: "=",
            is_regex: false,
            line_number: 345,
            alias: nil,
          },
          %{
            name: "LESS_THAN",
            pattern: "<",
            is_regex: false,
            line_number: 346,
            alias: nil,
          },
          %{
            name: "GREATER_THAN",
            pattern: ">",
            is_regex: false,
            line_number: 347,
            alias: nil,
          },
          %{
            name: "AMP",
            pattern: "&",
            is_regex: false,
            line_number: 348,
            alias: nil,
          },
          %{
            name: "PIPE",
            pattern: "|",
            is_regex: false,
            line_number: 349,
            alias: nil,
          },
          %{
            name: "CARET",
            pattern: "^",
            is_regex: false,
            line_number: 350,
            alias: nil,
          },
          %{
            name: "TILDE",
            pattern: "~",
            is_regex: false,
            line_number: 351,
            alias: nil,
          },
          %{
            name: "LPAREN",
            pattern: "(",
            is_regex: false,
            line_number: 357,
            alias: nil,
          },
          %{
            name: "RPAREN",
            pattern: ")",
            is_regex: false,
            line_number: 358,
            alias: nil,
          },
          %{
            name: "LBRACKET",
            pattern: "[",
            is_regex: false,
            line_number: 359,
            alias: nil,
          },
          %{
            name: "RBRACKET",
            pattern: "]",
            is_regex: false,
            line_number: 360,
            alias: nil,
          },
          %{
            name: "LBRACE",
            pattern: "{",
            is_regex: false,
            line_number: 361,
            alias: nil,
          },
          %{
            name: "RBRACE",
            pattern: "}",
            is_regex: false,
            line_number: 362,
            alias: nil,
          },
          %{
            name: "COMMA",
            pattern: ",",
            is_regex: false,
            line_number: 363,
            alias: nil,
          },
          %{
            name: "COLON",
            pattern: ":",
            is_regex: false,
            line_number: 364,
            alias: nil,
          },
          %{
            name: "SEMICOLON",
            pattern: ";",
            is_regex: false,
            line_number: 365,
            alias: nil,
          },
          %{
            name: "DOT",
            pattern: ".",
            is_regex: false,
            line_number: 366,
            alias: nil,
          },
          %{
            name: "ELLIPSIS",
            pattern: "...",
            is_regex: false,
            line_number: 367,
            alias: nil,
          },
        ],
      keywords: ["False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue", "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import", "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while", "with", "yield"],
      mode: "indentation",
      escape_mode: nil,
      skip_definitions: [
          %{
            name: "COMMENT",
            pattern: "#[^\\n]*",
            is_regex: true,
            line_number: 55,
            alias: nil,
          },
          %{
            name: "WHITESPACE",
            pattern: "[ \\t]+",
            is_regex: true,
            line_number: 56,
            alias: nil,
          },
        ],
      reserved_keywords: [],
      error_definitions: [],
      groups: %{},
      layout_keywords: [],
      case_sensitive: true,
      version: 1,
      case_insensitive: false,
      start_mode: nil,
      transitions: [],
    }
  end
  end
