"""Loader helpers for parsed Prolog sources and explicit initialization runs."""

from prolog_loader.adapters import adapt_prolog_goal
from prolog_loader.loader import (
    GoalAdapter,
    LoadedPrologProject,
    LoadedPrologSource,
    PrologDialect,
    PrologExpansionError,
    PrologInitializationError,
    PrologSourceDependency,
    SourceResolver,
    __version__,
    apply_expansion_directives,
    link_loaded_prolog_sources,
    load_iso_prolog_source,
    load_parsed_prolog_source,
    load_prolog_file,
    load_prolog_project,
    load_prolog_project_from_files,
    load_prolog_source,
    load_swi_prolog_file,
    load_swi_prolog_project,
    load_swi_prolog_project_from_files,
    load_swi_prolog_source,
    rewrite_loaded_prolog_query,
    run_initialization_goals,
    run_prolog_initialization_goals,
)

__all__ = [
    "__version__",
    "adapt_prolog_goal",
    "GoalAdapter",
    "LoadedPrologProject",
    "LoadedPrologSource",
    "PrologDialect",
    "PrologExpansionError",
    "PrologSourceDependency",
    "PrologInitializationError",
    "SourceResolver",
    "apply_expansion_directives",
    "load_iso_prolog_source",
    "load_parsed_prolog_source",
    "load_prolog_file",
    "load_prolog_project",
    "load_prolog_project_from_files",
    "load_prolog_source",
    "load_swi_prolog_file",
    "load_swi_prolog_project",
    "load_swi_prolog_project_from_files",
    "load_swi_prolog_source",
    "link_loaded_prolog_sources",
    "rewrite_loaded_prolog_query",
    "run_initialization_goals",
    "run_prolog_initialization_goals",
]
