# frozen_string_literal: true
# AUTO-GENERATED FILE — DO NOT EDIT
# Source: vhdl.tokens
# Regenerate with: grammar-tools compile-tokens vhdl.tokens
#
# This file embeds a TokenGrammar as native Ruby data structures.
# Downstream packages require this file directly instead of reading
# and parsing the .tokens file at runtime.

require "coding_adventures_grammar_tools"

GT = CodingAdventures::GrammarTools unless defined?(GT)

TOKEN_GRAMMAR = GT::TokenGrammar.new(
  version: 0,
  case_insensitive: false,
  case_sensitive: false,
  definitions: [
      GT::TokenDefinition.new(
        name: "STRING",
        pattern: "\"([^\"]|\"\")*\"",
        is_regex: true,
        line_number: 63,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BIT_STRING",
        pattern: "[bBoOxXdD]\"[0-9a-fA-F_]+\"",
        is_regex: true,
        line_number: 82,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CHAR_LITERAL",
        pattern: "'[^']'",
        is_regex: true,
        line_number: 100,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BASED_LITERAL",
        pattern: "[0-9]+#[0-9a-fA-F_]+(\\.[0-9a-fA-F_]+)?#([eE][+-]?[0-9_]+)?",
        is_regex: true,
        line_number: 116,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "REAL_NUMBER",
        pattern: "[0-9][0-9_]*\\.[0-9_]+([eE][+-]?[0-9_]+)?",
        is_regex: true,
        line_number: 120,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NUMBER",
        pattern: "[0-9][0-9_]*",
        is_regex: true,
        line_number: 124,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EXTENDED_IDENT",
        pattern: "\\\\[^\\\\]+\\\\",
        is_regex: true,
        line_number: 143,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NAME",
        pattern: "[a-zA-Z][a-zA-Z0-9_]*",
        is_regex: true,
        line_number: 144,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "VAR_ASSIGN",
        pattern: ":=",
        is_regex: false,
        line_number: 165,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_EQUALS",
        pattern: "<=",
        is_regex: false,
        line_number: 166,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_EQUALS",
        pattern: ">=",
        is_regex: false,
        line_number: 167,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "ARROW",
        pattern: "=>",
        is_regex: false,
        line_number: 168,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NOT_EQUALS",
        pattern: "/=",
        is_regex: false,
        line_number: 169,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "POWER",
        pattern: "**",
        is_regex: false,
        line_number: 170,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BOX",
        pattern: "<>",
        is_regex: false,
        line_number: 171,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS",
        pattern: "+",
        is_regex: false,
        line_number: 184,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS",
        pattern: "-",
        is_regex: false,
        line_number: 185,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR",
        pattern: "*",
        is_regex: false,
        line_number: 186,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SLASH",
        pattern: "/",
        is_regex: false,
        line_number: 187,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AMPERSAND",
        pattern: "&",
        is_regex: false,
        line_number: 188,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_THAN",
        pattern: "<",
        is_regex: false,
        line_number: 189,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_THAN",
        pattern: ">",
        is_regex: false,
        line_number: 190,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQUALS",
        pattern: "=",
        is_regex: false,
        line_number: 191,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "TICK",
        pattern: "'",
        is_regex: false,
        line_number: 192,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PIPE",
        pattern: "|",
        is_regex: false,
        line_number: 193,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LPAREN",
        pattern: "(",
        is_regex: false,
        line_number: 199,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RPAREN",
        pattern: ")",
        is_regex: false,
        line_number: 200,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACKET",
        pattern: "[",
        is_regex: false,
        line_number: 201,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACKET",
        pattern: "]",
        is_regex: false,
        line_number: 202,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SEMICOLON",
        pattern: ";",
        is_regex: false,
        line_number: 203,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COMMA",
        pattern: ",",
        is_regex: false,
        line_number: 204,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DOT",
        pattern: ".",
        is_regex: false,
        line_number: 205,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COLON",
        pattern: ":",
        is_regex: false,
        line_number: 206,
        alias_name: nil,
      ),
    ],
  keywords: ["abs", "access", "after", "alias", "all", "and", "architecture", "array", "assert", "attribute", "begin", "block", "body", "buffer", "bus", "case", "component", "configuration", "constant", "disconnect", "downto", "else", "elsif", "end", "entity", "exit", "file", "for", "function", "generate", "generic", "group", "guarded", "if", "impure", "in", "inout", "is", "label", "library", "linkage", "literal", "loop", "map", "mod", "nand", "new", "next", "nor", "not", "null", "of", "on", "open", "or", "others", "out", "package", "port", "postponed", "procedure", "process", "pure", "range", "record", "register", "reject", "rem", "report", "return", "rol", "ror", "select", "severity", "signal", "shared", "sla", "sll", "sra", "srl", "subtype", "then", "to", "transport", "type", "unaffected", "units", "until", "use", "variable", "wait", "when", "while", "with", "xnor", "xor"],
  mode: nil,
  escape_mode: "none",
  skip_definitions: [
      GT::TokenDefinition.new(
        name: "COMMENT",
        pattern: "--[^\\n]*",
        is_regex: true,
        line_number: 50,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "WHITESPACE",
        pattern: "[ \\t\\r\\n]+",
        is_regex: true,
        line_number: 51,
        alias_name: nil,
      ),
    ],
  reserved_keywords: [],
  error_definitions: [],
  groups: {},
)
