// Code generated by grammar-tools. DO NOT EDIT.
// Source: code/grammars/ecmascript/es1.tokens
//
// Embeds the grammar(s) as native Swift so the lexer/parser never reads
// code/grammars/** at run time. Regenerate from swift/grammar-tools with:
//   swift run grammar-tools-embed tokens <output> EmbeddedGrammar <label>=<file> ...

import GrammarTools

enum EmbeddedGrammar {
    /// Embedded grammars keyed by the version label the loader passes.
    static let tokenGrammars: [String: TokenGrammar] = [
        "es1": es1,
    ]

    static let es1: TokenGrammar = TokenGrammar(
    definitions: [
        TokenDefinition(name: "NAME", pattern: "[a-zA-Z_$][a-zA-Z0-9_$]*", isRegex: true, lineNumber: 43, alias: nil),
        TokenDefinition(name: "HEX_NUMBER", pattern: "0[xX][0-9a-fA-F]+", isRegex: true, lineNumber: 50, alias: "NUMBER"),
        TokenDefinition(name: "FLOAT_NUMBER", pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?", isRegex: true, lineNumber: 51, alias: "NUMBER"),
        TokenDefinition(name: "LEADING_DOT_FLOAT", pattern: "\\.[0-9]+([eE][+-]?[0-9]+)?", isRegex: true, lineNumber: 52, alias: "NUMBER"),
        TokenDefinition(name: "SCI_NUMBER", pattern: "[0-9]+[eE][+-]?[0-9]+", isRegex: true, lineNumber: 53, alias: "NUMBER"),
        TokenDefinition(name: "INT_NUMBER", pattern: "[0-9]+", isRegex: true, lineNumber: 54, alias: "NUMBER"),
        TokenDefinition(name: "STRING_DQ", pattern: "\"([^\"\\\\]|\\\\.)*\"", isRegex: true, lineNumber: 59, alias: "STRING"),
        TokenDefinition(name: "STRING_SQ", pattern: "'([^'\\\\]|\\\\.)*'", isRegex: true, lineNumber: 60, alias: "STRING"),
        TokenDefinition(name: "UNSIGNED_RIGHT_SHIFT_EQUALS", pattern: ">>>=", isRegex: false, lineNumber: 70, alias: nil),
        TokenDefinition(name: "UNSIGNED_RIGHT_SHIFT", pattern: ">>>", isRegex: false, lineNumber: 71, alias: nil),
        TokenDefinition(name: "LEFT_SHIFT_EQUALS", pattern: "<<=", isRegex: false, lineNumber: 72, alias: nil),
        TokenDefinition(name: "RIGHT_SHIFT_EQUALS", pattern: ">>=", isRegex: false, lineNumber: 73, alias: nil),
        TokenDefinition(name: "EQUALS_EQUALS", pattern: "==", isRegex: false, lineNumber: 74, alias: nil),
        TokenDefinition(name: "NOT_EQUALS", pattern: "!=", isRegex: false, lineNumber: 75, alias: nil),
        TokenDefinition(name: "LESS_EQUALS", pattern: "<=", isRegex: false, lineNumber: 76, alias: nil),
        TokenDefinition(name: "GREATER_EQUALS", pattern: ">=", isRegex: false, lineNumber: 77, alias: nil),
        TokenDefinition(name: "PLUS_EQUALS", pattern: "+=", isRegex: false, lineNumber: 78, alias: nil),
        TokenDefinition(name: "MINUS_EQUALS", pattern: "-=", isRegex: false, lineNumber: 79, alias: nil),
        TokenDefinition(name: "STAR_EQUALS", pattern: "*=", isRegex: false, lineNumber: 80, alias: nil),
        TokenDefinition(name: "SLASH_EQUALS", pattern: "/=", isRegex: false, lineNumber: 81, alias: nil),
        TokenDefinition(name: "PERCENT_EQUALS", pattern: "%=", isRegex: false, lineNumber: 82, alias: nil),
        TokenDefinition(name: "AMPERSAND_EQUALS", pattern: "&=", isRegex: false, lineNumber: 83, alias: nil),
        TokenDefinition(name: "PIPE_EQUALS", pattern: "|=", isRegex: false, lineNumber: 84, alias: nil),
        TokenDefinition(name: "CARET_EQUALS", pattern: "^=", isRegex: false, lineNumber: 85, alias: nil),
        TokenDefinition(name: "LEFT_SHIFT", pattern: "<<", isRegex: false, lineNumber: 86, alias: nil),
        TokenDefinition(name: "RIGHT_SHIFT", pattern: ">>", isRegex: false, lineNumber: 87, alias: nil),
        TokenDefinition(name: "AND_AND", pattern: "&&", isRegex: false, lineNumber: 88, alias: nil),
        TokenDefinition(name: "OR_OR", pattern: "||", isRegex: false, lineNumber: 89, alias: nil),
        TokenDefinition(name: "PLUS_PLUS", pattern: "++", isRegex: false, lineNumber: 90, alias: nil),
        TokenDefinition(name: "MINUS_MINUS", pattern: "--", isRegex: false, lineNumber: 91, alias: nil),
        TokenDefinition(name: "EQUALS", pattern: "=", isRegex: false, lineNumber: 97, alias: nil),
        TokenDefinition(name: "PLUS", pattern: "+", isRegex: false, lineNumber: 98, alias: nil),
        TokenDefinition(name: "MINUS", pattern: "-", isRegex: false, lineNumber: 99, alias: nil),
        TokenDefinition(name: "STAR", pattern: "*", isRegex: false, lineNumber: 100, alias: nil),
        TokenDefinition(name: "SLASH", pattern: "/", isRegex: false, lineNumber: 101, alias: nil),
        TokenDefinition(name: "PERCENT", pattern: "%", isRegex: false, lineNumber: 102, alias: nil),
        TokenDefinition(name: "LESS_THAN", pattern: "<", isRegex: false, lineNumber: 103, alias: nil),
        TokenDefinition(name: "GREATER_THAN", pattern: ">", isRegex: false, lineNumber: 104, alias: nil),
        TokenDefinition(name: "BANG", pattern: "!", isRegex: false, lineNumber: 105, alias: nil),
        TokenDefinition(name: "AMPERSAND", pattern: "&", isRegex: false, lineNumber: 106, alias: nil),
        TokenDefinition(name: "PIPE", pattern: "|", isRegex: false, lineNumber: 107, alias: nil),
        TokenDefinition(name: "CARET", pattern: "^", isRegex: false, lineNumber: 108, alias: nil),
        TokenDefinition(name: "TILDE", pattern: "~", isRegex: false, lineNumber: 109, alias: nil),
        TokenDefinition(name: "QUESTION", pattern: "?", isRegex: false, lineNumber: 110, alias: nil),
        TokenDefinition(name: "LPAREN", pattern: "(", isRegex: false, lineNumber: 116, alias: nil),
        TokenDefinition(name: "RPAREN", pattern: ")", isRegex: false, lineNumber: 117, alias: nil),
        TokenDefinition(name: "LBRACE", pattern: "{", isRegex: false, lineNumber: 118, alias: nil),
        TokenDefinition(name: "RBRACE", pattern: "}", isRegex: false, lineNumber: 119, alias: nil),
        TokenDefinition(name: "LBRACKET", pattern: "[", isRegex: false, lineNumber: 120, alias: nil),
        TokenDefinition(name: "RBRACKET", pattern: "]", isRegex: false, lineNumber: 121, alias: nil),
        TokenDefinition(name: "SEMICOLON", pattern: ";", isRegex: false, lineNumber: 122, alias: nil),
        TokenDefinition(name: "COMMA", pattern: ",", isRegex: false, lineNumber: 123, alias: nil),
        TokenDefinition(name: "COLON", pattern: ":", isRegex: false, lineNumber: 124, alias: nil),
        TokenDefinition(name: "DOT", pattern: ".", isRegex: false, lineNumber: 125, alias: nil),
    ],
    keywords: ["break", "case", "continue", "default", "delete", "do", "else", "for", "function", "if", "in", "new", "return", "switch", "this", "typeof", "var", "void", "while", "with", "true", "false", "null"],
    mode: nil,
    escapeMode: nil,
    skipDefinitions: [
        TokenDefinition(name: "WHITESPACE", pattern: "[ \\t\\r\\n\\v\\f]+", isRegex: true, lineNumber: 182, alias: nil),
        TokenDefinition(name: "LINE_COMMENT", pattern: "\\/\\/[^\\n]*", isRegex: true, lineNumber: 183, alias: nil),
        TokenDefinition(name: "BLOCK_COMMENT", pattern: "\\/\\*([^*]|\\*[^\\/])*\\*\\/", isRegex: true, lineNumber: 184, alias: nil),
    ],
    reservedKeywords: ["class", "const", "enum", "export", "extends", "import", "super"],
    contextKeywords: nil,
    layoutKeywords: nil,
    groups: nil,
    caseSensitive: nil,
    version: 1,
    caseInsensitive: false)
}
