"""IBM 704 mainframe simulator — Layer 4h of the computing stack.

The first mass-produced computer with hardware floating-point (1954). Host of
FORTRAN I and LISP 1. The names ``CAR`` and ``CDR`` come from this machine's
instruction-field names.
"""

from __future__ import annotations

from ibm704_simulator.simulator import (
    OP_ADD,
    OP_ADM,
    OP_CAL,
    OP_CLA,
    OP_DVH,
    OP_DVP,
    OP_FAD,
    OP_FDP,
    OP_FMP,
    OP_FSB,
    OP_HPR,
    OP_HTR,
    OP_LDQ,
    OP_LXA,
    OP_LXD,
    OP_MPY,
    OP_NOP,
    OP_PAX,
    OP_PDX,
    OP_PXA,
    OP_STO,
    OP_STQ,
    OP_STZ,
    OP_SUB,
    OP_SXA,
    OP_SXD,
    OP_TMI,
    OP_TNO,
    OP_TNZ,
    OP_TOV,
    OP_TPL,
    OP_TQO,
    OP_TQP,
    OP_TRA,
    OP_TZE,
    OP_XCA,
    PREFIX_TIX,
    PREFIX_TXH,
    PREFIX_TXI,
    PREFIX_TXL,
    IBM704Simulator,
    encode_type_a,
    encode_type_b,
)
from ibm704_simulator.state import IBM704State
from ibm704_simulator.word import (
    fp_to_float,
    float_to_fp,
    make_word,
    pack_program,
    pack_word,
    unpack_program,
    unpack_word,
    word_magnitude,
    word_sign,
    word_to_signed_int,
)

__all__ = [
    # Simulator and state
    "IBM704Simulator",
    "IBM704State",
    # Encoders
    "encode_type_a",
    "encode_type_b",
    # Type A prefixes
    "PREFIX_TXI",
    "PREFIX_TIX",
    "PREFIX_TXH",
    "PREFIX_TXL",
    # Type B opcodes (alphabetical)
    "OP_ADD",
    "OP_ADM",
    "OP_CAL",
    "OP_CLA",
    "OP_DVH",
    "OP_DVP",
    "OP_FAD",
    "OP_FDP",
    "OP_FMP",
    "OP_FSB",
    "OP_HPR",
    "OP_HTR",
    "OP_LDQ",
    "OP_LXA",
    "OP_LXD",
    "OP_MPY",
    "OP_NOP",
    "OP_PAX",
    "OP_PDX",
    "OP_PXA",
    "OP_STO",
    "OP_STQ",
    "OP_STZ",
    "OP_SUB",
    "OP_SXA",
    "OP_SXD",
    "OP_TMI",
    "OP_TNO",
    "OP_TNZ",
    "OP_TOV",
    "OP_TPL",
    "OP_TQO",
    "OP_TQP",
    "OP_TRA",
    "OP_TZE",
    "OP_XCA",
    # Word helpers
    "fp_to_float",
    "float_to_fp",
    "make_word",
    "pack_program",
    "pack_word",
    "unpack_program",
    "unpack_word",
    "word_magnitude",
    "word_sign",
    "word_to_signed_int",
]
