-- Tests for coding_adventures.device_driver_framework
-- Coverage target: 95%+

local DDF = require("coding_adventures.device_driver_framework")

-- Helper: make a zero-filled block string
local function zero_block(size)
  local t = {}
  for i = 1, size do t[i] = "\0" end
  return table.concat(t)
end

local function fill_block(char, size)
  local t = {}
  for i = 1, size do t[i] = char end
  return table.concat(t)
end

-- ============================================================================
-- Constants
-- ============================================================================

describe("constants", function()
  it("device type values", function()
    assert.are.equal(DDF.TYPE_CHARACTER, 0)
    assert.are.equal(DDF.TYPE_BLOCK,     1)
    assert.are.equal(DDF.TYPE_NETWORK,   2)
  end)

  it("defaults", function()
    assert.are.equal(DDF.DEFAULT_BLOCK_SIZE,   512)
    assert.are.equal(DDF.DEFAULT_TOTAL_BLOCKS, 2048)
    assert.are.equal(DDF.DEFAULT_BUFFER_SIZE,  4096)
  end)
end)

-- ============================================================================
-- SimulatedDisk tests
-- ============================================================================

describe("SimulatedDisk", function()
  it("new creates disk with defaults", function()
    local d = DDF.SimulatedDisk.new()
    assert.are.equal(d.name, "disk0")
    assert.are.equal(d.device_type, DDF.TYPE_BLOCK)
    assert.are.equal(d.major, 3)
    assert.are.equal(d.minor, 0)
    assert.are.equal(d.block_size, 512)
    assert.are.equal(d.total_blocks, 2048)
    assert.is_false(d.initialized)
    assert.are.equal(d.open_count, 0)
  end)

  it("new with custom options", function()
    local d = DDF.SimulatedDisk.new({ name = "disk1", major = 8, minor = 16, block_size = 256, total_blocks = 4 })
    assert.are.equal(d.name, "disk1")
    assert.are.equal(d.major, 8)
    assert.are.equal(d.minor, 16)
    assert.are.equal(d.block_size, 256)
    assert.are.equal(d.total_blocks, 4)
  end)

  it("initialize sets initialized flag", function()
    local d = DDF.SimulatedDisk.new()
    local st, d2 = d:initialize()
    assert.are.equal(st, "ok")
    assert.is_true(d2.initialized)
    assert.is_false(d.initialized)  -- immutable
  end)

  it("open before initialize returns error", function()
    local d = DDF.SimulatedDisk.new()
    local st, _ = d:open()
    assert.are.equal(st, "not_initialized")
  end)

  it("open and close lifecycle", function()
    local d = DDF.SimulatedDisk.new()
    local _, d2 = d:initialize()
    local st1, d3 = d2:open()
    assert.are.equal(st1, "ok")
    assert.are.equal(d3.open_count, 1)
    local st2, d4 = d3:close()
    assert.are.equal(st2, "ok")
    assert.are.equal(d4.open_count, 0)
  end)

  it("close without open returns error", function()
    local d = DDF.SimulatedDisk.new()
    local _, d2 = d:initialize()
    local st, _ = d2:close()
    assert.are.equal(st, "not_open")
  end)

  it("write_block and read_block round-trip", function()
    local d = DDF.SimulatedDisk.new({ block_size = 8, total_blocks = 4 })
    local data = "ABCDEFGH"
    local st1, d2 = d:write_block(0, data)
    assert.are.equal(st1, "ok")
    local st2, _, result = d2:read_block(0)
    assert.are.equal(st2, "ok")
    assert.are.equal(result, "ABCDEFGH")
  end)

  it("write_block to non-zero block", function()
    local d = DDF.SimulatedDisk.new({ block_size = 4, total_blocks = 8 })
    local _, d2 = d:write_block(3, "TEST")
    local _, _, r0 = d2:read_block(0)
    local _, _, r3 = d2:read_block(3)
    assert.are.equal(r3, "TEST")
    assert.are.equal(r0, "\0\0\0\0")
  end)

  it("write_block rejects out-of-bounds block", function()
    local d = DDF.SimulatedDisk.new({ block_size = 4, total_blocks = 2 })
    local st, _ = d:write_block(2, "XXXX")
    assert.are.equal(st, "out_of_bounds")
    st, _ = d:write_block(-1, "XXXX")
    assert.are.equal(st, "out_of_bounds")
  end)

  it("write_block rejects wrong-size data", function()
    local d = DDF.SimulatedDisk.new({ block_size = 8, total_blocks = 4 })
    local st, _ = d:write_block(0, "short")
    assert.are.equal(st, "wrong_size")
  end)

  it("read_block rejects out-of-bounds", function()
    local d = DDF.SimulatedDisk.new({ block_size = 4, total_blocks = 2 })
    local st, _, _ = d:read_block(5)
    assert.are.equal(st, "out_of_bounds")
  end)

  it("immutability: write does not mutate original", function()
    local d = DDF.SimulatedDisk.new({ block_size = 4, total_blocks = 4 })
    local _, d2 = d:write_block(0, "ABCD")
    local _, _, r1 = d:read_block(0)
    local _, _, r2 = d2:read_block(0)
    assert.are.equal(r1, "\0\0\0\0")
    assert.are.equal(r2, "ABCD")
  end)

  it("ioctl get_block_size", function()
    local d = DDF.SimulatedDisk.new({ block_size = 256 })
    local st, val = d:ioctl("get_block_size")
    assert.are.equal(st, "ok")
    assert.are.equal(val, 256)
  end)

  it("ioctl get_total_blocks", function()
    local d = DDF.SimulatedDisk.new({ total_blocks = 100 })
    local st, val = d:ioctl("get_total_blocks")
    assert.are.equal(st, "ok")
    assert.are.equal(val, 100)
  end)

  it("ioctl unsupported command", function()
    local d = DDF.SimulatedDisk.new()
    local st, _ = d:ioctl("format", nil)
    assert.are.equal(st, "unsupported")
  end)
end)

-- ============================================================================
-- SimulatedSerial tests
-- ============================================================================

describe("SimulatedSerial", function()
  it("new creates serial with defaults", function()
    local s = DDF.SimulatedSerial.new()
    assert.are.equal(s.name, "serial0")
    assert.are.equal(s.device_type, DDF.TYPE_CHARACTER)
    assert.are.equal(s.major, 4)
    assert.are.equal(s.minor, 0)
    assert.are.equal(s.baud_rate, 9600)
    assert.is_false(s.initialized)
  end)

  it("initialize, open, close", function()
    local s = DDF.SimulatedSerial.new()
    local _, s2 = s:initialize()
    assert.is_true(s2.initialized)
    local st1, s3 = s2:open()
    assert.are.equal(st1, "ok")
    assert.are.equal(s3.open_count, 1)
    local st2, s4 = s3:close()
    assert.are.equal(st2, "ok")
    assert.are.equal(s4.open_count, 0)
  end)

  it("open before initialize returns error", function()
    local s = DDF.SimulatedSerial.new()
    local st, _ = s:open()
    assert.are.equal(st, "not_initialized")
  end)

  it("close when not open returns error", function()
    local s = DDF.SimulatedSerial.new()
    local _, s2 = s:initialize()
    local st, _ = s2:close()
    assert.are.equal(st, "not_open")
  end)

  it("write and tx_contents", function()
    local s = DDF.SimulatedSerial.new()
    local _, s2 = s:initialize()
    local st, s3, n = s2:write("hello")
    assert.are.equal(st, "ok")
    assert.are.equal(n, 5)
    assert.are.equal(s3:tx_contents(), "hello")
  end)

  it("inject_rx and read", function()
    local s = DDF.SimulatedSerial.new()
    local _, s2 = s:initialize()
    local s3 = s2:inject_rx("world")
    local st, s4, data = s3:read(10)
    assert.are.equal(st, "ok")
    assert.are.equal(data, "world")
    assert.are.equal(#s4.rx_buffer, 0)
  end)

  it("read from empty buffer returns empty", function()
    local s = DDF.SimulatedSerial.new()
    local st, _, data = s:read(4)
    assert.are.equal(st, "empty")
    assert.are.equal(data, "")
  end)

  it("read partial", function()
    local s = DDF.SimulatedSerial.new()
    local s2 = s:inject_rx("hello world")
    local st, s3, data = s2:read(5)
    assert.are.equal(st, "ok")
    assert.are.equal(data, "hello")
    assert.are.equal(#s3.rx_buffer, 6)  -- " world"
  end)

  it("ioctl get_baud_rate", function()
    local s = DDF.SimulatedSerial.new({ baud_rate = 115200 })
    local st, val = s:ioctl("get_baud_rate")
    assert.are.equal(st, "ok")
    assert.are.equal(val, 115200)
  end)

  it("ioctl set_baud_rate", function()
    local s = DDF.SimulatedSerial.new()
    local st, s2 = s:ioctl("set_baud_rate", 115200)
    assert.are.equal(st, "ok")
    assert.are.equal(s2.baud_rate, 115200)
    assert.are.equal(s.baud_rate, 9600)  -- immutable
  end)

  it("ioctl unsupported", function()
    local s = DDF.SimulatedSerial.new()
    local st, _ = s:ioctl("flush", nil)
    assert.are.equal(st, "unsupported")
  end)

  it("multiple writes accumulate in tx buffer", function()
    local s = DDF.SimulatedSerial.new()
    local _, s2, _ = s:write("hel")
    local _, s3, _ = s2:write("lo")
    assert.are.equal(s3:tx_contents(), "hello")
  end)
end)

-- ============================================================================
-- SimulatedNIC tests
-- ============================================================================

describe("SimulatedNIC", function()
  it("new creates NIC with defaults", function()
    local n = DDF.SimulatedNIC.new()
    assert.are.equal(n.name, "eth0")
    assert.are.equal(n.device_type, DDF.TYPE_NETWORK)
    assert.are.equal(n.major, 5)
    assert.are.equal(n.minor, 0)
    assert.are.equal(#n.mac_address, 6)
    assert.is_false(n.initialized)
  end)

  it("initialize, open, close", function()
    local n = DDF.SimulatedNIC.new()
    local _, n2 = n:initialize()
    local _, n3 = n2:open()
    assert.are.equal(n3.open_count, 1)
    local st, n4 = n3:close()
    assert.are.equal(st, "ok")
    assert.are.equal(n4.open_count, 0)
  end)

  it("open before initialize returns error", function()
    local n = DDF.SimulatedNIC.new()
    local st, _ = n:open()
    assert.are.equal(st, "not_initialized")
  end)

  it("send and tx_queue", function()
    local n = DDF.SimulatedNIC.new()
    local st, n2 = n:send({ 0xAA, 0xBB, 0xCC })
    assert.are.equal(st, "ok")
    assert.are.equal(#n2.tx_queue, 1)
    assert.are.same(n2.tx_queue[1], { 0xAA, 0xBB, 0xCC })
  end)

  it("inject_rx and receive", function()
    local n = DDF.SimulatedNIC.new()
    local n2 = n:inject_rx({ 0x01, 0x02, 0x03 })
    local st, n3, pkt = n2:receive()
    assert.are.equal(st, "ok")
    assert.are.same(pkt, { 0x01, 0x02, 0x03 })
    assert.are.equal(#n3.rx_queue, 0)
  end)

  it("receive from empty queue returns empty", function()
    local n = DDF.SimulatedNIC.new()
    local st, _, pkt = n:receive()
    assert.are.equal(st, "empty")
    assert.is_nil(pkt)
  end)

  it("multiple packets in rx_queue — FIFO order", function()
    local n = DDF.SimulatedNIC.new()
    local n2 = n:inject_rx({ 1 })
    local n3 = n2:inject_rx({ 2 })
    local n4 = n3:inject_rx({ 3 })
    local _, n5, p1 = n4:receive()
    local _, n6, p2 = n5:receive()
    local _, _, p3 = n6:receive()
    assert.are.same(p1, { 1 })
    assert.are.same(p2, { 2 })
    assert.are.same(p3, { 3 })
  end)

  it("ioctl get_mac", function()
    local mac = { 0x11, 0x22, 0x33, 0x44, 0x55, 0x66 }
    local n = DDF.SimulatedNIC.new({ mac_address = mac })
    local st, got = n:ioctl("get_mac")
    assert.are.equal(st, "ok")
    assert.are.same(got, mac)
  end)

  it("ioctl unsupported", function()
    local n = DDF.SimulatedNIC.new()
    local st, _ = n:ioctl("reset", nil)
    assert.are.equal(st, "unsupported")
  end)

  it("close when not open returns error", function()
    local n = DDF.SimulatedNIC.new()
    local _, n2 = n:initialize()
    local st, _ = n2:close()
    assert.are.equal(st, "not_open")
  end)
end)

-- ============================================================================
-- Registry tests
-- ============================================================================

describe("Registry", function()
  it("new creates empty registry", function()
    local r = DDF.Registry.new()
    assert.are.same(r:list(), {})
  end)

  it("register and get by name", function()
    local r = DDF.Registry.new()
    local disk = DDF.SimulatedDisk.new()
    local st, r2 = r:register(disk)
    assert.are.equal(st, "ok")
    local st2, d = r2:get("disk0")
    assert.are.equal(st2, "ok")
    assert.are.equal(d.name, "disk0")
  end)

  it("register returns already_registered for duplicate", function()
    local r = DDF.Registry.new()
    local disk = DDF.SimulatedDisk.new()
    local _, r2 = r:register(disk)
    local st, _ = r2:register(disk)
    assert.are.equal(st, "already_registered")
  end)

  it("get returns not_found for missing device", function()
    local r = DDF.Registry.new()
    local st, _ = r:get("nodev")
    assert.are.equal(st, "not_found")
  end)

  it("get_by_major_minor", function()
    local r = DDF.Registry.new()
    local disk = DDF.SimulatedDisk.new({ major = 8, minor = 0 })
    local _, r2 = r:register(disk)
    local st, d = r2:get_by_major_minor(8, 0)
    assert.are.equal(st, "ok")
    assert.are.equal(d.name, "disk0")
  end)

  it("get_by_major_minor returns not_found", function()
    local r = DDF.Registry.new()
    local st, _ = r:get_by_major_minor(99, 0)
    assert.are.equal(st, "not_found")
  end)

  it("update replaces device", function()
    local r = DDF.Registry.new()
    local disk = DDF.SimulatedDisk.new({ block_size = 4, total_blocks = 4 })
    local _, r2 = r:register(disk)
    local _, d2 = disk:write_block(0, "ABCD")
    local st, r3 = r2:update("disk0", d2)
    assert.are.equal(st, "ok")
    local _, d3 = r3:get("disk0")
    local _, _, data = d3:read_block(0)
    assert.are.equal(data, "ABCD")
  end)

  it("update returns not_found for missing device", function()
    local r = DDF.Registry.new()
    local disk = DDF.SimulatedDisk.new()
    local st, _ = r:update("disk0", disk)
    assert.are.equal(st, "not_found")
  end)

  it("unregister removes device", function()
    local r = DDF.Registry.new()
    local disk = DDF.SimulatedDisk.new()
    local _, r2 = r:register(disk)
    local st, r3 = r2:unregister("disk0")
    assert.are.equal(st, "ok")
    local rs, _ = r3:get("disk0")
    assert.are.equal(rs, "not_found")
    -- major:minor also removed
    local rs2, _ = r3:get_by_major_minor(3, 0)
    assert.are.equal(rs2, "not_found")
  end)

  it("unregister returns not_found for missing device", function()
    local r = DDF.Registry.new()
    local st, _ = r:unregister("nodev")
    assert.are.equal(st, "not_found")
  end)

  it("list returns sorted device names", function()
    local r = DDF.Registry.new()
    local disk   = DDF.SimulatedDisk.new({ name = "disk0", major = 3, minor = 0 })
    local serial = DDF.SimulatedSerial.new({ name = "serial0", major = 4, minor = 0 })
    local nic    = DDF.SimulatedNIC.new({ name = "eth0", major = 5, minor = 0 })
    local _, r2 = r:register(disk)
    local _, r3 = r2:register(serial)
    local _, r4 = r3:register(nic)
    local names = r4:list()
    assert.are.same(names, { "disk0", "eth0", "serial0" })
  end)

  it("immutability: register does not mutate original", function()
    local r = DDF.Registry.new()
    local disk = DDF.SimulatedDisk.new()
    r:register(disk)
    assert.are.same(r:list(), {})
  end)

  it("full driver lifecycle: init → open → write → read → close", function()
    local disk = DDF.SimulatedDisk.new({ block_size = 8, total_blocks = 4 })
    local _, d2 = disk:initialize()
    local _, d3 = d2:open()
    local _, d4 = d3:write_block(1, "HELLO!!!")
    local _, _, data = d4:read_block(1)
    assert.are.equal(data, "HELLO!!!")
    local st, _ = d4:close()
    assert.are.equal(st, "ok")
  end)
end)
