// Code generated by grammar-tools. DO NOT EDIT.
// Source: code/grammars/algol/algol60.tokens
//
// Embeds the grammar(s) as native Swift so the lexer/parser never reads
// code/grammars/** at run time. Regenerate from swift/grammar-tools with:
//   swift run grammar-tools-embed tokens <output> EmbeddedGrammar <label>=<file> ...

import GrammarTools

enum EmbeddedGrammar {
    /// Embedded grammars keyed by the version label the loader passes.
    static let tokenGrammars: [String: TokenGrammar] = [
        "algol60": algol60,
    ]

    static let algol60: TokenGrammar = TokenGrammar(
    definitions: [
        TokenDefinition(name: "REAL_LIT", pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?|[0-9]+[eE][+-]?[0-9]+", isRegex: true, lineNumber: 38, alias: nil),
        TokenDefinition(name: "INTEGER_LIT", pattern: "[0-9]+", isRegex: true, lineNumber: 41, alias: nil),
        TokenDefinition(name: "STRING_LIT", pattern: "'[^']*'|\"[^\"]*\"", isRegex: true, lineNumber: 46, alias: nil),
        TokenDefinition(name: "NAME", pattern: "[a-zA-Z][a-zA-Z0-9]*", isRegex: true, lineNumber: 53, alias: nil),
        TokenDefinition(name: "ASSIGN", pattern: ":=", isRegex: false, lineNumber: 61, alias: nil),
        TokenDefinition(name: "POWER", pattern: "**", isRegex: false, lineNumber: 66, alias: nil),
        TokenDefinition(name: "LEQ", pattern: "<=|≤", isRegex: true, lineNumber: 70, alias: nil),
        TokenDefinition(name: "GEQ", pattern: ">=|≥", isRegex: true, lineNumber: 71, alias: nil),
        TokenDefinition(name: "NEQ", pattern: "!=|<>|≠", isRegex: true, lineNumber: 72, alias: nil),
        TokenDefinition(name: "NOT_SYM", pattern: "¬", isRegex: false, lineNumber: 76, alias: nil),
        TokenDefinition(name: "AND_SYM", pattern: "∧", isRegex: false, lineNumber: 77, alias: nil),
        TokenDefinition(name: "OR_SYM", pattern: "∨", isRegex: false, lineNumber: 78, alias: nil),
        TokenDefinition(name: "IMPL_SYM", pattern: "⊃", isRegex: false, lineNumber: 79, alias: nil),
        TokenDefinition(name: "EQV_SYM", pattern: "≡", isRegex: false, lineNumber: 80, alias: nil),
        TokenDefinition(name: "PLUS", pattern: "+", isRegex: false, lineNumber: 86, alias: nil),
        TokenDefinition(name: "MINUS", pattern: "-", isRegex: false, lineNumber: 87, alias: nil),
        TokenDefinition(name: "STAR", pattern: "\\*|×", isRegex: true, lineNumber: 90, alias: nil),
        TokenDefinition(name: "SLASH", pattern: "\\/|÷", isRegex: true, lineNumber: 91, alias: nil),
        TokenDefinition(name: "CARET", pattern: "\\^|↑", isRegex: true, lineNumber: 95, alias: nil),
        TokenDefinition(name: "EQ", pattern: "=", isRegex: false, lineNumber: 98, alias: nil),
        TokenDefinition(name: "LT", pattern: "<", isRegex: false, lineNumber: 100, alias: nil),
        TokenDefinition(name: "GT", pattern: ">", isRegex: false, lineNumber: 101, alias: nil),
        TokenDefinition(name: "LPAREN", pattern: "(", isRegex: false, lineNumber: 107, alias: nil),
        TokenDefinition(name: "RPAREN", pattern: ")", isRegex: false, lineNumber: 108, alias: nil),
        TokenDefinition(name: "LBRACKET", pattern: "[", isRegex: false, lineNumber: 109, alias: nil),
        TokenDefinition(name: "RBRACKET", pattern: "]", isRegex: false, lineNumber: 110, alias: nil),
        TokenDefinition(name: "SEMICOLON", pattern: ";", isRegex: false, lineNumber: 111, alias: nil),
        TokenDefinition(name: "COMMA", pattern: ",", isRegex: false, lineNumber: 112, alias: nil),
        TokenDefinition(name: "COLON", pattern: ":", isRegex: false, lineNumber: 116, alias: nil),
    ],
    keywords: ["begin", "end", "if", "then", "else", "for", "do", "step", "until", "while", "goto", "switch", "procedure", "own", "array", "label", "value", "integer", "real", "boolean", "string", "true", "false", "not", "and", "or", "impl", "eqv", "div", "mod", "comment"],
    mode: nil,
    escapeMode: nil,
    skipDefinitions: [
        TokenDefinition(name: "WHITESPACE", pattern: "[ \\t\\r\\n]+", isRegex: true, lineNumber: 183, alias: nil),
        TokenDefinition(name: "COMMENT", pattern: "comment[^a-zA-Z0-9_][^;]*;", isRegex: true, lineNumber: 192, alias: nil),
    ],
    reservedKeywords: nil,
    contextKeywords: nil,
    layoutKeywords: nil,
    groups: nil,
    caseSensitive: nil,
    version: 1,
    caseInsensitive: false)
}
