defmodule UnixTools.Head do
  @moduledoc """
  head -- output the first part of files.

  ## What This Program Does

  This is a reimplementation of the GNU `head` utility in Elixir. It prints
  the first N lines (or bytes) of each file to standard output. By default,
  N is 10.

  ## How head Works

  head is the complement of tail. Together they let you peek at the
  beginning or end of a file without loading the whole thing:

      head file.txt          =>   first 10 lines
      head -n 5 file.txt     =>   first 5 lines
      head -c 100 file.txt   =>   first 100 bytes

  ## Headers

  When processing multiple files, head prints a header before each file:

      ==> file1.txt <==
      (first 10 lines of file1)

  The -q flag suppresses headers; -v forces them even for single files.

  ## Zero-Terminated Mode (-z)

  By default, head uses newline (\\n) as the line delimiter. With -z,
  it uses NUL (\\0) instead. This is useful for processing file lists
  generated by `find -print0`.
  """

  alias CodingAdventures.CliBuilder.Parser
  alias CodingAdventures.CliBuilder.{ParseResult, HelpResult, VersionResult, ParseErrors}

  # ---------------------------------------------------------------------------
  # Entry point
  # ---------------------------------------------------------------------------

  @doc """
  Entry point. Receives `argv` as a list of strings.

  1. Parse arguments with CLI Builder.
  2. Handle --help and --version.
  3. Determine line/byte mode and count.
  4. Process each file, printing headers when appropriate.
  """
  def main(argv) do
    spec_path = resolve_spec_path()

    case Parser.parse(spec_path, ["head" | argv]) do
      {:ok, %HelpResult{text: text}} ->
        IO.puts(text)

      {:ok, %VersionResult{version: version}} ->
        IO.puts(version)

      {:ok, %ParseResult{flags: flags, arguments: arguments}} ->
        byte_mode = flags["bytes"] != nil
        line_count = flags["lines"] || 10
        byte_count = flags["bytes"]
        quiet = !!flags["quiet"]
        verbose = !!flags["verbose"]
        zero_terminated = !!flags["zero_terminated"]
        delimiter = if zero_terminated, do: <<0>>, else: "\n"

        file_list = normalize_files(arguments["files"])
        show_headers = determine_headers(quiet, verbose, length(file_list))

        file_list
        |> Enum.with_index()
        |> Enum.each(fn {file, index} ->
          # Print header if appropriate.
          if show_headers do
            if index > 0, do: IO.write("\n")
            label = if file == "-", do: "standard input", else: file
            IO.write("==> #{label} <==\n")
          end

          case read_file(file) do
            {:ok, content} ->
              if byte_mode do
                IO.write(head_bytes(content, byte_count))
              else
                IO.write(head_lines(content, line_count, delimiter))
              end

            {:error, reason} ->
              IO.puts(:stderr, "head: #{file}: #{:file.format_error(reason)}")
          end
        end)

      {:error, %ParseErrors{errors: errors}} ->
        Enum.each(errors, fn e ->
          IO.puts(:stderr, "head: #{e.message}")
        end)

        System.halt(1)
    end
  end

  # ---------------------------------------------------------------------------
  # Business Logic: Extract first N lines or bytes.
  # ---------------------------------------------------------------------------

  @doc """
  Extract the first `count` lines from content using the given delimiter.

  We split on the delimiter, take the first `count` elements, and rejoin.
  The trailing delimiter is included to match GNU head behavior.
  """
  def head_lines("", _count, _delimiter), do: ""

  def head_lines(content, count, delimiter) do
    lines = String.split(content, delimiter)

    has_trailing = String.ends_with?(content, delimiter)

    effective_lines =
      if has_trailing do
        Enum.slice(lines, 0..(length(lines) - 2)//1)
      else
        lines
      end

    selected = Enum.take(effective_lines, count)

    if length(selected) > 0 do
      Enum.join(selected, delimiter) <> delimiter
    else
      ""
    end
  end

  @doc """
  Extract the first `count` bytes from content.
  """
  def head_bytes(content, count) do
    binary_part(content, 0, min(count, byte_size(content)))
  end

  # ---------------------------------------------------------------------------
  # Helpers
  # ---------------------------------------------------------------------------

  defp determine_headers(quiet, verbose, file_count) do
    cond do
      quiet -> false
      verbose -> true
      file_count > 1 -> true
      true -> false
    end
  end

  defp read_file("-") do
    case IO.read(:stdio, :eof) do
      {:error, reason} -> {:error, reason}
      :eof -> {:ok, ""}
      data -> {:ok, data}
    end
  end

  defp read_file(file), do: File.read(file)

  defp normalize_files(nil), do: ["-"]
  defp normalize_files(files) when is_list(files), do: files
  defp normalize_files(file) when is_binary(file), do: [file]

  defp resolve_spec_path do
    candidates = [
      if(function_exported?(Mix, :Project, 0),
        do: Path.join(Mix.Project.config()[:lockfile] |> Path.dirname(), "head.json"),
        else: nil
      ),
      "head.json",
      Path.join(:code.priv_dir(:unix_tools) |> to_string(), "head.json")
    ]

    Enum.find(candidates, fn
      nil -> false
      candidate_path -> File.exists?(candidate_path)
    end) ||
      raise "Could not find head.json spec file"
  end
end
