# AUTO-GENERATED FILE - DO NOT EDIT
from grammar_tools.token_grammar import TokenGrammar, TokenDefinition, PatternGroup

StarlarkTokens = TokenGrammar(
    version=1,
    case_insensitive=False,
    case_sensitive=True,
    mode="indentation",
    keywords=["and", "break", "continue", "def", "elif", "else", "for", "if", "in", "lambda", "load", "not", "or", "pass", "return", "True", "False", "None"],
    reserved_keywords=["as", "assert", "async", "await", "class", "del", "except", "finally", "from", "global", "import", "is", "nonlocal", "raise", "try", "while", "with", "yield"],
    definitions=[
        TokenDefinition(name="STRING_RAW_TRIPLE_DQ", pattern="[rR][bB]?\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"|[bB][rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"", is_regex=True, line_number=70, alias="STRING"),
        TokenDefinition(name="STRING_RAW_TRIPLE_SQ", pattern="[rR][bB]?'''([^'\\\\]|\\\\.|\\n)*'''|[bB][rR]'''([^'\\\\]|\\\\.|\\n)*'''", is_regex=True, line_number=71, alias="STRING"),
        TokenDefinition(name="STRING_TRIPLE_DQ", pattern="[bB]?\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"", is_regex=True, line_number=72, alias="STRING"),
        TokenDefinition(name="STRING_TRIPLE_SQ", pattern="[bB]?'''([^'\\\\]|\\\\.|\\n)*'''", is_regex=True, line_number=73, alias="STRING"),
        TokenDefinition(name="STRING_RAW_DQ", pattern="[rR][bB]?\"([^\"\\\\]|\\\\.)*\"|[bB][rR]\"([^\"\\\\]|\\\\.)*\"", is_regex=True, line_number=76, alias="STRING"),
        TokenDefinition(name="STRING_RAW_SQ", pattern="[rR][bB]?'([^'\\\\]|\\\\.)*'|[bB][rR]'([^'\\\\]|\\\\.)*'", is_regex=True, line_number=77, alias="STRING"),
        TokenDefinition(name="STRING_DQ", pattern="[bB]?\"([^\"\\\\]|\\\\.)*\"", is_regex=True, line_number=78, alias="STRING"),
        TokenDefinition(name="STRING_SQ", pattern="[bB]?'([^'\\\\]|\\\\.)*'", is_regex=True, line_number=79, alias="STRING"),
        TokenDefinition(name="FLOAT", pattern="[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?|\\.[0-9]+([eE][+-]?[0-9]+)?|[0-9]+[eE][+-]?[0-9]+", is_regex=True, line_number=92),
        TokenDefinition(name="INT_HEX", pattern="0[xX][0-9a-fA-F]+", is_regex=True, line_number=95, alias="INT"),
        TokenDefinition(name="INT_OCT", pattern="0[oO][0-7]+", is_regex=True, line_number=96, alias="INT"),
        TokenDefinition(name="INT", pattern="[0-9]+", is_regex=True, line_number=97),
        TokenDefinition(name="NAME", pattern="[a-zA-Z_][a-zA-Z0-9_]*", is_regex=True, line_number=107),
        TokenDefinition(name="DOUBLE_STAR_EQUALS", pattern="**=", is_regex=False, line_number=116),
        TokenDefinition(name="LEFT_SHIFT_EQUALS", pattern="<<=", is_regex=False, line_number=117),
        TokenDefinition(name="RIGHT_SHIFT_EQUALS", pattern=">>=", is_regex=False, line_number=118),
        TokenDefinition(name="FLOOR_DIV_EQUALS", pattern="//=", is_regex=False, line_number=119),
        TokenDefinition(name="DOUBLE_STAR", pattern="**", is_regex=False, line_number=128),
        TokenDefinition(name="FLOOR_DIV", pattern="//", is_regex=False, line_number=129),
        TokenDefinition(name="LEFT_SHIFT", pattern="<<", is_regex=False, line_number=130),
        TokenDefinition(name="RIGHT_SHIFT", pattern=">>", is_regex=False, line_number=131),
        TokenDefinition(name="EQUALS_EQUALS", pattern="==", is_regex=False, line_number=132),
        TokenDefinition(name="NOT_EQUALS", pattern="!=", is_regex=False, line_number=133),
        TokenDefinition(name="LESS_EQUALS", pattern="<=", is_regex=False, line_number=134),
        TokenDefinition(name="GREATER_EQUALS", pattern=">=", is_regex=False, line_number=135),
        TokenDefinition(name="PLUS_EQUALS", pattern="+=", is_regex=False, line_number=136),
        TokenDefinition(name="MINUS_EQUALS", pattern="-=", is_regex=False, line_number=137),
        TokenDefinition(name="STAR_EQUALS", pattern="*=", is_regex=False, line_number=138),
        TokenDefinition(name="SLASH_EQUALS", pattern="/=", is_regex=False, line_number=139),
        TokenDefinition(name="PERCENT_EQUALS", pattern="%=", is_regex=False, line_number=140),
        TokenDefinition(name="AMP_EQUALS", pattern="&=", is_regex=False, line_number=141),
        TokenDefinition(name="PIPE_EQUALS", pattern="|=", is_regex=False, line_number=142),
        TokenDefinition(name="CARET_EQUALS", pattern="^=", is_regex=False, line_number=143),
        TokenDefinition(name="PLUS", pattern="+", is_regex=False, line_number=149),
        TokenDefinition(name="MINUS", pattern="-", is_regex=False, line_number=150),
        TokenDefinition(name="STAR", pattern="*", is_regex=False, line_number=151),
        TokenDefinition(name="SLASH", pattern="/", is_regex=False, line_number=152),
        TokenDefinition(name="PERCENT", pattern="%", is_regex=False, line_number=153),
        TokenDefinition(name="EQUALS", pattern="=", is_regex=False, line_number=154),
        TokenDefinition(name="LESS_THAN", pattern="<", is_regex=False, line_number=155),
        TokenDefinition(name="GREATER_THAN", pattern=">", is_regex=False, line_number=156),
        TokenDefinition(name="AMP", pattern="&", is_regex=False, line_number=157),
        TokenDefinition(name="PIPE", pattern="|", is_regex=False, line_number=158),
        TokenDefinition(name="CARET", pattern="^", is_regex=False, line_number=159),
        TokenDefinition(name="TILDE", pattern="~", is_regex=False, line_number=160),
        TokenDefinition(name="LPAREN", pattern="(", is_regex=False, line_number=166),
        TokenDefinition(name="RPAREN", pattern=")", is_regex=False, line_number=167),
        TokenDefinition(name="LBRACKET", pattern="[", is_regex=False, line_number=168),
        TokenDefinition(name="RBRACKET", pattern="]", is_regex=False, line_number=169),
        TokenDefinition(name="LBRACE", pattern="{", is_regex=False, line_number=170),
        TokenDefinition(name="RBRACE", pattern="}", is_regex=False, line_number=171),
        TokenDefinition(name="COMMA", pattern=",", is_regex=False, line_number=172),
        TokenDefinition(name="COLON", pattern=":", is_regex=False, line_number=173),
        TokenDefinition(name="SEMICOLON", pattern=";", is_regex=False, line_number=174),
        TokenDefinition(name="DOT", pattern=".", is_regex=False, line_number=175),
    ],
    skip_definitions=[
        TokenDefinition(name="COMMENT", pattern="#[^\\n]*", is_regex=True, line_number=51),
        TokenDefinition(name="WHITESPACE", pattern="[ \\t]+", is_regex=True, line_number=52),
    ],
)
