export {
  compress,
  decompress,
  encodeCodes,
  decodeCodes,
  packCodes,
  unpackCodes,
  BitWriter,
  BitReader,
  CLEAR_CODE,
  STOP_CODE,
  INITIAL_NEXT_CODE,
  INITIAL_CODE_SIZE,
  MAX_CODE_SIZE,
} from "./lzw.js";
