# AUTO-GENERATED FILE — DO NOT EDIT
# Source: sql.tokens
# Regenerate with: grammar-tools compile-tokens <source.tokens>
#
# This file embeds a TokenGrammar as native Python data structures.
# Downstream packages import TOKEN_GRAMMAR directly instead of
# reading and parsing the .tokens file at runtime.

from grammar_tools.token_grammar import PatternGroup, TokenDefinition, TokenGrammar

# fmt: off  # noqa: E501 — generated code may have long lines

TOKEN_GRAMMAR = TokenGrammar(
    version=1,
    case_insensitive=True,
    case_sensitive=False,
    definitions=[
        TokenDefinition(
            name='NAME',
            pattern='[a-zA-Z_][a-zA-Z0-9_]*',
            is_regex=True,
            line_number=17,
            alias=None,
        ),
        TokenDefinition(
            name='NUMBER',
            pattern='[0-9]+\\.?[0-9]*',
            is_regex=True,
            line_number=18,
            alias=None,
        ),
        TokenDefinition(
            name='STRING_SQ',
            pattern="'([^'\\\\]|\\\\.)*'",
            is_regex=True,
            line_number=19,
            alias='STRING',
        ),
        TokenDefinition(
            name='QUOTED_ID',
            pattern='`[^`]+`',
            is_regex=True,
            line_number=20,
            alias='NAME',
        ),
        TokenDefinition(
            name='LESS_EQUALS',
            pattern='<=',
            is_regex=False,
            line_number=22,
            alias=None,
        ),
        TokenDefinition(
            name='GREATER_EQUALS',
            pattern='>=',
            is_regex=False,
            line_number=23,
            alias=None,
        ),
        TokenDefinition(
            name='NOT_EQUALS',
            pattern='!=',
            is_regex=False,
            line_number=24,
            alias=None,
        ),
        TokenDefinition(
            name='NEQ_ANSI',
            pattern='<>',
            is_regex=False,
            line_number=25,
            alias='NOT_EQUALS',
        ),
        TokenDefinition(
            name='EQUALS',
            pattern='=',
            is_regex=False,
            line_number=27,
            alias=None,
        ),
        TokenDefinition(
            name='LESS_THAN',
            pattern='<',
            is_regex=False,
            line_number=28,
            alias=None,
        ),
        TokenDefinition(
            name='GREATER_THAN',
            pattern='>',
            is_regex=False,
            line_number=29,
            alias=None,
        ),
        TokenDefinition(
            name='PLUS',
            pattern='+',
            is_regex=False,
            line_number=30,
            alias=None,
        ),
        TokenDefinition(
            name='MINUS',
            pattern='-',
            is_regex=False,
            line_number=31,
            alias=None,
        ),
        TokenDefinition(
            name='STAR',
            pattern='*',
            is_regex=False,
            line_number=32,
            alias=None,
        ),
        TokenDefinition(
            name='SLASH',
            pattern='/',
            is_regex=False,
            line_number=33,
            alias=None,
        ),
        TokenDefinition(
            name='PERCENT',
            pattern='%',
            is_regex=False,
            line_number=34,
            alias=None,
        ),
        TokenDefinition(
            name='LPAREN',
            pattern='(',
            is_regex=False,
            line_number=36,
            alias=None,
        ),
        TokenDefinition(
            name='RPAREN',
            pattern=')',
            is_regex=False,
            line_number=37,
            alias=None,
        ),
        TokenDefinition(
            name='COMMA',
            pattern=',',
            is_regex=False,
            line_number=38,
            alias=None,
        ),
        TokenDefinition(
            name='SEMICOLON',
            pattern=';',
            is_regex=False,
            line_number=39,
            alias=None,
        ),
        TokenDefinition(
            name='DOT',
            pattern='.',
            is_regex=False,
            line_number=40,
            alias=None,
        ),
    ],
    keywords=['WITH', 'RECURSIVE', 'SELECT', 'FROM', 'WHERE', 'GROUP', 'BY', 'HAVING', 'ORDER', 'LIMIT', 'OFFSET', 'INSERT', 'INTO', 'VALUES', 'UPDATE', 'SET', 'DELETE', 'ALTER', 'ADD', 'COLUMN', 'CREATE', 'DROP', 'TABLE', 'IF', 'EXISTS', 'NOT', 'AND', 'OR', 'NULL', 'IS', 'IN', 'BETWEEN', 'LIKE', 'AS', 'DISTINCT', 'ALL', 'UNION', 'INTERSECT', 'EXCEPT', 'JOIN', 'INNER', 'LEFT', 'RIGHT', 'OUTER', 'CROSS', 'FULL', 'ON', 'ASC', 'DESC', 'TRUE', 'FALSE', 'CASE', 'WHEN', 'THEN', 'ELSE', 'END', 'PRIMARY', 'KEY', 'UNIQUE', 'CHECK', 'REFERENCES', 'DEFAULT', 'VIEW', 'SAVEPOINT', 'RELEASE', 'TO'],
    mode=None,
    escape_mode=None,
    skip_definitions=[
        TokenDefinition(
            name='WHITESPACE',
            pattern='[ \\t\\r\\n]+',
            is_regex=True,
            line_number=100,
            alias=None,
        ),
        TokenDefinition(
            name='LINE_COMMENT',
            pattern='--[^\\n]*',
            is_regex=True,
            line_number=101,
            alias=None,
        ),
        TokenDefinition(
            name='BLOCK_COMMENT',
            pattern='\\x2f\\*([^*]|\\*[^\\x2f])*\\*\\x2f',
            is_regex=True,
            line_number=102,
            alias=None,
        ),
    ],
    reserved_keywords=[],
    error_definitions=[],
    groups={},
    layout_keywords=[],
)
