-- AUTO-GENERATED FILE — DO NOT EDIT
-- Source: es5.tokens
-- Regenerate with: grammar-tools compile-tokens es5.tokens
--
-- This file embeds a TokenGrammar as native Lua data structures.
-- Call token_grammar() instead of reading and parsing the .tokens file.

local gt = require("coding_adventures.grammar_tools")

local function token_grammar()
  local g = gt.TokenGrammar.new()
  g.definitions = {
        {
          name="NAME",
          pattern="[a-zA-Z_$][a-zA-Z0-9_$]*",
          is_regex=true,
          line_number=41,
          alias="",
        },
        {
          name="HEX_NUMBER",
          pattern="0[xX][0-9a-fA-F]+",
          is_regex=true,
          line_number=45,
          alias="NUMBER",
        },
        {
          name="FLOAT_NUMBER",
          pattern="[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?",
          is_regex=true,
          line_number=46,
          alias="NUMBER",
        },
        {
          name="LEADING_DOT_FLOAT",
          pattern="\\.[0-9]+([eE][+-]?[0-9]+)?",
          is_regex=true,
          line_number=47,
          alias="NUMBER",
        },
        {
          name="SCI_NUMBER",
          pattern="[0-9]+[eE][+-]?[0-9]+",
          is_regex=true,
          line_number=48,
          alias="NUMBER",
        },
        {
          name="INT_NUMBER",
          pattern="[0-9]+",
          is_regex=true,
          line_number=49,
          alias="NUMBER",
        },
        {
          name="STRING_DQ",
          pattern="\"([^\"\\\\]|\\\\.)*\"",
          is_regex=true,
          line_number=56,
          alias="STRING",
        },
        {
          name="STRING_SQ",
          pattern="'([^'\\\\]|\\\\.)*'",
          is_regex=true,
          line_number=57,
          alias="STRING",
        },
        {
          name="REGEX",
          pattern="\\/([^\\/\\\\\\n]|\\\\.)+\\/[gim]*",
          is_regex=true,
          line_number=61,
          alias="",
        },
        {
          name="STRICT_EQUALS",
          pattern="===",
          is_regex=false,
          line_number=69,
          alias="",
        },
        {
          name="STRICT_NOT_EQUALS",
          pattern="!==",
          is_regex=false,
          line_number=70,
          alias="",
        },
        {
          name="UNSIGNED_RIGHT_SHIFT_EQUALS",
          pattern=">>>=",
          is_regex=false,
          line_number=71,
          alias="",
        },
        {
          name="UNSIGNED_RIGHT_SHIFT",
          pattern=">>>",
          is_regex=false,
          line_number=72,
          alias="",
        },
        {
          name="LEFT_SHIFT_EQUALS",
          pattern="<<=",
          is_regex=false,
          line_number=73,
          alias="",
        },
        {
          name="RIGHT_SHIFT_EQUALS",
          pattern=">>=",
          is_regex=false,
          line_number=74,
          alias="",
        },
        {
          name="EQUALS_EQUALS",
          pattern="==",
          is_regex=false,
          line_number=75,
          alias="",
        },
        {
          name="NOT_EQUALS",
          pattern="!=",
          is_regex=false,
          line_number=76,
          alias="",
        },
        {
          name="LESS_EQUALS",
          pattern="<=",
          is_regex=false,
          line_number=77,
          alias="",
        },
        {
          name="GREATER_EQUALS",
          pattern=">=",
          is_regex=false,
          line_number=78,
          alias="",
        },
        {
          name="PLUS_EQUALS",
          pattern="+=",
          is_regex=false,
          line_number=79,
          alias="",
        },
        {
          name="MINUS_EQUALS",
          pattern="-=",
          is_regex=false,
          line_number=80,
          alias="",
        },
        {
          name="STAR_EQUALS",
          pattern="*=",
          is_regex=false,
          line_number=81,
          alias="",
        },
        {
          name="SLASH_EQUALS",
          pattern="/=",
          is_regex=false,
          line_number=82,
          alias="",
        },
        {
          name="PERCENT_EQUALS",
          pattern="%=",
          is_regex=false,
          line_number=83,
          alias="",
        },
        {
          name="AMPERSAND_EQUALS",
          pattern="&=",
          is_regex=false,
          line_number=84,
          alias="",
        },
        {
          name="PIPE_EQUALS",
          pattern="|=",
          is_regex=false,
          line_number=85,
          alias="",
        },
        {
          name="CARET_EQUALS",
          pattern="^=",
          is_regex=false,
          line_number=86,
          alias="",
        },
        {
          name="LEFT_SHIFT",
          pattern="<<",
          is_regex=false,
          line_number=87,
          alias="",
        },
        {
          name="RIGHT_SHIFT",
          pattern=">>",
          is_regex=false,
          line_number=88,
          alias="",
        },
        {
          name="AND_AND",
          pattern="&&",
          is_regex=false,
          line_number=89,
          alias="",
        },
        {
          name="OR_OR",
          pattern="||",
          is_regex=false,
          line_number=90,
          alias="",
        },
        {
          name="PLUS_PLUS",
          pattern="++",
          is_regex=false,
          line_number=91,
          alias="",
        },
        {
          name="MINUS_MINUS",
          pattern="--",
          is_regex=false,
          line_number=92,
          alias="",
        },
        {
          name="EQUALS",
          pattern="=",
          is_regex=false,
          line_number=98,
          alias="",
        },
        {
          name="PLUS",
          pattern="+",
          is_regex=false,
          line_number=99,
          alias="",
        },
        {
          name="MINUS",
          pattern="-",
          is_regex=false,
          line_number=100,
          alias="",
        },
        {
          name="STAR",
          pattern="*",
          is_regex=false,
          line_number=101,
          alias="",
        },
        {
          name="SLASH",
          pattern="/",
          is_regex=false,
          line_number=102,
          alias="",
        },
        {
          name="PERCENT",
          pattern="%",
          is_regex=false,
          line_number=103,
          alias="",
        },
        {
          name="LESS_THAN",
          pattern="<",
          is_regex=false,
          line_number=104,
          alias="",
        },
        {
          name="GREATER_THAN",
          pattern=">",
          is_regex=false,
          line_number=105,
          alias="",
        },
        {
          name="BANG",
          pattern="!",
          is_regex=false,
          line_number=106,
          alias="",
        },
        {
          name="AMPERSAND",
          pattern="&",
          is_regex=false,
          line_number=107,
          alias="",
        },
        {
          name="PIPE",
          pattern="|",
          is_regex=false,
          line_number=108,
          alias="",
        },
        {
          name="CARET",
          pattern="^",
          is_regex=false,
          line_number=109,
          alias="",
        },
        {
          name="TILDE",
          pattern="~",
          is_regex=false,
          line_number=110,
          alias="",
        },
        {
          name="QUESTION",
          pattern="?",
          is_regex=false,
          line_number=111,
          alias="",
        },
        {
          name="LPAREN",
          pattern="(",
          is_regex=false,
          line_number=117,
          alias="",
        },
        {
          name="RPAREN",
          pattern=")",
          is_regex=false,
          line_number=118,
          alias="",
        },
        {
          name="LBRACE",
          pattern="{",
          is_regex=false,
          line_number=119,
          alias="",
        },
        {
          name="RBRACE",
          pattern="}",
          is_regex=false,
          line_number=120,
          alias="",
        },
        {
          name="LBRACKET",
          pattern="[",
          is_regex=false,
          line_number=121,
          alias="",
        },
        {
          name="RBRACKET",
          pattern="]",
          is_regex=false,
          line_number=122,
          alias="",
        },
        {
          name="SEMICOLON",
          pattern=";",
          is_regex=false,
          line_number=123,
          alias="",
        },
        {
          name="COMMA",
          pattern=",",
          is_regex=false,
          line_number=124,
          alias="",
        },
        {
          name="COLON",
          pattern=":",
          is_regex=false,
          line_number=125,
          alias="",
        },
        {
          name="DOT",
          pattern=".",
          is_regex=false,
          line_number=126,
          alias="",
        },
      }
  g.keywords = {"break", "case", "catch", "continue", "debugger", "default", "delete", "do", "else", "finally", "for", "function", "if", "in", "instanceof", "new", "return", "switch", "this", "throw", "try", "typeof", "var", "void", "while", "with", "true", "false", "null"}
  g.mode = ""
  g.escape_mode = ""
  g.skip_definitions = {
        {
          name="WHITESPACE",
          pattern="[ \\t\\r\\n\11\12]+",
          is_regex=true,
          line_number=191,
          alias="",
        },
        {
          name="LINE_COMMENT",
          pattern="\\/\\/[^\\n]*",
          is_regex=true,
          line_number=192,
          alias="",
        },
        {
          name="BLOCK_COMMENT",
          pattern="\\/\\*([^*]|\\*[^\\/])*\\*\\/",
          is_regex=true,
          line_number=193,
          alias="",
        },
      }
  g.reserved_keywords = {"class", "const", "enum", "export", "extends", "import", "super"}
  g.context_keywords = {}
  g.layout_keywords = {}
  g.soft_keywords = {}
  g.error_definitions = {
        {
          name="BAD_STRING_DQ",
          pattern="\"[^\"]*$",
          is_regex=true,
          line_number=200,
          alias="",
        },
        {
          name="BAD_STRING_SQ",
          pattern="'[^']*$",
          is_regex=true,
          line_number=201,
          alias="",
        },
        {
          name="BAD_REGEX",
          pattern="\\/([^\\/\\\\\\n]|\\\\.)*$",
          is_regex=true,
          line_number=202,
          alias="",
        },
      }
  g.groups = {}
  g.case_sensitive = true
  g.version = 0
  g.case_insensitive = false
  return g
end

return { token_grammar = token_grammar }
