// @generated by required-capabilities-compiler. Do not edit by hand.
#![allow(dead_code)]

pub const GENERATED_OPERATION_PACKAGE: &str = "rust/weather-agent-e2e";
pub const HTTP_DNS_DOMAINS: &[&str] = &["api.weather.gov"];
pub const HTTP_CONNECT_AUTHORITIES: &[&str] = &["api.weather.gov:443"];

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedOperationHttpClient {
    inner: operation_primitives::OperationHttpClient,
}

impl GeneratedOperationHttpClient {
    pub fn new() -> Result<Self, operation_primitives::OperationHttpClientError> {
        Ok(Self {
            inner: operation_primitives::OperationHttpClient::from_compiled_allowlist(
                HTTP_DNS_DOMAINS,
                HTTP_CONNECT_AUTHORITIES,
            )?,
        })
    }

    pub fn declared_domains(&self) -> &[String] {
        self.inner.declared_domains()
    }

    pub fn preflight_get(
        &self,
        url: &str,
    ) -> Result<
        operation_primitives::OperationHttpRequest,
        operation_primitives::OperationHttpClientError,
    > {
        self.inner.preflight_get(url)
    }

    pub fn get_with_transport<T, E, F>(
        &self,
        url: &str,
        fallback: T,
        transport: F,
    ) -> operation_primitives::OperationOutcome<T>
    where
        T: Clone,
        E: std::fmt::Display,
        F: FnOnce(operation_primitives::OperationHttpRequest) -> Result<T, E>,
    {
        self.inner.get_with_transport(url, fallback, transport)
    }

    pub fn into_inner(self) -> operation_primitives::OperationHttpClient {
        self.inner
    }
}

pub fn generated_http_client(
) -> Result<GeneratedOperationHttpClient, operation_primitives::OperationHttpClientError> {
    GeneratedOperationHttpClient::new()
}
