// AUTO-GENERATED FILE - DO NOT EDIT
// Source: es2021.tokens
// Regenerate with: grammar-tools compile-tokens es2021.tokens
//
// This file embeds a TokenGrammar as native TypeScript object literals.
// Import it directly instead of reading and parsing the .tokens file at
// runtime.

import type { TokenGrammar } from "@coding-adventures/grammar-tools";

export const TOKEN_GRAMMAR: TokenGrammar = {
  version: 1,
  caseInsensitive: false,
  caseSensitive: true,
  definitions: [
    {
      name: "NAME",
      pattern: "[a-zA-Z_$][a-zA-Z0-9_$]*",
      isRegex: true,
      lineNumber: 42,
    },
    {
      name: "BIGINT_HEX",
      pattern: "0[xX][0-9a-fA-F]([0-9a-fA-F_]*[0-9a-fA-F])?n",
      isRegex: true,
      lineNumber: 68,
      alias: "BIGINT",
    },
    {
      name: "BIGINT_BINARY",
      pattern: "0[bB][01]([01_]*[01])?n",
      isRegex: true,
      lineNumber: 69,
      alias: "BIGINT",
    },
    {
      name: "BIGINT_OCTAL",
      pattern: "0[oO][0-7]([0-7_]*[0-7])?n",
      isRegex: true,
      lineNumber: 70,
      alias: "BIGINT",
    },
    {
      name: "BIGINT_DECIMAL",
      pattern: "[0-9]([0-9_]*[0-9])?n",
      isRegex: true,
      lineNumber: 71,
      alias: "BIGINT",
    },
    {
      name: "BINARY_NUMBER",
      pattern: "0[bB][01]([01_]*[01])?",
      isRegex: true,
      lineNumber: 73,
      alias: "NUMBER",
    },
    {
      name: "OCTAL_NUMBER",
      pattern: "0[oO][0-7]([0-7_]*[0-7])?",
      isRegex: true,
      lineNumber: 74,
      alias: "NUMBER",
    },
    {
      name: "HEX_NUMBER",
      pattern: "0[xX][0-9a-fA-F]([0-9a-fA-F_]*[0-9a-fA-F])?",
      isRegex: true,
      lineNumber: 75,
      alias: "NUMBER",
    },
    {
      name: "FLOAT_NUMBER",
      pattern: "[0-9]([0-9_]*[0-9])?\\.[0-9]([0-9_]*[0-9])?([eE][+-]?[0-9]([0-9_]*[0-9])?)?",
      isRegex: true,
      lineNumber: 76,
      alias: "NUMBER",
    },
    {
      name: "LEADING_DOT_FLOAT",
      pattern: "\\.[0-9]([0-9_]*[0-9])?([eE][+-]?[0-9]([0-9_]*[0-9])?)?",
      isRegex: true,
      lineNumber: 77,
      alias: "NUMBER",
    },
    {
      name: "SCI_NUMBER",
      pattern: "[0-9]([0-9_]*[0-9])?[eE][+-]?[0-9]([0-9_]*[0-9])?",
      isRegex: true,
      lineNumber: 78,
      alias: "NUMBER",
    },
    {
      name: "INT_NUMBER",
      pattern: "[0-9]([0-9_]*[0-9])?",
      isRegex: true,
      lineNumber: 79,
      alias: "NUMBER",
    },
    {
      name: "STRING_DQ",
      pattern: "\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 83,
      alias: "STRING",
    },
    {
      name: "STRING_SQ",
      pattern: "'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 84,
      alias: "STRING",
    },
    {
      name: "TEMPLATE_HEAD",
      pattern: "`([^`\\\\$]|\\\\.|\\$[^{])*\\$\\{",
      isRegex: true,
      lineNumber: 88,
    },
    {
      name: "TEMPLATE_NO_SUB",
      pattern: "`([^`\\\\$]|\\\\.|\\$[^{])*`",
      isRegex: true,
      lineNumber: 89,
    },
    {
      name: "REGEX",
      pattern: "\\/([^\\/\\\\\\n]|\\\\.)+\\/[gimsuy]*",
      isRegex: true,
      lineNumber: 93,
    },
    {
      name: "OR_OR_EQUALS",
      pattern: "||=",
      isRegex: false,
      lineNumber: 106,
    },
    {
      name: "AND_AND_EQUALS",
      pattern: "&&=",
      isRegex: false,
      lineNumber: 107,
    },
    {
      name: "NULLISH_COALESCE_EQUALS",
      pattern: "??=",
      isRegex: false,
      lineNumber: 108,
    },
    {
      name: "OPTIONAL_CHAIN",
      pattern: "?.",
      isRegex: false,
      lineNumber: 109,
    },
    {
      name: "NULLISH_COALESCE",
      pattern: "??",
      isRegex: false,
      lineNumber: 110,
    },
    {
      name: "STAR_STAR_EQUALS",
      pattern: "**=",
      isRegex: false,
      lineNumber: 111,
    },
    {
      name: "STAR_STAR",
      pattern: "**",
      isRegex: false,
      lineNumber: 112,
    },
    {
      name: "STRICT_EQUALS",
      pattern: "===",
      isRegex: false,
      lineNumber: 113,
    },
    {
      name: "STRICT_NOT_EQUALS",
      pattern: "!==",
      isRegex: false,
      lineNumber: 114,
    },
    {
      name: "UNSIGNED_RIGHT_SHIFT_EQUALS",
      pattern: ">>>=",
      isRegex: false,
      lineNumber: 115,
    },
    {
      name: "UNSIGNED_RIGHT_SHIFT",
      pattern: ">>>",
      isRegex: false,
      lineNumber: 116,
    },
    {
      name: "LEFT_SHIFT_EQUALS",
      pattern: "<<=",
      isRegex: false,
      lineNumber: 117,
    },
    {
      name: "RIGHT_SHIFT_EQUALS",
      pattern: ">>=",
      isRegex: false,
      lineNumber: 118,
    },
    {
      name: "EQUALS_EQUALS",
      pattern: "==",
      isRegex: false,
      lineNumber: 119,
    },
    {
      name: "NOT_EQUALS",
      pattern: "!=",
      isRegex: false,
      lineNumber: 120,
    },
    {
      name: "LESS_EQUALS",
      pattern: "<=",
      isRegex: false,
      lineNumber: 121,
    },
    {
      name: "GREATER_EQUALS",
      pattern: ">=",
      isRegex: false,
      lineNumber: 122,
    },
    {
      name: "PLUS_EQUALS",
      pattern: "+=",
      isRegex: false,
      lineNumber: 123,
    },
    {
      name: "MINUS_EQUALS",
      pattern: "-=",
      isRegex: false,
      lineNumber: 124,
    },
    {
      name: "STAR_EQUALS",
      pattern: "*=",
      isRegex: false,
      lineNumber: 125,
    },
    {
      name: "SLASH_EQUALS",
      pattern: "/=",
      isRegex: false,
      lineNumber: 126,
    },
    {
      name: "PERCENT_EQUALS",
      pattern: "%=",
      isRegex: false,
      lineNumber: 127,
    },
    {
      name: "AMPERSAND_EQUALS",
      pattern: "&=",
      isRegex: false,
      lineNumber: 128,
    },
    {
      name: "PIPE_EQUALS",
      pattern: "|=",
      isRegex: false,
      lineNumber: 129,
    },
    {
      name: "CARET_EQUALS",
      pattern: "^=",
      isRegex: false,
      lineNumber: 130,
    },
    {
      name: "LEFT_SHIFT",
      pattern: "<<",
      isRegex: false,
      lineNumber: 131,
    },
    {
      name: "RIGHT_SHIFT",
      pattern: ">>",
      isRegex: false,
      lineNumber: 132,
    },
    {
      name: "AND_AND",
      pattern: "&&",
      isRegex: false,
      lineNumber: 133,
    },
    {
      name: "OR_OR",
      pattern: "||",
      isRegex: false,
      lineNumber: 134,
    },
    {
      name: "PLUS_PLUS",
      pattern: "++",
      isRegex: false,
      lineNumber: 135,
    },
    {
      name: "MINUS_MINUS",
      pattern: "--",
      isRegex: false,
      lineNumber: 136,
    },
    {
      name: "ARROW",
      pattern: "=>",
      isRegex: false,
      lineNumber: 137,
    },
    {
      name: "ELLIPSIS",
      pattern: "...",
      isRegex: false,
      lineNumber: 138,
    },
    {
      name: "EQUALS",
      pattern: "=",
      isRegex: false,
      lineNumber: 144,
    },
    {
      name: "PLUS",
      pattern: "+",
      isRegex: false,
      lineNumber: 145,
    },
    {
      name: "MINUS",
      pattern: "-",
      isRegex: false,
      lineNumber: 146,
    },
    {
      name: "STAR",
      pattern: "*",
      isRegex: false,
      lineNumber: 147,
    },
    {
      name: "SLASH",
      pattern: "/",
      isRegex: false,
      lineNumber: 148,
    },
    {
      name: "PERCENT",
      pattern: "%",
      isRegex: false,
      lineNumber: 149,
    },
    {
      name: "LESS_THAN",
      pattern: "<",
      isRegex: false,
      lineNumber: 150,
    },
    {
      name: "GREATER_THAN",
      pattern: ">",
      isRegex: false,
      lineNumber: 151,
    },
    {
      name: "BANG",
      pattern: "!",
      isRegex: false,
      lineNumber: 152,
    },
    {
      name: "AMPERSAND",
      pattern: "&",
      isRegex: false,
      lineNumber: 153,
    },
    {
      name: "PIPE",
      pattern: "|",
      isRegex: false,
      lineNumber: 154,
    },
    {
      name: "CARET",
      pattern: "^",
      isRegex: false,
      lineNumber: 155,
    },
    {
      name: "TILDE",
      pattern: "~",
      isRegex: false,
      lineNumber: 156,
    },
    {
      name: "QUESTION",
      pattern: "?",
      isRegex: false,
      lineNumber: 157,
    },
    {
      name: "LPAREN",
      pattern: "(",
      isRegex: false,
      lineNumber: 163,
    },
    {
      name: "RPAREN",
      pattern: ")",
      isRegex: false,
      lineNumber: 164,
    },
    {
      name: "LBRACE",
      pattern: "{",
      isRegex: false,
      lineNumber: 165,
    },
    {
      name: "RBRACE",
      pattern: "}",
      isRegex: false,
      lineNumber: 166,
    },
    {
      name: "LBRACKET",
      pattern: "[",
      isRegex: false,
      lineNumber: 167,
    },
    {
      name: "RBRACKET",
      pattern: "]",
      isRegex: false,
      lineNumber: 168,
    },
    {
      name: "SEMICOLON",
      pattern: ";",
      isRegex: false,
      lineNumber: 169,
    },
    {
      name: "COMMA",
      pattern: ",",
      isRegex: false,
      lineNumber: 170,
    },
    {
      name: "COLON",
      pattern: ":",
      isRegex: false,
      lineNumber: 171,
    },
    {
      name: "DOT",
      pattern: ".",
      isRegex: false,
      lineNumber: 172,
    },
  ],
  keywords: ["break","case","catch","class","const","continue","debugger","default","delete","do","else","export","extends","finally","for","function","if","import","in","instanceof","let","new","return","super","switch","this","throw","try","typeof","var","void","while","with","yield","true","false","null"],
  mode: undefined,
  escapeMode: undefined,
  skipDefinitions: [
    {
      name: "WHITESPACE",
      pattern: "[ \\t\\r\\n\\v\\f]+",
      isRegex: true,
      lineNumber: 251,
    },
    {
      name: "LINE_COMMENT",
      pattern: "\\/\\/[^\\n]*",
      isRegex: true,
      lineNumber: 252,
    },
    {
      name: "BLOCK_COMMENT",
      pattern: "\\/\\*([^*]|\\*[^\\/])*\\*\\/",
      isRegex: true,
      lineNumber: 253,
    },
  ],
  reservedKeywords: ["enum"],
  layoutKeywords: [],
  contextKeywords: ["as","async","await","from","of","get","set","static"],
  errorDefinitions: [],
  groups: {
    "template": {
      name: "template",
      definitions: [
        {
          name: "TEMPLATE_MIDDLE",
          pattern: "\\}([^`\\\\$]|\\\\.|\\$[^{])*\\$\\{",
          isRegex: true,
          lineNumber: 243,
        },
        {
          name: "TEMPLATE_TAIL",
          pattern: "\\}([^`\\\\$]|\\\\.|\\$[^{])*`",
          isRegex: true,
          lineNumber: 244,
        },
      ],
    },
  },
  softKeywords: [],
};
