// AUTO-GENERATED FILE - DO NOT EDIT
// Source: es1.tokens
// Regenerate with: grammar-tools compile-tokens es1.tokens
//
// This file embeds a TokenGrammar as native TypeScript object literals.
// Import it directly instead of reading and parsing the .tokens file at
// runtime.

import type { TokenGrammar } from "@coding-adventures/grammar-tools";

export const TOKEN_GRAMMAR: TokenGrammar = {
  version: 1,
  caseInsensitive: false,
  caseSensitive: true,
  definitions: [
    {
      name: "NAME",
      pattern: "[a-zA-Z_$][a-zA-Z0-9_$]*",
      isRegex: true,
      lineNumber: 43,
    },
    {
      name: "HEX_NUMBER",
      pattern: "0[xX][0-9a-fA-F]+",
      isRegex: true,
      lineNumber: 50,
      alias: "NUMBER",
    },
    {
      name: "FLOAT_NUMBER",
      pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?",
      isRegex: true,
      lineNumber: 51,
      alias: "NUMBER",
    },
    {
      name: "LEADING_DOT_FLOAT",
      pattern: "\\.[0-9]+([eE][+-]?[0-9]+)?",
      isRegex: true,
      lineNumber: 52,
      alias: "NUMBER",
    },
    {
      name: "SCI_NUMBER",
      pattern: "[0-9]+[eE][+-]?[0-9]+",
      isRegex: true,
      lineNumber: 53,
      alias: "NUMBER",
    },
    {
      name: "INT_NUMBER",
      pattern: "[0-9]+",
      isRegex: true,
      lineNumber: 54,
      alias: "NUMBER",
    },
    {
      name: "STRING_DQ",
      pattern: "\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 59,
      alias: "STRING",
    },
    {
      name: "STRING_SQ",
      pattern: "'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 60,
      alias: "STRING",
    },
    {
      name: "UNSIGNED_RIGHT_SHIFT_EQUALS",
      pattern: ">>>=",
      isRegex: false,
      lineNumber: 70,
    },
    {
      name: "UNSIGNED_RIGHT_SHIFT",
      pattern: ">>>",
      isRegex: false,
      lineNumber: 71,
    },
    {
      name: "LEFT_SHIFT_EQUALS",
      pattern: "<<=",
      isRegex: false,
      lineNumber: 72,
    },
    {
      name: "RIGHT_SHIFT_EQUALS",
      pattern: ">>=",
      isRegex: false,
      lineNumber: 73,
    },
    {
      name: "EQUALS_EQUALS",
      pattern: "==",
      isRegex: false,
      lineNumber: 74,
    },
    {
      name: "NOT_EQUALS",
      pattern: "!=",
      isRegex: false,
      lineNumber: 75,
    },
    {
      name: "LESS_EQUALS",
      pattern: "<=",
      isRegex: false,
      lineNumber: 76,
    },
    {
      name: "GREATER_EQUALS",
      pattern: ">=",
      isRegex: false,
      lineNumber: 77,
    },
    {
      name: "PLUS_EQUALS",
      pattern: "+=",
      isRegex: false,
      lineNumber: 78,
    },
    {
      name: "MINUS_EQUALS",
      pattern: "-=",
      isRegex: false,
      lineNumber: 79,
    },
    {
      name: "STAR_EQUALS",
      pattern: "*=",
      isRegex: false,
      lineNumber: 80,
    },
    {
      name: "SLASH_EQUALS",
      pattern: "/=",
      isRegex: false,
      lineNumber: 81,
    },
    {
      name: "PERCENT_EQUALS",
      pattern: "%=",
      isRegex: false,
      lineNumber: 82,
    },
    {
      name: "AMPERSAND_EQUALS",
      pattern: "&=",
      isRegex: false,
      lineNumber: 83,
    },
    {
      name: "PIPE_EQUALS",
      pattern: "|=",
      isRegex: false,
      lineNumber: 84,
    },
    {
      name: "CARET_EQUALS",
      pattern: "^=",
      isRegex: false,
      lineNumber: 85,
    },
    {
      name: "LEFT_SHIFT",
      pattern: "<<",
      isRegex: false,
      lineNumber: 86,
    },
    {
      name: "RIGHT_SHIFT",
      pattern: ">>",
      isRegex: false,
      lineNumber: 87,
    },
    {
      name: "AND_AND",
      pattern: "&&",
      isRegex: false,
      lineNumber: 88,
    },
    {
      name: "OR_OR",
      pattern: "||",
      isRegex: false,
      lineNumber: 89,
    },
    {
      name: "PLUS_PLUS",
      pattern: "++",
      isRegex: false,
      lineNumber: 90,
    },
    {
      name: "MINUS_MINUS",
      pattern: "--",
      isRegex: false,
      lineNumber: 91,
    },
    {
      name: "EQUALS",
      pattern: "=",
      isRegex: false,
      lineNumber: 97,
    },
    {
      name: "PLUS",
      pattern: "+",
      isRegex: false,
      lineNumber: 98,
    },
    {
      name: "MINUS",
      pattern: "-",
      isRegex: false,
      lineNumber: 99,
    },
    {
      name: "STAR",
      pattern: "*",
      isRegex: false,
      lineNumber: 100,
    },
    {
      name: "SLASH",
      pattern: "/",
      isRegex: false,
      lineNumber: 101,
    },
    {
      name: "PERCENT",
      pattern: "%",
      isRegex: false,
      lineNumber: 102,
    },
    {
      name: "LESS_THAN",
      pattern: "<",
      isRegex: false,
      lineNumber: 103,
    },
    {
      name: "GREATER_THAN",
      pattern: ">",
      isRegex: false,
      lineNumber: 104,
    },
    {
      name: "BANG",
      pattern: "!",
      isRegex: false,
      lineNumber: 105,
    },
    {
      name: "AMPERSAND",
      pattern: "&",
      isRegex: false,
      lineNumber: 106,
    },
    {
      name: "PIPE",
      pattern: "|",
      isRegex: false,
      lineNumber: 107,
    },
    {
      name: "CARET",
      pattern: "^",
      isRegex: false,
      lineNumber: 108,
    },
    {
      name: "TILDE",
      pattern: "~",
      isRegex: false,
      lineNumber: 109,
    },
    {
      name: "QUESTION",
      pattern: "?",
      isRegex: false,
      lineNumber: 110,
    },
    {
      name: "LPAREN",
      pattern: "(",
      isRegex: false,
      lineNumber: 116,
    },
    {
      name: "RPAREN",
      pattern: ")",
      isRegex: false,
      lineNumber: 117,
    },
    {
      name: "LBRACE",
      pattern: "{",
      isRegex: false,
      lineNumber: 118,
    },
    {
      name: "RBRACE",
      pattern: "}",
      isRegex: false,
      lineNumber: 119,
    },
    {
      name: "LBRACKET",
      pattern: "[",
      isRegex: false,
      lineNumber: 120,
    },
    {
      name: "RBRACKET",
      pattern: "]",
      isRegex: false,
      lineNumber: 121,
    },
    {
      name: "SEMICOLON",
      pattern: ";",
      isRegex: false,
      lineNumber: 122,
    },
    {
      name: "COMMA",
      pattern: ",",
      isRegex: false,
      lineNumber: 123,
    },
    {
      name: "COLON",
      pattern: ":",
      isRegex: false,
      lineNumber: 124,
    },
    {
      name: "DOT",
      pattern: ".",
      isRegex: false,
      lineNumber: 125,
    },
  ],
  keywords: ["break","case","continue","default","delete","do","else","for","function","if","in","new","return","switch","this","typeof","var","void","while","with","true","false","null"],
  mode: undefined,
  escapeMode: undefined,
  skipDefinitions: [
    {
      name: "WHITESPACE",
      pattern: "[ \\t\\r\\n\\v\\f]+",
      isRegex: true,
      lineNumber: 182,
    },
    {
      name: "LINE_COMMENT",
      pattern: "\\/\\/[^\\n]*",
      isRegex: true,
      lineNumber: 183,
    },
    {
      name: "BLOCK_COMMENT",
      pattern: "\\/\\*([^*]|\\*[^\\/])*\\*\\/",
      isRegex: true,
      lineNumber: 184,
    },
  ],
  reservedKeywords: ["class","const","enum","export","extends","import","super"],
  layoutKeywords: [],
  contextKeywords: [],
  errorDefinitions: [],
  groups: {},
  softKeywords: [],
};
