// AUTO-GENERATED FILE - DO NOT EDIT
// Source: es2017.tokens
// Regenerate with: grammar-tools compile-tokens es2017.tokens
//
// This file embeds a TokenGrammar as native TypeScript object literals.
// Import it directly instead of reading and parsing the .tokens file at
// runtime.

import type { TokenGrammar } from "@coding-adventures/grammar-tools";

export const TOKEN_GRAMMAR: TokenGrammar = {
  version: 1,
  caseInsensitive: false,
  caseSensitive: true,
  definitions: [
    {
      name: "NAME",
      pattern: "[a-zA-Z_$][a-zA-Z0-9_$]*",
      isRegex: true,
      lineNumber: 34,
    },
    {
      name: "BINARY_NUMBER",
      pattern: "0[bB][01]+",
      isRegex: true,
      lineNumber: 38,
      alias: "NUMBER",
    },
    {
      name: "OCTAL_NUMBER",
      pattern: "0[oO][0-7]+",
      isRegex: true,
      lineNumber: 39,
      alias: "NUMBER",
    },
    {
      name: "HEX_NUMBER",
      pattern: "0[xX][0-9a-fA-F]+",
      isRegex: true,
      lineNumber: 40,
      alias: "NUMBER",
    },
    {
      name: "FLOAT_NUMBER",
      pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?",
      isRegex: true,
      lineNumber: 41,
      alias: "NUMBER",
    },
    {
      name: "LEADING_DOT_FLOAT",
      pattern: "\\.[0-9]+([eE][+-]?[0-9]+)?",
      isRegex: true,
      lineNumber: 42,
      alias: "NUMBER",
    },
    {
      name: "SCI_NUMBER",
      pattern: "[0-9]+[eE][+-]?[0-9]+",
      isRegex: true,
      lineNumber: 43,
      alias: "NUMBER",
    },
    {
      name: "INT_NUMBER",
      pattern: "[0-9]+",
      isRegex: true,
      lineNumber: 44,
      alias: "NUMBER",
    },
    {
      name: "STRING_DQ",
      pattern: "\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 48,
      alias: "STRING",
    },
    {
      name: "STRING_SQ",
      pattern: "'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 49,
      alias: "STRING",
    },
    {
      name: "TEMPLATE_HEAD",
      pattern: "`([^`\\\\$]|\\\\.|\\$[^{])*\\$\\{",
      isRegex: true,
      lineNumber: 53,
    },
    {
      name: "TEMPLATE_NO_SUB",
      pattern: "`([^`\\\\$]|\\\\.|\\$[^{])*`",
      isRegex: true,
      lineNumber: 54,
    },
    {
      name: "REGEX",
      pattern: "\\/([^\\/\\\\\\n]|\\\\.)+\\/[gimuy]*",
      isRegex: true,
      lineNumber: 58,
    },
    {
      name: "STAR_STAR_EQUALS",
      pattern: "**=",
      isRegex: false,
      lineNumber: 66,
    },
    {
      name: "STAR_STAR",
      pattern: "**",
      isRegex: false,
      lineNumber: 67,
    },
    {
      name: "STRICT_EQUALS",
      pattern: "===",
      isRegex: false,
      lineNumber: 68,
    },
    {
      name: "STRICT_NOT_EQUALS",
      pattern: "!==",
      isRegex: false,
      lineNumber: 69,
    },
    {
      name: "UNSIGNED_RIGHT_SHIFT_EQUALS",
      pattern: ">>>=",
      isRegex: false,
      lineNumber: 70,
    },
    {
      name: "UNSIGNED_RIGHT_SHIFT",
      pattern: ">>>",
      isRegex: false,
      lineNumber: 71,
    },
    {
      name: "LEFT_SHIFT_EQUALS",
      pattern: "<<=",
      isRegex: false,
      lineNumber: 72,
    },
    {
      name: "RIGHT_SHIFT_EQUALS",
      pattern: ">>=",
      isRegex: false,
      lineNumber: 73,
    },
    {
      name: "EQUALS_EQUALS",
      pattern: "==",
      isRegex: false,
      lineNumber: 74,
    },
    {
      name: "NOT_EQUALS",
      pattern: "!=",
      isRegex: false,
      lineNumber: 75,
    },
    {
      name: "LESS_EQUALS",
      pattern: "<=",
      isRegex: false,
      lineNumber: 76,
    },
    {
      name: "GREATER_EQUALS",
      pattern: ">=",
      isRegex: false,
      lineNumber: 77,
    },
    {
      name: "PLUS_EQUALS",
      pattern: "+=",
      isRegex: false,
      lineNumber: 78,
    },
    {
      name: "MINUS_EQUALS",
      pattern: "-=",
      isRegex: false,
      lineNumber: 79,
    },
    {
      name: "STAR_EQUALS",
      pattern: "*=",
      isRegex: false,
      lineNumber: 80,
    },
    {
      name: "SLASH_EQUALS",
      pattern: "/=",
      isRegex: false,
      lineNumber: 81,
    },
    {
      name: "PERCENT_EQUALS",
      pattern: "%=",
      isRegex: false,
      lineNumber: 82,
    },
    {
      name: "AMPERSAND_EQUALS",
      pattern: "&=",
      isRegex: false,
      lineNumber: 83,
    },
    {
      name: "PIPE_EQUALS",
      pattern: "|=",
      isRegex: false,
      lineNumber: 84,
    },
    {
      name: "CARET_EQUALS",
      pattern: "^=",
      isRegex: false,
      lineNumber: 85,
    },
    {
      name: "LEFT_SHIFT",
      pattern: "<<",
      isRegex: false,
      lineNumber: 86,
    },
    {
      name: "RIGHT_SHIFT",
      pattern: ">>",
      isRegex: false,
      lineNumber: 87,
    },
    {
      name: "AND_AND",
      pattern: "&&",
      isRegex: false,
      lineNumber: 88,
    },
    {
      name: "OR_OR",
      pattern: "||",
      isRegex: false,
      lineNumber: 89,
    },
    {
      name: "PLUS_PLUS",
      pattern: "++",
      isRegex: false,
      lineNumber: 90,
    },
    {
      name: "MINUS_MINUS",
      pattern: "--",
      isRegex: false,
      lineNumber: 91,
    },
    {
      name: "ARROW",
      pattern: "=>",
      isRegex: false,
      lineNumber: 92,
    },
    {
      name: "ELLIPSIS",
      pattern: "...",
      isRegex: false,
      lineNumber: 93,
    },
    {
      name: "EQUALS",
      pattern: "=",
      isRegex: false,
      lineNumber: 99,
    },
    {
      name: "PLUS",
      pattern: "+",
      isRegex: false,
      lineNumber: 100,
    },
    {
      name: "MINUS",
      pattern: "-",
      isRegex: false,
      lineNumber: 101,
    },
    {
      name: "STAR",
      pattern: "*",
      isRegex: false,
      lineNumber: 102,
    },
    {
      name: "SLASH",
      pattern: "/",
      isRegex: false,
      lineNumber: 103,
    },
    {
      name: "PERCENT",
      pattern: "%",
      isRegex: false,
      lineNumber: 104,
    },
    {
      name: "LESS_THAN",
      pattern: "<",
      isRegex: false,
      lineNumber: 105,
    },
    {
      name: "GREATER_THAN",
      pattern: ">",
      isRegex: false,
      lineNumber: 106,
    },
    {
      name: "BANG",
      pattern: "!",
      isRegex: false,
      lineNumber: 107,
    },
    {
      name: "AMPERSAND",
      pattern: "&",
      isRegex: false,
      lineNumber: 108,
    },
    {
      name: "PIPE",
      pattern: "|",
      isRegex: false,
      lineNumber: 109,
    },
    {
      name: "CARET",
      pattern: "^",
      isRegex: false,
      lineNumber: 110,
    },
    {
      name: "TILDE",
      pattern: "~",
      isRegex: false,
      lineNumber: 111,
    },
    {
      name: "QUESTION",
      pattern: "?",
      isRegex: false,
      lineNumber: 112,
    },
    {
      name: "LPAREN",
      pattern: "(",
      isRegex: false,
      lineNumber: 118,
    },
    {
      name: "RPAREN",
      pattern: ")",
      isRegex: false,
      lineNumber: 119,
    },
    {
      name: "LBRACE",
      pattern: "{",
      isRegex: false,
      lineNumber: 120,
    },
    {
      name: "RBRACE",
      pattern: "}",
      isRegex: false,
      lineNumber: 121,
    },
    {
      name: "LBRACKET",
      pattern: "[",
      isRegex: false,
      lineNumber: 122,
    },
    {
      name: "RBRACKET",
      pattern: "]",
      isRegex: false,
      lineNumber: 123,
    },
    {
      name: "SEMICOLON",
      pattern: ";",
      isRegex: false,
      lineNumber: 124,
    },
    {
      name: "COMMA",
      pattern: ",",
      isRegex: false,
      lineNumber: 125,
    },
    {
      name: "COLON",
      pattern: ":",
      isRegex: false,
      lineNumber: 126,
    },
    {
      name: "DOT",
      pattern: ".",
      isRegex: false,
      lineNumber: 127,
    },
  ],
  keywords: ["break","case","catch","class","const","continue","debugger","default","delete","do","else","export","extends","finally","for","function","if","import","in","instanceof","let","new","return","super","switch","this","throw","try","typeof","var","void","while","with","yield","true","false","null"],
  mode: undefined,
  escapeMode: undefined,
  skipDefinitions: [
    {
      name: "WHITESPACE",
      pattern: "[ \\t\\r\\n\\v\\f]+",
      isRegex: true,
      lineNumber: 219,
    },
    {
      name: "LINE_COMMENT",
      pattern: "\\/\\/[^\\n]*",
      isRegex: true,
      lineNumber: 220,
    },
    {
      name: "BLOCK_COMMENT",
      pattern: "\\/\\*([^*]|\\*[^\\/])*\\*\\/",
      isRegex: true,
      lineNumber: 221,
    },
  ],
  reservedKeywords: ["enum"],
  layoutKeywords: [],
  contextKeywords: ["as","async","await","from","of","get","set","static"],
  errorDefinitions: [],
  groups: {
    "template": {
      name: "template",
      definitions: [
        {
          name: "TEMPLATE_MIDDLE",
          pattern: "\\}([^`\\\\$]|\\\\.|\\$[^{])*\\$\\{",
          isRegex: true,
          lineNumber: 211,
        },
        {
          name: "TEMPLATE_TAIL",
          pattern: "\\}([^`\\\\$]|\\\\.|\\$[^{])*`",
          isRegex: true,
          lineNumber: 212,
        },
      ],
    },
  },
  softKeywords: [],
};
