-- AUTO-GENERATED FILE — DO NOT EDIT
-- Source: java5.tokens
-- Regenerate with: grammar-tools compile-tokens java5.tokens
--
-- This file embeds a TokenGrammar as native Lua data structures.
-- Call token_grammar() instead of reading and parsing the .tokens file.

local gt = require("coding_adventures.grammar_tools")

local function token_grammar()
  local g = gt.TokenGrammar.new()
  g.definitions = {
        {
          name="NAME",
          pattern="[a-zA-Z_$][a-zA-Z0-9_$]*",
          is_regex=true,
          line_number=66,
          alias="",
        },
        {
          name="HEX_NUMBER",
          pattern="0[xX][0-9a-fA-F]+[lL]?",
          is_regex=true,
          line_number=93,
          alias="NUMBER",
        },
        {
          name="OCTAL_NUMBER",
          pattern="0[0-7]+[lL]?",
          is_regex=true,
          line_number=94,
          alias="NUMBER",
        },
        {
          name="FLOAT_NUMBER",
          pattern="[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?[fFdD]?",
          is_regex=true,
          line_number=95,
          alias="NUMBER",
        },
        {
          name="LEADING_DOT_FLOAT",
          pattern="\\.[0-9]+([eE][+-]?[0-9]+)?[fFdD]?",
          is_regex=true,
          line_number=96,
          alias="NUMBER",
        },
        {
          name="SCI_NUMBER",
          pattern="[0-9]+[eE][+-]?[0-9]+[fFdD]?",
          is_regex=true,
          line_number=97,
          alias="NUMBER",
        },
        {
          name="LONG_NUMBER",
          pattern="[0-9]+[lL]",
          is_regex=true,
          line_number=98,
          alias="NUMBER",
        },
        {
          name="FLOAT_SUFFIX",
          pattern="[0-9]+[fFdD]",
          is_regex=true,
          line_number=99,
          alias="NUMBER",
        },
        {
          name="INT_NUMBER",
          pattern="[0-9]+",
          is_regex=true,
          line_number=100,
          alias="NUMBER",
        },
        {
          name="STRING",
          pattern="\"([^\"\\\\]|\\\\.)*\"",
          is_regex=true,
          line_number=133,
          alias="",
        },
        {
          name="CHAR",
          pattern="'([^'\\\\]|\\\\.)*'",
          is_regex=true,
          line_number=134,
          alias="",
        },
        {
          name="ELLIPSIS",
          pattern="...",
          is_regex=false,
          line_number=164,
          alias="",
        },
        {
          name="UNSIGNED_RIGHT_SHIFT_EQUALS",
          pattern=">>>=",
          is_regex=false,
          line_number=165,
          alias="",
        },
        {
          name="UNSIGNED_RIGHT_SHIFT",
          pattern=">>>",
          is_regex=false,
          line_number=166,
          alias="",
        },
        {
          name="LEFT_SHIFT_EQUALS",
          pattern="<<=",
          is_regex=false,
          line_number=167,
          alias="",
        },
        {
          name="RIGHT_SHIFT_EQUALS",
          pattern=">>=",
          is_regex=false,
          line_number=168,
          alias="",
        },
        {
          name="EQUALS_EQUALS",
          pattern="==",
          is_regex=false,
          line_number=169,
          alias="",
        },
        {
          name="NOT_EQUALS",
          pattern="!=",
          is_regex=false,
          line_number=170,
          alias="",
        },
        {
          name="LESS_EQUALS",
          pattern="<=",
          is_regex=false,
          line_number=171,
          alias="",
        },
        {
          name="GREATER_EQUALS",
          pattern=">=",
          is_regex=false,
          line_number=172,
          alias="",
        },
        {
          name="AND_AND",
          pattern="&&",
          is_regex=false,
          line_number=173,
          alias="",
        },
        {
          name="OR_OR",
          pattern="||",
          is_regex=false,
          line_number=174,
          alias="",
        },
        {
          name="PLUS_PLUS",
          pattern="++",
          is_regex=false,
          line_number=175,
          alias="",
        },
        {
          name="MINUS_MINUS",
          pattern="--",
          is_regex=false,
          line_number=176,
          alias="",
        },
        {
          name="PLUS_EQUALS",
          pattern="+=",
          is_regex=false,
          line_number=177,
          alias="",
        },
        {
          name="MINUS_EQUALS",
          pattern="-=",
          is_regex=false,
          line_number=178,
          alias="",
        },
        {
          name="STAR_EQUALS",
          pattern="*=",
          is_regex=false,
          line_number=179,
          alias="",
        },
        {
          name="SLASH_EQUALS",
          pattern="/=",
          is_regex=false,
          line_number=180,
          alias="",
        },
        {
          name="PERCENT_EQUALS",
          pattern="%=",
          is_regex=false,
          line_number=181,
          alias="",
        },
        {
          name="AMPERSAND_EQUALS",
          pattern="&=",
          is_regex=false,
          line_number=182,
          alias="",
        },
        {
          name="PIPE_EQUALS",
          pattern="|=",
          is_regex=false,
          line_number=183,
          alias="",
        },
        {
          name="CARET_EQUALS",
          pattern="^=",
          is_regex=false,
          line_number=184,
          alias="",
        },
        {
          name="LEFT_SHIFT",
          pattern="<<",
          is_regex=false,
          line_number=185,
          alias="",
        },
        {
          name="RIGHT_SHIFT",
          pattern=">>",
          is_regex=false,
          line_number=186,
          alias="",
        },
        {
          name="AT",
          pattern="@",
          is_regex=false,
          line_number=204,
          alias="",
        },
        {
          name="EQUALS",
          pattern="=",
          is_regex=false,
          line_number=205,
          alias="",
        },
        {
          name="PLUS",
          pattern="+",
          is_regex=false,
          line_number=206,
          alias="",
        },
        {
          name="MINUS",
          pattern="-",
          is_regex=false,
          line_number=207,
          alias="",
        },
        {
          name="STAR",
          pattern="*",
          is_regex=false,
          line_number=208,
          alias="",
        },
        {
          name="SLASH",
          pattern="/",
          is_regex=false,
          line_number=209,
          alias="",
        },
        {
          name="PERCENT",
          pattern="%",
          is_regex=false,
          line_number=210,
          alias="",
        },
        {
          name="LESS_THAN",
          pattern="<",
          is_regex=false,
          line_number=211,
          alias="",
        },
        {
          name="GREATER_THAN",
          pattern=">",
          is_regex=false,
          line_number=212,
          alias="",
        },
        {
          name="BANG",
          pattern="!",
          is_regex=false,
          line_number=213,
          alias="",
        },
        {
          name="AMPERSAND",
          pattern="&",
          is_regex=false,
          line_number=214,
          alias="",
        },
        {
          name="PIPE",
          pattern="|",
          is_regex=false,
          line_number=215,
          alias="",
        },
        {
          name="CARET",
          pattern="^",
          is_regex=false,
          line_number=216,
          alias="",
        },
        {
          name="TILDE",
          pattern="~",
          is_regex=false,
          line_number=217,
          alias="",
        },
        {
          name="QUESTION",
          pattern="?",
          is_regex=false,
          line_number=218,
          alias="",
        },
        {
          name="LPAREN",
          pattern="(",
          is_regex=false,
          line_number=232,
          alias="",
        },
        {
          name="RPAREN",
          pattern=")",
          is_regex=false,
          line_number=233,
          alias="",
        },
        {
          name="LBRACE",
          pattern="{",
          is_regex=false,
          line_number=234,
          alias="",
        },
        {
          name="RBRACE",
          pattern="}",
          is_regex=false,
          line_number=235,
          alias="",
        },
        {
          name="LBRACKET",
          pattern="[",
          is_regex=false,
          line_number=236,
          alias="",
        },
        {
          name="RBRACKET",
          pattern="]",
          is_regex=false,
          line_number=237,
          alias="",
        },
        {
          name="SEMICOLON",
          pattern=";",
          is_regex=false,
          line_number=238,
          alias="",
        },
        {
          name="COMMA",
          pattern=",",
          is_regex=false,
          line_number=239,
          alias="",
        },
        {
          name="DOT",
          pattern=".",
          is_regex=false,
          line_number=240,
          alias="",
        },
        {
          name="COLON",
          pattern=":",
          is_regex=false,
          line_number=241,
          alias="",
        },
      }
  g.keywords = {"abstract", "assert", "boolean", "break", "byte", "case", "catch", "char", "class", "continue", "default", "do", "double", "else", "enum", "extends", "final", "finally", "float", "for", "if", "implements", "import", "instanceof", "int", "interface", "long", "native", "new", "package", "private", "protected", "public", "return", "short", "static", "strictfp", "super", "switch", "synchronized", "this", "throw", "throws", "transient", "try", "void", "volatile", "while", "true", "false", "null"}
  g.mode = ""
  g.escape_mode = ""
  g.skip_definitions = {
        {
          name="WHITESPACE",
          pattern="[ \\t\\r\\n\\v\\f]+",
          is_regex=true,
          line_number=362,
          alias="",
        },
        {
          name="LINE_COMMENT",
          pattern="\\/\\/[^\\n]*",
          is_regex=true,
          line_number=363,
          alias="",
        },
        {
          name="BLOCK_COMMENT",
          pattern="\\/\\*([^*]|\\*[^\\/])*\\*\\/",
          is_regex=true,
          line_number=364,
          alias="",
        },
      }
  g.reserved_keywords = {"const", "goto"}
  g.context_keywords = {}
  g.layout_keywords = {}
  g.soft_keywords = {}
  g.error_definitions = {
        {
          name="BAD_STRING",
          pattern="\"[^\"]*$",
          is_regex=true,
          line_number=375,
          alias="",
        },
        {
          name="BAD_CHAR",
          pattern="'[^']*$",
          is_regex=true,
          line_number=376,
          alias="",
        },
      }
  g.groups = {}
  g.case_sensitive = true
  g.version = 0
  g.case_insensitive = false
  return g
end

return { token_grammar = token_grammar }
