-- AUTO-GENERATED FILE — DO NOT EDIT
-- Source: java7.tokens
-- Regenerate with: grammar-tools compile-tokens java7.tokens
--
-- This file embeds a TokenGrammar as native Lua data structures.
-- Call token_grammar() instead of reading and parsing the .tokens file.

local gt = require("coding_adventures.grammar_tools")

local function token_grammar()
  local g = gt.TokenGrammar.new()
  g.definitions = {
        {
          name="NAME",
          pattern="[a-zA-Z_$][a-zA-Z0-9_$]*",
          is_regex=true,
          line_number=90,
          alias="",
        },
        {
          name="BINARY_NUMBER",
          pattern="0[bB][01](_*[01])*[lL]?",
          is_regex=true,
          line_number=138,
          alias="NUMBER",
        },
        {
          name="HEX_NUMBER",
          pattern="0[xX][0-9a-fA-F](_*[0-9a-fA-F])*[lL]?",
          is_regex=true,
          line_number=139,
          alias="NUMBER",
        },
        {
          name="OCTAL_NUMBER",
          pattern="0[0-7](_*[0-7])*[lL]?",
          is_regex=true,
          line_number=140,
          alias="NUMBER",
        },
        {
          name="FLOAT_NUMBER",
          pattern="[0-9](_*[0-9])*\\.[0-9](_*[0-9])*([eE][+-]?[0-9](_*[0-9])*)?[fFdD]?",
          is_regex=true,
          line_number=141,
          alias="NUMBER",
        },
        {
          name="LEADING_DOT_FLOAT",
          pattern="\\.[0-9](_*[0-9])*([eE][+-]?[0-9](_*[0-9])*)?[fFdD]?",
          is_regex=true,
          line_number=142,
          alias="NUMBER",
        },
        {
          name="SCI_NUMBER",
          pattern="[0-9](_*[0-9])*[eE][+-]?[0-9](_*[0-9])*[fFdD]?",
          is_regex=true,
          line_number=143,
          alias="NUMBER",
        },
        {
          name="LONG_NUMBER",
          pattern="[0-9](_*[0-9])*[lL]",
          is_regex=true,
          line_number=144,
          alias="NUMBER",
        },
        {
          name="FLOAT_SUFFIX",
          pattern="[0-9](_*[0-9])*[fFdD]",
          is_regex=true,
          line_number=145,
          alias="NUMBER",
        },
        {
          name="INT_NUMBER",
          pattern="[0-9](_*[0-9])*",
          is_regex=true,
          line_number=146,
          alias="NUMBER",
        },
        {
          name="STRING",
          pattern="\"([^\"\\\\]|\\\\.)*\"",
          is_regex=true,
          line_number=165,
          alias="",
        },
        {
          name="CHAR",
          pattern="'([^'\\\\]|\\\\.)*'",
          is_regex=true,
          line_number=166,
          alias="",
        },
        {
          name="ELLIPSIS",
          pattern="...",
          is_regex=false,
          line_number=187,
          alias="",
        },
        {
          name="UNSIGNED_RIGHT_SHIFT_EQUALS",
          pattern=">>>=",
          is_regex=false,
          line_number=188,
          alias="",
        },
        {
          name="UNSIGNED_RIGHT_SHIFT",
          pattern=">>>",
          is_regex=false,
          line_number=189,
          alias="",
        },
        {
          name="LEFT_SHIFT_EQUALS",
          pattern="<<=",
          is_regex=false,
          line_number=190,
          alias="",
        },
        {
          name="RIGHT_SHIFT_EQUALS",
          pattern=">>=",
          is_regex=false,
          line_number=191,
          alias="",
        },
        {
          name="EQUALS_EQUALS",
          pattern="==",
          is_regex=false,
          line_number=192,
          alias="",
        },
        {
          name="NOT_EQUALS",
          pattern="!=",
          is_regex=false,
          line_number=193,
          alias="",
        },
        {
          name="LESS_EQUALS",
          pattern="<=",
          is_regex=false,
          line_number=194,
          alias="",
        },
        {
          name="GREATER_EQUALS",
          pattern=">=",
          is_regex=false,
          line_number=195,
          alias="",
        },
        {
          name="AND_AND",
          pattern="&&",
          is_regex=false,
          line_number=196,
          alias="",
        },
        {
          name="OR_OR",
          pattern="||",
          is_regex=false,
          line_number=197,
          alias="",
        },
        {
          name="PLUS_PLUS",
          pattern="++",
          is_regex=false,
          line_number=198,
          alias="",
        },
        {
          name="MINUS_MINUS",
          pattern="--",
          is_regex=false,
          line_number=199,
          alias="",
        },
        {
          name="PLUS_EQUALS",
          pattern="+=",
          is_regex=false,
          line_number=200,
          alias="",
        },
        {
          name="MINUS_EQUALS",
          pattern="-=",
          is_regex=false,
          line_number=201,
          alias="",
        },
        {
          name="STAR_EQUALS",
          pattern="*=",
          is_regex=false,
          line_number=202,
          alias="",
        },
        {
          name="SLASH_EQUALS",
          pattern="/=",
          is_regex=false,
          line_number=203,
          alias="",
        },
        {
          name="PERCENT_EQUALS",
          pattern="%=",
          is_regex=false,
          line_number=204,
          alias="",
        },
        {
          name="AMPERSAND_EQUALS",
          pattern="&=",
          is_regex=false,
          line_number=205,
          alias="",
        },
        {
          name="PIPE_EQUALS",
          pattern="|=",
          is_regex=false,
          line_number=206,
          alias="",
        },
        {
          name="CARET_EQUALS",
          pattern="^=",
          is_regex=false,
          line_number=207,
          alias="",
        },
        {
          name="LEFT_SHIFT",
          pattern="<<",
          is_regex=false,
          line_number=208,
          alias="",
        },
        {
          name="RIGHT_SHIFT",
          pattern=">>",
          is_regex=false,
          line_number=209,
          alias="",
        },
        {
          name="AT",
          pattern="@",
          is_regex=false,
          line_number=229,
          alias="",
        },
        {
          name="EQUALS",
          pattern="=",
          is_regex=false,
          line_number=230,
          alias="",
        },
        {
          name="PLUS",
          pattern="+",
          is_regex=false,
          line_number=231,
          alias="",
        },
        {
          name="MINUS",
          pattern="-",
          is_regex=false,
          line_number=232,
          alias="",
        },
        {
          name="STAR",
          pattern="*",
          is_regex=false,
          line_number=233,
          alias="",
        },
        {
          name="SLASH",
          pattern="/",
          is_regex=false,
          line_number=234,
          alias="",
        },
        {
          name="PERCENT",
          pattern="%",
          is_regex=false,
          line_number=235,
          alias="",
        },
        {
          name="LESS_THAN",
          pattern="<",
          is_regex=false,
          line_number=236,
          alias="",
        },
        {
          name="GREATER_THAN",
          pattern=">",
          is_regex=false,
          line_number=237,
          alias="",
        },
        {
          name="BANG",
          pattern="!",
          is_regex=false,
          line_number=238,
          alias="",
        },
        {
          name="AMPERSAND",
          pattern="&",
          is_regex=false,
          line_number=239,
          alias="",
        },
        {
          name="PIPE",
          pattern="|",
          is_regex=false,
          line_number=240,
          alias="",
        },
        {
          name="CARET",
          pattern="^",
          is_regex=false,
          line_number=241,
          alias="",
        },
        {
          name="TILDE",
          pattern="~",
          is_regex=false,
          line_number=242,
          alias="",
        },
        {
          name="QUESTION",
          pattern="?",
          is_regex=false,
          line_number=243,
          alias="",
        },
        {
          name="LPAREN",
          pattern="(",
          is_regex=false,
          line_number=251,
          alias="",
        },
        {
          name="RPAREN",
          pattern=")",
          is_regex=false,
          line_number=252,
          alias="",
        },
        {
          name="LBRACE",
          pattern="{",
          is_regex=false,
          line_number=253,
          alias="",
        },
        {
          name="RBRACE",
          pattern="}",
          is_regex=false,
          line_number=254,
          alias="",
        },
        {
          name="LBRACKET",
          pattern="[",
          is_regex=false,
          line_number=255,
          alias="",
        },
        {
          name="RBRACKET",
          pattern="]",
          is_regex=false,
          line_number=256,
          alias="",
        },
        {
          name="SEMICOLON",
          pattern=";",
          is_regex=false,
          line_number=257,
          alias="",
        },
        {
          name="COMMA",
          pattern=",",
          is_regex=false,
          line_number=258,
          alias="",
        },
        {
          name="DOT",
          pattern=".",
          is_regex=false,
          line_number=259,
          alias="",
        },
        {
          name="COLON",
          pattern=":",
          is_regex=false,
          line_number=260,
          alias="",
        },
      }
  g.keywords = {"abstract", "assert", "boolean", "break", "byte", "case", "catch", "char", "class", "continue", "default", "do", "double", "else", "enum", "extends", "final", "finally", "float", "for", "if", "implements", "import", "instanceof", "int", "interface", "long", "native", "new", "package", "private", "protected", "public", "return", "short", "static", "strictfp", "super", "switch", "synchronized", "this", "throw", "throws", "transient", "try", "void", "volatile", "while", "true", "false", "null"}
  g.mode = ""
  g.escape_mode = ""
  g.skip_definitions = {
        {
          name="WHITESPACE",
          pattern="[ \\t\\r\\n\\v\\f]+",
          is_regex=true,
          line_number=367,
          alias="",
        },
        {
          name="LINE_COMMENT",
          pattern="\\/\\/[^\\n]*",
          is_regex=true,
          line_number=368,
          alias="",
        },
        {
          name="BLOCK_COMMENT",
          pattern="\\/\\*([^*]|\\*[^\\/])*\\*\\/",
          is_regex=true,
          line_number=369,
          alias="",
        },
      }
  g.reserved_keywords = {"const", "goto"}
  g.context_keywords = {}
  g.layout_keywords = {}
  g.soft_keywords = {}
  g.error_definitions = {
        {
          name="BAD_STRING",
          pattern="\"[^\"]*$",
          is_regex=true,
          line_number=380,
          alias="",
        },
        {
          name="BAD_CHAR",
          pattern="'[^']*$",
          is_regex=true,
          line_number=381,
          alias="",
        },
      }
  g.groups = {}
  g.case_sensitive = true
  g.version = 0
  g.case_insensitive = false
  return g
end

return { token_grammar = token_grammar }
