-- AUTO-GENERATED FILE — DO NOT EDIT
-- Source: java1.0.tokens
-- Regenerate with: grammar-tools compile-tokens java1.0.tokens
--
-- This file embeds a TokenGrammar as native Lua data structures.
-- Call token_grammar() instead of reading and parsing the .tokens file.

local gt = require("coding_adventures.grammar_tools")

local function token_grammar()
  local g = gt.TokenGrammar.new()
  g.definitions = {
        {
          name="NAME",
          pattern="[a-zA-Z_$][a-zA-Z0-9_$]*",
          is_regex=true,
          line_number=62,
          alias="",
        },
        {
          name="HEX_NUMBER",
          pattern="0[xX][0-9a-fA-F]+[lL]?",
          is_regex=true,
          line_number=86,
          alias="NUMBER",
        },
        {
          name="OCTAL_NUMBER",
          pattern="0[0-7]+[lL]?",
          is_regex=true,
          line_number=87,
          alias="NUMBER",
        },
        {
          name="FLOAT_NUMBER",
          pattern="[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?[fFdD]?",
          is_regex=true,
          line_number=88,
          alias="NUMBER",
        },
        {
          name="LEADING_DOT_FLOAT",
          pattern="\\.[0-9]+([eE][+-]?[0-9]+)?[fFdD]?",
          is_regex=true,
          line_number=89,
          alias="NUMBER",
        },
        {
          name="SCI_NUMBER",
          pattern="[0-9]+[eE][+-]?[0-9]+[fFdD]?",
          is_regex=true,
          line_number=90,
          alias="NUMBER",
        },
        {
          name="LONG_NUMBER",
          pattern="[0-9]+[lL]",
          is_regex=true,
          line_number=91,
          alias="NUMBER",
        },
        {
          name="FLOAT_SUFFIX",
          pattern="[0-9]+[fFdD]",
          is_regex=true,
          line_number=92,
          alias="NUMBER",
        },
        {
          name="INT_NUMBER",
          pattern="[0-9]+",
          is_regex=true,
          line_number=93,
          alias="NUMBER",
        },
        {
          name="STRING",
          pattern="\"([^\"\\\\]|\\\\.)*\"",
          is_regex=true,
          line_number=123,
          alias="",
        },
        {
          name="CHAR",
          pattern="'([^'\\\\]|\\\\.)*'",
          is_regex=true,
          line_number=124,
          alias="",
        },
        {
          name="UNSIGNED_RIGHT_SHIFT_EQUALS",
          pattern=">>>=",
          is_regex=false,
          line_number=139,
          alias="",
        },
        {
          name="UNSIGNED_RIGHT_SHIFT",
          pattern=">>>",
          is_regex=false,
          line_number=140,
          alias="",
        },
        {
          name="LEFT_SHIFT_EQUALS",
          pattern="<<=",
          is_regex=false,
          line_number=141,
          alias="",
        },
        {
          name="RIGHT_SHIFT_EQUALS",
          pattern=">>=",
          is_regex=false,
          line_number=142,
          alias="",
        },
        {
          name="EQUALS_EQUALS",
          pattern="==",
          is_regex=false,
          line_number=143,
          alias="",
        },
        {
          name="NOT_EQUALS",
          pattern="!=",
          is_regex=false,
          line_number=144,
          alias="",
        },
        {
          name="LESS_EQUALS",
          pattern="<=",
          is_regex=false,
          line_number=145,
          alias="",
        },
        {
          name="GREATER_EQUALS",
          pattern=">=",
          is_regex=false,
          line_number=146,
          alias="",
        },
        {
          name="AND_AND",
          pattern="&&",
          is_regex=false,
          line_number=147,
          alias="",
        },
        {
          name="OR_OR",
          pattern="||",
          is_regex=false,
          line_number=148,
          alias="",
        },
        {
          name="PLUS_PLUS",
          pattern="++",
          is_regex=false,
          line_number=149,
          alias="",
        },
        {
          name="MINUS_MINUS",
          pattern="--",
          is_regex=false,
          line_number=150,
          alias="",
        },
        {
          name="PLUS_EQUALS",
          pattern="+=",
          is_regex=false,
          line_number=151,
          alias="",
        },
        {
          name="MINUS_EQUALS",
          pattern="-=",
          is_regex=false,
          line_number=152,
          alias="",
        },
        {
          name="STAR_EQUALS",
          pattern="*=",
          is_regex=false,
          line_number=153,
          alias="",
        },
        {
          name="SLASH_EQUALS",
          pattern="/=",
          is_regex=false,
          line_number=154,
          alias="",
        },
        {
          name="PERCENT_EQUALS",
          pattern="%=",
          is_regex=false,
          line_number=155,
          alias="",
        },
        {
          name="AMPERSAND_EQUALS",
          pattern="&=",
          is_regex=false,
          line_number=156,
          alias="",
        },
        {
          name="PIPE_EQUALS",
          pattern="|=",
          is_regex=false,
          line_number=157,
          alias="",
        },
        {
          name="CARET_EQUALS",
          pattern="^=",
          is_regex=false,
          line_number=158,
          alias="",
        },
        {
          name="LEFT_SHIFT",
          pattern="<<",
          is_regex=false,
          line_number=159,
          alias="",
        },
        {
          name="RIGHT_SHIFT",
          pattern=">>",
          is_regex=false,
          line_number=160,
          alias="",
        },
        {
          name="EQUALS",
          pattern="=",
          is_regex=false,
          line_number=172,
          alias="",
        },
        {
          name="PLUS",
          pattern="+",
          is_regex=false,
          line_number=173,
          alias="",
        },
        {
          name="MINUS",
          pattern="-",
          is_regex=false,
          line_number=174,
          alias="",
        },
        {
          name="STAR",
          pattern="*",
          is_regex=false,
          line_number=175,
          alias="",
        },
        {
          name="SLASH",
          pattern="/",
          is_regex=false,
          line_number=176,
          alias="",
        },
        {
          name="PERCENT",
          pattern="%",
          is_regex=false,
          line_number=177,
          alias="",
        },
        {
          name="LESS_THAN",
          pattern="<",
          is_regex=false,
          line_number=178,
          alias="",
        },
        {
          name="GREATER_THAN",
          pattern=">",
          is_regex=false,
          line_number=179,
          alias="",
        },
        {
          name="BANG",
          pattern="!",
          is_regex=false,
          line_number=180,
          alias="",
        },
        {
          name="AMPERSAND",
          pattern="&",
          is_regex=false,
          line_number=181,
          alias="",
        },
        {
          name="PIPE",
          pattern="|",
          is_regex=false,
          line_number=182,
          alias="",
        },
        {
          name="CARET",
          pattern="^",
          is_regex=false,
          line_number=183,
          alias="",
        },
        {
          name="TILDE",
          pattern="~",
          is_regex=false,
          line_number=184,
          alias="",
        },
        {
          name="QUESTION",
          pattern="?",
          is_regex=false,
          line_number=185,
          alias="",
        },
        {
          name="LPAREN",
          pattern="(",
          is_regex=false,
          line_number=195,
          alias="",
        },
        {
          name="RPAREN",
          pattern=")",
          is_regex=false,
          line_number=196,
          alias="",
        },
        {
          name="LBRACE",
          pattern="{",
          is_regex=false,
          line_number=197,
          alias="",
        },
        {
          name="RBRACE",
          pattern="}",
          is_regex=false,
          line_number=198,
          alias="",
        },
        {
          name="LBRACKET",
          pattern="[",
          is_regex=false,
          line_number=199,
          alias="",
        },
        {
          name="RBRACKET",
          pattern="]",
          is_regex=false,
          line_number=200,
          alias="",
        },
        {
          name="SEMICOLON",
          pattern=";",
          is_regex=false,
          line_number=201,
          alias="",
        },
        {
          name="COMMA",
          pattern=",",
          is_regex=false,
          line_number=202,
          alias="",
        },
        {
          name="DOT",
          pattern=".",
          is_regex=false,
          line_number=203,
          alias="",
        },
        {
          name="COLON",
          pattern=":",
          is_regex=false,
          line_number=204,
          alias="",
        },
      }
  g.keywords = {"abstract", "boolean", "break", "byte", "case", "catch", "char", "class", "continue", "default", "do", "double", "else", "extends", "final", "finally", "float", "for", "if", "implements", "import", "instanceof", "int", "interface", "long", "native", "new", "package", "private", "protected", "public", "return", "short", "static", "super", "switch", "synchronized", "this", "throw", "throws", "transient", "try", "void", "volatile", "while", "true", "false", "null"}
  g.mode = ""
  g.escape_mode = ""
  g.skip_definitions = {
        {
          name="WHITESPACE",
          pattern="[ \\t\\r\\n\\v\\f]+",
          is_regex=true,
          line_number=321,
          alias="",
        },
        {
          name="LINE_COMMENT",
          pattern="\\/\\/[^\\n]*",
          is_regex=true,
          line_number=322,
          alias="",
        },
        {
          name="BLOCK_COMMENT",
          pattern="\\/\\*([^*]|\\*[^\\/])*\\*\\/",
          is_regex=true,
          line_number=323,
          alias="",
        },
      }
  g.reserved_keywords = {"const", "goto"}
  g.context_keywords = {}
  g.layout_keywords = {}
  g.soft_keywords = {}
  g.error_definitions = {
        {
          name="BAD_STRING",
          pattern="\"[^\"]*$",
          is_regex=true,
          line_number=334,
          alias="",
        },
        {
          name="BAD_CHAR",
          pattern="'[^']*$",
          is_regex=true,
          line_number=335,
          alias="",
        },
      }
  g.groups = {}
  g.case_sensitive = true
  g.version = 0
  g.case_insensitive = false
  return g
end

return { token_grammar = token_grammar }
