// AUTO-GENERATED FILE — DO NOT EDIT
// Source: starlark.tokens
// Regenerate with: grammar-tools compile-tokens starlark.tokens
//
// This file embeds a TokenGrammar as native TypeScript object literals.
// Import it directly instead of reading and parsing the .tokens file at
// runtime.

import type { TokenGrammar } from "@coding-adventures/grammar-tools";

export const TOKEN_GRAMMAR: TokenGrammar = {
  version: 1,
  caseInsensitive: false,
  caseSensitive: true,
  definitions: [
    {
      name: "STRING_RAW_TRIPLE_DQ",
      pattern: "[rR][bB]?\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"|[bB][rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 84,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_TRIPLE_SQ",
      pattern: "[rR][bB]?'''([^'\\\\]|\\\\.|\\n)*'''|[bB][rR]'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 85,
      alias: "STRING",
    },
    {
      name: "STRING_TRIPLE_DQ",
      pattern: "[bB]?\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
      isRegex: true,
      lineNumber: 86,
      alias: "STRING",
    },
    {
      name: "STRING_TRIPLE_SQ",
      pattern: "[bB]?'''([^'\\\\]|\\\\.|\\n)*'''",
      isRegex: true,
      lineNumber: 87,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_DQ",
      pattern: "[rR][bB]?\"([^\"\\\\]|\\\\.)*\"|[bB][rR]\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 90,
      alias: "STRING",
    },
    {
      name: "STRING_RAW_SQ",
      pattern: "[rR][bB]?'([^'\\\\]|\\\\.)*'|[bB][rR]'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 91,
      alias: "STRING",
    },
    {
      name: "STRING_DQ",
      pattern: "[bB]?\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 92,
      alias: "STRING",
    },
    {
      name: "STRING_SQ",
      pattern: "[bB]?'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 93,
      alias: "STRING",
    },
    {
      name: "FLOAT_EXP",
      pattern: "[0-9]+[eE][+-]?[0-9]+",
      isRegex: true,
      lineNumber: 110,
      alias: "FLOAT",
    },
    {
      name: "FLOAT_DOT",
      pattern: "\\.[0-9]+([eE][+-]?[0-9]+)?",
      isRegex: true,
      lineNumber: 111,
      alias: "FLOAT",
    },
    {
      name: "FLOAT",
      pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?",
      isRegex: true,
      lineNumber: 112,
      alias: "FLOAT",
    },
    {
      name: "INT_HEX",
      pattern: "0[xX][0-9a-fA-F]+",
      isRegex: true,
      lineNumber: 115,
      alias: "INT",
    },
    {
      name: "INT_OCT",
      pattern: "0[oO][0-7]+",
      isRegex: true,
      lineNumber: 116,
      alias: "INT",
    },
    {
      name: "INT",
      pattern: "[0-9]+",
      isRegex: true,
      lineNumber: 117,
    },
    {
      name: "NAME",
      pattern: "[a-zA-Z_][a-zA-Z0-9_]*",
      isRegex: true,
      lineNumber: 127,
    },
    {
      name: "DOUBLE_STAR_EQUALS",
      pattern: "**=",
      isRegex: false,
      lineNumber: 136,
    },
    {
      name: "LEFT_SHIFT_EQUALS",
      pattern: "<<=",
      isRegex: false,
      lineNumber: 137,
    },
    {
      name: "RIGHT_SHIFT_EQUALS",
      pattern: ">>=",
      isRegex: false,
      lineNumber: 138,
    },
    {
      name: "FLOOR_DIV_EQUALS",
      pattern: "//=",
      isRegex: false,
      lineNumber: 139,
    },
    {
      name: "DOUBLE_STAR",
      pattern: "**",
      isRegex: false,
      lineNumber: 148,
    },
    {
      name: "FLOOR_DIV",
      pattern: "//",
      isRegex: false,
      lineNumber: 149,
    },
    {
      name: "LEFT_SHIFT",
      pattern: "<<",
      isRegex: false,
      lineNumber: 150,
    },
    {
      name: "RIGHT_SHIFT",
      pattern: ">>",
      isRegex: false,
      lineNumber: 151,
    },
    {
      name: "EQUALS_EQUALS",
      pattern: "==",
      isRegex: false,
      lineNumber: 152,
    },
    {
      name: "NOT_EQUALS",
      pattern: "!=",
      isRegex: false,
      lineNumber: 153,
    },
    {
      name: "LESS_EQUALS",
      pattern: "<=",
      isRegex: false,
      lineNumber: 154,
    },
    {
      name: "GREATER_EQUALS",
      pattern: ">=",
      isRegex: false,
      lineNumber: 155,
    },
    {
      name: "PLUS_EQUALS",
      pattern: "+=",
      isRegex: false,
      lineNumber: 156,
    },
    {
      name: "MINUS_EQUALS",
      pattern: "-=",
      isRegex: false,
      lineNumber: 157,
    },
    {
      name: "STAR_EQUALS",
      pattern: "*=",
      isRegex: false,
      lineNumber: 158,
    },
    {
      name: "SLASH_EQUALS",
      pattern: "/=",
      isRegex: false,
      lineNumber: 159,
    },
    {
      name: "PERCENT_EQUALS",
      pattern: "%=",
      isRegex: false,
      lineNumber: 160,
    },
    {
      name: "AMP_EQUALS",
      pattern: "&=",
      isRegex: false,
      lineNumber: 161,
    },
    {
      name: "PIPE_EQUALS",
      pattern: "|=",
      isRegex: false,
      lineNumber: 162,
    },
    {
      name: "CARET_EQUALS",
      pattern: "^=",
      isRegex: false,
      lineNumber: 163,
    },
    {
      name: "PLUS",
      pattern: "+",
      isRegex: false,
      lineNumber: 169,
    },
    {
      name: "MINUS",
      pattern: "-",
      isRegex: false,
      lineNumber: 170,
    },
    {
      name: "STAR",
      pattern: "*",
      isRegex: false,
      lineNumber: 171,
    },
    {
      name: "SLASH",
      pattern: "/",
      isRegex: false,
      lineNumber: 172,
    },
    {
      name: "PERCENT",
      pattern: "%",
      isRegex: false,
      lineNumber: 173,
    },
    {
      name: "EQUALS",
      pattern: "=",
      isRegex: false,
      lineNumber: 174,
    },
    {
      name: "LESS_THAN",
      pattern: "<",
      isRegex: false,
      lineNumber: 175,
    },
    {
      name: "GREATER_THAN",
      pattern: ">",
      isRegex: false,
      lineNumber: 176,
    },
    {
      name: "AMP",
      pattern: "&",
      isRegex: false,
      lineNumber: 177,
    },
    {
      name: "PIPE",
      pattern: "|",
      isRegex: false,
      lineNumber: 178,
    },
    {
      name: "CARET",
      pattern: "^",
      isRegex: false,
      lineNumber: 179,
    },
    {
      name: "TILDE",
      pattern: "~",
      isRegex: false,
      lineNumber: 180,
    },
    {
      name: "LPAREN",
      pattern: "(",
      isRegex: false,
      lineNumber: 186,
    },
    {
      name: "RPAREN",
      pattern: ")",
      isRegex: false,
      lineNumber: 187,
    },
    {
      name: "LBRACKET",
      pattern: "[",
      isRegex: false,
      lineNumber: 188,
    },
    {
      name: "RBRACKET",
      pattern: "]",
      isRegex: false,
      lineNumber: 189,
    },
    {
      name: "LBRACE",
      pattern: "{",
      isRegex: false,
      lineNumber: 190,
    },
    {
      name: "RBRACE",
      pattern: "}",
      isRegex: false,
      lineNumber: 191,
    },
    {
      name: "COMMA",
      pattern: ",",
      isRegex: false,
      lineNumber: 192,
    },
    {
      name: "COLON",
      pattern: ":",
      isRegex: false,
      lineNumber: 193,
    },
    {
      name: "SEMICOLON",
      pattern: ";",
      isRegex: false,
      lineNumber: 194,
    },
    {
      name: "DOT",
      pattern: ".",
      isRegex: false,
      lineNumber: 195,
    },
  ],
  keywords: ["and","break","continue","def","elif","else","for","if","in","lambda","load","not","or","pass","return","True","False","None"],
  mode: "indentation",
  escapeMode: undefined,
  skipDefinitions: [
    {
      name: "COMMENT",
      pattern: "#[^\\n]*",
      isRegex: true,
      lineNumber: 65,
    },
    {
      name: "WHITESPACE",
      pattern: "[ \\t]+",
      isRegex: true,
      lineNumber: 66,
    },
  ],
  reservedKeywords: ["as","assert","async","await","class","del","except","finally","from","global","import","is","nonlocal","raise","try","while","with","yield"],
  layoutKeywords: [],
  contextKeywords: [],
  errorDefinitions: [],
  groups: {},
};
