// AUTO-GENERATED FILE - DO NOT EDIT
import type { TokenGrammar } from "@coding-adventures/grammar-tools";

export const StarlarkTokens: TokenGrammar = {
  definitions: [
    { name: "STRING_RAW_TRIPLE_DQ", pattern: "[rR][bB]?\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"|[bB][rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"", isRegex: true, lineNumber: 70, alias: "STRING" },
    { name: "STRING_RAW_TRIPLE_SQ", pattern: "[rR][bB]?'''([^'\\\\]|\\\\.|\\n)*'''|[bB][rR]'''([^'\\\\]|\\\\.|\\n)*'''", isRegex: true, lineNumber: 71, alias: "STRING" },
    { name: "STRING_TRIPLE_DQ", pattern: "[bB]?\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"", isRegex: true, lineNumber: 72, alias: "STRING" },
    { name: "STRING_TRIPLE_SQ", pattern: "[bB]?'''([^'\\\\]|\\\\.|\\n)*'''", isRegex: true, lineNumber: 73, alias: "STRING" },
    { name: "STRING_RAW_DQ", pattern: "[rR][bB]?\"([^\"\\\\]|\\\\.)*\"|[bB][rR]\"([^\"\\\\]|\\\\.)*\"", isRegex: true, lineNumber: 76, alias: "STRING" },
    { name: "STRING_RAW_SQ", pattern: "[rR][bB]?'([^'\\\\]|\\\\.)*'|[bB][rR]'([^'\\\\]|\\\\.)*'", isRegex: true, lineNumber: 77, alias: "STRING" },
    { name: "STRING_DQ", pattern: "[bB]?\"([^\"\\\\]|\\\\.)*\"", isRegex: true, lineNumber: 78, alias: "STRING" },
    { name: "STRING_SQ", pattern: "[bB]?'([^'\\\\]|\\\\.)*'", isRegex: true, lineNumber: 79, alias: "STRING" },
    { name: "FLOAT", pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?|\\.[0-9]+([eE][+-]?[0-9]+)?|[0-9]+[eE][+-]?[0-9]+", isRegex: true, lineNumber: 92 },
    { name: "INT_HEX", pattern: "0[xX][0-9a-fA-F]+", isRegex: true, lineNumber: 95, alias: "INT" },
    { name: "INT_OCT", pattern: "0[oO][0-7]+", isRegex: true, lineNumber: 96, alias: "INT" },
    { name: "INT", pattern: "[0-9]+", isRegex: true, lineNumber: 97 },
    { name: "NAME", pattern: "[a-zA-Z_][a-zA-Z0-9_]*", isRegex: true, lineNumber: 107 },
    { name: "DOUBLE_STAR_EQUALS", pattern: "**=", isRegex: false, lineNumber: 116 },
    { name: "LEFT_SHIFT_EQUALS", pattern: "<<=", isRegex: false, lineNumber: 117 },
    { name: "RIGHT_SHIFT_EQUALS", pattern: ">>=", isRegex: false, lineNumber: 118 },
    { name: "FLOOR_DIV_EQUALS", pattern: "//=", isRegex: false, lineNumber: 119 },
    { name: "DOUBLE_STAR", pattern: "**", isRegex: false, lineNumber: 128 },
    { name: "FLOOR_DIV", pattern: "//", isRegex: false, lineNumber: 129 },
    { name: "LEFT_SHIFT", pattern: "<<", isRegex: false, lineNumber: 130 },
    { name: "RIGHT_SHIFT", pattern: ">>", isRegex: false, lineNumber: 131 },
    { name: "EQUALS_EQUALS", pattern: "==", isRegex: false, lineNumber: 132 },
    { name: "NOT_EQUALS", pattern: "!=", isRegex: false, lineNumber: 133 },
    { name: "LESS_EQUALS", pattern: "<=", isRegex: false, lineNumber: 134 },
    { name: "GREATER_EQUALS", pattern: ">=", isRegex: false, lineNumber: 135 },
    { name: "PLUS_EQUALS", pattern: "+=", isRegex: false, lineNumber: 136 },
    { name: "MINUS_EQUALS", pattern: "-=", isRegex: false, lineNumber: 137 },
    { name: "STAR_EQUALS", pattern: "*=", isRegex: false, lineNumber: 138 },
    { name: "SLASH_EQUALS", pattern: "/=", isRegex: false, lineNumber: 139 },
    { name: "PERCENT_EQUALS", pattern: "%=", isRegex: false, lineNumber: 140 },
    { name: "AMP_EQUALS", pattern: "&=", isRegex: false, lineNumber: 141 },
    { name: "PIPE_EQUALS", pattern: "|=", isRegex: false, lineNumber: 142 },
    { name: "CARET_EQUALS", pattern: "^=", isRegex: false, lineNumber: 143 },
    { name: "PLUS", pattern: "+", isRegex: false, lineNumber: 149 },
    { name: "MINUS", pattern: "-", isRegex: false, lineNumber: 150 },
    { name: "STAR", pattern: "*", isRegex: false, lineNumber: 151 },
    { name: "SLASH", pattern: "/", isRegex: false, lineNumber: 152 },
    { name: "PERCENT", pattern: "%", isRegex: false, lineNumber: 153 },
    { name: "EQUALS", pattern: "=", isRegex: false, lineNumber: 154 },
    { name: "LESS_THAN", pattern: "<", isRegex: false, lineNumber: 155 },
    { name: "GREATER_THAN", pattern: ">", isRegex: false, lineNumber: 156 },
    { name: "AMP", pattern: "&", isRegex: false, lineNumber: 157 },
    { name: "PIPE", pattern: "|", isRegex: false, lineNumber: 158 },
    { name: "CARET", pattern: "^", isRegex: false, lineNumber: 159 },
    { name: "TILDE", pattern: "~", isRegex: false, lineNumber: 160 },
    { name: "LPAREN", pattern: "(", isRegex: false, lineNumber: 166 },
    { name: "RPAREN", pattern: ")", isRegex: false, lineNumber: 167 },
    { name: "LBRACKET", pattern: "[", isRegex: false, lineNumber: 168 },
    { name: "RBRACKET", pattern: "]", isRegex: false, lineNumber: 169 },
    { name: "LBRACE", pattern: "{", isRegex: false, lineNumber: 170 },
    { name: "RBRACE", pattern: "}", isRegex: false, lineNumber: 171 },
    { name: "COMMA", pattern: ",", isRegex: false, lineNumber: 172 },
    { name: "COLON", pattern: ":", isRegex: false, lineNumber: 173 },
    { name: "SEMICOLON", pattern: ";", isRegex: false, lineNumber: 174 },
    { name: "DOT", pattern: ".", isRegex: false, lineNumber: 175 },
  ],
  keywords: ["and","break","continue","def","elif","else","for","if","in","lambda","load","not","or","pass","return","True","False","None"],
  mode: "indentation",
  skipDefinitions: [
    { name: "COMMENT", pattern: "#[^\\n]*", isRegex: true, lineNumber: 51 },
    { name: "WHITESPACE", pattern: "[ \\t]+", isRegex: true, lineNumber: 52 },
  ],
  reservedKeywords: ["as","assert","async","await","class","del","except","finally","from","global","import","is","nonlocal","raise","try","while","with","yield"],
  version: 1,
  caseInsensitive: false
};
