# frozen_string_literal: true
# AUTO-GENERATED FILE — DO NOT EDIT
# Source: csharp9.0.tokens
# Regenerate with: grammar-tools compile-tokens csharp9.0.tokens
#
# This file embeds a TokenGrammar as native Ruby data structures.
# Downstream packages require this file directly instead of reading
# and parsing the .tokens file at runtime.

require "coding_adventures_grammar_tools"

GT = CodingAdventures::GrammarTools unless defined?(GT)

TOKEN_GRAMMAR = GT::TokenGrammar.new(
  version: 1,
  case_insensitive: false,
  case_sensitive: true,
  definitions: [
      GT::TokenDefinition.new(
        name: "NAME",
        pattern: "[a-zA-Z_][a-zA-Z0-9_]*",
        is_regex: true,
        line_number: 95,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "VERBATIM_NAME",
        pattern: "@[a-zA-Z_][a-zA-Z0-9_]*",
        is_regex: true,
        line_number: 96,
        alias_name: "NAME",
      ),
      GT::TokenDefinition.new(
        name: "BINARY_ULONG",
        pattern: "0[bB]_?[01][01_]*([uU][lL]|[lL][uU])",
        is_regex: true,
        line_number: 118,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "BINARY_LONG",
        pattern: "0[bB]_?[01][01_]*[lL]",
        is_regex: true,
        line_number: 119,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "BINARY_UINT",
        pattern: "0[bB]_?[01][01_]*[uU]",
        is_regex: true,
        line_number: 120,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "BINARY_NUMBER",
        pattern: "0[bB]_?[01][01_]*",
        is_regex: true,
        line_number: 121,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "HEX_ULONG",
        pattern: "0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*([uU][lL]|[lL][uU])",
        is_regex: true,
        line_number: 122,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "HEX_LONG",
        pattern: "0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*[lL]",
        is_regex: true,
        line_number: 123,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "HEX_UINT",
        pattern: "0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*[uU]",
        is_regex: true,
        line_number: 124,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "HEX_NUMBER",
        pattern: "0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*",
        is_regex: true,
        line_number: 125,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "DECIMAL_FLOAT",
        pattern: "[0-9][0-9_]*\\.[0-9_]*([eE][+-]?[0-9][0-9_]*)?[fFdDmM]?",
        is_regex: true,
        line_number: 126,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "LEADING_DOT_FLOAT",
        pattern: "\\.[0-9][0-9_]*([eE][+-]?[0-9][0-9_]*)?[fFdDmM]?",
        is_regex: true,
        line_number: 127,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "SCI_NUMBER",
        pattern: "[0-9][0-9_]*[eE][+-]?[0-9][0-9_]*[fFdDmM]?",
        is_regex: true,
        line_number: 128,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "ULONG_NUMBER",
        pattern: "[0-9][0-9_]*([uU][lL]|[lL][uU])",
        is_regex: true,
        line_number: 129,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "LONG_NUMBER",
        pattern: "[0-9][0-9_]*[lL]",
        is_regex: true,
        line_number: 130,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "UINT_NUMBER",
        pattern: "[0-9][0-9_]*[uU]",
        is_regex: true,
        line_number: 131,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "FLOAT_SUFFIX",
        pattern: "[0-9][0-9_]*[fFdDmM]",
        is_regex: true,
        line_number: 132,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "INT_NUMBER",
        pattern: "[0-9][0-9_]*",
        is_regex: true,
        line_number: 133,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "STRING",
        pattern: "\"([^\"\\\\]|\\\\.)*\"",
        is_regex: true,
        line_number: 155,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "VERBATIM_STRING",
        pattern: "@\"([^\"]|\"\")*\"",
        is_regex: true,
        line_number: 156,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "INTERPOLATED_STRING",
        pattern: "\\$\"([^\"\\\\{]|\\\\.|\\{\\{|\\}\\})*\"",
        is_regex: true,
        line_number: 157,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "INTERPOLATED_VERBATIM",
        pattern: "(\\$@|@\\$)\"([^\"{]|\"\"|\\{\\{|\\}\\})*\"",
        is_regex: true,
        line_number: 158,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CHAR",
        pattern: "'([^'\\\\]|\\\\.)*'",
        is_regex: true,
        line_number: 159,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "QUESTION_QUESTION_EQUALS",
        pattern: "??=",
        is_regex: false,
        line_number: 185,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NULL_CONDITIONAL_DOT",
        pattern: "?.",
        is_regex: false,
        line_number: 186,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NULL_CONDITIONAL_BRACKET",
        pattern: "?[",
        is_regex: false,
        line_number: 187,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NULL_COALESCING",
        pattern: "??",
        is_regex: false,
        line_number: 188,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LAMBDA_ARROW",
        pattern: "=>",
        is_regex: false,
        line_number: 189,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LEFT_SHIFT_EQUALS",
        pattern: "<<=",
        is_regex: false,
        line_number: 190,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RIGHT_SHIFT_EQUALS",
        pattern: ">>=",
        is_regex: false,
        line_number: 191,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DOT_DOT",
        pattern: "..",
        is_regex: false,
        line_number: 192,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQUALS_EQUALS",
        pattern: "==",
        is_regex: false,
        line_number: 193,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NOT_EQUALS",
        pattern: "!=",
        is_regex: false,
        line_number: 194,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_EQUALS",
        pattern: "<=",
        is_regex: false,
        line_number: 195,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_EQUALS",
        pattern: ">=",
        is_regex: false,
        line_number: 196,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AND_AND",
        pattern: "&&",
        is_regex: false,
        line_number: 197,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "OR_OR",
        pattern: "||",
        is_regex: false,
        line_number: 198,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS_PLUS",
        pattern: "++",
        is_regex: false,
        line_number: 199,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS_MINUS",
        pattern: "--",
        is_regex: false,
        line_number: 200,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS_EQUALS",
        pattern: "+=",
        is_regex: false,
        line_number: 201,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS_EQUALS",
        pattern: "-=",
        is_regex: false,
        line_number: 202,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR_EQUALS",
        pattern: "*=",
        is_regex: false,
        line_number: 203,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SLASH_EQUALS",
        pattern: "/=",
        is_regex: false,
        line_number: 204,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PERCENT_EQUALS",
        pattern: "%=",
        is_regex: false,
        line_number: 205,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AMPERSAND_EQUALS",
        pattern: "&=",
        is_regex: false,
        line_number: 206,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PIPE_EQUALS",
        pattern: "|=",
        is_regex: false,
        line_number: 207,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CARET_EQUALS",
        pattern: "^=",
        is_regex: false,
        line_number: 208,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LEFT_SHIFT",
        pattern: "<<",
        is_regex: false,
        line_number: 209,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RIGHT_SHIFT",
        pattern: ">>",
        is_regex: false,
        line_number: 210,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COLON_COLON",
        pattern: "::",
        is_regex: false,
        line_number: 211,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "ARROW",
        pattern: "->",
        is_regex: false,
        line_number: 212,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQUALS",
        pattern: "=",
        is_regex: false,
        line_number: 225,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS",
        pattern: "+",
        is_regex: false,
        line_number: 226,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS",
        pattern: "-",
        is_regex: false,
        line_number: 227,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR",
        pattern: "*",
        is_regex: false,
        line_number: 228,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SLASH",
        pattern: "/",
        is_regex: false,
        line_number: 229,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PERCENT",
        pattern: "%",
        is_regex: false,
        line_number: 230,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_THAN",
        pattern: "<",
        is_regex: false,
        line_number: 231,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_THAN",
        pattern: ">",
        is_regex: false,
        line_number: 232,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BANG",
        pattern: "!",
        is_regex: false,
        line_number: 233,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AMPERSAND",
        pattern: "&",
        is_regex: false,
        line_number: 234,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PIPE",
        pattern: "|",
        is_regex: false,
        line_number: 235,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CARET",
        pattern: "^",
        is_regex: false,
        line_number: 236,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "TILDE",
        pattern: "~",
        is_regex: false,
        line_number: 237,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "QUESTION",
        pattern: "?",
        is_regex: false,
        line_number: 238,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LPAREN",
        pattern: "(",
        is_regex: false,
        line_number: 256,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RPAREN",
        pattern: ")",
        is_regex: false,
        line_number: 257,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACE",
        pattern: "{",
        is_regex: false,
        line_number: 258,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACE",
        pattern: "}",
        is_regex: false,
        line_number: 259,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACKET",
        pattern: "[",
        is_regex: false,
        line_number: 260,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACKET",
        pattern: "]",
        is_regex: false,
        line_number: 261,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SEMICOLON",
        pattern: ";",
        is_regex: false,
        line_number: 262,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COMMA",
        pattern: ",",
        is_regex: false,
        line_number: 263,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DOT",
        pattern: ".",
        is_regex: false,
        line_number: 264,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COLON",
        pattern: ":",
        is_regex: false,
        line_number: 265,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_NULLABLE",
        pattern: "#\\s*nullable\\b[^\\n]*",
        is_regex: true,
        line_number: 420,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_IF",
        pattern: "#\\s*if\\b[^\\n]*",
        is_regex: true,
        line_number: 421,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_ELIF",
        pattern: "#\\s*elif\\b[^\\n]*",
        is_regex: true,
        line_number: 422,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_ELSE",
        pattern: "#\\s*else\\b[^\\n]*",
        is_regex: true,
        line_number: 423,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_ENDIF",
        pattern: "#\\s*endif\\b[^\\n]*",
        is_regex: true,
        line_number: 424,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_DEFINE",
        pattern: "#\\s*define\\b[^\\n]*",
        is_regex: true,
        line_number: 425,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_UNDEF",
        pattern: "#\\s*undef\\b[^\\n]*",
        is_regex: true,
        line_number: 426,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_REGION",
        pattern: "#\\s*region\\b[^\\n]*",
        is_regex: true,
        line_number: 427,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_ENDREGION",
        pattern: "#\\s*endregion\\b[^\\n]*",
        is_regex: true,
        line_number: 428,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_ERROR",
        pattern: "#\\s*error\\b[^\\n]*",
        is_regex: true,
        line_number: 429,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_WARNING",
        pattern: "#\\s*warning\\b[^\\n]*",
        is_regex: true,
        line_number: 430,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_LINE",
        pattern: "#\\s*line\\b[^\\n]*",
        is_regex: true,
        line_number: 431,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_PRAGMA",
        pattern: "#\\s*pragma\\b[^\\n]*",
        is_regex: true,
        line_number: 432,
        alias_name: nil,
      ),
    ],
  keywords: ["abstract", "as", "async", "await", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else", "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock", "long", "namespace", "new", "null", "object", "operator", "out", "override", "params", "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual", "void", "volatile", "while"],
  mode: nil,
  escape_mode: nil,
  skip_definitions: [
      GT::TokenDefinition.new(
        name: "WHITESPACE",
        pattern: "[ \\t\\r\\n\\v\\f]+",
        is_regex: true,
        line_number: 401,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LINE_COMMENT",
        pattern: "\\/\\/[^\\n]*",
        is_regex: true,
        line_number: 402,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BLOCK_COMMENT",
        pattern: "\\/\\*([^*]|\\*[^\\/])*\\*\\/",
        is_regex: true,
        line_number: 403,
        alias_name: nil,
      ),
    ],
  reserved_keywords: [],
  error_definitions: [
      GT::TokenDefinition.new(
        name: "BAD_STRING",
        pattern: "\"[^\"]*$",
        is_regex: true,
        line_number: 439,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BAD_CHAR",
        pattern: "'[^']*$",
        is_regex: true,
        line_number: 440,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BAD_VERBATIM_STRING",
        pattern: "@\"([^\"]|\"\")*$",
        is_regex: true,
        line_number: 441,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BAD_INTERPOLATED_STRING",
        pattern: "\\$\"([^\"\\\\{]|\\\\.)*$",
        is_regex: true,
        line_number: 442,
        alias_name: nil,
      ),
    ],
  groups: {},
  layout_keywords: [],
  context_keywords: [],
  soft_keywords: [],
)
