# frozen_string_literal: true
# AUTO-GENERATED FILE — DO NOT EDIT
# Source: csharp5.0.tokens
# Regenerate with: grammar-tools compile-tokens csharp5.0.tokens
#
# This file embeds a TokenGrammar as native Ruby data structures.
# Downstream packages require this file directly instead of reading
# and parsing the .tokens file at runtime.

require "coding_adventures_grammar_tools"

GT = CodingAdventures::GrammarTools unless defined?(GT)

TOKEN_GRAMMAR = GT::TokenGrammar.new(
  version: 1,
  case_insensitive: false,
  case_sensitive: true,
  definitions: [
      GT::TokenDefinition.new(
        name: "NAME",
        pattern: "[a-zA-Z_][a-zA-Z0-9_]*",
        is_regex: true,
        line_number: 99,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "VERBATIM_NAME",
        pattern: "@[a-zA-Z_][a-zA-Z0-9_]*",
        is_regex: true,
        line_number: 100,
        alias_name: "NAME",
      ),
      GT::TokenDefinition.new(
        name: "HEX_ULONG",
        pattern: "0[xX][0-9a-fA-F]+([uU][lL]|[lL][uU])",
        is_regex: true,
        line_number: 127,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "HEX_LONG",
        pattern: "0[xX][0-9a-fA-F]+[lL]",
        is_regex: true,
        line_number: 128,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "HEX_UINT",
        pattern: "0[xX][0-9a-fA-F]+[uU]",
        is_regex: true,
        line_number: 129,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "HEX_NUMBER",
        pattern: "0[xX][0-9a-fA-F]+",
        is_regex: true,
        line_number: 130,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "DECIMAL_FLOAT",
        pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?[fFdDmM]?",
        is_regex: true,
        line_number: 131,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "LEADING_DOT_FLOAT",
        pattern: "\\.[0-9]+([eE][+-]?[0-9]+)?[fFdDmM]?",
        is_regex: true,
        line_number: 132,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "SCI_NUMBER",
        pattern: "[0-9]+[eE][+-]?[0-9]+[fFdDmM]?",
        is_regex: true,
        line_number: 133,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "ULONG_NUMBER",
        pattern: "[0-9]+([uU][lL]|[lL][uU])",
        is_regex: true,
        line_number: 134,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "LONG_NUMBER",
        pattern: "[0-9]+[lL]",
        is_regex: true,
        line_number: 135,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "UINT_NUMBER",
        pattern: "[0-9]+[uU]",
        is_regex: true,
        line_number: 136,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "FLOAT_SUFFIX",
        pattern: "[0-9]+[fFdDmM]",
        is_regex: true,
        line_number: 137,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "INT_NUMBER",
        pattern: "[0-9]+",
        is_regex: true,
        line_number: 138,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "STRING",
        pattern: "\"([^\"\\\\]|\\\\.)*\"",
        is_regex: true,
        line_number: 152,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "VERBATIM_STRING",
        pattern: "@\"([^\"]|\"\")*\"",
        is_regex: true,
        line_number: 153,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CHAR",
        pattern: "'([^'\\\\]|\\\\.)*'",
        is_regex: true,
        line_number: 154,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NULL_COALESCE",
        pattern: "??",
        is_regex: false,
        line_number: 176,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LEFT_SHIFT_EQUALS",
        pattern: "<<=",
        is_regex: false,
        line_number: 177,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RIGHT_SHIFT_EQUALS",
        pattern: ">>=",
        is_regex: false,
        line_number: 178,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LAMBDA",
        pattern: "=>",
        is_regex: false,
        line_number: 179,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQUALS_EQUALS",
        pattern: "==",
        is_regex: false,
        line_number: 180,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NOT_EQUALS",
        pattern: "!=",
        is_regex: false,
        line_number: 181,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_EQUALS",
        pattern: "<=",
        is_regex: false,
        line_number: 182,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_EQUALS",
        pattern: ">=",
        is_regex: false,
        line_number: 183,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AND_AND",
        pattern: "&&",
        is_regex: false,
        line_number: 184,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "OR_OR",
        pattern: "||",
        is_regex: false,
        line_number: 185,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS_PLUS",
        pattern: "++",
        is_regex: false,
        line_number: 186,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS_MINUS",
        pattern: "--",
        is_regex: false,
        line_number: 187,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS_EQUALS",
        pattern: "+=",
        is_regex: false,
        line_number: 188,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS_EQUALS",
        pattern: "-=",
        is_regex: false,
        line_number: 189,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR_EQUALS",
        pattern: "*=",
        is_regex: false,
        line_number: 190,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SLASH_EQUALS",
        pattern: "/=",
        is_regex: false,
        line_number: 191,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PERCENT_EQUALS",
        pattern: "%=",
        is_regex: false,
        line_number: 192,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AMPERSAND_EQUALS",
        pattern: "&=",
        is_regex: false,
        line_number: 193,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PIPE_EQUALS",
        pattern: "|=",
        is_regex: false,
        line_number: 194,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CARET_EQUALS",
        pattern: "^=",
        is_regex: false,
        line_number: 195,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LEFT_SHIFT",
        pattern: "<<",
        is_regex: false,
        line_number: 196,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RIGHT_SHIFT",
        pattern: ">>",
        is_regex: false,
        line_number: 197,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NAMESPACE_ALIAS",
        pattern: "::",
        is_regex: false,
        line_number: 198,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "ARROW",
        pattern: "->",
        is_regex: false,
        line_number: 199,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQUALS",
        pattern: "=",
        is_regex: false,
        line_number: 214,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS",
        pattern: "+",
        is_regex: false,
        line_number: 215,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS",
        pattern: "-",
        is_regex: false,
        line_number: 216,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR",
        pattern: "*",
        is_regex: false,
        line_number: 217,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SLASH",
        pattern: "/",
        is_regex: false,
        line_number: 218,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PERCENT",
        pattern: "%",
        is_regex: false,
        line_number: 219,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_THAN",
        pattern: "<",
        is_regex: false,
        line_number: 220,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_THAN",
        pattern: ">",
        is_regex: false,
        line_number: 221,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BANG",
        pattern: "!",
        is_regex: false,
        line_number: 222,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AMPERSAND",
        pattern: "&",
        is_regex: false,
        line_number: 223,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PIPE",
        pattern: "|",
        is_regex: false,
        line_number: 224,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CARET",
        pattern: "^",
        is_regex: false,
        line_number: 225,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "TILDE",
        pattern: "~",
        is_regex: false,
        line_number: 226,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "QUESTION",
        pattern: "?",
        is_regex: false,
        line_number: 227,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LPAREN",
        pattern: "(",
        is_regex: false,
        line_number: 233,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RPAREN",
        pattern: ")",
        is_regex: false,
        line_number: 234,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACE",
        pattern: "{",
        is_regex: false,
        line_number: 235,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACE",
        pattern: "}",
        is_regex: false,
        line_number: 236,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACKET",
        pattern: "[",
        is_regex: false,
        line_number: 237,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACKET",
        pattern: "]",
        is_regex: false,
        line_number: 238,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SEMICOLON",
        pattern: ";",
        is_regex: false,
        line_number: 239,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COMMA",
        pattern: ",",
        is_regex: false,
        line_number: 240,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DOT",
        pattern: ".",
        is_regex: false,
        line_number: 241,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COLON",
        pattern: ":",
        is_regex: false,
        line_number: 242,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_IF",
        pattern: "#\\s*if\\b[^\\n]*",
        is_regex: true,
        line_number: 399,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_ELIF",
        pattern: "#\\s*elif\\b[^\\n]*",
        is_regex: true,
        line_number: 400,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_ELSE",
        pattern: "#\\s*else\\b[^\\n]*",
        is_regex: true,
        line_number: 401,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_ENDIF",
        pattern: "#\\s*endif\\b[^\\n]*",
        is_regex: true,
        line_number: 402,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_DEFINE",
        pattern: "#\\s*define\\b[^\\n]*",
        is_regex: true,
        line_number: 403,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_UNDEF",
        pattern: "#\\s*undef\\b[^\\n]*",
        is_regex: true,
        line_number: 404,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_REGION",
        pattern: "#\\s*region\\b[^\\n]*",
        is_regex: true,
        line_number: 405,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_ENDREGION",
        pattern: "#\\s*endregion\\b[^\\n]*",
        is_regex: true,
        line_number: 406,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_ERROR",
        pattern: "#\\s*error\\b[^\\n]*",
        is_regex: true,
        line_number: 407,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_WARNING",
        pattern: "#\\s*warning\\b[^\\n]*",
        is_regex: true,
        line_number: 408,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_LINE",
        pattern: "#\\s*line\\b[^\\n]*",
        is_regex: true,
        line_number: 409,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_PRAGMA",
        pattern: "#\\s*pragma\\b[^\\n]*",
        is_regex: true,
        line_number: 410,
        alias_name: nil,
      ),
    ],
  keywords: ["abstract", "as", "async", "await", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else", "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock", "long", "namespace", "new", "null", "object", "operator", "out", "override", "params", "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual", "void", "volatile", "while"],
  mode: nil,
  escape_mode: nil,
  skip_definitions: [
      GT::TokenDefinition.new(
        name: "WHITESPACE",
        pattern: "[ \\t\\r\\n\\v\\f]+",
        is_regex: true,
        line_number: 389,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LINE_COMMENT",
        pattern: "\\/\\/[^\\n]*",
        is_regex: true,
        line_number: 390,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BLOCK_COMMENT",
        pattern: "\\/\\*([^*]|\\*[^\\/])*\\*\\/",
        is_regex: true,
        line_number: 391,
        alias_name: nil,
      ),
    ],
  reserved_keywords: [],
  error_definitions: [
      GT::TokenDefinition.new(
        name: "BAD_STRING",
        pattern: "\"[^\"]*$",
        is_regex: true,
        line_number: 417,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BAD_CHAR",
        pattern: "'[^']*$",
        is_regex: true,
        line_number: 418,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BAD_VERBATIM_STRING",
        pattern: "@\"([^\"]|\"\")*$",
        is_regex: true,
        line_number: 419,
        alias_name: nil,
      ),
    ],
  groups: {},
  layout_keywords: [],
  context_keywords: [],
  soft_keywords: [],
)
