# frozen_string_literal: true
# AUTO-GENERATED FILE — DO NOT EDIT
# Source: csharp3.0.tokens
# Regenerate with: grammar-tools compile-tokens csharp3.0.tokens
#
# This file embeds a TokenGrammar as native Ruby data structures.
# Downstream packages require this file directly instead of reading
# and parsing the .tokens file at runtime.

require "coding_adventures_grammar_tools"

GT = CodingAdventures::GrammarTools unless defined?(GT)

TOKEN_GRAMMAR = GT::TokenGrammar.new(
  version: 1,
  case_insensitive: false,
  case_sensitive: true,
  definitions: [
      GT::TokenDefinition.new(
        name: "NAME",
        pattern: "[a-zA-Z_][a-zA-Z0-9_]*",
        is_regex: true,
        line_number: 106,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "VERBATIM_NAME",
        pattern: "@[a-zA-Z_][a-zA-Z0-9_]*",
        is_regex: true,
        line_number: 107,
        alias_name: "NAME",
      ),
      GT::TokenDefinition.new(
        name: "HEX_ULONG",
        pattern: "0[xX][0-9a-fA-F]+([uU][lL]|[lL][uU])",
        is_regex: true,
        line_number: 134,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "HEX_LONG",
        pattern: "0[xX][0-9a-fA-F]+[lL]",
        is_regex: true,
        line_number: 135,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "HEX_UINT",
        pattern: "0[xX][0-9a-fA-F]+[uU]",
        is_regex: true,
        line_number: 136,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "HEX_NUMBER",
        pattern: "0[xX][0-9a-fA-F]+",
        is_regex: true,
        line_number: 137,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "DECIMAL_FLOAT",
        pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?[fFdDmM]?",
        is_regex: true,
        line_number: 138,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "LEADING_DOT_FLOAT",
        pattern: "\\.[0-9]+([eE][+-]?[0-9]+)?[fFdDmM]?",
        is_regex: true,
        line_number: 139,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "SCI_NUMBER",
        pattern: "[0-9]+[eE][+-]?[0-9]+[fFdDmM]?",
        is_regex: true,
        line_number: 140,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "ULONG_NUMBER",
        pattern: "[0-9]+([uU][lL]|[lL][uU])",
        is_regex: true,
        line_number: 141,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "LONG_NUMBER",
        pattern: "[0-9]+[lL]",
        is_regex: true,
        line_number: 142,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "UINT_NUMBER",
        pattern: "[0-9]+[uU]",
        is_regex: true,
        line_number: 143,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "FLOAT_SUFFIX",
        pattern: "[0-9]+[fFdDmM]",
        is_regex: true,
        line_number: 144,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "INT_NUMBER",
        pattern: "[0-9]+",
        is_regex: true,
        line_number: 145,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "STRING",
        pattern: "\"([^\"\\\\]|\\\\.)*\"",
        is_regex: true,
        line_number: 166,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "VERBATIM_STRING",
        pattern: "@\"([^\"]|\"\")*\"",
        is_regex: true,
        line_number: 167,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CHAR",
        pattern: "'([^'\\\\]|\\\\.)*'",
        is_regex: true,
        line_number: 168,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LAMBDA",
        pattern: "=>",
        is_regex: false,
        line_number: 207,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COLON_COLON",
        pattern: "::",
        is_regex: false,
        line_number: 208,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LEFT_SHIFT_EQUALS",
        pattern: "<<=",
        is_regex: false,
        line_number: 209,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RIGHT_SHIFT_EQUALS",
        pattern: ">>=",
        is_regex: false,
        line_number: 210,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQUALS_EQUALS",
        pattern: "==",
        is_regex: false,
        line_number: 211,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NOT_EQUALS",
        pattern: "!=",
        is_regex: false,
        line_number: 212,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_EQUALS",
        pattern: "<=",
        is_regex: false,
        line_number: 213,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_EQUALS",
        pattern: ">=",
        is_regex: false,
        line_number: 214,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AND_AND",
        pattern: "&&",
        is_regex: false,
        line_number: 215,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "OR_OR",
        pattern: "||",
        is_regex: false,
        line_number: 216,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS_PLUS",
        pattern: "++",
        is_regex: false,
        line_number: 217,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS_MINUS",
        pattern: "--",
        is_regex: false,
        line_number: 218,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS_EQUALS",
        pattern: "+=",
        is_regex: false,
        line_number: 219,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS_EQUALS",
        pattern: "-=",
        is_regex: false,
        line_number: 220,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR_EQUALS",
        pattern: "*=",
        is_regex: false,
        line_number: 221,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SLASH_EQUALS",
        pattern: "/=",
        is_regex: false,
        line_number: 222,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PERCENT_EQUALS",
        pattern: "%=",
        is_regex: false,
        line_number: 223,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AMPERSAND_EQUALS",
        pattern: "&=",
        is_regex: false,
        line_number: 224,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PIPE_EQUALS",
        pattern: "|=",
        is_regex: false,
        line_number: 225,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CARET_EQUALS",
        pattern: "^=",
        is_regex: false,
        line_number: 226,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LEFT_SHIFT",
        pattern: "<<",
        is_regex: false,
        line_number: 227,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RIGHT_SHIFT",
        pattern: ">>",
        is_regex: false,
        line_number: 228,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "QUESTION_QUESTION",
        pattern: "??",
        is_regex: false,
        line_number: 229,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "ARROW",
        pattern: "->",
        is_regex: false,
        line_number: 230,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQUALS",
        pattern: "=",
        is_regex: false,
        line_number: 247,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS",
        pattern: "+",
        is_regex: false,
        line_number: 248,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS",
        pattern: "-",
        is_regex: false,
        line_number: 249,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR",
        pattern: "*",
        is_regex: false,
        line_number: 250,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SLASH",
        pattern: "/",
        is_regex: false,
        line_number: 251,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PERCENT",
        pattern: "%",
        is_regex: false,
        line_number: 252,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_THAN",
        pattern: "<",
        is_regex: false,
        line_number: 253,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_THAN",
        pattern: ">",
        is_regex: false,
        line_number: 254,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BANG",
        pattern: "!",
        is_regex: false,
        line_number: 255,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AMPERSAND",
        pattern: "&",
        is_regex: false,
        line_number: 256,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PIPE",
        pattern: "|",
        is_regex: false,
        line_number: 257,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CARET",
        pattern: "^",
        is_regex: false,
        line_number: 258,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "TILDE",
        pattern: "~",
        is_regex: false,
        line_number: 259,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "QUESTION",
        pattern: "?",
        is_regex: false,
        line_number: 260,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LPAREN",
        pattern: "(",
        is_regex: false,
        line_number: 269,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RPAREN",
        pattern: ")",
        is_regex: false,
        line_number: 270,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACE",
        pattern: "{",
        is_regex: false,
        line_number: 271,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACE",
        pattern: "}",
        is_regex: false,
        line_number: 272,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACKET",
        pattern: "[",
        is_regex: false,
        line_number: 273,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACKET",
        pattern: "]",
        is_regex: false,
        line_number: 274,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SEMICOLON",
        pattern: ";",
        is_regex: false,
        line_number: 275,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COMMA",
        pattern: ",",
        is_regex: false,
        line_number: 276,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DOT",
        pattern: ".",
        is_regex: false,
        line_number: 277,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COLON",
        pattern: ":",
        is_regex: false,
        line_number: 278,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_IF",
        pattern: "#\\s*if\\b[^\\n]*",
        is_regex: true,
        line_number: 442,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_ELIF",
        pattern: "#\\s*elif\\b[^\\n]*",
        is_regex: true,
        line_number: 443,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_ELSE",
        pattern: "#\\s*else\\b[^\\n]*",
        is_regex: true,
        line_number: 444,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_ENDIF",
        pattern: "#\\s*endif\\b[^\\n]*",
        is_regex: true,
        line_number: 445,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_DEFINE",
        pattern: "#\\s*define\\b[^\\n]*",
        is_regex: true,
        line_number: 446,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_UNDEF",
        pattern: "#\\s*undef\\b[^\\n]*",
        is_regex: true,
        line_number: 447,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_REGION",
        pattern: "#\\s*region\\b[^\\n]*",
        is_regex: true,
        line_number: 448,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_ENDREGION",
        pattern: "#\\s*endregion\\b[^\\n]*",
        is_regex: true,
        line_number: 449,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_ERROR",
        pattern: "#\\s*error\\b[^\\n]*",
        is_regex: true,
        line_number: 450,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_WARNING",
        pattern: "#\\s*warning\\b[^\\n]*",
        is_regex: true,
        line_number: 451,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_LINE",
        pattern: "#\\s*line\\b[^\\n]*",
        is_regex: true,
        line_number: 452,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_PRAGMA",
        pattern: "#\\s*pragma\\b[^\\n]*",
        is_regex: true,
        line_number: 453,
        alias_name: nil,
      ),
    ],
  keywords: ["abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else", "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock", "long", "namespace", "new", "null", "object", "operator", "out", "override", "params", "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual", "void", "volatile", "while", "yield"],
  mode: nil,
  escape_mode: nil,
  skip_definitions: [
      GT::TokenDefinition.new(
        name: "WHITESPACE",
        pattern: "[ \\t\\r\\n\\v\\f]+",
        is_regex: true,
        line_number: 426,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LINE_COMMENT",
        pattern: "\\/\\/[^\\n]*",
        is_regex: true,
        line_number: 427,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BLOCK_COMMENT",
        pattern: "\\/\\*([^*]|\\*[^\\/])*\\*\\/",
        is_regex: true,
        line_number: 428,
        alias_name: nil,
      ),
    ],
  reserved_keywords: [],
  error_definitions: [
      GT::TokenDefinition.new(
        name: "BAD_STRING",
        pattern: "\"[^\"]*$",
        is_regex: true,
        line_number: 460,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BAD_CHAR",
        pattern: "'[^']*$",
        is_regex: true,
        line_number: 461,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BAD_VERBATIM_STRING",
        pattern: "@\"([^\"]|\"\")*$",
        is_regex: true,
        line_number: 462,
        alias_name: nil,
      ),
    ],
  groups: {},
  layout_keywords: [],
  context_keywords: [],
  soft_keywords: [],
)
