# frozen_string_literal: true
# AUTO-GENERATED FILE — DO NOT EDIT
# Source: csharp12.0.tokens
# Regenerate with: grammar-tools compile-tokens csharp12.0.tokens
#
# This file embeds a TokenGrammar as native Ruby data structures.
# Downstream packages require this file directly instead of reading
# and parsing the .tokens file at runtime.

require "coding_adventures_grammar_tools"

GT = CodingAdventures::GrammarTools unless defined?(GT)

TOKEN_GRAMMAR = GT::TokenGrammar.new(
  version: 1,
  case_insensitive: false,
  case_sensitive: true,
  definitions: [
      GT::TokenDefinition.new(
        name: "NAME",
        pattern: "[a-zA-Z_][a-zA-Z0-9_]*",
        is_regex: true,
        line_number: 70,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "VERBATIM_NAME",
        pattern: "@[a-zA-Z_][a-zA-Z0-9_]*",
        is_regex: true,
        line_number: 71,
        alias_name: "NAME",
      ),
      GT::TokenDefinition.new(
        name: "BINARY_ULONG",
        pattern: "0[bB]_?[01][01_]*([uU][lL]|[lL][uU])",
        is_regex: true,
        line_number: 85,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "BINARY_LONG",
        pattern: "0[bB]_?[01][01_]*[lL]",
        is_regex: true,
        line_number: 86,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "BINARY_UINT",
        pattern: "0[bB]_?[01][01_]*[uU]",
        is_regex: true,
        line_number: 87,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "BINARY_NUMBER",
        pattern: "0[bB]_?[01][01_]*",
        is_regex: true,
        line_number: 88,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "HEX_ULONG",
        pattern: "0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*([uU][lL]|[lL][uU])",
        is_regex: true,
        line_number: 89,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "HEX_LONG",
        pattern: "0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*[lL]",
        is_regex: true,
        line_number: 90,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "HEX_UINT",
        pattern: "0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*[uU]",
        is_regex: true,
        line_number: 91,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "HEX_NUMBER",
        pattern: "0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*",
        is_regex: true,
        line_number: 92,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "DECIMAL_FLOAT",
        pattern: "[0-9][0-9_]*\\.[0-9_]*([eE][+-]?[0-9][0-9_]*)?[fFdDmM]?",
        is_regex: true,
        line_number: 93,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "LEADING_DOT_FLOAT",
        pattern: "\\.[0-9][0-9_]*([eE][+-]?[0-9][0-9_]*)?[fFdDmM]?",
        is_regex: true,
        line_number: 94,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "SCI_NUMBER",
        pattern: "[0-9][0-9_]*[eE][+-]?[0-9][0-9_]*[fFdDmM]?",
        is_regex: true,
        line_number: 95,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "ULONG_NUMBER",
        pattern: "[0-9][0-9_]*([uU][lL]|[lL][uU])",
        is_regex: true,
        line_number: 96,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "LONG_NUMBER",
        pattern: "[0-9][0-9_]*[lL]",
        is_regex: true,
        line_number: 97,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "UINT_NUMBER",
        pattern: "[0-9][0-9_]*[uU]",
        is_regex: true,
        line_number: 98,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "FLOAT_SUFFIX",
        pattern: "[0-9][0-9_]*[fFdDmM]",
        is_regex: true,
        line_number: 99,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "INT_NUMBER",
        pattern: "[0-9][0-9_]*",
        is_regex: true,
        line_number: 100,
        alias_name: "NUMBER",
      ),
      GT::TokenDefinition.new(
        name: "RAW_INTERPOLATED_STRING",
        pattern: "\\${1,}\"\"\"[\\s\\S]*?\"\"\"+",
        is_regex: true,
        line_number: 133,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RAW_STRING",
        pattern: "\"\"\"[\\s\\S]*?\"\"\"+",
        is_regex: true,
        line_number: 134,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STRING",
        pattern: "\"([^\"\\\\]|\\\\.)*\"",
        is_regex: true,
        line_number: 135,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "VERBATIM_STRING",
        pattern: "@\"([^\"]|\"\")*\"",
        is_regex: true,
        line_number: 136,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "INTERPOLATED_STRING",
        pattern: "\\$\"([^\"\\\\{]|\\\\.|\\{\\{|\\}\\})*\"",
        is_regex: true,
        line_number: 137,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "INTERPOLATED_VERBATIM",
        pattern: "(\\$@|@\\$)\"([^\"{]|\"\"|\\{\\{|\\}\\})*\"",
        is_regex: true,
        line_number: 138,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CHAR",
        pattern: "'([^'\\\\]|\\\\.)*'",
        is_regex: true,
        line_number: 139,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "UNSIGNED_RIGHT_SHIFT_EQUALS",
        pattern: ">>>=",
        is_regex: false,
        line_number: 160,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "QUESTION_QUESTION_EQUALS",
        pattern: "??=",
        is_regex: false,
        line_number: 161,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NULL_CONDITIONAL_DOT",
        pattern: "?.",
        is_regex: false,
        line_number: 162,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NULL_CONDITIONAL_BRACKET",
        pattern: "?[",
        is_regex: false,
        line_number: 163,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NULL_COALESCING",
        pattern: "??",
        is_regex: false,
        line_number: 164,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LAMBDA_ARROW",
        pattern: "=>",
        is_regex: false,
        line_number: 165,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LEFT_SHIFT_EQUALS",
        pattern: "<<=",
        is_regex: false,
        line_number: 166,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RIGHT_SHIFT_EQUALS",
        pattern: ">>=",
        is_regex: false,
        line_number: 167,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "UNSIGNED_RIGHT_SHIFT",
        pattern: ">>>",
        is_regex: false,
        line_number: 168,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DOT_DOT",
        pattern: "..",
        is_regex: false,
        line_number: 169,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQUALS_EQUALS",
        pattern: "==",
        is_regex: false,
        line_number: 170,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NOT_EQUALS",
        pattern: "!=",
        is_regex: false,
        line_number: 171,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_EQUALS",
        pattern: "<=",
        is_regex: false,
        line_number: 172,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_EQUALS",
        pattern: ">=",
        is_regex: false,
        line_number: 173,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AND_AND",
        pattern: "&&",
        is_regex: false,
        line_number: 174,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "OR_OR",
        pattern: "||",
        is_regex: false,
        line_number: 175,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS_PLUS",
        pattern: "++",
        is_regex: false,
        line_number: 176,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS_MINUS",
        pattern: "--",
        is_regex: false,
        line_number: 177,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS_EQUALS",
        pattern: "+=",
        is_regex: false,
        line_number: 178,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS_EQUALS",
        pattern: "-=",
        is_regex: false,
        line_number: 179,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR_EQUALS",
        pattern: "*=",
        is_regex: false,
        line_number: 180,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SLASH_EQUALS",
        pattern: "/=",
        is_regex: false,
        line_number: 181,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PERCENT_EQUALS",
        pattern: "%=",
        is_regex: false,
        line_number: 182,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AMPERSAND_EQUALS",
        pattern: "&=",
        is_regex: false,
        line_number: 183,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PIPE_EQUALS",
        pattern: "|=",
        is_regex: false,
        line_number: 184,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CARET_EQUALS",
        pattern: "^=",
        is_regex: false,
        line_number: 185,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LEFT_SHIFT",
        pattern: "<<",
        is_regex: false,
        line_number: 186,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RIGHT_SHIFT",
        pattern: ">>",
        is_regex: false,
        line_number: 187,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COLON_COLON",
        pattern: "::",
        is_regex: false,
        line_number: 188,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "ARROW",
        pattern: "->",
        is_regex: false,
        line_number: 189,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQUALS",
        pattern: "=",
        is_regex: false,
        line_number: 201,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS",
        pattern: "+",
        is_regex: false,
        line_number: 202,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS",
        pattern: "-",
        is_regex: false,
        line_number: 203,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR",
        pattern: "*",
        is_regex: false,
        line_number: 204,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SLASH",
        pattern: "/",
        is_regex: false,
        line_number: 205,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PERCENT",
        pattern: "%",
        is_regex: false,
        line_number: 206,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_THAN",
        pattern: "<",
        is_regex: false,
        line_number: 207,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_THAN",
        pattern: ">",
        is_regex: false,
        line_number: 208,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BANG",
        pattern: "!",
        is_regex: false,
        line_number: 209,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AMPERSAND",
        pattern: "&",
        is_regex: false,
        line_number: 210,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PIPE",
        pattern: "|",
        is_regex: false,
        line_number: 211,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CARET",
        pattern: "^",
        is_regex: false,
        line_number: 212,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "TILDE",
        pattern: "~",
        is_regex: false,
        line_number: 213,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "QUESTION",
        pattern: "?",
        is_regex: false,
        line_number: 214,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LPAREN",
        pattern: "(",
        is_regex: false,
        line_number: 224,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RPAREN",
        pattern: ")",
        is_regex: false,
        line_number: 225,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACE",
        pattern: "{",
        is_regex: false,
        line_number: 226,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACE",
        pattern: "}",
        is_regex: false,
        line_number: 227,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACKET",
        pattern: "[",
        is_regex: false,
        line_number: 228,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACKET",
        pattern: "]",
        is_regex: false,
        line_number: 229,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SEMICOLON",
        pattern: ";",
        is_regex: false,
        line_number: 230,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COMMA",
        pattern: ",",
        is_regex: false,
        line_number: 231,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DOT",
        pattern: ".",
        is_regex: false,
        line_number: 232,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COLON",
        pattern: ":",
        is_regex: false,
        line_number: 233,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_NULLABLE",
        pattern: "#\\s*nullable\\b[^\\n]*",
        is_regex: true,
        line_number: 360,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_IF",
        pattern: "#\\s*if\\b[^\\n]*",
        is_regex: true,
        line_number: 361,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_ELIF",
        pattern: "#\\s*elif\\b[^\\n]*",
        is_regex: true,
        line_number: 362,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_ELSE",
        pattern: "#\\s*else\\b[^\\n]*",
        is_regex: true,
        line_number: 363,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_ENDIF",
        pattern: "#\\s*endif\\b[^\\n]*",
        is_regex: true,
        line_number: 364,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_DEFINE",
        pattern: "#\\s*define\\b[^\\n]*",
        is_regex: true,
        line_number: 365,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_UNDEF",
        pattern: "#\\s*undef\\b[^\\n]*",
        is_regex: true,
        line_number: 366,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_REGION",
        pattern: "#\\s*region\\b[^\\n]*",
        is_regex: true,
        line_number: 367,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_ENDREGION",
        pattern: "#\\s*endregion\\b[^\\n]*",
        is_regex: true,
        line_number: 368,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_ERROR",
        pattern: "#\\s*error\\b[^\\n]*",
        is_regex: true,
        line_number: 369,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_WARNING",
        pattern: "#\\s*warning\\b[^\\n]*",
        is_regex: true,
        line_number: 370,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_LINE",
        pattern: "#\\s*line\\b[^\\n]*",
        is_regex: true,
        line_number: 371,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PP_PRAGMA",
        pattern: "#\\s*pragma\\b[^\\n]*",
        is_regex: true,
        line_number: 372,
        alias_name: nil,
      ),
    ],
  keywords: ["abstract", "as", "async", "await", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else", "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock", "long", "namespace", "new", "null", "object", "operator", "out", "override", "params", "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual", "void", "volatile", "while"],
  mode: nil,
  escape_mode: nil,
  skip_definitions: [
      GT::TokenDefinition.new(
        name: "WHITESPACE",
        pattern: "[ \\t\\r\\n\\v\\f]+",
        is_regex: true,
        line_number: 350,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LINE_COMMENT",
        pattern: "\\/\\/[^\\n]*",
        is_regex: true,
        line_number: 351,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BLOCK_COMMENT",
        pattern: "\\/\\*([^*]|\\*[^\\/])*\\*\\/",
        is_regex: true,
        line_number: 352,
        alias_name: nil,
      ),
    ],
  reserved_keywords: [],
  error_definitions: [
      GT::TokenDefinition.new(
        name: "BAD_RAW_STRING",
        pattern: "\"\"\"[^\"]*$",
        is_regex: true,
        line_number: 379,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BAD_STRING",
        pattern: "\"[^\"]*$",
        is_regex: true,
        line_number: 380,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BAD_CHAR",
        pattern: "'[^']*$",
        is_regex: true,
        line_number: 381,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BAD_VERBATIM_STRING",
        pattern: "@\"([^\"]|\"\")*$",
        is_regex: true,
        line_number: 382,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BAD_INTERPOLATED_STRING",
        pattern: "\\$\"([^\"\\\\{]|\\\\.)*$",
        is_regex: true,
        line_number: 383,
        alias_name: nil,
      ),
    ],
  groups: {},
  layout_keywords: [],
  context_keywords: [],
  soft_keywords: [],
)
