cd ../../../packages/typescript/directed-graph && npm install --quiet
cd ../../../packages/typescript/grammar-tools && npm install --quiet
cd ../../../packages/typescript/lexer && npm install --quiet
cd ../../../packages/typescript/state-machine && npm install --quiet
cd ../../../packages/typescript/parser && npm install --quiet
cd ../../../packages/typescript/lattice-lexer && npm install --quiet
cd ../../../packages/typescript/lattice-parser && npm install --quiet
cd ../../../packages/typescript/lattice-ast-to-css && npm install --quiet
cd ../../../packages/typescript/lattice-transpiler && npm install --quiet
cd ../../../packages/typescript/indexeddb && npm install --quiet
cd ../../../packages/typescript/store && npm install --quiet
cd ../../../packages/typescript/ui-components && npm install --quiet
cd ../../../packages/typescript/vite-plugin-lattice && npm install --quiet
cd ../../../programs/typescript/todo-app && npm install --quiet
npx vitest run
