// AUTO-GENERATED FILE - DO NOT EDIT
// Source: csharp10.0.tokens
// Regenerate with: grammar-tools compile-tokens csharp10.0.tokens
//
// This file embeds a TokenGrammar as native TypeScript object literals.
// Import it directly instead of reading and parsing the .tokens file at
// runtime.

import type { TokenGrammar } from "@coding-adventures/grammar-tools";

export const TOKEN_GRAMMAR: TokenGrammar = {
  version: 1,
  caseInsensitive: false,
  caseSensitive: true,
  definitions: [
    {
      name: "NAME",
      pattern: "[a-zA-Z_][a-zA-Z0-9_]*",
      isRegex: true,
      lineNumber: 105,
    },
    {
      name: "VERBATIM_NAME",
      pattern: "@[a-zA-Z_][a-zA-Z0-9_]*",
      isRegex: true,
      lineNumber: 106,
      alias: "NAME",
    },
    {
      name: "BINARY_ULONG",
      pattern: "0[bB]_?[01][01_]*([uU][lL]|[lL][uU])",
      isRegex: true,
      lineNumber: 126,
      alias: "NUMBER",
    },
    {
      name: "BINARY_LONG",
      pattern: "0[bB]_?[01][01_]*[lL]",
      isRegex: true,
      lineNumber: 127,
      alias: "NUMBER",
    },
    {
      name: "BINARY_UINT",
      pattern: "0[bB]_?[01][01_]*[uU]",
      isRegex: true,
      lineNumber: 128,
      alias: "NUMBER",
    },
    {
      name: "BINARY_NUMBER",
      pattern: "0[bB]_?[01][01_]*",
      isRegex: true,
      lineNumber: 129,
      alias: "NUMBER",
    },
    {
      name: "HEX_ULONG",
      pattern: "0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*([uU][lL]|[lL][uU])",
      isRegex: true,
      lineNumber: 130,
      alias: "NUMBER",
    },
    {
      name: "HEX_LONG",
      pattern: "0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*[lL]",
      isRegex: true,
      lineNumber: 131,
      alias: "NUMBER",
    },
    {
      name: "HEX_UINT",
      pattern: "0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*[uU]",
      isRegex: true,
      lineNumber: 132,
      alias: "NUMBER",
    },
    {
      name: "HEX_NUMBER",
      pattern: "0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*",
      isRegex: true,
      lineNumber: 133,
      alias: "NUMBER",
    },
    {
      name: "DECIMAL_FLOAT",
      pattern: "[0-9][0-9_]*\\.[0-9_]*([eE][+-]?[0-9][0-9_]*)?[fFdDmM]?",
      isRegex: true,
      lineNumber: 134,
      alias: "NUMBER",
    },
    {
      name: "LEADING_DOT_FLOAT",
      pattern: "\\.[0-9][0-9_]*([eE][+-]?[0-9][0-9_]*)?[fFdDmM]?",
      isRegex: true,
      lineNumber: 135,
      alias: "NUMBER",
    },
    {
      name: "SCI_NUMBER",
      pattern: "[0-9][0-9_]*[eE][+-]?[0-9][0-9_]*[fFdDmM]?",
      isRegex: true,
      lineNumber: 136,
      alias: "NUMBER",
    },
    {
      name: "ULONG_NUMBER",
      pattern: "[0-9][0-9_]*([uU][lL]|[lL][uU])",
      isRegex: true,
      lineNumber: 137,
      alias: "NUMBER",
    },
    {
      name: "LONG_NUMBER",
      pattern: "[0-9][0-9_]*[lL]",
      isRegex: true,
      lineNumber: 138,
      alias: "NUMBER",
    },
    {
      name: "UINT_NUMBER",
      pattern: "[0-9][0-9_]*[uU]",
      isRegex: true,
      lineNumber: 139,
      alias: "NUMBER",
    },
    {
      name: "FLOAT_SUFFIX",
      pattern: "[0-9][0-9_]*[fFdDmM]",
      isRegex: true,
      lineNumber: 140,
      alias: "NUMBER",
    },
    {
      name: "INT_NUMBER",
      pattern: "[0-9][0-9_]*",
      isRegex: true,
      lineNumber: 141,
      alias: "NUMBER",
    },
    {
      name: "STRING",
      pattern: "\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 154,
    },
    {
      name: "VERBATIM_STRING",
      pattern: "@\"([^\"]|\"\")*\"",
      isRegex: true,
      lineNumber: 155,
    },
    {
      name: "INTERPOLATED_STRING",
      pattern: "\\$\"([^\"\\\\{]|\\\\.|\\{\\{|\\}\\})*\"",
      isRegex: true,
      lineNumber: 156,
    },
    {
      name: "INTERPOLATED_VERBATIM",
      pattern: "(\\$@|@\\$)\"([^\"{]|\"\"|\\{\\{|\\}\\})*\"",
      isRegex: true,
      lineNumber: 157,
    },
    {
      name: "CHAR",
      pattern: "'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 158,
    },
    {
      name: "QUESTION_QUESTION_EQUALS",
      pattern: "??=",
      isRegex: false,
      lineNumber: 184,
    },
    {
      name: "NULL_CONDITIONAL_DOT",
      pattern: "?.",
      isRegex: false,
      lineNumber: 185,
    },
    {
      name: "NULL_CONDITIONAL_BRACKET",
      pattern: "?[",
      isRegex: false,
      lineNumber: 186,
    },
    {
      name: "NULL_COALESCING",
      pattern: "??",
      isRegex: false,
      lineNumber: 187,
    },
    {
      name: "LAMBDA_ARROW",
      pattern: "=>",
      isRegex: false,
      lineNumber: 188,
    },
    {
      name: "LEFT_SHIFT_EQUALS",
      pattern: "<<=",
      isRegex: false,
      lineNumber: 189,
    },
    {
      name: "RIGHT_SHIFT_EQUALS",
      pattern: ">>=",
      isRegex: false,
      lineNumber: 190,
    },
    {
      name: "DOT_DOT",
      pattern: "..",
      isRegex: false,
      lineNumber: 191,
    },
    {
      name: "EQUALS_EQUALS",
      pattern: "==",
      isRegex: false,
      lineNumber: 192,
    },
    {
      name: "NOT_EQUALS",
      pattern: "!=",
      isRegex: false,
      lineNumber: 193,
    },
    {
      name: "LESS_EQUALS",
      pattern: "<=",
      isRegex: false,
      lineNumber: 194,
    },
    {
      name: "GREATER_EQUALS",
      pattern: ">=",
      isRegex: false,
      lineNumber: 195,
    },
    {
      name: "AND_AND",
      pattern: "&&",
      isRegex: false,
      lineNumber: 196,
    },
    {
      name: "OR_OR",
      pattern: "||",
      isRegex: false,
      lineNumber: 197,
    },
    {
      name: "PLUS_PLUS",
      pattern: "++",
      isRegex: false,
      lineNumber: 198,
    },
    {
      name: "MINUS_MINUS",
      pattern: "--",
      isRegex: false,
      lineNumber: 199,
    },
    {
      name: "PLUS_EQUALS",
      pattern: "+=",
      isRegex: false,
      lineNumber: 200,
    },
    {
      name: "MINUS_EQUALS",
      pattern: "-=",
      isRegex: false,
      lineNumber: 201,
    },
    {
      name: "STAR_EQUALS",
      pattern: "*=",
      isRegex: false,
      lineNumber: 202,
    },
    {
      name: "SLASH_EQUALS",
      pattern: "/=",
      isRegex: false,
      lineNumber: 203,
    },
    {
      name: "PERCENT_EQUALS",
      pattern: "%=",
      isRegex: false,
      lineNumber: 204,
    },
    {
      name: "AMPERSAND_EQUALS",
      pattern: "&=",
      isRegex: false,
      lineNumber: 205,
    },
    {
      name: "PIPE_EQUALS",
      pattern: "|=",
      isRegex: false,
      lineNumber: 206,
    },
    {
      name: "CARET_EQUALS",
      pattern: "^=",
      isRegex: false,
      lineNumber: 207,
    },
    {
      name: "LEFT_SHIFT",
      pattern: "<<",
      isRegex: false,
      lineNumber: 208,
    },
    {
      name: "RIGHT_SHIFT",
      pattern: ">>",
      isRegex: false,
      lineNumber: 209,
    },
    {
      name: "COLON_COLON",
      pattern: "::",
      isRegex: false,
      lineNumber: 210,
    },
    {
      name: "ARROW",
      pattern: "->",
      isRegex: false,
      lineNumber: 211,
    },
    {
      name: "EQUALS",
      pattern: "=",
      isRegex: false,
      lineNumber: 219,
    },
    {
      name: "PLUS",
      pattern: "+",
      isRegex: false,
      lineNumber: 220,
    },
    {
      name: "MINUS",
      pattern: "-",
      isRegex: false,
      lineNumber: 221,
    },
    {
      name: "STAR",
      pattern: "*",
      isRegex: false,
      lineNumber: 222,
    },
    {
      name: "SLASH",
      pattern: "/",
      isRegex: false,
      lineNumber: 223,
    },
    {
      name: "PERCENT",
      pattern: "%",
      isRegex: false,
      lineNumber: 224,
    },
    {
      name: "LESS_THAN",
      pattern: "<",
      isRegex: false,
      lineNumber: 225,
    },
    {
      name: "GREATER_THAN",
      pattern: ">",
      isRegex: false,
      lineNumber: 226,
    },
    {
      name: "BANG",
      pattern: "!",
      isRegex: false,
      lineNumber: 227,
    },
    {
      name: "AMPERSAND",
      pattern: "&",
      isRegex: false,
      lineNumber: 228,
    },
    {
      name: "PIPE",
      pattern: "|",
      isRegex: false,
      lineNumber: 229,
    },
    {
      name: "CARET",
      pattern: "^",
      isRegex: false,
      lineNumber: 230,
    },
    {
      name: "TILDE",
      pattern: "~",
      isRegex: false,
      lineNumber: 231,
    },
    {
      name: "QUESTION",
      pattern: "?",
      isRegex: false,
      lineNumber: 232,
    },
    {
      name: "LPAREN",
      pattern: "(",
      isRegex: false,
      lineNumber: 242,
    },
    {
      name: "RPAREN",
      pattern: ")",
      isRegex: false,
      lineNumber: 243,
    },
    {
      name: "LBRACE",
      pattern: "{",
      isRegex: false,
      lineNumber: 244,
    },
    {
      name: "RBRACE",
      pattern: "}",
      isRegex: false,
      lineNumber: 245,
    },
    {
      name: "LBRACKET",
      pattern: "[",
      isRegex: false,
      lineNumber: 246,
    },
    {
      name: "RBRACKET",
      pattern: "]",
      isRegex: false,
      lineNumber: 247,
    },
    {
      name: "SEMICOLON",
      pattern: ";",
      isRegex: false,
      lineNumber: 248,
    },
    {
      name: "COMMA",
      pattern: ",",
      isRegex: false,
      lineNumber: 249,
    },
    {
      name: "DOT",
      pattern: ".",
      isRegex: false,
      lineNumber: 250,
    },
    {
      name: "COLON",
      pattern: ":",
      isRegex: false,
      lineNumber: 251,
    },
    {
      name: "PP_NULLABLE",
      pattern: "#\\s*nullable\\b[^\\n]*",
      isRegex: true,
      lineNumber: 398,
    },
    {
      name: "PP_IF",
      pattern: "#\\s*if\\b[^\\n]*",
      isRegex: true,
      lineNumber: 399,
    },
    {
      name: "PP_ELIF",
      pattern: "#\\s*elif\\b[^\\n]*",
      isRegex: true,
      lineNumber: 400,
    },
    {
      name: "PP_ELSE",
      pattern: "#\\s*else\\b[^\\n]*",
      isRegex: true,
      lineNumber: 401,
    },
    {
      name: "PP_ENDIF",
      pattern: "#\\s*endif\\b[^\\n]*",
      isRegex: true,
      lineNumber: 402,
    },
    {
      name: "PP_DEFINE",
      pattern: "#\\s*define\\b[^\\n]*",
      isRegex: true,
      lineNumber: 403,
    },
    {
      name: "PP_UNDEF",
      pattern: "#\\s*undef\\b[^\\n]*",
      isRegex: true,
      lineNumber: 404,
    },
    {
      name: "PP_REGION",
      pattern: "#\\s*region\\b[^\\n]*",
      isRegex: true,
      lineNumber: 405,
    },
    {
      name: "PP_ENDREGION",
      pattern: "#\\s*endregion\\b[^\\n]*",
      isRegex: true,
      lineNumber: 406,
    },
    {
      name: "PP_ERROR",
      pattern: "#\\s*error\\b[^\\n]*",
      isRegex: true,
      lineNumber: 407,
    },
    {
      name: "PP_WARNING",
      pattern: "#\\s*warning\\b[^\\n]*",
      isRegex: true,
      lineNumber: 408,
    },
    {
      name: "PP_LINE",
      pattern: "#\\s*line\\b[^\\n]*",
      isRegex: true,
      lineNumber: 409,
    },
    {
      name: "PP_PRAGMA",
      pattern: "#\\s*pragma\\b[^\\n]*",
      isRegex: true,
      lineNumber: 410,
    },
  ],
  keywords: ["abstract","as","async","await","base","bool","break","byte","case","catch","char","checked","class","const","continue","decimal","default","delegate","do","double","else","enum","event","explicit","extern","false","finally","fixed","float","for","foreach","goto","if","implicit","in","int","interface","internal","is","lock","long","namespace","new","null","object","operator","out","override","params","private","protected","public","readonly","ref","return","sbyte","sealed","short","sizeof","stackalloc","static","string","struct","switch","this","throw","true","try","typeof","uint","ulong","unchecked","unsafe","ushort","using","virtual","void","volatile","while"],
  mode: undefined,
  escapeMode: undefined,
  skipDefinitions: [
    {
      name: "WHITESPACE",
      pattern: "[ \\t\\r\\n\\v\\f]+",
      isRegex: true,
      lineNumber: 379,
    },
    {
      name: "LINE_COMMENT",
      pattern: "\\/\\/[^\\n]*",
      isRegex: true,
      lineNumber: 380,
    },
    {
      name: "BLOCK_COMMENT",
      pattern: "\\/\\*([^*]|\\*[^\\/])*\\*\\/",
      isRegex: true,
      lineNumber: 381,
    },
  ],
  reservedKeywords: [],
  layoutKeywords: [],
  contextKeywords: [],
  errorDefinitions: [],
  groups: {},
  softKeywords: [],
};
