// AUTO-GENERATED FILE - DO NOT EDIT
// Source: csharp1.0.tokens
// Regenerate with: grammar-tools compile-tokens csharp1.0.tokens
//
// This file embeds a TokenGrammar as native TypeScript object literals.
// Import it directly instead of reading and parsing the .tokens file at
// runtime.

import type { TokenGrammar } from "@coding-adventures/grammar-tools";

export const TOKEN_GRAMMAR: TokenGrammar = {
  version: 1,
  caseInsensitive: false,
  caseSensitive: true,
  definitions: [
    {
      name: "NAME",
      pattern: "[a-zA-Z_][a-zA-Z0-9_]*",
      isRegex: true,
      lineNumber: 86,
    },
    {
      name: "VERBATIM_NAME",
      pattern: "@[a-zA-Z_][a-zA-Z0-9_]*",
      isRegex: true,
      lineNumber: 87,
      alias: "NAME",
    },
    {
      name: "HEX_ULONG",
      pattern: "0[xX][0-9a-fA-F]+([uU][lL]|[lL][uU])",
      isRegex: true,
      lineNumber: 127,
      alias: "NUMBER",
    },
    {
      name: "HEX_LONG",
      pattern: "0[xX][0-9a-fA-F]+[lL]",
      isRegex: true,
      lineNumber: 128,
      alias: "NUMBER",
    },
    {
      name: "HEX_UINT",
      pattern: "0[xX][0-9a-fA-F]+[uU]",
      isRegex: true,
      lineNumber: 129,
      alias: "NUMBER",
    },
    {
      name: "HEX_NUMBER",
      pattern: "0[xX][0-9a-fA-F]+",
      isRegex: true,
      lineNumber: 130,
      alias: "NUMBER",
    },
    {
      name: "DECIMAL_FLOAT",
      pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?[fFdDmM]?",
      isRegex: true,
      lineNumber: 131,
      alias: "NUMBER",
    },
    {
      name: "LEADING_DOT_FLOAT",
      pattern: "\\.[0-9]+([eE][+-]?[0-9]+)?[fFdDmM]?",
      isRegex: true,
      lineNumber: 132,
      alias: "NUMBER",
    },
    {
      name: "SCI_NUMBER",
      pattern: "[0-9]+[eE][+-]?[0-9]+[fFdDmM]?",
      isRegex: true,
      lineNumber: 133,
      alias: "NUMBER",
    },
    {
      name: "ULONG_NUMBER",
      pattern: "[0-9]+([uU][lL]|[lL][uU])",
      isRegex: true,
      lineNumber: 134,
      alias: "NUMBER",
    },
    {
      name: "LONG_NUMBER",
      pattern: "[0-9]+[lL]",
      isRegex: true,
      lineNumber: 135,
      alias: "NUMBER",
    },
    {
      name: "UINT_NUMBER",
      pattern: "[0-9]+[uU]",
      isRegex: true,
      lineNumber: 136,
      alias: "NUMBER",
    },
    {
      name: "FLOAT_SUFFIX",
      pattern: "[0-9]+[fFdDmM]",
      isRegex: true,
      lineNumber: 137,
      alias: "NUMBER",
    },
    {
      name: "INT_NUMBER",
      pattern: "[0-9]+",
      isRegex: true,
      lineNumber: 138,
      alias: "NUMBER",
    },
    {
      name: "STRING",
      pattern: "\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 185,
    },
    {
      name: "VERBATIM_STRING",
      pattern: "@\"([^\"]|\"\")*\"",
      isRegex: true,
      lineNumber: 186,
    },
    {
      name: "CHAR",
      pattern: "'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 187,
    },
    {
      name: "LEFT_SHIFT_EQUALS",
      pattern: "<<=",
      isRegex: false,
      lineNumber: 209,
    },
    {
      name: "RIGHT_SHIFT_EQUALS",
      pattern: ">>=",
      isRegex: false,
      lineNumber: 210,
    },
    {
      name: "EQUALS_EQUALS",
      pattern: "==",
      isRegex: false,
      lineNumber: 211,
    },
    {
      name: "NOT_EQUALS",
      pattern: "!=",
      isRegex: false,
      lineNumber: 212,
    },
    {
      name: "LESS_EQUALS",
      pattern: "<=",
      isRegex: false,
      lineNumber: 213,
    },
    {
      name: "GREATER_EQUALS",
      pattern: ">=",
      isRegex: false,
      lineNumber: 214,
    },
    {
      name: "AND_AND",
      pattern: "&&",
      isRegex: false,
      lineNumber: 215,
    },
    {
      name: "OR_OR",
      pattern: "||",
      isRegex: false,
      lineNumber: 216,
    },
    {
      name: "PLUS_PLUS",
      pattern: "++",
      isRegex: false,
      lineNumber: 217,
    },
    {
      name: "MINUS_MINUS",
      pattern: "--",
      isRegex: false,
      lineNumber: 218,
    },
    {
      name: "PLUS_EQUALS",
      pattern: "+=",
      isRegex: false,
      lineNumber: 219,
    },
    {
      name: "MINUS_EQUALS",
      pattern: "-=",
      isRegex: false,
      lineNumber: 220,
    },
    {
      name: "STAR_EQUALS",
      pattern: "*=",
      isRegex: false,
      lineNumber: 221,
    },
    {
      name: "SLASH_EQUALS",
      pattern: "/=",
      isRegex: false,
      lineNumber: 222,
    },
    {
      name: "PERCENT_EQUALS",
      pattern: "%=",
      isRegex: false,
      lineNumber: 223,
    },
    {
      name: "AMPERSAND_EQUALS",
      pattern: "&=",
      isRegex: false,
      lineNumber: 224,
    },
    {
      name: "PIPE_EQUALS",
      pattern: "|=",
      isRegex: false,
      lineNumber: 225,
    },
    {
      name: "CARET_EQUALS",
      pattern: "^=",
      isRegex: false,
      lineNumber: 226,
    },
    {
      name: "LEFT_SHIFT",
      pattern: "<<",
      isRegex: false,
      lineNumber: 227,
    },
    {
      name: "RIGHT_SHIFT",
      pattern: ">>",
      isRegex: false,
      lineNumber: 228,
    },
    {
      name: "ARROW",
      pattern: "->",
      isRegex: false,
      lineNumber: 229,
    },
    {
      name: "EQUALS",
      pattern: "=",
      isRegex: false,
      lineNumber: 247,
    },
    {
      name: "PLUS",
      pattern: "+",
      isRegex: false,
      lineNumber: 248,
    },
    {
      name: "MINUS",
      pattern: "-",
      isRegex: false,
      lineNumber: 249,
    },
    {
      name: "STAR",
      pattern: "*",
      isRegex: false,
      lineNumber: 250,
    },
    {
      name: "SLASH",
      pattern: "/",
      isRegex: false,
      lineNumber: 251,
    },
    {
      name: "PERCENT",
      pattern: "%",
      isRegex: false,
      lineNumber: 252,
    },
    {
      name: "LESS_THAN",
      pattern: "<",
      isRegex: false,
      lineNumber: 253,
    },
    {
      name: "GREATER_THAN",
      pattern: ">",
      isRegex: false,
      lineNumber: 254,
    },
    {
      name: "BANG",
      pattern: "!",
      isRegex: false,
      lineNumber: 255,
    },
    {
      name: "AMPERSAND",
      pattern: "&",
      isRegex: false,
      lineNumber: 256,
    },
    {
      name: "PIPE",
      pattern: "|",
      isRegex: false,
      lineNumber: 257,
    },
    {
      name: "CARET",
      pattern: "^",
      isRegex: false,
      lineNumber: 258,
    },
    {
      name: "TILDE",
      pattern: "~",
      isRegex: false,
      lineNumber: 259,
    },
    {
      name: "QUESTION",
      pattern: "?",
      isRegex: false,
      lineNumber: 260,
    },
    {
      name: "LPAREN",
      pattern: "(",
      isRegex: false,
      lineNumber: 272,
    },
    {
      name: "RPAREN",
      pattern: ")",
      isRegex: false,
      lineNumber: 273,
    },
    {
      name: "LBRACE",
      pattern: "{",
      isRegex: false,
      lineNumber: 274,
    },
    {
      name: "RBRACE",
      pattern: "}",
      isRegex: false,
      lineNumber: 275,
    },
    {
      name: "LBRACKET",
      pattern: "[",
      isRegex: false,
      lineNumber: 276,
    },
    {
      name: "RBRACKET",
      pattern: "]",
      isRegex: false,
      lineNumber: 277,
    },
    {
      name: "SEMICOLON",
      pattern: ";",
      isRegex: false,
      lineNumber: 278,
    },
    {
      name: "COMMA",
      pattern: ",",
      isRegex: false,
      lineNumber: 279,
    },
    {
      name: "DOT",
      pattern: ".",
      isRegex: false,
      lineNumber: 280,
    },
    {
      name: "COLON",
      pattern: ":",
      isRegex: false,
      lineNumber: 281,
    },
    {
      name: "PP_IF",
      pattern: "#\\s*if\\b[^\\n]*",
      isRegex: true,
      lineNumber: 494,
    },
    {
      name: "PP_ELIF",
      pattern: "#\\s*elif\\b[^\\n]*",
      isRegex: true,
      lineNumber: 495,
    },
    {
      name: "PP_ELSE",
      pattern: "#\\s*else\\b[^\\n]*",
      isRegex: true,
      lineNumber: 496,
    },
    {
      name: "PP_ENDIF",
      pattern: "#\\s*endif\\b[^\\n]*",
      isRegex: true,
      lineNumber: 497,
    },
    {
      name: "PP_DEFINE",
      pattern: "#\\s*define\\b[^\\n]*",
      isRegex: true,
      lineNumber: 498,
    },
    {
      name: "PP_UNDEF",
      pattern: "#\\s*undef\\b[^\\n]*",
      isRegex: true,
      lineNumber: 499,
    },
    {
      name: "PP_REGION",
      pattern: "#\\s*region\\b[^\\n]*",
      isRegex: true,
      lineNumber: 500,
    },
    {
      name: "PP_ENDREGION",
      pattern: "#\\s*endregion\\b[^\\n]*",
      isRegex: true,
      lineNumber: 501,
    },
    {
      name: "PP_ERROR",
      pattern: "#\\s*error\\b[^\\n]*",
      isRegex: true,
      lineNumber: 502,
    },
    {
      name: "PP_WARNING",
      pattern: "#\\s*warning\\b[^\\n]*",
      isRegex: true,
      lineNumber: 503,
    },
    {
      name: "PP_LINE",
      pattern: "#\\s*line\\b[^\\n]*",
      isRegex: true,
      lineNumber: 504,
    },
    {
      name: "PP_PRAGMA",
      pattern: "#\\s*pragma\\b[^\\n]*",
      isRegex: true,
      lineNumber: 505,
    },
  ],
  keywords: ["abstract","as","base","bool","break","byte","case","catch","char","checked","class","const","continue","decimal","default","delegate","do","double","else","enum","event","explicit","extern","false","finally","fixed","float","for","foreach","goto","if","implicit","in","int","interface","internal","is","lock","long","namespace","new","null","object","operator","out","override","params","private","protected","public","readonly","ref","return","sbyte","sealed","short","sizeof","stackalloc","static","string","struct","switch","this","throw","true","try","typeof","uint","ulong","unchecked","unsafe","ushort","using","virtual","void","volatile","while"],
  mode: undefined,
  escapeMode: undefined,
  skipDefinitions: [
    {
      name: "WHITESPACE",
      pattern: "[ \\t\\r\\n\\v\\f]+",
      isRegex: true,
      lineNumber: 453,
    },
    {
      name: "LINE_COMMENT",
      pattern: "\\/\\/[^\\n]*",
      isRegex: true,
      lineNumber: 454,
    },
    {
      name: "BLOCK_COMMENT",
      pattern: "\\/\\*([^*]|\\*[^\\/])*\\*\\/",
      isRegex: true,
      lineNumber: 455,
    },
  ],
  reservedKeywords: [],
  layoutKeywords: [],
  contextKeywords: [],
  errorDefinitions: [],
  groups: {},
  softKeywords: [],
};
