// AUTO-GENERATED FILE - DO NOT EDIT
// Source: csharp11.0.tokens
// Regenerate with: grammar-tools compile-tokens csharp11.0.tokens
//
// This file embeds a TokenGrammar as native TypeScript object literals.
// Import it directly instead of reading and parsing the .tokens file at
// runtime.

import type { TokenGrammar } from "@coding-adventures/grammar-tools";

export const TOKEN_GRAMMAR: TokenGrammar = {
  version: 1,
  caseInsensitive: false,
  caseSensitive: true,
  definitions: [
    {
      name: "NAME",
      pattern: "[a-zA-Z_][a-zA-Z0-9_]*",
      isRegex: true,
      lineNumber: 63,
    },
    {
      name: "VERBATIM_NAME",
      pattern: "@[a-zA-Z_][a-zA-Z0-9_]*",
      isRegex: true,
      lineNumber: 64,
      alias: "NAME",
    },
    {
      name: "BINARY_ULONG",
      pattern: "0[bB]_?[01][01_]*([uU][lL]|[lL][uU])",
      isRegex: true,
      lineNumber: 87,
      alias: "NUMBER",
    },
    {
      name: "BINARY_LONG",
      pattern: "0[bB]_?[01][01_]*[lL]",
      isRegex: true,
      lineNumber: 88,
      alias: "NUMBER",
    },
    {
      name: "BINARY_UINT",
      pattern: "0[bB]_?[01][01_]*[uU]",
      isRegex: true,
      lineNumber: 89,
      alias: "NUMBER",
    },
    {
      name: "BINARY_NUMBER",
      pattern: "0[bB]_?[01][01_]*",
      isRegex: true,
      lineNumber: 90,
      alias: "NUMBER",
    },
    {
      name: "HEX_ULONG",
      pattern: "0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*([uU][lL]|[lL][uU])",
      isRegex: true,
      lineNumber: 91,
      alias: "NUMBER",
    },
    {
      name: "HEX_LONG",
      pattern: "0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*[lL]",
      isRegex: true,
      lineNumber: 92,
      alias: "NUMBER",
    },
    {
      name: "HEX_UINT",
      pattern: "0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*[uU]",
      isRegex: true,
      lineNumber: 93,
      alias: "NUMBER",
    },
    {
      name: "HEX_NUMBER",
      pattern: "0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*",
      isRegex: true,
      lineNumber: 94,
      alias: "NUMBER",
    },
    {
      name: "DECIMAL_FLOAT",
      pattern: "[0-9][0-9_]*\\.[0-9_]*([eE][+-]?[0-9][0-9_]*)?[fFdDmM]?",
      isRegex: true,
      lineNumber: 95,
      alias: "NUMBER",
    },
    {
      name: "LEADING_DOT_FLOAT",
      pattern: "\\.[0-9][0-9_]*([eE][+-]?[0-9][0-9_]*)?[fFdDmM]?",
      isRegex: true,
      lineNumber: 96,
      alias: "NUMBER",
    },
    {
      name: "SCI_NUMBER",
      pattern: "[0-9][0-9_]*[eE][+-]?[0-9][0-9_]*[fFdDmM]?",
      isRegex: true,
      lineNumber: 97,
      alias: "NUMBER",
    },
    {
      name: "ULONG_NUMBER",
      pattern: "[0-9][0-9_]*([uU][lL]|[lL][uU])",
      isRegex: true,
      lineNumber: 98,
      alias: "NUMBER",
    },
    {
      name: "LONG_NUMBER",
      pattern: "[0-9][0-9_]*[lL]",
      isRegex: true,
      lineNumber: 99,
      alias: "NUMBER",
    },
    {
      name: "UINT_NUMBER",
      pattern: "[0-9][0-9_]*[uU]",
      isRegex: true,
      lineNumber: 100,
      alias: "NUMBER",
    },
    {
      name: "FLOAT_SUFFIX",
      pattern: "[0-9][0-9_]*[fFdDmM]",
      isRegex: true,
      lineNumber: 101,
      alias: "NUMBER",
    },
    {
      name: "INT_NUMBER",
      pattern: "[0-9][0-9_]*",
      isRegex: true,
      lineNumber: 102,
      alias: "NUMBER",
    },
    {
      name: "RAW_INTERPOLATED_STRING",
      pattern: "\\${1,}\"\"\"[\\s\\S]*?\"\"\"+",
      isRegex: true,
      lineNumber: 166,
    },
    {
      name: "RAW_STRING",
      pattern: "\"\"\"[\\s\\S]*?\"\"\"+",
      isRegex: true,
      lineNumber: 167,
    },
    {
      name: "STRING",
      pattern: "\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 176,
    },
    {
      name: "VERBATIM_STRING",
      pattern: "@\"([^\"]|\"\")*\"",
      isRegex: true,
      lineNumber: 177,
    },
    {
      name: "INTERPOLATED_STRING",
      pattern: "\\$\"([^\"\\\\{]|\\\\.|\\{\\{|\\}\\})*\"",
      isRegex: true,
      lineNumber: 178,
    },
    {
      name: "INTERPOLATED_VERBATIM",
      pattern: "(\\$@|@\\$)\"([^\"{]|\"\"|\\{\\{|\\}\\})*\"",
      isRegex: true,
      lineNumber: 179,
    },
    {
      name: "CHAR",
      pattern: "'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 180,
    },
    {
      name: "UNSIGNED_RIGHT_SHIFT_EQUALS",
      pattern: ">>>=",
      isRegex: false,
      lineNumber: 218,
    },
    {
      name: "QUESTION_QUESTION_EQUALS",
      pattern: "??=",
      isRegex: false,
      lineNumber: 219,
    },
    {
      name: "NULL_CONDITIONAL_DOT",
      pattern: "?.",
      isRegex: false,
      lineNumber: 220,
    },
    {
      name: "NULL_CONDITIONAL_BRACKET",
      pattern: "?[",
      isRegex: false,
      lineNumber: 221,
    },
    {
      name: "NULL_COALESCING",
      pattern: "??",
      isRegex: false,
      lineNumber: 222,
    },
    {
      name: "LAMBDA_ARROW",
      pattern: "=>",
      isRegex: false,
      lineNumber: 223,
    },
    {
      name: "LEFT_SHIFT_EQUALS",
      pattern: "<<=",
      isRegex: false,
      lineNumber: 224,
    },
    {
      name: "RIGHT_SHIFT_EQUALS",
      pattern: ">>=",
      isRegex: false,
      lineNumber: 225,
    },
    {
      name: "UNSIGNED_RIGHT_SHIFT",
      pattern: ">>>",
      isRegex: false,
      lineNumber: 226,
    },
    {
      name: "DOT_DOT",
      pattern: "..",
      isRegex: false,
      lineNumber: 227,
    },
    {
      name: "EQUALS_EQUALS",
      pattern: "==",
      isRegex: false,
      lineNumber: 228,
    },
    {
      name: "NOT_EQUALS",
      pattern: "!=",
      isRegex: false,
      lineNumber: 229,
    },
    {
      name: "LESS_EQUALS",
      pattern: "<=",
      isRegex: false,
      lineNumber: 230,
    },
    {
      name: "GREATER_EQUALS",
      pattern: ">=",
      isRegex: false,
      lineNumber: 231,
    },
    {
      name: "AND_AND",
      pattern: "&&",
      isRegex: false,
      lineNumber: 232,
    },
    {
      name: "OR_OR",
      pattern: "||",
      isRegex: false,
      lineNumber: 233,
    },
    {
      name: "PLUS_PLUS",
      pattern: "++",
      isRegex: false,
      lineNumber: 234,
    },
    {
      name: "MINUS_MINUS",
      pattern: "--",
      isRegex: false,
      lineNumber: 235,
    },
    {
      name: "PLUS_EQUALS",
      pattern: "+=",
      isRegex: false,
      lineNumber: 236,
    },
    {
      name: "MINUS_EQUALS",
      pattern: "-=",
      isRegex: false,
      lineNumber: 237,
    },
    {
      name: "STAR_EQUALS",
      pattern: "*=",
      isRegex: false,
      lineNumber: 238,
    },
    {
      name: "SLASH_EQUALS",
      pattern: "/=",
      isRegex: false,
      lineNumber: 239,
    },
    {
      name: "PERCENT_EQUALS",
      pattern: "%=",
      isRegex: false,
      lineNumber: 240,
    },
    {
      name: "AMPERSAND_EQUALS",
      pattern: "&=",
      isRegex: false,
      lineNumber: 241,
    },
    {
      name: "PIPE_EQUALS",
      pattern: "|=",
      isRegex: false,
      lineNumber: 242,
    },
    {
      name: "CARET_EQUALS",
      pattern: "^=",
      isRegex: false,
      lineNumber: 243,
    },
    {
      name: "LEFT_SHIFT",
      pattern: "<<",
      isRegex: false,
      lineNumber: 244,
    },
    {
      name: "RIGHT_SHIFT",
      pattern: ">>",
      isRegex: false,
      lineNumber: 245,
    },
    {
      name: "COLON_COLON",
      pattern: "::",
      isRegex: false,
      lineNumber: 246,
    },
    {
      name: "ARROW",
      pattern: "->",
      isRegex: false,
      lineNumber: 247,
    },
    {
      name: "EQUALS",
      pattern: "=",
      isRegex: false,
      lineNumber: 258,
    },
    {
      name: "PLUS",
      pattern: "+",
      isRegex: false,
      lineNumber: 259,
    },
    {
      name: "MINUS",
      pattern: "-",
      isRegex: false,
      lineNumber: 260,
    },
    {
      name: "STAR",
      pattern: "*",
      isRegex: false,
      lineNumber: 261,
    },
    {
      name: "SLASH",
      pattern: "/",
      isRegex: false,
      lineNumber: 262,
    },
    {
      name: "PERCENT",
      pattern: "%",
      isRegex: false,
      lineNumber: 263,
    },
    {
      name: "LESS_THAN",
      pattern: "<",
      isRegex: false,
      lineNumber: 264,
    },
    {
      name: "GREATER_THAN",
      pattern: ">",
      isRegex: false,
      lineNumber: 265,
    },
    {
      name: "BANG",
      pattern: "!",
      isRegex: false,
      lineNumber: 266,
    },
    {
      name: "AMPERSAND",
      pattern: "&",
      isRegex: false,
      lineNumber: 267,
    },
    {
      name: "PIPE",
      pattern: "|",
      isRegex: false,
      lineNumber: 268,
    },
    {
      name: "CARET",
      pattern: "^",
      isRegex: false,
      lineNumber: 269,
    },
    {
      name: "TILDE",
      pattern: "~",
      isRegex: false,
      lineNumber: 270,
    },
    {
      name: "QUESTION",
      pattern: "?",
      isRegex: false,
      lineNumber: 271,
    },
    {
      name: "LPAREN",
      pattern: "(",
      isRegex: false,
      lineNumber: 279,
    },
    {
      name: "RPAREN",
      pattern: ")",
      isRegex: false,
      lineNumber: 280,
    },
    {
      name: "LBRACE",
      pattern: "{",
      isRegex: false,
      lineNumber: 281,
    },
    {
      name: "RBRACE",
      pattern: "}",
      isRegex: false,
      lineNumber: 282,
    },
    {
      name: "LBRACKET",
      pattern: "[",
      isRegex: false,
      lineNumber: 283,
    },
    {
      name: "RBRACKET",
      pattern: "]",
      isRegex: false,
      lineNumber: 284,
    },
    {
      name: "SEMICOLON",
      pattern: ";",
      isRegex: false,
      lineNumber: 285,
    },
    {
      name: "COMMA",
      pattern: ",",
      isRegex: false,
      lineNumber: 286,
    },
    {
      name: "DOT",
      pattern: ".",
      isRegex: false,
      lineNumber: 287,
    },
    {
      name: "COLON",
      pattern: ":",
      isRegex: false,
      lineNumber: 288,
    },
    {
      name: "PP_NULLABLE",
      pattern: "#\\s*nullable\\b[^\\n]*",
      isRegex: true,
      lineNumber: 442,
    },
    {
      name: "PP_IF",
      pattern: "#\\s*if\\b[^\\n]*",
      isRegex: true,
      lineNumber: 443,
    },
    {
      name: "PP_ELIF",
      pattern: "#\\s*elif\\b[^\\n]*",
      isRegex: true,
      lineNumber: 444,
    },
    {
      name: "PP_ELSE",
      pattern: "#\\s*else\\b[^\\n]*",
      isRegex: true,
      lineNumber: 445,
    },
    {
      name: "PP_ENDIF",
      pattern: "#\\s*endif\\b[^\\n]*",
      isRegex: true,
      lineNumber: 446,
    },
    {
      name: "PP_DEFINE",
      pattern: "#\\s*define\\b[^\\n]*",
      isRegex: true,
      lineNumber: 447,
    },
    {
      name: "PP_UNDEF",
      pattern: "#\\s*undef\\b[^\\n]*",
      isRegex: true,
      lineNumber: 448,
    },
    {
      name: "PP_REGION",
      pattern: "#\\s*region\\b[^\\n]*",
      isRegex: true,
      lineNumber: 449,
    },
    {
      name: "PP_ENDREGION",
      pattern: "#\\s*endregion\\b[^\\n]*",
      isRegex: true,
      lineNumber: 450,
    },
    {
      name: "PP_ERROR",
      pattern: "#\\s*error\\b[^\\n]*",
      isRegex: true,
      lineNumber: 451,
    },
    {
      name: "PP_WARNING",
      pattern: "#\\s*warning\\b[^\\n]*",
      isRegex: true,
      lineNumber: 452,
    },
    {
      name: "PP_LINE",
      pattern: "#\\s*line\\b[^\\n]*",
      isRegex: true,
      lineNumber: 453,
    },
    {
      name: "PP_PRAGMA",
      pattern: "#\\s*pragma\\b[^\\n]*",
      isRegex: true,
      lineNumber: 454,
    },
  ],
  keywords: ["abstract","as","async","await","base","bool","break","byte","case","catch","char","checked","class","const","continue","decimal","default","delegate","do","double","else","enum","event","explicit","extern","false","finally","fixed","float","for","foreach","goto","if","implicit","in","int","interface","internal","is","lock","long","namespace","new","null","object","operator","out","override","params","private","protected","public","readonly","ref","return","sbyte","sealed","short","sizeof","stackalloc","static","string","struct","switch","this","throw","true","try","typeof","uint","ulong","unchecked","unsafe","ushort","using","virtual","void","volatile","while"],
  mode: undefined,
  escapeMode: undefined,
  skipDefinitions: [
    {
      name: "WHITESPACE",
      pattern: "[ \\t\\r\\n\\v\\f]+",
      isRegex: true,
      lineNumber: 425,
    },
    {
      name: "LINE_COMMENT",
      pattern: "\\/\\/[^\\n]*",
      isRegex: true,
      lineNumber: 426,
    },
    {
      name: "BLOCK_COMMENT",
      pattern: "\\/\\*([^*]|\\*[^\\/])*\\*\\/",
      isRegex: true,
      lineNumber: 427,
    },
  ],
  reservedKeywords: [],
  layoutKeywords: [],
  contextKeywords: [],
  errorDefinitions: [],
  groups: {},
  softKeywords: [],
};
