// AUTO-GENERATED FILE - DO NOT EDIT
// Source: csharp7.0.tokens
// Regenerate with: grammar-tools compile-tokens csharp7.0.tokens
//
// This file embeds a TokenGrammar as native TypeScript object literals.
// Import it directly instead of reading and parsing the .tokens file at
// runtime.

import type { TokenGrammar } from "@coding-adventures/grammar-tools";

export const TOKEN_GRAMMAR: TokenGrammar = {
  version: 1,
  caseInsensitive: false,
  caseSensitive: true,
  definitions: [
    {
      name: "NAME",
      pattern: "[a-zA-Z_][a-zA-Z0-9_]*",
      isRegex: true,
      lineNumber: 100,
    },
    {
      name: "VERBATIM_NAME",
      pattern: "@[a-zA-Z_][a-zA-Z0-9_]*",
      isRegex: true,
      lineNumber: 101,
      alias: "NAME",
    },
    {
      name: "BINARY_ULONG",
      pattern: "0[bB]_?[01][01_]*([uU][lL]|[lL][uU])",
      isRegex: true,
      lineNumber: 142,
      alias: "NUMBER",
    },
    {
      name: "BINARY_LONG",
      pattern: "0[bB]_?[01][01_]*[lL]",
      isRegex: true,
      lineNumber: 143,
      alias: "NUMBER",
    },
    {
      name: "BINARY_UINT",
      pattern: "0[bB]_?[01][01_]*[uU]",
      isRegex: true,
      lineNumber: 144,
      alias: "NUMBER",
    },
    {
      name: "BINARY_NUMBER",
      pattern: "0[bB]_?[01][01_]*",
      isRegex: true,
      lineNumber: 145,
      alias: "NUMBER",
    },
    {
      name: "HEX_ULONG",
      pattern: "0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*([uU][lL]|[lL][uU])",
      isRegex: true,
      lineNumber: 146,
      alias: "NUMBER",
    },
    {
      name: "HEX_LONG",
      pattern: "0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*[lL]",
      isRegex: true,
      lineNumber: 147,
      alias: "NUMBER",
    },
    {
      name: "HEX_UINT",
      pattern: "0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*[uU]",
      isRegex: true,
      lineNumber: 148,
      alias: "NUMBER",
    },
    {
      name: "HEX_NUMBER",
      pattern: "0[xX]_?[0-9a-fA-F][0-9a-fA-F_]*",
      isRegex: true,
      lineNumber: 149,
      alias: "NUMBER",
    },
    {
      name: "DECIMAL_FLOAT",
      pattern: "[0-9][0-9_]*\\.[0-9_]*([eE][+-]?[0-9][0-9_]*)?[fFdDmM]?",
      isRegex: true,
      lineNumber: 150,
      alias: "NUMBER",
    },
    {
      name: "LEADING_DOT_FLOAT",
      pattern: "\\.[0-9][0-9_]*([eE][+-]?[0-9][0-9_]*)?[fFdDmM]?",
      isRegex: true,
      lineNumber: 151,
      alias: "NUMBER",
    },
    {
      name: "SCI_NUMBER",
      pattern: "[0-9][0-9_]*[eE][+-]?[0-9][0-9_]*[fFdDmM]?",
      isRegex: true,
      lineNumber: 152,
      alias: "NUMBER",
    },
    {
      name: "ULONG_NUMBER",
      pattern: "[0-9][0-9_]*([uU][lL]|[lL][uU])",
      isRegex: true,
      lineNumber: 153,
      alias: "NUMBER",
    },
    {
      name: "LONG_NUMBER",
      pattern: "[0-9][0-9_]*[lL]",
      isRegex: true,
      lineNumber: 154,
      alias: "NUMBER",
    },
    {
      name: "UINT_NUMBER",
      pattern: "[0-9][0-9_]*[uU]",
      isRegex: true,
      lineNumber: 155,
      alias: "NUMBER",
    },
    {
      name: "FLOAT_SUFFIX",
      pattern: "[0-9][0-9_]*[fFdDmM]",
      isRegex: true,
      lineNumber: 156,
      alias: "NUMBER",
    },
    {
      name: "INT_NUMBER",
      pattern: "[0-9][0-9_]*",
      isRegex: true,
      lineNumber: 157,
      alias: "NUMBER",
    },
    {
      name: "INTERPOLATED_STRING",
      pattern: "\\$\"([^\"\\\\{]|\\\\.|\\{\\{|\\}\\})*\"",
      isRegex: true,
      lineNumber: 177,
    },
    {
      name: "INTERPOLATED_VERBATIM",
      pattern: "(\\$@|@\\$)\"([^\"{]|\"\"|\\{\\{|\\}\\})*\"",
      isRegex: true,
      lineNumber: 178,
    },
    {
      name: "STRING",
      pattern: "\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 179,
    },
    {
      name: "VERBATIM_STRING",
      pattern: "@\"([^\"]|\"\")*\"",
      isRegex: true,
      lineNumber: 180,
    },
    {
      name: "CHAR",
      pattern: "'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 181,
    },
    {
      name: "NULL_COALESCE",
      pattern: "??",
      isRegex: false,
      lineNumber: 208,
    },
    {
      name: "NULL_CONDITIONAL_DOT",
      pattern: "?.",
      isRegex: false,
      lineNumber: 209,
    },
    {
      name: "NULL_CONDITIONAL_BRACKET",
      pattern: "?[",
      isRegex: false,
      lineNumber: 210,
    },
    {
      name: "LEFT_SHIFT_EQUALS",
      pattern: "<<=",
      isRegex: false,
      lineNumber: 211,
    },
    {
      name: "RIGHT_SHIFT_EQUALS",
      pattern: ">>=",
      isRegex: false,
      lineNumber: 212,
    },
    {
      name: "LAMBDA",
      pattern: "=>",
      isRegex: false,
      lineNumber: 213,
    },
    {
      name: "EQUALS_EQUALS",
      pattern: "==",
      isRegex: false,
      lineNumber: 214,
    },
    {
      name: "NOT_EQUALS",
      pattern: "!=",
      isRegex: false,
      lineNumber: 215,
    },
    {
      name: "LESS_EQUALS",
      pattern: "<=",
      isRegex: false,
      lineNumber: 216,
    },
    {
      name: "GREATER_EQUALS",
      pattern: ">=",
      isRegex: false,
      lineNumber: 217,
    },
    {
      name: "AND_AND",
      pattern: "&&",
      isRegex: false,
      lineNumber: 218,
    },
    {
      name: "OR_OR",
      pattern: "||",
      isRegex: false,
      lineNumber: 219,
    },
    {
      name: "PLUS_PLUS",
      pattern: "++",
      isRegex: false,
      lineNumber: 220,
    },
    {
      name: "MINUS_MINUS",
      pattern: "--",
      isRegex: false,
      lineNumber: 221,
    },
    {
      name: "PLUS_EQUALS",
      pattern: "+=",
      isRegex: false,
      lineNumber: 222,
    },
    {
      name: "MINUS_EQUALS",
      pattern: "-=",
      isRegex: false,
      lineNumber: 223,
    },
    {
      name: "STAR_EQUALS",
      pattern: "*=",
      isRegex: false,
      lineNumber: 224,
    },
    {
      name: "SLASH_EQUALS",
      pattern: "/=",
      isRegex: false,
      lineNumber: 225,
    },
    {
      name: "PERCENT_EQUALS",
      pattern: "%=",
      isRegex: false,
      lineNumber: 226,
    },
    {
      name: "AMPERSAND_EQUALS",
      pattern: "&=",
      isRegex: false,
      lineNumber: 227,
    },
    {
      name: "PIPE_EQUALS",
      pattern: "|=",
      isRegex: false,
      lineNumber: 228,
    },
    {
      name: "CARET_EQUALS",
      pattern: "^=",
      isRegex: false,
      lineNumber: 229,
    },
    {
      name: "LEFT_SHIFT",
      pattern: "<<",
      isRegex: false,
      lineNumber: 230,
    },
    {
      name: "RIGHT_SHIFT",
      pattern: ">>",
      isRegex: false,
      lineNumber: 231,
    },
    {
      name: "NAMESPACE_ALIAS",
      pattern: "::",
      isRegex: false,
      lineNumber: 232,
    },
    {
      name: "ARROW",
      pattern: "->",
      isRegex: false,
      lineNumber: 233,
    },
    {
      name: "EQUALS",
      pattern: "=",
      isRegex: false,
      lineNumber: 241,
    },
    {
      name: "PLUS",
      pattern: "+",
      isRegex: false,
      lineNumber: 242,
    },
    {
      name: "MINUS",
      pattern: "-",
      isRegex: false,
      lineNumber: 243,
    },
    {
      name: "STAR",
      pattern: "*",
      isRegex: false,
      lineNumber: 244,
    },
    {
      name: "SLASH",
      pattern: "/",
      isRegex: false,
      lineNumber: 245,
    },
    {
      name: "PERCENT",
      pattern: "%",
      isRegex: false,
      lineNumber: 246,
    },
    {
      name: "LESS_THAN",
      pattern: "<",
      isRegex: false,
      lineNumber: 247,
    },
    {
      name: "GREATER_THAN",
      pattern: ">",
      isRegex: false,
      lineNumber: 248,
    },
    {
      name: "BANG",
      pattern: "!",
      isRegex: false,
      lineNumber: 249,
    },
    {
      name: "AMPERSAND",
      pattern: "&",
      isRegex: false,
      lineNumber: 250,
    },
    {
      name: "PIPE",
      pattern: "|",
      isRegex: false,
      lineNumber: 251,
    },
    {
      name: "CARET",
      pattern: "^",
      isRegex: false,
      lineNumber: 252,
    },
    {
      name: "TILDE",
      pattern: "~",
      isRegex: false,
      lineNumber: 253,
    },
    {
      name: "QUESTION",
      pattern: "?",
      isRegex: false,
      lineNumber: 254,
    },
    {
      name: "LPAREN",
      pattern: "(",
      isRegex: false,
      lineNumber: 260,
    },
    {
      name: "RPAREN",
      pattern: ")",
      isRegex: false,
      lineNumber: 261,
    },
    {
      name: "LBRACE",
      pattern: "{",
      isRegex: false,
      lineNumber: 262,
    },
    {
      name: "RBRACE",
      pattern: "}",
      isRegex: false,
      lineNumber: 263,
    },
    {
      name: "LBRACKET",
      pattern: "[",
      isRegex: false,
      lineNumber: 264,
    },
    {
      name: "RBRACKET",
      pattern: "]",
      isRegex: false,
      lineNumber: 265,
    },
    {
      name: "SEMICOLON",
      pattern: ";",
      isRegex: false,
      lineNumber: 266,
    },
    {
      name: "COMMA",
      pattern: ",",
      isRegex: false,
      lineNumber: 267,
    },
    {
      name: "DOT",
      pattern: ".",
      isRegex: false,
      lineNumber: 268,
    },
    {
      name: "COLON",
      pattern: ":",
      isRegex: false,
      lineNumber: 269,
    },
    {
      name: "PP_IF",
      pattern: "#\\s*if\\b[^\\n]*",
      isRegex: true,
      lineNumber: 400,
    },
    {
      name: "PP_ELIF",
      pattern: "#\\s*elif\\b[^\\n]*",
      isRegex: true,
      lineNumber: 401,
    },
    {
      name: "PP_ELSE",
      pattern: "#\\s*else\\b[^\\n]*",
      isRegex: true,
      lineNumber: 402,
    },
    {
      name: "PP_ENDIF",
      pattern: "#\\s*endif\\b[^\\n]*",
      isRegex: true,
      lineNumber: 403,
    },
    {
      name: "PP_DEFINE",
      pattern: "#\\s*define\\b[^\\n]*",
      isRegex: true,
      lineNumber: 404,
    },
    {
      name: "PP_UNDEF",
      pattern: "#\\s*undef\\b[^\\n]*",
      isRegex: true,
      lineNumber: 405,
    },
    {
      name: "PP_REGION",
      pattern: "#\\s*region\\b[^\\n]*",
      isRegex: true,
      lineNumber: 406,
    },
    {
      name: "PP_ENDREGION",
      pattern: "#\\s*endregion\\b[^\\n]*",
      isRegex: true,
      lineNumber: 407,
    },
    {
      name: "PP_ERROR",
      pattern: "#\\s*error\\b[^\\n]*",
      isRegex: true,
      lineNumber: 408,
    },
    {
      name: "PP_WARNING",
      pattern: "#\\s*warning\\b[^\\n]*",
      isRegex: true,
      lineNumber: 409,
    },
    {
      name: "PP_LINE",
      pattern: "#\\s*line\\b[^\\n]*",
      isRegex: true,
      lineNumber: 410,
    },
    {
      name: "PP_PRAGMA",
      pattern: "#\\s*pragma\\b[^\\n]*",
      isRegex: true,
      lineNumber: 411,
    },
  ],
  keywords: ["abstract","as","async","await","base","bool","break","byte","case","catch","char","checked","class","const","continue","decimal","default","delegate","do","double","else","enum","event","explicit","extern","false","finally","fixed","float","for","foreach","goto","if","implicit","in","int","interface","internal","is","lock","long","namespace","new","null","object","operator","out","override","params","private","protected","public","readonly","ref","return","sbyte","sealed","short","sizeof","stackalloc","static","string","struct","switch","this","throw","true","try","typeof","uint","ulong","unchecked","unsafe","ushort","using","virtual","void","volatile","while"],
  mode: undefined,
  escapeMode: undefined,
  skipDefinitions: [
    {
      name: "WHITESPACE",
      pattern: "[ \\t\\r\\n\\v\\f]+",
      isRegex: true,
      lineNumber: 390,
    },
    {
      name: "LINE_COMMENT",
      pattern: "\\/\\/[^\\n]*",
      isRegex: true,
      lineNumber: 391,
    },
    {
      name: "BLOCK_COMMENT",
      pattern: "\\/\\*([^*]|\\*[^\\/])*\\*\\/",
      isRegex: true,
      lineNumber: 392,
    },
  ],
  reservedKeywords: [],
  layoutKeywords: [],
  contextKeywords: [],
  errorDefinitions: [],
  groups: {},
  softKeywords: [],
};
