// AUTO-GENERATED FILE - DO NOT EDIT
// Source: csharp2.0.tokens
// Regenerate with: grammar-tools compile-tokens csharp2.0.tokens
//
// This file embeds a TokenGrammar as native TypeScript object literals.
// Import it directly instead of reading and parsing the .tokens file at
// runtime.

import type { TokenGrammar } from "@coding-adventures/grammar-tools";

export const TOKEN_GRAMMAR: TokenGrammar = {
  version: 1,
  caseInsensitive: false,
  caseSensitive: true,
  definitions: [
    {
      name: "NAME",
      pattern: "[a-zA-Z_][a-zA-Z0-9_]*",
      isRegex: true,
      lineNumber: 88,
    },
    {
      name: "VERBATIM_NAME",
      pattern: "@[a-zA-Z_][a-zA-Z0-9_]*",
      isRegex: true,
      lineNumber: 89,
      alias: "NAME",
    },
    {
      name: "HEX_ULONG",
      pattern: "0[xX][0-9a-fA-F]+([uU][lL]|[lL][uU])",
      isRegex: true,
      lineNumber: 98,
      alias: "NUMBER",
    },
    {
      name: "HEX_LONG",
      pattern: "0[xX][0-9a-fA-F]+[lL]",
      isRegex: true,
      lineNumber: 99,
      alias: "NUMBER",
    },
    {
      name: "HEX_UINT",
      pattern: "0[xX][0-9a-fA-F]+[uU]",
      isRegex: true,
      lineNumber: 100,
      alias: "NUMBER",
    },
    {
      name: "HEX_NUMBER",
      pattern: "0[xX][0-9a-fA-F]+",
      isRegex: true,
      lineNumber: 101,
      alias: "NUMBER",
    },
    {
      name: "DECIMAL_FLOAT",
      pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?[fFdDmM]?",
      isRegex: true,
      lineNumber: 102,
      alias: "NUMBER",
    },
    {
      name: "LEADING_DOT_FLOAT",
      pattern: "\\.[0-9]+([eE][+-]?[0-9]+)?[fFdDmM]?",
      isRegex: true,
      lineNumber: 103,
      alias: "NUMBER",
    },
    {
      name: "SCI_NUMBER",
      pattern: "[0-9]+[eE][+-]?[0-9]+[fFdDmM]?",
      isRegex: true,
      lineNumber: 104,
      alias: "NUMBER",
    },
    {
      name: "ULONG_NUMBER",
      pattern: "[0-9]+([uU][lL]|[lL][uU])",
      isRegex: true,
      lineNumber: 105,
      alias: "NUMBER",
    },
    {
      name: "LONG_NUMBER",
      pattern: "[0-9]+[lL]",
      isRegex: true,
      lineNumber: 106,
      alias: "NUMBER",
    },
    {
      name: "UINT_NUMBER",
      pattern: "[0-9]+[uU]",
      isRegex: true,
      lineNumber: 107,
      alias: "NUMBER",
    },
    {
      name: "FLOAT_SUFFIX",
      pattern: "[0-9]+[fFdDmM]",
      isRegex: true,
      lineNumber: 108,
      alias: "NUMBER",
    },
    {
      name: "INT_NUMBER",
      pattern: "[0-9]+",
      isRegex: true,
      lineNumber: 109,
      alias: "NUMBER",
    },
    {
      name: "STRING",
      pattern: "\"([^\"\\\\]|\\\\.)*\"",
      isRegex: true,
      lineNumber: 118,
    },
    {
      name: "VERBATIM_STRING",
      pattern: "@\"([^\"]|\"\")*\"",
      isRegex: true,
      lineNumber: 119,
    },
    {
      name: "CHAR",
      pattern: "'([^'\\\\]|\\\\.)*'",
      isRegex: true,
      lineNumber: 120,
    },
    {
      name: "COLON_COLON",
      pattern: "::",
      isRegex: false,
      lineNumber: 154,
    },
    {
      name: "LEFT_SHIFT_EQUALS",
      pattern: "<<=",
      isRegex: false,
      lineNumber: 155,
    },
    {
      name: "RIGHT_SHIFT_EQUALS",
      pattern: ">>=",
      isRegex: false,
      lineNumber: 156,
    },
    {
      name: "EQUALS_EQUALS",
      pattern: "==",
      isRegex: false,
      lineNumber: 157,
    },
    {
      name: "NOT_EQUALS",
      pattern: "!=",
      isRegex: false,
      lineNumber: 158,
    },
    {
      name: "LESS_EQUALS",
      pattern: "<=",
      isRegex: false,
      lineNumber: 159,
    },
    {
      name: "GREATER_EQUALS",
      pattern: ">=",
      isRegex: false,
      lineNumber: 160,
    },
    {
      name: "AND_AND",
      pattern: "&&",
      isRegex: false,
      lineNumber: 161,
    },
    {
      name: "OR_OR",
      pattern: "||",
      isRegex: false,
      lineNumber: 162,
    },
    {
      name: "PLUS_PLUS",
      pattern: "++",
      isRegex: false,
      lineNumber: 163,
    },
    {
      name: "MINUS_MINUS",
      pattern: "--",
      isRegex: false,
      lineNumber: 164,
    },
    {
      name: "PLUS_EQUALS",
      pattern: "+=",
      isRegex: false,
      lineNumber: 165,
    },
    {
      name: "MINUS_EQUALS",
      pattern: "-=",
      isRegex: false,
      lineNumber: 166,
    },
    {
      name: "STAR_EQUALS",
      pattern: "*=",
      isRegex: false,
      lineNumber: 167,
    },
    {
      name: "SLASH_EQUALS",
      pattern: "/=",
      isRegex: false,
      lineNumber: 168,
    },
    {
      name: "PERCENT_EQUALS",
      pattern: "%=",
      isRegex: false,
      lineNumber: 169,
    },
    {
      name: "AMPERSAND_EQUALS",
      pattern: "&=",
      isRegex: false,
      lineNumber: 170,
    },
    {
      name: "PIPE_EQUALS",
      pattern: "|=",
      isRegex: false,
      lineNumber: 171,
    },
    {
      name: "CARET_EQUALS",
      pattern: "^=",
      isRegex: false,
      lineNumber: 172,
    },
    {
      name: "LEFT_SHIFT",
      pattern: "<<",
      isRegex: false,
      lineNumber: 173,
    },
    {
      name: "RIGHT_SHIFT",
      pattern: ">>",
      isRegex: false,
      lineNumber: 174,
    },
    {
      name: "QUESTION_QUESTION",
      pattern: "??",
      isRegex: false,
      lineNumber: 175,
    },
    {
      name: "ARROW",
      pattern: "->",
      isRegex: false,
      lineNumber: 176,
    },
    {
      name: "EQUALS",
      pattern: "=",
      isRegex: false,
      lineNumber: 191,
    },
    {
      name: "PLUS",
      pattern: "+",
      isRegex: false,
      lineNumber: 192,
    },
    {
      name: "MINUS",
      pattern: "-",
      isRegex: false,
      lineNumber: 193,
    },
    {
      name: "STAR",
      pattern: "*",
      isRegex: false,
      lineNumber: 194,
    },
    {
      name: "SLASH",
      pattern: "/",
      isRegex: false,
      lineNumber: 195,
    },
    {
      name: "PERCENT",
      pattern: "%",
      isRegex: false,
      lineNumber: 196,
    },
    {
      name: "LESS_THAN",
      pattern: "<",
      isRegex: false,
      lineNumber: 197,
    },
    {
      name: "GREATER_THAN",
      pattern: ">",
      isRegex: false,
      lineNumber: 198,
    },
    {
      name: "BANG",
      pattern: "!",
      isRegex: false,
      lineNumber: 199,
    },
    {
      name: "AMPERSAND",
      pattern: "&",
      isRegex: false,
      lineNumber: 200,
    },
    {
      name: "PIPE",
      pattern: "|",
      isRegex: false,
      lineNumber: 201,
    },
    {
      name: "CARET",
      pattern: "^",
      isRegex: false,
      lineNumber: 202,
    },
    {
      name: "TILDE",
      pattern: "~",
      isRegex: false,
      lineNumber: 203,
    },
    {
      name: "QUESTION",
      pattern: "?",
      isRegex: false,
      lineNumber: 204,
    },
    {
      name: "LPAREN",
      pattern: "(",
      isRegex: false,
      lineNumber: 212,
    },
    {
      name: "RPAREN",
      pattern: ")",
      isRegex: false,
      lineNumber: 213,
    },
    {
      name: "LBRACE",
      pattern: "{",
      isRegex: false,
      lineNumber: 214,
    },
    {
      name: "RBRACE",
      pattern: "}",
      isRegex: false,
      lineNumber: 215,
    },
    {
      name: "LBRACKET",
      pattern: "[",
      isRegex: false,
      lineNumber: 216,
    },
    {
      name: "RBRACKET",
      pattern: "]",
      isRegex: false,
      lineNumber: 217,
    },
    {
      name: "SEMICOLON",
      pattern: ";",
      isRegex: false,
      lineNumber: 218,
    },
    {
      name: "COMMA",
      pattern: ",",
      isRegex: false,
      lineNumber: 219,
    },
    {
      name: "DOT",
      pattern: ".",
      isRegex: false,
      lineNumber: 220,
    },
    {
      name: "COLON",
      pattern: ":",
      isRegex: false,
      lineNumber: 221,
    },
    {
      name: "PP_IF",
      pattern: "#\\s*if\\b[^\\n]*",
      isRegex: true,
      lineNumber: 350,
    },
    {
      name: "PP_ELIF",
      pattern: "#\\s*elif\\b[^\\n]*",
      isRegex: true,
      lineNumber: 351,
    },
    {
      name: "PP_ELSE",
      pattern: "#\\s*else\\b[^\\n]*",
      isRegex: true,
      lineNumber: 352,
    },
    {
      name: "PP_ENDIF",
      pattern: "#\\s*endif\\b[^\\n]*",
      isRegex: true,
      lineNumber: 353,
    },
    {
      name: "PP_DEFINE",
      pattern: "#\\s*define\\b[^\\n]*",
      isRegex: true,
      lineNumber: 354,
    },
    {
      name: "PP_UNDEF",
      pattern: "#\\s*undef\\b[^\\n]*",
      isRegex: true,
      lineNumber: 355,
    },
    {
      name: "PP_REGION",
      pattern: "#\\s*region\\b[^\\n]*",
      isRegex: true,
      lineNumber: 356,
    },
    {
      name: "PP_ENDREGION",
      pattern: "#\\s*endregion\\b[^\\n]*",
      isRegex: true,
      lineNumber: 357,
    },
    {
      name: "PP_ERROR",
      pattern: "#\\s*error\\b[^\\n]*",
      isRegex: true,
      lineNumber: 358,
    },
    {
      name: "PP_WARNING",
      pattern: "#\\s*warning\\b[^\\n]*",
      isRegex: true,
      lineNumber: 359,
    },
    {
      name: "PP_LINE",
      pattern: "#\\s*line\\b[^\\n]*",
      isRegex: true,
      lineNumber: 360,
    },
    {
      name: "PP_PRAGMA",
      pattern: "#\\s*pragma\\b[^\\n]*",
      isRegex: true,
      lineNumber: 361,
    },
  ],
  keywords: ["abstract","as","base","bool","break","byte","case","catch","char","checked","class","const","continue","decimal","default","delegate","do","double","else","enum","event","explicit","extern","false","finally","fixed","float","for","foreach","goto","if","implicit","in","int","interface","internal","is","lock","long","namespace","new","null","object","operator","out","override","params","private","protected","public","readonly","ref","return","sbyte","sealed","short","sizeof","stackalloc","static","string","struct","switch","this","throw","true","try","typeof","uint","ulong","unchecked","unsafe","ushort","using","virtual","void","volatile","while","yield"],
  mode: undefined,
  escapeMode: undefined,
  skipDefinitions: [
    {
      name: "WHITESPACE",
      pattern: "[ \\t\\r\\n\\v\\f]+",
      isRegex: true,
      lineNumber: 340,
    },
    {
      name: "LINE_COMMENT",
      pattern: "\\/\\/[^\\n]*",
      isRegex: true,
      lineNumber: 341,
    },
    {
      name: "BLOCK_COMMENT",
      pattern: "\\/\\*([^*]|\\*[^\\/])*\\*\\/",
      isRegex: true,
      lineNumber: 342,
    },
  ],
  reservedKeywords: [],
  layoutKeywords: [],
  contextKeywords: [],
  errorDefinitions: [],
  groups: {},
  softKeywords: [],
};
