load("code/packages/starlark/program-rules/ruby_binary.star", "ruby_binary")

_targets = [
    ruby_binary(
        name = "scaffold-generator",
        srcs = ["lib/**/*.rb", "*.rb"],
        deps = [],
    ),
]
