// GENERATED by code/scripts/generate_atbash_fixture_consumers.py.
// Source SHA-256: efd6c3a85a0c1d0676c31bf709d7c3d7eb5f4aef6b31ac2f904ebad6d76ad02c
// Cases: classical-ciphers-v1-atbash-empty, classical-ciphers-v1-atbash-uppercase-alphabet, classical-ciphers-v1-atbash-lowercase-alphabet, classical-ciphers-v1-atbash-passthrough, classical-ciphers-v1-atbash-involution-forward, classical-ciphers-v1-atbash-involution-reverse

use atbash_cipher::encrypt;

#[test]
fn executes_complete_normative_atbash_objects() {
    let cases = [
        ("classical-ciphers-v1-atbash-empty", "", ""),
        ("classical-ciphers-v1-atbash-uppercase-alphabet", "\u{41}\u{42}\u{43}\u{44}\u{45}\u{46}\u{47}\u{48}\u{49}\u{4a}\u{4b}\u{4c}\u{4d}\u{4e}\u{4f}\u{50}\u{51}\u{52}\u{53}\u{54}\u{55}\u{56}\u{57}\u{58}\u{59}\u{5a}", "\u{5a}\u{59}\u{58}\u{57}\u{56}\u{55}\u{54}\u{53}\u{52}\u{51}\u{50}\u{4f}\u{4e}\u{4d}\u{4c}\u{4b}\u{4a}\u{49}\u{48}\u{47}\u{46}\u{45}\u{44}\u{43}\u{42}\u{41}"),
        ("classical-ciphers-v1-atbash-lowercase-alphabet", "\u{61}\u{62}\u{63}\u{64}\u{65}\u{66}\u{67}\u{68}\u{69}\u{6a}\u{6b}\u{6c}\u{6d}\u{6e}\u{6f}\u{70}\u{71}\u{72}\u{73}\u{74}\u{75}\u{76}\u{77}\u{78}\u{79}\u{7a}", "\u{7a}\u{79}\u{78}\u{77}\u{76}\u{75}\u{74}\u{73}\u{72}\u{71}\u{70}\u{6f}\u{6e}\u{6d}\u{6c}\u{6b}\u{6a}\u{69}\u{68}\u{67}\u{66}\u{65}\u{64}\u{63}\u{62}\u{61}"),
        ("classical-ciphers-v1-atbash-passthrough", "\u{48}\u{65}\u{6c}\u{6c}\u{6f}\u{2c}\u{20}\u{57}\u{6f}\u{72}\u{6c}\u{64}\u{21}\u{20}\u{31}\u{32}\u{33}\u{0}\u{20}\u{e9}\u{1f600}", "\u{53}\u{76}\u{6f}\u{6f}\u{6c}\u{2c}\u{20}\u{44}\u{6c}\u{69}\u{6f}\u{77}\u{21}\u{20}\u{31}\u{32}\u{33}\u{0}\u{20}\u{e9}\u{1f600}"),
        ("classical-ciphers-v1-atbash-involution-forward", "\u{48}\u{45}\u{4c}\u{4c}\u{4f}", "\u{53}\u{56}\u{4f}\u{4f}\u{4c}"),
        ("classical-ciphers-v1-atbash-involution-reverse", "\u{53}\u{56}\u{4f}\u{4f}\u{4c}", "\u{48}\u{45}\u{4c}\u{4c}\u{4f}"),
    ];
    for (case_id, input, expected) in cases {
        assert_eq!(encrypt(input), expected, "{case_id}");
    }
}
