// AUTO-GENERATED by Mosaic. Edits will be overwritten on next emit.
#include "MosaicHost.h"

#include <QCoreApplication>
#include <QDebug>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonParseError>
#include <QLocale>
#include <QSaveFile>
#include <QStandardPaths>
#include <QStringList>

#include <limits>
#include <stdexcept>

namespace {
template <typename T>
T resolve(QLibrary &library, const char *name)
{
    const auto symbol = library.resolve(name);
    if (!symbol) {
        throw std::runtime_error(QStringLiteral("missing Mosaic ABI symbol %1")
                                     .arg(QString::fromLatin1(name))
                                     .toStdString());
    }
    return reinterpret_cast<T>(symbol);
}

QString platformName()
{
#if defined(Q_OS_ANDROID)
    return QStringLiteral("android");
#elif defined(Q_OS_WIN)
    return QStringLiteral("windows");
#elif defined(Q_OS_MACOS) || defined(Q_OS_IOS)
    return QStringLiteral("apple");
#elif defined(Q_OS_LINUX)
    return QStringLiteral("linux");
#else
    return QStringLiteral("web");
#endif
}

QStringList libraryCandidates()
{
    const auto requested = qEnvironmentVariable("MOSAIC_APP_LIBRARY");
    if (!requested.trimmed().isEmpty()) return {requested};
#if defined(Q_OS_WIN)
    const auto fileName = QStringLiteral("mosaic_app.dll");
#elif defined(Q_OS_MACOS) || defined(Q_OS_IOS)
    const auto fileName = QStringLiteral("libmosaic_app.dylib");
#else
    const auto fileName = QStringLiteral("libmosaic_app.so");
#endif
    const auto bundled = QDir(QCoreApplication::applicationDirPath()).filePath(fileName);
    return {bundled, fileName, QStringLiteral("mosaic_app")};
}
}

MosaicHost::MosaicHost(QObject *parent)
    : QObject(parent)
{
    if (!load()) return;

    const auto restoredSnapshot = loadPersistedSnapshot();
    const auto createApplication = [this](const QVariant &snapshot) {
        const QVariantMap context{
            {QStringLiteral("protocolVersion"), ProtocolVersion},
            {QStringLiteral("locale"), QLocale::system().name().replace('_', '-')},
            {QStringLiteral("colorScheme"), QStringLiteral("system")},
            {QStringLiteral("textScale"), 1.0},
            {QStringLiteral("platform"), platformName()},
            {QStringLiteral("restoredSnapshot"), snapshot},
        };
        const auto encoded = QJsonDocument::fromVariant(context).toJson(QJsonDocument::Compact);
        Bytes input{reinterpret_cast<const unsigned char *>(encoded.constData()),
                    static_cast<size_t>(encoded.size())};
        Buffer output{};
        const auto status = create_(input, &app_, &output);
        return requireMap(consume(status, output), "startup update");
    };
    try {
        try {
            latestUpdate_ = createApplication(restoredSnapshot);
        } catch (const std::exception &exception) {
            if (!restoredSnapshot.isValid()) throw;
            if (app_ && destroy_) destroy_(app_);
            app_ = nullptr;
            quarantinePersistedState(
                QStringLiteral("Mosaic runtime rejected persisted state: %1")
                    .arg(QString::fromUtf8(exception.what())));
            latestUpdate_ = createApplication(QVariant());
        }
        latestUpdate_ = withPersistenceWarning(latestUpdate_);
        if (!app_) throw std::runtime_error("Mosaic runtime returned a null application handle");
    } catch (const std::exception &exception) {
        if (app_ && destroy_) destroy_(app_);
        app_ = nullptr;
        error_ = QString::fromUtf8(exception.what());
    }
}

MosaicHost::~MosaicHost()
{
    if (app_ && destroy_) destroy_(app_);
    app_ = nullptr;
    library_.unload();
}

void MosaicHost::registerTypes() {}

void MosaicHost::attach(QObject *root)
{
    Q_UNUSED(root);
}

void MosaicHost::requireRuntime() const
{
    if (app_) return;
    throw std::runtime_error(
        QStringLiteral("native-complete requires the Mosaic Rust application runtime: %1")
            .arg(error_.isEmpty() ? QStringLiteral("runtime unavailable") : error_)
            .toStdString());
}

void MosaicHost::configureRequiredProps(const QVariantMap &slotNames,
                                        const QStringList &requiredProps)
{
    requireRuntime();
    requiredSlotNames_ = slotNames;
    requiredProps_ = requiredProps;
}

QVariantMap MosaicHost::propsRequired() const
{
    requireRuntime();
    return requireAndMapUpdate(latestUpdate_, "startup update")
        .value(QStringLiteral("props"))
        .toMap();
}

QVariantMap MosaicHost::props() const
{
    return app_ ? latestUpdate_ : failure(error_);
}

QVariantMap MosaicHost::handleEvent(const QVariantMap &event)
{
    if (!app_) return failure(error_);
    const auto nameValue = event.contains(QStringLiteral("name"))
        ? event.value(QStringLiteral("name"))
        : event.value(QStringLiteral("event"));
    const auto name = nameValue.toString();
    if (name.isEmpty()) return failure(QStringLiteral("missing Mosaic event name"));
    if (sequence_ == std::numeric_limits<quint64>::max()) {
        return failure(QStringLiteral("Mosaic event sequence overflow"));
    }

    QVariant payload = event.value(QStringLiteral("payload"));
    if (!payload.isValid()) {
        auto fields = event;
        fields.remove(QStringLiteral("name"));
        fields.remove(QStringLiteral("event"));
        fields.remove(QStringLiteral("payload"));
        payload = fields;
    }
    const auto nextSequence = sequence_ + 1;
    const QVariantMap envelope{
        {QStringLiteral("protocolVersion"), ProtocolVersion},
        {QStringLiteral("sequence"), QVariant::fromValue(nextSequence)},
        {QStringLiteral("name"), name},
        {QStringLiteral("payload"), payload},
    };
    const auto encoded = QJsonDocument::fromVariant(envelope).toJson(QJsonDocument::Compact);
    Bytes input{reinterpret_cast<const unsigned char *>(encoded.constData()),
                static_cast<size_t>(encoded.size())};
    Buffer output{};
    try {
        const auto status = dispatch_(app_, input, &output);
        const auto update = requireMap(consume(status, output), "event update");
        sequence_ = nextSequence;
        persistSnapshot();
        latestUpdate_ = withPersistenceWarning(update);
        return latestUpdate_;
    } catch (const std::exception &exception) {
        return failure(QString::fromUtf8(exception.what()));
    }
}

QVariantMap MosaicHost::handleRequiredEvent(const QVariantMap &event)
{
    requireRuntime();
    const auto update = handleEvent(event);
    return requireAndMapUpdate(update, "event update");
}

QVariant MosaicHost::snapshot()
{
    if (!app_) return QVariant();
    Buffer output{};
    try {
        const auto status = snapshot_(app_, &output);
        return consume(status, output);
    } catch (const std::exception &exception) {
        error_ = QString::fromUtf8(exception.what());
        return QVariant();
    }
}

QVariantMap MosaicHost::restore(const QVariantMap &snapshot)
{
    if (!app_) return failure(error_);
    const auto encoded = QJsonDocument::fromVariant(snapshot).toJson(QJsonDocument::Compact);
    Bytes input{reinterpret_cast<const unsigned char *>(encoded.constData()),
                static_cast<size_t>(encoded.size())};
    Buffer output{};
    try {
        const auto status = restore_(app_, input, &output);
        latestUpdate_ = requireMap(consume(status, output),
                                   "restore update");
        return latestUpdate_;
    } catch (const std::exception &exception) {
        return failure(QString::fromUtf8(exception.what()));
    }
}

bool MosaicHost::load()
{
    QString lastError;
    for (const auto &candidate : libraryCandidates()) {
        library_.setFileName(candidate);
        if (!library_.load()) {
            lastError = library_.errorString();
            continue;
        }
        try {
            create_ = resolve<Create>(library_, "mosaic_app_create");
            dispatch_ = resolve<Dispatch>(library_, "mosaic_app_dispatch");
            snapshot_ = resolve<Snapshot>(library_, "mosaic_app_snapshot");
            restore_ = resolve<Restore>(library_, "mosaic_app_restore");
            bufferFree_ = resolve<BufferFree>(library_, "mosaic_buffer_free");
            destroy_ = resolve<Destroy>(library_, "mosaic_app_destroy");
            return true;
        } catch (const std::exception &exception) {
            lastError = QString::fromUtf8(exception.what());
            library_.unload();
        }
    }
    error_ = QStringLiteral("Unable to load the Mosaic application library: %1").arg(lastError);
    return false;
}

QVariant MosaicHost::consume(quint32 status, Buffer buffer)
{
    QByteArray encoded;
    try {
        encoded = QByteArray(reinterpret_cast<const char *>(buffer.ptr),
                             static_cast<qsizetype>(buffer.len));
    } catch (...) {
        if (bufferFree_) bufferFree_(buffer);
        throw;
    }
    if (bufferFree_) bufferFree_(buffer);
    if (status != 0) throw std::runtime_error(encoded.toStdString());

    QJsonParseError parseError;
    const auto document = QJsonDocument::fromJson(encoded, &parseError);
    if (parseError.error != QJsonParseError::NoError) {
        throw std::runtime_error(parseError.errorString().toStdString());
    }
    return document.toVariant();
}

QVariantMap MosaicHost::requireMap(const QVariant &value, const char *kind) const
{
    if (value.canConvert<QVariantMap>()) return value.toMap();
    throw std::runtime_error(QStringLiteral("Mosaic runtime returned a non-object %1")
                                 .arg(QString::fromLatin1(kind))
                                 .toStdString());
}

QVariantMap MosaicHost::requireAndMapUpdate(const QVariantMap &update, const char *kind) const
{
    if (update.contains(QStringLiteral("error"))) {
        throw std::runtime_error(update.value(QStringLiteral("error")).toString().toStdString());
    }
    const auto props = requireMap(update.value(QStringLiteral("props")), kind);
    for (const auto &name : requiredProps_) {
        if (!props.contains(name)) {
            throw std::runtime_error(
                QStringLiteral("native-complete runtime %1 is missing required MIL prop '%2'")
                    .arg(QString::fromLatin1(kind), name)
                    .toStdString());
        }
    }

    QVariantMap mappedProps;
    for (auto it = props.cbegin(); it != props.cend(); ++it) {
        const auto target = requiredSlotNames_.value(it.key(), it.key()).toString();
        mappedProps.insert(target, it.value());
    }
    auto mappedUpdate = update;
    mappedUpdate.insert(QStringLiteral("props"), mappedProps);
    return mappedUpdate;
}

QVariantMap MosaicHost::failure(const QString &message) const
{
    return {
        {QStringLiteral("props"), QVariantMap{}},
        {QStringLiteral("error"), message.isEmpty()
             ? QStringLiteral("Mosaic Rust runtime unavailable")
             : message},
    };
}

QVariant MosaicHost::loadPersistedSnapshot()
{
    const auto path = statePath();
    if (path.isEmpty() || !QFile::exists(path)) return QVariant();
    QFile file(path);
    if (!file.open(QIODevice::ReadOnly)) {
        persistenceWarning_ = QStringLiteral("Could not read Mosaic state at %1: %2")
            .arg(path, file.errorString());
        return QVariant();
    }
    QJsonParseError parseError;
    const auto document = QJsonDocument::fromJson(file.readAll(), &parseError);
    if (parseError.error == QJsonParseError::NoError && document.isObject()) {
        return document.object().toVariantMap();
    }
    file.close();
    quarantinePersistedState(
        QStringLiteral("Ignored invalid Mosaic state: %1").arg(parseError.errorString()));
    return QVariant();
}

void MosaicHost::quarantinePersistedState(const QString &reason)
{
    const auto path = statePath();
    if (path.isEmpty()) {
        persistenceWarning_ = reason;
        return;
    }
    const auto corrupt = path + QStringLiteral(".corrupt");
    QFile::remove(corrupt);
    if (QFile::exists(path)) QFile::rename(path, corrupt);
    persistenceWarning_ = QStringLiteral("%1 (%2)").arg(reason, path);
    qWarning().noquote() << persistenceWarning_;
}

void MosaicHost::persistSnapshot()
{
    const auto path = statePath();
    if (path.isEmpty()) return;
    Buffer output{};
    try {
        const auto status = snapshot_(app_, &output);
        const auto value = consume(status, output);
        if (!value.isValid() || value.isNull()) {
            QFile::remove(path);
            persistenceWarning_.clear();
            return;
        }
        const auto encoded = QJsonDocument::fromVariant(value).toJson(QJsonDocument::Compact);
        QDir().mkpath(QFileInfo(path).absolutePath());
        QSaveFile file(path);
        if (!file.open(QIODevice::WriteOnly) || file.write(encoded) != encoded.size()
            || !file.commit()) {
            throw std::runtime_error(file.errorString().toStdString());
        }
        persistenceWarning_.clear();
    } catch (const std::exception &exception) {
        persistenceWarning_ = QStringLiteral("Could not persist Mosaic state: %1")
            .arg(QString::fromUtf8(exception.what()));
        qWarning().noquote() << persistenceWarning_;
    }
}

QVariantMap MosaicHost::withPersistenceWarning(const QVariantMap &update) const
{
    if (persistenceWarning_.isEmpty()) return update;
    auto augmented = update;
    augmented.insert(QStringLiteral("persistenceWarning"), persistenceWarning_);
    auto props = augmented.value(QStringLiteral("props")).toMap();
    if (props.contains(QStringLiteral("storage-warning"))) {
        props.insert(QStringLiteral("storage-warning"), persistenceWarning_);
        augmented.insert(QStringLiteral("props"), props);
    }
    return augmented;
}

QString MosaicHost::statePath() const
{
    if (!PersistenceEnabled) return {};
    const auto requested = qEnvironmentVariable("MOSAIC_APP_STATE_PATH").trimmed();
    if (!requested.isEmpty()) return requested;
    const auto root = QStandardPaths::writableLocation(QStandardPaths::AppDataLocation);
    if (root.isEmpty()) return {};
    return QDir(root).filePath(
        QString::fromUtf8(ApplicationId) + QStringLiteral("/mosaic-state.v1.json"));
}
