// AUTO-GENERATED by Mosaic. Edits will be overwritten on next emit.
#pragma once

#include <QLibrary>
#include <QObject>
#include <QStringList>
#include <QVariant>
#include <QVariantMap>

class MosaicHost final : public QObject
{
    Q_OBJECT

public:
    explicit MosaicHost(QObject *parent = nullptr);
    ~MosaicHost() override;

    static void registerTypes();
    void attach(QObject *root);
    void requireRuntime() const;
    void configureRequiredProps(const QVariantMap &slotNames,
                                const QStringList &requiredProps);
    QVariantMap propsRequired() const;

    Q_INVOKABLE QVariantMap props() const;
    Q_INVOKABLE QVariantMap handleEvent(const QVariantMap &event);
    Q_INVOKABLE QVariantMap handleRequiredEvent(const QVariantMap &event);
    Q_INVOKABLE QVariant snapshot();
    Q_INVOKABLE QVariantMap restore(const QVariantMap &snapshot);

private:
    struct Bytes {
        const unsigned char *ptr;
        size_t len;
    };

    struct Buffer {
        unsigned char *ptr;
        size_t len;
        size_t capacity;
    };

    using Create = quint32 (*)(Bytes, void **, Buffer *);
    using Dispatch = quint32 (*)(void *, Bytes, Buffer *);
    using Snapshot = quint32 (*)(void *, Buffer *);
    using Restore = quint32 (*)(void *, Bytes, Buffer *);
    using BufferFree = void (*)(Buffer);
    using Destroy = void (*)(void *);

    bool load();
    QVariant consume(quint32 status, Buffer buffer);
    QVariantMap requireMap(const QVariant &value, const char *kind) const;
    QVariantMap requireAndMapUpdate(const QVariantMap &update, const char *kind) const;
    QVariantMap failure(const QString &message) const;

    static constexpr quint32 ProtocolVersion = __MOSAIC_PROTOCOL_VERSION__;
    QLibrary library_;
    void *app_ = nullptr;
    quint64 sequence_ = 0;
    QVariantMap latestUpdate_;
    QVariantMap requiredSlotNames_;
    QStringList requiredProps_;
    QString error_;
    Create create_ = nullptr;
    Dispatch dispatch_ = nullptr;
    Snapshot snapshot_ = nullptr;
    Restore restore_ = nullptr;
    BufferFree bufferFree_ = nullptr;
    Destroy destroy_ = nullptr;
};
