cd ../../../packages/typescript/code39 && npm install
cd ../../../packages/typescript/draw-instructions-svg && npm install
cd ../../../packages/typescript/lattice-transpiler && npm install
cd ../../../programs/typescript/code39-visualizer && npm install
npm run build
npx vitest run
