cd ../../../packages/typescript/directed-graph && npm install
cd ../../../packages/typescript/grammar-tools && npm install
cd ../../../packages/typescript/lexer && npm install
cd ../../../packages/typescript/state-machine && npm install
cd ../../../packages/typescript/lattice-lexer && npm install
cd ../../../packages/typescript/parser && npm install
cd ../../../packages/typescript/lattice-parser && npm install
cd ../../../packages/typescript/lattice-ast-to-css && npm install
cd ../../../packages/typescript/pixel-container && npm install
cd ../../../packages/typescript/paint-instructions && npm install
cd ../../../packages/typescript/paint-vm && npm install
cd ../../../packages/typescript/paint-vm-canvas && npm install
cd ../../../packages/typescript/paint-vm-svg && npm install
cd ../../../packages/typescript/barcode-layout-1d && npm install
cd ../../../packages/typescript/code39 && npm install
cd ../../../packages/typescript/lattice-transpiler && npm install
cd ../../../programs/typescript/code39-visualizer && npm install
npm run build
npx vitest run
