# AUTO-GENERATED FILE — DO NOT EDIT
# Source: starlark.tokens
# Regenerate with: perl code/programs/perl/grammar-tools/grammar-tools.pl compile-tokens starlark.tokens
#
# This file embeds a TokenGrammar as native Perl data structures.
# Call token_grammar() instead of reading and parsing the .tokens file.

package CodingAdventures::StarlarkLexer::_Grammar;
use strict;
use warnings;

sub token_grammar {
    return bless {
        definitions => [
            bless({
                name => 'STRING_RAW_TRIPLE_DQ',
                pattern => '[rR][bB]?"""([^"\\\\]|\\\\.|\\n)*"""|[bB][rR]"""([^"\\\\]|\\\\.|\\n)*"""',
                is_regex => 1,
                line_number => 84,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_TRIPLE_SQ',
                pattern => '[rR][bB]?\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'|[bB][rR]\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'',
                is_regex => 1,
                line_number => 85,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_TRIPLE_DQ',
                pattern => '[bB]?"""([^"\\\\]|\\\\.|\\n)*"""',
                is_regex => 1,
                line_number => 86,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_TRIPLE_SQ',
                pattern => '[bB]?\'\'\'([^\'\\\\]|\\\\.|\\n)*\'\'\'',
                is_regex => 1,
                line_number => 87,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_DQ',
                pattern => '[rR][bB]?"([^"\\\\]|\\\\.)*"|[bB][rR]"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 90,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_RAW_SQ',
                pattern => '[rR][bB]?\'([^\'\\\\]|\\\\.)*\'|[bB][rR]\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 91,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_DQ',
                pattern => '[bB]?"([^"\\\\]|\\\\.)*"',
                is_regex => 1,
                line_number => 92,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STRING_SQ',
                pattern => '[bB]?\'([^\'\\\\]|\\\\.)*\'',
                is_regex => 1,
                line_number => 93,
                alias => 'STRING',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOAT_EXP',
                pattern => '[0-9]+[eE][+-]?[0-9]+',
                is_regex => 1,
                line_number => 110,
                alias => 'FLOAT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOAT_DOT',
                pattern => '\\.[0-9]+([eE][+-]?[0-9]+)?',
                is_regex => 1,
                line_number => 111,
                alias => 'FLOAT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOAT',
                pattern => '[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?',
                is_regex => 1,
                line_number => 112,
                alias => 'FLOAT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'INT_HEX',
                pattern => '0[xX][0-9a-fA-F]+',
                is_regex => 1,
                line_number => 115,
                alias => 'INT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'INT_OCT',
                pattern => '0[oO][0-7]+',
                is_regex => 1,
                line_number => 116,
                alias => 'INT',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'INT',
                pattern => '[0-9]+',
                is_regex => 1,
                line_number => 117,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NAME',
                pattern => '[a-zA-Z_][a-zA-Z0-9_]*',
                is_regex => 1,
                line_number => 127,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'DOUBLE_STAR_EQUALS',
                pattern => '**=',
                is_regex => 0,
                line_number => 136,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEFT_SHIFT_EQUALS',
                pattern => '<<=',
                is_regex => 0,
                line_number => 137,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RIGHT_SHIFT_EQUALS',
                pattern => '>>=',
                is_regex => 0,
                line_number => 138,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOOR_DIV_EQUALS',
                pattern => '//=',
                is_regex => 0,
                line_number => 139,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'DOUBLE_STAR',
                pattern => '**',
                is_regex => 0,
                line_number => 148,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'FLOOR_DIV',
                pattern => '//',
                is_regex => 0,
                line_number => 149,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LEFT_SHIFT',
                pattern => '<<',
                is_regex => 0,
                line_number => 150,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RIGHT_SHIFT',
                pattern => '>>',
                is_regex => 0,
                line_number => 151,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'EQUALS_EQUALS',
                pattern => '==',
                is_regex => 0,
                line_number => 152,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'NOT_EQUALS',
                pattern => '!=',
                is_regex => 0,
                line_number => 153,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LESS_EQUALS',
                pattern => '<=',
                is_regex => 0,
                line_number => 154,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'GREATER_EQUALS',
                pattern => '>=',
                is_regex => 0,
                line_number => 155,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS_EQUALS',
                pattern => '+=',
                is_regex => 0,
                line_number => 156,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS_EQUALS',
                pattern => '-=',
                is_regex => 0,
                line_number => 157,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STAR_EQUALS',
                pattern => '*=',
                is_regex => 0,
                line_number => 158,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SLASH_EQUALS',
                pattern => '/=',
                is_regex => 0,
                line_number => 159,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PERCENT_EQUALS',
                pattern => '%=',
                is_regex => 0,
                line_number => 160,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AMP_EQUALS',
                pattern => '&=',
                is_regex => 0,
                line_number => 161,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PIPE_EQUALS',
                pattern => '|=',
                is_regex => 0,
                line_number => 162,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'CARET_EQUALS',
                pattern => '^=',
                is_regex => 0,
                line_number => 163,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PLUS',
                pattern => '+',
                is_regex => 0,
                line_number => 169,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'MINUS',
                pattern => '-',
                is_regex => 0,
                line_number => 170,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'STAR',
                pattern => '*',
                is_regex => 0,
                line_number => 171,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SLASH',
                pattern => '/',
                is_regex => 0,
                line_number => 172,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PERCENT',
                pattern => '%',
                is_regex => 0,
                line_number => 173,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'EQUALS',
                pattern => '=',
                is_regex => 0,
                line_number => 174,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LESS_THAN',
                pattern => '<',
                is_regex => 0,
                line_number => 175,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'GREATER_THAN',
                pattern => '>',
                is_regex => 0,
                line_number => 176,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'AMP',
                pattern => '&',
                is_regex => 0,
                line_number => 177,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'PIPE',
                pattern => '|',
                is_regex => 0,
                line_number => 178,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'CARET',
                pattern => '^',
                is_regex => 0,
                line_number => 179,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'TILDE',
                pattern => '~',
                is_regex => 0,
                line_number => 180,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LPAREN',
                pattern => '(',
                is_regex => 0,
                line_number => 186,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RPAREN',
                pattern => ')',
                is_regex => 0,
                line_number => 187,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LBRACKET',
                pattern => '[',
                is_regex => 0,
                line_number => 188,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RBRACKET',
                pattern => ']',
                is_regex => 0,
                line_number => 189,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'LBRACE',
                pattern => '{',
                is_regex => 0,
                line_number => 190,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'RBRACE',
                pattern => '}',
                is_regex => 0,
                line_number => 191,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COMMA',
                pattern => ',',
                is_regex => 0,
                line_number => 192,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'COLON',
                pattern => ':',
                is_regex => 0,
                line_number => 193,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'SEMICOLON',
                pattern => ';',
                is_regex => 0,
                line_number => 194,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'DOT',
                pattern => '.',
                is_regex => 0,
                line_number => 195,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        keywords => [
            'and',
            'break',
            'continue',
            'def',
            'elif',
            'else',
            'for',
            'if',
            'in',
            'lambda',
            'load',
            'not',
            'or',
            'pass',
            'return',
            'True',
            'False',
            'None',
        ],
        context_keywords => [],
        layout_keywords => [],
        soft_keywords => [],
        mode => 'indentation',
        escape_mode => '',
        skip_definitions => [
            bless({
                name => 'COMMENT',
                pattern => '#[^\\n]*',
                is_regex => 1,
                line_number => 65,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
            bless({
                name => 'WHITESPACE',
                pattern => '[ \\t]+',
                is_regex => 1,
                line_number => 66,
                alias => '',
            }, 'CodingAdventures::GrammarTools::TokenDefinition'),
        ],
        error_definitions => [],
        reserved_keywords => [
            'as',
            'assert',
            'async',
            'await',
            'class',
            'del',
            'except',
            'finally',
            'from',
            'global',
            'import',
            'is',
            'nonlocal',
            'raise',
            'try',
            'while',
            'with',
            'yield',
        ],
        groups => {},
        start_mode => '',
        transitions => [],
    }, 'CodingAdventures::GrammarTools::TokenGrammar';
}

1;
