// Generated by vscode-lang-extension-generator (LS04).
// Edit at your own risk; re-running the generator overwrites this file.

import * as vscode from "vscode";

/**
 * Factory that VS Code calls each time the user starts a debug session
 * with `"type": "twig"`.  We resolve the adapter binary from the
 * "twig.adapterPath" setting (defaulting to "twig-dap" on
 * PATH) and hand back a DebugAdapterExecutable — VS Code spawns the
 * subprocess and proxies DAP messages.
 */
class TwigDebugAdapterFactory
  implements vscode.DebugAdapterDescriptorFactory
{
  createDebugAdapterDescriptor(
    _session: vscode.DebugSession,
  ): vscode.ProviderResult<vscode.DebugAdapterDescriptor> {
    const config = vscode.workspace.getConfiguration("twig");
    const adapterPath = config.get<string>("adapterPath", "twig-dap");
    return new vscode.DebugAdapterExecutable(adapterPath, []);
  }
}

/** Wire the factory into VS Code's debug subsystem. */
export function registerDebugAdapter(context: vscode.ExtensionContext): void {
  context.subscriptions.push(
    vscode.debug.registerDebugAdapterDescriptorFactory(
      "twig",
      new TwigDebugAdapterFactory(),
    ),
  );
}

/** Reference the language name so it shows up in the bundle metadata. */
export const LANGUAGE_NAME = "Twig";
