/**
 * reducer.ts — Pure state transition function.
 *
 * The reducer is a pure function: (state, action) => newState.
 * It must not mutate the input state or perform I/O. All randomness
 * and timestamps are passed in through actions (generated by action
 * creators in actions.ts).
 *
 * === Immutability ===
 *
 * Every case returns a new object via spread. React detects changes by
 * reference equality — if we mutated in place, useStore() would not
 * trigger a re-render.
 */

import type { Action } from "@coding-adventures/store";
import type { Entry, AppState } from "./types.js";
import {
  ENTRY_CREATE,
  ENTRY_UPDATE,
  ENTRY_DELETE,
  ENTRIES_LOAD,
} from "./actions.js";

export type { AppState };

// ── Initial state ──────────────────────────────────────────────────────────

export const initialState: AppState = {
  entries: [],
};

// ── Reducer ────────────────────────────────────────────────────────────────

export function reducer(state: AppState, action: Action): AppState {
  switch (action.type) {
    // ── ENTRY_CREATE ──────────────────────────────────────────────────────
    //
    // Appends a new entry to the list. The id, createdAt, and updatedAt
    // are provided by the action creator (not generated here).
    case ENTRY_CREATE: {
      const entry: Entry = {
        id: action.id as string,
        title: action.title as string,
        content: action.content as string,
        createdAt: action.createdAt as string,
        updatedAt: action.updatedAt as number,
      };
      return { ...state, entries: [...state.entries, entry] };
    }

    // ── ENTRY_UPDATE ──────────────────────────────────────────────────────
    //
    // Replaces the title, content, and updatedAt of an existing entry.
    // If the id is not found, state is returned unchanged.
    case ENTRY_UPDATE: {
      const id = action.id as string;
      const title = action.title as string;
      const content = action.content as string;
      const updatedAt = action.updatedAt as number;
      const found = state.entries.some((e) => e.id === id);
      if (!found) return state;
      return {
        ...state,
        entries: state.entries.map((e) =>
          e.id === id ? { ...e, title, content, updatedAt } : e,
        ),
      };
    }

    // ── ENTRY_DELETE ──────────────────────────────────────────────────────
    //
    // Removes the entry with the matching id. If not found, state is
    // returned unchanged.
    case ENTRY_DELETE: {
      const id = action.id as string;
      return {
        ...state,
        entries: state.entries.filter((e) => e.id !== id),
      };
    }

    // ── ENTRIES_LOAD ──────────────────────────────────────────────────────
    //
    // Bulk-loads all persisted entries from storage on startup. Replaces
    // the entire entries array.
    case ENTRIES_LOAD: {
      return {
        ...state,
        entries: action.entries as Entry[],
      };
    }

    default:
      return state;
  }
}
