# frozen_string_literal: true
# AUTO-GENERATED FILE — DO NOT EDIT
# Source: python3.6.tokens
# Regenerate with: grammar-tools compile-tokens python3.6.tokens
#
# This file embeds a TokenGrammar as native Ruby data structures.
# Downstream packages require this file directly instead of reading
# and parsing the .tokens file at runtime.

require "coding_adventures_grammar_tools"

GT = CodingAdventures::GrammarTools unless defined?(GT)

TOKEN_GRAMMAR = GT::TokenGrammar.new(
  version: 1,
  case_insensitive: false,
  case_sensitive: true,
  definitions: [
      GT::TokenDefinition.new(
        name: "STRING_RAW_FSTR_TRIPLE_DQ",
        pattern: "[rR][fF]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"|[fF][rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
        is_regex: true,
        line_number: 198,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_RAW_FSTR_TRIPLE_SQ",
        pattern: "[rR][fF]'''([^'\\\\]|\\\\.|\\n)*'''|[fF][rR]'''([^'\\\\]|\\\\.|\\n)*'''",
        is_regex: true,
        line_number: 199,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_RAW_TRIPLE_DQ",
        pattern: "[rR][bB]?\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"|[bB][rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
        is_regex: true,
        line_number: 200,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_RAW_TRIPLE_SQ",
        pattern: "[rR][bB]?'''([^'\\\\]|\\\\.|\\n)*'''|[bB][rR]'''([^'\\\\]|\\\\.|\\n)*'''",
        is_regex: true,
        line_number: 201,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_FSTR_TRIPLE_DQ",
        pattern: "[fF]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
        is_regex: true,
        line_number: 203,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_FSTR_TRIPLE_SQ",
        pattern: "[fF]'''([^'\\\\]|\\\\.|\\n)*'''",
        is_regex: true,
        line_number: 204,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_TRIPLE_DQ",
        pattern: "[bB]?\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
        is_regex: true,
        line_number: 205,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_TRIPLE_SQ",
        pattern: "[bB]?'''([^'\\\\]|\\\\.|\\n)*'''",
        is_regex: true,
        line_number: 206,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_RAW_FSTR_DQ",
        pattern: "[rR][fF]\"([^\"\\\\]|\\\\.)*\"|[fF][rR]\"([^\"\\\\]|\\\\.)*\"",
        is_regex: true,
        line_number: 210,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_RAW_FSTR_SQ",
        pattern: "[rR][fF]'([^'\\\\]|\\\\.)*'|[fF][rR]'([^'\\\\]|\\\\.)*'",
        is_regex: true,
        line_number: 211,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_RAW_DQ",
        pattern: "[rR][bB]?\"([^\"\\\\]|\\\\.)*\"|[bB][rR]\"([^\"\\\\]|\\\\.)*\"",
        is_regex: true,
        line_number: 212,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_RAW_SQ",
        pattern: "[rR][bB]?'([^'\\\\]|\\\\.)*'|[bB][rR]'([^'\\\\]|\\\\.)*'",
        is_regex: true,
        line_number: 213,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_FSTR_DQ",
        pattern: "[fF]\"([^\"\\\\]|\\\\.)*\"",
        is_regex: true,
        line_number: 215,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_FSTR_SQ",
        pattern: "[fF]'([^'\\\\]|\\\\.)*'",
        is_regex: true,
        line_number: 216,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_DQ",
        pattern: "[bB]?\"([^\"\\\\]|\\\\.)*\"",
        is_regex: true,
        line_number: 217,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_SQ",
        pattern: "[bB]?'([^'\\\\]|\\\\.)*'",
        is_regex: true,
        line_number: 218,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "FLOAT_EXP",
        pattern: "[0-9](_?[0-9])*[eE][+-]?[0-9](_?[0-9])*",
        is_regex: true,
        line_number: 251,
        alias_name: "FLOAT",
      ),
      GT::TokenDefinition.new(
        name: "FLOAT_DOT",
        pattern: "\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?\\b",
        is_regex: true,
        line_number: 252,
        alias_name: "FLOAT",
      ),
      GT::TokenDefinition.new(
        name: "FLOAT",
        pattern: "[0-9](_?[0-9])*\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?",
        is_regex: true,
        line_number: 253,
        alias_name: "FLOAT",
      ),
      GT::TokenDefinition.new(
        name: "FLOAT_TRAIL",
        pattern: "[0-9](_?[0-9])*\\.([eE][+-]?[0-9](_?[0-9])*)?\\b",
        is_regex: true,
        line_number: 254,
        alias_name: "FLOAT",
      ),
      GT::TokenDefinition.new(
        name: "IMAG_FLOAT",
        pattern: "[0-9](_?[0-9])*\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?[jJ]",
        is_regex: true,
        line_number: 259,
        alias_name: "IMAGINARY",
      ),
      GT::TokenDefinition.new(
        name: "IMAG_DOT",
        pattern: "\\.[0-9](_?[0-9])*([eE][+-]?[0-9](_?[0-9])*)?[jJ]",
        is_regex: true,
        line_number: 260,
        alias_name: "IMAGINARY",
      ),
      GT::TokenDefinition.new(
        name: "IMAG_EXP",
        pattern: "[0-9](_?[0-9])*[eE][+-]?[0-9](_?[0-9])*[jJ]",
        is_regex: true,
        line_number: 261,
        alias_name: "IMAGINARY",
      ),
      GT::TokenDefinition.new(
        name: "IMAG_INT",
        pattern: "[0-9](_?[0-9])*[jJ]",
        is_regex: true,
        line_number: 262,
        alias_name: "IMAGINARY",
      ),
      GT::TokenDefinition.new(
        name: "INT_HEX",
        pattern: "0[xX](_?[0-9a-fA-F])+",
        is_regex: true,
        line_number: 272,
        alias_name: "INT",
      ),
      GT::TokenDefinition.new(
        name: "INT_OCT",
        pattern: "0[oO](_?[0-7])+",
        is_regex: true,
        line_number: 273,
        alias_name: "INT",
      ),
      GT::TokenDefinition.new(
        name: "INT_BIN",
        pattern: "0[bB](_?[01])+",
        is_regex: true,
        line_number: 274,
        alias_name: "INT",
      ),
      GT::TokenDefinition.new(
        name: "INT",
        pattern: "[0-9](_?[0-9])*",
        is_regex: true,
        line_number: 275,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NAME",
        pattern: "[a-zA-Z_][a-zA-Z0-9_]*",
        is_regex: true,
        line_number: 285,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AT",
        pattern: "@",
        is_regex: false,
        line_number: 297,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DOUBLE_STAR_EQUALS",
        pattern: "**=",
        is_regex: false,
        line_number: 306,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LEFT_SHIFT_EQUALS",
        pattern: "<<=",
        is_regex: false,
        line_number: 307,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RIGHT_SHIFT_EQUALS",
        pattern: ">>=",
        is_regex: false,
        line_number: 308,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "FLOOR_DIV_EQUALS",
        pattern: "//=",
        is_regex: false,
        line_number: 309,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AT_EQUALS",
        pattern: "@=",
        is_regex: false,
        line_number: 310,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DOUBLE_STAR",
        pattern: "**",
        is_regex: false,
        line_number: 318,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "FLOOR_DIV",
        pattern: "//",
        is_regex: false,
        line_number: 319,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LEFT_SHIFT",
        pattern: "<<",
        is_regex: false,
        line_number: 320,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RIGHT_SHIFT",
        pattern: ">>",
        is_regex: false,
        line_number: 321,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQUALS_EQUALS",
        pattern: "==",
        is_regex: false,
        line_number: 322,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NOT_EQUALS",
        pattern: "!=",
        is_regex: false,
        line_number: 323,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_EQUALS",
        pattern: "<=",
        is_regex: false,
        line_number: 324,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_EQUALS",
        pattern: ">=",
        is_regex: false,
        line_number: 325,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS_EQUALS",
        pattern: "+=",
        is_regex: false,
        line_number: 326,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS_EQUALS",
        pattern: "-=",
        is_regex: false,
        line_number: 327,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR_EQUALS",
        pattern: "*=",
        is_regex: false,
        line_number: 328,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SLASH_EQUALS",
        pattern: "/=",
        is_regex: false,
        line_number: 329,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PERCENT_EQUALS",
        pattern: "%=",
        is_regex: false,
        line_number: 330,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AMP_EQUALS",
        pattern: "&=",
        is_regex: false,
        line_number: 331,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PIPE_EQUALS",
        pattern: "|=",
        is_regex: false,
        line_number: 332,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CARET_EQUALS",
        pattern: "^=",
        is_regex: false,
        line_number: 333,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "ARROW",
        pattern: "->",
        is_regex: false,
        line_number: 334,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS",
        pattern: "+",
        is_regex: false,
        line_number: 340,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS",
        pattern: "-",
        is_regex: false,
        line_number: 341,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR",
        pattern: "*",
        is_regex: false,
        line_number: 342,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SLASH",
        pattern: "/",
        is_regex: false,
        line_number: 343,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PERCENT",
        pattern: "%",
        is_regex: false,
        line_number: 344,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQUALS",
        pattern: "=",
        is_regex: false,
        line_number: 345,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_THAN",
        pattern: "<",
        is_regex: false,
        line_number: 346,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_THAN",
        pattern: ">",
        is_regex: false,
        line_number: 347,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AMP",
        pattern: "&",
        is_regex: false,
        line_number: 348,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PIPE",
        pattern: "|",
        is_regex: false,
        line_number: 349,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CARET",
        pattern: "^",
        is_regex: false,
        line_number: 350,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "TILDE",
        pattern: "~",
        is_regex: false,
        line_number: 351,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LPAREN",
        pattern: "(",
        is_regex: false,
        line_number: 357,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RPAREN",
        pattern: ")",
        is_regex: false,
        line_number: 358,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACKET",
        pattern: "[",
        is_regex: false,
        line_number: 359,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACKET",
        pattern: "]",
        is_regex: false,
        line_number: 360,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACE",
        pattern: "{",
        is_regex: false,
        line_number: 361,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACE",
        pattern: "}",
        is_regex: false,
        line_number: 362,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COMMA",
        pattern: ",",
        is_regex: false,
        line_number: 363,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COLON",
        pattern: ":",
        is_regex: false,
        line_number: 364,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SEMICOLON",
        pattern: ";",
        is_regex: false,
        line_number: 365,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DOT",
        pattern: ".",
        is_regex: false,
        line_number: 366,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "ELLIPSIS",
        pattern: "...",
        is_regex: false,
        line_number: 367,
        alias_name: nil,
      ),
    ],
  keywords: ["False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue", "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import", "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while", "with", "yield"],
  mode: "indentation",
  escape_mode: nil,
  skip_definitions: [
      GT::TokenDefinition.new(
        name: "COMMENT",
        pattern: "#[^\\n]*",
        is_regex: true,
        line_number: 55,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "WHITESPACE",
        pattern: "[ \\t]+",
        is_regex: true,
        line_number: 56,
        alias_name: nil,
      ),
    ],
  reserved_keywords: [],
  error_definitions: [],
  groups: {},
  layout_keywords: [],
  context_keywords: [],
  soft_keywords: [],
)
