# frozen_string_literal: true
# AUTO-GENERATED FILE — DO NOT EDIT
# Source: python2.7.tokens
# Regenerate with: grammar-tools compile-tokens python2.7.tokens
#
# This file embeds a TokenGrammar as native Ruby data structures.
# Downstream packages require this file directly instead of reading
# and parsing the .tokens file at runtime.

require "coding_adventures_grammar_tools"

GT = CodingAdventures::GrammarTools unless defined?(GT)

TOKEN_GRAMMAR = GT::TokenGrammar.new(
  version: 1,
  case_insensitive: false,
  case_sensitive: true,
  definitions: [
      GT::TokenDefinition.new(
        name: "STRING_RAW_UNICODE_TRIPLE_DQ",
        pattern: "[uU][rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"|[rR][uU]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
        is_regex: true,
        line_number: 136,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_RAW_UNICODE_TRIPLE_SQ",
        pattern: "[uU][rR]'''([^'\\\\]|\\\\.|\\n)*'''|[rR][uU]'''([^'\\\\]|\\\\.|\\n)*'''",
        is_regex: true,
        line_number: 137,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_RAW_BYTES_TRIPLE_DQ",
        pattern: "[bB][rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"|[rR][bB]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
        is_regex: true,
        line_number: 140,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_RAW_BYTES_TRIPLE_SQ",
        pattern: "[bB][rR]'''([^'\\\\]|\\\\.|\\n)*'''|[rR][bB]'''([^'\\\\]|\\\\.|\\n)*'''",
        is_regex: true,
        line_number: 141,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_UNICODE_TRIPLE_DQ",
        pattern: "[uU]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
        is_regex: true,
        line_number: 145,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_UNICODE_TRIPLE_SQ",
        pattern: "[uU]'''([^'\\\\]|\\\\.|\\n)*'''",
        is_regex: true,
        line_number: 146,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_RAW_TRIPLE_DQ",
        pattern: "[rR]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
        is_regex: true,
        line_number: 147,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_RAW_TRIPLE_SQ",
        pattern: "[rR]'''([^'\\\\]|\\\\.|\\n)*'''",
        is_regex: true,
        line_number: 148,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_BYTES_TRIPLE_DQ",
        pattern: "[bB]\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
        is_regex: true,
        line_number: 149,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_BYTES_TRIPLE_SQ",
        pattern: "[bB]'''([^'\\\\]|\\\\.|\\n)*'''",
        is_regex: true,
        line_number: 150,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_TRIPLE_DQ",
        pattern: "\"\"\"([^\"\\\\]|\\\\.|\\n)*\"\"\"",
        is_regex: true,
        line_number: 153,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_TRIPLE_SQ",
        pattern: "'''([^'\\\\]|\\\\.|\\n)*'''",
        is_regex: true,
        line_number: 154,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_RAW_UNICODE_DQ",
        pattern: "[uU][rR]\"([^\"\\\\]|\\\\.)*\"|[rR][uU]\"([^\"\\\\]|\\\\.)*\"",
        is_regex: true,
        line_number: 157,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_RAW_UNICODE_SQ",
        pattern: "[uU][rR]'([^'\\\\]|\\\\.)*'|[rR][uU]'([^'\\\\]|\\\\.)*'",
        is_regex: true,
        line_number: 158,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_RAW_BYTES_DQ",
        pattern: "[bB][rR]\"([^\"\\\\]|\\\\.)*\"|[rR][bB]\"([^\"\\\\]|\\\\.)*\"",
        is_regex: true,
        line_number: 161,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_RAW_BYTES_SQ",
        pattern: "[bB][rR]'([^'\\\\]|\\\\.)*'|[rR][bB]'([^'\\\\]|\\\\.)*'",
        is_regex: true,
        line_number: 162,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_UNICODE_DQ",
        pattern: "[uU]\"([^\"\\\\]|\\\\.)*\"",
        is_regex: true,
        line_number: 165,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_UNICODE_SQ",
        pattern: "[uU]'([^'\\\\]|\\\\.)*'",
        is_regex: true,
        line_number: 166,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_RAW_DQ",
        pattern: "[rR]\"([^\"\\\\]|\\\\.)*\"",
        is_regex: true,
        line_number: 167,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_RAW_SQ",
        pattern: "[rR]'([^'\\\\]|\\\\.)*'",
        is_regex: true,
        line_number: 168,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_BYTES_DQ",
        pattern: "[bB]\"([^\"\\\\]|\\\\.)*\"",
        is_regex: true,
        line_number: 169,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_BYTES_SQ",
        pattern: "[bB]'([^'\\\\]|\\\\.)*'",
        is_regex: true,
        line_number: 170,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_DQ",
        pattern: "\"([^\"\\\\]|\\\\.)*\"",
        is_regex: true,
        line_number: 173,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "STRING_SQ",
        pattern: "'([^'\\\\]|\\\\.)*'",
        is_regex: true,
        line_number: 174,
        alias_name: "STRING",
      ),
      GT::TokenDefinition.new(
        name: "IMAG_FLOAT_EXP",
        pattern: "[0-9]+[eE][+-]?[0-9]+[jJ]",
        is_regex: true,
        line_number: 199,
        alias_name: "IMAG",
      ),
      GT::TokenDefinition.new(
        name: "IMAG_FLOAT_DOT",
        pattern: "\\.[0-9]+([eE][+-]?[0-9]+)?[jJ]",
        is_regex: true,
        line_number: 200,
        alias_name: "IMAG",
      ),
      GT::TokenDefinition.new(
        name: "IMAG_FLOAT",
        pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?[jJ]",
        is_regex: true,
        line_number: 201,
        alias_name: "IMAG",
      ),
      GT::TokenDefinition.new(
        name: "IMAG_INT",
        pattern: "[0-9]+[jJ]",
        is_regex: true,
        line_number: 202,
        alias_name: "IMAG",
      ),
      GT::TokenDefinition.new(
        name: "FLOAT_EXP",
        pattern: "[0-9]+[eE][+-]?[0-9]+",
        is_regex: true,
        line_number: 209,
        alias_name: "FLOAT",
      ),
      GT::TokenDefinition.new(
        name: "FLOAT_DOT",
        pattern: "\\.[0-9]+([eE][+-]?[0-9]+)?",
        is_regex: true,
        line_number: 210,
        alias_name: "FLOAT",
      ),
      GT::TokenDefinition.new(
        name: "FLOAT",
        pattern: "[0-9]+\\.[0-9]*([eE][+-]?[0-9]+)?",
        is_regex: true,
        line_number: 211,
        alias_name: "FLOAT",
      ),
      GT::TokenDefinition.new(
        name: "INT_HEX_LONG",
        pattern: "0[xX][0-9a-fA-F]+[lL]",
        is_regex: true,
        line_number: 217,
        alias_name: "INT",
      ),
      GT::TokenDefinition.new(
        name: "INT_OCT_LONG",
        pattern: "0[oO][0-7]+[lL]",
        is_regex: true,
        line_number: 218,
        alias_name: "INT",
      ),
      GT::TokenDefinition.new(
        name: "INT_LEGACY_OCT_LONG",
        pattern: "0[0-7]+[lL]",
        is_regex: true,
        line_number: 219,
        alias_name: "INT",
      ),
      GT::TokenDefinition.new(
        name: "INT_DEC_LONG",
        pattern: "[0-9]+[lL]",
        is_regex: true,
        line_number: 220,
        alias_name: "INT",
      ),
      GT::TokenDefinition.new(
        name: "INT_HEX",
        pattern: "0[xX][0-9a-fA-F]+",
        is_regex: true,
        line_number: 224,
        alias_name: "INT",
      ),
      GT::TokenDefinition.new(
        name: "INT_BIN",
        pattern: "0[bB][01]+",
        is_regex: true,
        line_number: 226,
        alias_name: "INT",
      ),
      GT::TokenDefinition.new(
        name: "INT_OCT",
        pattern: "0[oO][0-7]+",
        is_regex: true,
        line_number: 228,
        alias_name: "INT",
      ),
      GT::TokenDefinition.new(
        name: "INT_LEGACY_OCT",
        pattern: "0[0-7]+",
        is_regex: true,
        line_number: 232,
        alias_name: "INT",
      ),
      GT::TokenDefinition.new(
        name: "INT",
        pattern: "[0-9]+",
        is_regex: true,
        line_number: 234,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NAME",
        pattern: "[a-zA-Z_][a-zA-Z0-9_]*",
        is_regex: true,
        line_number: 247,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DOUBLE_STAR_EQUALS",
        pattern: "**=",
        is_regex: false,
        line_number: 256,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LEFT_SHIFT_EQUALS",
        pattern: "<<=",
        is_regex: false,
        line_number: 257,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RIGHT_SHIFT_EQUALS",
        pattern: ">>=",
        is_regex: false,
        line_number: 258,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "FLOOR_DIV_EQUALS",
        pattern: "//=",
        is_regex: false,
        line_number: 259,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DOUBLE_STAR",
        pattern: "**",
        is_regex: false,
        line_number: 273,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "FLOOR_DIV",
        pattern: "//",
        is_regex: false,
        line_number: 274,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LEFT_SHIFT",
        pattern: "<<",
        is_regex: false,
        line_number: 275,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RIGHT_SHIFT",
        pattern: ">>",
        is_regex: false,
        line_number: 276,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQUALS_EQUALS",
        pattern: "==",
        is_regex: false,
        line_number: 277,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "NOT_EQUALS",
        pattern: "!=",
        is_regex: false,
        line_number: 278,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LEGACY_NOT_EQUALS",
        pattern: "<>",
        is_regex: false,
        line_number: 279,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_EQUALS",
        pattern: "<=",
        is_regex: false,
        line_number: 280,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_EQUALS",
        pattern: ">=",
        is_regex: false,
        line_number: 281,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS_EQUALS",
        pattern: "+=",
        is_regex: false,
        line_number: 282,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS_EQUALS",
        pattern: "-=",
        is_regex: false,
        line_number: 283,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR_EQUALS",
        pattern: "*=",
        is_regex: false,
        line_number: 284,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SLASH_EQUALS",
        pattern: "/=",
        is_regex: false,
        line_number: 285,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PERCENT_EQUALS",
        pattern: "%=",
        is_regex: false,
        line_number: 286,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AMP_EQUALS",
        pattern: "&=",
        is_regex: false,
        line_number: 287,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PIPE_EQUALS",
        pattern: "|=",
        is_regex: false,
        line_number: 288,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CARET_EQUALS",
        pattern: "^=",
        is_regex: false,
        line_number: 289,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PLUS",
        pattern: "+",
        is_regex: false,
        line_number: 304,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "MINUS",
        pattern: "-",
        is_regex: false,
        line_number: 305,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "STAR",
        pattern: "*",
        is_regex: false,
        line_number: 306,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SLASH",
        pattern: "/",
        is_regex: false,
        line_number: 307,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PERCENT",
        pattern: "%",
        is_regex: false,
        line_number: 308,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "EQUALS",
        pattern: "=",
        is_regex: false,
        line_number: 309,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LESS_THAN",
        pattern: "<",
        is_regex: false,
        line_number: 310,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "GREATER_THAN",
        pattern: ">",
        is_regex: false,
        line_number: 311,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AMP",
        pattern: "&",
        is_regex: false,
        line_number: 312,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "PIPE",
        pattern: "|",
        is_regex: false,
        line_number: 313,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "CARET",
        pattern: "^",
        is_regex: false,
        line_number: 314,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "TILDE",
        pattern: "~",
        is_regex: false,
        line_number: 315,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "AT",
        pattern: "@",
        is_regex: false,
        line_number: 316,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "BACKTICK",
        pattern: "`",
        is_regex: false,
        line_number: 317,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LPAREN",
        pattern: "(",
        is_regex: false,
        line_number: 327,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RPAREN",
        pattern: ")",
        is_regex: false,
        line_number: 328,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACKET",
        pattern: "[",
        is_regex: false,
        line_number: 329,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACKET",
        pattern: "]",
        is_regex: false,
        line_number: 330,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LBRACE",
        pattern: "{",
        is_regex: false,
        line_number: 331,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "RBRACE",
        pattern: "}",
        is_regex: false,
        line_number: 332,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COMMA",
        pattern: ",",
        is_regex: false,
        line_number: 333,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "COLON",
        pattern: ":",
        is_regex: false,
        line_number: 334,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "SEMICOLON",
        pattern: ";",
        is_regex: false,
        line_number: 335,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "DOT",
        pattern: ".",
        is_regex: false,
        line_number: 336,
        alias_name: nil,
      ),
    ],
  keywords: ["and", "as", "assert", "break", "class", "continue", "def", "del", "elif", "else", "except", "exec", "finally", "for", "from", "global", "if", "import", "in", "is", "lambda", "not", "or", "pass", "print", "raise", "return", "try", "while", "with", "yield"],
  mode: "indentation",
  escape_mode: nil,
  skip_definitions: [
      GT::TokenDefinition.new(
        name: "COMMENT",
        pattern: "#[^\\n]*",
        is_regex: true,
        line_number: 83,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "WHITESPACE",
        pattern: "[ \\t]+",
        is_regex: true,
        line_number: 84,
        alias_name: nil,
      ),
      GT::TokenDefinition.new(
        name: "LINE_CONTINUATION",
        pattern: "\\\\[ \\t]*\\n",
        is_regex: true,
        line_number: 98,
        alias_name: nil,
      ),
    ],
  reserved_keywords: [],
  error_definitions: [],
  groups: {},
  layout_keywords: [],
  context_keywords: [],
  soft_keywords: [],
)
