// AUTO-GENERATED FILE — DO NOT EDIT
// Source: c.tokens
// Regenerate with: grammar-tools compile-tokens c.tokens
//
// This file embeds a TokenGrammar as native Rust data structures.
// Call `token_grammar()` instead of reading and parsing the .tokens file.

#[allow(unused_imports)]
use grammar_tools::token_grammar::{
    ModeTransition, PatternGroup, TokenDefinition, TokenGrammar, TransitionAction,
};
#[allow(unused_imports)]
use std::collections::HashMap;

pub fn token_grammar() -> TokenGrammar {
    TokenGrammar {
        definitions: vec![
            TokenDefinition {
                name: r#"EQ_EQ"#.to_string(),
                pattern: r#"=="#.to_string(),
                is_regex: false,
                line_number: 25,
                alias: None,
            },
            TokenDefinition {
                name: r#"NE"#.to_string(),
                pattern: r#"!="#.to_string(),
                is_regex: false,
                line_number: 26,
                alias: None,
            },
            TokenDefinition {
                name: r#"LE"#.to_string(),
                pattern: r#"<="#.to_string(),
                is_regex: false,
                line_number: 27,
                alias: None,
            },
            TokenDefinition {
                name: r#"GE"#.to_string(),
                pattern: r#">="#.to_string(),
                is_regex: false,
                line_number: 28,
                alias: None,
            },
            TokenDefinition {
                name: r#"SHL"#.to_string(),
                pattern: r#"<<"#.to_string(),
                is_regex: false,
                line_number: 29,
                alias: None,
            },
            TokenDefinition {
                name: r#"SHR"#.to_string(),
                pattern: r#">>"#.to_string(),
                is_regex: false,
                line_number: 30,
                alias: None,
            },
            TokenDefinition {
                name: r#"AND_AND"#.to_string(),
                pattern: r#"&&"#.to_string(),
                is_regex: false,
                line_number: 31,
                alias: None,
            },
            TokenDefinition {
                name: r#"OR_OR"#.to_string(),
                pattern: r#"||"#.to_string(),
                is_regex: false,
                line_number: 32,
                alias: None,
            },
            TokenDefinition {
                name: r#"FLOAT_LIT"#.to_string(),
                pattern:
                    r#"(([0-9]+\.[0-9]*|\.[0-9]+)([eE][+-]?[0-9]+)?|[0-9]+[eE][+-]?[0-9]+)[fFlL]?"#
                        .to_string(),
                is_regex: true,
                line_number: 42,
                alias: None,
            },
            TokenDefinition {
                name: r#"INT_LIT"#.to_string(),
                pattern: r#"(0[xX][0-9a-fA-F]+|[0-9]+)([uUlL]*)"#.to_string(),
                is_regex: true,
                line_number: 47,
                alias: None,
            },
            TokenDefinition {
                name: r#"CHAR_LIT"#.to_string(),
                pattern: r#"'([^'\\]|\\.)'"#.to_string(),
                is_regex: true,
                line_number: 51,
                alias: None,
            },
            TokenDefinition {
                name: r#"STR_LIT"#.to_string(),
                pattern: r#""([^"\\]|\\.)*""#.to_string(),
                is_regex: true,
                line_number: 54,
                alias: None,
            },
            TokenDefinition {
                name: r#"NAME"#.to_string(),
                pattern: r#"[A-Za-z_][A-Za-z0-9_]*"#.to_string(),
                is_regex: true,
                line_number: 89,
                alias: None,
            },
            TokenDefinition {
                name: r#"PLUS"#.to_string(),
                pattern: r#"+"#.to_string(),
                is_regex: false,
                line_number: 94,
                alias: None,
            },
            TokenDefinition {
                name: r#"MINUS"#.to_string(),
                pattern: r#"-"#.to_string(),
                is_regex: false,
                line_number: 95,
                alias: None,
            },
            TokenDefinition {
                name: r#"STAR"#.to_string(),
                pattern: r#"*"#.to_string(),
                is_regex: false,
                line_number: 96,
                alias: None,
            },
            TokenDefinition {
                name: r#"SLASH"#.to_string(),
                pattern: r#"/"#.to_string(),
                is_regex: false,
                line_number: 97,
                alias: None,
            },
            TokenDefinition {
                name: r#"PERCENT"#.to_string(),
                pattern: r#"%"#.to_string(),
                is_regex: false,
                line_number: 98,
                alias: None,
            },
            TokenDefinition {
                name: r#"AMP"#.to_string(),
                pattern: r#"&"#.to_string(),
                is_regex: false,
                line_number: 99,
                alias: None,
            },
            TokenDefinition {
                name: r#"PIPE"#.to_string(),
                pattern: r#"|"#.to_string(),
                is_regex: false,
                line_number: 100,
                alias: None,
            },
            TokenDefinition {
                name: r#"CARET"#.to_string(),
                pattern: r#"^"#.to_string(),
                is_regex: false,
                line_number: 101,
                alias: None,
            },
            TokenDefinition {
                name: r#"TILDE"#.to_string(),
                pattern: r#"~"#.to_string(),
                is_regex: false,
                line_number: 102,
                alias: None,
            },
            TokenDefinition {
                name: r#"BANG"#.to_string(),
                pattern: r#"!"#.to_string(),
                is_regex: false,
                line_number: 103,
                alias: None,
            },
            TokenDefinition {
                name: r#"LT"#.to_string(),
                pattern: r#"<"#.to_string(),
                is_regex: false,
                line_number: 104,
                alias: None,
            },
            TokenDefinition {
                name: r#"GT"#.to_string(),
                pattern: r#">"#.to_string(),
                is_regex: false,
                line_number: 105,
                alias: None,
            },
            TokenDefinition {
                name: r#"EQ"#.to_string(),
                pattern: r#"="#.to_string(),
                is_regex: false,
                line_number: 106,
                alias: None,
            },
            TokenDefinition {
                name: r#"LPAREN"#.to_string(),
                pattern: r#"("#.to_string(),
                is_regex: false,
                line_number: 107,
                alias: None,
            },
            TokenDefinition {
                name: r#"RPAREN"#.to_string(),
                pattern: r#")"#.to_string(),
                is_regex: false,
                line_number: 108,
                alias: None,
            },
            TokenDefinition {
                name: r#"LBRACE"#.to_string(),
                pattern: r#"{"#.to_string(),
                is_regex: false,
                line_number: 109,
                alias: None,
            },
            TokenDefinition {
                name: r#"RBRACE"#.to_string(),
                pattern: r#"}"#.to_string(),
                is_regex: false,
                line_number: 110,
                alias: None,
            },
            TokenDefinition {
                name: r#"LBRACKET"#.to_string(),
                pattern: r#"["#.to_string(),
                is_regex: false,
                line_number: 111,
                alias: None,
            },
            TokenDefinition {
                name: r#"RBRACKET"#.to_string(),
                pattern: r#"]"#.to_string(),
                is_regex: false,
                line_number: 112,
                alias: None,
            },
            TokenDefinition {
                name: r#"SEMICOLON"#.to_string(),
                pattern: r#";"#.to_string(),
                is_regex: false,
                line_number: 113,
                alias: None,
            },
            TokenDefinition {
                name: r#"COMMA"#.to_string(),
                pattern: r#","#.to_string(),
                is_regex: false,
                line_number: 114,
                alias: None,
            },
        ],
        keywords: vec![
            r#"void"#.to_string(),
            r#"char"#.to_string(),
            r#"short"#.to_string(),
            r#"int"#.to_string(),
            r#"long"#.to_string(),
            r#"signed"#.to_string(),
            r#"unsigned"#.to_string(),
            r#"float"#.to_string(),
            r#"double"#.to_string(),
            r#"int8_t"#.to_string(),
            r#"int16_t"#.to_string(),
            r#"int32_t"#.to_string(),
            r#"int64_t"#.to_string(),
            r#"uint8_t"#.to_string(),
            r#"uint16_t"#.to_string(),
            r#"uint32_t"#.to_string(),
            r#"uint64_t"#.to_string(),
            r#"size_t"#.to_string(),
            r#"if"#.to_string(),
            r#"else"#.to_string(),
            r#"while"#.to_string(),
            r#"for"#.to_string(),
            r#"return"#.to_string(),
        ],
        mode: None,
        skip_definitions: vec![
            TokenDefinition {
                name: r#"WHITESPACE"#.to_string(),
                pattern: r#"[ \t\r\n]+"#.to_string(),
                is_regex: true,
                line_number: 120,
                alias: None,
            },
            TokenDefinition {
                name: r#"LINE_COMMENT"#.to_string(),
                pattern: r#"\/\/[^\n]*"#.to_string(),
                is_regex: true,
                line_number: 121,
                alias: None,
            },
            TokenDefinition {
                name: r#"BLOCK_COMMENT"#.to_string(),
                pattern: r#"\/\*([^*]|\*+[^*\/])*\*+\/"#.to_string(),
                is_regex: true,
                line_number: 122,
                alias: None,
            },
            TokenDefinition {
                name: r#"PREPROC"#.to_string(),
                pattern: r#"#[^\n]*"#.to_string(),
                is_regex: true,
                line_number: 123,
                alias: None,
            },
        ],
        reserved_keywords: vec![],
        escapes: None,
        error_definitions: vec![TokenDefinition {
            name: r#"UNKNOWN"#.to_string(),
            pattern: r#"."#.to_string(),
            is_regex: true,
            line_number: 126,
            alias: None,
        }],
        groups: HashMap::new(),
        case_sensitive: true,
        version: 1,
        case_insensitive: false,
        context_keywords: vec![],
        soft_keywords: vec![],
        layout_keywords: vec![],
        start_mode: None,
        transitions: vec![],
    }
}
