// GENERATED by code/scripts/generate_scytale_fixture_consumers.py.
// Source SHA-256: efd6c3a85a0c1d0676c31bf709d7c3d7eb5f4aef6b31ac2f904ebad6d76ad02c
// Do not edit by hand.

import { describe, expect, it } from "vitest";
import { bruteForce, decrypt, encrypt } from "../src/index.js";

describe("generated classical-cipher Scytale fixtures", () => {
  it("matches every normative case", () => {
    // classical-ciphers-v1-scytale-worked-encrypt
    expect(encrypt(String.fromCodePoint(72, 69, 76, 76, 79, 32, 87, 79, 82, 76, 68), 3)).toBe(String.fromCodePoint(72, 76, 87, 76, 69, 79, 79, 68, 76, 32, 82, 32));
    // classical-ciphers-v1-scytale-worked-decrypt
    expect(decrypt(String.fromCodePoint(72, 76, 87, 76, 69, 79, 79, 68, 76, 32, 82, 32), 3)).toBe(String.fromCodePoint(72, 69, 76, 76, 79, 32, 87, 79, 82, 76, 68));
    // classical-ciphers-v1-scytale-ragged-decrypt
    expect(decrypt(String.fromCodePoint(65, 66, 67, 68, 69, 70), 4)).toBe(String.fromCodePoint(65, 67, 69, 70, 66, 68));
    // classical-ciphers-v1-scytale-unicode-encrypt
    expect(encrypt(String.fromCodePoint(65, 128512, 66, 233), 3)).toBe(String.fromCodePoint(65, 233, 128512, 32, 66, 32));
    // classical-ciphers-v1-scytale-unicode-decrypt
    expect(decrypt(String.fromCodePoint(65, 233, 128512, 32, 66, 32), 3)).toBe(String.fromCodePoint(65, 128512, 66, 233));
    // classical-ciphers-v1-scytale-combining-scalar-encrypt
    expect(encrypt(String.fromCodePoint(65, 101, 769, 66), 3)).toBe(String.fromCodePoint(65, 66, 101, 32, 769, 32));
    // classical-ciphers-v1-scytale-combining-scalar-decrypt
    expect(decrypt(String.fromCodePoint(65, 66, 101, 32, 769, 32), 3)).toBe(String.fromCodePoint(65, 101, 769, 66));
    // classical-ciphers-v1-scytale-genuine-trailing-space-encrypt
    expect(encrypt(String.fromCodePoint(69, 78, 68, 32), 3)).toBe(String.fromCodePoint(69, 32, 78, 32, 68, 32));
    // classical-ciphers-v1-scytale-genuine-trailing-space-loss
    expect(decrypt(String.fromCodePoint(69, 32, 78, 32, 68, 32), 3)).toBe(String.fromCodePoint(69, 78, 68));
    // classical-ciphers-v1-scytale-trailing-tab-retained
    expect(decrypt(String.fromCodePoint(65, 9, 66, 32), 2)).toBe(String.fromCodePoint(65, 66, 9));
    // classical-ciphers-v1-scytale-newline-nbsp-retained
    expect(decrypt(String.fromCodePoint(65, 160, 9, 32, 10, 32), 3)).toBe(String.fromCodePoint(65, 9, 10, 160));
    // classical-ciphers-v1-scytale-empty-before-low-key
    expect(encrypt(String.fromCodePoint(), -1)).toBe(String.fromCodePoint());
    // classical-ciphers-v1-scytale-empty-before-high-key
    expect(decrypt(String.fromCodePoint(), 8194)).toBe(String.fromCodePoint());
    // classical-ciphers-v1-scytale-invalid-low-key
    let invalidID0 = String.fromCodePoint(117, 110, 101, 120, 112, 101, 99, 116, 101, 100, 45, 101, 114, 114, 111, 114);
    try { encrypt(String.fromCodePoint(65), 1); } catch (error) {
      if (error instanceof Error && error.message.startsWith(String.fromCodePoint(75, 101, 121, 32, 109, 117, 115, 116, 32, 98, 101))) invalidID0 = String.fromCodePoint(115, 99, 121, 116, 97, 108, 101, 45, 105, 110, 118, 97, 108, 105, 100, 45, 107, 101, 121);
    }
    expect(invalidID0).toBe(String.fromCodePoint(115, 99, 121, 116, 97, 108, 101, 45, 105, 110, 118, 97, 108, 105, 100, 45, 107, 101, 121));
    // classical-ciphers-v1-scytale-invalid-high-key
    let invalidID1 = String.fromCodePoint(117, 110, 101, 120, 112, 101, 99, 116, 101, 100, 45, 101, 114, 114, 111, 114);
    try { decrypt(String.fromCodePoint(65, 66, 67), 4); } catch (error) {
      if (error instanceof Error && error.message.startsWith(String.fromCodePoint(75, 101, 121, 32, 109, 117, 115, 116, 32, 98, 101))) invalidID1 = String.fromCodePoint(115, 99, 121, 116, 97, 108, 101, 45, 105, 110, 118, 97, 108, 105, 100, 45, 107, 101, 121);
    }
    expect(invalidID1).toBe(String.fromCodePoint(115, 99, 121, 116, 97, 108, 101, 45, 105, 110, 118, 97, 108, 105, 100, 45, 107, 101, 121));
    // classical-ciphers-v1-scytale-brute-force-ascending
    expect(bruteForce(String.fromCodePoint(72, 76, 87, 76, 69, 79, 79, 68, 76, 32, 82, 32))).toEqual([{ key: 2, text: String.fromCodePoint(72, 79, 76, 68, 87, 76, 76, 32, 69, 82, 79) }, { key: 3, text: String.fromCodePoint(72, 69, 76, 76, 79, 32, 87, 79, 82, 76, 68) }, { key: 4, text: String.fromCodePoint(72, 76, 79, 32, 76, 69, 68, 82, 87, 79, 76) }, { key: 5, text: String.fromCodePoint(72, 76, 79, 76, 82, 76, 69, 68, 32, 32, 87, 79) }, { key: 6, text: String.fromCodePoint(72, 87, 69, 79, 76, 82, 76, 76, 79, 68) }]);
    // classical-ciphers-v1-scytale-brute-force-short
    expect(bruteForce(String.fromCodePoint(65, 66, 67))).toEqual([]);
    // classical-ciphers-v1-scytale-brute-force-preflight-limit
    expect(() => bruteForce(String.fromCodePoint(65).repeat(4097))).toThrow(String.fromCodePoint(115, 99, 121, 116, 97, 108, 101, 45, 98, 114, 117, 116, 101, 45, 102, 111, 114, 99, 101, 45, 108, 105, 109, 105, 116));
  });
});
