package com.codingadventures.wasmopcodes

data class OpcodeInfo(
    val opcode: Int,
    val name: String,
    val category: String,
    val immediates: List<String>,
    val stackPop: Int,
    val stackPush: Int,
)

private val RAW_OPCODES: List<OpcodeInfo> = listOf(
    OpcodeInfo(opcode = 0x00, name = "unreachable", category = "control", immediates = emptyList(), stackPop = 0, stackPush = 0),
    OpcodeInfo(opcode = 0x01, name = "nop", category = "control", immediates = emptyList(), stackPop = 0, stackPush = 0),
    OpcodeInfo(opcode = 0x02, name = "block", category = "control", immediates = listOf("blocktype"), stackPop = 0, stackPush = 0),
    OpcodeInfo(opcode = 0x03, name = "loop", category = "control", immediates = listOf("blocktype"), stackPop = 0, stackPush = 0),
    OpcodeInfo(opcode = 0x04, name = "if", category = "control", immediates = listOf("blocktype"), stackPop = 1, stackPush = 0),
    OpcodeInfo(opcode = 0x05, name = "else", category = "control", immediates = emptyList(), stackPop = 0, stackPush = 0),
    OpcodeInfo(opcode = 0x0B, name = "end", category = "control", immediates = emptyList(), stackPop = 0, stackPush = 0),
    OpcodeInfo(opcode = 0x0C, name = "br", category = "control", immediates = listOf("labelidx"), stackPop = 0, stackPush = 0),
    OpcodeInfo(opcode = 0x0D, name = "br_if", category = "control", immediates = listOf("labelidx"), stackPop = 1, stackPush = 0),
    OpcodeInfo(opcode = 0x0E, name = "br_table", category = "control", immediates = listOf("vec_labelidx"), stackPop = 1, stackPush = 0),
    OpcodeInfo(opcode = 0x0F, name = "return", category = "control", immediates = emptyList(), stackPop = 0, stackPush = 0),
    OpcodeInfo(opcode = 0x10, name = "call", category = "control", immediates = listOf("funcidx"), stackPop = 0, stackPush = 0),
    OpcodeInfo(opcode = 0x11, name = "call_indirect", category = "control", immediates = listOf("typeidx", "tableidx"), stackPop = 1, stackPush = 0),
    OpcodeInfo(opcode = 0x1A, name = "drop", category = "parametric", immediates = emptyList(), stackPop = 1, stackPush = 0),
    OpcodeInfo(opcode = 0x1B, name = "select", category = "parametric", immediates = emptyList(), stackPop = 3, stackPush = 1),
    OpcodeInfo(opcode = 0x20, name = "local.get", category = "variable", immediates = listOf("localidx"), stackPop = 0, stackPush = 1),
    OpcodeInfo(opcode = 0x21, name = "local.set", category = "variable", immediates = listOf("localidx"), stackPop = 1, stackPush = 0),
    OpcodeInfo(opcode = 0x22, name = "local.tee", category = "variable", immediates = listOf("localidx"), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x23, name = "global.get", category = "variable", immediates = listOf("globalidx"), stackPop = 0, stackPush = 1),
    OpcodeInfo(opcode = 0x24, name = "global.set", category = "variable", immediates = listOf("globalidx"), stackPop = 1, stackPush = 0),
    OpcodeInfo(opcode = 0x28, name = "i32.load", category = "memory", immediates = listOf("memarg"), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x29, name = "i64.load", category = "memory", immediates = listOf("memarg"), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x2A, name = "f32.load", category = "memory", immediates = listOf("memarg"), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x2B, name = "f64.load", category = "memory", immediates = listOf("memarg"), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x2C, name = "i32.load8_s", category = "memory", immediates = listOf("memarg"), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x2D, name = "i32.load8_u", category = "memory", immediates = listOf("memarg"), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x2E, name = "i32.load16_s", category = "memory", immediates = listOf("memarg"), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x2F, name = "i32.load16_u", category = "memory", immediates = listOf("memarg"), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x30, name = "i64.load8_s", category = "memory", immediates = listOf("memarg"), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x31, name = "i64.load8_u", category = "memory", immediates = listOf("memarg"), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x32, name = "i64.load16_s", category = "memory", immediates = listOf("memarg"), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x33, name = "i64.load16_u", category = "memory", immediates = listOf("memarg"), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x34, name = "i64.load32_s", category = "memory", immediates = listOf("memarg"), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x35, name = "i64.load32_u", category = "memory", immediates = listOf("memarg"), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x36, name = "i32.store", category = "memory", immediates = listOf("memarg"), stackPop = 2, stackPush = 0),
    OpcodeInfo(opcode = 0x37, name = "i64.store", category = "memory", immediates = listOf("memarg"), stackPop = 2, stackPush = 0),
    OpcodeInfo(opcode = 0x38, name = "f32.store", category = "memory", immediates = listOf("memarg"), stackPop = 2, stackPush = 0),
    OpcodeInfo(opcode = 0x39, name = "f64.store", category = "memory", immediates = listOf("memarg"), stackPop = 2, stackPush = 0),
    OpcodeInfo(opcode = 0x3A, name = "i32.store8", category = "memory", immediates = listOf("memarg"), stackPop = 2, stackPush = 0),
    OpcodeInfo(opcode = 0x3B, name = "i32.store16", category = "memory", immediates = listOf("memarg"), stackPop = 2, stackPush = 0),
    OpcodeInfo(opcode = 0x3C, name = "i64.store8", category = "memory", immediates = listOf("memarg"), stackPop = 2, stackPush = 0),
    OpcodeInfo(opcode = 0x3D, name = "i64.store16", category = "memory", immediates = listOf("memarg"), stackPop = 2, stackPush = 0),
    OpcodeInfo(opcode = 0x3E, name = "i64.store32", category = "memory", immediates = listOf("memarg"), stackPop = 2, stackPush = 0),
    OpcodeInfo(opcode = 0x3F, name = "memory.size", category = "memory", immediates = listOf("memidx"), stackPop = 0, stackPush = 1),
    OpcodeInfo(opcode = 0x40, name = "memory.grow", category = "memory", immediates = listOf("memidx"), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x41, name = "i32.const", category = "numeric_i32", immediates = listOf("i32"), stackPop = 0, stackPush = 1),
    OpcodeInfo(opcode = 0x45, name = "i32.eqz", category = "numeric_i32", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x46, name = "i32.eq", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x47, name = "i32.ne", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x48, name = "i32.lt_s", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x49, name = "i32.lt_u", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x4A, name = "i32.gt_s", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x4B, name = "i32.gt_u", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x4C, name = "i32.le_s", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x4D, name = "i32.le_u", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x4E, name = "i32.ge_s", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x4F, name = "i32.ge_u", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x67, name = "i32.clz", category = "numeric_i32", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x68, name = "i32.ctz", category = "numeric_i32", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x69, name = "i32.popcnt", category = "numeric_i32", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x6A, name = "i32.add", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x6B, name = "i32.sub", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x6C, name = "i32.mul", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x6D, name = "i32.div_s", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x6E, name = "i32.div_u", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x6F, name = "i32.rem_s", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x70, name = "i32.rem_u", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x71, name = "i32.and", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x72, name = "i32.or", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x73, name = "i32.xor", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x74, name = "i32.shl", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x75, name = "i32.shr_s", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x76, name = "i32.shr_u", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x77, name = "i32.rotl", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x78, name = "i32.rotr", category = "numeric_i32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x42, name = "i64.const", category = "numeric_i64", immediates = listOf("i64"), stackPop = 0, stackPush = 1),
    OpcodeInfo(opcode = 0x50, name = "i64.eqz", category = "numeric_i64", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x51, name = "i64.eq", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x52, name = "i64.ne", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x53, name = "i64.lt_s", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x54, name = "i64.lt_u", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x55, name = "i64.gt_s", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x56, name = "i64.gt_u", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x57, name = "i64.le_s", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x58, name = "i64.le_u", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x59, name = "i64.ge_s", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x5A, name = "i64.ge_u", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x79, name = "i64.clz", category = "numeric_i64", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x7A, name = "i64.ctz", category = "numeric_i64", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x7B, name = "i64.popcnt", category = "numeric_i64", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x7C, name = "i64.add", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x7D, name = "i64.sub", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x7E, name = "i64.mul", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x7F, name = "i64.div_s", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x80, name = "i64.div_u", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x81, name = "i64.rem_s", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x82, name = "i64.rem_u", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x83, name = "i64.and", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x84, name = "i64.or", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x85, name = "i64.xor", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x86, name = "i64.shl", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x87, name = "i64.shr_s", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x88, name = "i64.shr_u", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x89, name = "i64.rotl", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x8A, name = "i64.rotr", category = "numeric_i64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x43, name = "f32.const", category = "numeric_f32", immediates = listOf("f32"), stackPop = 0, stackPush = 1),
    OpcodeInfo(opcode = 0x5B, name = "f32.eq", category = "numeric_f32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x5C, name = "f32.ne", category = "numeric_f32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x5D, name = "f32.lt", category = "numeric_f32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x5E, name = "f32.gt", category = "numeric_f32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x5F, name = "f32.le", category = "numeric_f32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x60, name = "f32.ge", category = "numeric_f32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x8B, name = "f32.abs", category = "numeric_f32", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x8C, name = "f32.neg", category = "numeric_f32", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x8D, name = "f32.ceil", category = "numeric_f32", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x8E, name = "f32.floor", category = "numeric_f32", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x8F, name = "f32.trunc", category = "numeric_f32", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x90, name = "f32.nearest", category = "numeric_f32", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x91, name = "f32.sqrt", category = "numeric_f32", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x92, name = "f32.add", category = "numeric_f32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x93, name = "f32.sub", category = "numeric_f32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x94, name = "f32.mul", category = "numeric_f32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x95, name = "f32.div", category = "numeric_f32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x96, name = "f32.min", category = "numeric_f32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x97, name = "f32.max", category = "numeric_f32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x98, name = "f32.copysign", category = "numeric_f32", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x44, name = "f64.const", category = "numeric_f64", immediates = listOf("f64"), stackPop = 0, stackPush = 1),
    OpcodeInfo(opcode = 0x61, name = "f64.eq", category = "numeric_f64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x62, name = "f64.ne", category = "numeric_f64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x63, name = "f64.lt", category = "numeric_f64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x64, name = "f64.gt", category = "numeric_f64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x65, name = "f64.le", category = "numeric_f64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x66, name = "f64.ge", category = "numeric_f64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0x99, name = "f64.abs", category = "numeric_f64", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x9A, name = "f64.neg", category = "numeric_f64", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x9B, name = "f64.ceil", category = "numeric_f64", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x9C, name = "f64.floor", category = "numeric_f64", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x9D, name = "f64.trunc", category = "numeric_f64", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x9E, name = "f64.nearest", category = "numeric_f64", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0x9F, name = "f64.sqrt", category = "numeric_f64", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xA0, name = "f64.add", category = "numeric_f64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0xA1, name = "f64.sub", category = "numeric_f64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0xA2, name = "f64.mul", category = "numeric_f64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0xA3, name = "f64.div", category = "numeric_f64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0xA4, name = "f64.min", category = "numeric_f64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0xA5, name = "f64.max", category = "numeric_f64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0xA6, name = "f64.copysign", category = "numeric_f64", immediates = emptyList(), stackPop = 2, stackPush = 1),
    OpcodeInfo(opcode = 0xA7, name = "i32.wrap_i64", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xA8, name = "i32.trunc_f32_s", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xA9, name = "i32.trunc_f32_u", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xAA, name = "i32.trunc_f64_s", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xAB, name = "i32.trunc_f64_u", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xAC, name = "i64.extend_i32_s", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xAD, name = "i64.extend_i32_u", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xAE, name = "i64.trunc_f32_s", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xAF, name = "i64.trunc_f32_u", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xB0, name = "i64.trunc_f64_s", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xB1, name = "i64.trunc_f64_u", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xB2, name = "f32.convert_i32_s", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xB3, name = "f32.convert_i32_u", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xB4, name = "f32.convert_i64_s", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xB5, name = "f32.convert_i64_u", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xB6, name = "f32.demote_f64", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xB7, name = "f64.convert_i32_s", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xB8, name = "f64.convert_i32_u", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xB9, name = "f64.convert_i64_s", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xBA, name = "f64.convert_i64_u", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xBB, name = "f64.promote_f32", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xBC, name = "i32.reinterpret_f32", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xBD, name = "i64.reinterpret_f64", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xBE, name = "f32.reinterpret_i32", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1),
    OpcodeInfo(opcode = 0xBF, name = "f64.reinterpret_i64", category = "conversion", immediates = emptyList(), stackPop = 1, stackPush = 1)
)

object WasmOpcodes {
    const val VERSION: String = "0.1.0"

    val OPCODES: Map<Int, OpcodeInfo> = RAW_OPCODES.associateBy { it.opcode }
    val OPCODES_BY_NAME: Map<String, OpcodeInfo> = RAW_OPCODES.associateBy { it.name }

    fun getOpcode(opcode: Int): OpcodeInfo? = OPCODES[opcode]

    fun getOpcodeByName(name: String): OpcodeInfo? = OPCODES_BY_NAME[name]
}
