//! Our reader, against files **Anki wrote**.
//!
//! Issue #13940: until now the one committed `.apkg` was generated by our own
//! test code. Real SQLite wrote the bytes, so the *file format* was genuinely
//! oracled — but the **Anki semantics were entirely our own understanding of
//! them**, and every import test validated our model against our model.
//!
//! That is the shape the zstd decoder failed in: its encoder and decoder agreed
//! perfectly while neither could read a real file. Two halves wrong in the same
//! way agree perfectly.
//!
//! Every fixture in `fixtures/anki/` was built and written by Anki's
//! own Rust backend (the `anki` PyPI package, version recorded in
//! `_manifest.json`) via `code/scripts/generate_anki_fixtures.py`. Nothing in
//! them came from this crate.
//!
//! ## What the corpus already corrected
//!
//! Writing it caught a wrong assumption before a line of test code existed:
//! answering **Good** on a new card does *not* graduate it. Anki leaves it in
//! learning — `type=1, queue=1`, with `due` a **timestamp**. Only `Easy`
//! graduates to review, where `due` becomes a **day number**. The fixture that
//! was going to be called "review-scheduled" would have contained a learning
//! card, and every assertion written against it would have encoded the wrong
//! meaning of `due` while passing.

use engram_anki_package::read_v11_collection;

const REVIEW: &[u8] = include_bytes!("fixtures/anki/anki-review-scheduled.apkg");
const LEARNING: &[u8] = include_bytes!("fixtures/anki/anki-in-learning.apkg");
const SUSPENDED_BURIED: &[u8] = include_bytes!("fixtures/anki/anki-suspended-buried.apkg");
const CLOZE: &[u8] = include_bytes!("fixtures/anki/anki-cloze.apkg");
const WITH_MEDIA: &[u8] = include_bytes!("fixtures/anki/anki-media.apkg");
const FILTERED: &[u8] = include_bytes!("fixtures/anki/anki-filtered-deck.apkg");

/// Every fixture parses at all.
///
/// Deliberately first and deliberately dull: before any question about what a
/// column *means*, the reader has to cope with a real Anki collection —
/// whatever note types, deck config and column defaults Anki chose to write,
/// none of which our own generator ever produced.
#[test]
fn every_anki_authored_fixture_parses() {
    for (name, bytes) in [
        ("review-scheduled", REVIEW),
        ("learning", LEARNING),
        ("suspended-buried", SUSPENDED_BURIED),
        ("cloze", CLOZE),
        ("with-media", WITH_MEDIA),
        ("filtered-deck", FILTERED),
    ] {
        let collection = read_v11_collection(bytes)
            .unwrap_or_else(|error| panic!("{name}: real Anki file failed to parse: {error:?}"));
        assert!(
            !collection.cards.is_empty(),
            "{name}: parsed but found no cards"
        );
        assert!(
            !collection.notes.is_empty(),
            "{name}: parsed but found no notes"
        );
    }
}

/// A review card, as Anki actually schedules one.
///
/// `type = 2`, `queue = 2`, and `due` is a **day number** counted from the
/// collection's creation day — not a timestamp. Getting that backwards makes
/// every review card's next-due date wrong by decades, in a way no
/// self-generated fixture would reveal.
#[test]
fn a_review_card_carries_the_values_anki_wrote() {
    let collection = read_v11_collection(REVIEW).expect("parse");
    assert_eq!(collection.cards.len(), 1);
    let card = &collection.cards[0];

    assert_eq!(card.kind, 2, "review card type");
    assert_eq!(card.queue, 2, "review card queue");
    assert!(
        card.interval > 0,
        "a graduated card has a real interval, got {}",
        card.interval
    );
    // 2500 is Anki's starting ease, expressed in permille.
    assert_eq!(card.factor, 2500, "starting ease factor");
    // The distinction the issue names: small day number, not a unix timestamp.
    assert!(
        card.due > 0 && card.due < 100_000,
        "review `due` should be a DAY NUMBER; {} looks like a timestamp",
        card.due
    );
}

/// A learning card, which encodes `due` completely differently.
///
/// Same column, different meaning, decided by `queue`. This pair of tests is
/// the whole argument for the corpus: a fixture we generated ourselves would
/// have used whichever interpretation we already believed.
#[test]
fn a_learning_card_uses_a_timestamp_where_a_review_card_uses_a_day() {
    let learning = read_v11_collection(LEARNING).expect("parse");
    let card = &learning.cards[0];

    assert_eq!(card.kind, 1, "learning card type");
    assert_eq!(card.queue, 1, "learning card queue");
    // Seconds since the epoch — vastly larger than any day number.
    assert!(
        card.due > 1_000_000_000,
        "learning `due` should be a TIMESTAMP, got {}",
        card.due
    );
    // `left` counts remaining steps. Anki writes a small count here; the older
    // packed-two-numbers encoding the issue mentions is not what 26.08 emits,
    // which is exactly the kind of thing only a real file can settle.
    assert!(
        card.left > 0,
        "a learning card has steps left, got {}",
        card.left
    );

    let review = read_v11_collection(REVIEW).expect("parse");
    assert!(
        review.cards[0].due < learning.cards[0].due,
        "the two encodings should not be confusable: review {} vs learning {}",
        review.cards[0].due,
        learning.cards[0].due
    );
}

/// Suspended and buried are negative `queue` values, and they are distinct.
///
/// Collapsing them loses the difference between "the user hid this until
/// tomorrow" and "the user took it out of rotation". Anki distinguishes -2
/// (buried as a sibling) from -3 (buried by hand) as well, so a reader that
/// tests `queue == -2` alone misses half the buried cards.
#[test]
fn suspended_and_buried_are_distinct_negative_queues() {
    let collection = read_v11_collection(SUSPENDED_BURIED).expect("parse");
    assert_eq!(collection.cards.len(), 2);

    let mut queues: Vec<i64> = collection.cards.iter().map(|card| card.queue).collect();
    queues.sort();
    assert_eq!(
        queues,
        vec![-2, -1],
        "expected one suspended (-1) and one buried (-2), got {queues:?}"
    );
    // Both are still NEW cards -- suspending does not change `type`, and a
    // reader that infers state from `type` alone would show them as due.
    for card in &collection.cards {
        assert_eq!(card.kind, 0, "suspend/bury must not alter card type");
    }
}

/// One cloze note produces one card per deletion.
///
/// The card count comes from Anki's own cloze expansion, so this checks our
/// note-type handling against a real `models` blob rather than one we wrote.
#[test]
fn a_cloze_note_expands_to_one_card_per_deletion() {
    let collection = read_v11_collection(CLOZE).expect("parse");
    assert_eq!(collection.notes.len(), 1, "one note");
    assert_eq!(
        collection.cards.len(),
        2,
        "two deletions should give two cards"
    );
    let note_type = collection
        .note_types
        .iter()
        .find(|nt| nt.id == collection.notes[0].note_type_id)
        .expect("the note's type should be present in the collection");
    assert!(
        note_type.name.to_lowercase().contains("cloze"),
        "expected a cloze note type, got {:?}",
        note_type.name
    );
}

/// A filtered deck moves the card and records where it came from.
///
/// `odid` is the original deck. A reader that ignores it puts the card back in
/// the filtered deck on export, which loses the user's real deck structure.
#[test]
fn a_filtered_deck_records_the_original_deck_in_odid() {
    let collection = read_v11_collection(FILTERED).expect("parse");
    assert_eq!(collection.cards.len(), 1);
    let card = &collection.cards[0];

    assert_ne!(
        card.original_deck_id, 0,
        "odid should name the deck the card came from"
    );
    assert_ne!(
        card.deck_id, card.original_deck_id,
        "the card should currently be in the filtered deck, not its origin"
    );
    // Both decks must be present, or an importer cannot restore the card.
    let ids: Vec<i64> = collection.decks.iter().map(|deck| deck.id).collect();
    assert!(
        ids.contains(&card.original_deck_id),
        "the original deck {} is missing from {ids:?}",
        card.original_deck_id
    );
}

/// The media map, as Anki writes it.
///
/// Anki stores media under numbered archive names with a JSON map from number
/// to filename. Ours is the only implementation that has ever produced the
/// fixtures this was tested against until now.
#[test]
fn media_is_readable_from_an_anki_written_package() {
    let files = engram_anki_package::read_media_files(WITH_MEDIA)
        .expect("real Anki media package should be readable");
    assert_eq!(files.len(), 2, "an image and an audio file were added");
    let mut names: Vec<&str> = files
        .iter()
        .filter_map(|file| file.filename.as_deref())
        .collect();
    names.sort();
    assert_eq!(names.len(), 2, "both members should resolve to real names");
    // Every member must carry real bytes. The archive members are NUMBERED
    // with a JSON map to filenames, so a wrong lookup yields the wrong bytes
    // for a name rather than an error -- silence is the failure mode.
    for file in &files {
        assert!(
            !file.data.is_empty(),
            "{:?} resolved to no bytes",
            file.filename
        );
    }
}
